* 健康饮食 by WHO
:PROPERTIES:
:CUSTOM_ID: 健康饮食-by-who
:END:
https://www.who.int/zh/news-room/fact-sheets/detail/healthy-diet

*** 成年人
:PROPERTIES:
:CUSTOM_ID: 成年人
:END:
健康饮食包括以下食物：

- 水果、蔬菜、豆类（例如滨豆和豆荚等）、坚果和全豆类（例如未加工的玉米、小米、燕麦、大麦、糙米）。

- 每天至少食用400克（即5种）水果和蔬菜(2)，不包括土豆、红薯、木薯和其它淀粉类根茎食物。

- 在摄入的总能量中，不到10%的能量来自游离糖 (2, 7)，这对于每天消耗约2000卡路里，体重正常的个人而言相当于50克（或大约12茶勺）。不过，在理想情况下应低于总能量摄入的5%，以获得更多健康益处(7)。游离糖是制造商、厨师或消费者添加到食品或饮料中的所有糖分，以及在蜂蜜、糖浆、果汁和浓缩果汁中天然存在的糖分。

- 脂肪摄入占总能量的30%以下(1, 2, 3)。不饱和脂肪（来自鱼、鳄梨、坚果、葵花油、黄豆、菜籽油和橄榄油等）优于饱和脂肪（来自肥肉、黄油、棕榈油和椰子油、奶油、奶酪、酥油和猪油等）和所有种类的反式脂肪，包括工业生产的反式脂肪（来自烘烤和油炸食品、预包装的零食和食品，如冷冻比萨饼、馅饼，曲奇饼、饼干、薄脆饼、食用油和涂抹食品的酱膏等）和哺乳动物反式脂肪（见于哺乳动物肉类和乳制品中，如牛、绵羊、山羊、骆驼等）。建议将饱和脂肪的摄入量减少到总能量摄入的10%以下，将反式脂肪降到总能量摄入的1%以下(5)。尤其是，工业生产的反式脂肪不属健康饮食之列，应避免食用(4, 6)。

- 每日食盐量低于5克（相当于大约一茶勺）(8)。食盐应得到碘化。

** 保持健康饮食的实际建议
:PROPERTIES:
:CUSTOM_ID: 保持健康饮食的实际建议
:END:
*** 水果和蔬菜
:PROPERTIES:
:CUSTOM_ID: 水果和蔬菜
:END:
每日至少食用400克或五份水果和蔬菜，会降低非传染性疾病发生风险(2)，并有助于确保每日充分摄入膳食纤维。

可用来增加水果和蔬菜摄入的方法有：

- 菜肴总是配有蔬菜；

- 将新鲜水果和生蔬菜作为零食食用；

- 食用时令新鲜水果和蔬菜；

- 食用各类水果和蔬菜。

*** 脂肪
:PROPERTIES:
:CUSTOM_ID: 脂肪
:END:
成年人将摄入的脂肪总量减至总能量的30%以下，会有助于防止体重过重(1, 2, 3)。还可以通过以下方式降低罹患非传染性疾病的风险：

- 将饱和脂肪摄入量减至总能量的10%以下；

- 将反式脂肪降至总能量摄入的1%以下；

- 用不饱和脂肪代替饱和脂肪和反式脂肪（2, 3），尤其要用多不饱和脂肪来代替。

可通过以下方式减少脂肪摄入量，特别是饱和脂肪和工业生产的反式脂肪摄入量：

- 做饭时采用蒸或煮的方式，而不是油炸方式；

- 用豆油、菜籽油、玉米油、红花油和葵花油等富含多不饱和脂肪的油类来代替奶油、猪油和酥油；

- 食用减脂乳制品和瘦肉，或去掉过肥的肉；

- 限制食用烘焙或油炸食品，以及含有工业生产的反式脂肪的预包装零食和食品（如甜甜圈、蛋糕、馅饼，曲奇饼、饼干和薄脆饼）。

*** 盐、钠和钾
:PROPERTIES:
:CUSTOM_ID: 盐钠和钾
:END:
大多数人通过食盐摄入过多的钠（相当于每日平均摄入9-12克盐），而钾的摄入量则不足（少于3.5克）。钠摄入量过高与钾摄入量不足会导致高血压，进而加剧心脏病和中风的发生风险(8, 11)。

将盐的摄入量降至每日低于5克的推荐用量，每年就可避免170万例死亡(12)。

人们往往不知道自己的食盐量。在许多国家，盐大多来自加工食品（如即食食品，腊肉、火腿、香肠等加工肉类，奶酪，咸味小吃等），或通常大量食用的食物（如面包）。人们还在烹饪（例如肉汤、固体汤料、酱油和鱼露等）或食用时（例如精盐）往食物中加盐。

可用来减少盐摄入的方法有：

- 在烹饪和加工食物时限制盐和高钠调料（如酱油、鱼露和肉汤等）用量；

- 不在饭桌上摆放盐或其他高钠调味品；

- 限制食用咸味零食；

- 选择钠含量较低的产品。

一些食品生产商正调整配方，以降低产品的钠含量。应该鼓励人们在购买或食用前检查营养标签，了解产品的钠含量。

钾可以减轻钠摄入量过高对血压的不良影响。食用新鲜水果和蔬菜可增加钾摄入量。

*** 糖
:PROPERTIES:
:CUSTOM_ID: 糖
:END:
无论是成人还是儿童，游离糖的摄入量应减至总能量摄入的10%以下(2, 7)。减到总能量摄入的5%以下会有更多健康益处(7)。

食用游离糖会加剧龋齿（蛀牙）的风险。从含有大量游离糖的食物和饮料中摄取多余热量还会导致体重不当增加，可能会导致超重和肥胖。近期证据还表明，游离糖会对血压和血脂造成影响，并提示降低游离糖的摄入可减少心血管疾病的危险因素(13)。

可用来减少糖摄入的方法有：

- 限制食用糖含量较高的食品和饮料，如含糖零食、糖果和含糖饮料（即各类含有游离糖的饮料------包括碳酸或非碳酸软饮料、水果或蔬菜汁和饮料、液体和粉末浓缩物、加味水、能量和运动饮料、即饮茶、即饮咖啡和加味乳饮料等）；

- 将新鲜水果和生蔬作为零食食用，而不是含糖零食。

** 如何促进健康饮食
:PROPERTIES:
:CUSTOM_ID: 如何促进健康饮食
:END:
饮食随时间而变，受到多个社会和经济因素的影响。这些因素在十分复杂的情况下发生交互作用，从而形成个体饮食模式。这些因素包括收入、食品价格（会影响到健康食物的可得性和可负担性）、个人喜好和信仰、文化传统以及地理和环境因素（包括气候变化）。因此，要促进形成健康食物环境（包括可促进多样化、平衡和健康膳食的食品系统），就要求多个部门和利益攸关方参与其中，包括政府和公共和私立部门。

政府可在创造健康食品环境方面发挥核心作用，使人们能够养成并保持健康的饮食习惯。决策者为创造健康食物环境而采取的有效行动包括以下内容：

- 通过以下方式使国家政策和投资计划保持协调，包括贸易、食品和农业政策，以促进健康饮食并保护公众健康；

- 进一步鼓励生产者和零售商种植、使用和销售新鲜水果和蔬菜；

- 不鼓励食品行业继续或者加大生产含有高浓度饱和脂肪、反式脂肪、游离糖和盐/钠的加工食品；

- 鼓励调整食品配方，减少饱和脂肪、反式脂肪、游离糖和盐/钠的含量，目标是消除工业生产的反式脂肪；

- 实施世卫组织关于向儿童推销食品和非酒精饮料问题的建议；

- 确保学前机构、学校、其它公共机构并在工作场所提供健康、有营养、安全和负担得起的食物，从而为促进健康饮食习惯建立标准；

- 探索用以促进健康饮食的监管和自愿性工具（如推销规制和营养标签政策）和经济鼓励或不鼓励做法（如税收、补贴）；

- 鼓励跨国、本国和当地食品服务机构和饮食网点提高其食品的营养质量，确保可供选择的健康食品的可得性和可负担性，检查份量和价格。

- 通过以下方式鼓励消费者提出健康食品和饭食要求：

- 增强消费者对健康饮食的意识；

- 制定学校政策和规划，鼓励儿童养成并保持健康饮食习惯；

- 向儿童、青少年和成年人讲解营养知识和健康饮食做法；

- 鼓励掌握烹饪技艺，包括在学校对儿童进行传授；

- 支持在销售点传播信息，包括（根据《食品法典委员会》的指南）印贴适当的营养标签，在包装正面加贴有助于消费者了解的说明性标签，确保提供关于食品成分的准确、规范化和通俗易懂的信息；

- 在初级卫生保健机构提供营养和饮食咨询。

- 促进婴幼儿适当喂养做法的方式有：

- 落实《国际母乳代用品销售守则》和世界卫生大会随后通过的相关决议；

- 实施相关政策和做法，促进对在职母亲的保护；

- 在卫生服务机构和社区中促进、保护和支持母乳喂养，包括落实爱婴医院行动。
