* How To Wake Up Not Tired
:PROPERTIES:
:CUSTOM_ID: how-to-wake-up-not-tired
:END:
https://youtu.be/SbUoLi34KHw

视频参考以下文章：

#+begin_src txt
https://blog.mindvalley.com/how-to-wake-up-early/
https://www.sleepfoundation.org/articles/what-circadian-rhythm
https://www.sharecare.com/health/sleep-basics/what-happens-wake-up
https://www.tuck.com/waking-up/
https://science.howstuffworks.com/life/inside-the-mind/human-brain/sleep2.htm
https://www.healthline.com/health/morning-fatigue-remedies#3
https://www.lifehack.org/404417/6-ways-to-wake-up-early-without-feeling-tired
https://www.redeemingproductivity.com/how-to-wake-up-early-and-not-feel-tired/
https://www.sciencedirect.com/science/article/abs/pii/S0272494409000838
http://colossalsleep.com/waking-up-tired/
#+end_src

起床后人体的一些变化：

- 心跳加快，呼吸变快
- 血液流速增快，大脑开始产生不同的脑波
- 肝脏与肾脏在夜间处于睡眠模式，但醒来后他们开始运作

夜间睡眠时，会有一个快速眼动周期（REM，repid eye movement）。大多数人一夜有五次REM。

一个成年人可能的最佳睡眠时长是7-9小时。

怎样做才能在起床以后感觉良好？

1. 睡前不吃东西，阻止血糖上升，便于入睡；
2. 睡前喝适量的水，床边放水，以便早起后及时补充水分；
3. 适量运动；
4. 不要被手机打扰；
5. 以90分钟为一个单位，制定睡眠计划；
6. 起床后做一些需要力量的拉伸动作，唤醒身体的各处肌肉；
7. 当环境允许的时候洗冷水澡，要用冷水洗脸；
8. 早起后，我是要吃早餐的，不要吃含糖的食物；
9. 早起后面对太阳站一会儿；
10. 写一些今日期待的东西：今天要解决什么样的难题，今天可以做什么让自己开心的事情；
11. 睡觉前洗澡；
12. 每天在同一时段醒来；
13. 睡前不应做让自己紧张的事情，睡前一小时做一些让自己放松的事情，读书或只是坐着不动；
14. 不要看手机，手机的光线不利于快速入睡；
15. 睡觉前去上个厕所；
16. 睡觉的地方不应该玩耍；
17. 睡前不喝酒，会让人打呼噜；
18. 睡前不吸烟，尼古丁会提高心率，影响睡眠；
19. 颜色影响睡眠质量，蓝色、黄色和绿色是好颜色，最糟糕的颜色是紫色和棕色。

#+begin_quote
The more you pay attention to your body and notice feelings of alertness and drowsiness, and the more time you spend developing good sleep hygiene habits, the better your slumber will be and the better you'll feel.

#+end_quote
