* 脚气的成因是什么，什么细菌产生了脚气的臭味
:PROPERTIES:
:CUSTOM_ID: 脚气的成因是什么什么细菌产生了脚气的臭味
:END:
脚气的成因是真菌感染足部皮肤，主要是一些毛癣菌属的真菌。脚气的臭味主要是由葡萄球菌等细菌产生的化学物质引起的。葡萄球菌通常生存在脚底，特别是脚前掌部位，而这些部位的葡萄球菌数量较多，因此这些部位的味道会更重一些。

** 脚气的症状和治疗方法
:PROPERTIES:
:CUSTOM_ID: 脚气的症状和治疗方法
:END:
脚气的症状包括脚趾间发痒的白斑、脚上出现红色片状斑块、脚上可能会流血的皮肤破裂、脚底或脚侧有充满液体的水泡[fn:1]。治疗脚气的方法包括保持双脚清洁、干燥，每天洗两次脚，用毛巾轻轻擦干脚趾间的水分，使用抗真菌产品，定期换袜子[fn:2][fn:3]。局部抗真菌治疗通常每天应用一次或两次，持续四个星期。局部抗真菌药物的例子包括唑类、烯丙胺类、环吡酮和布替萘芬。口服抗真菌药物包括氟康唑、伊曲康唑和特比萘芬[fn:4]。如果非处方药和自我护理未能使脚癣好转，应该使用处方药治疗[fn:5]。预防脚气的方法包括始终穿着拖鞋或凉鞋，避免赤脚进入公共淋浴间、游泳池、桑拿浴室和公共更衣室，游泳或沐浴后，一定要彻底擦干脚和脚趾间的缝隙，用肥皂彻底清洗双脚和脚趾间的缝隙，避免穿由不易干燥的材料（例如尼龙）制成的密闭鞋袜，感染应该用处方药治疗[fn:6]。

Citations:

** 脚气与脚气病的区别
:PROPERTIES:
:CUSTOM_ID: 脚气与脚气病的区别
:END:
脚气和脚气病实际上是两种不同的疾病。脚气，又称足癣，是一种由致病性真菌引起的足部皮肤病[fn:7][fn:8]。它的特点包括：

- 由红色毛癣菌等一系列皮肤癣菌的感染引起[fn:9]。
- 发病率非常高，全球发病人群达到10%以上[fn:10]。
- 脚部出汗比较多，空气流通比较差，导致局部环境潮湿温暖，形成了有利于丝状真菌繁殖的条件[fn:11]。

另一方面，脚气病是由维生素B缺乏引起的全身性疾病[fn:12]。这两种疾病的名称和治疗方法都很相似，但实际上它们是两种完全不同的病症。

Citations:

** 脚气可能导致疾病
:PROPERTIES:
:CUSTOM_ID: 脚气可能导致疾病
:END:
[[https://www.bbc.com/future/article/20150730-the-disgusting-secrets-of-smelly-feet]]

金黄色葡萄球菌的菌落生活在你的脚上--作为回报，它们会喷出令人厌恶的气味。

无论你多么爱干净，由于脚部的解剖结构，轻微的异味几乎是不可避免的。脚部每平方厘米平均有 600 个汗腺，比腋窝多出数百个。汗腺分泌的盐分、葡萄糖、维生素和氨基酸营养丰富，为细菌提供了完美的食物。作为免费午餐的回报，细菌为我们留下了脂肪酸鸡尾酒，这些物质共同形成了标志性的麝香。

例如，她发现疟疾寄生虫似乎会改变蚊子的嗅觉，使它们更喜欢脚上的气味，就像蜜蜂飞向花坛一样，蜂拥而至穿破的袜子。"有证据表明，蚊子头部的一些蛋白质发生了某种变化，它们在蚊子的嗅觉反应中发挥了作用。这是一种狡猾的机制，它引导疟疾宿主寻找潜在的受害者，以便在人体内继续其生命周期。"这也是蚊子成为疟疾传播媒介的原因。

[fn:1] [[https://www.thepaper.cn/newsDetail_forward_8522055]]

[fn:2] [[https://www.thepaper.cn/newsDetail_forward_8522055]]

[fn:3] [[https://www.163.com/news/article/G9FKTA7100019OH3.html]]

[fn:4] [[https://www.thepaper.cn/newsDetail_forward_8522055]]

[fn:5] [[https://www.163.com/news/article/G9FKTA7100019OH3.html]]

[fn:6] [[https://www.thepaper.cn/newsDetail_forward_8522055]]

[fn:7] [[https://www.thepaper.cn/newsDetail_forward_8522055]]

[fn:8] [[https://e.dxy.cn/wisdom/front/zhihuihao/698]]

[fn:9] [[https://www.163.com/dy/article/HGLD0ERU0534RNQB.html]]

[fn:10] [[https://www.163.com/dy/article/HGLD0ERU0534RNQB.html]]

[fn:11] [[https://www.163.com/news/article/G9FKTA7100019OH3.html]]

[fn:12] [[https://www.zhihu.com/question/36446285]]
