* running-and-heart-rate
:PROPERTIES:
:CUSTOM_ID: running-and-heart-rate
:END:
[折返点 2215 ｜跑步与心率]([[https://conge.github.io/2022/04/16/ReturnPoint-heart-rate/]])

跑步对全身的系统都是一个锻炼。

跑者的杰出表现，来自于强有力的心脏。心率是心脏健康的晴雨表。

1、跑者静息心率最低都是在 40，这正常吗？

提问：

> 我想咨询一下，我的静止心率最低都是在 40，这正常吗？

我的回复：

> 我的静止心率最低也是这个水平。 > > 我的医生担心我心动过缓，还给我做了心电图，让我拿结果去咨询心脏专科。我没去。 > > 跑步久了，心脏的泵血带氧功能强。身体从血液中获取氧气养分的效率高。自然，也不用跳太快，就能满足身体需求。 > > 你可以自检一下，平时是否有心动过缓的症状表现。或者有缺血的症状表现。没有，就不用担心。 > > 实在担心，就找个医生，看看，做做检查。

2、如何降低心率

我的回复：

> 如果你说的是保持速度的同时且让心率处于一个更低的水平，那么，你需要的就是：1. 真正的有氧运动 + 2. 时间。 > > 1: 真正的有氧运动 > > 保持速度并降低心率过程，实际是要提升自己的有氧能力。有氧能力，需要有氧运动。所谓的有氧运动，就是在有氧心率区间进行运动。有氧心率区间，在自己的最大心率的 60%～ 70%。最大运动心率的估算可以用公式，最简单的就是 220 - 年纪的。 > > 心率最好自己实际测一下。我的跑步周记里简单写过一个如何确定最大心率，你可以点击这里去看看. > > 确定自己的最大心率和有氧运动心率区间之后，你需要做的就是，每次运动都保持心率在那个区间。最好是区间的靠上的部分。 > > 至于运动方式，可以是跑步，也可以是骑行，游泳。运动方式多样一些，主要是避免方式太单一，造成某些身体部位总被用到而过劳。但如果休息的充分，只是持续一种运动也可以。 > > 2: 时间 > > 对心率的改变，是很难立竿见影的。身体随着锻炼强度的变化而对心率的调整，需要相当长的时间。三四个月若能看到些许变化，就算是速效了。注意循序渐进，把眼光放长远。因为在有氧区间跑步，往往比你想要的速度要慢不少，所以许多人都因为不能有”强风吹拂”的感觉，而不能坚持慢速。要认清自己的目的。 > > 当然，不是每次跑步都必须在这个区间内跑。但是要想降低心率，就得增加这种有氧运动的比例。心急吃不了热豆腐。

3、什么是真正的有氧运动

所谓的有氧运动，就是在有氧心率区间进行运动。有氧心率区间，在自己最大心率的 60%-70%。

最大心率计算：通常而言是 220-年龄，但是每个人的体质不同，这个公式并不适用于所有人。

按照公式计算，得出我的有氧心率区间：119-139。

--------------

参考资料

1. [折返点 2134 ｜跑步动力不足怎么半？]([[https://conge.github.io/2021/08/29/ReturnPoint-not-motivated/]])
2. [如何计算跑步时的最大心率 | Polar ﻿ 中国]([[https://www.polar.com/zh-hans/running-academy/calculate-maximum-heart-rate-running]])
