services:
  blog:
    image: tianheg/hugo
    container_name: blog_live
    restart: unless-stopped
    volumes:
      - ".:/src"
    ports:
      - 1314:1313
    environment:
      - HUGO_WATCH=true
      - HUGO_BASEURL=http://127.0.0.1
  node:
    image: "node:lts"
    user: "node"
    working_dir: /src
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/src
    command: "npm run all"
