baseURL = "https://tianheg.co/"
defaultContentLanguage = "zh"
hasCJKLanguage = true
pluralizeListTitles = false
summaryLength = 42
title = "YI-DA-JIA-BEI"

[permalinks]
tags = "/tags/:slug/"

[taxonomies]
tag = "tags"

[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]


[module]
    [module.hugoVersion]
        min = "0.128.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true
[build.buildStats]
    enable = true
[[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
[[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[markup]

[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = false

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
tabWidth = 2

[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 2

[author]
avatar = "/icons/apple-touch-icon.png"
email = "i@tianheg.co"
motto = "Knowing oneself, grasp the world"
name = "tianheg"
website = "https://tianheg.co/"

[related]
includeNewer = true
threshold = 80
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "date"
pattern = "2006"
weight = 90

[[related.indices]]
name = "fragmentrefs"
type = "fragments"
applyFilter = false
weight = 80

[outputFormats.SectionsRSS]
baseName = "index"
mediaType = "application/rss+xml"

[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "posts"

[outputs]
home = ["HTML", "SectionsRSS", "SearchIndex"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[services.rss]
limit = 10

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Now"
pageRef = "/now"
weight = 3

[[menu.main]]
name = "Read"
url = "https://read.tianheg.org"
weight = 4

[[menu.main]]
name = "Tech"
url = "/tags/tech/"
weight = 5

[[menu.main]]
name = "Service"
pageRef = "/service"
weight = 6

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 7

[[menu.main]]
identifier = "menu-time"
weight = 9

[params]
## theme
defaultTheme = "light"
enableDarkMode = true
hideThemeToggle = false
hideThemeToggleInHome = false
primaryColorDark = "201, 65%, 62%"
primaryColorLight = "220, 90%, 56%"
## PWA
themeColor = "#fff"
themeColorDark = "#16171d"
## meta data
jsonLD = true
openGraph = true
# footnote
footnoteReturnLinkIcon = "angle-up"
insertHrBySelf = true
squareBrackets = true
## para
backToTopIcon = "arrow-up"
### TODO
enableBackToTop = true
enableBackToTopAutoHide = true
enableDropCap = false
enableDropCapAfterHr = false
enableFooter = true
enableJustify = false
enableMinimalFooter = true
enableParagraphIndent = true
enablePostGitInfo = true
enablePostNav = true
enableRelatedPosts = true
enableSmallCaps = false
indentFirstParagraph = false
lineHeight = 2
paragraphStyle = "margin"
postNavInSection = true
relatedPostsIcon = "plus-circle"
relatedPostsNumber = 10
repoEditURL = "https://github.com/tianheg/blog/edit/main"
repoURL = "https://github.com/tianheg/blog"
# Code Blocks
enableCopy = true
enableCopyAutoHide = true
enableFingerprint = true
enableHighlight = true
enableOverflowY = false
enableSRI = true
# 404 page
fofPoster = "./images/flying-clouds-720p.jpg"
fofVideoMp4 = "/videos/flying-clouds-720p.mp4"
fofVideoWebm = "/videos/flying-clouds-720p.webm"
