baseURL = "https://tianheg.co/"
hasCJKLanguage = true
pluralizeListTitles = false
summaryLength = 42
title = "Tianhe Gao | 高天贺"

[permalinks]
tags = "/tags/:slug/"

[taxonomies]
tag = "tags"

[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[module]
[module.hugoVersion]
min = "0.128.0"
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[build.cachebusters]]
source = 'layouts/.*'
target = 'css'

[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"

[markup]
[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = false

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark  .parser.attribute]
block = false
title = false

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
tabWidth = 2

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[author]
avatar = "/icons/apple-touch-icon.png"
email = "i@tianheg.co"
motto = "Knowing oneself, grasp the world"
website = "https://tianheg.co/"

[related]
includeNewer = true
threshold = 80
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "date"
pattern = "2006"
weight = 90

[[related.indices]]
name = "fragmentrefs"
type = "fragments"
applyFilter = false
weight = 80

[outputFormats.SectionsRSS]
baseName = "index"
mediaType = "application/rss+xml"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "posts"

[outputs]
home = ["HTML", "SectionsRSS", "SearchIndex"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[services.rss]
limit = 10

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Now"
pageRef = "/now"
weight = 3

[[menu.main]]
name = "Read"
url = "https://read.tianheg.org"
weight = 4

[[menu.main]]
name = "Tech"
url = "/tags/tech/"
weight = 5

[[menu.main]]
name = "Service"
pageRef = "/service"
weight = 6

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 7

[params]
# footnote
squareBrackets = true
## para
backToTopIcon = "arrow-up"
### TODO
enableBackToTop = true
enableJustify = false
