[build]
publish = "public"
command = "bash scripts/build.sh"
functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.112.0"
  NODE_VERSION = "18"
  PAGEFIND_VERSION = "0.12.0"
  DART_SASS_VERSION = "1.62.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://a.tianheg.xyz/; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' https://a.tianheg.xyz/; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; require-trusted-types-for 'script';"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
