[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.77.0"

[[redirects]]
  from = "https://www.yidajiabei.xyz/tags/"
  to = "https://blog.yidajiabei.xyz/tags/"
  force = true
