[build]
publish = "public"
command = "bash scripts/build.sh"
functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.116.0"
  NODE_VERSION = "18"
  PAGEFIND_VERSION = "0.12.0"
  DART_SASS_VERSION = "1.63.4"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval'; object-src 'none'; base-uri 'none'; frame-ancestors 'none';"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
