[build]
publish = "public"
command = "bash scripts/build.sh"
functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.111.3"
  NODE_VERSION = "18"
  PAGEFIND_VERSION = "0.12.0"
  DART_SASS_VERSION = "1.62.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self' https://a.tianheg.xyz/"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
