[build]
publish = "public"
command = "bash scripts/build.sh"
functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.110.0"
  NODE_VERSION = "18.12.1"
  PAGEFIND_VERSION = "0.11.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
