[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.73.0"

[[redirects]]
  from = "https://www.yidajiabei.xyz/about/"
  to = "https://blog.yidajiabei.xyz/about/"

[[redirects]]
  from = "https://www.yidajiabei.xyz/tags/"
  to = "https://blog.yidajiabei.xyz/tags/"