[build]
publish = "public"
command = "bash scripts/build.sh"
functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.122.0"
  NODE_VERSION = "20"
  PAGEFIND_VERSION = "1.0.2"
  DART_SASS_VERSION = "1.67.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "object-src 'none'; base-uri 'none'; frame-ancestors 'none';"

[[headers]]
  for = "/*.(css|js|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
