* 避免被车撞

和所有突发事件一样，蓄意的车辆撞击行为难以预测和避免，但是和所有安全防护问题一样，多注意到一些细节，多具备一些基本的安防意识和知识，结果就有可能是生死之差。因为最近的一系列事件，我开始关注基于车辆碰撞的蓄意袭击行为，并对相关的个人安防策略一些研究总结，在此分享给所有人。

灾难在本质上是个人选择的急剧减少，在最极端情况下，连保有个人生命的选择都会受到威胁。所以如果在时间轴上看，灾难发生那一刻人的选择是最少的，而从灾难发生往回倒推，距离时间越远你拥有的选择越多。

所以安防意识就是在仍然拥有选择的时候，尽量选那些有利于人身安全，有助于避免灾难的选项。尽管灾难并不总会降临，但培养安防意识习惯可以让你在灾难真的降临之前多一些有利条件。这意味着你应该将安防的意识、策略和行为尽可能融入到日常生活里去。你不必杞人忧天，但也不能高枕无忧，在享受生活和敏锐警觉之间有一道微妙的动态边界。安防意识的建立就是找到属于你的那条边界。

** 预防措施

1. 环境敏感：要能灵活调整这个边界，一个首要问题就是明确具体场景。在经过某些特定环境和场景时，你需要一定程度上提高自己的警惕性，比如摘下耳机，避免一边走路一边用手机，把更多注意力放在环境观察上。

哪些环境有必要提高警惕呢？结合普遍经验来看，袭击通常发生在：

-  道路通畅地段：例如十字路口，体育场跑道等，给予了车辆充足的加速距离
-  行人密布区域：例如学校、夜市、公车站和商业区人行道
-  人车流弱区隔地段：也就是机动车道、非机动车道和人行道之间缺少隔离带、防护栏等设施

比如你路过一个临街公车站，而车站旁边一个学校正在放学，而道路没有隔离带，人行道马路牙子也很低，那么这样的场景从袭击者视角来看就是非常适合作案的地点，相应的，你也应该在路过此地时提高警惕性。

2. 在缺少硬性隔离带的地段，你需要注意到那些有可能避险的障碍物。如果一条道路上其中一侧的非机动车道是机动车停车带，那么你应该尽量走这一侧，因为停留车辆可以成为避险障碍物。

3. 如果你不得不在某些风险区域停留，比如等红灯，等车，蹲下来系鞋带等，那么尽量选择站在灯柱、石墩、隔离桩或者停在街边的车辆等硬物背后。

4. 过马路不检查左右来车以及一边看手机一边过街都应该被视为威胁生命的恶习！！！

5. 如果你可以选择的话，尽量走迎着车流的那一侧，也就是双行道的左侧。这可以增加你提前注意到异常和躲避的反应时间。

6. 在人流车流较大，安全风险增加的区域，摘下耳机，暂停音乐，或者选择耳机通透模式。在听到刹车声、引擎轰鸣声或撞击声等异响的时候第一时间识别声音来源

7. 注意警惕异常的驾驶员行为，例如开窗咒骂、连续按喇叭，强行抢道加塞或者其他类似的路怒行为

8. 如果不得不在机动车道上行走，让并肩行走的老人、儿童或行动不便者走在较为靠近人行道的那一侧，这样遇到危险你可以第一时间将他们推离机动车道。

** 遇袭处理

9.  如果遭遇车辆迎面袭来，不要背对车辆奔跑，更不要停在原地不动，应该立刻朝左右两侧奔跑。如果可能的话，朝着来袭车辆前轮的斜后方奔跑，因为纯左右奔跑车辆依然用可能通过转向来追踪你。只要你的身位在车辆前轮后面了，车辆就不再具有威胁。

10. 在来不及奔跑的情况下，向两侧纵身飞扑，不要害怕摔伤，因为摔伤比撞伤更安全。站在原地最容易被车辆碾压，也是最致命的情况。

11. 遭遇袭击后，应该尽快转移到室内，或者立刻寻找附近有灯柱、隔离桩或停留车辆的背后，并且在安全的情况下尽快远离袭击区域，避免围观事故现场。因为后续有可能发生车辆燃爆、司机下车后进一步施暴等行为

12. 遇到蓄意撞人，在躲避后摔倒，或者不幸被撞倒在地以后，在有移动能力的情况下应该尽量起身转移到安全地带，以避免袭击车辆通过快速倒车来进行二次碾压。实际上在所有交通事故发生后，行人在有移动能力的情况下都应该尽量转移到安全地带，避免其他路过车辆的碾压风险。是否一直躺在地上和交通事故鉴定没有关联。

13. 在袭击发生以后，先不要着急冲上去帮助伤者，应该观察肇事车辆的后续行为，包括是否有其他车辆进行二次袭击。如果车辆失去移动能力，离开了肇事区域而且现场没有火灾、爆炸和其他风险后再去帮忙。

14. 在拨打120急救电话的时候，应该言简意赅地告知事故地点和受伤人数。这些会直接决定120调派救护车的时机和数量。其次，如果有评估能力，也可以告知伤者伤情，其中最危重的情况例如昏迷、大出血、呼吸困难等情况会帮助医护人员初步判断抢救优先级。沟通中保持简洁清晰，减少冗余信息，也不要有催促指责和情绪发作。拨打电话后请继续保持电话畅通，便于救援人员和你进一步联络。

15. 如果不具备医疗急救常识，无法评估伤者情况，请勿随意搬动伤者，因为如果他们的头部或脊柱受到了损伤，移动会导致进一步的伤害。如果因为危险不得不移动伤者，在移动过程中尽量稳定他们头、脖子和背部。

16. 如果有显著的出血，请使用尽量干净的毛巾、布料、衣物等覆盖伤口，向下施加一定压力。如果是四肢出血，可以将出血处抬高以减少出血量。

17. 如果伤者依然有心跳和呼吸，请不要做人工呼吸和胸腔按压。失去意识的伤者在平躺情况下有可能会被自己的舌头或者喉咙肿的血液呛到，从而难以呼吸。如果出现了这样的情况，可以小心地将其旋转为侧卧。

18. 人在受伤后会产生生理和心理上的应激状态，出现抽搐、呼吸急促、发冷、焦虑恐慌的反应。在确保安全的情况下，你可以让伤者平躺，覆盖衣物保持体温，同时进行言语上的安抚鼓励，询问伤者是否需要帮忙联系家人或者有其他重要需求。

19. 作为目击者，在面对鲜血、创伤等画面时自己也有可能出现应激反应，导致呼吸急促，恐慌等反应。请量力而行，如果自身状态无法保持一定的专注和冷静，请通过深呼吸调节应激反应。

20. 如果自己是受害者，只要你仍然有意识且没有明显的大出血或其他危及生命的情况，就有理由保持乐观。尽量调节自己的呼吸和情绪状态，如果担心自己的性命，在有能力的情况下，可以试着联系家人，或者通过语音备忘录来留下重要的信息。

以及，看完这些建议之后你或许也意识到了接受一定的急救技能训练是非常有必要的，否则的话在施救和自救过程中会有很多错误操作。所以你可以专门花些时间寻找相关培训课程，具备一些上手操作的经验。

最后，希望每个人都永远用不到这些知识，但也希望你能直面对危险的探讨与研究，因为这才是维护安全最有效的选择。还是那句话，意外无法被预测，但是安防意识和习惯可以减少伤害，带来生死之差。
