* 买笔记本

** 需求分析

随着AI的发展，以前自己觉得不需要一台高性能笔记本，不需要有独立显卡——现在不买，什么时候现在的笔记本用坏了，什么时候买。为此我给旧笔记本做了清洁，买了致态的1T SATA固态硬盘。但是，为了未来的个人职业发展考虑，我需要一台高性能笔记本来拓宽我的技能树（主要是硬件领域）。旧笔记本用起来已经比较卡了，日常写文章没问题，浏览器窗口打开多就卡了。

AI从ChatGPT发布以来，已经有了长足的发展。不论是出于职业考虑还是个人兴趣，都需要掌握从原理到应用的全流程。

所以，一台高性能笔记本就显得至关重要。这关系着我未来五年的职业发展。我需要不断push自己学习新东西，掌握新能力，构建自己的职业护城河，使得自己不会被轻易替代。


** 我用过的笔记本

| 购买于     | 生产年份 | 品牌型号                  | CPU                              | GPU                                                | LinuxHardware probe                          |
|------------+----------+---------------------------+----------------------------------+----------------------------------------------------+----------------------------------------------|
| 2019/01/01 |     2018 | [[https://h10032.www1.hp.com/ctg/Manual/c06146792.pdf][HP Laptop 14s-cr0xxx(PDF)]] | Intel Core i5-8250U CPU @1.60GHz | Intel UHD Graphics 620 + AMD Radeon R5 M445 Series | https://linux-hardware.org/?probe=f95d67a702 |

** 评估指标

一、CPU

AMD

#+BEGIN_EXPORT html
<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr>
      <th>年份</th>
      <th>CPU架构</th>
      <th>工艺制程</th>
      <th>核心代号</th>
      <th>U / HS / H / HX 系列型号 (移动端)</th>
      <th>市场定位 / 备注说明</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2022</td>
      <td>Zen 3+ (全大核)</td>
      <td>TSMC 6nm FinFET</td>
      <td>Rembrandt</td>
      <td>
        Ryzen 5 6***H/HS<br />
        Ryzen 7 6***H/HS<br />
        Ryzen 9 6***H/HS
      </td>
      <td>锐龙6000系列 · 全大核设计 · DDR5/LPDDR5 · RDNA2核显</td>
    </tr>
    <tr>
      <td>2023</td>
      <td>Zen 3+ (全大核)<br />〝马甲版〞</td>
      <td>TSMC 6nm FinFET</td>
      <td>Rembrandt-R (Refresh)</td>
      <td>
        Ryzen 5 7*35H/HS<br />
        Ryzen 7 7*35H/HS<br />
        Ryzen 9 7*35H/HS
      </td>
      <td>伪·锐龙7000 · 锐龙6000马甲 · 全大核设计 · 仅命名升级</td>
    </tr>
    <tr>
      <td>2023</td>
      <td>Zen 4 (全大核)</td>
      <td>TSMC 4nm FinFET</td>
      <td>Phoenix</td>
      <td>
        Ryzen 5 7*4*H/HS<br />
        Ryzen 7 7*4*H/HS<br />
        Ryzen 9 7*4*H/HS
      </td>
      <td>真·锐龙7000 · 全大核设计 · 一代神U · RDNA3核显 · 集成AI引擎</td>
    </tr>
    <tr>
      <td>2023/2024</td>
      <td>Zen 4 (全大核)</td>
      <td>TSMC 5nm FinFET</td>
      <td>Dragon Range</td>
      <td>
        Ryzen 5 7***HX<br />
        Ryzen 7 7***HX<br />
        Ryzen 9 7***HX<br />
        Ryzen 9 7***HX3D
      </td>
      <td>锐龙7000 · 积热</td>
    </tr>

    <tr>
      <td>2024</td>
      <td>Zen 4 (全大核)</td>
      <td>TSMC 4nm FinFET</td>
      <td>Hawk Point</td>
      <td>
        Ryzen 5 8***H/HS<br />
        Ryzen 7 8***H/HS<br />
        Ryzen 9 8***H/HS
      </td>
      <td>伪·锐龙8000 · 锐龙7000马甲风格 · 全大核设计 · 能效小幅优化</td>
    </tr>
    <tr>
      <td>2025</td>
      <td>Zen 4</td>
      <td>TSMC 4nm FinFET</td>
      <td>Hawk Point</td>
      <td>
        Ryzen 5 2**H / Ryzen 7 2**H<br />
        Ryzen 5 H 2** / Ryzen 7 H 2**
      </td>
      <td>锐龙7000二次马甲 · 全大核设计</td>
    </tr>
    <tr>
      <td>2025</td>
      <td>Zen 5</td>
      <td>TSMC 5nm FinFET</td>
      <td>Krackan Point</td>
      <td>
        Ryzen AI 5 3*0<br />
        Ryzen AI 7 3*0<br />
        Ryzen AI 5 H 3*0<br />
        Ryzen AI 7 H 3*0
      </td>
      <td>CPU规格缩水 · iGPU规格缩水 · 鸡肋NPU规格增加 · 大小核设计</td>
    </tr>
    <tr>
      <td>2025</td>
      <td>Zen 5</td>
      <td>TSMC 4nm FinFET</td>
      <td>Strix Point</td>
      <td>
        Ryzen AI 9 H 3**<br />
        Ryzen AI 9 HX 3**
      </td>
      <td>CPU规格增加 · iGPU规格增加 · 鸡肋NPU规格增加 · 大小核设计</td>
    </tr>
    <tr>
      <td>2025</td>
      <td>Zen 4 (全大核)</td>
      <td>TSMC 5nm FinFET</td>
      <td>Dragon Range</td>
      <td>
        Ryzen 7 8***HX<br />
        Ryzen 9 8***HX
      </td>
      <td>伪·锐龙8000 · 锐龙7000马甲 · 积热</td>
    </tr>
    <tr>
      <td>2025</td>
      <td>Zen 5</td>
      <td>TSMC 4nm FinFET</td>
      <td>Fire Range</td>
      <td>
        Ryzen 9 9***HX<br />
        Ryzen 9 9***HX3D
      </td>
      <td>锐龙9000</td>
    </tr>
    <tr>
      <td>2026</td>
      <td>Zen 3+ (全大核)</td>
      <td>TSMC 6nm FinFET</td>
      <td>Rembrandt</td>
      <td>
        Ryzen 3 1*0<br />
        Ryzen 5 1*0<br />
        Ryzen 7 1*0
      </td>
      <td>锐龙6000二次马甲 · 全大核设计</td>
    </tr>
    <tr>
      <td>2026</td>
      <td>Zen 5 (全大核优化)</td>
      <td>TSMC 4nm FinFET</td>
      <td>Gorgon Point</td>
      <td>
        Ryzen AI 5 4*0 / Ryzen AI 7 4*0 [Krackan Point马甲]<br />
        Ryzen AI 9 HX 4*0 / Ryzen AI 9 4*5 [Strix Point马甲]
      </td>
      <td>NPU提升 · 强化AI吞吐 · 主流AI笔记本</td>
    </tr>
  </tbody>
</table>
#+END_EXPORT

二、GPU

RTX5060

三、内存

32G

四、硬盘

1T

最好的固态盘：PCIe 4.0 + M.2 2280 + TLC

固态硬盘有哪些颗粒类型？哪种最好？

综合性能与寿命：SLC>MLC>TLC>QLC。主流是TLC。

- CPU、GPU、内存、显示屏大小、硬盘、摄像头、NIC、电池、接口、键盘、电源适配器

** 买电脑后

1. 不激活，确保笔记本无明显问题：屏幕问题、风扇异常、散热不行
2. 要先更新Windows，确保所有的firmware都更新了
3. 烤机，保证笔记本性能

** 参考资料

- [[https://www.kdocs.cn/l/chzEHrH90jRz][笔记本购机指南]] by 夏蒙乾
- [[https://blog.huan99.com/post/20250215172536/][笔记本电脑开箱验货烤机流程 | Huan's Blog]]
- [[https://blog.huan99.com/post/20250217000458/][机械革命翼龙15Pro配置信息一览及简单优化 | Huan's Blog]]
- [[https://wiki.archlinux.org/title/Laptop][Laptop - ArchWiki]]
- [[https://linux-hardware.org/][Linux Hardware Database]]
- 图吧工具箱 https://www.tbtool.cn/
- CPU对比
  - https://www.cpubenchmark.net/singleCompare.php
