* how-i-regained-concentration-and-focus
:PROPERTIES:
:CUSTOM_ID: how-i-regained-concentration-and-focus
:END:
[[https://www.innoq.com/en/blog/wie-ich-meine-konzentration-wiederfand/]]

如何摆脱注意力不集中的问题？

> 新闻（消息）之于大脑，就如同糖之于身体。 > > ------Rolf Dobelli (Author, Entrepreneur)

作者是如何克服这一情况的？

因为一本书和一篇博客，作者开始改变旧有的生活习惯。只用了两种他就能完成更多事情，睡眠也变好了，明显更快乐了。简而言之，少看新闻，更有生产力地使用智能手机。

​## 我如何失去了自己的注意力

> 只有想法是不够的，还要能实现它，并且用他人理解的方式写下来。

作者尝试了「早起」和「夜晚工作」，但收效甚微。

最后，作者采用了自己作为 IT 顾问总结的方法，成功了！方法是：

> A systematic analysis of the situation, a self-review.

​### 自我分析

注意力分散在多个事情上。

​### 自我发现

大脑是无法处理多个上下文的相互切换的。

作者尝试过番茄钟、纯音乐，都失败了。

但有一次，偶然的闲暇让作者读了一本书------[《停止阅读新闻消息（Stop Reading The News）》]([[https://www.dobelli.com/en/books/]])。

作者还推荐了一篇文章------[《为生产力和停止分心而配置 iPhone 手机》]([[https://betterhumans.pub/how-to-set-up-your-iphone-for-productivity-focus-and-your-own-longevity-bb27a68cc3d8]])。

​### 很激进，但是有效果

1. 停止阅读任何新闻
2. 重新为了生产力而使用手机、减少干扰
3. 重新配置电脑

​### 零新闻

规定了早晨不能看手机，晚上八点以后也不能看。

​### 重新配置手机

1. 关闭几乎所有通知
2. 尽可能隐藏所有社交媒体
3. 打开勿扰模式（每天夜间开启）
4. 消息应用放在一起
5. 开启屏幕使用时间统计
6. 开启内容和App使用限制
7. 使用黑色壁纸

​### 重新配置电脑

​### 以防旧瘾复发

​### 更进一步

--------------

作者从别人那里得到 [[https://unhook.app/]] （Remove YouTube Recommended Videos）
