* imitate-then-innovate
:PROPERTIES:
:CUSTOM_ID: imitate-then-innovate
:END:
[[https://perell.com/essay/imitate-then-innovate/]]

「模仿，并创新」是我的座右铭，它帮助我提高所要学习的任何技能。

这是反常识的，但当我们模仿他人越多，我们就越快发现自己的独特风格。在娱乐界，有一大批喜剧演员努力地模仿别人，失败了，然后变得比以前更好：Johnny Carson 想要模仿 Jack Benny，但失败了，赢得了六个 Emmy 奖。还有，David Letterman 想模仿 Johnny Carson，但失败了，成为美国最伟大的电视节目主持人之一。

在反思自己的影响时，Conan O'Brien 说道："正是我们的失败让我们感知到自己的理想，让它不断地定义自己，让我们独一无二。（正是我们未能成为我们理想中的自己，最终定义了我们，并使我们独一无二）"

但是，现在的创造者在做相反的事情。他们拒绝模仿他人，固执地坚持原创，他们把这视为最高价值------即使以牺牲作品质量为代价。当你和他们谈论时，他们会否认自己对于原创的雄心，但他们在行动中把这种意图表达出来。总的来说，创造者花更少的时间模仿他们的偶像，花更多的时间试图创造新事物。我称这种情况为「原创疾病」------一种普遍灾难，它让创造者对于模仿他人的风格感到恐惧。

这种问题在写作者中间可能最严重，他们谈及自己的职业时常带有不同程度的神秘感，而这种神秘感是为神秘的人准备的（写作者不需要保持神秘）。不过，写作者们最好还是向他人学习。

​## Quentin Tarantino

之所以想到好莱坞导演，是因为他们被视为创造性专业精神的核心。当人们注视 Quentin Tarantino，他们看到的是一个有着制作原创电影天赋的疯狂创意家。但 Tarantino 的原创性起始于模仿。他因复制并基于来自其他电影的场景进行构建而闻名，并且他曾经说道："我从每一部电影偷东西。"

看着 Tarantino 的作品，我陶醉于这样的悖论：模仿和创新并非对立，而是相辅相成的。

我不了解你，但我是那种”坐下来，拿些爆米花，然后享受电影”的人。电影对我来说是纯粹的娱乐。一个逃离现实世界责任并进入一种有着迷人故事的恍惚感的机会。我认为每个人都是如此，直到我看到一部电影，导演做的事情和我想象的完全相反。那个导演专注于全部的细节，从配乐增强电影的情感之路的程度，到灯光如何在演员脸上移动，再到摄影机的移动能够预示故事情节该向哪个方向发展。

听到他反思自己的电影，我不得不问他："我们看的是同一部电影吗？"我感觉自己困在二维世界，而他住在四维时空。
