#+TITLE: Life Philosophy
:PROPERTIES:
:CUSTOM_ID: life-philosophy
:END:

** Think Like Munger, Do Like Musk
:PROPERTIES:
:CUSTOM_ID: think-like-munger-do-like-musk
:END:

[[https://www.ruanyifeng.com/blog/2022/03/weekly-issue-200.html]]

低期望是芒格的幸福秘诀。

> 马斯克其实同意芒格，也认为不宜对这个项目有期待。但是，他的过人之处就在于，他认定汽油车会被淘汰，电动车是未来的趋势，值得冒险。也就是说，马斯克是从科学和个人理想的角度，看待这个项目。
> 
> 这两种立场并不矛盾，可以结合在一起。我们应该做一个积极行动的悲观主义者，对未来低期望，但只要是值得的，就坚定去做。当一个有前途的新项目出现在你面前时，不妨认定它很难成功，但是如果你相信这个项目，即便赚不到钱你也想做，那么无论如此，你要去试一下。

> 我觉得，这就是当代的写照。这是一个科技高速发展的时代，但是普通人无法参与，只是时代的旁观者。
> 
> 就是因为这个原因，你不得不对发生在你身上的事情抱有低期望，不能盲目乐观自己会有好运。普通人很难遇到好运，反而任何一个小意外，就足以把你难倒。但是你不能放弃，必须多尝试，多去做，尽量参与，这样才可能会有改变。

** Free to Choose
:PROPERTIES:
:CUSTOM_ID: free-to-choose
:END:

[[https://mp.weixin.qq.com/s/41VkepLdDcimQRL3BbhvQg]]

选择的自由，前提是认知——知道世界上的路，除了眼前这条，还有很多可能。自由地选择，要做到不设限。

自由的另一面是要有勇气面对不确定性，承担选择的后果。

> 有那么多人在生活中随波逐流，却不去寻找机会，即使他们内心深处知道自己真正想做什么。不要成为那种人。生命太短暂了。
> 
> I am also continually amazed at the number of people who coast through life and don't go and seek out opportunities even when they know in their gut what they'd really like to do. Don't be one of those people. Life is way too short.
> 
> -- Marc Andreessen

** Feynman and His Student
:PROPERTIES:
:CUSTOM_ID: feynman-and-his-student
:END:

来自【产品沉思录 Product Thinking】Vol.20220417：加速奔跑并不能形成优势，不要对自己默默无闻

一个问题有没有价值并不在于问题本身的大小，而是看我能否真正解决它，或有助于解决它。这样，我的辛苦便有真正的贡献，不是白费的。

> 在科学界，只要是出现在我们面前而还没有解决的问题，我们却有办法向答案推进一点，这就是伟大的问题。我倒是想建议你，先找一些更简单的，或者如你说的，更卑微的问题，让你可以轻易解决掉。不管问题多么平凡都没关系，你会尝到成功的喜悦。而且要经常协助同事，就算回答那些能力不如你的人所提的问题，都是值得做的，都会累积自己的成就感。不要因为"什么问题没意思、什么问题才有价值"这种错误想法，而一直闷闷不乐，剥夺了自己对成功的喜悦。
> 
> 不要对自己保持无名状态——这是一种太悲伤的方式。
> 
> 知道自己在这个世上的定位，努力扮演好自己的角色。
> 
> 了解自己在世界上的位置，公正地评价自己。

** The Devaluation of Language
:PROPERTIES:
:CUSTOM_ID: the-devaluation-of-language
:END:

Here are some reading materials:

*** [[https://www.ted.com/talks/john_mcwhorter_txtng_is_killing_language_jk][Txtng is killing language. JK!!!]]
:PROPERTIES:
:CUSTOM_ID: txtng-is-killing-language-jk
:END:

In the past, people spoke as if they were writing formally; now, people write as if they are speaking.

** Don't Bother Others
:PROPERTIES:
:CUSTOM_ID: donot-bother
:END:

尊重别人正在做的事，不过多干涉。

不打扰是最大的温柔，不打扰别人正在进行的谈话，不打扰别人正在做的事情。不打扰是一种自律，是一种处事方式。

我好为人师（贬义）。
