* Protecting Yourself Against Unexpected Violence
:PROPERTIES:
:CUSTOM_ID: protecting-yourself-against-unexpected-violence
:END:
https://www.artofmanliness.com/skills/outdoor-survival/podcast-960-a-guide-to-protecting-yourself-against-unexpected-violence/

#+begin_quote
I was a wrestler, was division one wrestler. I felt like I had a certain level of competence and grasp on the subject of how to protect myself. But what the hard reality was that the first realization was that it was not my body that had failed me. It was my mind, my ability to think and make decisions and that all of the physicality was irrelevant. I was bigger, stronger, faster, younger than the guy that I was dealing with. I was in great shape, all that stuff.

#+end_quote

#+begin_quote
And this is why at the core of everything, when we start to look at how the brain actually operates under stress and what are the forces in place that make it very difficult to think and make good decisions when we are under stress. And at the end of the day, what it really comes down to, Brett, is experience.

#+end_quote

#+begin_quote
"Oh, you gotta really be a skilled martial artist to be able to defend yourself." But the reality is that's just the gateway. The real dynamic is being able to think and make decisions, which means you don't allow your brain or you've overridden this process that causes paralysis or panic in a situation.

#+end_quote

#+begin_quote
And we don't know where this is going to go, how it's going to go, what's going to be involved and neither does the bad guy. So the concept is if we're competing and we have those controls and expectations in place, it's very easy to kind of manage this on a more competitive level. And the stress we feel is more what I consider to be performance anxiety.

#+end_quote

#+begin_quote
So if we're talking about the easy stuff, if you're walking down the street and you see someone and you instantly get a bad vibe, this is kind of the Gavin de Becker approach of the intuition type of dynamic, is intuitively we have the ability to read a lot of information, and we'll very often get a gut reaction of fear

#+end_quote

#+begin_quote
You have to have a decision-making process to say, "Where am I safe most of the time functionally? Where can I relax? And where do I need to have my awareness turned on and switched on a little bit more?"

#+end_quote

#+begin_quote
He does a great job talking about how to develop situational awareness. And what it all comes down to is just any situation you're in, you gotta establish what the baselines are, like, what's normal, and then look for anomalies.

#+end_quote

#+begin_quote
*the best way to defend yourself is just to not put yourself in a situation where you have to defend yourself. And if you are in a situation where you have to defend yourself, your first recourse should just be get out of the situation, do things to deter violence.*

#+end_quote
