* 你可能无法从同人小说和/或色情小说中学到的性知识：
:PROPERTIES:
:CUSTOM_ID: 你可能无法从同人小说和或色情小说中学到的性知识
:END:
https://delphinidin4.tumblr.com/post/752140659697270784

色情小说和色情片是非常有趣的！但如果你没有通过其他渠道获得足够的性教育（比如全面的性教育和可信赖的成年人开诚布公的交流等），转向同人文和色情片来了解性爱可能会有很多盲点，还会让你有一些不现实的期望... 虽然这些情色作品没啥问题，但它们剧情是虚构的，往往忽略了真正性中更多现实和人性化的部分------它们的主要目的不是教育。以下是一些你应该知道但很多同人文和色情片常常忽略的性知识：

❶ 性爱并不总是激情四射或甜蜜恩爱。有时它很搞笑，有时很平淡，你们只是满足一下彼此性需求而已。这也没什么问题。（有时候你们可能在做爱时讨论漫画，而你的伴侣在努力让你高潮时你却因为《蜘蛛侠》漫画很生气。） ❷ 两人很难同时达到高潮。虽然这是个美好的想法，但实际上很难协调，如果你们把全部精力都放在同时高潮上，可能无法尽情享受。 ❸ 身体会发出奇怪的声音。啪啪声、拍打声、空气溢出的声音、不性感的声音。这些都很正常，可以笑出来。 ❹ 在啪啪过程中笑是可以的。 ❺ 有时候会放屁。有时在对方为你口交时放屁会很尴尬，但这并不是大不了的事。尴尬的身体现象是正常的。走后庭时，有时候会拉出点便便。你会习惯的。

❻ 有时候性体验会很糟糕。这并不意味着这是强暴或创伤------有时候是双方自愿的但结果不如预期。如果你和伴侣是长期的伴侣，不妨和TA谈谈，找出问题所在，讨论你喜欢和不喜欢的地方，沟通什么姿势技术适合你们。不要害怕在不喜欢的性爱过程中停下来，提供指导让对方也能让你享受。（提示：自慰是了解自己性偏好的好方法。） ❼ 你不会喜欢每一个性爱动作。不是每个人都能从每一个动作中获得愉悦。你可能觉得走后庭对你没感觉，可能觉得G点刺激让你很紧张不舒服，担心会尿出来。你可能不喜欢口交或接受口交。如果你不喜欢每个色情明星或同人文主角都能从中获得强烈高潮的东西，并不代表你有问题。每个人的神经末梢分布在不同的地方------真的是不同的喜好。 ❽ 并非所有高潮都是强烈的。有时候只是感觉温暖和舒适，这也已经很棒了。 ❾ 如果你对某个性爱动作无感，而你的伴侣非常喜欢，你可以为TA忍耐一下，TA也会为你做你喜欢的事情。但要和对方沟通好喜好！要知道，当你的伴侣做你喜欢而他们不太喜欢的事情时，这是关心你感受的表现，反之亦然。 ❿ 疯狂激情性爱后立即抱在一起睡觉看似浪漫，但干涸的体液早上会很难清理。性后你们双方都应该（无论男女）小便，清理尿道中的细菌和杂质，减少尿路感染的风险。

⓫ 在床上铺毛巾有助于避免睡在湿漉漉的床单上。（如果你或你的伴侣有月经，这也非常有用。） ⓬ 很多人不喜欢脏话或粗暴的性爱。一定要先询问对方。（同人文在展示沟通方面比色情片做得更好，但很多还是存在虚构成分。） ⓭ 保护措施非常重要。使用避孕套、牙科护膜等不仅能防止怀孕，还能降低性传播感染的风险。（是的，即使是同性别的伴侣，也需要注意性传播感染。） ⓮ 润滑剂很重要，但周围随机出现的粘稠物不是好的润滑剂。尤其是随便什么润滑油类，因为油不容易被冲洗干净，可能会在体内滞留细菌------油基润滑剂也会破坏避孕套。使用专为私密部位设计的润滑剂。水基和硅基润滑剂让性生活更愉快！ ⓯ 尺寸不一定越大越好。许多女生的阴道不喜欢被巨大的阴茎不停撞击宫颈。有些人在被身体或玩具插入时喜欢大尺寸，有些则不喜欢。

⓰ 身体有毛发。生殖器有毛发。有时你可能会在牙齿上发现一根阴毛。如果你的伴侣比色情片里看到的毛发多得多，这很正常。 ⓱ 并不是每个人都喜欢精液的味道。有时它很难吃（味道因人而异，取决于饮食习惯，但有时你就是不喜欢。就像有些人讨厌花生酱一样。每个人的口味不同）。可以不吞咽，或者要求有阴茎的伴侣在射精前提醒你，以免射在你嘴里（事实上，提醒是礼貌的表现）。 ⓲ 如果你要在淋浴时进行性爱，买一个防滑垫。否则，湿漉漉且裸体地叫救护车会很尴尬，因为你在淋浴时滑倒弄伤了自己，而你的伴侣也在试图做爱时撞到头。 ⓳ 在性爱时大声呻吟和尖叫很有趣，但会让隔壁的邻居讨厌你。要根据环境做出选择。

https://delphinidin4.tumblr.com/post/752140659697270784
