#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 听从你心，无问西东

#+begin_quote
  如果提前了解了你们要面对的人生，不知你们是否还会有勇气前来

  看见的和听到的，经常会令人们沮丧

  世俗是这样的强大

  强大到生不出改变他们的念头来

  可是如果有机会能够提前了解你们的人生

  知道青春也不过只有这些日子

  不知你们是否在意那些世俗希望你们在意的事情

  比如占有多少才更荣耀，拥有什么才能被爱

  等你们长大，你们会因为绿芽冒出土地而喜悦

  会对初升的朝阳欢呼跳跃

  也会给别人善意和温暖

  但是却会在赞美别的生命的同时

  常常

  甚至永远地忘了自己的珍贵

  愿你在被打击时，记起你的珍贵，

  抵抗恶意

  愿你在迷茫时，坚信你的珍贵

  爱你所爱，行你所行，听从你心，无问西东

  ------语自《无问西东》
#+end_quote

--------------

#+begin_quote
  你的物理学是不列

  而英文学国文学

  都是满分

  如此天资

  当初你为什么不学文科

  而偏要念实科呢（A）

  因为最好的学生都读实科（B）

  你求学的目的是什么啊（A）

  我只知道

  不管我将来做什么

  在这个年纪读书 学习 都是对的

  我何用管我学什么

  每天把自己交给书本

  就有种踏实（B）

  但是

  你还忽略了一件事情------真实（A）

  真实（B）

  人把自己置身于忙碌当中

  有一种麻木的踏实

  但丧失了真实

  你的青春也不过只有这些日子（A）

  什么是真实（B）

  你看到什么

  听到什么

  做什么

  和谁在一起

  有一种从心灵深处满溢出来的不懊悔也不羞耻的平和与喜悦（A）

  A------梅贻琦，B------吴岭澜，语自《无问西东》
#+end_quote

我一直想培养自己演讲的能力。因为我觉得演讲能力很重要。昨天是第二次在大家面前进行演讲。第一次距离时间太长，我都快忘了。我感觉自己好像比第一次还要紧张。

但是我能够比较完整地把自己的观点表达出来，我觉得这就是一种进步。挺为自己高兴的。跟发言的其他同学相比，还有很多不足。这说明我还有很大的进步空间，所以我很期待自己以后的表现。

--------------

《无问西东》在我看来它就是一部经典大片。四个时代，四个不同的故事，由人物联系贯穿在一起。刚看第一遍的时候还有些看不明白，看第二遍的时候就有一种恍然大悟的感觉。看到疑惑揭晓之处，才突然对情节有一个较为清晰的把握。

吴岭澜受梅贻琦影响走文科道路，在西南联大吴岭澜告诉沈光耀要追求自我，沈光耀救了陈鹏等孤儿使得陈鹏能够继续他的故事，陈鹏带王敏佳远走，告诉李想“逝者已矣，生者如斯”，李想才会在救了张果果的父母之后说了那句“逝者已矣，生者如斯”，所以才有了张果果的现代故事。

这个电影，讨论了我们人生中最重要的三个问题。第一个是 *尊重内心选择，还是随波逐流* 。第二个是 *听从父母教诲，还是遵从内心选择* 。第三个是 *自我意识的觉醒* 。

--------------

一个人在这个世界上安身立命，他想干什么，他能干什么，他会干什么，这是他的个人价值。

一个人最初有“我”这个概念应该是在很小的时候。那个时候还并不知道“我”跟他人有什么不同。只知道“我”的需要即是第一需要，他人的需要都不重要。

随着年龄见长，我们逐渐懂得了：*我是重要的，他人也是重要的*。于是就有了理解尊重。有了理解尊重这些道德规范的约束，这个社会才会平稳地运行下去。

但是在运行的过程中，我们好像又迷失了自我。

因为随着社会的发展，经济不断发展。物质生活极大丰富，精神追求与物质追求脱节。

年轻人处在社会发展的前沿，他们能够接触到更多更新的经济发展所带来的红利，所以他们更容易迷失自我。因为可以接受的东西太多了，你想得到什么就能够得到什么。

于是，在物欲横流中，我们就渐渐地找不到自我，我们被眼前的一切蒙蔽了，忘却了即将到来的危机。所以每天追小说，每天打游戏成为一种常态，这就是绝大多数年轻人的生活状态。

这样生活不好吗？我这么问你能给出标准答案吗？但是这样的生活真的好吗？我这么问你同样也给不出答案。

--------------

我可以不带任何偏见地去这样讲： *一个人的眼界取决于他过去的经历以及他当下的生活。*

如果他真的有更高水平的追求，那么他就不该沉溺于当下的暂时的娱乐生活中。他也很清楚，自己想要什么，自己的追求是什么，而不是每天在无意义的事情上浪费时间。

---

曾经听到一句话： *所幸人生无意义，才容得下各自赋予的意义* 。你给生活什么样的定义，生活就会给你什么样的反馈。那么在你眼中生活是什么样子？

生活可以是早晨初升的太阳，可以是傍晚优雅的晚霞，可以是湖边青蛙的鸣叫，也可以是天边白云的闲游。

生活可以是每天在固定的时间上课，在固定的时间读书，在固定的时间聊天。在固定的时间游戏。

生活可以是每天追小说，每天打游戏，每天和朋友聊天，每天和朋友去压马路。

生活可以是一个星期有 6 天都在熬夜。熬夜做实验，熬夜查文献，和不同领域的精英交谈，与他们进行思想的交锋。

这些都是生活。生活还有成百上千种样子。你的生活又是什么样的呢？

所以不要再抱怨了，好吗？你也许会抱怨自己在一所二本院校里有一身鸿鹄之志而无处伸展。你也许会抱怨，身边没有志同道合的朋友，让你倍感孤独。你也许会抱怨，为什么会有那么多的不公，都落到你的身上。

但是你除了抱怨，还剩下什么呢？你的生活就只有抱怨了吗？随便抱怨一下，眼前的困境就能够改变。那么那些努力拼搏的人，他们岂不是亏大了。

所以不要总是去抱怨。抱怨学校不好，抱怨没有人陪你，抱怨自己深受诸多偏见。

你的抱怨是那么无力，那么勉强，那么可笑。

人的一生中有几个青春能够任我们挥霍，我们的青春也不过只有这些日子，我们能够用他们来做什么呢？你想好了吗？
