#+TITLE: Home

#+BEGIN_EXPORT html
<p class="">Hi, I'm tianheg. I write this blog in both Chinese and English <br> to share my life
  experiences.</p>
<p class="">I hope you enjoy reading it!</p>
<p class="text-lg">我想找个女朋友。如果你感兴趣，可以读下<a href="/posts/want-to-be-in-a-relationship/">这篇文章</a>。</p>

<hr>

<div class="italic">
<p class="">The Explorer</p>

<p class="">Knowing oneself, grasp the world</p>

<p class="">Dedicated to the present self</p>
</div>

<hr>

<ul>
  <li>Spend less than you earn</li>
  <li>Avoid toxic people and toxic activities in both work and life</li>
  <li>Try and keep learning all your life</li>
  <li>Learn fast</li>
  <li>Do a lot of deferred gratification because you prefer life that way</li>
</ul>

<h2>1. ME IN 10 SECONDS</h2>

<ul>
  <li>born on June 28, 2000</li>
  <li>a man who is straight</li>
  <li>always trying to understand myself and connecting with people</li>
</ul>


<h2>2. ME IN 10 MINUTES</h2>

<p>
  See <a href="/about">my "About" page</a>.
</p>


<h2>3. Search this site</h2>

<p>
  Go to <a href="/search">the search page</a> to use to search for any word or phrase.
</p>


<h2>4. Some links</h2>

<ul>
  <li><a href="/links">Blogroll</a></li>
  <li><a href="/support">Support me & I support people</a></li>
  <li><a href="/uses">Uses</a></li>
  <li><a href="/img">Photos I shot & Images I like from internet</a></li>
</ul>


<h2>5. Leave a comment & RSS</h2>

<p>
  Email <code class="select-all">i@tianheg.co</code>
</p>

<p>
  RSS: <a href="https://tianheg.co/index.xml">https://tianheg.co/index.xml</a> or on <a href="https://app.folo.is/share/feeds/56264968416220160">Folo</a>
</p>


<hr>

<footer id="footer" class="text-center">
2018 – now &nbsp; by &nbsp; tianheg
</footer>
#+END_EXPORT
