#+TITLE: More About

I was first a person, then a person who wanted to know myself, and finally a person who was curious about technology (science and craft).

Grand narratives cannot tell the daily life of my life, and little words can eventually flow into a trickle in your heart and mine.

Other than that, the biggest interest lies in books and audio-visuals:

Reading mostly for seeking self, communicating with seniors, learning experience. Reading categories and intermittent, more humanities and social sciences, more programming books, more classic novels.

Movie watching is mostly for enriching the sensory experience and appreciating the visual beauty. Regardless of the limitations of movie watching, classic masterpieces and children's animations are also watched; the former is mostly for appreciation and the latter is mostly for relaxation. Both are beneficial.

Music is mostly soothing and relaxing, occasionally savoring the masterpieces. When it comes to music, the only thing that moves my heart is the best, regardless of style or category.

I intend to live, write and record until I'm old. Therefore, my writings record everything, hardships and joys, and what is in my heart, whether it is light or dark.

Kind reminder:

My articles are useful to me, when you read them do not follow them lightly, after all everyone is unique and imitating others will not get you out of your own way in the end.

I will also post content that has not been verified. Because there are times when ignorance leads me to new knowledge.

My beliefs in life:

1, Create different life experiences

- 2022 - 2032: In this decade, figuring out your own taste in technology
- 2024.07.10 - ?: In Shenzhen Peisheng Electronic Ltd., test BMS circuit boards
- 2023.6.12 - 2024.04.30: Worked as a map editor for an outsourcing company in Fuyang hometown, helping mainstream mapping apps to update the road network status
- 2023.3.2 - forever: Join the Kaiyuanshe China open source community as a volunteer and no longer actively contribute as of August 2023. Became an official member on January 28, 2024; on July 7, took over as the deputy head of the infrastructure team and the secretary of the project committee
- 2022.9.26 - 2023.3.27, ELM, delivery, half a year
- 2021: In the first semester of my senior year, I worked as a cashier at "Teppanyaki Cuisine" on the third floor of the school's Longyuan Cafeteria
- 2020.10: Worked as a food handler for a few days during the National Day at a restaurant near the school, "Small Pot Rice"
- 2019 - 2021: Worked with my father doing interior decorating (scraping and sandpapering) while on summer and winter breaks from college
- 2018: 10 days working at a cell phone screen manufacturing plant during the summer after high school graduation

2, Don't have a separate mind

- Each person is a separate and rich individual, and you can't make a judgment about a person's character based on just one or two sentences.
- Right now I'm separatist, and I'm going to work on weakening that mindset.

3, Love for parents

- Call home often (can't do it often)
