#+TITLE: About

#+BEGIN_QUOTE
- Spend less than you earn
- Avoid toxic people and toxic activities in both work and life
- Try and keep learning all your life
- Learn fast
- Do a lot of deferred gratification because you prefer life that way
#+END_QUOTE

我先是一个人，然后是一个想认识自己的人，最后是一个对科技（科学与技艺）好奇的人。

I was first a person, then a person who wanted to know myself, and finally a person who was curious about technology (science and craft).

#+BEGIN_QUOTE
宏大的叙事无法讲述我的生活日常，点滴话语终能汇成涓涓细流，在你我的心间流淌。

Grand narratives cannot tell the daily life of my life, and little words can eventually flow into a trickle in your heart and mine.
#+END_QUOTE

除此之外，最大的兴趣在于书影音：

读书多为寻求自我，与前辈交流，学习经验。读书品类多且断续，多人文社科，多编程书籍，多经典小说。

观影多为丰富感官体验，欣赏视觉之美。观影不论限制，经典佳作看，儿童动画亦看，前者多为欣赏，后者多为放松。皆有益处。

音乐多为舒缓放松，间或品味大师雅作。谈及音乐，唯动我心者最佳，不论风格品类。

我是打算活到老，写到老，记录到老的。所以，我的文章什么都记录，困苦有、快乐也有，内心所想，无论光明或黑暗，皆有。

善意提醒：

我的文章对我是有用处的，当你读的时候切勿轻易效仿，毕竟每个人都是独一无二的，模仿别人终究无法走出自己的路来。

未经考证的内容，我也会发布。因为有些时候，无知能让我获得新知。

Other than that, the biggest interest lies in books and audio-visuals:

Reading mostly for seeking self, communicating with seniors, learning experience. Reading categories and intermittent, more humanities and social sciences, more programming books, more classic novels.

Movie watching is mostly for enriching the sensory experience and appreciating the visual beauty. Regardless of the limitations of movie watching, classic masterpieces and children's animations are also watched; the former is mostly for appreciation and the latter is mostly for relaxation. Both are beneficial.

Music is mostly soothing and relaxing, occasionally savoring the masterpieces. When it comes to music, the only thing that moves my heart is the best, regardless of style or category.

I intend to live, write and record until I'm old. Therefore, my writings record everything, hardships and joys, and what is in my heart, whether it is light or dark.

Kind reminder:

My articles are useful to me, when you read them do not follow them lightly, after all everyone is unique and imitating others will not get you out of your own way in the end.

I will also post content that has not been verified. Because there are times when ignorance leads me to new knowledge.

-----

- [[/links][Blogroll]]
- [[/search][Search]]
- [[/support][Support me & I support people]]
- [[/uses][Uses]]

-----

*我的人生信念* ：

1, 创造不同的人生体验

- 2022 - 2032：在这十年，摸索自己的技术品味
- 2023.6.12 - 2024.04.30：在阜阳老家的一家外包公司，做地图编辑，帮助主流地图应用更新路网状态
- 2023.3.2 - forever：以志愿者的身份加入[[https://github.com/kaiyuanshe][开源社]]，从2023年8月开始，不再积极贡献。于2024年1月28日成为正式成员
- 2022.9.26 - 2023.3.27，饿了么，送外卖，半年时间
- 2021：在大四上学期，学校龙源食堂三楼-「铁板烧料理」，做收银员
- 2020.10：在国庆期间，学校附近饭店「小锅饭」，做几天传菜员
- 2019 - 2021：在大学放寒暑假时，跟着父亲做室内装修（刮大白、打砂纸）
- 2018：在高中毕业的暑假时，手机屏幕制造厂，工作10天

2, 不该有分别心

- 每个人都是独立的丰富的个体，不能仅凭一两句话就对一个人的品性下定论。
- 现在的我是有分别心的，我要努力削弱这种心态。

3, 爱父母

  - 常打电话给家里（现在还做不到）

*我是一个怎样的人* ：

1. 安静：喜欢安静，不喜欢吵闹
2. 随和：不容易拒绝别人，在某些情况下先想到别人的感受。如果某件事不重要但是要做，随大流是个好选择
3. 自私：我永远也无法忘记，曾经的我因为和妹妹争夺手机，而一气之下把手机摔碎的行为。当时我想，不让我玩你也别想玩。现在想来，惭愧不已
4. 愚笨：学习东西很慢，领会别人意思很慢
5. 孤僻：我一个人过得挺好，排斥别人进入我的私人空间，使用我的物品
6. 好奇：对一些事物有一定的好奇
7. 记性时好时坏：别人对我好不一定记很久，别人对我不好，即使事情很细微，也能记很久
8. 尽量不麻烦别人：能够自己完成的时候，绝不会请别人帮忙
9. 在一群有陌生人的会议里，我会紧张得说不出话
10. 打有起伏的呼噜
11. 还不知道如果恰当地表达自己的想法

My beliefs in life:

1, Create different life experiences

- 2022 - 2032: In this decade, figuring out your own taste in technology
- 2023.6.12 - 2024.04.30: Worked as a map editor for an outsourcing company in Fuyang hometown, helping mainstream mapping apps to update the road network status
- 2023.3.2 - forever: Join the Kaiyuanshe China open source community as a volunteer and no longer actively contribute as of August 2023. Became an official member on January 28, 2024
- 2022.9.26 - 2023.3.27, ELM, delivery, half a year
- 2021: In the first semester of my senior year, I worked as a cashier at "Teppanyaki Cuisine" on the third floor of the school's Longyuan Cafeteria
- 2020.10: Worked as a food handler for a few days during the National Day at a restaurant near the school, "Small Pot Rice"
- 2019 - 2021: Worked with my father doing interior decorating (scraping and sandpapering) while on summer and winter breaks from college
- 2018: 10 days working at a cell phone screen manufacturing plant during the summer after high school graduation

2, Don't have a separate mind

- Each person is a separate and rich individual, and you can't make a judgment about a person's character based on just one or two sentences.
- Right now I'm separatist, and I'm going to work on weakening that mindset.

3, Love for parents

- Call home often (can't do it now)

What kind of person am I:

1. Quiet: likes to be quiet, doesn't like noise
2. Easy-going: not easily rejected by others, think of others' feelings first in certain situations. If something is not important but needs to be done, going with the flow is a good choice
3. Selfishness: I can never forget the act of shattering my cell phone in a fit of rage because I was once fighting with my sister over it. At the time, I thought, "Don't let me play with it and you won't play with it either". Now I think about it and am ashamed
4. Stupid: slow to learn things, slow to understand what others mean
5. Isolation: I'm doing fine on my own, excluding people from my personal space and using my belongings
6. Curiosity: a certain curiosity about something
7. Memory is sometimes good and sometimes bad: I don't always remember for a long time when people are nice to me, but I can remember for a long time when people are not nice to me, even if it's a very small thing
8. Try not to bother others: never ask for help when you can do it yourself
9. In a meeting with a bunch of strangers, I'd be too nervous to speak
10. Snore
11. I don't know how to express myself properly

-----

** Leave a comment & RSS

Way 1: Email =i@tianheg.co=

Way 2: [[/msg][Online Form]]

RSS: [[https://tianheg.co/index.xml]]
