#+TITLE: ChangeLog

博客相关的注意事项：

1. 技术类文章、时效性强的文章，会随时间推移、我理解程度的加深，而改变文章链接，或者与其他文章合并，简化。如果你发现我的文章链接 404 了，最好在我博客上找找。我选择不做重定向，因为维护重定向列表不是一件能坚持很久的事。我的博客的此时此刻，代表了我此时的状态，博客内容的改变反映了我状态的改变。
2. 开始了强烈整理博客内容的欲望。
3. 我博客上的内容，不会是静态不变的，它永远在变化，永远反映我的思维方式的改变、我的情绪的变化。它是活的，是我旺盛生命力的代表。没有它，我只是一个人，有了它，我能冲破现实的枷锁，和无尽的想象力相伴，让自己不断探索生命的奥义。
4. 有时候一图胜万语，但我的博客不需要。

博客内容结构备忘：

1. 所有技术向内容都在「技术」标签下
2. 看的部分，有「电影」、「动漫」、「剧集」、「音乐剧」、「纪录片」标签
3. 听的部分，有「音乐」标签
4. 读的部分（阅读技术向的书籍只加 /阅读/ 标签，无需 /技术/ 标签），有「阅读」标签
6. 和创作相关的标签（诗作中有些来自别处），有「随笔」、「诗作」、「梦境」、「年终总结」
7. 生活方面，有「食」、「备忘」、「健康」、「摄影」、「父母」
8. 来自别处的，有「他山之石」、「艺术」、「古文」
9. 记录博客的变化或者对于博客等写作理念的思考，有「博客」

#+BEGIN_EXPORT html
<details>
  <summary><span>博客改变记录</span></summary>
  <p>2024-02-14 把单个页面的书影音数据导入NeoDB neodb.social</p>
  <p>2023-09-24 【现在】页的更新，通过 <a href="https://github.com/usememos/memos" target="_blank">Memos</a> API 实现，公开 Memo 作为自己现在在做什么的状态更新（已弃用）</p>
  <p>2023-09-22 使用域名邮箱作为永久联系邮箱，之后可通过Cloudflare Email Routing配置邮件转发</p>
  <p>2023-09-03 移除文章中使用的所有图片，博客将只使用文字表达</p>
  <p>2023-07-26 改变博客域名为 <code>tianheg.co</code>，原域名 <code>tianheg.xyz</code></p>
  <p>2023-04-29 把 shortcodes 的样式放到了各自的 shortcode 文件中，减小总体 CSS 大小</p>
  <p>2023-02-04 文章列表样式修改</p>
  <p>2022-11-15 将所有他处的笔记移动到博客中，下一步计划——合并同类文章，删除无价值文章，简化标签分类</p>
  <p>2022-10-22 在每页加上“编辑”链接，方便修改</p>
  <p>2022-10-12 改变博客域名为 <code>tianheg.xyz</code>，原域名
    <code>www.yidajiabei.xyz</code></p>
  <p>2022-10-10 弃用 <a href="https://github.com/kaushalmodi/ox-hugo" target="_blank">ox-hugo</a>，使用 *.org 格式文件写作，直接在
    <code>content/posts</code> 文件夹下新建</p>
  <p>2022-02-09 借助 ox-hugo 重回 Hugo 怀抱</p>
  <p>2022-02-06 借助 highlight.js 为代码添加高亮</p>
  <p>2021-11-19 使用 <a href="https://github.com/dirtysalt/dirtysalt.github.io" target="_blank">Emacs Org-mode</a></p>
  <p>2021-09-23 使用 <a href="https://github.com/tianheg/hugo-theme-tianheg" target="_blank">Tianheg</a> 主题，已合并到 blog 仓库
  </p>
  <p>2021-09-07 使用 <a href="https://giscus.app/" target="_blank">https://giscus.app/</a> 评论</p>
  <p>2021-07-31 让博客的导航栏固定在窗口的边缘</p>
  <p>2021-07-21 开启 Service Worker</p>
  <p>2021-07-02 这里主要是随时学习的记录，生活感想，对于外语电影，首选外语作为文章标题，中文放在文中</p>
  <p>2021-06-29 把「自我」中的内容再次放到博客里</p>
  <p>2021-05-26 把 blog 的主题改成技术，以前是生活技术。生活部分的文章放到自我站点（已弃用）中（已全部移入 blog）</p>
  <p>2021-01-26 可以使用 <code>[post-title](/posts/post-file-name/)</code> 和 <code>[tag-name](/tags/tag-name/)</code>
    相互引用文章，文章中的“他”，不单指男性，还有女性，在写作中，作者退居二线，多以「你」称呼</p>
</details>
#+END_EXPORT
