#+TITLE: What am I doing now?
#+DESCRIPTION: My goals for this period of time

#+BEGIN_QUOTE
I've learned that the most important thing is: "Learn from day to day". Only goals are not enough.

However, asking myself to improve daily is a bit unrealistic and overly stressful for the pace of my life right now.

So, lengthen the cycle to something every week instead.

Three strikes and you're out
#+END_QUOTE

-----

- Learn interdisciplinary thinking from Charlie Munger

-----

Reference: [[https://nownownow.com/about][/now]]

#+BEGIN_QUOTE
  So a website with a link that says “now” goes to a page that tells you
  what this person is focused on at this point in their life. For short,
  we call it a “now page”.

  It's useful for the same reason an “about” page is useful on your
  site: because people on your site want to know more about you.

  Besides answering the common question, “What are you up to these
  days?”, those who have a now page say it's a good reminder of their
  priorities. By publicly showing what you are focused on now, it helps
  you say no to other requests.
#+END_QUOTE
