#+TITLE: 咨询服务 Consulting services

根据目前我掌握的知识领域，我可以提供以下内容的答疑解惑：

- 书写文字的心得体会
- Arch Linux 安装与基本软件（桌面环境）配置（[[/tags/arch-linux][Arch Linux 相关文章]]）
- 如何构建像我这种风格的个人网站
- Web 开发的学习收获

Based on the knowledge I currently possess, I can provide clarification and answers to the following topics:

- Experience and Insights on Writing
- Arch Linux Installation and Basic Software (Desktop Environment) Configuration ([[/tags/arch-linux][Arch Linux Related Articles]])
- How to build a personal website like mine in this style
- Learning gains from web development

这是我初次尝试将自己的知识经验，以有偿方式进行分享。

This is my first attempt to share my knowledge and experience in a paid manner.

定价

¥50 / 50 分钟 ¥50 / 50 minutes

付款方式见[[/support][这里（【支持】页）]]，付款后可以点击[[https://cal.com/tianheg/50m][这里（【cal.com】）]]预约我的时间。

Payment methods can be found [[/support][here]] ([Support] page). After making the payment, you can click [[https://cal.com/tianheg/50m][here]] ([cal.com]) to schedule an appointment with me.
#+BEGIN_EXPORT html
<!--
参考了

- https://dingyu.me/service
- https://amazt.netlify.app/people/geekdada/
- https://lutaonan.com/consulting/

二维码的背景图片出处

https://unsplash.com/photos/a-painting-of-a-body-of-water-surrounded-by-trees-AckZaYtIq3I

-->
#+END_EXPORT
