#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 关于好文章

我现在突然明白------我需要一个地方来存储我所认为的「好文章」，值得反复阅读的，也就是《[[/posts/how-to-read-a-book/][如何阅读一本书]]》中提及的“第
3 层的书”。不过，最先被发现的是“第 2
层的书”。因为我们总是先知道文章或书的内容，才决定是否要再次阅读。

那么，我需要为这些文章新建一个 repository 吗？我曾经通过 Git
仓库积累有价值的文章，不过没有持续太久，因为我不知道这些文章存在的意义。我真的会反复阅读这些文章吗？

另外，「分类」也是一个问题。我找不到一个彻底完美的分类方案，囊括我所遇到的好文章。一切都是在积累过程中，不管修改，不断添加。我明白这一过程必不可少。

** 什么是好文章
   :PROPERTIES:
   :CUSTOM_ID: 什么是好文章
   :END:
它是我们看不懂的东西吗？显然不是，因为我们看不懂，所以它好不好我们不知道。所以，好文章的前提是*看得懂*。但是，什么程度才算是看得懂？这个没有统一的标准，对我来说，我通读完一遍觉得收获很大，这就算是*看得懂*。

一篇好文章首先得是“第 2
层的书”，然后才决定是否要反复阅读，放入好文章里。

"第 3
层的书"一般是很少的，但它们也是最有价值的。如果你遇到这样的书，一定要珍惜。

我有一种心理------害怕自己遇见的有价值的东西会消失、有趣的文章会不见，然后就会想保留一个备份，结果就是备份是保存了，那些有价值的东西却没有被我吸收。我为什么会这样做？究其原因，可能是我还没有明确自己如何处理遇到的有价值的东西。只有被我理解并运用的东西才是真正对我有价值的，而不是保存在那里就完事儿了。

** 好文章该怎么分类
   :PROPERTIES:
   :CUSTOM_ID: 好文章该怎么分类
   :END:
分类的两个问题：语言和领域。

- 语言：汉语和英语，其他语言我还没有想法去学习。
- 领域：主攻的技术（编程），人文，社科（历史、心理学、社会心理学、哲学）

** 好文章的收集规则
   :PROPERTIES:
   :CUSTOM_ID: 好文章的收集规则
   :END:
好文章有很多，要选择真正有价值的文章。但是，真正有价值的文章需要时间的检验。而且真正有价值的文章往往会有很多备份。所以，不用担心找不到原文。所以，全文收集就显得不那么必要了。

- 只保存出处
- 进行分类

--------------

*参考资料*：

1. [[https://program-think.blogspot.com/2013/09/knowledge-structure.html][如何完善自己的知识结构]]
