#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 看海的人

#+begin_quote
  我啊，不太喜欢历史。

  你看，以前人做过什么，知道了又能怎么样？

  但是呢，我想，再有趣点是不是更好呀。

  历史当中全都是奇妙的故事，不是吗？
#+end_quote

的确，历史中有很多有趣的故事。观察自己的历史是件有趣的事情，可以看到自己的初心、看到自己的雏形、看到自己
比现在稚嫩的一面。

#+begin_quote
  人类无法正确、完整地理解历史。
#+end_quote

因为历史由胜利者书写，历史的走向会向着他们需要的方向写下。客观的历史并不存在。这是我目前的历史观。

#+begin_quote
  在人类被赋予的有限的智慧范围内，理解历史有两种方法：

  一种是作为有趣的故事去理解，另一种是作为引导自己的科学去理解。

  科学适合现在的你，以史为鉴，思考将来该做的事。
#+end_quote

理解历史的两种方法：当作故事；作为引导自己的科学。

#+begin_quote
  对于整个宇宙而言，生存者的存在有什么意义呢？如此辛苦地想要逃出去的意义又在哪里呢？为什么不能在这个世界里安定快乐地生活下去呢？整个部族为什么不能就在这里中止一直以来的旅程呢？真的不能中止吗？
#+end_quote

真的不能中止吗？

#+begin_quote
  世界是广阔而又永恒的，人生则是渺小而又短暂的。尽管如此------啊，不，应该是正因为如此，才不能不去考虑自己的行动对于全世界乃至全宇宙的意义。
#+end_quote

明白自己的行动对于自己的意义，对于世界的意义。

#+begin_quote
  就算在同样的环境里生活，有希望的时候和没有希望的时候，快乐与痛苦也完全不同。就算做同样的工作，有目的的时候和讨厌去做的时候，疲惫与否也完全不同。
#+end_quote

同样的工作，有目的地做和无目的地做，体验是不同的。

#+begin_quote
  一开始谁都没有外表，没有声音，没有名字，所有这些都是每个人自己花费很长时间才决定的东西，反复斟酌，用心挑选，盼望能给他人留下好印象，一想到每个接触的人都在看这个外表，就会有种满足感。可是，有时候我也意识到，其实别人根本不会用我费尽心思决定的外表和名字。他们只会随手给我的外表、声音或者名字加上别名。
#+end_quote

别人并不像自己以为的那样，也看中自己的外表。

#+begin_quote
  伪装成想让人看的自己，他们却不看；

  他们看到的是，我并不知道的自己。

  那样的世界令人窒息。

  是吗？那请仔细听好：

  不管哪个世界，都是一样的。

  你只会看到想让人看到的自己，

  别人只会看到他们想看到的你。

  人类可以看到自己想看的东西，

  也只能看到自己想看的东西。

  既不自由，却也很任性。

  即使如此，也应该接受世界本来的样子。

  用没有阴霾的眼睛去看没有扭曲的世界，

  用坦诚的心去追寻，世界必将向你倾诉。
#+end_quote

我看到的都是别人想让我看到的，我所表现的也是期待别人发现的。即便如此，这个世界还是如此美丽，所以用你的心去接受世界本来的样子，用没有阴霾的眼睛去看没有扭曲的世界，用坦诚的心去追寻，世界必将向你倾诉。

#+begin_quote
  她成了永远。

  但那是对他而言的吗？

  得到永远的，是他吗？

  还是她？

  永远在哪里都不存在。

  世界的一切都是刹那的梦。

  同时，永远在哪里都存在。

  一切都伫立在永劫之缘中。

  一切都是坐标系的游戏。

  没有确定的基础。

  刹那即永恒。

  永远即瞬间。

  如果那是真的，永远也会有终点吗？

  如果有终点，为什么会是永远？

  为什么你只关心终点？

  终点也是起点，

  恰如早晨是夜晚的终点，

  恰如春天是冬天的终点。

  没有终点，便不会有起点。

  永远开始的时候，首先必须要在那里终结。

  如果那是真的，那就没有真正的起点了。

  那样的话，为什么会有世界？

  为什么，我们会存在？
#+end_quote

她的时间无限漫长，他渐渐老去，彼此永远不能在一起。
