#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 我什么也没干，只是在好好活着 | 和抑郁情绪共处的315天

https://mp.weixin.qq.com/s/btV7AG9cWpHRGywReUL4ew

#+BEGIN_QUOTE
上个月我正式30岁了。在二十七八岁的时候，我无数次害怕30岁的到来。像骑着一匹注定奔向悬崖的马，无论再怎么拉紧缰绳，那种焦虑和惶恐都如影随形。

这是一篇很长很长很长的文章，长到我自己也未曾料想。从精神世界的坍塌，到漫长的无所事事，接受自己失控、脆弱和自怜，一点点慢慢找到新的秩序。我从未有过这样清晰、刚健和独立的自我意识。

在家里，我常常瘫在沙发上，一边和父母心不在焉地聊天，一边刷社交平台，2倍速看最新的热门视频。我大脑高度活跃，像跑马灯一样旋转着，不放过任何一个新的热点、新的趋势。精进、迭代，自我跃升。

大部分人，出生开始就逐渐有了“出厂设置”，来自父母、他人和社会的被动教育。这是一些既已被认定的大众价值观，混乱地堆积在思维里——我们会在别人都说好的时候，懵懵懂懂地说好。会在别人都买的时候，觉得自己也需要。会在流行一种美的时候，也去成为那种美。也会在面对阶级、权力和金钱的落差时，觉得确实低人一等。

为了写作，我开始建立完全新的秩序——

*如何能保持专注？*

真正的写作最难的是什么？不是写得好不好，有没有人看，是能不能日复一日的枯坐于此处，让心流在脑海里凿出一条通路，让自己浩浩荡荡地去真诚表达。

一些保持专注的方法：

- 练习冥想

- 早睡早起

- 低碳饮食

*我的金钱观/消费观是什么？*

我明确的是——钱是重要的，但对我来说没有重要到成为一种追求。我绝对不会再为了赚钱去做损害我精神和灵气的事情。

*美是什么？我的审美是什么样的？*

*我该如何定义朋友？*

1. 利益关系里没有朋友

在利益关系中保持边界感非常重要。如果你是领导，要和下属保持距离，不用幻想和任何人交朋友。如果你是下属，你有一个没有边界感的领导，他没法控制自己，你就要有意识和她保持距离。

2. 对关系有更多定义，精准朋友

面对各方面条件都比你优越的人，也不用非要攀附着去成为朋友，你们还不合适。平心静气面对落差，你可以毫不在乎，也可以努力和真诚去达到那个标准。都可以，但不要有混圈子交朋友实现阶级跃升的渴求，这是妄念。

对确定的朋友好一点，再好一点。不要吝啬你的爱、赞美和帮助。不要对他们做任何道德、道理和对错的判断。因为好朋友，就是要站队。这很重要。永远做最好的后盾，永远相信他。一旦你要去judge你朋友了，你不和她站队了，也许你们就不适合做朋友了。

很多人讲人际烦恼，说某某朋友怎么让自己不舒服了。看完之后，我一般只觉得：关系错了，他不是你的朋友。你不要拿朋友的标准要求他。他只是你的同事/领导/室友/同学/晚辈，你可以找到一种更合适的关系。随着关系变得明朗，不舒服的感觉就会消失。

当我说出来那一刻，我明白，父母的理解不再重要了。

我一直以来希望达到一种彼此理解的状态，即使是假的，是扮演的，我也贪恋这种平和气氛。我是你们心中的好孩子，而你们赞美我、鼓励我，做我的好爸妈。我畏惧不理解，我害怕关系里的倒刺，我希望每段关系都平滑流畅、和和气气。

如今我好像可以平静地接受——我们不用互相理解。

我们是家人，我们相亲相爱，有困难时会第一时间互相帮助，但我们不必真的理解对方想做什么。不必再去一遍遍解释。

今后的人生，我们必然秉承着完全不同的价值观，不同的行事风格，活成两种样子。不如就此把“彼此说服、统一观念”搁置，我们一起吃饭，旅游，聊八卦聊生活，看电影逛街，我们有更好的、超越“彼此理解”的相处模式。

*我们曾一次次把自己的痛苦、弱点和创伤，以及各种来路不明的自我苛求，归结于“原生家庭”“父母”，但这事实上是一种向外追责。它们也许是小小的诱因，是时不时打乱你心神的羁绊，但绝对不是答案。你的任何答案，都应该只来自你自己。它们只是旁枝末节，是你需要突破的一层关于“外界”的障碍。*

只有你自己是你的压力，是你的痛苦之源。没有任何其他人该为此负责。只有你自己能期待你自己，你不能满足任何其他人的期待。
#+END_QUOTE

读了这篇文章，让我开始思考自己是否在自己想要的方向上努力。我很容易听从他人的「意见」，却忽视自己内心真正的需要。我好想有点能明白，为什么看过体会过那些别人嘴里的有价值的事情，依然无法获得进步、认识自己。因为那只是别人的看法，我自己就像一个默默无闻的追随者，你说这个好，那我就去学习；那个好，我也想去学习。完全不知道真正应该把时间精力花在哪里。

我也一直在等待，等待某个「顿悟」的时刻，幻想着自己一旦度过那个时刻，此后一切都畅通无阻，做着一劳永逸的美梦，现实却一遍遍地打脸。不能停下自己的脚步，找到自己喜欢的事情，一定要不断地问自己，这件事是你真正想做好的吗？

关于父母。现在我很少和父母主动联系，都是母亲偶尔打来电话，聊一会儿。到了这个年龄，这个即将进入社会的阶段，我不知道如何与家人相处，只是不断地熬着，希望能度过这段时间。曾经的我以为获得父母的理解有多么重要，读了文章后，发觉理解并非如此重要，共同面对差异，才更珍贵。