#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 新年随笔

今天是 2019 年 2 月 5 日星期二，农历正月初一。这是一个值得纪念的日子。在过去几年，这一天我都过得很别扭，早晨很早就被叫醒，尽管前一天熬夜。对于传统习俗不甚理解：为什么要在这一天上午去串门呢？要早起没什么好说的，对于拜年我就要说了。对于像我这样常年不在老家的人来说，村子里的人对我几乎没有什么印象，我又何必拜年，简单认识呢？

这是我前几年的想法。今年，我却发现了一些不同的地方：邻里邻外的熟人们聚在一起唠唠家常，谈谈工作，彼此之间的距离更近了，感觉就像一个大家庭，尽管可能有些矛盾，但在这个时候是被忘却的。因为一年就一次春节，正是这个节日让我们这些平日里见不到面的熟人们有了些相处的时间。所以，这段时间是弥足珍贵的。

因为老家的房子不能久待，所以在给电动车充好电之后，我就回到县城的家。睡觉像个魔咒一样催促着我钻进被窝，所以，在吃完中午饭后我就爬进了温暖的被窝。睡醒之后的我有点不舒服，即便如此自己还是骑着电动车出去玩了。因为过年，人们都回了老家，所以街上的人比较少，除了商场之外。

骑着车微风拂面，感觉很自在，觉得很愉快。我慢悠悠地骑着，看着人来人往，生发出无限感慨。人这一辈子，*要做很多事，唯有在与自己相处时才是最自在的*。

--------------

一段文字：

#+begin_quote
  好的文字往往带给人两种阅读感受，一口气读完或者舍不得读完。我不想说老蔡的文字是哪种，因为不希望读者在阅读前有个讨厌的推荐人给他们先入为主的印象。

  很早前就看过他的几篇短文，于是这本书便成了我很期待的一样事物。我会将这本书带上旅途，在每个静谧陌生的夜晚拿出来慢慢看，而不是红灯亮起或者堵车不动时。

  这本书他写了很久，我希望自己能读更久。慢一些，不争一些，也许得到更多，到达更快。
#+end_quote

这是韩寒给蔡崇达的《皮囊》写的序，我觉得这就是读书的感受。这就是阅读的感受。

"人活着就是为了一口气，这口气比什么都值得。"------《皮囊》

这是“母亲”的话，我还不太明白这句话的真正含义，但我觉得可能母亲是要告诉“我”和姐姐一个道理，具体是什么道理可能等到我再读几遍时就会明白了。

生活的学问多着呢！永远也没有穷尽的时候，兜兜转转十几载，我的人生如蓄势待发的赛车手，只等那一声令下，我便奔雷般向前。我会退缩，我会抱怨，但在这一切之后的我，一定会有所进步，有所成长。当我走过这一段路再回首时，我想自己绝对不会后悔，/因为我真的在一心地做着我该做的事情，不管喜欢与否/。

** 更新
   :PROPERTIES:
   :CUSTOM_ID: 更新
   :END:
我再认真看这篇文章时，已经是 2021 年 1 月 18
日。这篇文章有几处错误，如今已经改正（我发现的错误）。重新阅读这篇文章才明白：时间是珍贵的。时间改变了我，改变了世界。但我与世界依然同步运转，此时的我正在准备实习，计划当一名程序员，我喜欢编程时的自己，我热爱编程。我相信世界会一点点变好，尽管新冠肺炎又起波澜。
