#+SETUPFILE: ./hugo_setup.org
#+TITLE: Others

Every person learns at a different speed and that's ok.

Is your speed, and you'll be fine in the future if you are consistent.

Don't compare yourself to others because we tend to see only the good in them.

Learn at your pace.

Great point, everyone's journey is different. Just take small but
consistent steps everyday

autfu 的开源经历 [[https://antfu.me/posts/about-yak-shaving-zh]]

---

Randy 的编程经历 [[https://lutaonan.com/blog/my-coding-road/]]

把自行车做成了自动驾驶 [[https://www.bilibili.com/video/BV1fV411x72a]]

钉钉创始人陈航的成长故事 [[https://cjxy.zust.edu.cn/info/1075/1727.htm]]

---

丁红的奇特的、令我向往的人生经历（海马星球播客已被封杀）
https://www.jianguoyun.com/p/DWVRG5MQzZOlBxjFyaUE

- 选择与自己志趣相投的朋友，拒绝不合适的朋友
- 有些事情，只有做了，才会看到，有很多人，在做和我一样的事情
- 考试这种事情，它不是个凭运气的问题；它的结果取决于，你花多少时间和毅力的问题
- 先试了再说，不要想着自己干不了；（6 分的时候做成了一件 10 分的事）一个机会只给你打 6 分，你要拼命争取那个机会，为什么？失败了是应该的，万一不小心成功了呢？如果你真的很努力地争取这些机会，你就会很努力地弥补这些不足，慢慢的你的能力就会往那个方向提高；如果一个机会给你打 10 分，那个机会本来就是你的，没有必要争，就看你要不要
- 对一件事的爱够不够？如果够，你就能够排除万难，做到你想做的事情

编程启蒙/从社区学习/个人竞争力（本期人物：Randy，AB）
[[https://binary.2bab.me/episodes/008-enlightenment-n-self-innovation]]

- Randy 对编程的理解升华到信仰——《[[https://movie.douban.com/subject/3205624/][社交网络]]》
- Randy 的启蒙书《JavaScript DOM 编程艺术》和《JavaScript 高级程序设计》
- 了解做一件事，如何入手
- 人是不可靠的，让程序辅助自己编程
- 开源社区帮助 Randy 赚取名声
- 前端简历没有区分度
- 在技术社区和别人不一样
- 每天看 Twitter、HN：看别人怎么解决问题
- 听技术大会 JSConf，React Conf
- 习惯于英文技术环境

---

maya 的故事，让我记忆深刻 <https://www.xiaoyuzhoufm.com/episode/61257677cc5f215c6e0b868a?s=eyJ1IjoiNjA1NGU4NjFlMGY1ZTcyM2JiMjRjMzQ4In0%3D%0A>

- 如何理解自己和父母的关系

---

[[https://twitter.com/codingyuri/status/1437019319557308416?s=19]]
- 做真实的自己
- 不知道一些事情是完全 OK 的
- 参与进自己的学习活动中
- 变得强大起来，不受别人的消极影响
- 建立有意义的链接

---

[[https://mp.weixin.qq.com/s/z_-jB2bhL6HYyGHg2MzOcg][张一鸣：我的大学四年收获及工作感悟]]

- 做好自己事情的同时，尽自己最大努力帮助别人解决问题
- 有好奇心，能够主动学习新事物、新知识和新技能
- 对不确定性保持乐观
- 不甘于平庸
- 不傲娇，要能延迟满足感
- 对重要的选择要有判断力

---

[[https://www.xiaoyuzhoufm.com/episode/5fca27e0dee9c1e16d0eb010][Steve 说 212 期 - 杜素娟 - 文学是人生的后悔药]]

- 建立多元价值体系，相信自己

---

[[https://treecat.cn/%E5%85%A5%E8%81%8C%E5%B8%86%E8%BD%AF%E4%B8%80%E4%B8%AA%E5%8D%8A%E6%9C%88%E6%9C%89%E6%84%9F/][入职帆软一个半月有感]]

---

[[https://her.blue/about/][很美的页面]]
