#+TITLE: Tech Learn Way How to Self Learning Cs Zilongshanren
[[https://zilongshanren.com/post/how-to-self-learning-cs/]]

​## 学什么

理论（ [[https://csdiy.wiki/]] ） + 实践

在做中理解深入理论。

实践部分：

- 有一个自己的爱好
- 学习吃饭的技能。一定要学习和使用业内最先进的技术，比如 Web 领域一定要使用 Vue 或者 React，如果你还在学习 JQuery 可能就会比较被动。
- 学习可以迁移的技能。尽可能地学习跨平台且开源的技术，不要跟某些私有公司绑定地太死，这样你下次在换工作的时候才会更有优势。
- 学习可以带来复利的技能。这些技能可以不断地丰富你的工具箱，让你在面对一个具体问题的时候有更多地可选方案，同时也能帮助你在做一些决策时更有效率，因为你掌握的信息越多，你的决策越有效。

​## 跟谁学

一定要向大师学习，像高手学习。这个行业的人才是非常多的，一定要找到比你厉害的人并且向他们学习。

那么去哪里找这些人呢？这里我分享我自己的一些小技巧：通过 Github 为出发点，找到知名项目的主要贡献者的个人主页，然后从个人主页中找到他的 Twitter 或者知乎帐号。然后关注他们，看看这些优秀的人每天都在关注些什么东西，读了哪些书，看了哪些演讲视频，目前正在做些什么项目。

可以经常逛逛 Reddit，Medium 和 Youtube，关注一些你觉得分享内容特别好的创作者，订阅他们的博客 RSS，收听他们的 Podcast（如果有的话），躺在床上不想编程的时候，可以看看他们每年在各种 XXX Conf 上的演讲，GDC 视频，WWDC 或者 Google IO 的视频，给他们点赞分享，让他们更愿意分享。

融入到更大的全球社区中去，增长自己的见识，而不要做一个只会面向百度和 CSDN 编程的码农。

​## 怎么学

文字比视频的信息密度更高、学习更有效率。

编程实践是重要的。每天保持一定的代码量。

​## 一些学习心态

* 终身学习， 不要太着急，[[http://daiyuwen.freeshell.org/gb/misc/21-days-cn.html][十年学会编程]]。
* 集中精力并且管理好自己的精力（看视频放在碎片时间，编码留好大段连续时间），每次学习 1\-2 小时，每天保持在学习比偶尔通宵达旦学习要好，细水长流。
* 空杯心态，不断提高自身的认知，可以每年学习一门新的编程语言，学习一个新的工具（比如 Emacs），学习一些新的框架和技术来扩展自己的视野。
* 定时总结输出，写博客，写 Side Project，分享输出会让你的学习更有效率。
* 积极锻炼身体，避免颈椎问题、腰椎问题和眼睛的问题，这个也非常关键。
