* Ferrite Bead

Ferrite bead, full name: Ferrite bead filter, used for anti-interference, mainly for suppressing high-frequency noise and spike interference on signal lines and power lines.

It is equivalent to a series connection of a resistor and an inductor in the circuit, but the resistance and inductance values of the ferrite bead change with frequency.

The ferrite bead is resistive at high frequencies, which can convert AC signals into heat energy, thereby achieving the effect of frequency modulation and filtering.

It is widely used in the power input parts of RF circuits, PLLs, oscillator circuits, and high-frequency storage circuits (such as DDR SDRAM, Rambus, etc.). Compared with inductors, ferrite beads are more suitable for high-frequency noise suppression and ESD pulse absorption.

磁珠全称：铁氧体磁珠滤波器，用于抗干扰，主要作用：抑制信号线和电源线上的高频噪声和尖峰干扰。

在电路中等效于电阻和电感的串联，但磁珠的阻值和电感值会随频率变化。

磁珠在高频时呈现阻性，能将交流信号转为热能，从而起到调频滤波的效果。

广泛应用于RF电路、PLL、震荡电路以及含超高频存储电路（如DDR SDRAM、RAMBUS等）的电源输入部分，相比电感，磁珠更适合用于高频噪声的抑制和吸收静电脉冲。