* 十三邀
:PROPERTIES:
:CUSTOM_ID: shisan-yao
:END:

** Vogel (许知远对话杨迈)
伟大的思想需要建立共识的机会。

> 杨迈 1940 年代从燕京大学毕业，学习西方自由市场经济学。1949 年他发现学习的这些都没用，他转而做了一名工程师。1949-1980 之间，他都没有施展才华的机会，直到改革开放之后，他的市场经济知识，帮助他在广州立足。

全世界真正出类拔萃的人有时没有机会，但是有时机会会迟一些到来。

人类的文明，不是仅仅只关于商业利益、经济发展或者技术的创新突破，文明应该是更广博的概念。某种程度上，文明应该是一种智识上发展的眼光，努力认清现实，又有更大的视野。

拥有一个宏观视角看待世界的发展运行。

Talk with them, Learn about them. Don't cheat yourself. Be a real person. 了解人，与他们交谈更重要。

他认为（2019 年）现在，在全球范围内，所有人都痴迷于细节，不再关注大的图景。

很多才华横溢的人丢掉了他们对于文明的信心。

现代美国大学太过官僚主义，大多关注种族议题、女性议题，这些尽管重要但从提升学术活力的角度来说，这些受欢迎的议题占据了学者们大部分时间和精力，使他们无暇顾及其他同等重要的社会话题。

如何发现有趣的议题：先从有趣的现象入手，然后发掘背后的大图景，一个未曾发现的大图景。

** 王宝强
离开这个环境；

坚持是一种技术；

面对恐惧，告诉自己，时间到了，一切就自然得解。

学习，学不完是好事，而事实上也学不完。不过，如果自以为学完，那可能就坏事了。

给自己以自信。

每个人都是带着成见来看待这个世界的，如果你不带着成见，那你对世界根本就没有看待方式（来自许知远）。

** 徐皓峰
动作的变化，事后分析为合理的运动方式，但起点就不对。

影像表达现实。

贾樟柯的《小武》。

写完文章，放两个星期再看，就容易改了。

自我的生命感觉和具体的事不见得是一个对应关系。

艺术：不能直言，提供另外一种生活的可能

水华《林家铺子》——巴尔扎克化

电影和现实的密切联系

生活充满隐喻

放弃区别和推理的心理，因为很多因果都是我们自己强加上的

李小龙《截拳道》——放弃分别心

城市的场景在 90 年代发生巨大改变

多种方式的自我欺骗

在如梦如戏的人间，做一件我喜欢的事吧

大家并不处在相同的世界，每个人都活在自己的世界里。活到四五十岁了，感受世界的方式，其实永远是他十几岁的时候构成他生命的最重要的事情。一辈子就是那两三件，然后后来发生的所有事都是这两三件事的解释。

所以生命就只在这两三件事上了

** 徐峥
佩恩（美国导演）：杯酒人生

《醉乡民谣》

--------------

有效的标签

--------------

我觉得我浪费了很多时间

但那些困惑和迷茫是不是也很重要

不重要

也都应该被有效利用起来是吗

我现在就觉得如果被有效利用起来，那就更好了

--------------

因为我们那一代文艺青年，因为满脑子比如你上大学，你要读什么尤金·奥尼尔的作品、什么易卜生的作品，然后你要关心当年巴黎演了什么、纽约演了什么，但其实你又在现实之中，它中间有一个很大的反差。你听鲍勃·迪伦的音乐，但你出门是吃那个生煎包子嘛。就是好像我们这代人普遍生活在一个很大的分离里面

--------------

《孤独的美食家》
