#+TITLE: 古希腊哲学学派
#+DATE: <2022-11-11 Fri 15:31>
#+TAGS[]: 随笔

** 斯多葛派

*** 内容

根据斯多葛主义的见解，哲学由逻辑学、物理学和伦理学三部分构成。在哲学划分的这三部分中，特别是在伦理学中，斯多葛派都谈到了国家、法律和政治问题。克雷安德把哲学分为六大部分，其中除了辩证法、演说术、伦理学和物理学和神学之外，又把政治学作为一个独立部分区分出来。在哲学各部分的进一步细分中，原来作为逻辑学的一部分的演说术，又被斯多葛派分为三部分：立法演说术、诉讼演说术和庆典演说术。

*** 自然法思想

西塞罗指出：“真正的法律乃是正确的规则，它与自然相吻合，适用于所有的人，是稳定的、恒久的，以命令的方式召唤履行责任，以禁止的方式阻止犯罪......要求修改或取消这样的法律是亵渎，限制它的某个方面发生作用是不允许的，完全取消它是不可能的；我们无论以元老院的决议或是以人民的决议都不可能摆脱这样的法律，......一种永恒的、不变的法律将适用于所有的民族，适用于各个时代；将会有一个对所有的人共同的，如同教师和统帅的神：它是这一法律的创造者、裁判者、倡导者。”

*** 独立的个人

个人主义是西方政治文化的独特观念，它在非西方的政治文化中是不存在的，这种个人主义观念在西方可说是古已有之，而最早、最鲜明又最系统地表达个人主义观念的哲学家是斯多葛主义，这种个人主义观念是在城邦体制瓦解以后，在对个人与国家的关系的重新解说中提出来的。由于个人与国家关系的疏离、个人日益从政治生活退回到个人生活，日益关注个人的精神世界，这实际促成了个人的某种解释和个人主义的萌发。

*** 世界主义的滥觞

在西方，世界主义的观念也是由斯多葛主义首先提出来的。

当然，它首先是对当时政治现实的一种反映。在小国寡民的城邦国家解体以后，人们生活在一个更大的帝国之中，这种大型帝国，不论是马其顿还是罗马都拆除了种族间的屏障，使各种族的人都共同生活在一个政治共同体之内，促进了种族间的相互交流和融合，使得原有的狭隘的种族观念逐渐淡化，一种世界主义思潮悄然兴起。

另一方面，从理论上说，个人主义必然从逻辑上引伸出某种形式的世界主义观念，因为独立存在的“个人既要考虑如何安排他自己的生活，又要考虑同其他个人的关系（他就是同这些个人构成了人们居住的世界的）；为了满足前一需要，就产生了研究行为的种种哲学，而为了满足后一需要，则产生了有关四海之内皆兄弟的某种新思想。”“个人的生活和孤立的意识也有其相反的一面，这就是人意识到自己是一个人，是种族的一员，具有到处大致相同的人类本性。斯多葛主义由他们的平等思想推出的结论是：人类一体，每个人都是人类大家庭中的一员，个人与人类整体的关系优于个别种族、国家的关系。因此，要树立一种超越单一种族和国家的世界主义新观念。

*** 平等的观念

所有的人，无论其出身、种族、财富以及社会地位如何不同，在都具有自然赋予的理性这一点上他们都是相同的，作为一个人，他们都是平等的。

西塞罗曾指出，在给人下定义时，应该是适用于所有的人。更为可贵的是，在奴隶制普遍存在，奴隶不被当作人看待的时代，斯多葛主义毫不迟疑地将平等原则适用于奴隶。塞内卡就认为，从伦理的意义上讲，奴隶制是不道德的，他还要求人们以由己推人的方式，将奴隶作为精神平等的伙伴、朋友来对待。

** 柏拉图的学院派

柏拉图主义的核心是：承认抽象对象的存在（existence of abstract
objects）。抽象对象并不依赖于时间和空间而存在，因此既非物理的，又非心灵的，而是存在于第三个地方。

柏拉图主义最初的概念是理型论。真正存在的是理念，是永恒、不变、完美的东西，而由此产生的诸多对象则是不完美的复制品。理念的数量，是由普遍概念的数量定义的。

** 亚里士多德的逍遥学派

亚里士多德主义（英语：Aristotelianism），又称亚里士多德学派，受亚里士多德著作启发而成立的哲学传统。最早由逍遥学派，以及新柏拉图主义学者对于亚里士多德著作的注解而成立。在古典时期，柏拉图主义与亚里士多德主义为欧洲哲学的两大主流。在欧洲中世纪时，亚里士多德的著作被译为阿拉伯文，亚里士多德主义因而传入伊斯兰世界，成为早斯伊斯兰哲学的重要部分。在
12
世纪之后，亚里士多德的著作由阿拉伯文译为拉丁文，亚里士多德主义重新传回欧洲，对经院哲学产生重大影响。

** 伊璧鸠鲁学派

伊比鸠鲁学派（英语：Epicureanism）是以伊比鸠鲁的学说为基础，创建于公元前
307
年的一个哲学思想体系。伊比鸠鲁是原子论唯物主义者，他认为存在着的万物必定是由永恒不变的原子所构成，而原子是一些细小的、不可毁坏的、坚硬的物质微粒。拥护德谟克利特的理论。他不采信决定论，并提出偏斜的原则，反对迷信、否认神的干预。伊比鸠鲁延续了昔兰尼的阿瑞斯提普斯（苏格拉底的学生之一，较不为人所知）的论点，认为最大的善是驱逐恐惧、追求快乐，以达到一种宁静（ataraxia）且自由的状态，并透过知识免除生理的痛苦（aponia），降低欲望。所以伊比鸠鲁的弟子都有同样的基本知识，认为哲学必须贡献给宁静和平。

*** 罪恶问题（伊壁鸠鲁悖论）

前设

#+BEGIN_EXAMPLE
    在分析罪恶问题前，一些概念必须加以明确定义，这是由于宗教信仰本身的特点所决定的。

    - 神是谁或什么？
    - 什么是恶？
    - 什么是全能（全能悖论）？
    - 以及什么是全善？
#+END_EXAMPLE

表述

#+BEGIN_EXAMPLE
    如果是上帝想阻止“恶”而阻止不了，那么上帝就是无能的；
    如果是上帝能阻止“恶”而不愿阻止，那么上帝就是坏的；
    如果是上帝既想阻止又能阻止“恶”，那为什么我们的世界依然充满了“恶”呢？
    如果是上帝既不想阻止也阻止不了“恶”，那么为什么还叫他上帝呢？
#+END_EXAMPLE

逻辑分析

1.  神存在（前提）
2.  神全能（前提，或者由“神”的定义得为真）
3.  神全善（前提，或者由“神”的定义得为真）
4.  所有全善的存在都反对任何的恶（无论此‘恶'是否是为了达成‘善'的结果）。（前提，或者由“全善”的定义得为真）
5.  所有全善的存在如果可能会立即消灭任何的恶。（前提）
6.  神反对任何的恶。（由 3 和 4 得出的结论）
7.  神可以立即彻底的消灭恶。（由 2 得出的结论）
8.  神会立即彻底的消灭恶。（由 3、5 和 7 得出的结论）
9.  恶存在而且可能永远存在。（前提）
10. 8 和 9
    矛盾，因此至少一个前提不成立：或者神不存在，或者神不全善全能，或者神有理由不立即这么做，再或者恶不存在。

--------------

参考资料：

1. [[https://baike.baidu.com/item/%E6%96%AF%E5%A4%9A%E8%91%9B%E4%B8%BB%E4%B9%89/2496268][斯多葛主义 - 百度百科]]
2. [[https://zh.wikipedia.org/wiki/%E4%BC%8A%E6%AF%94%E9%B3%A9%E9%AD%AF%E5%AD%B8%E6%B4%BE][伊比鸠鲁学派 - 维基百科，自由的百科全书]]
3. [[https://zh.wikipedia.org/wiki/%E7%BD%AA%E6%83%A1%E5%95%8F%E9%A1%8C][罪恶问题 - 维基百科，自由的百科全书]]
4. [[https://zh.wikipedia.org/wiki/%E5%8F%A4%E5%B8%8C%E8%85%8A%E5%93%B2%E5%AD%A6][古希腊哲学 - 维基百科，自由的百科全书]]
5. [[https://zh.wikipedia.org/wiki/%E6%9F%8F%E6%8B%89%E5%9B%BE%E4%B8%BB%E4%B9%89][柏拉图主义 - 维基百科，自由的百科全书]]
6. [[https://zh.wikipedia.org/wiki/%E4%BA%9E%E9%87%8C%E6%96%AF%E5%A4%9A%E5%BE%B7%E4%B8%BB%E7%BE%A9][亚里士多德主义 - 维基百科，自由的百科全书]]
