* product-thinking-2022-06-13
:PROPERTIES:
:CUSTOM_ID: product-thinking-2022-06-13
:END:
一味求快无法解决问题。要给自己留够思考的时间。

​## 羔羊：Patrick Collison：在提升互联网 GDP 之外，还在思考什么问题

问 Patrick Collison

1. 哪些小习惯对你影响最深远

欣赏一个人的作品，会和作者主动谈，彼此的对话是有益的。促进对对方的了解。当你联系一个人，一半时间他们回复，一半时间他们不回复，不回复也没什么，一旦回复就是巨大收获。

1. 在招聘时，如何识别那些将你的企业从优秀发展到非凡的领导者呢

问自己三个问题：

- 这个候选人好到你愿意为他们工作吗
- 这个候选人能比任何通情达理的人，更快地把你带到你需要的地方吗
- 当这个人不同意你的观点时，你认为你错的可能性会和他们错的一样大吗

1. 如何选择读什么书

> 读书应该是一个更加自主性的活动。你可以扫过、跳过、翻回去，不看了。你不是你的书的客体，也不是一个被动的接受者。书是你买的，想干嘛就干嘛。书分值不值得读，和好不好读，只有大概 10%~20%是又值得又好读的，我会先读那些值得又好读的。

Patrick Collison 发问

1. 改变人们重大的生活的决策是如何发生的

大多数时候，人们不会决定大幅改变他们的生活。有几天他们做到了。

那些日子有什么特别的？

刺激和他们自己的内心状态有多大关系？

1. 理解和塑造人格的正确方法是什么

自 20 世纪 80 年代以来，五因素的人格模型获得了巨大的牵引力。它表面上适用于大量的生活。它有什么局限性，我们应该在哪些情况下使用它？

1. 为什么中国还没有进行大量的顶层研究

在我最熟悉的领域（经济学、生物学、计算机科学、物理学），一致的报告是，中国大学还没有出现有影响力的研究（日本、法国、德国等大学有很多）。

这显然不是潜在个人任何特征的结果------中国研究人员已经并将继续在中国以外的大学做令人惊叹的 工作。中国大陆公民已经获得了六个诺贝尔科学奖，但只有一个是因为在中国所做的工作。尽管中国现在显然是的世界第二资金 R&D。

我们可能忽略了中国大学所做的许多伟大工作，尽管国家科学基金会报告称，中国机构的学者每年发表的同行评议论文比美国机构的学者多，所以我们似乎并没有简单地忽视中国的研究。

假设这里有需要解释的地方，中国大学到底缺了什么？

​## 理论：布迪厄：经济资本之外，还有两种资本

三种资本：经济的、文化的、社会的。

- 社会资本：我们在社会中关系的总和。例如家庭关系、专业网络以及与有影响力的人的关系。
- 文化资本：是指一个人获得教育，技能和知识等资源的机会。比如学位证或者举止习惯。
- 经济资本：是指现金和各种可以转化为现金的资产，例如股票、房产或专利。

关于文化资本，布迪厄理论的一个关键思想是，文化资本在社会成员之间分布不均。相反，它集中在某些社会群体中，例如上层阶级。文化资本的这种集中有可能导致机会和生活结果的不平等，因为那些拥有更多资源的人更有可能成功。

​## 考古：当 Apple 创造了 PC，意味着什么？

- 什么是 PC ？
- PC 和其它电脑的区别？
- PC 如何提高个人效率？
- 人们购买 PC 用来做什么？
- 十年后人们会用苹果电脑做什么？
- 苹果如何传承硅谷文化？
- 苹果的创业精神渗透到其它领域了吗？
- 苹果如何保持行业领先？

​## 心灵：为《杖藜远眺》的人，守护他的雄心壮志

[[https://etiennefd.substack.com/p/remaining-ambitious?s=r]]

白云如带束山腰 ，石磴飞空细路遥。独倚杖藜舒眺望，欲因鸣涧答吹箫。

一个人对一件事的野心会发生变化。

什么导致了这些变化？拒绝。

如何保护我们自己的抱负？我们怎样才能减轻被拒绝的打击？

- 把努力花在不需要别人认可的事情上。你不必承诺一旦找到工作就会成为一个有天赋的程序员/作家/摄影师，而是可以自己编码/写作/拍照。
- 让自己尽可能多地遭到拒绝。经常收到”不”的回答。但是我不喜欢把它作为一种应对拒绝的心理策略: 它相当于麻木我们自己，我怀疑当我们最终得到一个”是”的时候，麻木会削弱对雄心壮志的激励。
