* 最近有个朋友离开大城市回到家乡了。
:PROPERTIES:
:CUSTOM_ID: 最近有个朋友离开大城市回到家乡了
:END:
https://x.com/Yangyixxxx/status/1754168714247987230?s=20

聊天聊起来，每天在家里园子种种地，喂喂家畜。闲了泡个茶写个字，不亦乐乎。

但就这样，他说闲久了也想做点事情，问我有什么能做的。

我想了想，问了他第一个问题。"你的成就感来源于赚钱还是什么？"

他一直“正在输入”，迟疑了半天回了我一句：为什么问这个问题？

"有些人只要赚钱他就觉得开心，有些人是做出自己觉得有意思的东西会开心，还有些人是期望能帮到别人，对他人有价值，觉得开心，不同的人不同时空下都有不同的多巴胺来源，你属于哪种？"

他想了想，说出的答案可能和大多数人差不多：都有吧

我问他："那我这样问吧，我们从三个元素中排除两个：如果做一件事情，不够酷，但能帮到别人，有可能没钱赚，你能坚持多久？"

他想了想，觉得自己没那么圣母心，说坚持不了。

"那一个事情，很赚钱，但不酷，可能短期帮助别人爽，长期可能价值是负向的，你会做吗？比如搞黑五类，或者做色情交友，或者割韭菜？"

他问还有更好的选择吗？

"做一个酷酷的产品，有一小撮人喜欢，能赚小钱，你能坚持多久？"

他毫不犹豫的说："我可以持续做，直到我觉得它不酷了，我就再做个酷的！"

"那就是它了！那你有什么酷酷的想法吗？"

"目前没想到什么。有什么推荐的？"

"先找到你热爱的事情。"

"我喜欢写字"

"写字的人有很多，有期望入门的人，有已经报了课持续在练习的人，也有每天读帖持续临摹的大师，你觉得不同的人遇到了什么不同的问题？或者你走过来的时候，遇到过什么问题？"

"我读帖的时候，有些地方不知道该怎么用笔，导致怎么写都不对，很受挫，就难以继续。往往要调整心态不断练习才能找到门路"

"好了，就是这个。你写的什么体？"

"瘦金体"

"那你把瘦金体最核心的几个帖子，比如千字文，每个字怎么写的，都搞出来！要逐字，最好按笔画的，然后下面关联B站的视频讲解！"

"这能有人用吗？"

“你不是遇到问题了吗？如果你能解决问题，不就有人用吗？先去搜搜现在的瘦金体字帖，ipad上的那种，看看别人怎么解决的。看看用户在抱怨什么。

只是他们解决这个问题，要花多少钱，就需要测试。

要知道这个答案，也不难。

你去画一个UI稿，做一个landingpage，然后写个waitlist，让用户填写你的调研问卷后，分享给一个好友添加waitlist后增加他的排队名次！然后去你平时的书法论坛，传播它！看看能不能炸开！”

"好，我先去看看现在有没有这种产品！"

其实，想清楚要什么，开始就会变得异常简单。如果没有背负太多不切实际的幻想，反而能得到更多的发挥机会。
