#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 有愿景，有路线，大事可成

** 有愿景
   :PROPERTIES:
   :CUSTOM_ID: 有愿景
   :END:
愿景就是信仰，类似于理想。做事情没有一个好的愿景不行，这样做不成事的。因为做事难免会遇到困难，愿景的作用就在于它能够给你足够的动力去克服这个困难。之后的一些琐碎问题就变得无足轻重迎刃而解了。

我现在在做的事情，我自己心里也很没有打算。对于学习技术编程还是有非常多的迷茫之处。我的路还很长呐！

不太清楚自己现在的心理，我总是非常羡慕那些事先比我早些行动的人，有些人的博客主题很棒，内容写得也非常不错。

我就羡慕这样的人。一方面羡慕，另一方面又在担心：我能不能赶上什么时候赶上等等一系列问题。

这些问题现在时不时地困扰我，不会影响生活，但会影响心情。再加上自己不是特别认可自己的现状。所以，这两天心情不是很好。

不过，心情时好时坏也很正常，就当调剂生活。也不用太过担心。

** 有路线
   :PROPERTIES:
   :CUSTOM_ID: 有路线
   :END:
这里的路线可以理解为步骤。今天，着重看了 B 站 up 主 Codesheep
程序羊的几期有关技术学习的视频。下面是总结： 我主要是以 Java
为主记的笔记。有关 Java 的基础知识分为四个部分，分别是：

1. 编程语言
2. 基本算法
3. 基本网络知识
4. 基本设计模式

编程语言就是 Java 语言了。最首要的就是学习 Java
语法，使用规则等等。学习过 C 语言的小伙伴应该清楚。

算法嘛，就是数据结构这一块儿了。像什么栈和队列、二分查找、二叉排序等等这些就是算法范畴。算法有广义和狭义两种概念：广义算法是一门独立的学科，它包括的东西很多，目前我也不是特别懂。

后两种在这谈不了，我也不是特别了解，以后有一个深入的学习后再谈吧。

至于学习 Java 需要什么书籍，up 主推荐了几本。

学习编程语言可以看《 Java 编程思想》，这本是圣经级别的，要食用的话还是应该找些解释辅助性的书籍来看。《Java 并发编程实践》这本书讲多线程。《深入理解 Java 虚拟机》这本书将 Java 虚拟机，正是有虚拟机的存在才能够使得 Java 编写的语言能够一次编译，多系统执行。因为 Java 语言是通过 JVM （ Java 虚拟机）与底层操作系统进行交互。《函数式编程思维》就不那么偏向于语言，而是一种思维型训练，很值得一看。像我们这些大学生，想学编程，正好空闲时间很多，可以学习。

我今天看了很多视频，算是对于自己想要学习的编程方向有一个很模糊的认识，明天还要再思考思考。

还有，我不清楚网站备案为什么需要那么长时间。在我们安徽省，网站备案时间至少需要 17 天，也就是说。我要等待 17 天才能够对我的网站进行操作。这个等待时间很煎熬。不过还好我有其他事情要忙，内心的焦虑又降低了几分。
