#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 海蒂和爷爷

Heidi 海蒂和爷爷 - 2015 - 德国 / 瑞士 / 南非

** 故事梗概
   :PROPERTIES:
   :CUSTOM_ID: 故事梗概
   :END:
德特姨妈不想继续照顾海蒂，于是把她送给住在阿尔卑斯山附近的爷爷那里。刚来到那里的时候，爷爷不欢迎她们，赶她们。德特留下海蒂一个人逃跑了，爷爷从木屋里出来，问："你怎还不走？""她不要我。"海蒂回答道。那一天，海蒂睡在羊圈里，爷爷从窗口看她。

第二天天亮，爷爷进羊圈给羊挤奶，然后把奶递给海蒂，示意她喝下去。之后，爷爷慢慢地接受了这个小孙女，在到达约定期限的那一天------重新为海蒂寻找一户人家，爷爷为海蒂做的椅子做好了。海蒂可以继续生活在这里，这里很美，还有皮特这个玩伴。

如果不是德特的突然造访，海蒂会一直这样无忧无虑地生活下去。海蒂被德特“拐走卖掉”，她来到一户富裕人家，在那里她被教以礼仪、规范言行，她受到极大的约束，不能在山间玩耍，又有什么意思呢？

在城里生活的这段时间，有一处场景，让我印象颇深：海蒂推着克拉拉，在集市中寻找那座“能看到山”的塔，找到之后，海蒂上去看。当她望向远处时，发现远处依然是红色为主色调的房子，冒着黑烟的烟囱，那个干净的阿尔卑斯山，她再也看不到了。想到这里，海蒂沮丧至极。

海蒂在奶奶的鼓励下开始识字，家庭教师无耻地认为是自己的功劳。城市中的生活束缚了海蒂那颗渴望与自然接触的心，她时常梦游，看着天空的月亮。

海蒂和克拉拉是好朋友。克拉拉在封闭的城市里生活，当她遇见海蒂这个同龄小孩时，她再也不想离开她。但是，她知道如果海蒂想走，自己是留不住的。海蒂也和克拉拉一起玩，但是这种感觉总是没有在山间那么痛快、无拘束。

后来，海蒂回到爷爷身边，克拉拉来看海蒂，皮特把克拉拉的轮椅扔掉，克拉拉能够站起来。这样一个故事就结束了。

** 剧情分析
   :PROPERTIES:
   :CUSTOM_ID: 剧情分析
   :END:
我不知道 /Heidi/ 译成 海蒂和爷爷
是否合适，但是我认为“海蒂和爷爷”是适合这部电影的。这部电影虽然以海蒂为主线，但爷爷在其中的作用也很难忽视，至于为什么不以友情命题，我不清楚，可能也和
2015 时的情况相关。

看电影时，总会出现人物，而一部好电影，它的人物一定具有鲜明独特的人格特点。这些特点，或令我心生敬佩与赞美，或令我感到作呕与恶心，无论让我产生怎样的感觉，我都对这种人物记忆深刻。

这部电影中的女管家、德特姨妈和那个男保姆安什么来着。Ta
们三人令我印象深刻，女管家怕猫，对猫过敏呢；德特姨妈势利、傲慢、无礼、狡诈；男保姆温柔、和蔼。

整部电影的节奏点把握刚好。德特的来到是一个转折，皮特把轮椅扔掉也是一个转折。前者意味着海蒂将远离自然、来到城市，后者则表明克拉拉可能会站起来，因为她不得不这样。只有这样她才能追逐那只蝴蝶。

** 我的感受
   :PROPERTIES:
   :CUSTOM_ID: 我的感受
   :END:
心疼她，多小的一个孩子呀，要承受想念爷爷的痛苦。

那些痛苦，只有当我身在别处，夜深人静、辗转反侧时，才能感受的到。

希望我心里的那个海蒂，永远快乐，永远永远......

写于 2020 年 6 月 9 日
