#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 努力的方向不对

痛恨用假钱者，卖菠菜的老头收了假钱：这个人买了 5 块钱的菠菜，给了老头
100 块的假钱。周围卖东西的都聚在一起说道这件事，可怜。

#+begin_quote
  唐代诗仙李太白，在他《北风行》诗里说："燕山雪花大如席，片片吹落轩辕台。"描写塞外风雪，凛冽苦寒。想不到就在燕山之北，却有一座名城，冬不酷寒，夏宜避暑，这就是久为众口交誉的“北国江南”承德。
#+end_quote

唐鲁孙如是说。不论其他文字，单论这后一句话就有着说不出的好。三言两语，介绍清楚这承德的气候特点以及地理位置。我所缺乏的恰是这种用语的简练，写文时拖拉，三两句话能完事，五六句方可。这样写来岂不是很费精力？

然经深思熟虑写出，亦忧其速。故余将勤加练习之。（不知道这两句文言写得中看否？大意是经过深思熟虑写出的文章，没有速度，需要很长时间写就。所以，我要勤加练习。）

就在刚才，看到一篇讨论
[[http://mp.weixin.qq.com/s?__biz=MzU1OTYyMTQ1MA==&mid=2247487970&idx=1&sn=51099843d370d7fb3ef254779a02023b&chksm=fc1525c7cb62acd173b69c2e8dcdd10e330aa9b94685fedb99f5dc4939eb70c2c05d87081d91&mpshare=1&scene=21&srcid=&sharer_sharetime=1579444311590&sharer_shareid=437b422f294856364ccf4b95415ead8d#wechat_redirect][应试教育与素质教育]]
的文章。它动摇了我的观点------*我认为学校成绩并不是评价一个人的首要因素*。*这是一个很安全的论断，因为它似乎迎合各方观点，好像没有人会反对这句话。*一直以来，我都是一种用这种写作技巧，巧妙地避开尖锐表达观点的时刻。

因为在现在这个时候，安全最重要，对吧？小心驶得万年船呐！可是当我陷入这种安全的境地无法自拔的时候，内心的真实想法就没有能力表达了。

这些年来，我对应试教育深有体会，对素质教育略有耳闻。刚听说素质教育时很兴奋，觉得这样很棒，不用写作业，每天轻松，培养特长就
OK 了。但是，那些所谓“素质”真的都是用钱砸出来的。

像我这样的中产以下的家庭，根本承担不起这种素质教育。我终于理解母亲不能再让妹妹上舞蹈班的本质，因为对于我们这些家庭来说，衣食住行是主要问题。其他的素质培养、精神需求，是在夯实的经济基础上才能拥有的。

马克思说："*经济基础决定上层建筑。*"这句话是最真实的写照。现在，我对素质教育持谨慎态度，但对个人主观培养能力特长是很有信心的。一个人在能够自己满足自己的基本生活所需之后，还有额外的经济能力，那么他可以为自己找一些兴趣爱好培养。这是人在满足物质需求之后，所必备的精神需求。

*我感觉自己好像一直在追求方法，而越来越忽视思想。*具体的体现就是学习计算机时，只注重工具的收集，而忽视了这些工具的共性以及应用的范围异同。导致我对于学习技术的兴趣逐渐下降，支撑我学习的动力越来越弱。

记于 2020 年 1 月 19 日
