#!/bin/bash

## remvoe old html files
find . -name "*.html" -type f -delete # https://askubuntu.com/a/377442

## generate new html files
rm -rf ~/.org-timestamps/
emacs --batch --script ./scripts/publish.el

## generate sitemap
python ./scripts/gen-sitemap

## generate RSS
# cp ~/repo/random-blog/blogs.json scripts/blogs.json

## push two remotes
git add --all
git commit -m "BUILD HTML"
git push origin main