#!/bin/bash

# generate html files.
# rm ~/.org-timestamps/pages.cache
emacs --batch --script ./scripts/publish.el

if [ $? != 0 ]
then
    echo "publish failed!"
    exit 1
fi

# post processing html files.
python ./scripts/gen-sitemap
rm */**/**/*.html
git add --all
git commit -m 'BUILD HTML'
git push ts main
git push origin main
