#+TITLE: 2022 年终总结
#+DATE: <2023-01-01 Sun 09:26>
#+TAGS[]: 年终总结

上半年在学校，下半年在社会。上半年，处理毕业相关的事情；下半年，找工作无果，去送外卖。

上半年是身处象牙塔的最后时光，天真地以为自己在离开学校后会如愿找到工作，正常工作生活。工作的确是找到了，不过因为自己的技术不过关而被辞退了。6月20号找到工作，7月4号辞退。此后，我自暴自弃了2个星期，每天在住处刷剧。后来，我开始继续学习技术。父母也一直催促我出去找而不是在网络上投简历。我去了两家公司，一家需要预约才能进去，另一家见到了HR，给了面试机会，但还是不行被拒。时间就来到了9月26日，我不知道怎么的，就在BOSS直聘上找服务员之类的工作，看到有招外卖员，也问了一下，于是我就开始送外卖。最初的想法是，一边送外卖，一边学习技术。而实际上，我也是这么过来的。到现在我已经做了三个多月的外卖员，挣的钱够我在杭州吃饭生活的，没有更多钱剩余了。

我已经不敢计划将来了，因为计划好的将来，总会被现实发生的不知道什么事情打乱。我脑袋里现在只有一个目标，学习好前端技术，还有计算机基础。其他事情，要等到我完成这一部分再说，时间的话，持续到2月25日吧，因为这一天发1月份工资。然后，我可能不做外卖员了。但是，如果我还找不到工作，继续做下去也就成了唯二出路。

送外卖时，并不总是有单可送的，等单的时候，我会阅读。阅读，能让我摆脱生活的平庸感觉，沉浸在作者讲述的或真实或虚幻的世界里。上半年在学校的时候还看过几部电影，下半年离开了学校，似乎看电影就没有心劲儿了，新看的电影很少，多是回顾以前看过的内容。

今年读过的一些书：

- DOM Scripting
- 深入 PHP 与 jQuery 开发
- 自学是门手艺
- Operating System Concepts
- 文化苦旅
- 挽救计划
- 小偷家族
- 献给阿尔吉侬的花束
- 只是为了好玩
- 索拉里斯星
- 以鸟兽之名
- 寂寞的游戏
- 钢铁是怎样炼成的
- 心理学与生活
- The Linux Programming Interface
- 哲学的故事
- Pragmatic Programmer 程序员修炼之道
- The Zen of CSS Design
- 窗边的小豆豆
- 算法设计手册
- 银河帝国系列
- Operating Systems: Three Easy Pieces
- 狂热分子
- 寻找家园
- 张春桥：1949年及以后

有些已经读完，有些只读一部分。

我曾经认为：政治就是一群人的权力争夺，和我没有关系。但是，当切身体会到政策的改变给我造成的影响时，我明白：政治跟我们每个人都息息相关。我当然可以选择「两耳不闻窗外事」，送外卖的生活就是这样，午晚高峰时期工作，其余时间在住处躺着玩手机。我也可以选择阅读与思考，让自己明白这个社会究竟发生了什么，何以到现在这个地步。我没有忘记自己的目标——了解自己，认识世界。我每天都在朝这个目标前进。

2022年12月份的疫情放开，导致我从21号开始的六天没办法工作送外卖，我最后想要回老家养病，但被外卖的站长（李明）劝下来了。他对我说：如果现在回去，手里没有多少钱，过年心里也不踏实，年后就更发愁了。继续送外卖，别管挣多挣少，终归比回家强。现实如此，我也就没有回去的念头，幸好在28号时我就可以继续工作了。尽管咳嗽不断。

我为自己定了一个十年计划：从2022年开始，到2032年结束，我要培养自己在人文方面的素养。主要培养方式，就是阅读思考。大致涵盖主流的社会科学领域，像社会学、心理学、政治学等等我感兴趣的领域。文学也在其列。如今，2022年已经过去，时间还剩9/10，新的一年多多阅读、多多思考。
