#+TITLE: 2024 年终总结
#+DATE: <2025-01-01 Wed 21:05>
#+TAGS[]: 年终总结

今年和去年很是相似呢。23年从杭州回到老家，在老家学车考驾照，之后去老家所在的阜阳市做腾讯地图的外包。24年4月底辞职，休息两个月去了深圳，找前端开发工作无果，在电子厂做硬件测试。

* 大事记

** 阜阳马拉松

第一次参加马拉松活动，和那么多人在一起跑步还是很激动的。我只跑了3.7公里，不到规定的5公里。但仍然很是激动，当时的自己想着：以后一定要跑个全马和半马。跑步的时候我在意的是自己跑起来是否爽快自在，丝毫没有在意别人是否会超过我。当我写下这段时，我的思绪又回到了跑步的时候，回忆起自己跑步时的愉悦感觉。

** 请大家给我发一封邮件

5月份的时候，给读我博客的大家写了这篇文章，想获得一些鼓励。谢谢他们和我分享自己的故事，把自己对于生活的见解分享于我，我很感谢他们。有的时候，我或许只看见眼前的种种困局，却不知道看得更广一些、更远一些。人是不是只能做事后诸葛，身在局中，永远看不清自己未来的路该如何走？

奈何只能走一步看一步，不断地选择，不断地作出决定，多年以后，回头再看，一条脉络清晰的路线已经清晰可见了。

** 父亲住院

3月份父亲出车祸，右肩肩袖断开。当时我还在上家公司上夜班，出车祸的时候妈妈没有告诉我，只是在开始做手术的前一天才告诉我。手术是在县医院做的，我去陪了他几天。但是这次手术并没有完全修复父亲的肩袖。

6月份父亲先在阜阳市第二人民医院检查，想让他们再进行一次手术，但是这里的医生并无把握。推荐父亲去合肥的安徽医科大学第一附属医院，找一个叫王高远的骨科医生。于是，我又陪父亲去合肥做手术。这次手术成功修复了肩袖，以后每隔一段时间复查一次就行了。

** 第一次来深圳

6月30日早晨到达深圳，晚上就约了在深圳的两个大学同学吃饭。在那个饭店，我们边吃边聊自己这两年的故事，感慨时间过得好快。很多人都问过我，你一个安徽人，为什么会到深圳来？去上海应该更合适吧。我回道，我来这里是因为一个技术活动——VueConf CN 2024。3月份报名了这个活动，此后就一直期待着参加。一切都是机缘巧合，并没有仔细的计划。

如今，我可以这样说：我很高兴，自己在这样的年纪来到了这座城市。我见识到了不曾见过的事物，认识了很多了不起的人。他们帮助我了解这个世界，进而激发了我对这个世界更强烈的好奇。

** VueConf CN 2024

Anthony Fu的“薅羊毛”式开源之路，提供给我一个简单的做开源项目的思路——先解决自己的问题，之后抽象出来，给别人用。

见到了Randy Lu，和他握了手，也算是网友线下面基了。

** 国庆游玩

国庆的时候做了两件事，和新认识的朋友李，去坐了湾区游轮；去惠州找大学的两个同学玩，逛了西湖，吃了顿饭。

** 24年中国开源年会

这个技术活动是开源社主办的，我去做志愿者。最大的收获是见到了开源社的大家，名字和脸能对上了。增进了对这个组织的理解，也思考了自己以后的技术路应该如何走。

** Maker Faire 深圳 24

这是一个创客活动，和开源社的大鹏老师一块参加的。了解了现在大家都在做什么，是怎样利用技术来表达自己的想法的。

** 音乐剧《巴黎圣母院》

作为今年最后一个活动，以此作结，是圆满的结局。我是一个很容易进入剧情的人，如果一个故事足够打动我，我可以跟着故事的发展一会儿哭一会儿笑，我能够体味到主人公情感的流淌。

当卡西莫多怀抱爱斯梅拉达的躯体，诉说着自己的一片痴情时，我感受到了那种无奈与叹惋。世人都爱美丽皮囊，却不知道那皮囊下藏着一颗怎样的心。

* 见人

说说我今年认识的两个新朋友。

** Chirs李

和他认识是经过一个同样写作博客的网友搭线，我们第一次吃饭是在桃园。互相聊一些工作技术生活的话题。后来，这个网友因为没有时间就没再和我们一起吃饭。我和李每个月见一次，约定在一个地方吃饭，吃完饭去散步聊天，几乎每次都是这样。我们去过海上世界酒吧街、坐过湾区游轮、吃过好几次饭。我以前不怎么出去吃饭，所以烤肉、日料等这些食材都没怎么吃过。他带我去吃，他说有些东西翅果才知道，自己并不是消费不起，也就不必觉得自己低人一等。

我们互相分享家里的故事，自己对未来的打算和迷茫；我们分享自己对于这世界的种种看法，怎么应对这一切的变化；我们倾诉自己的不安，自己该如何面对等等。

庆幸自己刚来到这个新环境，就能够认识这样一位朋友。

** 易姐

易姐是电子厂工作的同事，她是我见过的性格最开朗的人。和她一起工作很愉快，她教会我要快乐地度过每一天。

最近几天，我认识到自己的情绪变化会有一个起伏期。有两三个星期，每天起床知道自己今天要做什么，对于未来充满期待，渴望通过自己的努力实现自己的目标，成为想象中的自己；但这个阶段一旦过去，就开始浑浑噩噩起来。再加上我容易受到外界环境的影响，所以低谷期会持续得更久一些。低谷期过去后，我又开始充满干劲儿地完成我的任务了。

当我和易姐聊这种情况时，她分享了自己的故事，她年轻时就是我前面描述的那种充满干劲儿的状态，24岁就开始创业的她，总是想要有自己的一份事业，后来在事业和家庭之间，她选择了家庭。25年我想改变这种局面，提高我积极情绪的占比，在出现消极情绪时及时找到原因，调整心态，让自己回到积极的状态中。

易姐告诉我，以前她不是这种爱笑的人，后来在朋友家人和书籍的帮助下，她改变了自己，让自己享受当下、享受生活。我在这里想说：

#+BEGIN_QUOTE
谢谢你，易姐。你的笑容感染了我，你积极的心态让我更有动力去探索属于我的未知。
#+END_QUOTE

* 2025年的主题

我要改变自己的心态，尽力提高积极情绪的占比，减少消极情绪。

多读书，读好书，好读书。
