#+TITLE: 2025 年终总结
#+DATE: <2026-01-01 Thu 00:00>
#+TAGS[]: 年终总结

今年做了很多尝试，被父母逼着去了一次相亲、看了几场音乐剧、计划看两场演唱会（都被取消:-)）、看了两场Live、写了找女朋友的文章、和来深圳打工的妹妹一起吃了顿狼狈饭、去了一次香港；经历了一次很严重的压抑阶段，堪比22年那次。

工作依旧是在工厂，不过工作内容变了，以前是样品测试，现在是量产测试。中间还有些许波折，下文再说。

* 年初的TODO完成度

- 多读书：25年阅读时间近600h，读了几部长篇网文，也读了几本非虚构
- 提高积极情绪占比：会在人前微笑了，心态的确比年初时积极许多，经历更加丰富了

* 大事记

** 三场音乐剧：日落大道、芝加哥、罗密欧与朱丽叶

今年看音乐剧比较多，主要是想感受视听音乐的氛围，剧情对我来说并不重要。看罗密欧与朱丽叶的目的性很强，主要是想找个心仪的人一起看，最后还是没能如愿。看着舞台上的人在演绎着那样的人物，自己是在回顾经典吗？或许吧。又像是在找寻着什么。

借助故事、借助音乐，让人的思绪飘飞，短暂地脱离现实，离开束缚自己思想的工作，和人们一起幻想那别人的人生。这或许是我看音乐剧的想往所在。

** 两场Live：李上安、简约情人

李上安这场是第一次看Live，期待已久，感觉还可以。几乎全暗的氛围中，等待着开场，我靠在墙角等待。

简约情人这场比李上安的要更打动我，女主唱的声音让我觉得似乎一些不好的事情都不必久留心间，人要向前看、平和安宁。

看Live对我来说，像是一次探险，不知道现场会带我的感觉如何。只是慢慢地，人就这样不自主地沉浸其中了。等到回过神，曲终人散。

** 妹妹来深圳打工，我和她见了一面

妹妹高中毕业，来深圳打工。想见她一面，但是她一直不想见我。因为工厂工作很累不想出门。

直到她快离开深圳了，才说和我见一面，让我帮她带路去火车站。带完路后，打算去吃饭，没想到下了大雨。雨中我们慌不择路，随便用导航找了一家披萨店，吃了没那么好吃的披萨后，又打车回到地铁站。她回她的宿舍，我回我的住处。

** 工作转岗

工作到年底，我自嘲：自己在这家公司做了三种工作。一年多的工厂样品测试，一个月的研发测试，两个月的工厂PE。心理状况急转直下的时段就是在从研发测试换到工厂PE的阶段，我浑噩了两天，第三天还是去上班了，无他不上班活不下去。

未来会怎么样，天知道。走一步算一步。

* 今年读书

1. 支付战争 by Eric M. Jackson
2. 不要因为走得太远而忘记为什么出发：陈虻，我们听你讲 by 徐泓
3. 在春天 by Karl Ove Knausgård
4. 窗边的小豆豆&续 by 黑柳彻子
5. 东莞乐队和流水线上的孔雀们 by 袁斯来（谷雨实验室）
6. 别相信直觉 by Seth Stephens-Davidowitz
7. 消失的多巴胺 by Tanith Carey
8. 神曲 by Dante
9. 失明症漫记 by José Saramago
10. 可能性的艺术 by 刘瑜
11. 希望之书 by Jane Goodall
12. 被讨厌的勇气 by 岸见一郎, 古贺史健

在找这些书的时候，发现很多都忘记讲的什么内容了，如果不是微信读书有记录。我都不会记得今年读过这本书。

* 明年计划

1. 思维能力的提升
2. 折腾中心全部放在Emacs，其他技术只要能维持正常学习生活运转，就不再投入精力深度钻研
3. 摒除一切非必要消费欲望，记账规划财务
