#+TITLE: Climate change from 80000 hours
#+DATE: <2022-11-06 Sun 14:36>
#+TAGS[]: 他山之石

[[https://80000hours.org/problem-profiles/climate-change/][Climate change - 80,000 Hours]]

#+BEGIN_QUOTE
Could climate change lead to the end of civilisation?
#+END_QUOTE

气候变化会导致文明的终结吗？

#+BEGIN_QUOTE
Across the world, over half of young people worry that, as a result of climate change, humanity is doomed. They feel angry, powerless, and — above all — afraid about what the future may hold.
#+END_QUOTE

从世界范围来看，超过半数的年轻人担心，人类因为气候变化而灭绝。他们感到愤怒、无能为力，最重要的是，他们害怕未来会发生什么。

#+BEGIN_QUOTE
Climate change matters so much, to so many, not just because of the suffering and injustice it’s already causing, but also because it’s one of the few issues that has obvious potential to affect our world over many future generations. We think safeguarding future generations is a key moral priority, and should be a crucial consideration in prioritising problems on which to work.
#+END_QUOTE

气候变化如此重要，对很多人来说，不仅仅是因为它已经造成的痛苦和不公正，还因为它是少数几个明显有可能影响我们后代的问题之一。我们认为，保护子孙后代是一个关键的道德优先事项，在确定需要解决的问题的优先顺序时，也应该是一个至关重要的考虑因素。

#+BEGIN_QUOTE
If climate change could lead to the end of civilisation, then that would mean future generations might never get to exist – or they could live in a permanently worse world. If so, then preventing it, and adapting to its effects, might be more important than working on almost any other issue.
#+END_QUOTE

如果气候变化可能导致文明的终结，那么这将意味着未来世代可能永远不会存在——或者他们可能生活在一个永远更糟糕的世界。如果是这样的话，那么防止它，并适应它的影响，可能比解决几乎任何其他问题都更重要。

#+BEGIN_QUOTE
So – what does the science say?
#+END_QUOTE

那么，科学怎么说？

#+BEGIN_QUOTE
The Intergovernmental Panel on Climate Change (IPCC) Sixth Assessment Report is, to our knowledge, the most authoritative and comprehensive source on climate change. The report is clear: climate change will be hugely destructive. We’ll see floods, famines, fires, and droughts — and the world’s poorest people will be affected the most.
#+END_QUOTE

据我们所知，政府间气候变化专门委员会政府间气候变化专门委员会(IPCC)第六次评估报告是关于气候变化的最权威和最全面的资料来源。这份报告很清楚：气候变化将具有巨大的破坏性。我们将看到洪水、饥荒、火灾和干旱，而世界上最贫穷的人将受到最严重的影响。

#+BEGIN_QUOTE
But even when we try to account for unknown unknowns, nothing in the IPCC’s report suggests that civilisation will be destroyed.
#+END_QUOTE

但即使我们试图解释未知的未知因素，IPCC 的报告中也没有任何迹象表明文明会被摧毁。

#+BEGIN_QUOTE
This isn’t to say society shouldn’t do far more to tackle climate change.
#+END_QUOTE

这并不是说社会不应该在应对气候变化方面做得更多。

#+BEGIN_QUOTE
That’s because climate change’s impacts will still be significant – it could destabilise society, destroy ecosystems, put millions into poverty, and worsen other existential threats such as engineered pandemics, risks from AI, or nuclear war. If you want to make climate change the focus of your career, we include some thoughts below on the most effective ways to help tackle it.
#+END_QUOTE

这是因为气候变化的影响仍将是巨大的——它可能破坏社会稳定，破坏生态系统，使数百万人陷入贫困，并加剧其他生存威胁，如人工流行病、人工智能风险或核战争。如果你想把气候变化作为你职业生涯的重点，我们在下面提供一些帮助你解决气候变化问题的最有效方法。

#+BEGIN_QUOTE
So yes, climate change is scary. And people are right to be angry that too little is being done.

But we’re not powerless.

And we’re far from doomed.
#+END_QUOTE

是的，气候变化是可怕的。人们对于政府做得太少感到愤怒是正确的。

但我们并非无能为力。

我们还远没有完蛋。

------未完待读------

-----

人工智能，核武器导致人类灭绝的可能性比气候变化大得多；

但是，气候变化会导致地球上最贫困的那些人，承受更多的苦难。
