#+TITLE: 关于自信的一次顿悟 by 廖海波
#+DATE: <2023-05-19 Fri 09:50>
#+TAGS[]: 他山之石

- https://twitter.com/realliaohaibo/status/1659223451771752448
- https://twitter.com/realliaohaibo/status/1638888965779648519

成长虽然能够消除反复失败带来的习得性无助，让人不再自卑，但也无法让人真正自信起来。

从未意识到自己没有获得足够的自信，把正反馈带来的自负当自信的关键问题在于：

a. 遇到负反馈就很低落，没有反脆弱性
b. 遇到疑似攻击/挑战，应激反应很大

一个低俗的英文短语：[[https://www.urbandictionary.com/define.php?term=Big%20Dick%20Energy][Big Dick Energy]]，它在Urban dictionary的解释：

#+BEGIN_QUOTE
The loud and boisterous energy emitted by someone who has a colossal phallus and doesn't have to tell anyone about it. The energy speaks for itself. The Big Dick tells it's own story. Everyone strives for big dick energy. Only few possess such a gift. People with big dick energy possess qualities such as leadership, kindness, positivity towards others, great humor, and a "dont fuck with me" aura. Great hair too.
#+END_QUOTE

BDE意味着一个人既知道在哪些地方是无知的，又知道自己的价值。所以他会忽视绝大多数外部评价体系，除非这种评价体系揭示了自己尚未理解的维度。

拥有BDE的人不会成为外界评价的受害者，更关键的是不需要通过伤害他人获取满足，因为他拥有完全的安全感。

BDE让人持续进步，因为我们可以清醒地评估和接受自己的无知之处，持续建立自己的“纠错反馈循环”：

#+BEGIN_QUOTE
马斯克曾被问及“你一生中最大的挑战是什么？”。一向思维清晰，滔滔不绝的马斯克少见地陷入了沉思，然后说出了他对我启发最大的话之一：

One of the biggest challenges I think is making sure you have a corrective feedback loop, and then maintaining that corrective feedback loop over time even when people want to tell you exactly what you want to hear...

（有一个纠错反馈循环，并且始终维持这个循环。）
#+END_QUOTE

“迭代”本质上就是要打造一个纠错反馈循环。

*问题在于，在绝大多数的设计里，反馈并不明确，没有指向性，无法用于纠错。* 这就是我们停止进步的时候。

为什么大多数人都能学会骑自行车，学会投篮？

因为简单？那到底什么是简单？

“简单”的本质是：纠错反馈循环足够明确，人人都能维持这样一个循环，获取进步，直到达到目标。

在一个模糊的、维度足够多的系统里，我们如何建立并维持这样一个循环？

对于不同的情况不能一概而论，作者的答案是：第一性原理。

#+BEGIN_QUOTE
第一性原理有很多不同的理解层面，但在认知范围内把问题拆解成底层逻辑以后，如果找不出需要的维度，在上层的尝试就已经不必要了。

例如在互联网产品迭代上经常用的AB test，如果你能拆解出此处应该用A/B去尝试，必有一个能有效，你只是不知道哪一个，那进行AB test，这个corrective feedback loop就已经搭建起来了。

反之需要测试AB，而你的认知范围内只能拆解出CD因素，那你随便怎么测试，这个问题都不在你能解决的范围内，因为你的知识储备还不够，看不见需要的维度。
#+END_QUOTE

采用第一性原理的思考方式与否的区别在哪里？

1. 打破路径依赖
2. 遍历解决方案
