#+TITLE: The Chinese Way of Innovation
#+DATE: <2022-11-05 Sat 21:45>
#+TAGS[]: 他山之石

[[https://www.foreignaffairs.com/articles/china/2022-04-21/chinese-way-innovation][The Chinese Way of Innovation | Foreign Affairs]]（注册登录后，可见全文）

#+BEGIN_QUOTE
For decades, many Americans derided China as a nation of copycats incapable of creativity, let alone breakthrough innovation. Authoritarianism and central planning were thought to be naturally inimical to fresh ideas. Rapid technological advancement, many in the United States believed, required the kind of fearless, “disruptive” thinking that was most at home in a freewheeling, democratic society.
#+END_QUOTE

几十年来，许多美国人嘲笑中国是一个没有创造力的山寨国家，更不用说突破性创新了。人们认为，威权主义和中央计划自然不利于新思想。许多美国人认为，快速的技术进步需要一种无畏的“破坏性”思维，这种思维在一个自由、民主的社会中最为常见。

#+BEGIN_QUOTE
Over the past several years, however, the narrative has shifted, and any complacency over U.S. technological superiority has evaporated. Business columns explaining China’s seeming inability to innovate have given way to op-eds warning that it is poised to surpass the United States in strategic technologies such as artificial intelligence and 5G. Policymakers in Washington who had long been content to leave technology up to Silicon Valley are now racing to find ways to bolster U.S. technological capabilities and counter Chinese progress. But making effective technology policy requires a clear understanding of how both countries got here, and what that means going forward.
#+END_QUOTE

然而，在过去的几年里，叙事已经发生了转变，任何对美国技术优势的自满情绪都烟消云散了。解释中国似乎无法创新的商业专栏已经让位于专栏警告，即中国在人工智能和5G 等战略技术方面有望超越美国。长期以来，华盛顿的政策制定者们一直满足于把技术留给硅谷，现在他们正在竞相寻找方法，以加强美国的技术能力，并对抗中国的进步。但是，制定有效的技术政策需要清楚地了解两国是如何走到这一步的，以及这意味着什么。

#+BEGIN_QUOTE
Traditional explanations for China's rise have focused heavily on the stealing of intellectual property. Although that has played a role, allowing Chinese manufacturers to crank out imitations of specific products, it is overly simplistic to imagine that intellectual property theft alone explains China’s rapid progress. In fact, that misconception deludes American policymakers into believing that all that is required to preserve the United States’ technological edge is to cut off China’s access to emerging technologies. The roots of China's technological takeoff are more complex, and formulating an effective U.S. policy response requires a solid grasp of emerging technologies and a degree of projective empathy—understanding how an ambitious Chinese bureaucrat is likely to view innovation and the range of tools available for encouraging it.
#+END_QUOTE

对中国崛起的传统解释主要集中在窃取知识产权上。尽管这起到了一定作用，使得中国制造商能够大量仿制特定产品，但如果认为盗窃知识产权本身就是中国迅速发展的原因，那就过于简单化了。事实上，这种错误观念误导了美国的政策制定者，使他们相信，要保持美国的技术优势，就必须切断中国获取新兴技术的渠道。中国技术腾飞的根源更为复杂，制定有效的美国政策回应需要对新兴技术的牢固把握和一定程度的投射性同理心ーー理解雄心勃勃的中国官员可能如何看待创新，以及可用于鼓励创新的各种工具。

* STATE INTERVENTION 国家干预

#+BEGIN_QUOTE
Any individual Chinese innovation is the product of creative thinking by hard-working technologists. At the micro level, these innovative processes look much the same in China as they do everywhere else. But explaining China’s technological rise at a macro level requires understanding the steps the Chinese government took to encourage the development of one of the world’s most dynamic innovation ecosystems.
#+END_QUOTE

中国的任何个人创新都是勤奋的技术人员创造性思维的产物。在微观层面上，这些创新过程在中国看起来与其他地方大同小异。但要从宏观层面解释中国的技术崛起，需要理解中国政府为鼓励发展全球最具活力的创新生态系统之一而采取的措施。

#+BEGIN_QUOTE
From a Chinese perspective, innovation is not a delicate or mysterious endeavor that can be accomplished only by special people, and it is certainly not something that must be shielded from government meddling. Instead, innovation is viewed as a social and economic process, one that can be guided and accelerated with the right mix of physical resources and bureaucratic resolve. Although China’s approach contradicts Silicon Valley’s deeply ingrained assumptions about the necessity of free markets and free speech, it has yielded more technological advances and commercial success than most American experts believed possible. In China, that process has involved three crucial steps.
#+END_QUOTE

从中国人的角度来看，创新不是只有特殊的人才能完成的微妙或神秘的努力，当然也不是必须避免政府干预的事情。相反，创新被视为一个社会和经济进程，可以通过物质资源和官僚决心的正确组合加以引导和加速。尽管中国的做法与硅谷关于自由市场和言论自由必要性的根深蒂固的假设背道而驰，但它带来的技术进步和商业成功，超出了大多数美国专家的想象。在中国，这一过程包括三个关键步骤。

#+BEGIN_QUOTE
The first step in that process, one that took place from 2000 to 2010, was for China to create a large, semiprotected market. Fostering a nascent innovation ecosystem required markets to be lucrative enough to fuel fierce competition, but it also required some degree of protection so that the established juggernauts of Silicon Valley did not come in and steamroll local startups before they could get off the ground. China achieved this balance by combining decades of breakneck economic growth with the creation of the Great Firewall, which blocks access to leading foreign online platforms such as Facebook and Google. The prospect of winning China's massive domestic market attracted huge capital investments from abroad and fostered fierce competition, but the Firewall also gave the local startups a fighting chance against their foreign competitors.
#+END_QUOTE

这个过程的第一步，从2000年到2010年，是中国建立一个大的、半保护的市场。培育一个新生的创新生态系统需要市场有足够的利润来推动激烈的竞争，但它也需要一定程度的保护，以便硅谷的老牌巨头不会在本土初创企业起步之前进入并摧毁它们。中国将数十年的高速经济增长与“防火长城”(Great Firewall)的建立结合起来，从而实现了这种平衡。“防火长城”屏蔽了对 Facebook 和谷歌(Google)等领先外国在线平台的访问。赢得中国庞大国内市场的前景吸引了来自海外的巨额资本投资，并促进了激烈的竞争，但防火墙也给了本土初创企业一个与外国竞争对手抗衡的机会。

#+BEGIN_QUOTE
Crucially, the Great Firewall was never rock solid. For most of the past two decades, the Firewall always remained somewhat porous, insulating the Chinese market from foreign competition but never fully isolating it from new ideas. Google, Facebook, and Twitter competed in China for years before being blocked. Less politically sensitive consumer platforms such as Airbnb, Uber, Amazon, and LinkedIn were never fully blocked; instead, they were beaten out by scrappy local startups. The Great Firewall’s porous nature allowed Chinese entrepreneurs, engineers, and scientists to stay up to date with leading technology trends and products without letting those products dominate the Chinese market. At the same time, the sheer size of China’s market kept foreign tech companies on their best behavior when interacting with the Chinese government, in the hopes that it would one day give them access to a billion new customers.
#+END_QUOTE

至关重要的是，防火长城从来都不是坚不可摧的。在过去20年的大部分时间里，防火墙一直保持着某种程度上的漏洞，将中国市场与外国竞争隔离开来，但从未完全将其与新想法隔离开来。谷歌、Facebook 和 Twitter 在被屏蔽之前已经在中国竞争了多年。政治上不那么敏感的消费者平台，如 Airbnb、Uber、Amazon 和 LinkedIn 从未被完全屏蔽；相反，它们被好斗的本地初创公司击败。防火长城漏洞百出的特性使得中国的企业家、工程师和科学家能够跟上领先的技术趋势和产品，而不会让这些产品主导中国市场。与此同时，中国市场的巨大规模使外国科技公司在与中国政府互动时保持最佳表现，希望有朝一日这能让它们接触到10亿新客户。

* U.S.-CHINESE COLLABORATION 美中合作

#+BEGIN_QUOTE
Those relationships were integral to the second, and most controversial, step in the process. For decades, China has maintained scientific and commercial ties to leading Western companies, universities, and labs—especially U.S. ones. These have ranged from professors at American universities collaborating with Chinese peers on public AI research to Chinese venture capitalists investing in Silicon Valley startups. Critics tend to view these ties as a vector for intellectual property theft, a foot in the door that has allowed Chinese spies to steal the “crown jewels of U.S. innovation,” as a 2018 Pentagon report put it. Industrial and scientific espionage have been a major problem, but the largest impact of these transpacific ties came not from stealing, but instead from learning. Exposure to world-class innovative processes gave China the intellectual fodder—the ideas, best practices, and operating models—that it needed to ignite its nascent tech ecosystem.
#+END_QUOTE

这些关系是不可或缺的第二步，也是最有争议的一步。几十年来，中国一直与领先的西方公司、大学和实验室保持着科学和商业联系，尤其是美国的公司。从与中国同行合作进行公共人工智能研究的美国大学教授，到投资于硅谷初创企业的中国风险投资家。批评人士倾向于将这些关系视为窃取知识产权的载体，正如五角大楼2018年的一份报告所指出的那样，这种关系是中国间谍窃取“美国创新皇冠上的明珠”的敲门砖。工业和科学间谍活动一直是一个主要问题，但这些跨太平洋关系的最大影响不是来自盗窃，而是来自学习。接触世界级的创新过程给了中国启动其新生的科技生态系统所需的知识素材ーー想法、最佳实践和运营模式。

#+BEGIN_QUOTE
Beginning around 2008, Chinese engineers who had worked at Google began returning to China to found their own startups, bringing some of Silicon Valley’s culture with them. Researchers at Chinese universities began collaborating more with their peers abroad, which exposed them to fresh approaches. Chinese tech companies studied their competitors in the United States and Europe, ingesting the latest tech trends and adapting them to the Chinese context. Most of these interactions were bottom-up, driven by technologists in both countries who wanted to work with and learn from one another. But the Chinese government also played an important role in chaperoning these relationships. It pushed for greater academic collaboration, and it dangled the carrot of market access before U.S. technology companies, encouraging them to open research centers in China.
#+END_QUOTE

大约从2008年开始，曾在谷歌工作过的中国工程师开始返回中国创建自己的初创企业，带来了一些硅谷文化。中国大学的研究人员开始更多地与国外同行合作，这让他们接触到了新的研究方法。中国的科技公司研究他们在美国和欧洲的竞争对手，吸收最新的科技趋势，并使之适应中国的情况。这些互动大多是自下而上的，由两国的技术专家驱动，他们希望与对方合作并相互学习。但中国政府也在维护这些关系方面发挥了重要作用。它推动更大的学术合作，并在美国科技公司面前晃动市场准入的胡萝卜，鼓励他们在中国开设研究中心。
