#+TITLE: The Chinese Way of Innovation
#+DATE: <2022-11-05 Sat 21:45>
#+TAGS[]: 他山之石

[[https://www.foreignaffairs.com/articles/china/2022-04-21/chinese-way-innovation][The Chinese Way of Innovation | Foreign Affairs]]（注册登录后，可见全文）

文章发表时间：April 26, 2022

作者是 [[https://carnegieendowment.org/experts/2116][Matt Sheehan]]（He is a fellow at the Carnegie Endowment for International Peace, where his research focuses on global technology issues, with a specialization in China’s artificial intelligence ecosystem. ）

#+BEGIN_QUOTE
For decades, many Americans derided China as a nation of copycats incapable of creativity, let alone breakthrough innovation. Authoritarianism and central planning were thought to be naturally inimical to fresh ideas. Rapid technological advancement, many in the United States believed, required the kind of fearless, “disruptive” thinking that was most at home in a freewheeling, democratic society.
#+END_QUOTE

几十年来，许多美国人嘲笑中国是一个没有创造力的山寨国家，更不用说突破性创新了。人们认为，威权主义和中央计划自然不利于新思想。许多美国人认为，快速的技术进步需要一种无畏的“破坏性”思维，这种思维在一个自由、民主的社会中最为常见。

#+BEGIN_QUOTE
Over the past several years, however, the narrative has shifted, and any complacency over U.S. technological superiority has evaporated. Business columns explaining China’s seeming inability to innovate have given way to op-eds warning that it is poised to surpass the United States in strategic technologies such as artificial intelligence and 5G. Policymakers in Washington who had long been content to leave technology up to Silicon Valley are now racing to find ways to bolster U.S. technological capabilities and counter Chinese progress. But making effective technology policy requires a clear understanding of how both countries got here, and what that means going forward.
#+END_QUOTE

然而，在过去的几年里，叙事已经发生了转变，任何对美国技术优势的自满情绪都烟消云散了。解释中国似乎无法创新的商业专栏已经让位于专栏警告，即中国在人工智能和5G 等战略技术方面有望超越美国。长期以来，华盛顿的政策制定者们一直满足于把技术留给硅谷，现在他们正在竞相寻找方法，以加强美国的技术能力，并对抗中国的进步。但是，制定有效的技术政策需要清楚地了解两国是如何走到这一步的，以及这意味着什么。

#+BEGIN_QUOTE
Traditional explanations for China's rise have focused heavily on the stealing of intellectual property. Although that has played a role, allowing Chinese manufacturers to crank out imitations of specific products, it is overly simplistic to imagine that intellectual property theft alone explains China’s rapid progress. In fact, that misconception deludes American policymakers into believing that all that is required to preserve the United States’ technological edge is to cut off China’s access to emerging technologies. The roots of China's technological takeoff are more complex, and formulating an effective U.S. policy response requires a solid grasp of emerging technologies and a degree of projective empathy—understanding how an ambitious Chinese bureaucrat is likely to view innovation and the range of tools available for encouraging it.
#+END_QUOTE

对中国崛起的传统解释主要集中在窃取知识产权上。尽管这起到了一定作用，使得中国制造商能够大量仿制特定产品，但如果认为盗窃知识产权本身就是中国迅速发展的原因，那就过于简单化了。事实上，这种错误观念误导了美国的政策制定者，使他们相信，要保持美国的技术优势，就必须切断中国获取新兴技术的渠道。中国技术腾飞的根源更为复杂，制定有效的美国政策回应需要对新兴技术的牢固把握和一定程度的投射性同理心ーー理解雄心勃勃的中国官员可能如何看待创新，以及可用于鼓励创新的各种工具。

* STATE INTERVENTION 国家干预

#+BEGIN_QUOTE
Any individual Chinese innovation is the product of creative thinking by hard-working technologists. At the micro level, these innovative processes look much the same in China as they do everywhere else. But explaining China’s technological rise at a macro level requires understanding the steps the Chinese government took to encourage the development of one of the world’s most dynamic innovation ecosystems.
#+END_QUOTE

中国的任何个人创新都是勤奋的技术人员创造性思维的产物。在微观层面上，这些创新过程在中国看起来与其他地方大同小异。但要从宏观层面解释中国的技术崛起，需要理解中国政府为鼓励发展全球最具活力的创新生态系统之一而采取的措施。

#+BEGIN_QUOTE
From a Chinese perspective, innovation is not a delicate or mysterious endeavor that can be accomplished only by special people, and it is certainly not something that must be shielded from government meddling. Instead, innovation is viewed as a social and economic process, one that can be guided and accelerated with the right mix of physical resources and bureaucratic resolve. Although China’s approach contradicts Silicon Valley’s deeply ingrained assumptions about the necessity of free markets and free speech, it has yielded more technological advances and commercial success than most American experts believed possible. In China, that process has involved three crucial steps.
#+END_QUOTE

从中国人的角度来看，创新不是只有特殊的人才能完成的微妙或神秘的努力，当然也不是必须避免政府干预的事情。相反，创新被视为一个社会和经济进程，可以通过物质资源和官僚决心的正确组合加以引导和加速。尽管中国的做法与硅谷关于自由市场和言论自由必要性的根深蒂固的假设背道而驰，但它带来的技术进步和商业成功，超出了大多数美国专家的想象。在中国，这一过程包括三个关键步骤。

#+BEGIN_QUOTE
The first step in that process, one that took place from 2000 to 2010, was for China to create a large, semiprotected market. Fostering a nascent innovation ecosystem required markets to be lucrative enough to fuel fierce competition, but it also required some degree of protection so that the established juggernauts of Silicon Valley did not come in and steamroll local startups before they could get off the ground. China achieved this balance by combining decades of breakneck economic growth with the creation of the Great Firewall, which blocks access to leading foreign online platforms such as Facebook and Google. The prospect of winning China's massive domestic market attracted huge capital investments from abroad and fostered fierce competition, but the Firewall also gave the local startups a fighting chance against their foreign competitors.
#+END_QUOTE

这个过程的第一步，从2000年到2010年，是中国建立一个大的、半保护的市场。培育一个新生的创新生态系统需要市场有足够的利润来推动激烈的竞争，但它也需要一定程度的保护，以便硅谷的老牌巨头不会在本土初创企业起步之前进入并摧毁它们。中国将数十年的高速经济增长与“防火长城”(Great Firewall)的建立结合起来，从而实现了这种平衡。“防火长城”屏蔽了对 Facebook 和谷歌(Google)等领先外国在线平台的访问。赢得中国庞大国内市场的前景吸引了来自海外的巨额资本投资，并促进了激烈的竞争，但防火墙也给了本土初创企业一个与外国竞争对手抗衡的机会。

#+BEGIN_QUOTE
Crucially, the Great Firewall was never rock solid. For most of the past two decades, the Firewall always remained somewhat porous, insulating the Chinese market from foreign competition but never fully isolating it from new ideas. Google, Facebook, and Twitter competed in China for years before being blocked. Less politically sensitive consumer platforms such as Airbnb, Uber, Amazon, and LinkedIn were never fully blocked; instead, they were beaten out by scrappy local startups. The Great Firewall’s porous nature allowed Chinese entrepreneurs, engineers, and scientists to stay up to date with leading technology trends and products without letting those products dominate the Chinese market. At the same time, the sheer size of China’s market kept foreign tech companies on their best behavior when interacting with the Chinese government, in the hopes that it would one day give them access to a billion new customers.
#+END_QUOTE

至关重要的是，防火长城从来都不是坚不可摧的。在过去20年的大部分时间里，防火墙一直保持着某种程度上的漏洞，将中国市场与外国竞争隔离开来，但从未完全将其与新想法隔离开来。谷歌、Facebook 和 Twitter 在被屏蔽之前已经在中国竞争了多年。政治上不那么敏感的消费者平台，如 Airbnb、Uber、Amazon 和 LinkedIn 从未被完全屏蔽；相反，它们被好斗的本地初创公司击败。防火长城漏洞百出的特性使得中国的企业家、工程师和科学家能够跟上领先的技术趋势和产品，而不会让这些产品主导中国市场。与此同时，中国市场的巨大规模使外国科技公司在与中国政府互动时保持最佳表现，希望有朝一日这能让它们接触到10亿新客户。

* U.S.-CHINESE COLLABORATION 美中合作

#+BEGIN_QUOTE
Those relationships were integral to the second, and most controversial, step in the process. For decades, China has maintained scientific and commercial ties to leading Western companies, universities, and labs—especially U.S. ones. These have ranged from professors at American universities collaborating with Chinese peers on public AI research to Chinese venture capitalists investing in Silicon Valley startups. Critics tend to view these ties as a vector for intellectual property theft, a foot in the door that has allowed Chinese spies to steal the “crown jewels of U.S. innovation,” as a 2018 Pentagon report put it. Industrial and scientific espionage have been a major problem, but the largest impact of these transpacific ties came not from stealing, but instead from learning. Exposure to world-class innovative processes gave China the intellectual fodder—the ideas, best practices, and operating models—that it needed to ignite its nascent tech ecosystem.
#+END_QUOTE

这些关系是不可或缺的第二步，也是最有争议的一步。几十年来，中国一直与领先的西方公司、大学和实验室保持着科学和商业联系，尤其是美国的公司。从与中国同行合作进行公共人工智能研究的美国大学教授，到投资于硅谷初创企业的中国风险投资家。批评人士倾向于将这些关系视为窃取知识产权的载体，正如五角大楼2018年的一份报告所指出的那样，这种关系是中国间谍窃取“美国创新皇冠上的明珠”的敲门砖。工业和科学间谍活动一直是一个主要问题，但这些跨太平洋关系的最大影响不是来自盗窃，而是来自学习。接触世界级的创新过程给了中国启动其新生的科技生态系统所需的知识素材ーー想法、最佳实践和运营模式。

#+BEGIN_QUOTE
Beginning around 2008, Chinese engineers who had worked at Google began returning to China to found their own startups, bringing some of Silicon Valley’s culture with them. Researchers at Chinese universities began collaborating more with their peers abroad, which exposed them to fresh approaches. Chinese tech companies studied their competitors in the United States and Europe, ingesting the latest tech trends and adapting them to the Chinese context. Most of these interactions were bottom-up, driven by technologists in both countries who wanted to work with and learn from one another. But the Chinese government also played an important role in chaperoning these relationships. It pushed for greater academic collaboration, and it dangled the carrot of market access before U.S. technology companies, encouraging them to open research centers in China.
#+END_QUOTE

大约从2008年开始，曾在谷歌工作过的中国工程师开始返回中国创建自己的初创企业，带来了一些硅谷文化。中国大学的研究人员开始更多地与国外同行合作，这让他们接触到了新的研究方法。中国的科技公司研究他们在美国和欧洲的竞争对手，吸收最新的科技趋势，并使之适应中国的情况。这些互动大多是自下而上的，由两国的技术专家驱动，他们希望与对方合作并相互学习。但中国政府也在维护这些关系方面发挥了重要作用。它推动更大的学术合作，并在美国科技公司面前晃动市场准入的胡萝卜，鼓励他们在中国开设研究中心。

#+BEGIN_QUOTE
Once the market conditions and international connections were in place, China took the third step, unleashing a wave of resources: investment capital, physical infrastructure, trained engineers, and bureaucratic energy. From an American vantage point, this investment appeared wasteful and even counterproductive, since it violated the sacred precept that governments should never pick winners. On the ground in China, however, it proved to be an effective method for accelerating the diffusion and commercialization of technology.
#+END_QUOTE

一旦市场条件和国际联系到位，中国就迈出了第三步，释放出一波资源：投资资本、有形基础设施、训练有素的工程师和官僚能源。从美国的角度来看，这种投资似乎是浪费，甚至适得其反，因为它违反了政府永远不应挑选赢家的神圣信条。然而，在中国，这被证明是一种加速技术扩散和商业化的有效方法。

#+BEGIN_QUOTE
The Chinese government’s 2017 artificial intelligence initiative, for example, set an ambitious goal: making China the world’s preeminent AI hub by 2030. But its biggest impact was a wave of experimentation and activity across the Chinese bureaucracy and private sector. Mayors built sparkling new AI startup accelerators in their cities. Agricultural officials created pilot programs for smart fertilizer drones. Public hospitals partnered with universities to create medical AI research institutes. And police departments across the country spent lots and lots of money purchasing surveillance technology.
#+END_QUOTE

例如，中国政府2017年的人工智能计划设定了一个雄心勃勃的目标：到2030年使中国成为全球首屈一指的人工智能中心。但其最大的影响是，中国官僚机构和私营部门掀起了一波试验和活动的浪潮。市长们在他们的城市建立了崭新的人工智能启动加速器。农业官员为智能化肥无人机制定了试点项目。公立医院与大学合作建立医学人工智能研究机构。全国各地的警察部门花费了大量金钱购买监控技术。

#+BEGIN_QUOTE
Considered individually, many of these projects appeared laughably wasteful. Startup incubators in backwater towns often sat empty for years. But these scattered government efforts helped fuel an AI boom in the private sector, stimulating even greater venture investment and startup formation. In 2018, China accounted for nearly half of all global funding for AI startups, surpassing the United States. These funds allowed Chinese companies and scientists to experiment with new products, features, and approaches, and turbocharged AI adoption across the economy.
#+END_QUOTE

从个人角度来看，这些项目中的许多看起来都是可笑的浪费。落后城镇的创业孵化器常常空置多年。但这些分散的政府努力帮助推动了私营部门的人工智能繁荣，刺激了更多的风险投资和初创企业的形成。2018年，中国超过美国，占全球人工智能初创企业融资总额的近一半。这些基金使中国企业和科学家得以试验新产品、新功能和新方法，并在整个经济领域推动人工智能的应用。

#+BEGIN_QUOTE
By building and protecting its markets while learning from global innovation ecosystems, China ultimately accelerated its own development of key technologies. That success wasn't all the result of some perfectly executed master plan. Instead, it was the product of ideological paranoia, smart planning, a lot of hard work, and a bit of good luck. China originally built the Great Firewall to protect its highly censored information environment and only later stumbled into the innovation benefits. Although China’s intentions were mixed and sometimes self-contradictory, its end results exceeded almost anyone’s expectations.
#+END_QUOTE

通过建立和保护市场，同时学习全球创新生态系统，中国最终加快了自身关键技术的发展。这个成功并不全是某个完美执行的总体计划的结果。相反，它是意识形态偏执、精明计划、大量艰苦工作和一点点好运的产物。中国最初建立长城防火墙是为了保护其高度审查的信息环境，后来才偶然发现创新的好处。尽管中国的意图好坏参半，有时甚至自相矛盾，但其最终结果超出了几乎所有人的预期。

* AMERICAN OVERREACTION 美国人的过度反应

#+BEGIN_QUOTE
Over the past four years, Washington has focused on cutting off China’s connections to the American technological ecosystem. Some of these initiatives have had real strategic value, such as the targeted controls that have prevented China from manufacturing cutting-edge semiconductors. But many of these efforts have been strategic blunders that undercut U.S. innovation and fed China’s rise. Misguided prosecutions of Chinese-born scientists at American universities have sent a chill through the foreign-born scientific community and have driven some of its best and brightest minds to return to China out of fear. More fundamentally, the era in which the United States could stop China's rise simply by cutting it off has largely passed. If the United States had cut technological ties with China in 2005, it might have slowed global innovation and hampered the United States’ own capabilities, but it probably would have hurt China more. At that point, China did not have a self-sustaining domestic technological ecosystem and bootstrapping one by itself would have taken far more time.
#+END_QUOTE

在过去的四年里，华盛顿一直致力于切断中国与美国技术生态系统的联系。其中一些举措具有真正的战略价值，例如阻止中国制造尖端半导体的有针对性的控制措施。但是，这些努力中的许多都是战略失误，削弱了美国的创新，助长了中国的崛起。美国大学对中国出生的科学家的误导性起诉，让外国出生的科学界感到不寒而栗，并迫使一些最优秀、最聪明的科学家出于恐惧回到中国。更为根本的是，美国仅仅通过切断中国的崛起就能阻止中国崛起的时代基本上已经过去了。如果美国在2005年切断与中国的技术联系，可能会减缓全球创新，阻碍美国自身的能力，但这可能会对中国造成更大的伤害。在那个时候，中国还没有一个自给自足的国内技术生态系统，要想自己建立一个这样的生态系统需要花费更多的时间。

#+BEGIN_QUOTE
China today already has most of the raw ingredients for technological success, and the haphazard cutting of bilateral ties would likely be counterproductive. Instead, the United States should take targeted action to maintain Chinese dependence on foreign technology while continuing to attract and engage with Chinese innovators. For maintaining that dependence, the best point of leverage is semiconductors, specifically the highly specialized manufacturing equipment that is produced only by a handful of U.S. allies. For attracting Chinese talent, America's universities act as a powerful magnet for high-end researchers, but reforms to the U.S. immigration system are urgently needed to keep those people in the country after graduation.
#+END_QUOTE

如今，中国已经拥有技术成功的大部分原材料，随意切断双边关系可能会适得其反。相反，美国应该采取有针对性的行动，维持中国对外国技术的依赖，同时继续吸引和接触中国的创新者。为了保持这种依赖性，最好的筹码是半导体，特别是只有少数美国盟友生产的高度专业化的制造设备。为了吸引中国人才，美国的大学成为吸引高端研究人员的强大磁石，但美国移民制度的改革迫切需要，以便让这些人毕业后留在美国。

#+BEGIN_QUOTE
Can the United States learn anything from China when it comes to accelerating its own tech ecosystem? The two countries have such drastically different systems of government that simply copying the Chinese model is impossible. The Trump administration’s attempt to block the Chinese apps WeChat and TikTok were blocked by the courts. And mayors across the United States will not suddenly start creating pilot programs for autonomous drones on the federal government’s orders. But there is a deeper lesson to be learned. If the United States hopes to maintain its edge over China, the U.S. government must be willing to experiment with new ways of incentivizing technology development, even if some efforts result in wasted funds or fail entirely. If every failed project becomes a partisan bludgeon, then innovation policy will grind to a halt.
#+END_QUOTE

美国能从中国身上学到什么，来加速自己的科技生态系统吗？两国的政府体制截然不同，不可能简单地照搬中国模式。特朗普政府试图屏蔽中国应用程序微信(WeChat)和 TikTok 的努力被法院屏蔽。而且美国各地的市长也不会突然开始按照联邦政府的命令为自主无人机创建试点项目。但还有更深层次的教训需要学习。如果美国希望保持其相对于中国的优势，美国政府必须愿意尝试新的激励技术发展的方式，即使一些努力导致资金浪费或完全失败。如果每个失败的项目都成为党派的大棒，那么创新政策就会陷入停滞。

#+BEGIN_QUOTE
The congressional proposal to create a “technology directorate” in the National Science Foundation—a new division empowered to connect academia, government, and industry to accelerate deployment of commercial technology—offers a promising start for this kind of experimentation. The resources and scope of the technology directorate have been the subject of intense debate in Congress and will be decided as the House and Senate attempt to reconcile their competing bills in the months ahead. The proposed directorate is a far cry from China’s “flood the zone” approach to catalyzing technology development. But its emergence suggests that the U.S. government is beginning to recognize that it can no longer afford to simply fund basic research and leave the rest up to the markets.
#+END_QUOTE

国会提议在美国国家科学基金会(National Science Foundation)内设立一个“技术董事会”，为这类实验提供了一个良好的开端。国家科学基金会是一个新的部门，有权将学术界、政府和工业界联系起来，以加速商业技术的应用。技术董事会的资源和规模一直是国会激烈辩论的主题，将在未来几个月内由参众两院试图调和彼此竞争的法案时作出决定。拟议中的董事会与中国催化技术发展的“洪水区”方式相去甚远。但它的出现表明，美国政府已经开始认识到，它不能再仅仅为基础研究提供资金，而将其余的资金留给市场。

#+BEGIN_QUOTE
No single bill or innovative policy will be enough to ensure the United States maintains its edge in technology. If China’s trajectory teaches American leaders anything, it is that stimulating technological innovation can be a messy, muddled, and often contradictory process. Given the stakes of this competition, the United States cannot let that messiness cause paralysis.
#+END_QUOTE

任何单一的法案或创新政策都不足以确保美国保持其技术优势。如果说中国的发展轨迹给了美国领导人什么启示的话，那就是，刺激技术创新可能是一个混乱、混乱、往往相互矛盾的过程。考虑到这场竞争的利害关系，美国不能让这种混乱局面导致瘫痪。
