#+TITLE: 【读书记8】格（杂志） by 随机波动
#+DATE: <2025-10-01 Wed 12:00>
#+TAGS[]: 读书记


更确切的称呼是 MOOK（Magazine Book，杂志书）。

随机波动（曾用名：剩余价值）是由三位女性媒体人发起的一档泛文化类播客。

这本设计感十足的杂志是她们在2024年2月推出的。

我对这本书的感受：

我已经很久没用手触摸纸质书了。收到书的那天，我还在上家公司上班，拿书的时候是午休时间，旁人或是睡觉或是刷手机，唯独我在这本杂志书上摸索，阅读其中的文字，用心感受着手指划过书页。我沉浸其中，旁若无人，唯有心声和翻书声。

当再次拿起这本书，我决定把其中的视觉部分看完，各种意象：格子、树影、楼宇、方舱、围棋、乐园、自然、珍图、贝壳、蜂鸟、麦鸡、柜子、神灵、罪人、天堂、碎片、世界、环球、旅行、城市、规划、纽约、捉奸、隔离、渔网、风铃、女子、缝衣、手工、永动、丝路、蓝天、白云、标线、插座、座机、拨盘、iPhone、像素、粉色、出格、囤粮、末日、生存、徒步、宠物、桌布、家庭、遐想。

丰富的意象，无尽的想象。给即将归于平稳的我的生活，带来一些波澜，重新思考起——我想要怎样的人生？

** 卷首语

[[https://mermaid.ink/img/pako:eNqrVkrOT0lVslJKy8kvT85ILCpR8AmKyVMAAsfoF_snvtg_53FD49PW7U_2Tn7WtffFxoWxCrq6dgpO0c8W7Hm6dkIsRK0TWNA5-mnrxqcds6GCzmBBl-gXy9teLO-ECjqCBV2jn81Z82TnsmcdE57O60YxBKuUM24pF1xSSjpKualFuYmZKUDvVYNEYpRKMlJzU2OUrIDMlMSi7BilmLxaoLrE0pL84Mq8ZCWrkqLSVB2lovzS9AwYp7QgJbEk1SUzMb0oMRcmmJqSWZJf5AsJO3AQ1gIAe7SELA?type=png][![]]](https://mermaid.live/edit#pako:eNqrVkrOT0lVslJKy8kvT85ILCpR8AmKyVMAAsfoF_snvtg_53FD49PW7U_2Tn7WtffFxoWxCrq6dgpO0c8W7Hm6dkIsRK0TWNA5-mnrxqcds6GCzmBBl-gXy9teLO-ECjqCBV2jn81Z82TnsmcdE57O60YxBKuUM24pF1xSSjpKualFuYmZKUDvVYNEYpRKMlJzU2OUrIDMlMSi7BilmLxaoLrE0pL84Mq8ZCWrkqLSVB2lovzS9AwYp7QgJbEk1SUzMb0oMRcmmJqSWZJf5AsJO3AQ1gIAe7SELA)

#+BEGIN_QUOTE
一切都是那样新鲜，一切都是那样困难。

————冷建国（黄月）
#+END_QUOTE

** 何谓“格子”

格子中套格子——城市->区域->街区->楼群->单元->家庭or办公

格子中的人近在咫尺又远在天涯。

单面人

** 棋类、博弈和人工智能 by 李喆

棋手与棋子是人与物的关系，是主体与客体的关系。如果把人比作棋子，那么棋手只能是超越于人的抽象存在，不能是人自身。前现代文明中的皇权和神权近乎这种抽象存在，而现代文明的一个特点是在观念和政治实践中消解了它们，尽管它们还存在于传统的文化土壤之中。

另一种隐喻呼之欲出了。围棋没有将帅兵卒的天生价值差异，每个棋子不分强弱，落在棋盘上不多不少就占一个交叉点，落子的优劣完全取决于它与其他棋子的关联，或者说“结构”。由此，关于平等、联结与合作的隐喻或许会生长出来：

棋子的意义，只有在与其他棋子不同形式的联结中才得以显现。世界与棋局一般无法预知，当意外来临，我们在绝望面前所能秉持的，除了知识和直面真实的勇气，就只有爱——或者说，人与人之间平等自愿的联结。

** 参考资料

- [[https://www.moma.org/s/lb/collection_lb/objbytag/objbytag_tag-vo98440_sov.html][Ode à l'Oubli]] by Louise Bourgeois


2025年读完的第8本,总阅读量第8本