#+TITLE: 【读书记12】可能性的艺术 by 刘瑜
#+DATE: <2025-10-11 Sat 12:00>
#+TAGS[]: 读书记


#+BEGIN_QUOTE
什么是社会科学的洞察力？它首先是把熟悉的事物陌生化的能力，把句号变成问号的能力，把“此时此刻”和无数“他时他刻”联系起来的能力。这种能力和每个人的敏感性有关，但是，也和每个人的“见识”有关——也就是说，你阅读过的、听过的、走过的、观察过的、思考过的越多，你就越容易把现实当作“一万种可能性之一”来对待。如果你是一个井底之蛙，那么你就永远无法获得那个反观自身的视角，甚至还可能因为这种狭隘而狂妄自大。
#+END_QUOTE

#+BEGIN_QUOTE
“政治是可能性的艺术”​，​“Politics is the art of thepossible”​。其中，​“the possible”这个词非常重要，为什么？因为它的本意正是强调政治不是魔术，它不能抵达“the impossible”​，它不能做成无米之炊，它不能让水变成油，它不能发明永动机。
#+END_QUOTE

#+BEGIN_QUOTE
比较政治学思考的核心任务：在差异中寻找规律
#+END_QUOTE

#+BEGIN_QUOTE
社会科学的思考就像是开车，需要时刻警觉，时刻观察路况，并根据路况随时调整速度和方向。一刹那间的走神，就可能导致车毁人亡。这听上去的确很累，但也是唯一安全的做法。世界是复杂的，但又不是随机的，知识也应当如此。求知的道路，意味着永恒的疲倦以及偶尔的惊喜。
#+END_QUOTE

皇权统治 读书人 驯化 科举制

国家能力 中央集权 社会变革

美国 反国家主义

不是国家的国家

民主稳固 vs 民主转型

改革热情和服从意识

平庸之恶

理性的无知

主动作恶，被动作恶

who is nobody, to become somebody, join the evil game

政治文化的冲突——当今社会的分歧所在。 the West vs the Rest

** 序言 可能性的艺术：通过比较理解政治

#+BEGIN_QUOTE
什么是社会科学的洞察力？它首先是把熟悉的事物陌生化的能力，把句号变成问号的能力，把“此时此刻”和无数“他时他刻”联系起来的能力。这种能力和每个人的敏感性有关，但是，也和每个人的“见识”有关——也就是说，你阅读过的、听过的、走过的、观察过的、思考过的越多，你就越容易把现实当作“一万种可能性之一”来对待。如果你是一个井底之蛙，那么你就永远无法获得那个反观自身的视角，甚至还可能因为这种狭隘而狂妄自大。
#+END_QUOTE

#+BEGIN_QUOTE
“政治是可能性的艺术”​，​“Politics is the art of thepossible”​。其中，​“the possible”这个词非常重要，为什么？因为它的本意正是强调政治不是魔术，它不能抵达“the impossible”​，它不能做成无米之炊，它不能让水变成油，它不能发明永动机。
#+END_QUOTE

#+BEGIN_QUOTE
比较政治学思考的核心任务：在差异中寻找规律
#+END_QUOTE

#+BEGIN_QUOTE
社会科学的思考就像是开车，需要时刻警觉，时刻观察路况，并根据路况随时调整速度和方向。一刹那间的走神，就可能导致车毁人亡。这听上去的确很累，但也是唯一安全的做法。世界是复杂的，但又不是随机的，知识也应当如此。求知的道路，意味着永恒的疲倦以及偶尔的惊喜。
#+END_QUOTE

** 韩国电影中的革命：观念的水位与制度的变迁

#+BEGIN_QUOTE
自发的买卖行为，在自由主义的观念下，叫“市场交换”，但是在极左观念下叫什么？“投机倒把”。明明是同一件事，在两个观念体系里，听上去会成为道义上截然相反的事情。又比如，一个私营企业家投资挣钱了，在自由市场的观念下叫“投资盈利”，但是在左翼的观念下叫什么？叫作“剥削剩余价值”。仍然是同一件事，被两个不同的话语体系诠释成了褒贬相反的事情。这就是观念的力量——它是我们吸收信息的“意义加工软件”。
#+END_QUOTE

#+BEGIN_QUOTE
所谓启蒙，未必是把一个外来的什么思想塞到我们的脑子里，而是用一盏灯把本来就是我们心灵深处里的东西给照亮而已。
#+END_QUOTE

和邵亦波提及的找回自己内心本就有的东西，挺像的

#+BEGIN_QUOTE
到最后，我发现，这种源于道德直觉的正义感有种令人敬畏的天真。你会发现，当所有政治的泥沙沉淀、所有理论的波涛平息、所有流行的趋势过去，最终，这种无与伦比的天真还是会从水底浮现。它熠熠的光芒，还是会诱惑你向它伸出手去。
#+END_QUOTE

** 新镀金时代？不平等的幽灵(1)

#+BEGIN_QUOTE
一旦一个社会高度不平等，哪怕它采用了民主的外衣，依然可能会沦为寡头统治。
#+END_QUOTE

#+BEGIN_QUOTE
有一种常见的看法是，在公平和效率之间，只能二选一，为了效率，就不得不牺牲公平。也许在经济发展的初级阶段，这话有一定道理，毕竟，资源极度稀缺时，把有限的资源用于再分配，就意味着投资的枯竭，经济发展失去动力。
#+END_QUOTE

#+BEGIN_QUOTE
边际消费倾向递减趋势
#+END_QUOTE

#+BEGIN_QUOTE
政府很怕疫情暴发后，人们因为缺钱而消费锐减，结果就是经济发展失去动力。
#+END_QUOTE

#+BEGIN_QUOTE
在这个意义上，现代政治虽然比古代更平等，但是却更脆弱了，因为人们不是根据自己的绝对处境，而是根据“相对剥夺感”而采取政治行动的。
#+END_QUOTE

如果被剥夺得太厉害,人们就要起义为自己争取权利

** 新镀金时代？不平等的幽灵(2)

#+BEGIN_QUOTE
我们真正想要的，不是“向下的平等”，而是“向上的平等”，不是把上面的人拉下来，而是把下面的人拉上去。而在“向上的平等”中，平等就必须和其他价值并存：自由、秩序、创新、责任感，等等。
#+END_QUOTE

#+BEGIN_QUOTE
我们希望那些年轻的保安、快递、保洁中被埋没的科学家、艺术家、企业家能够有机会实现自我，但我们也害怕过于均等的社会让潜在的科学家、艺术家、企业家失去奋斗的激励机制
#+END_QUOTE

** 政治的可能与不可能

#+BEGIN_QUOTE
“政治是可能性的艺术”，表达的正是这种政治现实主义主张。据说，这句话的完整表述是这样的：“Politics is the art of the possible,the attainable - the art of the next best.”政治是可能性的艺术、可行性的艺术，是次优的艺术。这个完整说法，更清晰地呈现了它的“政治现实主义”指向。
#+END_QUOTE

#+BEGIN_QUOTE
政治创造可能，但是政治亦有其边界
#+END_QUOTE

#+BEGIN_QUOTE
当观念的水位太低，所谓宪法就成了一张随时可以撕掉的废纸而已。
#+END_QUOTE

#+BEGIN_QUOTE
真正的政治变革不可能仅靠自上而下的力量推动，它必须同时自下而上地生长。在人们学会宽容、学会耐心、学会同情性理解、学会从各种集体主义的轮椅中站起来迈出个体的步伐之前，没有什么政治可以成为改造生活的魔法棒。好的政治给每个人一张船票，但是它无法也不应该把每个人带到他的目的地
#+END_QUOTE

#+BEGIN_QUOTE
恰恰是知识的不确定性，让我们需要在每一个时代、每一个情境中不断重返基本的道德问题和历史经验，用我们自己的头脑思考，并以这种思考成就人之为人的尊严。
#+END_QUOTE


@@html:<span style="color:var(--dushuji-count-color)">2025年读完的第12本，总阅读量第12本</span>@@