#+TITLE: 【读书记15】你是你吃出来的1&2 by 夏萌
#+DATE: <2025-10-15 Wed 12:00>
#+TAGS[]: 读书记


当看到化验单上总胆固醇高时，我们要去看低密度脂蛋白胆固醇。如果低密度脂蛋白胆固醇旁边有个向上的箭头时，我们至少要知道三点：第一，来源于肝脏的胆固醇合成比较多，说明肝脏功能还不错；第二，身体对于胆固醇的需求没有得到满足，尤其是对血管内皮、动脉壁平滑肌、肌肉组织、肾上腺素等组织器官要多关注；第三，吃进去的胆固醇可能不够。

胆固醇存在于动物性食物中，比如，鸡蛋、肉、内脏，不存在于植物性食物中

计算食物的胆固醇，一般人每天摄入300-500mg胆固醇，

- 一个鸡蛋-250mg
- 100g瘦肉-70mg
- 100g内脏-200mg

肥胖型高血压患者要减轻体重，主要是降低每日热量的摄入，辅以适当的运动，让消耗的总能量大于摄入的总能量。如果同时限制钠的摄入，可使降压效果更为明显。减体重的过程中，要充分认识到肥胖的危害，循序渐进，切忌急于求成。

当情绪紧张时，肾上腺素分泌会增多，交感神经会兴奋，这样会提高心脏的收缩力，并使外周血管收缩，导致血压高。

如何减少胰腺β细胞的负担呢？

第一，每一餐摄入的碳水化合物要少，可以少吃多餐，也可以用混合食物降低升糖指数。

第二，多给胰腺β细胞提供修复自己的原料——蛋白质、磷脂、胆固醇，饮食中增加鱼、蛋、肉、奶的比例。

第三，帮助胰岛素消耗多余的血糖。多运动可以增加肌肉上胰岛素受体的灵敏度，使细胞更多地消耗葡萄糖，肌肉里贮存葡萄糖的能力也有所增强。

如果我们总是吃一些升糖很快的食物，比如馒头、米饭、面包，进食后就需要很多胰岛素迅速把这些血糖处理掉，吃得越多，胰岛素分泌越多。如果三顿饭都是高碳水化合物饮食，又没有有效的运动消耗过多的葡萄糖，血液中的葡萄糖含量就会增高。而血液中的葡萄糖越多，胰腺β细胞生产胰岛素就越努力，负担也越大。

长此以往，胰腺β细胞不堪重负，就会慢慢出现胰岛素分泌不足的情况，再不注意，就会发展成糖尿病。

如果这一天一直没有吃东西，第二天血糖依然在正常范围，这是怎么回事呢？正常成年人每小时可以由肝脏释放出葡萄糖210克/千克，如果没有及时从食物中补充一些进来，十几小时左右肝糖原就会被耗尽，之后人体会通过糖异生途径获得葡萄糖。

** 甲状腺

当一个人吃含碘的食物和蛋白质类食物不足时，甲状腺细胞合成T3、T4的原料减少，上级领导一道一道的命令下达，不仅促进甲状腺激素的合成，还会促进甲状腺细胞的恶性增生。此时做B超的话会显示出甲状腺多发结节，化验检查T3、T4正常，而TSH增加。


@@html:<span style="color:var(--dushuji-count-color)">2025年读完的第15本，总阅读量第15本</span>@@