#+TITLE: 参与2024中国开源年会
#+DATE: <2024-11-04 Mon 22:55>
#+TAGS[]: 随笔

作为COScon'24项目工作组的一员，年会从开始筹备时，我就在群组里，本来没打算线下参与。只是想着这次年会先了解一下整个的流程，待到明年年会时再线下贡献。直到上个月月末的29号，那天我记得是在上午，我坐在工位上，仿佛受到了刺激一般，一种强烈的欲望涌上心头——我想参加这次年会，我想和大家见面。

线上经常会和基础设施组的小伙伴们聊天，但有几位线下还没见过面，比如yiwei、基印、大鹏、陈玄。水歌、文超和止戈在freeCodeCamp 2023广州聚会时见过。除此之外，还见到了Corrie、月饼、萱萱、居居和佳欣，大家都很nice，自由表达对事情的看法。很庆幸自己这次选择线下参与，我收获了更紧密的友谊以及更清晰的自我认知。

* 会议前

10月31日晚上八点半下班，之后公交地铁来到福田站，这时已经十点多了，傍晚时没怎么吃东西，也比较饿，就在附近找吃的。地处深圳市中心，附近都是高楼大厦，我觉得不自在。找了半天只找到一家麦当劳，点了套餐边吃便继续看《星际迷航》系列。吃麦当劳的时候遇到一位外国小哥，拿着百元纸币付款，但工作人员表示那个时间已经收不了了。小哥双手合十，离开了。当时我坐在那里看着他，有一种请他这顿的冲动，但最后还是没有请。如果请了我相信肯定会有意想不到的收获。

吃了以后，就准备下去在火车站过夜，没想到人家已经关门了，地铁站也快关门了，保安小哥告诉我不能在这里过夜，我就又返回地面。

11月1日凌晨从福田站出来后，我想找一个24h开放的地方，就瞄到了图书馆附近的24h书吧，在那里我趴在桌子上很冷地趴了四个小时，睡着了醒来、醒来又继续睡。还好这里有插座可以给手机充电。

4:37 从书吧出来，到达福田站一个入口时将近五点，恰好开门。又见到几小时前告诉我地铁站不能过夜的保安小哥，问他在哪里可以吃早餐，就在地铁站的喜乐多便利店买了一个三明治和茶叶蛋。

6:30 坐上高铁，还是睡了醒、醒了睡。中午吃了火车套餐。当到北京时已然傍晚六点。出了车厢，感到了北京深秋的凉意，只穿T-shirt的我感到冷。我不是第一次来北京，也不是第一次到北京西站，可是我已经不记得它的样子了。还记得我[[/posts/first-time-in-beijing/][第一次到北京]]，带着一丝幻想，走马观花似的溜过了北京的一些地方，可是依旧给了我很深的印象。

七点多到酒店，放好东西出去吃了碗红烧牛肉面，此时和止戈联系说要吃饭。但因为面很快会凉，我就先吃完了。待到我回酒店房间，给止戈发消息，他说他已经到了，其他人也到了。又去吃饭，十一点多才回来。

司机送我到酒店时谈的那些内容，让我深思：人们生活得不幸福，但科技发展的步伐不会停滞。在科技发展的当下，不要太过逻辑思考，人情味是很重要的东西。

吃饭之前，我只接触基础设施组的小伙伴们，对开源社的其他小组没有了解；吃饭之后，我了解了更多的事情，也认识了更多的朋友。我认识到一个新的开源社，更加全面的开源社。我有些害怕了，因为我不愿意处理复杂的人际关系。

我一直觉得：真诚是最好的敲门砖，你想要和人建立良好的互动，首先你自己就要是真诚的。有问题要及时讲出来，过后再说可能就有些迟了。不过，讲得太厉害了，有些人可能面子上会挂不住。这种情况我没想好该怎么办。

* 两天会议

** 一、准备签到

1月2日吃过酒店早餐和Corrie一起来到会场，开始准备签到物品以及集市开源社摊位的布置。八点多陆续开始有人参会，主要有三种身份：志愿者、参会者和讲师。

签到就是用百格app扫码，之后会根据票种判断是否有大礼包。还要发早午餐券和晚宴券。我负责引导人们到对应位置排队。

** 二、遇到SWHL

期间还遇到一个有意思的哥们（SWHL），他是[[https://github.com/RapidAI][RapidAI]]的核心开发，聊天谈及学习编程方法（从自己想做的事情出发）、技术界的近期新闻，还有他一直鼓励我去开源集市转一转，和大家聊天。

** 三、看yihong演讲

一直在外面引导人们排队签到，我没有时间去主会场看演讲。看到签到这里已经不忙了，就去主会场看看是什么人在演讲，正好看到了yihong老师，当时他讲到自己把每年经历都记到一个GitHub仓库。我很开心能线下见到yihong老师，之前一直都是在线上沟通，他的项目running_page我还贡献过样式相关的代码。

所以，当他来到签到处，说自己就是yihong时，本在走神的我马上就精神起来了，告诉他我是tianheg，在X/Twitter上还互关了。


** 四、班夫中国

下午四五点钟有个黑客马拉松，我对这个活动印象深刻，原因是我穿得少，走在去附近海淀公园的路上，冷得我直跳脚。哈哈，虽然有点奇怪，但这是事实。从深圳来北京没准备防冷的衣服。

我对这个班夫中国很好奇，就问在现场的一位来自班夫的小姐姐，他们到底是做什么的。她说，班夫是做户外影展的，就是将户外主题的电影和户外运动相结合。又问她到在这样的公司里负责的是什么，她回是负责市场商务这一块，因为没什么事儿所以来这边帮忙。

** 五、一个问题

周六晚宴之后，我见到了一位朋友。他问了我一个问题：如何解决无法及时处理事情的问题。他举的例子是，今天年会加了很多不认识但想认识的人，因为没有及时做备注，所以等到空闲的时候再想认识这些人时已经想不起来，他们是谁了。

我当时的回答是：既然已经没办法挽回，只能放弃了，既然没有时间做，那还能怎么样呢？

现在想来，我注意到一点：如果对方真的想让你记住他，就会在添加好友之后，发一段自我介绍。如果彼此都没有这样做，那么显然双方都没有觉得加微信是多么重要的事情，自然也不会发生进一步的交流。

** 六、青少年开源

这是我负责的分论坛。因为没有事先统计好、也没有想到需要做这方面的工作，导致临时更换演讲场地。让大家从一个地点转移到另一个场地。在此特别感谢许银老师、刘茜文，感谢他们帮忙协调场地，没有他们就没有青少年开源分论坛的顺利进行。

周日下午分论坛快结束时，给刘茜文发消息感谢她在这几天的付出：

#+BEGIN_QUOTE
这几天辛苦你做志愿者的总指挥。我第一次来参加这种会议，所以在做志愿者时有诸多问题无法及时解决，需要你以及大家的协助。尤其是今天下午，因为没有提前了解自己负责论坛参会的实际人数，导致突发情况出现。幸好没有大的纰漏出现。
#+END_QUOTE

分论坛分享中印象最为深刻的部分，是吴宇老师分享的田野录音公益项目，去偏僻山村录下那些即将消失的歌声。这让我想起另一个关于乡音的项目 [[https://phonemica.net/][乡音苑]]。大家都是文化传承的保护者，希望能够传承这源远流长的文化精粹。

Selina介绍了自己的[[https://eselina.cn][诗歌朗诵公益网站]]，目的是为了帮助孩子们培养关于朗诵的兴趣以及鼓励他们持续练习。

* 会议后

周日晚上和小伙伴们聚餐，到半夜十二点多，回到房间又和yiwei、基印聊天，我直到两点多才睡。

当我醒的时候，已经六点半了，而我要赶七点二十六的高铁。整个人立刻就慌起来，用最短的时间收拾下楼打车，打车我算是运气好打到了，如果没打到，那只能找其他办法走了。

司机很给力，在高铁发车前十五分钟，把我送到西站。之后我一路狂奔，跑到车厢里，也丝毫没有注意两边都有列车。当我在座位上坐定，广播员提醒检查是否坐错列车，我一看窗户发现对面车厢上写着G335，还没反应过来，又问了旁边的人确认了这不是我要坐的车次。又着急忙慌地跑到对面列车跟前找我坐的车厢。我坐下去没几分钟，列车就出发了，真的很是惊险呀。

我到达深圳北站是晚上六点半，到家已经八点多，至此这次出游算是结束了。

* 一些思考

当我走出福田站，来到这深圳市中心。晚上九十点钟少有人影，这里给我一种感觉——没有人情味。我永远也无法想象自己这样生活的场景。一切都是干净整洁的，在这里生活的人会否快乐幸福呢？短暂地邂逅了另一种生活，这生活贵得让我望而却步。

周六一整天都有的一种不安的感觉，当我晚宴后独处时开始显露，逼我分析这种不安从何而来。当我在会场的时候，深切体会到自己不属于这里，不属于这个技术圈子，我想进入但我在圈子之外。我的工作和技术无关，我的业余时间不多想投入技术有心无力。

对自己还不够自信，这种不自信是因为没有实践造成的，解决办法很简单就是开始做起来，不要停止做事。下一步就是怎样做？我该怎样改变目前的困境？我还注意到：在这一系列做事的流程中，“我是怎么样看待自己的”是很关键的。如果自我评价积极一些都好办，但实际上是我想积极地评价自己，但有时候又会回到消极的循环里无法自拔。

曾经有一个想法：在22年到32年这十年探索出自己的技术品味。晚宴之后，我花了一段时间一直在思考这句话究竟是什么意思。以下是我的理解：

技术之于我的意义是什么？我想借助技术实现个人价值，用技术助人，其次是与人建立连接。

我坐在那里一直询问自己一个问题：

What do you want?

What do you want to do?

I want to do things that ...
