#+TITLE: 参与2024中国开源年会
#+DATE: <2024-11-04 Mon 22:55>
#+TAGS[]: 随笔
#+DRAFT: true

作为开源社执行委员会的一员，年会从开始筹备时，我就在群组里，本来没打算线下参与。只是想着这次年会先了解一下整个的流程，待到明年年会时再线下贡献。直到上个月月末的29号，那天我记得是在上午，我坐在工位上，仿佛受到了刺激一般，一种强烈的欲望涌上心头——我想参加这次年会，我想和大家见面。

线上经常会和基础设施组的小伙伴们聊天，但有几位线下还没见过面，比如yiwei、基印、大鹏。水歌、文超和止戈在freeCodeCamp 2023广州聚会时见过。除此之外，还见了Corrie、月饼、萱萱、居居和佳欣，大家都很可爱，自由表达对事情的看法。很庆幸自己这次选择线下参与，我收获了更紧密的友谊以及更清晰的自我认知。

10月31日晚上八点半下班，之后公交地铁来到福田站，这时已经十点多了，傍晚时没怎么吃东西，也比较饿，就在附近找吃的。地处深圳市中心，附近都是高楼大厦，我觉得不自在。找了半天只找到一家麦当劳，点了套餐边吃便继续看《星际迷航》系列。吃麦当劳的时候遇到一位外国小哥，拿着百元纸币付款，但工作人员表示那个时间已经收不了了。小哥双手合十，离开了。当时我坐在那里看着他，有一种请他这顿的冲动，但最后还是没有请。如果请了我相信肯定会有意想不到的收获。

吃了以后，就准备下去在火车站过夜，没想到人家已经关门了，地铁站也快关门了，保安小哥告诉我不能在这里过夜，我就又返回地面。

11月1日凌晨从福田站出来后，我想找一个24h开放的地方，就瞄到了图书馆附近的24h书吧，在那里我趴在桌子上很冷地趴了四个小时，睡着了醒来，醒来又继续睡。还好这里有插座可以给手机充电。

4:37 从书吧出来，到达福田站一个入口时将近五点，恰好开门。又见到几小时前告诉我地铁站不能过夜的保安小哥，问他在哪里可以吃早餐，就在地铁站的喜乐多便利店买了一个三明治和茶叶蛋。

6:30 坐上高铁，还是睡了醒、醒了睡。中午吃了火车套餐。当到北京时已然傍晚六点。出了车厢，感到了北京深秋的凉意，只穿T-shirt的我感到冷。七点多到酒店，放好东西出去吃了碗红烧牛肉面，此时和止戈联系说要吃饭。但因为面很快会凉，我就先吃完了。待到我回酒店房间，给止戈发消息，他说他已经到了，其他人也到了。又去吃饭，十一点多才回来。

吃饭时的一些谈话，让我发现：开源社并没有我想象的那样是一个单纯的组织，它内部的人际关系的错综复杂超出了我的想象。当我这样说的时候，水歌告诉我：这就是中国社区的现状，但要不忘初心。

司机送我到酒店时谈的那些内容，让我深思：人们生活得不幸福，但科技发展的步伐不会停滞。在科技发展的当下，不要太过逻辑思考，人情味是很重要的东西。

11月2日吃过酒店早晨和Corrie一起来到会场，开始准备签到物品以及集市开源社摊位的布置。八点多陆续开始有人参会，主要有三种身份：志愿者、参会者和讲师。

签到就是用百格app扫码，之后会根据票种判断是否有大礼包。还要发早午餐券和晚宴券。我负责引导人们到对应位置排队。

期间还遇到一个有意思的哥们（佳华），他是[[https://github.com/RapidAI][RapidAI]]的核心开发，聊天谈及学习编程方法（从自己想做的事情出发）、技术界的近期新闻，还有他一直鼓励我去开源集市转一转，和大家聊天。

青少年开源论坛本来是一位叫黑珍珠的姑娘负责的，她周日有事所以让我帮忙处理。她周六有空来到了现场，其实很莫名的有种感觉，想和她见上一面，那种心绪萦绕在心头，久久不散。十点多问她到了没有，快十二点问了一次，一点多问了最后一次。

终于，见面了，是个很漂亮的姑娘。长发披肩，黑色夹克穿在身上，很是帅气。自我介绍之后我就走开了，在签到处的她很快就忙了起来。没有什么聊天的机会。发的志愿者卫衣太小，不合她的身，我帮她换了一件。

晚上有一顿大家一起吃的晚宴，因为人数太多所以我们这些晚走的只能在会场门口等第二班车。这恰好给了我和她聊天的机会。现在还记得的部分，有聊到她的身高更可能是模特，而不是运动教练；聊到各自家庭，她有一个哥哥，我也恰好有一个妹妹。她问我和妹妹关系，我说道以前还会吵架，但后来就宠得不得了了；她曾经是国家运动员，退役后来到大学，要花超常人百倍的努力补文化课，很是辛苦。

我记得很深的，我问她的最后一个问题：你的未来的人生规划是怎样的？

她回答说：现在的大环境并不好，想先在体制内工作几年，之后会出来创业，做体育产业的事情。

我很欣赏她，她对自己的人生有思考，并且为之努力。我也是这样的人。

周六晚宴之后，我见到了梁尧老师，他是开源社法务组的负责人，当时在我房间里组装第二天要用的奖牌。他问了我一个问题：如何解决无法及时处理事情的问题。比如，今天原计划做A，但因为工作太过繁忙，待到一天结束A都没来得及做。只能后悔惋惜让自己背负消极情绪。

我当时的回答是：既然已经没办法挽回，只能放弃了，既然没有时间做，那还能怎么样呢？

现在想来，难道没有更好的解决办法了吗？我想到了一本书《福格行为模型（Tiny Habits）》，它的主要观点是：如果拥有恰当的提示、明确的动机以及符合目标要求的能力，那么我们就能够完成这件事情。
