#+TITLE: 参与2024中国开源年会
#+DATE: <2024-11-04 Mon 22:55>
#+TAGS[]: 随笔

作为开源社执行委员会的一员，年会从开始筹备时，我就在群组里，本来没打算线下参与。只是想着这次年会先了解一下整个的流程，待到明年年会时再线下贡献。直到上个月月末的29号，那天我记得是在上午，我坐在工位上，仿佛受到了刺激一般，一种强烈的欲望涌上心头——我想参加这次年会，我想和大家见面。

线上经常会和基础设施组的小伙伴们聊天，但有几位线下还没见过面，比如yiwei、基印、大鹏。水歌、文超和止戈在freeCodeCamp 2023广州聚会时见过。除此之外，还见了Corrie、月饼、萱萱、居居和佳欣，大家都很可爱，自由表达对事情的看法。很庆幸自己这次选择线下参与，我收获了更紧密的友情以及更清晰的自我认知。

10月31日晚上八点半下班，之后公交地铁来到福田站，这时已经十点多了，傍晚时没怎么吃东西，也比较饿，就在附近找吃的。地处深圳市中心，附近都是高楼大厦，我觉得不自在。找了半天只找到一家麦当劳，点了套餐边吃便继续看《星际迷航》系列。吃麦当劳的时候遇到一位外国小哥，拿着百元纸币付款，但工作人员表示那个时间已经收不了了。小哥双手合十，离开了。当时我坐在那里看着他，有一种请他这顿的冲动，但最后还是没有请。如果请了我相信肯定会有意想不到的收获。

吃了以后，就准备下去在火车站过夜，没想到人家已经关门了，地铁站也快关门了，保安小哥告诉我不能在这里过夜，我就又返回地面。

11月1日凌晨从福田站出来后，我想找一个24h开放的地方，就瞄到了图书馆附近的24h书吧，在那里我趴在桌子上很冷地趴了四个小时，睡着了醒来，醒来又继续睡。还好这里有插座可以给手机充电。

4:37 从书吧出来，到达福田站一个入口时将近五点，恰好开门。又见到几小时前告诉我地铁站不能过夜的保安小哥，问他在哪里可以吃早餐，就在地铁站的喜乐多便利店买了一个三明治和茶叶蛋。

6:30 坐上高铁，还是睡了醒、醒了睡。中午吃了火车套餐。当到北京时已然傍晚六点。出了车厢，感到了北京深秋的凉意，只穿T-shirt的我感到冷。七点多到酒店，放好东西出去吃了碗红烧牛肉面，此时和止戈联系说要吃饭。但因为面很快会凉，我就先吃完了。待到我回酒店房间，给止戈发消息，他说他已经到了，其他人也到了。其他人指水歌、基印，还有其他几位美女（Corrie、李佳欣、屈屈等）。又去吃饭，十一点多才回来。

吃饭时的一些谈话，让我发现：开源社并没有我想象的那样是一个单纯的组织，它内部的人际关系的错综复杂超出了我的想象。当我这样说的时候，水歌告诉我：这就是中国社区的现状，但要不忘初心。

司机送我到酒店时谈的那些内容，让我深思：人们生活得不幸福，但科技发展的步伐不会停滞。在科技发展的当下，不要太过逻辑思考，人情味是很重要的东西。

11月2日吃过酒店早晨和Corrie一起来到会场，开始准备签到物品以及集市开源社摊位的布置。八点多陆续开始有人参会，主要有三种身份：志愿者、参会者和讲师。


签到就是用百格app扫码，之后会根据票种判断是否有大礼包。还要发早午餐券和晚宴券。我负责引导人们到各自的位置排队，期间还遇到一个有意思的哥们（佳华），他
