#+TITLE: 域名
#+DATE: <2023-07-26 Wed 21:24>
#+TAGS[]: 随笔 博客

我的个站的域名变化：

1. =yidajiabei.xyz=
2. =tianheg.xyz=
3. =tianheg.co=

这是我最后的域名了，直到不再书写为止。

我目前持有的域名：

- tianheg.co
- tianheg.org
- tianheg.net
- tianheg.me
- tianheg.xyz

这些域名是一直会续费的。tianheg.com被别人注册了，但是tianheg.co更短，我也就不在意了。

-----

域名是个巨大的面子工程。能够选到好域名需要运气，以及一定程度的思考。运气自不必说，如果你出生得早，再加上手里有些钱，自然是看中什么域名就能购买；如果你出生得晚，有些域名组合特别适合你，也可以买到，同时暗暗庆幸别人没有注册。

我的真名叫高天贺，按照惯常的英文式写法，我的英文名可以是 Tianhe Gao，稍微以简化就成了我的id——tianheg。所以，我的域名也是围绕着它来购买。我最开始买的是.xyz域名，因为当时我手上的钱似乎只能购买这个价位的。最近一年，痴迷于.com后缀，在终于买了tianhegao.com（到期后不再续费）后发现，也不过如此。几天前，Twitter上看到有人说.co和.com差不多，但比.com还少一个字母。昨天午休时，想到了这里，就直接购买了。

之后，就开始想换博客域名了。原因有以下几点：

1. 更短
2. 降低偏见

“降低偏见”是指，很多人会把带有.xyz域名后缀的网站看作垃圾网站。为了不致被人识别成垃圾网站，所以选择更换了域名。

当然了，如果我足够有钱，说不定会把tianh.eg买下来。

-----

那么，这一系列行为背后，我是怎么想的，反映了我的什么性格（也可表述为行为模式或思考方式）？

第一，

购买域名这个行为是虚荣心满足的过程。因为我“获得”了“真正属于自己”的东西，这种“获得”仅指主观意义上的，我通过金钱购买了该域名的使用权（我租借了域名），在这段时间内我可以用它展示自己想要分享的内容。

第二，

网络中很多能够用文字打动我的个人网站作者，他们有自己的域名，有些还很特别。这让我有一种效仿心理。我也想像他们一样，有一个符合自己特征的域名。

第三，

最常见的域名后缀是.com，所以我想要拥有tianheg.com，但因为已经被人注册，所以我退而求其次，找到了更好的 tianheg.co。

对于.xyz。我一开始并没有什么想法，只是说这是个域名，我使用了它，这就可以了。我没有去想xyz背后的含义。后来，我想了一个含义——道教的“一生二，二生三，三生万物”。xyz是英文字母排序后的最后三位，与abc具有类似的含义。我所理解的xyz是三角形的三个顶点，xyz所形成了三角形构成了稳定的万事万物。这个想法我觉得很不错。后来在一次言论风波中，让我知道了这xyz的另一个含义——小姨子，而这是让我产生换域名念头的根本原因。如果我不知道这件事，或许我的域名后缀还是.xyz。

身处在中国这样的社会环境下，我很难摆脱那些我深恶痛绝的东西。换个视角讽刺自己，让自己铭记：

就因为看到了xyz更多的含义就能让你生发出改变的念头，如果你那么轻易就能改变，为什么不让自己快些进步呢？还是说，这种改变仅仅是表面（域名），实际上不会发生任何变化。

你自以为不在乎别人的看法，但实际上，还是会因为别人的看法而改变自己。你慢慢地把自己塑造成别人喜欢的样子，而刻意忽视自己内心真正的渴望，这样做真的可以吗？

当你这样做的时候，当你违背自己内心的时候，你的真我大概是在心里的某个角落，静静哭泣吧。