#+TITLE: 【读书记38】神曲 by 但丁 La Divina Commedia
#+DATE: <2025-11-06 Thu 12:00>
#+TAGS[]: 读书记


#+BEGIN_QUOTE
一个人如若看见别人需要，还等着别人的请求，显而易见不是诚心的援助了。
#+END_QUOTE

《神曲（全3册）（果麦经典）》

[意]但丁
38个笔记

点评

◆ 2020/07/23 认为好看




地狱

◆ 2020/07/21发表想法

抽象


第一篇 Inferno.I

◆ 2020/07/21发表想法

普布留斯·维吉留斯·马罗，通称维吉尔（Virgil），在欧洲文学发展中占据一个关键地位。他生活在欧洲古代文明的结尾、基督教即将对欧洲开始其统治的时期，他的历史地位颇像生活在中世纪和近代之交的但丁的历史地位。他开创了一种新型的史诗，在他手里，史诗脱离了在宫廷或民间-上说唱的口头文学传统和集体性。他给诗歌注入了新的内容，赋予它新的风格，产生了深远的影响。他的作品具有历史感和思想的成熟性。他是一个自觉的艺术家。他可以说是第一个近代意义上的作家。这些特点已为一般所公认了。

原文：诗人维吉尔

◆ 2020/07/22发表想法

黑暗太黑

原文：当人生的中途，[插图]我迷失在一个黑暗的森林[插图]之中。

◆ 2020/07/22发表想法

一不小心就误入歧途

原文：只知道我在昏昏欲睡的当儿，我就失掉了正道。

◆ 2020/07/22发表想法

人已死，回首生前，一切消沉

原文：从海里逃上岸来的，每每回头去看看那惊涛骇浪，所以我在惊魂初定之后，我也就回顾来路，才晓得来路险恶，不是生人所到的。

◆ 2020/07/22发表想法

即有豹又有狮，路上艰难险阻，政治环境险恶

原文：没有爬得多么高，前面忽然有一只敏捷的、五色斑斓的豹，正拦住我的去路，我几次想回头逃避他。[插图]那时天晓了，太阳正同着美丽的群星[插图]从东方升起；这样清爽的早晨，这样温和的季候，使我有克服那眩眼的走兽之希望。[插图]但是，一波未平，一波又起，一只狮子又出现了，[插图]他似乎向着我冲过来，他的肚子饿极了，高抬他的头，呼呼的口气吓煞人。

◆ 2020/07/22发表想法

痛苦悲哀

原文：我好比那渴望着金钱的人，忽然受到一个失败的打击，而沉迷于痛哭悲哀的情境。

◆ 2020/07/22发表想法

各方势力的胁迫，让但丁不得不做出某种错误决定。

原文：我受到那只母狼的压迫，她一步一步地接近我，使我不得不退往那黑暗无光的森林。

◆ 2020/07/22发表想法

长久缄默的结果

原文：他似乎是静默了长久，因此不会说话一样

◆ 2020/07/22发表想法

爬过这座山，这是一切幸福的源头

原文：但是你为什么这样惊慌失措？为什么不爬过这座明媚的山？这是一切幸福的源头。

◆ 2020/07/22发表想法

激动地与老师相识

原文：那么你就是维吉尔么？从你的嘴里，流出多么美丽而和谐的诗句呀！你是众诗人的火把，一切的光荣归于你！我已经长久学习过，爱好过，研究过你的著作！你是我的老师，是我的模范，我从你那学得些好诗句，因此使我有了一些声名。

◆ 2020/07/22发表想法

沟通先贤的力量

原文：请你看那野兽，我后退的缘故就是为着她。著名的哲人，请你帮助我来反抗她，她使我四肢的血脉都颤动起来了！

◆ 2020/07/22发表想法

象征某种极权

原文：她的性质非常残酷，肚子从来没有饱足的时候，吃得愈加多，反而愈加饥饿。

◆ 2020/07/22发表想法

诗意的语言，悲哀的心绪

原文：我于是这样说：“诗人呀！请你为上帝的缘故，引导我逃出这个森林和其他更坏的地方罢；伴着我到你方才所说的境界，一看沉溺在悲哀的深渊里的幽灵；最后引导我到圣彼得的门。”


第二篇 Inferno.II

◆ 2020/07/23发表想法

但丁认为自己没有资格踏上旅途

原文：无论我自己或别人看来，都觉得我不够资格，我要是冒昧地跟着你去，适足以证实我的愚昧。你是哲人，虽然我的话说得不清楚，你总十分明白我的意思罢。

◆ 2020/07/23发表想法

后悔莫及

原文：因此我逗留在昏暗的山路上，自悔不加深思，便轻易答允了这样重大的使命。

◆ 2020/07/23发表想法

恐惧让人在危难面前止步

原文：假使我十分明白你的说话，就是你的心里生了恐惧。恐惧，他使人们在正大的事业前面望而却步，好比胆怯的野兽，听见风声就吓得逃走一样。我要赶开你心里的恐惧，我要告诉你我为什么来到这里，我听了什么人的嘱咐才来搭救你。

◆ 2020/07/23发表想法

贝雅特丽齐帮助人类摆脱于其他动物的群体

原文：善女人呀，因为你的缘故，地上的人类成为万物之灵！

◆ 2020/07/23发表想法

是啊，为什么不勇敢些？

原文：现在你为什么踟蹰不前？为什么一颗心被恐惧包围了？为什么不勇敢些？岂不辜负了天庭三个圣女和我的一片好意么？

◆ 2020/07/23发表想法

温暖无比

原文：好比夜里受了霜打的花朵，垂头丧气地紧闭着，忽然受着太阳的照耀而开放了


第三篇 Inferno.III

◆ 2020/08/01发表想法

面前就是地狱

原文：到了此地，一切的恐怖和畏怯都要放在脑后了。

◆ 2020/08/01发表想法

行尸走肉

原文：他们既没有寂灭的希望，[插图]只是过着盲目的平庸生活，也没有改进的可能。


第五篇 Inferno.V

◆ 2020/08/02发表想法

理性胜于肉欲

原文：我知道这种刑罚是加于荒淫之人的，他们都是屈服于肉欲而忘记了理性的。


第十一篇 Inferno.XI

◆ 2020/08/05发表想法

一个人会强暴自己

原文：一个人会对于自己和自己的所有施以强暴

◆ 2020/08/05发表想法

获取到知识的喜悦！

原文：哦，太阳呀！他把我昏暗的精神照明亮了；从一个疑问得着一段知识，你使我多么快活呀！

◆ 哦，太阳呀！他把我昏暗的精神照明亮了；从一个疑问得着一段知识，你使我多么快活呀！


第二十四篇 Inferno.XXIV

◆ 2020/08/24发表想法

在柔软的环境里不能成就大事

原文：你现在应当避开懒惰，因为一个人坐在绒毯之上，困在绸被之下，一定不会成名的；无声无臭度一生，好比空中烟，水面泡，他在世上的痕迹顷刻就消灭了。所以，你要站起来，用你的精神，克服你的气喘；假使精神不跟着肉体堕落，那么他可以战胜一切艰难。你要爬的梯子还长呢，就是离开了此地也不算完结；假使你明白我的话，那么快些行动罢，对于你是有益处的。


第二十七篇 Inferno.XXVII

◆ 一个人不忏悔，就不能得着赦免；一方面忏悔，一方面作恶，这也是不能允许的矛盾。


第五篇 Purgatorio.V

◆ 2020/09/08发表想法

想法过多似乎也是一种过错呢！

原文：一个人常常由这个思想引起那个思想，因而远离了他所追求的正鹄，第二个思想每每减少第一个的活力呢。


第十五篇 Purgatorio.XV

◆ 2020/10/05发表想法

众人的幸福，大智慧也

原文：因为你们的心太注意在一种财产了，这种财产分之者愈众，则每个人享受的便愈少；可是，假使你们的欲望放在那至高的幸福上面，那就不生这种烦恼了。因为在那里，只说‘我们的’，占有人的数目愈多，每个人的幸福愈大。


第十六篇 Purgatorio.XVI

◆ 2020/10/05发表想法

熟读圣书，但不能分辨善恶

原文：因为领导群羊的牧人能够反刍，但是没有分蹄。


第十七篇 Purgatorio.XVII

◆ 2020/10/10发表想法

挺玄乎

原文：凡爱不能没有主体，所以人不能嫉妒他自己；凡人都不能超然独立而自存，所以不能对于造物主有所嫉妒。

◆ 2020/10/10发表想法

乖戾之爱

原文：一种人欢喜自高自大，觉得他的邻人都是卑小，只恐怕自己有一天要倒下来。一种人要保持他自己的尊荣富贵，只恐怕别人超过他，于是他心里忧愁，希望别人得祸。还有一种人，因为受了一些委屈，便突然大怒，立刻要报复他的冤家。


第十九篇 Purgatorio.XIX

◆ 2020/10/12发表想法

但丁第二梦中所见之西壬（Serena），为在海上以音乐迷惑航海者之女神，象征肉体快乐，暗示以后三种罪恶（贪财、贪食、贪色）之洗涤，视三种罪恶为女神所迷惑。据《荷马史诗》，尤利西斯拒绝西壬，此处言其受迷惑者，盖依西塞罗之注解云。

原文：说话是口吃的，眼睛是斜视的，脚是曲的，手是断的，面色是灰白的


第二十二篇 Purgatorio.XXII

◆ 2020/10/14发表想法

zhuàng zhí

憨厚而刚直。为人戆直。

原文：戆直

◆ 戆直

◆ 你好比一个夜行人，掮着火把在背后，自己没有受益，但照明了跟随他走的人。

-- 来自微信读书


@@html:<span style="color:var(--dushuji-count-color)">2025年读完的第38本，总阅读量第38本</span>@@