#+TITLE: 【读书记51】MAKE: The Indie Maker Handbook by levelsio
#+DATE: <2025-11-20 Thu 12:00>
#+TAGS[]: 读书记


https://readmake.com/

- Idea
   
  从生活中遇到的问题获得新想法。
  
  Don't build products that are solutions in search of a problem.
  
  含义：不要开发那些只是为了找问题而提供解决方案的产品。这句话的意思是，不要开发那些只是为了解决一个并不存在或不重要的问题而存在的产品。换句话说，开发产品时应该先确定问题的存在，然后设计相应的解决方案，而不是相反。这样可以确保开发的产品具有真正的需求，并能够解决实际存在的问题。

- Build

  使用熟悉的工具构建产品。不要在构建产品以前先花很长时间学习编程语言，更何况以后很可能不会用它。不要让外包插手构建过程。
  
  刚开始只构建核心功能，剩下的之后再说。
  
- Launch

  早发布多发布。Launch to famous startups websites (like Product Hunt, Hacker News, The Next Web), mainstream websites (like Reddit) and mainstream press (like Forbes).
  
  找到产品真正目标用户的位置。

- Grow

  自然增长。人们真正需要的好产品会让人们主动使用，糟糕的产品会逼人们使用它。
  
  不需要广告。
  
  如果没有收入，就不要雇人。如果有收入，也不要雇很多人。
  
  保持精简和快速。
  
  自己的事情自己做。

- Monetize

  向用户收费。
  
  不要出售他们的数据，不要在产品的各处放置广告，不要稀释你的产品。
  
  诚实地告诉用户，你需要钱来打造他们喜爱的产品，他们会很乐意为你的产品买单。

- Automate

  通过写程序自动化要做的事情，通过AI自动化要写的程序。

- Exit

  不出售公司，让买家自己找上门。

- Ethics

  讲道德。


2025年读完的第51本，总阅读量第51本