#+TITLE: 【读书记54】一九八四 by George Orwell
#+DATE: <2025-11-23 Sun 12:00>
#+TAGS[]: 读书记


这是一本很难读懂的小说，以我现在的阅读经历，读起来太过晦涩。仅能记住一句调侃的话：“老大哥正在看你。”

人的精力宝贵，觉得把它浪费在盲目重新政党上。拒绝歇斯底里。

** 译本序

#+BEGIN_QUOTE
我感到我必须洗赎那压得我透不过气来的罪咎……我觉得我不仅仅应该与帝国主义决裂，而且也应该与一切人对人的统治决裂。我希望融合到受压迫的人中间去，成为他们之中的一个，站在他们的一边反对他们的暴君……在这时候，在我看来，没有出息倒是唯一的美德。自我奋斗，哪怕稍有成就，一年能挣上几百镑，我觉得稍有这种想法都是精神丑恶的，是一种欺压行为。
#+END_QUOTE

与帝国主义、人与人之间的统治决裂，和被压迫的人站在一起反抗压迫者

#+BEGIN_QUOTE
他尽力接近下层群众，体验他们的生活，但是有一道无形的墙，隔在他与他们之间，成了一道不可逾越的鸿沟。这就是他身上的中产阶级烙印。
#+END_QUOTE

我是无产的一份子，但我受过教育，这个教育不仅指所谓高等教育，还指自我教育

#+BEGIN_QUOTE
他的一切疙瘩都来自这个事实：他认为他应该去爱他的同胞，但是他连同他们随便交谈都做不到。
#+END_QUOTE

口音，导致奥威尔无法和下层群众打成一片

#+BEGIN_QUOTE
在这以前，他生活颠沛，对下层社会生活不是没有体会，但这毕竟是个人经历，只有到了英格兰北部工业区后，他的这种体会才有了社会性和阶级性。
#+END_QUOTE

为什么到工业区后，才能体会到阶级性和社会性

#+BEGIN_QUOTE
明确了他要的是哪一种社会主义，那就是主张政治民主和社会公正的社会主义，反对一切变种形式的社会主义，包括法西斯主义—纳粹主义(即国家社会主义)。
#+END_QUOTE

主张政治民主和社会公正的社会主义，反对其他社会主义变种，比如法西斯主义——纳粹主义（即国家社会主义）

#+BEGIN_QUOTE
奥威尔反极权主义斗争是他对社会主义的坚定信念的必然结果。他相信，只有击败极权主义，社会主义才有可能胜利，因此揭露极权主义的危害，向世人敲起警钟，让大家都看到它的危害性——对伦理的破坏，对思想的控制，对自由的剥夺，对人性的扼杀，对历史的捏造和篡改……——是何等的重要。如果听任它横行，在不久的将来，人类社会将陷入万劫不复的境地。
#+END_QUOTE

** 第一部

#+BEGIN_QUOTE
在他住所里面，有个圆润的嗓子在念一系列与生铁产量有关的数字。声音来自一块像毛玻璃一样的椭圆形金属板，这构成右边墙壁的一部分墙面。温斯顿按了一个开关，声音就轻了一些，不过说的话仍听得清楚。这个装置(叫做电幕)可以放低声音，可是没有办法完全关上。
#+END_QUOTE

电幕——既能输入又能输出，是个不错的监控与控制机器。

#+BEGIN_QUOTE
你只能在这样的假定下生活——从已经成为本能的习惯出发，你早已这样生活了：你发出的每一个声音，都是有人听到的，你做出的每一个动作，除非在黑暗中，都是有人仔细观察的。
#+END_QUOTE

自我审查

#+BEGIN_QUOTE
破败的十九世纪的房子，墙头用木材撑着，窗户钉上了硬纸板，屋顶上盖着波纹铁皮，倒塌的花园围墙东倒西歪；还有那尘土飞扬、破砖残瓦上野草丛生的空袭地点；还有那炸弹清出了一大块空地，上面忽然出现了许多像鸡笼似的肮脏木房子的地方。
#+END_QUOTE

这是未来世界，一九八四年的伦敦。

#+BEGIN_QUOTE
战争即和平

自由即奴役

无知即力量
#+END_QUOTE

真理部建筑上的宣传口号

#+BEGIN_QUOTE
它们是整个政府机构四部的所在地：真理部负责新闻、娱乐、教育、艺术；和平部负责战争；友爱部维持法律和秩序；富裕部负责经济事务。用新话来说，它们分别称为真部、和部、爱部、富部。

真正教人害怕的部是友爱部。它连一扇窗户也没有。温斯顿从来没有到友爱部去过，也从来没有走近距它半公里之内的地带。这个地方，除非因公，是无法进入的，而且进去也要通过重重铁丝网、铁门、隐蔽的机枪阵地。甚至在环绕它的屏障之外的大街上，也有穿着黑色制服、携带连枷棍的凶神恶煞般的警卫在巡逻。
#+END_QUOTE

友爱部最教人害怕

#+BEGIN_QUOTE
这时他已经使自己的脸部现出一种安详乐观的表情，在面对电幕的时候，最好是用这种表情。
#+END_QUOTE

如果不是这种表情，可能就被思想警察盯上了

#+BEGIN_QUOTE
在一天的这个时间里离开真理部，他牺牲了在食堂的中饭，他知道厨房里没有别的吃的，只有一块深色的面包，那是得省下来当明天的早饭的。
#+END_QUOTE

未来世界，食物并不丰裕

#+BEGIN_QUOTE
温斯顿坐在壁龛里，尽量躲得远远的，可以处在电幕的控制范围之外，不过这仅仅就视野而言。当然，他的声音还是可以听到的，但只要他留在目前的位置，电幕就看不到他。一半是由于这间屋子的与众不同的布局，使他想到要做他目前要做的事。
#+END_QUOTE

有电幕监视不到的地方，使得Winston可以写日记

#+BEGIN_QUOTE
她是个年约二十七岁、表情大胆的姑娘，浓浓的黑发，长满雀斑的脸，动作迅速敏捷，像个运动员。她的工作服的腰上重重地围了一条猩红色的狭缎带，这是青年反性同盟的标志，围得不松不紧，正好露出她的腰部的苗条。温斯顿头一眼看到她就不喜欢她。他知道为什么原因。这是因为她竭力在自己身上带上一种曲棍球场、冷水浴、集体远足，总的来说是思想纯洁的味道。

几乎所有的女人他都不喜欢，特别是年轻漂亮的。总是女人，尤其是年轻的女人，是党的最盲目的拥护者，生吞活剥口号的人，义务的密探，非正统思想的检查员。
#+END_QUOTE

文学作品中似乎总喜欢用年轻女人或女孩，来表达某种对强大党派的盲目拥护。《一九八四》如此，《三体》也如此。是否是因为作者是男性，所以带有某种偏见，还是历史事实如此？

#+BEGIN_QUOTE
他甚至想到这样的念头：她可能是思想警察的特务。不错，这是很不可能的。但是只要她在近处，他仍有一种特别的不安之感，这种感觉中掺杂着敌意，也掺杂着恐惧。
#+END_QUOTE

“不错，这是很不可能的”这句如果不是错的，是想表达什么呢？看了英文版，中文翻译得没错。

#+BEGIN_QUOTE
奥勃良是个体格魁梧的人，脖子短粗，有着一张粗犷残忍、兴高采烈的脸。尽管他的外表令人望而生畏，他的态度却有一定迷人之处。他有一个小动作奇怪地使人感到可亲，那就是端正一下鼻梁上的眼镜；也很难说清楚，这奇怪地使人感到很文明。
#+END_QUOTE

现在是“文明”的，之后惩罚Winston时就不是了。

#+BEGIN_QUOTE
他感到对他特别有兴趣，这并不完全是因为他对奥勃良彬彬有礼的态度和拳击师的体格的截然对比感到有兴趣，更多的是因为他心中暗自认为——也许甚至还不是认为，而仅仅是希望——奥勃良的政治信仰不完全是正统的。他脸上的某种表情使人无法抗拒地得出这一结论。而且，表现在他脸上的，甚至不是不正统，而干脆就是智慧。不过无论如何，他的外表使人感到，如果你能躲过电幕而单独与他在一起的话，他是个可以谈谈的人。
#+END_QUOTE

如果将这种想法付诸实施，Winston逃不掉被思想改造的命运

#+BEGIN_QUOTE
果尔德施坦因在对党进行他一贯的恶毒攻击，这种攻击夸张其事，不讲道理，即使一个儿童也能一眼看穿，但是听起来却又似乎有些道理，使你觉得要提高警惕，别人要是没有你那么清醒的头脑，可能上当受骗。
#+END_QUOTE

皇帝的新装

#+BEGIN_QUOTE
所有这一切的话都是用大字眼飞快地说的，可以说是对党的演说家一贯讲话作风的一种模仿，甚至还有一些新话的词汇；说真的，比任何党员在实际生活中一般使用的新话词汇还要多。在他说话的当儿，唯恐有人会对果尔德施坦因的花言巧语所涉及的现实有所怀疑，电幕上他的脑袋后面有无穷无尽的欧亚国军队列队经过——一队又一队的结实的士兵蜂拥而过电幕的表面，他们的亚细亚式的脸上没有表情，跟上来的是完全一样的一队士兵。这些士兵们的军靴有节奏的踩踏声衬托着果尔德施坦因的嘶叫声。
#+END_QUOTE

我觉得这演讲，干脆就是小说司的人撰写的，目的就是激起群众的仇恨情绪

#+BEGIN_QUOTE
两分钟仇恨所以可怕，不是你必须参加表演，而是要避不参加是不可能的。不出三十秒钟，一切矜持都没有必要了。一种夹杂着恐惧和报复情绪的快意，一种要杀人、虐待、用大铁锤痛打别人脸孔的欲望，似乎像一股电流一般穿过了这一群人，甚至使你违反本意地变成一个恶声叫喊的疯子。然而，你所感到的那种狂热情绪是一种抽象的、无目的的感情，好像喷灯的火焰一般，可以从一个对象转到另一个对象。因此，有一阵子，温斯顿的仇恨并不是针对果尔德施坦因的，而是反过来转向了老大哥、党、思想警察；在这样的时候，他打从心眼里同情电幕上那个孤独的、受到嘲弄的异端分子，谎话世界中真理和理智的唯一卫护者。
#+END_QUOTE

人在集体中，在极端情绪的渲染下，是丑陋的、无恶不作的。仇恨情绪的对象如果不复存在，那么仇恨将何去何从？

#+BEGIN_QUOTE
温斯顿突然把仇恨从电幕上的脸孔转到了坐在他背后那个黑发女郎的身上，其变化之迅速就像做噩梦醒来时猛地坐起来一样。一些栩栩如生的、美丽动人的幻觉在他的心中闪过。他想象自己用橡皮棍把她揍死，又把她赤身裸体地绑在一根木桩上，像圣塞巴斯蒂安一样乱箭穿身。在最后高潮中，他污辱了她，割断了她的喉管。而且，他比以前更加明白他为什么恨她。他恨她是因为她年轻漂亮，却没有性感，是因为他要同她睡觉但永远不会达到目的，是因为她窈窕的纤腰似乎在招引你伸出胳膊去搂住她，但是却围着那条令人厌恶的猩红色绸带，那是咄咄逼人的贞节的象征。
#+END_QUOTE

社会对性的压抑，会产生极端情绪，让人恶念丛生。Winston认为：年轻漂亮的女人，应该主动展现自己的性感，而不是带上绸带以表贞节，把自己献给了老大哥。

#+BEGIN_QUOTE
全部在场的人缓慢地、有节奏地、深沉地再三高叫“B—B！……B—B！……B—B！”
#+END_QUOTE

这不是在骂老大哥2B吗

#+BEGIN_QUOTE
不那么做是办不到的。掩饰你真实的感情，控制你脸部的表情，大家做什么你就做什么，这是一种本能的反应。但是有那么一两秒钟的时间里，他的眼睛里的神色很可能暴露了他自己。
#+END_QUOTE

#+BEGIN_QUOTE
总是在夜里——逮捕总是在夜里进行的。突然在睡梦中惊醒，一只粗手捏着你的肩膀，灯光直射你的眼睛，床边围着一圈凶狠的脸孔。在绝大多数情况下不举行审讯，不报道逮捕消息，人就是这么销声匿迹了，而且总是在夜里。你的名字从登记册上除掉了，你做过的一切事情的记录都除掉了，你的一度存在也给否定了，接着被遗忘了。你被取消，消灭了：通常用的字眼是化为乌有。
#+END_QUOTE

#+BEGIN_QUOTE
最好是来个纯粹虚构幻想。突然他的脑海里出现了一个叫做奥吉尔维同志的人的形象，好像是现成的一样，这个人最近在作战中英勇牺牲。
#+END_QUOTE

#+BEGIN_QUOTE
能够创造死人，却不能创造活人。
#+END_QUOTE

#+BEGIN_QUOTE
一盒暗红色的炖菜，一块面包，一小块干酪，一杯无奶的胜利咖啡，一片糖精。
#+END_QUOTE

#+BEGIN_QUOTE
新话的全部目的是要缩小思想的范围。
#+END_QUOTE

#+BEGIN_QUOTE
最后我们要使得大家在实际上不可能犯任何思想罪，因为将来没有词汇可以表达。凡是有必要使用的概念，都只有一个词来表达，意义受到严格限制，一切附带含义都被消除忘掉。
#+END_QUOTE

#+BEGIN_QUOTE
语言完善之时，即革命完成之日。新话即英社，英社即新话。
#+END_QUOTE

#+BEGIN_QUOTE
正统即没有意识。
#+END_QUOTE

#+BEGIN_QUOTE
不论他说的是什么，你可以肯定，每一句话都是纯粹正统的，纯粹英社的。温斯顿看着那张没有眼睛的脸上的嘴巴忙个不停在一张一合，心中有一种奇怪的感觉，觉得这不是一个真正的人，而是一种假人。说话的不是那个人的脑子，而是他的喉头。说出来的东西虽然是用词儿组成的，但不是真正的话，而是在无意识状态中发出来的闹声，像鸭子呱呱叫一样。
#+END_QUOTE

#+BEGIN_QUOTE
不知道你是不是知道，叫鸭话，就是像鸭子那样呱呱叫。这种词儿很有意思，它有两个相反的含义。用在对方，这是骂人的；用在你同意的人身上，这是称赞。
#+END_QUOTE

#+BEGIN_QUOTE
他不快地沉思着物质生活的各个方面。一直是这样的吗？他的饭一直是这个味道？他环顾食堂四周。一间天花板很低、挤得满满的屋子，由于数不清的人体接触，墙头发黑；破旧的铁桌铁椅挨得很近，你坐下来就碰到别人的手肘；汤匙弯曲，铁盘凹凸，白缸子都很粗糙；所有东西的表面都油腻腻的，每一条缝道里都积满尘垢；到处都弥漫着一股劣质杜松子酒、劣质咖啡、涮锅水似的炖菜和脏衣服混合起来的气味。
#+END_QUOTE

#+BEGIN_QUOTE
脸上表情不适当(例如在听到胜利公告时露出不信的表情)本身就是一桩应予惩罚的罪行。新话里甚至有一个专门的词，叫做脸罪。
#+END_QUOTE

#+BEGIN_QUOTE
暗地里，党甚至鼓励卖淫，以此作为发泄不能完全压制的本能的出路。
#+END_QUOTE

#+BEGIN_QUOTE
党的目的不仅仅是要防止男女之间结成可能使它无法控制的誓盟关系。党的真正目的虽然未经宣布，实际上是要使性行为失去任何乐趣。
#+END_QUOTE

#+BEGIN_QUOTE
他一碰到她，她就仿佛要往后退缩，全身肌肉紧张起来。搂抱她像搂抱木头人一样。奇怪的是，甚至在她主动抱紧他的时候，他也觉得她同时在用全部力气推开他。她全身肌肉僵硬使他有这个印象。她常常闭着眼睛躺在那里，既不抗拒，也不合作，就是默默忍受。
#+END_QUOTE

#+BEGIN_QUOTE
正如党的口号所说：“无产者和牲口都是自由的。”
#+END_QUOTE

#+BEGIN_QUOTE
看看四周，就可以看到现在的生活不仅同电幕上滔滔不绝的谎言毫无共同之处，而且同党要想达到的理想也无共同之处
#+END_QUOTE

#+BEGIN_QUOTE
生活的许多方面都是中性的，非政治性的，单纯地是每天完成单调乏味的工作、在地铁中抢一个座位、补一双破袜子、揩油一片糖精、节省一个烟头。而党所树立的理想却是一种庞大、可怕、闪闪发光的东西，到处是一片钢筋水泥、庞大机器和可怕武器，个个是骁勇的战士和狂热的信徒，团结一致地前进，大家都思想一致、口号一致，始终不懈地在努力工作、战斗、取胜、迫害——三亿人民都是—张脸孔。而现实却是城市破败阴暗，人民面有菜色，食不果腹，穿着破鞋在奔波忙碌，住在十九世纪东补西破的房子里，总有一股烂白菜味和尿臊臭。
#+END_QUOTE

#+BEGIN_QUOTE
在遮荫的栗树下，我出卖了你，你出卖了我；

他们躺在那里，我们躺在这里，在遮荫的栗树下。
#+END_QUOTE

#+BEGIN_QUOTE
他们的哲学不仅不言而喻地否认经验的有效性，而且否认客观现实的存在。
#+END_QUOTE

#+BEGIN_QUOTE
想到碰到危急状态，你要对付的从来不是那个外部的敌人，而是自己的身体。
#+END_QUOTE

** 第二部

#+BEGIN_QUOTE
看到了我爱你三字以后，他要活下去的欲望猛然高涨，为一些小事担风险太不划算了。一直到了二十三点，他回家上床以后，在黑暗中他才能连贯地思考问题。在黑暗中，只要你保持静默，你是能够躲开电幕的监视而安然无事的。
#+END_QUOTE

#+BEGIN_QUOTE
她逐一说明了他要走的路线，清楚明确，犹如军事计划一样，使他感到惊异。坐半小时火车，然后出车站往左拐，沿公路走两公里，到了一扇顶上没有横梁的大门，穿过了田野中的一条小径，到了一条长满野草的路上，灌木丛中又有一条小路，上面横着一根长了青苔的枯木。好像她头脑里有一张地图一样。
#+END_QUOTE

#+BEGIN_QUOTE
我恨纯洁，我恨善良。我都不希望哪里有什么美德。我希望大家都腐化透顶。
#+END_QUOTE

#+BEGIN_QUOTE
这就是他最想听的话。不仅是一个人的爱，而是动物的本能，简单的不加区别的欲望：这就是能够把党搞垮的力量。
#+END_QUOTE

#+BEGIN_QUOTE
任何有组织的反叛党的尝试都注定要失败的，因此她认为都是愚蠢之极。聪明人该做的事是打破它的规矩而不危及你的生命。
#+END_QUOTE

#+BEGIN_QUOTE
不像温斯顿，她了解党在性方面搞禁欲主义的内在原因。这只是因为性本能创造了它自己的天地，非党所能控制，因此必须尽可能加以摧毁。尤其重要的是，性生活的剥夺能够造成歇斯底里，而这是一件很好的事，因为可以把它转化为战争狂热和领袖崇拜。
#+END_QUOTE

控制最原始的欲望

#+BEGIN_QUOTE
你做爱的时候，你就用去了你的精力；事后你感到愉快，天塌下来也不顾。他们不能让你感到这样。
#+END_QUOTE

#+BEGIN_QUOTE
他站在一道黑暗的墙前，墙的那一边是一种不可忍受的、可怕得使你不敢正视的东西。他在这种梦中总是深感到一种自欺欺人的感觉，因为事实上他知道黑暗的墙后是什么。他只要拼命努力一下，就可以把这东西拉到光天化日之下来，就像从自己的脑子里掏出一块东西来一样。他总是还没有弄清这东西到底是什么就醒来了，不过这东西有些同刚才他打断裘莉亚的时候她正在说的东西有关。
#+END_QUOTE

#+BEGIN_QUOTE
他尤其记得他老是肚子饿，吃饭的时候总要吵个不休。他常常一次又一次哼哼唧唧地问他母亲，为什么没有更多吃的，他常常向她大喊大闹(他甚至还记得他自己的嗓门，由于大喊大叫过早地变了音，有时候洪亮得有些奇怪)，他也常常为了要分到他一些吃的而伪装可怜相。他母亲是很乐意多分给他一些的。她认为他是个“男孩”，分得最多是当然之理；但是不论她分给他多少，他总是嫌不够。每次吃饭时她总求他不要自私，不要忘了小妹妹有病，也需要吃的，但是没有用。她如果不给他多盛一些，他就气得大喊大叫，把锅子和勺子从她手中夺过来，或者把他妹妹盆中的东西抢过来。他也明白这么做，他母亲和妹妹得挨饿，但是他没有办法；他甚至觉得自己有权这么做。他肚中的辘辘饥肠似乎就是他的理由。两餐之间，如果他母亲防卫不严，他还常常偷吃食物柜上一点点可怜的贮藏。

有一天发了巧克力的定量供应。过去已经有好几个星期、好几个月没有发了。他还十分清楚地记得那珍贵的一点点巧克力，二两重的一块(那时候仍用磅秤)，三人分。应该分成等量的三块。但是突然之间，仿佛有人在指使他似的，温斯顿听到自己声如洪钟的要求，把整块巧克力都给他。他母亲叫他别贪心。接着就是没完没了的哼哼唧唧，又是叫，又是哭，眼泪鼻涕，劝诫责骂，讨价还价。他的小妹妹双手紧抱着他母亲，活像一只小猴子，坐在那里，从他母亲的肩后望过来，眨着大眼睛悲伤地看着他。最后他母亲把那块巧克力掰了四分之三，给了温斯顿，把剩下的四分之一给了他妹妹。那小姑娘拿着巧克力，呆呆地看着，好像不知它是什么东西。温斯顿站着看了一会儿。接着他突然跃身一跳，从他妹妹手中把那块巧克力一把抢走就跑到门外去了。

“温斯顿，温斯顿！”他母亲在后面叫他。“快回来！把你妹妹的那块巧克力还给她！”

他停了下来，但没有回来。他母亲的焦虑眼光盯着他的脸。就是在这个时候，她也在想那就要发生的事，即使他不知道究竟是什么。他妹妹这时意识到有东西给抢走了，软弱地哭了几声。他母亲搂紧了她，把她的脸贴在自己的胸口上。这个姿势使温斯顿意识到他妹妹快要死了。他转过身去，逃下了楼梯，巧克力捏在手中快要化了，有点黏糊糊的。

他以后没有再见到他母亲。
#+END_QUOTE

孩子，冷漠地让人害怕

#+BEGIN_QUOTE
一旦处在党的掌握之中，不论你有感觉还是没有感觉，不论你做一件事还是不做一件事，都无关重要。不论怎么样，你还是要消失的，不论是你或你的行动，都不会再有人提到。历史的潮流里已没有你的踪影。
#+END_QUOTE

#+BEGIN_QUOTE
圣克利门特教堂的钟声说，橘子和柠檬，圣马丁教堂的钟声说，你欠我三个铜板，老巴莱教堂的钟声说，你什么时候归还？肖尔迪区教堂的钟声说，等我发了财。
#+END_QUOTE

#+BEGIN_QUOTE
如果人人都能享受闲暇和生活保障，原来由于贫困而愚昧无知的绝大多数人就会学习文化，就会独立思考。
#+END_QUOTE

由此可见，学习文化能够让我们接近独立思考

** 第三部

#+BEGIN_QUOTE
在这里招供的都是真的。我们想办法做到这些供词是真的。
#+END_QUOTE

通过修改过去的各种媒体，使得逼供的证词成为现实

#+BEGIN_QUOTE
温斯顿，你是白玉上的瑕疵。你是必须擦去的污点。我刚才不是对你说过，我们同过去的迫害者不同吗？我们不满足于消极的服从，甚至最奴颜婢膝的服从都不要。你最后投降，要出于你自己的自由意志。
#+END_QUOTE

#+BEGIN_QUOTE
我们在杀死他之前也要把他改造成为我们的人。我们不能容许世界上有一个地方，不论多么隐蔽，多么不发生作用，居然有一个错误思想存在。甚至在死的时候，我们也不容许有任何脱离正规的思想。
#+END_QUOTE

#+BEGIN_QUOTE
党要当权完全是为了它自己。我们对别人的好处并没有兴趣。我们只对权力有兴趣。不论财富、奢侈、长寿或者幸福，我们都没有兴趣，只对权力，纯粹的权力有兴趣。
#+END_QUOTE

#+BEGIN_QUOTE
所有其他寡头政治家，即使那些同我们相像的人，也都是些懦夫和伪君子。德国的纳粹党人和俄国的共产党人在方法上同我们很相像，但是他们从来没有勇气承认自己的动机。他们假装，或许他们甚至相信，他们夺取权力不是出于自愿，只是为了一个有限的时期，不久就会出现一个人人都自由平等的天堂。我们可不是那样。我们很明白，没有人会为了废除权力而夺取权力。权力不是手段，权力是目的。
#+END_QUOTE

#+BEGIN_QUOTE
建立专政不是为了保卫革命；反过来进行革命是为了建立专政。迫害的目的是迫害。拷打的目的是拷打。权力的目的是权力。
#+END_QUOTE

#+BEGIN_QUOTE
你必须明白的第一件事情是，权力是集体的。个人只是在停止作为个人的时候才有权力。你知道党的口号‘自由即奴役’。你有没有想到过这句口号是可以颠倒过来的？奴役即自由。一个人在单独和自由的时候总是要被打败的。所以必然如此，是因为人都必死，这是最大的失败。但是如果他能完全绝对服从，如果他能摆脱个人存在，如果他能与党打成一片而做到他就是党，党就是他，那么他就是全能的、永远不朽。
#+END_QUOTE

#+BEGIN_QUOTE
温斯顿，一个人是怎样对另外一个人发挥权力的？

温斯顿想了一想说：

“通过使另外一个人受苦。”
#+END_QUOTE


2025年读完的第54本，总阅读量第54本