#+TITLE: 【读书记60】穷查理宝典 by Charlie Munger
#+DATE: <2025-11-29 Sat 12:00>
#+TAGS[]: 读书记


https://www.stripe.press/poor-charlies-almanack/cover

https://www.poorcharliesalmanack.com/

https://www.acquired.fm/episodes/charlie-munger

** 献给查理·芒格

芒格将会用他自己的话来告诉你：

获取普世的智慧，

并相应地调整你的行为。

即使你的特立独行让你在人群中不受欢迎……

那就随他们去吧。

** 中文版序言 书中自有黄金屋

#+BEGIN_QUOTE
巴菲特说股票本质上是公司的部分所有权，股票的价格就是由股票的价值，也就是公司的价值所决定的。而公司的价值又是由公司的盈利情况及净资产决定的。虽然股票价格上上下下的波动在短期内很难预测，但长期而言一定是由公司的长期价值决定的。而聪明的投资者只要在股票的价格远低于公司实际价值的时候买进，又在价格接近或者高于价值时卖出，就能够在风险很小的情况下赚很多钱。
#+END_QUOTE

公司的价值决定了股票的价格，决定着投资人能够从中收获利益——金钱或其他

#+BEGIN_QUOTE
听完演讲后，我回去立刻找来了有关巴菲特的所有图书，包括他致伯克希尔股东的年信及各种关于他的研究，也了解到芒格先生是巴菲特先生几十年来形影不离的合伙人，然后整整花了一两年的时间来彻底地研究他们，所有的研究都印证了我当时听演讲时的印象。完成了这个调研过程，我便真正自信这个行业是可为的。
#+END_QUOTE

需要以年为单位进行的研究思考，才能掌握芒格巴菲特的思想

#+BEGIN_QUOTE
在1998年的下半年里，我顶住压力、鼓起勇气，连续做出了当时我最重要的三四个投资决定。恰恰是这几个投资在以后的两年里给我和我的投资者带来了丰厚的回报。现在回过头来想，在时间上我是幸运的，但巴菲特和芒格的榜样以及他们的书籍和思想，对我的确起了至关重要的影响。
#+END_QUOTE

时势、胆识，决定了个人在股市的收获

#+BEGIN_QUOTE
在价值投资者看来，投资股市最大的风险其实并不是价格的上下起伏，而是你的投资未来会不会出现永久性的亏损。单纯的股价下跌不仅不是风险，其实还是机会。不然哪里去找便宜的股票呢？就像如果你最喜欢的餐馆里牛排的价格下跌了一半，你会吃得更香才对。买进下跌的股票时是卖家难受，作为买家你应该高兴才对。
#+END_QUOTE

从价值投资的角度来看，股票价格的短期涨跌并不会影响公司的长远价值

#+BEGIN_QUOTE
查理就是如此独特的人，他的独特性既表现在他的思想上，也表现在他的人格上。

比如说，查理思考问题总是从逆向开始。如果要明白人生如何得到幸福，查理首先是研究人生如何才能变得痛苦；要研究企业如何做强做大，查理首先研究企业是如何衰败的；大部分人更关心如何在股市投资上成功，查理最关心的是为什么在股市投资上大部分人都失败了。他的这种思考方法来源于下面这句农夫谚语中所蕴含的哲理：我只想知道将来我会死在什么地方，这样我就不去那儿了。
#+END_QUOTE

从坏的角度思考，如何达成自己的好的目的

#+BEGIN_QUOTE
查理的头脑是原创性的，从来不受任何条条框框的束缚，也没有任何教条。他有儿童一样的好奇心，又有第一流的科学家所具备的研究素质和科学研究方法，一生都有强烈的求知欲和好奇心，几乎对所有的问题都感兴趣。任何一个问题在他看来都可以使用正确的方法通过自学完全掌握，并可以在前人的基础上创新。
#+END_QUOTE

了不起的人物。能够不被束缚、有好奇心、有科学的方法，让自己不断前进，不断进步

#+BEGIN_QUOTE
近代很多第一流的专家学者能够在自己狭小的研究领域内做到相对客观，一旦离开自己的领域不远，就开始变得主观、教条、僵化，或者干脆就失去了自我学习的能力，所以大都免不了瞎子摸象的局限。查理的脑子就从来没有任何学科的条条框框。他的思想辐射到事业、人生、知识的每一个角落。在他看来，世间宇宙万物都是一个相互作用的整体，人类所有的知识都是对这一整体研究的部分尝试，只有把这些知识结合起来，并贯穿在一个思想框架中，才能对正确的认知和决策起到帮助作用。所以他提倡要学习在所有学科中真正重要的理论，并在此基础上形成所谓的“普世智慧”，以此为利器去研究商业投资领域的重要问题。

查理这种思维方式的基础是基于对知识的诚实。他认为，这个世界复杂多变，人类的认知永远存在着限制，所以你必须要使用所有的工具，同时要注重收集各种新的可以证否的证据，并随时修正，即所谓“知之为知之，不知为不知”。事实上，所有的人都存在思想上的盲点。我们对于自己的专业、旁人或是某一件事情或许能够做到客观，但是对于天下万事万物都秉持客观的态度却是很难的，甚至可以说是有违人之本性的。但是查理却可以做到凡事客观。在这本书里，查理也讲到了通过后天的训练是可以培养客观的精神的。而这种思维方式的养成将使你看到别人看不到的东西，预测到别人预测不到的未来，从而过上更幸福、自由和成功的生活。
#+END_QUOTE

客观对待任何知识，承认自己对大部分知识的无知，然后学习它们

#+BEGIN_QUOTE
但即使这样，一个人在一生中可以真正得到的真见卓识仍然非常有限，所以正确的决策必须局限在自己的“能力圈”以内。一种不能够界定其边界的能力当然不能称为真正的能力。怎么才能界定自己的能力圈呢？查理说，如果我要拥有一种观点，如果我不能够比全世界最聪明、最有能力、最有资格反驳这个观点的人更能够证否自己，我就不配拥有这个观点。所以当查理真正地持有某个观点时，他的想法既原创、独特又几乎从不犯错。
#+END_QUOTE

什么叫【不能够比全世界最聪明、最有能力、最有资格反驳这个观点的人更能够证否自己】

是说，如果我有一个观点，只有这个观点还不够，还必须能够对其进行证伪吗

#+BEGIN_QUOTE
查理对我而言，不仅是合伙人，是长辈，是老师，是朋友，是事业成功的典范，也是人生的楷模。我从他的身上不仅学到了价值投资的道理，也学到了很多做人的道理。他让我明白，一个人的成功并不是偶然的，时机固然重要，但人的内在品质更重要。
#+END_QUOTE

时机是重要的，品质比时机更重要

#+BEGIN_QUOTE
查理一生研究人类失败的原因，所以对人性的弱点有着深刻的理解。基于此，他认为人对自己要严格要求，一生不断提高修养，以克服人性本身的弱点。这种生活方式对查理而言是一种道德要求。在外人看来，查理可能像个苦行僧，但在查理看来，这个过程却是既理性又愉快，能够让人过上成功、幸福的人生。
#+END_QUOTE

对自己严格要求、在一生中不断提高修养以克服人性本身的弱点

** 导读

#+BEGIN_QUOTE
查理进行观察和作出推论的基础是根本的人性、基本的真理和许多学科的核心原理。
#+END_QUOTE

有所为=洞察人性+基本真理+多学科的核心原理

#+BEGIN_QUOTE
查理正是以这种价值观闻名的：活到老学到老，对知识抱有好奇心，遇事冷静镇定，不心生妒忌和仇恨，言出必行，能从别人的错误中吸取教训，有毅力恒心，拥有客观的态度，愿意检验自己的信念等等。
#+END_QUOTE

这些美好品质，如果自己能够做到，的确能改变自己的人生

#+BEGIN_QUOTE
查理认为生活的决定比投资的决定重要。他那来自各种学科的思维模型反复地出现，却从不关注“企业组合投资策略”、“beta系数”或者“资产定价模型”，而是以基本的公理、人类的成就、人性的弱点和通往智慧的崎岖道路为中心。查理曾经说：“就像约翰·梅纳德·凯恩斯男爵那样，我想通过发财致富来变得独立。”对于查理而言，独立是赚钱的目的，而不是倒过来。
#+END_QUOTE

使用多学科思维方式，来指引自己的生活。赚钱不是目的，赚钱是达到独立这一目的的手段

** 关于本书

#+BEGIN_QUOTE
“如果你轻车熟路地走上跨学科的途径，你将永远不想往回走。那就像砍断你的双手。”
#+END_QUOTE

#+BEGIN_QUOTE
要特别指出的是，查理会反复地使用一些用语和例子。他是有意的：他知道对于要达到他所倡导的那种有深度的“熟练”来说，重复是教导的核心。
#+END_QUOTE

重复可以让我们更加深刻地理解抽象概念

** 第一章
*** 查理·芒格传略

#+BEGIN_QUOTE
只要相互支持，芒格家族就能度过美国历史上最糟糕的经济崩溃。
#+END_QUOTE

家族团结

#+BEGIN_QUOTE
“由于受到第二次世界大战期间各种因素的刺激，我曾短暂地钻研过基础物理学。这次钻研极大地提高了我的智慧。
#+END_QUOTE

物理学提高智慧

#+BEGIN_QUOTE
任何人要想获得成功，都应该学习物理学，因为它的概念和公式十分美丽地展现了正确理论的力量。
#+END_QUOTE

物理定律的特点：经由精确的语言和准确的公式，表达关于世界的基本规则

#+BEGIN_QUOTE
合伙人最好能够独立工作。你可以当一名指挥型的合伙人、服从型的合伙人，或者一名总是平等协作的合伙人。我三种都当过。人们无法相信我突然让自己变成沃伦的一名服从型合伙人，但有些人很好，你成为他的服从型合伙人也挺好的。我并没有妄自尊大，对此无法接受。总是会有人在某些方面比你优秀。你必须先成为下属，然后才能成为领导。人们应该学会扮演各种角色。
#+END_QUOTE

人们应该学会扮演各种角色，使自己的经验不断丰富

#+BEGIN_QUOTE
查理说：“我本人是个传记爱好者。我认为当你试图让人们学到有用的伟大概念时，最好是将这些概念和提出它们的伟人的生活与个性联系起来。我想你要是能够和亚当·斯密交朋友，那你的经济学肯定可以学得更好。和‘已逝的伟人’交朋友，这听起来很好玩，但如果你确实在生活中与那些有杰出思想的已逝的伟人成为朋友，那么我认为你会过上更好的生活，得到更好的教育。这种方法比简单地给出一些基本概念好得多。”
#+END_QUOTE

与已经离世的伟人交朋友，榜样的力量带动我们产生改变

#+BEGIN_QUOTE
虽然查理自称是保守的共和党人，但他却大力提倡计划生育。他认为女性只有热爱孩子才能生育。他还资助各种旨在改善教育环境和教育质量的活动。身为8个孩子的父亲和16个孙辈的祖父，查理认为他的财富应该用于帮助子孙继承一个更美好的世界。
#+END_QUOTE

“计划生育”，对于部分中国人来说，并不陌生

*** 歌颂长者：芒格论晚年

#+BEGIN_QUOTE
持有和西塞罗相同的政治观点之后，我曾多次暗中以为，我提倡这种政治制度，是为我的同胞着想。但现在我觉得，一个人很少完全清楚他自己的动机。因此，我现在认为，我之所以赞同这种观点，在很大意义上是因为认识到在西塞罗的价值系统中，我将很有可能飞黄腾达。
#+END_QUOTE

一种思想体系让人更为成功，它的拥趸愈多。如果一个人在开始的某个阶段没有财富，或许寻找那些让自己成功的思想无可厚非，因为财富能给人独立，让人不必为物质发愁，充分开拓精神

#+BEGIN_QUOTE
《论老年》最著名的段落当属下面这段了不起的总结：“晚年的最佳保护铠甲是一段在它之前被悉心度过的生活，一段被用于追求有益的知识、光荣的功绩和高尚的举止的生活；过着这种生活的人从青年时代就致力于提升他自己，而且将会在晚年收获它们产生的最幸福的果实；这不仅是因为有益的知识、光荣的功绩和高尚的举止将会陪伴他终生，甚至直到他生命的最后一刻，也会因为见证了正直的人生的良心和对过往美好功绩的回忆将会给灵魂带来无上的安慰。”
#+END_QUOTE

有益的知识、光荣的功绩和高尚的举止，见证美好人生

*** 忆念：晚辈谈芒格

#+BEGIN_QUOTE
大约在我15岁的时候，我们全家去太阳谷滑雪；假期的最后那天，爸爸和我冒着风雪开车出去，他绕了十分钟的路去给我们开的那辆红色吉普车加油。当时他正争分夺秒地让我们全家能赶得上回家的飞机呢，所以到加油站后当我发现油箱里还有半箱油时，我感到很吃惊。我问爸爸，还有那么多汽油，我们为什么要停下来；他教导我说：“查理，你要是借了别人的车，别忘了加满油再还给人家。”

我在斯坦福念大一时，有个熟人把车借给我。倒不是因为他跟我关系很好，而是因为一个我们都认识的朋友迫使他这么做。那辆奥迪佛克斯是红色的，油箱里还有一半油。所以我想起了吉普车的事，先把油加满了，再将车还回去。他发现了。自那以后，我们共同度过了很多美好的时光，我结婚的时候，他是我的伴郎。

从斯坦福毕业之后，我才知道当年度假时我们住的是瑞克·格伦的房子，开的是瑞克·格伦的吉普。瑞克是爸爸的朋友，当他回到太阳谷，就算吉普车的汽油比他离开的时候少，他也自然不会介意，甚至可能都不会发现。但爸爸无论什么事情都做得公平和周到。所以那天我不仅学到了如何交朋友，还学到了如何维护友谊。
#+END_QUOTE

无论做什么事情都会做到公平和周到

#+BEGIN_QUOTE
这是个可怕的错误，我们不希望你再犯同样的错误。但人孰无过呢，我们可以不追究这件事。你做了正确的事情，就是承认你的错误。如果你试图掩盖错误，或者拖延一段时间再坦白，你将会离开这家公司。不过现在我们希望你留下来。
#+END_QUOTE

勇于承认自己的错误

#+BEGIN_QUOTE
这个故事发生的时候我们还住在明尼苏达州。当时我已到了可以开车的年纪，去卡斯湖镇接送女佣是我的一项任务。这项任务不是光开车就可以完成的，我必须先开船越过卡斯湖，到了对岸的码头再开车去镇上，然后沿原路返回。我每天早晨的任务还包括在镇上买报纸。嗯，有一天风雨交加，湖面上的浪很大。经过所有的惊险和困难，我终于去镇上把女佣接了回家，可是忘了买报纸。查理问我：“报纸在哪？”我说没买。他停顿了一秒钟之后说：“再去一次，把报纸买回来，以后别忘记了！”所以我只好冒着风雨回镇上买报纸，湖面上波涛汹涌，风雨扑打着小船，当时我告诉自己，我再也不会让这样的事情发生了。
#+END_QUOTE

把工作一次就做好

#+BEGIN_QUOTE
每年夏天，查理的母亲都会从奥马哈开车到明尼苏达。她在明尼苏达的时候，我们有事可以用她的车。但车的钥匙只有一套。有一次，我和几个朋友在帆船上玩，车钥匙从我口袋里掉进了五英尺深的浑水。我回家坦白了。那里是明尼苏达北部的大森林地区，根本就没几个锁匠，而且查理也无法容忍如此愚蠢的行为。同样不到一秒钟之后，他提出了解决方法：“和你的朋友们潜到水底去找钥匙，没找到别回家。”在水底找了差不多两个小时之后，太阳快要下山了，我看到前面的水草丛中奇迹般地闪耀着金属的光芒，我终于可以回家了。
#+END_QUOTE

承担责任

#+BEGIN_QUOTE
父亲思考时能够抵制绝大多数的外界干扰，如果你试图在此时引起他的注意，你会觉得他让人又好气又好笑。但正是有了这种能力，他才会如此成功。
#+END_QUOTE

我也可以做到，像查理这样专注地思考

#+BEGIN_QUOTE
在明尼苏达，他找到一种方法把同样的信息灌输给我们。他请原来的拉尔森造船公司为我们制作了“水上飞机”；那是一片厚实的木板，他开船拖着它，让我们站在它上面。他会突然拐弯，看我们是否还能站稳；唯一能够避免掉进水里而出丑的方法是不停地调节力道来抵消角度变化引起的失衡。从那时起，直到现在和将来，如果有任何念头或者行动似乎将要朝这个或者那个方向离开我的控制，我就会感到深深的恐惧。
#+END_QUOTE

在自己能够掌控的范围内，全力让自己进步

*** 朋友们如是说
*** 沃伦·巴菲特答问录
*** 苏丝·巴菲特答问录
*** 芒格、托尔斯&奥尔森律师事务所
*** 查理·芒格的投资合伙公司的投资业绩
*** 沃伦和瑞克谈“船长查理”
*** 查理·芒格的慈善课程
*** 富兰克林论衰老
** 第二章 芒格的生活、学习和决策方法
*** 芒格进行商业分析和评估的“多元思维模型”
*** 芒格的投资评估过程
*** 投资原则检查清单
*** 诚实是最好的策略
*** L·O·L·L·A·P·A·L·O·O·Z·A效应
*** 多元思维模型
*** 纪律和耐心 泰德·威廉姆斯的77格击球区
*** 查理论诚实：在2004年西科年会上的讲话
** 第三章 芒格主义：查理的即席谈话
*** 我们成功的关键
*** 论伯克希尔·哈撒韦
*** 对巴菲特的评论
*** 投资建议
*** 谈市场
*** 对企业管理层的批评
*** 对基金管理企业的批评
*** 对华尔街的批评
*** 对会计的批评
*** 对股票期权的批评
*** 对金融机构和衍生品的警告
*** 对律师、律师事务所和诉讼的批评
*** 思维模型
*** 对高等教育的批评
*** 怎样变得幸福、富裕，以及其他建议
*** 幽默
*** 辛普森谈芒格
*** 芒格谈辛普森
*** 塞内加尔谈芒格
*** 芒格谈塞内加尔
** 第四章 查理十一讲
*** 第一讲 在哈佛学校毕业典礼上的演讲
*** 第二讲 论基本的、普世的智慧，及其与投资管理和商业的关系
*** 第三讲 论基本的、普世的智慧（修正稿）
*** 第四讲 关于现实思维的现实思考？
*** 第五讲 专业人士需要更多的跨学科技能
*** 第六讲 一流慈善基金的投资实践
*** 第七讲 在慈善圆桌会议早餐会上的讲话
*** 第八讲 2003年的金融大丑闻
*** 第九讲 论学院派经济学：考虑跨学科需求之后的优点和缺点
*** 第十讲 在南加州大学古尔德法学院毕业典礼上的演讲
*** 第十一讲 人类误判心理学

二十二、权威——错误影响倾向

#+BEGIN_QUOTE
由于人类的反应大多数是自动的，追随领袖的倾向也并不例外，所以当领袖犯错的时候，或者当领袖的想法并没有得到很好的传达、被大众所误解的时候，追随领袖的人就难免会遭受极大的痛苦。
#+END_QUOTE

#+BEGIN_QUOTE
在飞行模拟训练中，人们也注意到这类情况。副机长在模拟训练中必须学会忽略机长某些真正愚蠢的命令，因为机长有时会犯严重的错误。然而，即使经过这种严格的训练，副机长在模拟飞行中仍然非常频繁地让模拟飞机由于机长某些极其明显的严重错误而坠毁。
#+END_QUOTE

#+BEGIN_QUOTE
对权威人物不应该的尊敬造成了这种情况：这位总裁和许多甚至比他更糟糕的管理人员明明早就该被革除职务，却继续担任一些重要商业组织的领导人。内中蕴含的意义不言自明：选择将权力交给谁时要很谨慎，因为权威人物一旦上台，将会得到权威——错误影响倾向的帮助，那就很难被推翻。
#+END_QUOTE

二十三、废话倾向

#+BEGIN_QUOTE
聪明的行政机构应该采取一种非常重要的做法，就是让那些啰里啰唆、喜欢说废话的人远离严肃的工作。
#+END_QUOTE

二十四、重视理由倾向

#+BEGIN_QUOTE
人，尤其是生活在发达文化中的人，天生就热爱准确的认知，以及获取准确认知过程中得到的快乐。
#+END_QUOTE

这种倾向既能帮助人们，又能让人们误入歧途。

二十五、lollapalooza倾向——数种心理倾向共同作用造成极端后果的倾向

最后、问与答


*** 最新的普世智慧：查理答问录
*** 查理的检查清单
*** 赛马就是投资，投资就是赛马
*** 事关信任
** 第五章 文章、报道与评论
*** 如果说标准石油正在试图变得贪婪的话，那么它的表现可不够好
*** 巴菲特的副手…… 查理·芒格和伯克希尔的主席所见略同
*** 互助储蓄与贷款联盟的请辞信
*** 反托拉斯法的滥用
*** 芒格科学中心接近完工
*** 不那么沉默的合伙人
*** 乐观主义在会计中没有容身之地
*** 贝西克兰兴衰记 关于一个国家如何陷入经济崩溃的寓言
*** “贪无厌”“高财技”“黑心肠”和“脑残”国的悲剧
*** 过去与未来：副董事长致辞
** 查理·芒格推荐书目
** 查理·芒格年谱


@@html:<span style="color:#8B0000">2025年读完的第60本，总阅读量第60本</span>@@