#+TITLE: 【读书记89】福格行为模型 by B.J.福格
#+DATE: <2025-12-30 Tue 12:00>
#+TAGS[]: 读书记


一个可以生成B=MAP图的小工具：[[https://fogg-behavior-model-tianheg.vercel.app/][这里]]

** 适合我的执行方案



** 推荐序1

#+BEGIN_QUOTE
我们的关注点都是愿望。愿望从来不会改变现实，行动才会。
#+END_QUOTE

要想改变，需要行动，需要每次一步一步地完成计划。

#+BEGIN_QUOTE
B=MAP

行为（发生于）动机 & 能力 & 提示（同时出现的时候）
#+END_QUOTE

制作焦点地图

这本手册提供了7个可以解决无法行动问题的方法，前三种分别是

1. 明确愿望
2. 确定做什么可以实现愿望
3. 确定哪些是目前的条件可以做到的

推荐序3

◆ 这就像是要读完一本很厚的书，翻开书只读一页，就已经朝着成功迈进了一步，值得庆祝。如果急躁地要求自己在某个时间段内读完，那也许没几个人能坚持下来


中文版序

◆ 微习惯的精髓——让你通过感觉良好而不是感觉糟糕来实现改变


前言

◆ 要想设计出成功的习惯并改变自身行为，你需要做到3件事：·　停止自我批评；·　把你的愿望拆解成微行为；·　将每一次错误当成是一种新发现，并利用它们不断改进。

◆ 即使我本来就是一名行为科学家，我也必须去学习如何养成某种生活习惯。这并不是自然而然就能学会的

◆ 如果我们能为人们提供正确的信息，就能改变人们的态度，进而改变人们的行为。我将这种观点称为“信息–行动谬误”

◆ 从小改变着手的5个原因

◆ 原因1，可以利用碎片时间

◆ 原因2，可以立刻开始改变

◆ 原因3，不需要担心会失败

◆ 原因4，一样能吃掉“大鲸鱼”

◆ 原因5，不需要依赖动机或意志力也能做到

◆ 将有意识的动作快速转化为无意识的习惯。

◆ 这些行为都由相同的要素组成。它们是人类行为的基本要素，其相互关系驱动我们的每一个行为和反应。

◆ 人们在感觉良好而不是感觉难过的状态下进行改变，效果最佳。


明明拥有动机却还是无法改变的5个原因

◆ 人物（person）、行动（action）和情境（context）是理解人类行为的基础。

◆ 在行为设计领域，我们将动机短期激增的现象称为动机波浪。你以前一定有过这样的经历：你的动机冲到顶峰，随后急转直下。或许你会责备自己没能坚持下来，但这不怪你，这就是动机在生活中的运作方式。

◆ 把时间和精力用在激励自己或他人追逐不明确的概念上，则是错误的举动。

◆ 动机是最不可预测和最不可靠的。如果你以前只关注动机，那么现在，我希望你能够理解，想获得持久的改变，仅靠动机是不够的，因为你多半无法维持它，也可能无法对它进行可靠的操作或设计。


轻松找到你的黄金行为

◆ 焦点地图


“珍珠习惯”，管理压力与焦虑

◆ 珍珠习惯


2025年读完的第89本,总阅读量第89本