#+TITLE: 【读书记77】希望之书：珍·古道尔谈人类的生存、未来与行动 by 珍·古道尔 道格拉斯·艾布拉姆斯
#+DATE: <2025-12-30 Tue 12:00>
#+TAGS[]: 读书记


#+BEGIN_QUOTE
不要放弃对自己未来的希望呀！
#+END_QUOTE

** 🎯 阅读契机与目标

- **为什么读：**好奇珍到底在讲希望的哪些方面
- **期望获得：**了解这本书的内容


** 💡 启发与互联 (The Thinking)
*** 1. 精彩金句与我的“杠杠”

#+BEGIN_QUOTE
不屈的精神可以战胜极端的虐待和痛苦，重塑一个完整的人格。

**[我的评论]**：真的是这样吗？我的生活中很少有这种强烈的情感体验
#+END_QUOTE

#+BEGIN_QUOTE
虽然我们两个人的能力有限，但是我们可以有我们这种精神。所以，让我们的后代和世人看看两个残疾人做到的事情吧。以后我们不在了，他们也已然能够看到一个盲人和一个没有胳膊的人给他们留下的森林。

**[我的评论]**：两个中国残疾人为改变周围的环境，而努力种树的故事
#+END_QUOTE

#+BEGIN_QUOTE
有决心、有方向的人可以激发他人一起为解决问题去努力？要帮助人们意识到，作为一个个体，他或她很重要。每个人都有自己的角色。每个人来到这个世界上都是有原因的。

**[我的评论]**：我在这个世界的任务是什么呢？
#+END_QUOTE

#+BEGIN_QUOTE
我想象着世界各地的人们以各自微小但力所能及的方式修复人类已造成的伤害，觉得珍的比喻令人既感到安慰又深受鼓舞。

**[我的评论]**：这个世界已经被破坏得千疮百孔，但是还有无数像珍这样的人愿意付出自己的余生去逆转各种破坏
#+END_QUOTE


◆ 它太特别了，”珍说，“比我认识的其他的狗都要聪明。是它教我意识到动物有解决问题的头脑，也有情感和鲜明的个性，给我开展黑猩猩研究带来了很大帮助。

◆ 珍仍然向我展示了保持希望的几个深刻理由：它在我们不可思议的智识里，在自然的韧性里，在当今青年的活力和承诺里，当然也在人类的不屈精神里。珍目睹了如此多发生在世界各地的人们与动物身上的残忍和痛苦之事，如此多的对自然的破坏之事，是什么让她在痛心之后仍然站成了希望的灯塔？这种能力是她与生俱来的吗？

◆ “成长于第二次世界大战教会了我很多东西——我懂得了食物和衣服的价值，因为一切都是定量供应的。我懂得了死亡和人性残酷的真相，一边是爱、同情心和勇气，一边是暴力和对他人难以置信的残忍。


从青涩的年轻女性到全球公众演说家

◆ 我认为很多人都怀有不自知的天赋，只是还没有机缘逼他们发挥出来


“姑且说这是一项使命吧”

◆ 是人生席卷着我，把我扫到了它的道路

◆ 自然规律性的和谐——

◆ 自然规律性的和谐……揭示出了一种如此深邃的理性；与此相比，人类一切有意义的思考和安排都只不过是其微乎其微的反映。


是巧合吗？

◆ “你总是会留意机会吗？”“对，哪怕是很累的时候，我也会在心里问自己，我会在飞机上或者会议上坐在这个人旁边，是不是有什么原因？总之，付出一点努力是值得的，万一有其原因呢。我那样认识过好些有趣的人，其中一些成了我的朋友和支持者。”

◆ 我并不相信命运或定数。我相信自由选择，

◆ ’我相信当一个机会出现时，你要么抓住它，要么弃之不顾——或者根本无知无觉。


精神进化之旅

◆ 但现在已经有越来越多的人意识到我们正变得愈加物质主义，需要在精神上与自然世界重新建立联系

◆ 作为一个物种，我们人类正沿着道德进化的道路前进。我们会辩论是与非、作为个体应如何对待他人和社会，以及建立民主政体的种种努力。也有人同时在精神进化的路上向前走着

◆ 道德进化和精神进化的区别何在


珍的下一场伟大冒险

◆ 外祖母笑着说：‘我想你今晚应该给我写好讣告，亲爱的。’第二天早上妈妈进去的时候，外祖母安详地躺在床上，已经走了。她胸前抱着‘拳击手’所有的来信，用红丝带系着，边上附有一张便条——‘请在我的最后一次旅行中为我带上’。”

◆ 想起了那则著名的犹太传说：有一位叫祖沙的拉比临终前在床上哭，别人问他为什么，他说：“我知道上帝不会问我为什么没有成为摩西或者大卫王，但他会问我为什么没有成为祖沙，那我该怎么回答呢？”

◆ 但我会告诉他们一些关于濒死体验的神奇故事。伊丽莎白·库伯勒——罗斯对这个课题开展过相当多的研究


结语 一则来自珍·古道尔的希望的讯息

◆ 在这个世界上，每个人都应该能够体面地生存，同时与自然和谐地共处

◆ 我们应该感恩自然惊人的韧性。我们也可以去帮助大自然恢复，不仅仅是通过大型生态修复项目，我们个人所选择的生活方式和对环境足迹的考量，都是让大自然得以恢复的强大力量


2025年读完的第77本,总阅读量第77本