#+TITLE: 【读书记87】窗边的小豆豆 by Tetsuko Kuroyanagi（黑柳彻子）
#+DATE: <2025-12-25 Thu 12:00>
#+TAGS[]: 读书记


1. 250907 最近又读了一次，回顾了一些故事的细节

Totto-Chan: The Little Girl at the Window


真是了不起，这本书的中文版竟然印刷了221次。

这本书小学的时候读过，初中时又读了很多遍，至今仍然对巴学园的校长怀有深深的敬意。

-----

#+BEGIN_QUOTE
妈妈没有告诉小豆豆这次退学的事情。因为，即便和小豆豆说了，她恐怕也不会理解自己哪里做错了吧。而且，如果小豆豆因为退学这件事，在心里留下自卑的情结，那就不好了。​“等她长大以后，再找个机会告诉她吧。​”
#+END_QUOTE

-----

#+BEGIN_QUOTE
小豆豆挣脱妈妈的手，蹦跳着跑上台阶。突然，她猛地停住，转过身来，差点和走在后面的妈妈撞个满怀。

“怎么了？​”

妈妈以为小豆豆又改变主意了，慌忙问道。小豆豆正好站在最高一级台阶上，神色认真地小声问妈妈：

“哎，我们要去见的那个人，是车站的人吧？​”

妈妈不愧是一位极有耐心的人……或许，妈妈也觉得挺有趣的吧，她把脸靠近小豆豆，也小声问：

“为什么这么说呢？​”

小豆豆越发压低了声音说：

“因为，妈妈说他是校长先生，可是他有这么多电车，可能他实际上是车站的人吧？​”

确实，把废旧的电车当作教室，这样的学校实在稀罕，也许小豆豆的想法不无道理。妈妈这样想着，可这个时候已经没有时间去解释了，便说道：

“那你可以自己问问校长先生。你想一想，爸爸是拉小提琴的，他有好几把小提琴，可是他并不是卖小提琴的。这样的人也是有的呀。​”
#+END_QUOTE

-----

#+BEGIN_QUOTE
无论是之前，还是这以后，再也没有一个大人这么认真地听小豆豆说话了。
#+END_QUOTE

哀伤

-----

#+BEGIN_QUOTE
一般的学校都是按照每个时间段，有顺序地上课。比如第一节课是语文的话，就上语文；第二节课是算术的话，就上算术。可是这个学校却完全不一样。在第一节课开始的时候，女老师就把当天要上的所有的课，还有每一节课要学习的所有问题点，满满地写在黑板上，然后说：“下面开始上课，从你喜欢的那门课开始吧。​”

这样上课的话，随着年级的升高，老师就能逐渐掌握每一个学生的兴趣所在，以及他感兴趣的方式、对问题的思考方法等。由此，老师能清楚地了解每个学生的个性。对老师而言，在了解学生的基础上因材施教，是最有效果的上课方法。
#+END_QUOTE

奇特的教学方式、因材施教

-----

#+BEGIN_QUOTE
她认为“能把想说的话如此简练地表达出来，这样的成年人，除了校长先生之外，没有第二个了”​。
#+END_QUOTE

我也在学习如何用简练的语言，表达清楚自己的意思

-----

#+BEGIN_QUOTE
实际上，在小豆豆的满足之中，还有一点是因为“校长先生对我做的事没有生气，很信任我，把我当作一位很有人格的人来尊重”​。
#+END_QUOTE

-----

#+BEGIN_QUOTE
这是既没有星星，也没有月亮的露营。但是孩子们在小小礼堂里的露营，却使他们从心底感到满足。
#+END_QUOTE

-----

#+BEGIN_QUOTE
小豆豆跟在泰明后面，用手抬泰明的脚，用头顶住泰明的屁股。泰明也用尽了全力，一点儿一点儿地，终于爬到了梯凳的顶部。
#+END_QUOTE

细节动人

-----

#+BEGIN_QUOTE
韵律是让身体的组织结构更加精巧的游戏，是教给我们怎样去开动心灵的游戏，是让心灵和身体理解节奏的游戏。
#+END_QUOTE

-----


#+BEGIN_QUOTE
过于依赖文字和语言的现代教育，恐怕会使孩子们用心去感受自然、倾听神灵之声、触摸灵感的能力渐渐衰退吧？
#+END_QUOTE

大概吧

-----

#+BEGIN_QUOTE
世界上最可怕的事情，莫过于有眼睛却发现不了美，有耳朵却不会欣赏音乐，有心灵却无法理解什么是真。不会感动，也不会充满激情……
#+END_QUOTE

-----

#+BEGIN_QUOTE
一生的心愿，就这么早早地夭折了……这是小豆豆的人生中，第一次品尝到“别离”的滋味。
#+END_QUOTE

别离的滋味

-----

#+BEGIN_QUOTE
以后，孩子们能够在别人面前，清楚、自由、毫不羞涩地表达出自己的想法，是绝对有必要的。
#+END_QUOTE

我还是有些羞涩的

-----

#+BEGIN_QUOTE
夏末的月亮，在院子上方升起，好像在温柔地看着这一对更加亲近的好朋友：那个缠满了绷带的女孩儿，和那只永远也不会再玩“狼游戏”了的小狗……
#+END_QUOTE

-----

#+BEGIN_QUOTE
说起运动会的奖品，也富有校长先生的特色。一等奖是“一根萝卜”，二等奖是“两根牛蒡”，三等奖是“一束菠菜”之类。以至于小豆豆长大以后，还以为无论什么地方都是用蔬菜当运动会的奖品
#+END_QUOTE

-----

#+BEGIN_QUOTE
可是，那几个孩子看着对方做手势的时候，眼睛里都洋溢着光彩。小豆豆觉得那样子美丽极了，她期待着有一天，会和他们成为朋友
#+END_QUOTE

-----

#+BEGIN_QUOTE
小豆豆还喜欢丸山老师的声音，他的声音是那么温和，让人觉得它和老师厚厚的镜片后面小小的眼睛，以及老师胖胖的身体有些不相称
#+END_QUOTE

-----

#+BEGIN_QUOTE
小豆豆是日本人，正男呢，是叫作朝鲜的国家的人。但是，你和正男一样都是小孩子。所以，绝对不能区分说‘那个人是日本人’，或者‘那个人是朝鲜人’。要友好地对待正男，只因为他是朝鲜人，就被人这样粗暴地叫来叫去，是很可怜的
#+END_QUOTE

-----

#+BEGIN_QUOTE
正男妈妈的声音，有一种异样的焦虑感，仿佛夹杂着某种不安，拖着长长的尾音。她的声音有时会被旁边通过的电车声淹没，但这句“正男！”的叫声，是这么寂寞，如泣如诉，让人只要听过一次，就永远难以忘怀。
#+END_QUOTE

寂寞，如泣如诉

-----

#+BEGIN_QUOTE
在小豆豆看来，辫子是“成熟女人”的象征，看到扎了小辫子的小豆豆，也许大家会像对待成年女子那样说“不好意思”，谁知道竟然…
#+END_QUOTE

-----

#+BEGIN_QUOTE
小豆豆有些吃惊，因为她还从来没有听说过“对女孩要友好”这样的话。趾高气扬的总是男孩。
#+END_QUOTE

-----

#+BEGIN_QUOTE
这天发生的事情，对大荣君来说，也是一个很大的触动。“要爱护女孩，要对她们友好。”这是他永远不会忘记的回忆。为什么这么说呢？因为大荣君在巴学园期间，被校长先生教训的经历，无论是在这以前，还是在这之后，就仅仅这么一回。
#+END_QUOTE

要爱护女孩，对她们友好

-----

#+BEGIN_QUOTE
在他的身后，是一片纯白的世界，无边无垠地伸展开去。
#+END_QUOTE

-----

#+BEGIN_QUOTE
如果觉得‘旁边太吵闹了，我没法学习’，那就很麻烦了。要练习无论周围怎么嘈杂，都能立刻集中精力。
#+END_QUOTE

周围无论怎么嘈杂，都能集中精力学习

-----

#+BEGIN_QUOTE
校园里的树木，又长出了柔软的绿叶，花坛里的花朵，也急急忙忙绽放。
#+END_QUOTE

-----

#+BEGIN_QUOTE
妈妈从来不对小豆豆说“应该去干什么”，小豆豆如果说“我想干什么”的时候，妈妈就会说“好啊”，然后并不多问，但她会把孩子们做不了的手续上的事情帮孩子做好
#+END_QUOTE

-----

#+BEGIN_QUOTE
当她看到奇怪的事情、有趣的事情时，为了满足自己的好奇心，经常做出让老师们大吃一惊的事来
#+END_QUOTE


@@html:<span style="color:var(--dushuji-count-color)">2025年读完的第87本，总阅读量第87本</span>@@