#+TITLE: 【读书记96】狂热分子 True Believer : Thoughts on the Nature of Mass Movements by Eric Hoffer
#+DATE: <2025-12-30 Tue 12:00>
#+TAGS[]: 读书记


https://en.wikipedia.org/wiki/The_True_Believer

** 序言 狂热分子的心灵

#+BEGIN_QUOTE
所有群众运动都会激发起其追随者赴死的决心和团结行动的意愿；不管它们宣扬的主张或制定的纲领为何，所有群众运动都会助长狂热、激情、热望、仇恨和不宽容；所有群众运动都能够从生活的某些部门释放出强大的动能；它们全都要求信徒盲从和一心一意效忠。
#+END_QUOTE

群众运动的特点

#+BEGIN_QUOTE
没有任何话比蒙田所言更能道出我的心声：“我要说的一切都是通过论述，而非通过说教。如果我的目的是说服别人，话就不会说得那么满。”
#+END_QUOTE

** 第一部 群众运动的吸引力
*** 第一章 对改变的渴望

#+BEGIN_QUOTE
很多人参加革命运动，是因为憧憬革命可以急遽而大幅地改变他们的生活处境。这是个不言自明的道理，因为革命运动明明白白就是一种追求改变的工具。
#+END_QUOTE

#+BEGIN_QUOTE
要是蒋介石知道怎样发起一个扎实的群众运动，或者至少懂得怎样让因日本侵华而点燃的爱国激情维持不坠，那他现在说不定已被尊为革兴中国的巨人。但因为他不懂得这样做，所以才会被精通“religiofication”（宗教化）艺术的大师给推到一边去——所谓的“宗教化”艺术，就是给实际目的披上神圣大衣的艺术。
#+END_QUOTE

#+BEGIN_QUOTE
我们都有一种倾向，那就是到自身以外寻找解释自身命运的理由。
#+END_QUOTE

#+BEGIN_QUOTE
在他眼中，世界是一个勉强取得平衡的天平，而只要这种平衡对他有利，他就不会敢去扰乱它。因此，抗拒变革和热望变革事实上是同源的，前者的激烈程度也可以不亚于后者。
#+END_QUOTE

#+BEGIN_QUOTE
不满情绪并不一定会让人产生改变现状的渴望。要让不满加深为愤愤不平，还需要加入另一些因素。其中一个因素是拥有权力感。
#+END_QUOTE

#+BEGIN_QUOTE
不管处境有多么可怜兮兮，那些对周遭环境又敬又畏的人不会想要去改变现状。当我们的生活朝不保夕，完全无力控制我们的生存环境时，就会执著于熟悉的生活方式。我们通过把生活模式固定化去对抗深深的不安全感。借此我们给自己制造了一种幻象：不可预测性已为我们所驯服。
#+END_QUOTE

#+BEGIN_QUOTE
企图改造一个国家或整个世界的人，不可能单靠培养和利用不满情绪成事，单是展示变革的合理性或诉诸强制手段亦不足以为功。
#+END_QUOTE

#+BEGIN_QUOTE
倘若共产主义者有朝一日能够征服欧洲和大半个世界，那将不是因为他们懂得怎样去煽动不满情绪或仇恨，而是因为他们懂得宣扬希望。
#+END_QUOTE

*** 第二章 对替代品的渴望

#+BEGIN_QUOTE
一个群众运动会吸引到一群追随者，不在于它可以满足人们追求自我改善的渴望，而在于可以满足他们自我否定的热望。
#+END_QUOTE

#+BEGIN_QUOTE
当一个群众运动开始吸引有事业野心的人加入，就是该运动已过了全盛时期的征兆；它不再以创造新世界为务，而只求掌握和保有现在。因此，它不再是个运动而是一项事业。
#+END_QUOTE

#+BEGIN_QUOTE
一个人自己的事要是值得管，他通常都会去管自己的事。如果自己的事不值得管，他就会丢下自己那些没意义的事，转而去管别人家的事。
#+END_QUOTE

*** 第三章 群众运动间的可替代性

#+BEGIN_QUOTE
因为所有群众运动都是从同一类人中间吸收信徒，且吸引到的都是同一类型的心灵，所以：（一）所有群众运动是相互竞争的，一个群众运动增加多少追随者，就会让其他群众运动减少多少追随者；（二）所有群众运动都具有相互取代性。一个宗教运动有可能会发展为一场社会革命或民族主义革命；一场社会革命有可能会演变为军国主义或宗教运动；一个民族主义运动也有可能蜕变为一场社会革命或宗教运动。
#+END_QUOTE

** 第二部 潜在的皈依者
*** 第一章 不受欢迎者在人类事务中扮演的角色

#+BEGIN_QUOTE
社会中最优秀的个人——不管是活跃于政界、文学界、科学界还是工商界，固然是国家的重要形塑者，然而，站在社会另一端的个人，包括失败者、流浪者、罪犯，任何不能在高尚人群中立足或从未厕身其间的人，也是一个国家的重要角色。历史这个游戏的玩家一般都是社会的最上层和最下层，占大多数的中间层次只有在台下看戏的份。
#+END_QUOTE

Why? 答案就是下面这段：

#+BEGIN_QUOTE
社会低等成员之所以能对社会发生重大影响，是因为他们对“现在”全不尊重。他们认为他们的生活和“现在”都已败坏到无可救药，所以随时准备好把这两者加以毁弃。他们也渴望通过某种惊心动魄的集体事业，去掩埋他们已经败坏和了无意义的自我：这是他们倾向于集体行动的原因。因此，他们总是一场革命、集体迁徙、宗教运动或种族主义运动的最早皈依者之一，而他们也会把自己的色彩烙印到运动之中。
#+END_QUOTE

#+BEGIN_QUOTE
一个没有废料和不满者的国家，固然会井然有序、高尚、和平而愉快，但它缺少开拓未来的种子。欧洲的弃民竟能远涉重洋来到美洲建立一个新世界，并不是历史开的玩笑——唯独他们能够成就此等事业。
#+END_QUOTE

*** 第二章 穷人

#+BEGIN_QUOTE
在饥饿边缘挣扎的贫民过的是目标鲜明的生活。他们拼命为填饱肚子而挣扎，完全不会为闲愁所困扰。他们的目标具体而直接。有饭吃就心满意足；能够饱着肚子上床睡觉是一种成就；每一笔意外之财都是一个神迹。
#+END_QUOTE

#+BEGIN_QUOTE
对苏联政权来说，最危险的时刻将会是国家经济已有相当改善而极权统治因为某种缘故稍见松动之时。
#+END_QUOTE

#+BEGIN_QUOTE
已经拥有许多而想拥有更多的人，其失意感要大于一无所有而只想拥有一点点的人。另外，只缺一样东西的人也会比缺很多东西的人更不满。
#+END_QUOTE

#+BEGIN_QUOTE
我们追求奢侈品的时候会比追求必需品的时候更勇猛。情况往往是，到我们不得不放弃追求奢侈品的时候，我们的必需品也会开始短缺。
#+END_QUOTE

#+BEGIN_QUOTE
希望可以让人不顾一切地行动，也可以训练和培养人的耐性。差别就在于它是一个短程的希望还是远程的希望。
#+END_QUOTE

#+BEGIN_QUOTE
一个兴起中的群众运动会传扬短程的希望，其目的是诱发追随者行动的激情。而最能煽动人们行动激情的，就是宣传一个近在咫尺的希望。基督宗教初兴时宣传世界末日即将来临，天国近在咫尺；穆罕默德把劫掠而来的战利品悬在信徒面前；雅各宾党人应许立刻兑现的自由与平等；早期的布尔什维克许诺面包与土地；希特勒许诺立刻撕毁《凡尔赛和约》以及让人人都有工作。然后，当一个运动已经得势，它就会转而强调一些远程的希望——一些梦想与愿景。对一个得势的群众运动而言，它的首要关心是维持现状，所以它会鼓励顺从与耐性，教他的追随者一个道理：“若盼望那所不见的，就必忍耐等候。”
#+END_QUOTE

#+BEGIN_QUOTE
自我若是软弱无力，再多的自由又有何用？
#+END_QUOTE

#+BEGIN_QUOTE
那些最大声呼吁自由的人，往往是最不乐于住在自由社会里的人。“失意者”因为受到自己的短处压迫，会把他们的失败归咎于现有的种种限制。实际上，他们最深的渴望是终结“人人皆有自由”的现象。他们想要取消自由竞争，取消自由社会里人人都要经历的无情考验。
#+END_QUOTE

#+BEGIN_QUOTE
在自由实际存在的地方，平等是大众的热望。在平等实际存在的地方，自由是极少数人的热望。有平等而没有自由，会比有自由而没有平等更能创造稳定的社会模式。
#+END_QUOTE

#+BEGIN_QUOTE
一个传扬爱人如己的人竟会反对父母子女、兄弟姊妹之间的爱，尽管奇怪，却是事实。
#+END_QUOTE

#+BEGIN_QUOTE
今天群众运动会在西方和在被西方殖民的国家之间蔚为风潮，正是人们强烈渴望摆脱无能、无目的感的个人存在所导致的。
#+END_QUOTE

#+BEGIN_QUOTE
即使没有俄国人推波助澜，目前在亚洲风起云涌的民族主义运动最后会带来的，也很可能是一些多少集体化的社会而非民主社会。
#+END_QUOTE

#+BEGIN_QUOTE
把一个村庄、部落或国家分割为独立的个人，并不能窒息或消除当地人民的反抗心理。有效的分化政策是培养尽量多的团体（种族的、宗教的或经济的），使它们互相竞争和猜忌。
#+END_QUOTE

#+BEGIN_QUOTE
在那几十年间，人口的高度流动性和都市化使大量人离乡背井。因为经济上极不安定和心理上适应不良，他们很容易为煽动性的宣传所感染，不管那是来自社会主义还是民族主义的宣传。
#+END_QUOTE

#+BEGIN_QUOTE
在宗教改革的时代，人们“反对的不是教会的权力，而是它的弱化……他们在教会内外发动反教会运动，并非要从宗教的控制下获得释放，而是希望得到更充分更多样的宗教控制”。
#+END_QUOTE

*** 第三章 畸零人

#+BEGIN_QUOTE
他们还是会憧憬一种有意义和有希望的独立自主生活。只要有一点点进步和成就，就足以使他们和这个世界以及自我取得协调。
#+END_QUOTE

#+BEGIN_QUOTE
所谓“永久性的畸零人”，是指因为缺乏才干，或身心上有不可补救的缺陷，故而无法达成生平愿望的那些人。即使他们在其他领域成绩傲人，仍然不会得到满足感。他们从事任何追求都会热切急躁，也不会停下来。他们证明了一个道理：对于不是我们真正想要的东西，得到再多也不会让我们满足。
#+END_QUOTE


*** 第四章 极端自私的人
*** 第五章 面对无穷机会的野心者
*** 第六章 少数民族
*** 第七章 烦闷者

#+BEGIN_QUOTE
人们会感到厌烦，主要是他们的自我让他们厌烦。意识到自己生活贫乏和无意义是人们厌烦感的主要来源。
#+END_QUOTE

*** 第八章 罪犯

#+BEGIN_QUOTE
一个有力的群众运动会培养其追随者的罪恶感。它不但会把人的自主“自我”形容为贫乏和无助的，还会把它说成是罪孽深重。悔罪的方法是抛弃个人的特殊性和独立性，得救的方法是把自我掩埋在团体的神圣一体性中。
#+END_QUOTE

** 第三部 团结行动与自我牺牲
*** 第一章 前言

#+BEGIN_QUOTE
本书并不是一部权威性的教科书。它是一部思考之书，并不避讳提出一些片面的真理，因为有时片面的真理也可以开辟新的思路，帮助架构一些新的问题。
#+END_QUOTE

#+BEGIN_QUOTE
为了成为一个紧密团体的一分子，个人得抛弃许多东西。他必须放弃隐私，不能有个人意见，也往往不能有个人财物。因之，每一种促成团结的工具也是促进自我牺牲精神的方法，反之亦然。
#+END_QUOTE

#+BEGIN_QUOTE
想要培养出人们随时准备好战斗和赴死的心态，诀窍在于把个人从他的血肉之我（flesh-and-blood self）分离出来。有几个方法可以做到这一点：把他彻底同化到一个紧密的团体（第44至46节）；赋予他一个假想的自我（第47节）；灌输他一种贬抑“现在”的态度（第48至55节）；在他与真实世界之间架设一道帷幕（第56至59节）；通过诱发激情，阻止个人与其自我建立稳定的平衡（第60至63节）。
#+END_QUOTE

*** 第二章 促进自我牺牲精神的方法

#+BEGIN_QUOTE
想要把一个人完全同化到集体，对个人特殊性的抹杀必须彻底。他的欢乐与哀愁、骄傲与自信都必须源自团体的机运与权能，而不是源于他个人的前途和能力。
#+END_QUOTE

#+BEGIN_QUOTE
抗高压的能力部分源自一个人对群体的认同感。在纳粹集中营，最能挺得住煎熬的是那些觉得自己是隶属某个党、教会或民族主义团体的人。反之，所有个人主义者（不分国籍）全都陷于崩溃边缘。
#+END_QUOTE

#+BEGIN_QUOTE
碰到苦难和死亡的威胁，个人是无法依赖自己的勇气的。他仅有的力量来源不在他自身，而在于他隶属某个伟大的、光荣的、不可摧毁的集体。这种信仰主要来自认同；通过认同，个人不再是他自己，而成了某种永恒之物的一部分。不管我们是准备好为人类、后代子孙、某个宗教、国家、种族、政党或家族而死，它们都不过是我们行将被消灭的自我所依附的永恒之物的具象化罢了。
#+END_QUOTE

#+BEGIN_QUOTE
一想到我们时代的独裁领袖有多聪明，就让人不寒而栗。他们不只知道有什么方法可以磨砺其追随者的意志，还知道同一个方法反过来用，可以折断其反对者的意志。
#+END_QUOTE

#+BEGIN_QUOTE
他们觉得自己“孤立于每一种构成生活要素的事物之外”。于是他们认了罪。他们在群众面前自我批判，借以打破孤立。他们辱骂自己，指责自己犯有滔天大罪，借以重建他们与那永恒集体之间的联系。
#+END_QUOTE

#+BEGIN_QUOTE
克里姆林宫的理论家大概已经意识到，要让俄国民众顺从，就不能让他们有丝毫机会认同俄国以外的任何集体。
#+END_QUOTE

#+BEGIN_QUOTE
若是作为仪式、典礼、戏剧表演或游戏的一部分，捐躯或杀人都显得不难。所以，为了让人面对死亡而不皱眉头，就有必要加入一些戏剧元素。
#+END_QUOTE

#+BEGIN_QUOTE
在我们的小我看来，天上地下没有一样东西是值得为之效死的。只有当我们自视为舞台上的演员，死亡才会失去其恐怖性和终极性，而成为一种模拟行为和戏剧姿态。一个能干领袖的主要职责之一，是为他的追随者制造一种幻想，让他们觉得自己是从事什么了不得的大事，是在进行某种肃穆或轻松的表演，从而忘了生死问题的严重性。
#+END_QUOTE

#+BEGIN_QUOTE
赴死和杀人的艰巨事业不能缺少戏剧元素，在军队方面尤其明显。制服、旗帜、军徽、阅兵、军乐以及繁缛的仪式礼节，目的都是为了让士兵忘了他的血肉之躯，以及把生死问题的绝大真实性掩盖起来。战场常被称为战争舞台，战况常被称为战争场景，其理在此。
#+END_QUOTE

#+BEGIN_QUOTE
下达作战命令时，指挥官总不忘提醒部下，全世界都在注视他们，他们的祖先在看，后代子孙也会听取他们的故事。伟大的将军懂得怎样在沙漠的黄沙与海洋的波涛里变出大批观众来。
#+END_QUOTE

#+BEGIN_QUOTE
失意者大概要比自足者更易于受群众力量与光辉的感染。这是因为，逃离自我的渴望会让失意者极愿意在壮观的群众场面中隐没自己。
#+END_QUOTE

#+BEGIN_QUOTE
一个群众运动初起时，似乎都会歌颂现在，攻击过去。它把现存制度和特权一律看成是老迈、恶毒的“过去”对于纯洁的“现在”的侵蚀。但是，想要撼动“过去”这座堡垒，需要最大的团结和无限量的自我牺牲。换言之，那些被号召去攻击过去以解放现在的人，必须自愿放弃任何享受或继承“现在”的机会。
#+END_QUOTE

#+BEGIN_QUOTE
一个群众运动不只会把“现在”形容为卑劣惨淡的，它还会刻意把“现在”塑造成那样。它贬低欢乐和舒适，歌颂严格律己的生活。它视寻常享乐为微不足道，甚至是可耻的，把追求个人欢乐视为不道德。
#+END_QUOTE

#+BEGIN_QUOTE
群众运动给自己设定很多不切实际的目标，乃是其对抗“现在”的策略的一部分。大凡行得通或有可行性的事情都是“现在”的一部分。标榜一些可能达到的目标，等于是肯定“现在”的价值，并与之妥协。
#+END_QUOTE

#+BEGIN_QUOTE
没有对美好的“未来”抱有深信不疑的信仰，对“现在”的贬抑就不会彻底。因为不管把“现在”描绘得有多么不堪，如果未来在预期中只会更走下坡或把“现在”不变地维持下去，那我们就必然会和我们的环境妥协——不管这样做有多艰难和会让我们觉得自己有多卑劣。
#+END_QUOTE

现在就是这样

#+BEGIN_QUOTE
愉快的生活会让我们对巨变的逼近茫然不见。我们执著于所谓的常识，执著于所谓务实的观点。但这只是我们执著于熟悉事物的表现。快乐安定的生活会让其他的“真实”——哪怕迫在眉睫——看来模糊和遥远。因此，在陡生巨变时，最手忙脚乱的，就是那些自命务实的人。
#+END_QUOTE

我就是此类务实的人

#+BEGIN_QUOTE
反动派则不相信人的自身具有深不可测的向善潜力，认为如果想建立一个稳定健全的社会，就应该取法过去成功的楷模。在反动派看来，未来应该是壮丽的复古，而不是前所未有的革新。
#+END_QUOTE

#+BEGIN_QUOTE
群众运动喜欢鼓吹不切实际和不可能的任务，这也正对失意者的胃口。那些一般事情都做不好的人喜欢去做不可能的事。那是他们掩饰自己无能的手段。
#+END_QUOTE

#+BEGIN_QUOTE
我们会愿意为想得到的东西而死，多于愿意为已拥有的东西而死。
#+END_QUOTE

#+BEGIN_QUOTE
当人们业已获得值得他为之奋战的东西后，就不太会愿意为之奋战了。渴望而非拥有，才是人们赴汤蹈火在所不辞的动力。
#+END_QUOTE

#+BEGIN_QUOTE
“未有的东西”确实比“已有的东西”[插图]更有吸引力。在任何时代，人类争夺得最头破血流的，都是尚未修筑的漂亮城市和尚未辟建的园林。撒旦说过：“人……情愿舍去一切所有的保全性命。”[插图]这话固然没错，但人却会情愿以性命换取他还没有的东西。
#+END_QUOTE

#+BEGIN_QUOTE
那些珍视“现在”并以全力抓住“现在”的人，正是最没有能力保护“现在”的人。反之，那些鄙视“现在”、避之唯恐不及的人，却不用开口，就有所有“现在”的礼物与财宝投向他们。
#+END_QUOTE

#+BEGIN_QUOTE
因为，对一个人来说，真实的东西中最真实的，莫过于他的生命，没有了这生命，他就不能拥有任何值得拥有的东西。所以，自我牺牲的动力不可能是出于任何具体利益的考虑。
#+END_QUOTE

#+BEGIN_QUOTE
自我牺牲精神往往是一种对现实认知有所不足的衍生物。一个有能力根据自己经验和观察作判断的人，通常不会有殉道的念头。
#+END_QUOTE

#+BEGIN_QUOTE
但凡“忠实信徒”都具有“闭眼掩耳”的能力，对“不值得看或听”的事不屑一顾，而他们所以能够无比坚定不移，力量亦是源于此。他们不会因为危险却步，不会因为障碍重重而气馁，不会因为有反面证据而困惑，因为他们根本否定有危险、障碍和反面证据的存在。
#+END_QUOTE

#+BEGIN_QUOTE
只有对我们不理解的东西，我们才会有百分百的信仰。
#+END_QUOTE

#+BEGIN_QUOTE
一个积极的群众运动会否定现在，把目光集中在未来。它的力量正是衍生自这种态度，因为否定现在让它可以对现在的一切——其信徒的健康、财富和生命——无所顾惜。
#+END_QUOTE

#+BEGIN_QUOTE
狂热者并不是真会坚持原则的人。他拥抱一项大业，主要并非由于它正确神圣，而是因为他亟须有所依附。这种感情上要有所依附的需要，往往会把他拥抱的任何大业转化为神圣伟业。
#+END_QUOTE

#+BEGIN_QUOTE
你无法用理性或道德上的理由去说服一个狂热者抛弃他的大业。他害怕妥协，因此你不可能让他相信他信奉的主义并不可靠。但他却不难突然从一件神圣伟业转投另一件神圣伟业的怀抱。他无法被说服，只能被煽动。对他而言，真正重要的不是他所依附的大业的本质，而是他渴望有所依附的情感需要。
#+END_QUOTE

*** 第三章 团结催化剂

#+BEGIN_QUOTE
我们爱一个对象的时候，一般不会寻找同好，甚至反而会把跟我们爱同一对象的人视为竞争者和侵犯者。但我们恨一个对象时，却总是会寻求有志一同的人。
#+END_QUOTE

#+BEGIN_QUOTE
哪怕在我们的不满是合理的情况下，我们的恨意主要仍然不是来自别人对我们的伤害，而是来自我们意识到自己的无能和懦弱——换言之是源于自卑。
#+END_QUOTE

#+BEGIN_QUOTE
自卑可以让人产生“能想象得出的最不公正和最易作奸犯科的激情，因为他对于那谴责他和让他认识自己缺点的真理，心怀切齿痛恨”。
#+END_QUOTE

#+BEGIN_QUOTE
在我们揭发别人过错使对方羞愧时，他更可能的反应并不是变得谦卑和柔顺，而是变得咄咄逼人和火气十足。死不认错是一种响亮的噪音，可以把我们罪恶感的发声给淹没。
#+END_QUOTE

#+BEGIN_QUOTE
任何崇高（sublime）的宗教必然会让信徒产生强烈的罪疚感。这是因为高不可攀的理想必然会带来实践上的落差。
#+END_QUOTE

#+BEGIN_QUOTE
失意者看到有钱人走下坡和正直者受辱时，会深感安慰。他们在普遍的没落中看到人类平等的前景。
#+END_QUOTE

#+BEGIN_QUOTE
一个漫无目标的人要是想为生活找到新意义，办法除了献身于一种神圣大业以外，还可以培养狂热的悲愤。
#+END_QUOTE

#+BEGIN_QUOTE
帕斯卡尔说过：“人类就天性来说是恨彼此的。”还说过，爱和仁慈不过是“一种伪装和假象，因为归根结底它们不过是恨”。
#+END_QUOTE

#+BEGIN_QUOTE
团结性和自我牺牲精神这回事本身就足以诱发仇恨——哪怕当初它们是以最高尚的手段培养出来的。即使一群人的结合是为了鼓吹宗教宽容与世界和平之类的崇高目标，一样会对意见相左的人极不宽容。
#+END_QUOTE

#+BEGIN_QUOTE
这是因为，如前所述，[插图]个人舍弃自我乃是他产生无私心理和完全融入一个集体的先决条件，但舍弃自我的人极容易产生各种激情，其中包括仇恨的激情。
#+END_QUOTE

#+BEGIN_QUOTE
顺服和谦卑会孕育出骄傲与自大。
#+END_QUOTE

#+BEGIN_QUOTE
当我们抛弃自我，成为一个紧密团体的一部分时，我们不仅抛开了个人利益，同时也抛开了个人责任。
#+END_QUOTE

#+BEGIN_QUOTE
一个人如果没有了恐惧、犹豫、怀疑和是非感，他会变得有多残暴和冷酷，令人不敢想象。
#+END_QUOTE

#+BEGIN_QUOTE
当我们在群众运动中丧失了自我独立性，我们就得到一种新自由——一种无愧无疚地去恨、去恫吓、去撒谎、去凌虐、去背叛的自由。这毫无疑问是群众运动的部分吸引力之所寄。在群众运动中，我们获得了“干下流勾当的权利”。
#+END_QUOTE

#+BEGIN_QUOTE
我们当自己当得愈不自在，想要当别人的渴望就愈强烈。因此，我们会偏好模仿与我们迥然不同的人多于与我们差不多的人，偏好模仿我们钦佩的人多于我们鄙夷的人。
#+END_QUOTE

我有这种心理和行为

#+BEGIN_QUOTE
模仿往往是解决问题的快捷方式。当我们没有意向、能力或时间去独自解决问题时，就会模仿别人。
#+END_QUOTE

#+BEGIN_QUOTE
忙人比闲人更易于去模仿。换言之，匆匆忙忙的生活更易制造齐一性。因此，如果处心积虑要把一群个人融合为一个紧密的团体，不断制造些行动让他们投入，看来是个相当有效的方法。
#+END_QUOTE

#+BEGIN_QUOTE
现代人喜欢夸大说服手段的效果，认为从宣传主张到形塑行为，说服手段都无所不能。我们把宣传看成一种攻无不克的武器，把我们时代很多大获成功的群众运动都归功于高明的宣传技巧，并且开始像害怕刀剑一样害怕语言文字。
#+END_QUOTE

#+BEGIN_QUOTE
事实上，把一切功劳归于宣传，就像把耶利哥城城墙的崩塌归功于约书亚（Joshua）的号角声一样，是没有多少根据的。
#+END_QUOTE

#+BEGIN_QUOTE
事实似乎是这样的：宣传单靠自身的力量，是无法叫那些不愿接受的人接受的。它既不能创造全新事物，也无法保证那些相信它的人一直相信到底。它只能打入那些本来就打开的心扉，或是把某些已经为人们所接受的主张强化。
#+END_QUOTE

#+BEGIN_QUOTE
高明宣传家所做的事只是把听众心中业已徐徐成熟的意见和情绪引发至沸腾翻滚的程度而已。他呼应了他们内心深处的感情。在意见并非通过强制手段强加的时候，宣传家只能使群众信仰他们“已知”的事情。
#+END_QUOTE

#+BEGIN_QUOTE
失意者亦容易成为最坚定的追随者。令人惊讶的一件事情是，在集体行动中，最缺乏独立性的人是最不容易因为失败而气馁的人。理由在于，他们之所以参加一件共同事业，动机不那么是为了增加成功的机会，而主要是为了在面临失败时，不需要负失败之责。因此，即使一件共同事业失败了，他们仍然可以躲过一件他们最害怕的事：在别人面前暴露出个人短处。
#+END_QUOTE

#+BEGIN_QUOTE
没有撕去自己特殊性和分化性的人会难以投入行动。
#+END_QUOTE

#+BEGIN_QUOTE
一个鼓励行动的群众运动可以唤起失意者的热烈反应。因为失意者把行动视为医治他们烦恼痛苦的良方。行动可以让他们遗忘自我，让他们有一种目的感和价值感。
#+END_QUOTE

#+BEGIN_QUOTE
失意者的失意感很可能主要是源于缺乏行动的机会，而失意感最深重的就是那些才具与性情都足以过一种行动性生活，却为环境所囿，只能在闲散中虚耗人生的人。
#+END_QUOTE

#+BEGIN_QUOTE
以下这些特质都足以让人在任何行动领域坚定而无情地迈进：自信拥有唯一和独一真理，从不自疑；感觉自己受到一股神秘力量支持，不管这力量是上帝、命运还是历史法则；绝对相信自己的敌人是邪恶化身，必须予以粉碎；乐于泯灭自我和为义务献身。
#+END_QUOTE

#+BEGIN_QUOTE
因为深谙自己的瑕疵与缺点，失意者对别人的歹意与恶念总是特别眼尖。一个有自卑感的人特别容易看出别人的短处。
#+END_QUOTE

#+BEGIN_QUOTE
团结性不是“忠实信徒”彼此间手足之爱的产物。“忠实信徒”忠诚的对象是整体（教会、党、国家），而不是同仁。
#+END_QUOTE

#+BEGIN_QUOTE
拥挤的居住或生活空间可以让人少些独立性，逼使每个人每天参与公共活动。
#+END_QUOTE

#+BEGIN_QUOTE
对文学、艺术、音乐和科学强力审查，可让即使有创造力的人也无法过上自足的生活。
#+END_QUOTE

** 第四部 始与终
*** 第一章 言辞人

#+BEGIN_QUOTE
如果一个地方缺乏言辞人，或这些言辞人心中没有不平，现行政权再无能和腐败，也可能会继续掌权，直到自行倾圮崩溃为止。另一方面，一个体制即使有再多美德和活力，如果它争取不到言辞人的效忠，一样有垮台之虞。
#+END_QUOTE

#+BEGIN_QUOTE
只要现行秩序大体还能运行，群众的基本态度就会是保守的。他们可能会想到改革，但不会想到全面革新。
#+END_QUOTE

#+BEGIN_QUOTE
但群众对典型言辞人的态度却截然不同。群众会愿意倾听他们的话，这是因为群众知道，不管言辞人的话有多么激烈，都不会产生实时效果。
#+END_QUOTE

#+BEGIN_QUOTE
不管是哪一类型的言辞人，差不多都有一种深切的向往：被肯定。
#+END_QUOTE

#+BEGIN_QUOTE
不管一个抨击当局的言辞人，多么相信自己是为被压迫者和受伤害者仗义执言的斗士，他的动机十之八九都是私人和个人性的。
#+END_QUOTE

#+BEGIN_QUOTE
若是一个言辞人的崇高地位受到当权者恰如其分的承认，他往往会找出各种高尚理由来解释自己为什么会站到强者一边，打压弱者。例如，路德刚开始挑战天主教会时，曾对“贫穷、单纯、普通的大众”[插图]寄予莫大同情，一旦得到德意志各诸侯的支持，他却宣称：“不管政府多么坏，上帝会宁愿忍痛让它存在下去，而不会容许暴民反抗，不管他们多么有理。”
#+END_QUOTE

*** 第二章 狂热者

#+BEGIN_QUOTE
前一天在与外部敌人生死斗争中获得发泄的激情，现在会通过斗争自己人来宣泄。
#+END_QUOTE

*** 第三章 务实的行动人

#+BEGIN_QUOTE
一个群众运动一般都是由言辞人为前驱，由狂热者实现，再由行动人加以巩固。
#+END_QUOTE

*** 第四章 良性与恶性的群众运动

#+BEGIN_QUOTE
说一个有自由传统的国家不会出现斯大林或希特勒之流是没有根据的。较有根据的说法是：在有自由传统的国家，希特勒或斯大林之流要取得政权也许不难，但权力要长久保持却难上加难。所谓自由的传统就是反抗的传统，而在一个经济明显改善的地方，自由的传统几乎是一定会被激活的。
#+END_QUOTE

#+BEGIN_QUOTE
赫拉克利特说过：“让人一切渴望得到满足，对他大概不是可喜之事。”
#+END_QUOTE


2025年读完的第96本,总阅读量第96本