#+TITLE: 每天锻炼与周末锻炼对肌肉增长的影响
#+DATE: <2022-08-24 Wed>
#+TAGS[]: 健康", "他山之石

[[https://studyfinds.org/exercise-each-day-builds-muscle/]]

原文是英文，标题是 How to build bigger biceps: A little exercise each
day boosts muscles more than one big weekly
workout（如何增大二头肌：每天少量锻炼在增强肌肉上好过每周一次的增大强度锻炼）。

获得更强肌肉的答案是数量大于质量吗？一项新研究发现：每天锻炼一点点要好过一次性高强度锻炼。

来自澳大利亚和日本的研究人员发现，每天做一些二头肌弯曲运动，每周五天的确能够改善肌肉强度，这样做的效果要好过一周一次，在本次锻炼中进行高强度的二头肌弯曲运动。此外，他们发现人们甚至不需要全力以赴就能达到改善肌肉强度的效果。

在他们的研究中，研究小组让两组志愿者连续四周进行"最大自愿偏心二头肌收缩"，同时测量每个人的肌肉力量和肌肉厚度。偏心收缩是指肌肉伸长。在二头肌弯曲的情况下，一个人通过放下沉重的哑铃来延长肌肉。

一组这样每天做六次，一周做五天（6x5）。另一组只做一天，这一天做 30
次（30x1）。研究人员还让第三组每周做六次运动以作为对照组。

结果显示：30x1
小组志愿者的肌肉强度在四周后并无多大提升。然而，他们的肌肉厚度的确增大了
5.8 个百分点。对照组在肌肉强度或厚度上并无变化。

另外，6x5 组发现他们的肌肉强度增加超过 10 个百分点，和 30x1
小组一样获得相似的肌肉厚度提升。

** 即使是 3 秒钟的锻炼对更大的肌肉也足够
   :PROPERTIES:
   :CUSTOM_ID: 即使是-3-秒钟的锻炼对更大的肌肉也足够
   :END:

有趣的是，团队还发现：在 6x5
小组中有着和之前的研究类似的结果------之前的研究通过每天进行一次用时三秒钟的二头肌弯曲运动。

Edith Cowan 大学的教授 Ken Nosaka
说这些研究显示：只要定期进行一定量的运动就能显著提高力量。"人们认为他们必须在健身房进行长时间的阻力训练，但可能不需要，"Nosaka
在一次大学会议上说。"每天缓慢放下哑铃一次或六次就足够了。"

此外，他还说最新研究发现它不需要人们尽最大努力实现这些结果。

"我们在此次研究中只使用了二头肌弯曲练习，但我们相信在某种程度上，这同样适用于其他肌肉组织，"研究人员补充道。“”肌肉强度对我们的健康至关重要。这可能有助于防止随年龄增长肌肉质量和力量的减少。肌肉数量减少是很多慢性疾病的原因，例如心血管疾病、二型糖尿病、一些癌症、痴呆症，再加上肌肉骨骼问题，如骨质疏松症。

** 休息要足够
   :PROPERTIES:
   :CUSTOM_ID: 休息要足够
   :END:

虽然最新研究发现经常锻炼身体是件好事，但研究作者表明休息和构建肌肉一样重要。

"这项研究中，6x5 小组每周休息两天，"Nosaka
教授解释道。"在我们休息时肌肉稳定下来；如果某人以某种方式每天锻炼 24
小时，那实际上肌肉的强度不会有任何改善。肌肉需要休息来提高他们的力量和质量，但是肌肉似乎更喜欢被刺激。"

研究团队同样发现，人们不应该试图"赶上"锻炼如果他们已经很久没有去健身房锻炼了。一次性的长时间锻炼不会实现他们期望的结果。Nosaka
推荐道："如果某个人生病了，这一周无法锻炼，这是没问题的，只要病好以后回到日常的锻炼规划中即可。"

美国疾病控制和预防中心（Centers for Disease Control and
Prevention）建议成年人每周进行 150 分钟中等强度的体育活动，然而，Nosaka
的团队认为，更重要的是优先考虑每天的身体活动，而不是一个具体的分钟标志。

"如果你只是每周去一次健身房，它不如每天在家做一点运动有效，"Nosaka
总结道。"这项研究，加上我们之前的研究，表明了每周少量运动的重要性，而不仅仅是每周花几个小时运动一次。我们需要知道，
*每个肌肉收缩都很重要，重要的是你执行它们的频率* 。"
