#+TITLE: 父亲住院笔记
#+DATE: <2024-06-21 Fri 18:08>
#+TAGS[]: 随笔

* 事情梗概

父亲骑电动车戴头盔在机动车道行驶，走在机动车道上的原因是：辅道已经停满了车，不容易通过。

父亲直行，汽车从看不见的地方冲出，撞到父亲的电动车，使得父亲的右手撞击到地面，致使肩袖韧带断裂，需要进行手术。

车祸时间是2024年3月7日，8日开始在县医院住院。事故责任划分是父亲占三成，对方占七成。

先后进行了两次手术：

1. 在太和县人民医院，进行了“肩关节镜下肩袖修补术”，时间是2024年3月14日，耗时四个多小时，从上午九点四十五到下午两点二十五。不过，这次手术不那么成功，手术时还做了一个无必要的可能带来潜在危险的动作——把连接肩部到手臂的一根筋切断了。
2. 在安徽医科大学第一附属医院，进行了同样的手术，时间是2024年6月18日，耗时三个多小时，从下午五点零几到七点三十多，但实际手术时间只用了35分钟。据王高远手术医生所说，这次手术把父亲的韧带彻底缝合了，除了因第一次手术切除的那根筋因为肌肉收缩找不到了。

* 看病经过

#+BEGIN_QUOTE
以下是一些经过，包括内心想法。

幸好有记日记的习惯，否则别看只隔了几个月，当时发生的事情已经忘得差不多、当时的感受也早已经不在了。
#+END_QUOTE

** 2024-03-13

当需要承担责任的时候，无论是否准备好，都要去面对

早晨下夜班后，吃早饭回宿舍睡觉，睡不着，看了很多集老友记到十点多才睡着。下午四点多起床，做梦，梦到了爷爷，不知道为什么。吃了即将坏掉的香蕉，坐上回家路上的公交，在从市到县的专车上我因为车速过快而难受。因为赶时间，司机又拉不到足够的人，本来只要三十最后花了五十，终于到达父亲住院的地方。父亲7号被人家开车碰到，8号住院，直到昨天13号晚上，母亲告诉我才知道。直到看到父亲坐在病床上，我才真的相信－－父亲要动手术这一事实。在这之前，我一直在想：母亲和父亲一定是在骗我回来。因为我和他们上次的沟通并不愉快－－他们都想让我辞职，去工厂工作，因为这样看起来比在现在这家公司挣得更多。但是我并不想去，因为我知道一旦我去了，我就会离自己憧憬的生活愈来愈远，直到遥不可及。

从市回到县里医院，我一直噙住眼泪，不让它落下来，我几乎成功了，在公交车上，还是流下眼泪了，心里不断想着各种糟糕的情况。但见到父亲的那一刻时，悬着的心放下来，父亲看起来精神不错。

我开始想到接下来的种种：

- 父亲手术不能干重活，家庭收入骤降
- 我要加倍努力工作，挣更多钱

** 2024-03-14

9:45开始进行手术（肩关节镜下肩袖修补术），一直到下午14:25才结束手术

这一天不能下床，我在医院过夜，但是因为疲惫睡着了，差点让空气通过输液管进入爸爸的血液

** 2024-03-15

晚上回家睡的，白天在医院照顾爸爸，帮他拿尿壶小便，给他买饭，看着吊水输完叫护士换新的点滴或者暂停输液

中午买了猪蹄和烤鸭，爸爸吃了猪蹄，烤鸭晚上我们一起吃的

** 2024-03-16

爸爸中午吃馄饨和油酥烧饼

** 2024-03-17

中午我们出去吃了炒面，爸爸还去看了看活（判断能不能干，刮大白）

下午三点多我就会市里了，晚上继续上了夜班

** 2024-03-18

父亲在这一天出院

** 2024-06-10

因为还是疼痛，所以父亲决定去更大的医院——阜阳市第二人民医院。

这家医院的医生在看过相关检查的结果后说，二次手术的风险比较大，如果失败右胳膊可能会残废。医生推荐了安医大一附院的王高远医生。

** 2024-06-14

四点起床，准备去合肥。四点半多下楼，送我们去合肥的司机，接我们的时候有点晚，不过最终还是按时（预约时间是九点，不到把八点半就到了）

去合肥带了：风扇，水杯，墨镜，衣服（五件），拖鞋，牙刷，毛巾，ipad，两个充电器，钱包

于是，我和父亲坐上一人100元的从太和到合肥的商务专线，来到了位于绩溪路的医院门诊部。王医生了解了情况后，让我们去住院部办理住院手续。不过，这个住院部离门诊部有17公里，打车花了44元。

晚上窗帘不要拉完，不方便护士查房

** 2024-06-15

告诉医生不需要抽血了，把这个项目取消掉。每天晚上换垃圾袋

** 2024-06-16

其实在家这个月让我有空和父母多相处，挺好的。在照顾父亲时，更好地了解父亲。在诉说病史的时候，能够清晰表达自己的生病历史也很重要。

父亲的心跳过慢，如果出现症状，心内科门诊-->急诊，需要装心脏起搏器。做手术时有需要装，虽然只是右肩的肩袖损伤，但需要全身麻醉，父亲平时心率四十多不到50，做手术在全麻的情况下还要心率下降，有心脏停止跳动的风险。

#+BEGIN_QUOTE
嘴唇发紫

嘴唇发紫可能是身体某种状况的表现，可能是缺氧、循环问题、心脏问题、呼吸问题等。以下是一些可能导致嘴唇发紫的原因：

1. 缺氧：当身体缺氧时，嘴唇可能会变得发紫。这可能是由于呼吸系统问题、心脏问题或其他因素导致的氧气供应不足。
2. 心脏问题：心脏问题如心脏病、心脏衰竭等可能导致血液循环不畅，使得嘴唇出现发紫的情况。
3. 呼吸问题：肺部疾病或呼吸系统问题可能导致氧气供应不足，进而导致嘴唇发紫。
4. 寒冷：在极端寒冷的环境下，嘴唇可能会因为血液循环受限而发紫。

如果你或他人出现嘴唇发紫的情况，特别是伴随有呼吸困难、胸痛、头晕、意识丧失等症状时，应立即就医。这些症状可能表明严重的健康问题，需要及时的医疗干预。最好的做法是咨询医生，让医生进行全面的评估和诊断。
#+END_QUOTE

** 2024-06-17

说起这家医院给我的感觉，陌生的环境让我不安，因为医院规定只有病人才能躺在床上家属不行，所以当我有次躺在床上休息时，来查房的护士们让我下来，似乎医院不让你躺你就不能躺，没有任何温馨的提醒为什么家属不能躺在病床上。后来我听到了：是怕疾病传播。

我为什么想躺在床上呢？因为白天的时候如果不躺在床上只能坐着，无论是坐在床上还是坐在没有靠背的方凳上，长时间坐着玩手机是很痛苦的。

在医院本身情绪不免低落，医院不是个久待的地方，又遭受身体劳累，只会让照顾病人更加疲惫。

在这个新使用刚半年的医院，一切都是崭新的，这种新让我有种疏离陌生的感觉。觉得自己不配在这样的医院，因为自己没钱。如果有病却没钱在这样的医院是消耗不起的。

手术前，今天17号晚上12点后不能吃喝，直到手术以前

父亲右手肩膀肩袖，即使康复（至少需要一年）也无法上举，如果上举次数过多，肩袖韧带还是会断裂。

** 2024-06-18

父亲以为我不担心，不认为事情严重，不认为一旦手术失败可能有死亡的风险。但怎么可能不担心呢？虽然不能体会到死亡的恐惧，但作为儿子会有种恐惧，想到如果父亲去世了，以后会怎么样。

在用软针的时候，针扎在手上，看到父亲直挤眼，可能是疼的。不禁想到，父亲不怕干活的疼痛却害怕医生的针头。

9:17 现在在医院3号楼一楼医学影像中心介入手术室门口，我们在等待10点的临时心脏起搏器植入手术。

看着父亲穿着病号衣服，右腿搭在左腿上跷二郎腿，看快手上的“地痞流氓”视频。

10:09 大约是这个时间，进入手术室，手术台有四五米长，对面的一侧很多显示器和仪器，无影灯高大明亮，让人畏惧

10:20 来了其他病人和家属，让等待多了些煎熬与烦躁。

10:26 终于让那些人安静下来了，说话声小了很多。我快哭了

10:39 终于从手术室出来，心脏起搏器安装好了。在护工阿姨的帮助下，一路缓慢地走向病房。悬着的心落下了一半

#+BEGIN_QUOTE
为什么做手术当天要从零点开始不能吃喝？

手术当天要求患者空腹是为了减少手术风险并确保手术过程顺利进行。以下是一些原因：

- 减少呕吐风险：如果胃部有食物或液体，手术过程中患者可能会因为麻醉药物或手术刺激而呕吐。呕吐物进入呼吸道可能导致窒息或其他严重并发症。
- 减少误吸风险：手术过程中，患者可能因为麻醉而失去咽喉反射，如果有食物或液体在胃部，可能会误吸到呼吸道中，导致呼吸道阻塞或感染。
- 麻醉药物效果：胃部有食物或液体时，麻醉药物的吸收和分布可能会受到影响，影响手术的效果和安全性。
- 降低术中并发症风险：空腹状态可以减少手术中出现胃内容物反流、误吸等并发症的风险，有助于手术的顺利进行。

因此，遵守医生或医院规定的空腹时间是非常重要的，以确保手术过程安全无误。在手术前，患者应该按照医生的指导停止饮食和饮水，以确保手术的成功和患者的安全。
#+END_QUOTE

16:04 从病房出发

16:13 进入等待手术区域（家属不能进）

18:19 还没出来，上次手术做了4h40min，这次目前两小时

术后打点滴：乳酸钠格林注射液、氯化钠注射液

19:34 护士告知，如果血氧低于95，父亲睡着了，要把他叫醒。2h后用生理盐水漱口后喝水4h后吃饭，清淡馄炖面条，不过父亲没用生理盐水到2h时直接喝的水，快4h时吃了饭

20:34 从手术室回病房差不多1h了，我的大拇指在颤抖

21:50 隔两个小时后喝第一口水

同病房的一个年轻小伙，可能没动过手术，第一次动，喊着很疼。受不了。

小伙问我爸，问他疼不疼，我爸说，疼啊，但他一直在忍着。

冰敷只能敷半个小时。

23:12 吃了一根香蕉、一根火腿肠、和了一些鲜牛奶。

过了一会儿，吃了买的饺子。

回病房后，三四次解小便，尿壶

23点多 中间的叔叔，回来后也喊着很疼，他开的刀在腿上

这一夜我没怎么睡，披着从家带的被子，守在父亲的床边

** 2024-06-19

从18号上午装了心脏起搏器开始，父亲就不能坐立行走了，因为机器是从大腿的静脉通过电线进到心脏中的，一旦坐立会使电线弯曲，对心脏产生意外影响。

直到今天九点左右，在经过和手术医生、主治医生的电话、见面沟通后，负责起搏器的医生，终于来到病房取出电线了。当我看到带血的电线从父亲的体内慢慢拔出时，内心还是非常害怕的，因为一个疏忽就可能让心脏停止跳动。

幸好，父亲挺过来了。

** 2024-06-20

医生说，像打印病例的话需要出院一个月以后，在公众号上找入口。

手术过很疼，医生推荐了艾瑞昔布片，用于镇痛。不过父亲选择在家附近的镇卫生院打点滴去痛。

之后就是在医院拆线，锻炼，一个月后去医院复查。
