#+TITLE: 第一次去香港
#+DATE: <2025-08-10 Sun 22:32>
#+TAGS[]: 随笔

当我开始写这篇文章时是周日的晚上十点三十二。我坐在住处的椅子上，总结自己昨天和今天的行程。

昨天下午考试，考到五点困死了，就去睡觉，睡了半小时后下楼买煎饼果子。六点三十六已经在去福田地铁站的路上了，努力维持一种平和的心情，来迎接接下来的游玩。到福田后在喜士多便利店取自己在支付宝上购买的境外流量卡，然后就在福田高铁站候车。再次来到福田站，那种高大上的气味，还是会让我觉得不适。

我到高铁站时，距离发车时间还很早，所以就想着能不能改签，能早点到香港。结果发现可以，就这样我通过高铁到达了香港。要过两次海关，一次是中国海关，一次是香港海关。每次要放证件时我都不清楚要拿出来港澳通行证还是身份证。可能是那个时候人少的缘故我过海关是很快的，大概半小时不到。

我到香港的第一件事就让我很是窘迫：内地的手机卡到这里彻底不能用了没流量，我也没开漫游。所以，着急地站在一个便利店门口，把自己买的流量卡换到手机上，把自己的内地流量卡收好。就这样出发了。

离开西九龙站后我要去旅舍，在携程上花两百多订的，这是最便宜的了。我当然不会有什么期待，只是想找个休息的地方而已。这个旅舍满足我的需求了。旅舍在旺角站附近，所以我步行到佐敦站，坐地铁到旺角。

讲到地铁，这作为最基本的出行方式，价格和深圳比肯定是贵的。坐个两三站就要花四五块人民币。而且只要出去玩，至少两公里步行。昨天+今天总算是让我体会到了步行的痛苦。

初来香港，不同环线在不同楼层，这让我迷惑了一会儿。好在没有迷路，跟着导航找到了想去的地方。放下随身的帆布包在旅舍后，我就出发去尖沙咀，想去维多利亚港看看。海景确实不错，对岸中环的大厦灯火通明，各种logo还在亮灯，标志着大厦的归属。

在那里用手机拍了几张感觉还不错，但是照片里没有我，为什么呢？因为我还没找到女朋友，没人帮我拍呀。我一个人在海边思考，尽管周围人不少，但他们和我无关。我抬头望天，月亮又大又圆又亮，美极了。思考的结论是这样的： *不管是工作也好，寻找恋人也罢，一开始都是很难的事情。但正是因为做成这样的事很难，所以才有挑战的欲望。做成之后成就感满满，能够获得极大的幸福感。*

之后，就到了第二天。

一点睡觉，将近九点起床，睡旅舍真的不舒服，不过没办法这是最便宜的了。想在这里过夜，不想委屈自己，就要在住宿上花很多钱。起床后，喝口水洗脸，就出发了，九点多的太阳让人感到一股能量但是不好的那种，好在有周围的高楼阻挡倒也不算糟糕。因为对这里不熟悉，所以就只选遮阳的地方走，走了一圈在旺角地铁站打转，无奈打开高德地图看看附近有什么吃的地方，然后就看到了半路咖啡（豉油街店）。远处看去发现门面不大。进去后，店员用英文问我：需要什么，我中文回答：卡布奇诺，哈哈。这是当时脑子想到的唯一的一种。还问了是否支持支付宝，是支持的。我坐在这里，听着店里播放的英文歌，望着门口陷入沉思。我想要放松下来，但还是有些许紧张，觉得自己不属于这里。但下一刻便恍然：我本来就不属于这里，我的生活不在这里。我只是到这里来旅游的，感受一下在我住的地方感受不到的一些氛围，看看环境的改变能让我发生什么变化。

这家店很不错，很偏僻，少人来往，但不少常客。我很喜欢。我坐门口的椅子上，思考着一些事情。我在想自己生命中最重要的事情：了解自己，认识世界。这两句其实就是一句：了解自己。

我为什么要认识这个世界？其实还是为了了解自己，了解自己是如何生活在这个世界中。为此，我要做什么？

1. 拥有足够多的经历
2. 思考得足够深入
3. 写得足够多

这是我在这家咖啡店思考的所得。之后，我会一点点地实践，为了了解我自己。

喝完咖啡，该去艺术馆了。这是昨天定下的计划。艺术一直对我有很强的吸引力，手机上一直装着DailyArt这个App，有时推荐的艺术作品被我用作手机壁纸。我认为，艺术是一种自我表达的方式，艺术家们透过自己的作品表达自己的性格、对生活的态度等。

能否欣赏艺术，是一种能力，它涉及一个人的想象力、抽象思维和理解能力。当艺术作品的表达内容和表现形式超出人们的生活经验太多时，这类作品就只有少数人才能欣赏了。

在二楼一处空间，展示着刘国松的《[[https://liukuosung.org/projects.php?lang=cn&CateID=3][云树银枝：西藏组曲之十六]]》水墨画，我在这幅画前停留了很久，身后的人来来往往，我视而不见，只是注视着这幅画。刚开始时，我的心没有完全静下来，看不出画中的内容，随着我愈发专注，画的内容向我呈现了出来——在西藏的某处，云与雪缭绕于群山之间，那种空灵轻盈之感，让人似乎觉得有些许凉意。

我喜欢水墨画，那种只用墨色表达的方式，让我觉得简单但不失深刻。笔下所画全凭画家心中所想，由画家的生活经验出发，生发出一种抽象于生活的东西，就是艺术。 *艺术就是对生活中事物进行抽象化表达，让人不能一眼就看出现实中的对应物，从而激发人对艺术作品的无限想象。*

逛到快一点了，可以去吃午饭了。本来想去一个叫旺记冰室的地方吃，但是来到附近时发现好多人在排队。于是，就找了个没人排队的餐馆吃饭，名字是「烏蠅館」（The Fly Place）。点了份鱼香肉丝+默认饮品，花了65人民币，确实贵哈。

吃完饭，就开始去西九龙高铁站，准备回深圳了。在去的路上，虽然天气很热，但是人有很多。一边走一边想着，自己下一次来，就是明年的港马喽。

就这样，这次香港之行结束了。在一个陌生的环境里，我很好地观察了自己，并思考了一些重要事情。很不错！
