#+TITLE: 恋人絮语
#+DATE: <2023-06-07 Wed>
#+TAGS[]: 随笔

文章真实的新建日期：<2023-06-07 Wed>

提醒自己：

1. X和我目前来看，成为恋人的可能性不太大，但我想尽力追她，我很久没遇到一个让我心动的女孩了。
2. 你的记忆不一定准确，很多她的做法你会以自己的想法让它合理化。所以，如果下面的记述和事实有偏差也不要担心，请你记住：你要记录的是两个人之间发生的美好。
3. 如果描述中若无法分辨，就用X指代她。
4. 认识一个人，不一定要谈恋爱才能让彼此变得更好

2023年6月23日：

今天，回顾上周六发生的事，她说对我没有感觉，我有些不知所措。她问我：“如果他们没有撮合我们，你会想到要进一步发展吗？”她问出这句话后，我明白了：我没有那么喜欢她。

我很感谢她，让我体会谈恋爱的美好。尽管时间短暂。

2023年6月17日：

14号周三那天和她聊了她考教资的细节，知道了她现在在看七年级的数学，不选语文是觉得语文自己讲不好，需要丰富的知识储备。

之后想到《让陌生人快速相爱的36个问题》中的一个：你上一次哭是什么时候？我就直接问了，后来经室友洪雅豪的提醒，觉得这不是一个好问题。又说：“我是没救了，竟然会想到问你这样的问题”。她回了一个😂的表情。下一句是洪雅豪想的，我说：“报一丝，我就是有点好奇”。没想到，她真的回了这个问题：“我经常 emo”。我回：“怎么说”。她说：“没啥，都有心情不好的时候”。我回：“确实，我也有情绪低落的时候”。那天的最后一句话，是我跟她说晚安：“不行了我要睡觉了，明天还要上班，晚安”。

15号周四傍晚五点过三分钟，我问她：

#+BEGIN_QUOTE
你说，你要是喜欢一个人，你是要直接跟他说呢，还是继续自己一个人茶不思饭不想，或者你会作出其他选择
#+END_QUOTE

她：

#+BEGIN_QUOTE
会说
#+END_QUOTE

我：

#+BEGIN_QUOTE
上次你说的那个人，他回复你了吗
#+END_QUOTE

她：

#+BEGIN_QUOTE
怎么说呢，反正我们不可能
#+END_QUOTE

我：

#+BEGIN_QUOTE
“我喜欢的人不喜欢自己”，没有比这更无奈的了吧

你要是想找个人倾诉一下，我可以听你说说话，无论什么时候
#+END_QUOTE

她：

#+BEGIN_QUOTE
一般我都是跟我女生朋友讲😂
#+END_QUOTE

我：

#+BEGIN_QUOTE
[捂脸]

你会发呆吗？就是坐着，目光盯着某处，思绪万千
#+END_QUOTE

她：

#+BEGIN_QUOTE
也有，但是可能是真发呆，啥也不想
#+END_QUOTE

我：

#+BEGIN_QUOTE
😂

刚才就在想，自己发给你的那些笨拙的文字，单纯得令我自己都想笑
#+END_QUOTE

她：

#+BEGIN_QUOTE
[捂脸]
#+END_QUOTE

我：

#+BEGIN_QUOTE
现在在湖边，跟着耳机里的歌哼着唱。感觉很棒！

终于找到了！你那天穿的鞋子的名字——玛丽珍鞋

（附上「玛丽珍鞋」中文维基百科截图）
#+END_QUOTE

她：

#+BEGIN_QUOTE
差不多
#+END_QUOTE

16号周五，下午快四点的时候

我：

#+BEGIN_QUOTE
刚才工作上，HR组织了一些活动，本来以为会很尴尬，没想到还挺有趣的。你在做什么
#+END_QUOTE

她：

#+BEGIN_QUOTE
（发了一张溜冰场图片）

溜冰
#+END_QUOTE

我：

#+BEGIN_QUOTE
酷😎

摔倒过吗
#+END_QUOTE

她：

#+BEGIN_QUOTE
摔了一次

我小学滑过

以前会，好久没滑了，不会了
#+END_QUOTE

我：

#+BEGIN_QUOTE
溜冰挺有意思的。滑的时候，那种身体快速移动的感觉，很刺激吧
#+END_QUOTE

她：

#+BEGIN_QUOTE
确实
#+END_QUOTE


突然想到问她是否花粉过敏。

我：

#+BEGIN_QUOTE
你花粉过敏吗
#+END_QUOTE

她：

#+BEGIN_QUOTE
不过敏，但我从来不买花😂
#+END_QUOTE

我：

#+BEGIN_QUOTE
花是传递美好的事物，收到花应该是很快乐的吧，你说呢
#+END_QUOTE

她：

#+BEGIN_QUOTE
还好吧，俺家也没花瓶，过几天还是扔太浪费了

我没啥仪式感
#+END_QUOTE

我：

#+BEGIN_QUOTE
收到花后可以把花插到瓶子里，这样多开几天

我也不太在意仪式感，只是想着可以给自己的生活添加一些不一样的东西
#+END_QUOTE

她：

#+BEGIN_QUOTE
我是收到花就觉得浪费[捂脸]
#+END_QUOTE

我：

#+BEGIN_QUOTE
😂没事，钱是别人付的，你只要接受那份心意就好啦
#+END_QUOTE

她：

#+BEGIN_QUOTE
那也是钱
#+END_QUOTE

我：

#+BEGIN_QUOTE
可以自己找花，自己做出来，这样就基本不花钱了
#+END_QUOTE

她：

#+BEGIN_QUOTE
俺家连花瓶都没买，之前我买的几盆绿萝都死完了

买的栀子花也死了

都不养了[捂脸]
#+END_QUOTE

我：

#+BEGIN_QUOTE
唉，你是不是都不搭理它们，给它们浇水啊
#+END_QUOTE

她：

#+BEGIN_QUOTE
浇了

水质不好吧

反正死了
#+END_QUOTE

我：

#+BEGIN_QUOTE
可能是的，家里的水里没有它们生长需要的一些营养

侍弄花草也是蛮费心思的
#+END_QUOTE

她：

#+BEGIN_QUOTE
对

有人养花的都从小区门口河里舀水，自来水不好
#+END_QUOTE

我：

#+BEGIN_QUOTE
刚才想到仙人球应该好养吧，搜了一下才发现它也要满足一些条件才长得好
#+END_QUOTE

她：

#+BEGIN_QUOTE
我养死过多肉

不过那个时候不知道不能经常浇水
#+END_QUOTE

这是16号周五我们最后的几句对话。

2023年6月14日：

我到阜阳工作三天了，每天都主动找她说上几句话。我知道如果我不主动聊天，她就不和我发消息。我不知道她怎么看，可能只是觉得只是两个朋友聊天吧。

10号到14号这几天：会分享自己看到的美丽的画作、看到一篇记录自己当教师经历的文章也分享给她，感慨当老师很幸福。

想到性格，就问她像爸爸还是像妈妈，她说像爸爸，我说自己像妈妈，敏感、感性。

我还说，不觉得男生哭是什么大不了的事情。男生也需要情绪表达。她说，遇到的事的时候总是需要有个人顶住，冷静下来，像女生很容易哭，男生需要安慰，主持大局。但不是所有都这样。

看到商场父亲节活动，告诉她父亲节快到了。

*询问她关于恋爱时做的事情——吃吃喝喝，一起旅游* 。

讨论了关于语言的局限。

有时候，她会略过一些话题不答，这大概也是一种回应吧？

周一我报道她考科四，她考过了，驾驶证邮寄到家，我告诉她已经到公司了。

吐槽了，食堂的饭很贵，坐在办公室里，既困又热又渴。

问她接下来是不是要准备教师资格证考试。她说下午和晚上看书，我问她晚上给她发消息会不会打扰她，她说没事。

13号晚上下班，给她发了公司附近公园的景色。告诉她晚上绕着湖跑了两圈。

2023年6月9日：

中午约她今天晚上或者明天晚上出来走走。她说今晚就可以。

晚上七点二十多从干活的工地回家，着急忙慌地洗澡、换衣服，骑妈妈的电动车去她小区西门。等我到达时已经7点58分了。我八点时给她发消息，她说一会就下来。

之后，等她下来。我就告诉她，在过去半个小时，很慌，想着不能迟到。想给她留下好印象。我们就开始一边走路一边聊天。

最开始的时候，我跟她说：8号凌晨睡不着，是因为担心她。担心可能遇到危险。她说，都是朋友在一起，没有什么。之后，我又问她对于不那么熟悉的人，有肢体接触是否铭感，她说还好。如果两个人不熟悉，手拉着手啊，之类的就不对了。跟她说明那次等待科三考试时，用左手拍了两下她的肩膀。她说不记得了。

我和她谈论了：

- 穿衣搭配：她穿的鞋子我刚好在某个网页上见过，但忘记叫什么名字了
- 日后的安排
- 回答《能让陌生人相爱的36个问题》中的问题
- 很冒昧的问题，有些后悔问她——如何看待性
- 生活经历：想体验更多，她做过服务员，我送过外卖、做过传菜员
- 她的相亲经历
- 我写博客记录的原因
- 问她对我的感觉：感觉你人挺好（被发好人卡了 (´;︵;`)）；我明白此时她对我并没有那种心动的感觉，之前的一切都是我的一厢情愿
- 谈及被男性贪恋美色，慎重告诉她要注意警惕
- 想体验不一样的生活/职业
- 自卑的心理，找到自卑的原因
- 考教师资格证，批改五年级学生卷子，只有两个学生及格；不想在补习班教课，要拉人。教学生心很累的
- 孩子般的自由，无拘无束
- 人情世故：请教练吃饭
- 扩大自己的社交圈
- 相信一见钟情/日久生情——她相信自己会对别人一见钟情，但别人如果说对她一见钟情，她觉得对方没说实话
- 两个人真的要在一起需要缘分，而不是所谓的标签
- 问她是如何看待爱情

有时候，聊天能带来新的可能性

完全沉浸在和她聊天的兴奋中，完全忘记要关注她的情绪。

我在说话时，没有一个劲地表达我喜欢你这个信息。

我们还没到可以畅所欲言的程度，对她来说。她应该把她的不同意见表达出来。

我妹妹说我，我们的对话中，我问的问题，说明我比直男还直男，太过直白。

我是个笨蛋，聊天的时候一直没有敏锐关注到她的表情和反应，看出来她的真实想法。

我或许应该接受这份愧疚——没有照顾她感受的愧疚，如果获得了她的谅解，我就会把这件事忘掉，进而下次还是会这样（没有敏锐察觉到对方的感受）。

我没有问一问她的感受，她感觉这次对话怎么样，有哪些问题我问得不合时宜，我应该问她的，我却没有问，不该如此。

在说话的时候，有些时刻语无伦次，不好组织语言。

对那晚她的靓影神往不已，还有她的手：圆润的、手指缝隙间不知何处染上的橙色，可能是吃东西染上的

2023年6月8日：

现在是凌晨1:34，我睡不着，想着她。

昨天，快晚上十一点。她跟我说，刚到家又要出去。问她这么晚出去干嘛，她回喝酒。当时，我觉得晚上喝酒，对一个女生来说并不安全。问她是喝白酒吗，回喝啤酒，白酒难喝。问她几点回家，她回不知道，会打车。问她一起回家只有一个人吗，回还有朋友。我当时想着，为什么不找我一起去呢，是因为认识没多久吗？心里不是滋味。告诉她注意安全。过了几分钟，我告诉她：当你安全到家时，如果你还记得可以给我发条消息。她回：好，催我睡觉。

*长这么大第一次，因为担心一个女孩子失眠了。*

想着她到底安全到家没，想去送她回家。又担心彼此的关系还没有近到那种可以叫我出去喝酒的程度，贸然说出这样的话，会令她反感。喜欢一个人的感觉，真的是很奇妙，各种情绪涌上心头，让我烦躁又享受。

再读了Hayami恋人絮语系列的几篇文章，思考“什么是恋爱、人与人的关系是复杂多变的吗”之类的问题。

凌晨2:22，她回我到家了，我立刻回早点休息。她问你还没睡啊，我回睡不着了。没有说是因为担心她。

2023年6月6日：

今天晚上想约她出来，问她有没有空。她说：好啊。问她几点合适、从小区的哪个门出来。说好后，我打算晚上快八点的时候去她小区门口等她。

下午回老家干活——把晒好的麦子放起来。等到我正往县城赶时，她发消息说：吃饭比较晚，要不然改天吧。我当时很失望，觉得自己见不到她了。只好回复“好吧”。想着自己过两天就要去工作了，想见面不那么容易。她回：都在一个地方，时间还长，见面很容易。我回：你什么时候有空，跟我说一声。

在回县城的路上，我思绪万千：怀疑是自己太着急，吓到她了，还是有些举动（把手搭在她的肩膀上）过于亲密了。转念一想，如果我不信任她，我们接下来还要往何处发展呢？这样想着，我决定自己去她小区看看，我数了：我家到她家一路上要经过八个红绿灯。这就是我和她的距离。在这过程中，我平复自己的心绪，让自己耐心一些，不要着急，慢慢地了解她。

八点多问了她，平时喜欢听什么歌。一个小时后，她回复：流行音乐或轻音乐。我说到想关注你的网易云音乐，她说第一次有人问她要这个账号，我回：想看看你都喜欢听什么歌嘛3。我说自己听过的歌比较杂，分成听得懂和听不懂的，听不懂的话听旋律。

互关网易云音乐后，我发现一个“一起听”的功能，发给她，她说自己在打电话。问她有没有被打断，她说没有。问她要不要一起听歌，她说还在打电话。我说：那我等等。我去洗澡了，22:23她问：你想啥歌，二十分钟后我看到这条消息，给她网易云发了一起听歌的邀请。

听了痛仰乐队的《两个人的假期》、钟立风的《爱情万岁》，还有她选择的Skeeter Davis的 /The end of the world/ 。问她感觉如何，她说有点那感觉，说不出来。我想是恋爱的感觉吗？我没有问。

快十一点了，她问我该睡觉了吧，她在刷科目四的题目。我回：确实该睡了，下午回家把晒好的麦子装起来，挺累的。她让我赶紧休息。想到之前她似乎提过自己一点多睡觉，问她：都是一点多才睡吗？她回：十一二点吧。我说：晚安。她回：晚安。

2023年6月5日：

这天上午就考科三了。走到待考大厅，刷身份证进去找座位坐下，我坐在她旁边，跟她说话，想让她放轻松。互相记忆着三条考试路线。提醒遗漏的点。在考试以前，还要从待考大厅进到一个稍小些的房间。这个过程是喊名字，喊到我的时候，我右手放在她肩膀上，轻拍了两下，让她放松一些。

在小房间里，我和她坐在一起，回顾路线图。听到喊她的名字，看她离开去考试。我在待考大厅的屏幕上看她上了哪辆车，发到群里，让教练帮忙关注着。

我们五个人考试，都考过了。她的路线是二号，我是三号。我和她一样，考了两次才考过。

下午在家里，我问她晚上几点吃饭，想约她在她家附近的地方走走。

2023年6月4日：

这一天依旧是在考试场地练习科目三，到晚上吃饭的时间，我们一行7人去了一家饭馆吃饭。在去的路上，外面还在下雨，我给她打伞。不时会碰到她的头发，想着她应该感觉到了（头发是敏感部位吧）。在过十字路口时，问她冷不冷，她说冷。有点懊悔没有穿着长袖褂，这样就可以给她穿了。同行的一个女生说：你问她有什么用？言下之意，就是她说自己冷，你也不是没做什么吗？我不这样想，即使没有行动，这样的话语在我看来也是有力量的，能表达我对她的关心。

吃饭的时候，我自然是拘谨的。因为是和不熟悉的人吃饭，担心自己流鼻涕（我一吃辣的就流鼻涕，老毛病了）被他们看见。吃饭的时候，大家讨论饭菜的咸淡，知道她口味偏淡，我也不喜欢吃太咸的。在回宾馆的路上，她说到自己不喜欢饭后刷碗，我也不喜欢。我还知道她喜欢喝奶茶，不能吃酸。

临睡前，说要买奶茶喝。她问我：只有冰的，要不要换常温的。我想到晚上不该吃凉的，容易肚子疼。我跟她说：晚上吃冰的，容易肚子疼。建议你买个常温的，给你自己。她换成了常温的。

2023年6月3日：

这一天我们去考试场地练习科目三。上午在练习靠近三号线起点的路段时，她谈到自己想谈恋爱。我当时没太在意。晚上七点多，练车返程时。一起练车的其他两个女生就开始聊到这件事，聊着聊着，她说自己遇不到合适的，之前母亲安排的相亲，最后也是不了了之。大学的时候没谈过恋爱。

之后那两个女生中的一个，就问我：是否谈过恋爱之类的话，我说自己没谈过，表白被拒了。之后，她就说：那你们两个挺合适，X是99年的，我是00年的。我当时觉得不好意思，想着能只靠着这些就能判断两个人是否相处吗？事实上，一定是不可能的。但是，那个女生的一番话让我设想到这样一种可能——我和X慢慢地认识了解，等到一定程度，就发现自己已经离不开她了。我无法停止这种美好的幻想。

如果我不主动、不放弃那些胆怯的想法，我的意中人何处寻得？

晚上到家后，以车上尴尬的聊天为契机，我向她袒露自己的想法：我们现在还不太了解彼此，可以先以朋友的关系熟悉彼此，待到有一天发现自己和对方在一起有那种处于恋爱中的心扑通扑通跳的感觉，我们就告诉对方，这样就明确自己对彼此的感觉了。她同意了。

2023年5月18日以前的某一天：

第一次加她微信是什么时候不记得了，只知道是在驾校科目二的训练场地。所以这篇文章的日期，选在了训练的某一天。当时，选择加她微信是觉得：哇，这个人蛮有趣的，说话风格呀什么的，彼此简单地聊一聊最近的生活打算。就这样结束了，加了她微信后，我就把她从消息列表删除了，当时觉得短期内不太能有什么交集。
