#+TITLE: 记第一次来深圳
#+DATE: <2024-06-30 Sun 23:29>
#+TAGS[]: 随笔

或许是前不久刚到合肥的原因，当我初到深圳时，并不觉得有什么陌生的感觉。只是觉得自己到了深圳，一个南方的发达城市，来到这里找到工作，一切就都好。

露天地铁让我觉得挺新鲜的，地铁广播三种语言的播报，让我想起[[/posts/first-time-in-guangzhou/][第一次去广州]]，广州的地铁里也有三种语言（汉语、粤语、英语），但感觉深圳地铁的粤语发音没有广州地道，可能是我的错觉。

* 行程记录

周六9:29坐上太和到阜阳的大巴，我带着行李，不方便系安全带，一路上心惊胆战，最终安全到达了阜阳，还是挺好的。进站前吃了一碗15块板面，味同嚼蜡，但好歹是面做的，挡饿。

之后，走进候车室，发现人很多，不禁奇怪：这个时候（六月底七月初），为什么火车站还有那么多人？进而想到：可能无法哪个月份火车站的人都多，只是多与更多的问题。

人们坐上火车，总要到达一些地方，人们的目的不同，当这些目的交织在一起，就构成了我眼前的人群。

从安徽阜阳坐硬卧到深圳，需要将近二十个小时。我睡在上中下铺中的上铺，爬上铺要费些功夫，躺在铺上感觉好危险，旁边的扶手较矮，怕一不小心翻过去，摔在地上。所幸这种事并没有发生。

#+BEGIN_QUOTE
既期待在火车上和异性的邂逅，又觉得这只是短暂的交集，下火车后大家形同陌路。
#+END_QUOTE

见到一个女生，似乎是前一天上的车，身穿白色体恤，及膝短裤，站在那里落落大方。在卧铺走道的椅子上对视过几次，我不知道对方所想，对方亦不知道我之所想，仅此而已。第二天，睡醒后起床，看到她在化妆，她把额头的头发卷起，用各种工具（眉笔、粉扑，原谅我化妆知识的匮乏），让自己的脸更加白皙干净，给人一种美感。

和一位小哥说上几句话，他从兰州到深圳走亲戚，顺便打个暑假工。期间谈到工作，他为自己的学校不好担忧，我不知道该说什么。

处在陌生环境，我会感到拘谨，感到无法自在地把握在身边的事，在火车上是这样，来到暂住的青年公寓也是这样。一旦熟悉了环境，那种拘谨自然就会消失，开始沉着地安排自己的生活。

* 深圳会友

刚到深圳就开始联系在这里的大学同学（运湘），他提议大家一起吃个饭。于是，我、运湘和海丽三人，在车公庙地铁站附近大厦的一家饭店约定见面。我到的最早，坐在饭店门口的等待椅子上读小说。

吃饭不是目的，目的是想要很久没见面的同学聚在一起，聊聊最近的生活。

运湘一毕业就去了国企的建筑公司，这两年一直在深圳，不过国企越来越不行了，他跟我说已经两个月没发工资了。

海丽以前在上海做前端软件开发，后来来深圳做东软的测试外包，和她男朋友在深圳，不过不住在一起。

* 开源社求助

今天是周日，晚上在路边听开源社基础设施组的大家分享本周的工作进展。在前两天的编程自习室里，我分享了自己关于个人书影音数据迁移的想法，水歌让我在例会上分享一下。

分享完以后，想着可以向大家寻求关于工作的帮助。

会后，ted刘天栋老师联系我，拉我进了ALC（Apache Local Community）深圳社区和开源社深圳社区的群，然后我发了一段自我介绍，想让更多人认识自己。

ted老师说，我可以去关注一下从中国开源社区孵化出的Apache项目，尝试给这些项目贡献代码，让更多人认可自己的技术能力。这为我打开了崭新的思路。

止戈也在会后和我聊了一下，我告诉他毕业以来的工作变化，他没有合适的工作机会可以推给我。之后谈到另一个话题，他问我，想不想担任项目委员会秘书和基础设施组副组长。

他解释了这两个职位的工作内容，简单来说就是写总结报告。

我没有深思就答应了。因为我觉得自己成为了开源社的正式成员，就应该主动承担更多的工作职责，为这个社区服务。除此之外，我想要拥有更多的经历来丰富自己，在不同的事情中体验，学到更多原本我不知道的东西。
