#+TITLE: 阜阳马拉松
#+DATE: <2024-04-21 Sat 09:00>
#+TAGS[]: 随笔

* 经过

二十号八点多出发，坐52路公交车，之后转53路，目的地在阜阳师范大学（西湖校区）的体育馆。我不能长时间坐公交，晕车的感觉很难受，坐在公交车内的座位上心神不宁，担心会把早饭吐出来。所幸在这难堪事发生前我可以下车了。

首先，我走到正门口，询问保安体育馆的所在。他笑着指着西边，说你过红绿灯就看到了。我将信将疑，走到十字路口，不确定是否要过去，终于我决定走过去，看到很多人似乎也都是来领取比赛物品的，我放心了，自己没找错地方。

领物的时候，先签安全责任书，然后用身份证取票，之后凭票领号码纸、蓝色布包（装着品牌赞助的东西和比赛可能用到的雨衣）、坚果（领号码的时候人家说可以领坚果，我当时不想要因为觉得挺费事儿的，还要带着太麻烦。一会儿我就改变想法了，之后证明这个坚果我还是需要的）、衣服（这个衣服太烂了，跑完后我的乳头就很疼，后来有朋友建议以后跑步可以穿更舒适的衣服或者在乳头上涂凡士林，下次马拉松赛事可以试试）。

二十一号正式跑步，当时的室友开车带着我从宿舍出发，到地方六点半左右，步行到检录的地方，检录就是安检，不过也就是形式，人们可以从跑道两边直接进行等待区。

人山人海就是用来形容这种场景的，这让我刚开始有些不知所措，后来适应了也就无所谓了，我就一直在等待着，等待人们跑起来，我也好跑起来。等待的过程中，发现了各种各样的人，还在上学的各个年龄段的孩子、各种年龄段的成年人，大家似乎对这次活动很兴奋，各种拍照录像。来到人群中，本以为会很紧张，但没那么紧张。好像这一切都与自己无关，只需要跑，就足够了。人们抱着各种希望来到这里，希望他们达成所愿。

用Keep记录全程发现只有3.7km，我觉得困惑，误差有那么大吗？不过也无所谓了，仅是只有3.7km我也跑得挺累的，后来想可能是因为那段处在人群中的时候消耗了我的能量。

* 其他

那么多人，起跑是如何安排的？后来看到，就是全马的先跑、之后是半马，最后是欢乐跑。在走向起点的过程中，人太多根本跑不起来，直到临近起点才开始能够迈开腿。

在等待的时候，我注意到一个问题：有些人会在拍照录像的时候，不在意陌生人出现在自己的镜头内。这或许是部分中国人的特征，不在乎隐私，自己高兴的时候会认为他人同样高兴。照相摄影的时候，肆意拍摄他人面部，而不在意这种行为是否会侵犯他人的权利。这或许是中国的数据收集公司（所谓的大公司），能够做大做强的一个原因。部分中国人把自己的数据免费给了大公司，以此来换取便利。

处在AI流行的时候，数据就更成了公司的宝贝，各家公司都在推出自己的聊天应用，恨不得让人们住在自己的app里，好让他们收集更多的数据，“更好”地训练自家的大模型。
