#+TITLE: 去深圳国际美术馆——艺术源于生活，是对生活的总结和升华
#+DATE: <2026-05-31 Sun 22:44>
#+TAGS[]: 随笔

我发现自己在选择这种开拓眼界的活动时很随机，往往是在某处看到文章或者知道消息，觉得有意思就想去了。这次也是，我有时会看一下保利票务上有没有感兴趣的音乐剧或其它演出，周三那天很偶然，就看到了[[https://mp.weixin.qq.com/s/UDeaLcja7d0Ix7Jmot_0vA][深圳国际美术馆要办七大展览]]的消息。想去看是因为最近总是高压的工作让我有些崩溃，想要感受些不一样的事物调节一下。这次经历让我想到自己去年去看[[/posts/september-and-october/][印象派画展]]时的事情，那时欣赏了很多梵高、莫奈等大师的作品。

工作上从周三开始去了加工厂出差，在惠州的一个鸟不拉屎的地方，坐公交坐到火车站竟然需要从起点坐到终点站，要花两个小时，无奈只能坐顺风车。昨天才回来，打车回来花了将近两百块，而且这个司机开车不行，头晕难受一路子，到家后悲催地发现：竟然不能开发票（高德打车顺风车开不了发票），也就无法报销。本来工作是赚钱的，我还倒贴两百块，可想而知我有多郁闷。下次再让我出去，绝对不去了。

早上睡到九点多，简单吃个早餐（两片全麦面包+一盒纯牛奶）就出发了。到地方后，按照主题开始观看：

1. 大师之境——布达佩斯艺术博物馆馆藏
2. 东方根脉与当代转化——中国抽象派画作
3. 闪烁的1/∞——科技与艺术的结合
4. 维素绵延——中国传统水墨画
5. 徐冰：字在乐园——《凤凰》作品印象深刻
6. 新链：艺术的未来——艺术的未来和对科技的巧妙运用分不开关系

* 大师之境

我觉得这是几个展中最易懂的一个，因为画的都是自然中存在的事物，而非抽象的符号。即使不在自己的生活范畴里，发挥些想象力也是能够体会到的。我觉得自己能够从这些画作中体会到一种独属于自己的理解。

- 夏，秋两幅作品，作者是[[https://www.mfab.hu/artworks/?artwork_author=veronese-bonifazio][Bonifazio Veronese]]。当我想到夏，想到秋，该怎么表达出来，用画面的形式？作者为什么选择人作为描绘季节的核心？孩子代表着怎样的含义？
- [[https://www.mfab.hu/artworks/8872/][圣父]]，作者是Giovanni Domenico Tiepolo。这幅画吸引我的是它用到了那种蓝色，那种能够看出衣物质感的蓝色，这样一种上帝的形象，看起来还行
- [[https://www.mfab.hu/artworks/517/][Ondine]]，作者是Jules Lefebvre。这幅画吸引人的地方不言而喻——年轻貌美的裸体女子形象。等身的高度，红棕色的头发垂到膝盖，单手触摸着墙壁单手抚发。对置式（重心在一条腿上，另外一条腿弯曲。整个身体呈现S形）站姿让女人好像要动起来。光滑的身体雕塑般的质感，描绘出一种理想美。
- 飞鸽传书。这幅画过于鲜艳了，这种鲜艳让我觉得女孩是很真实的，手握着信鸽，期待它将自己的爱意传递给远方的恋人。
- 红罂粟。罂粟花盛开在绿色的原野上，有毒的花朵却是这样的美丽。
- 阿利加的悬崖岩岸。阳光穿过云层，射下一道道光辉，让我觉得：希望就在这里。

* 中国抽象画作

抽象派画作，欣赏这种作品，更具个性体会，不同的颜色线条搭配出不一样的氛围，欣赏的人注视到不同的色调搭配，会有不一样的感受。

- 荷塘，作者是吴冠中。色块或深或浅地铺叠在画布上，黑色、棕色、黄色、绿色、粉红，没有逻辑可言，不规则的形状，涂鸦般的线条，花非花，物非物
- 灵魂之光，作者是朱德俊。很喜欢这幅作品，混乱不成人形，这是灵魂的形状？蒙眬迷茫，不知所云
- 2019，作者是余有涵。近乎圆形的，波浪分割了几种颜色，界限分明，但是墨迹自然滴落，划过那分界，沾染着什么

* 科技与艺术

最令我印象深刻的有几个：

1. 一个圆形，上面布满了各种不同时刻的钟，将一个人从早到晚的时间都囊括进去
2. 利用透镜和投影仪，表现出日冕的形态，很逼真
3. 星空。星星点缀着漆黑的夜空，深色背景下的，那一颗颗耀眼的星辰，好像我的思想，多密且乱
4. [[https://calculatingempires.net/][计算帝国]]。作者探讨了从1500年到今天，技术与社会结构是怎样变化的
5. 叶锦添的存而有疑，说实话没看懂。现场的黑暗氛围，再加上视频里深沉的讲述，让我觉得有些害怕

-----

艺术源于生活，如果一幅画不能引起自己的共鸣或者引发一些思考，那么这部作品对于我来说便一文不值。即使这部作品很有名。

艺术来源于生活，是对生活的总结和升华。日常的琐碎与不安，让人烦躁无法专注。有些情绪会在画作中得到深刻体现，能让人透过画作感悟自己的心绪。

艺术对于我的意义——溺水时好不容易鼻子接触到空气，呼吸的那第一口氧气。

生活是一天接着一天的，如果工作不是自己感兴趣的，把上班看成坐牢也很正常。而穿插于工作的一些小的爱好，像是真正的自己想追求的生活。艺术是我的一个爱好，欣赏那些艺术作品，让我有种焕然一新的感觉，不再是被工作摧残得不成样子的我，而是沉迷于画中的世界，欣赏那画的美与真。

一些燥热的不安的想法，向我弥漫而来，我无法阻挡只能任由对方侵蚀。我的精神比我的身体先投降，我的肉体也逐渐枯萎，人的与生俱来的意义在这一刻仿佛烟消云散。
