#+TITLE: 好内容
#+DATE: <2022-11-11 Fri 15:33>
#+TAGS[]: 他山之石

** [[https://www.ted.com/talks/roger_antonsen_math_is_the_hidden_secret_to_understanding_the_world?subtitle=en][Roger Antonsen: Math is the hidden secret to understanding the world | TED Talk]]
变换角度，理解计算机科学的事物

** [[https://www.youtube.com/watch?v=Pr4Sw6cYAfU][为什么有些人用一年时间获得了你十年的工作经验？（演讲：学习曲线和Hacking大脑，谈终身学习如何改变你的人生） - YouTube]]
** 口音
https://yufree.cn/cn/2022/04/24/accent/
从口音讲到人的感性

作者生活的纽约，有着来自世界各地的人们，他们的英语也大多存在口音。其实，如果对方的目的是交流，彼此之间不太把口音当一回事。

注重细节确实是对他人的一种礼貌，但礼貌的度应该是构建在相互尊重而不是相互讨好或施虐受虐上的。

现代职业结构的冗余造成大系统里的螺丝钉既不需要有自我意识，也不需要创造性技能，因此会对走流程守规矩特别看重。

通过细节引导情绪化。很多人在将细节的重要性时用的例子大都是一个点没注意到然后某件事失败的小故事。但这里面有点概念混淆，很多例子中的细节其实并不是细节，例如所有的安全检查都不算是细节，缺里都算是事故。

从作者的语文成绩，说到感情脱敏。

#+BEGIN_QUOTE
我小时候摔了喊疼，大概率得不到任何反馈，要是喊得时间长还会被说娇惯坏了，跟别的小朋友打架回家告父母大概率是在家里反思为啥跟人打架后再挨顿打长记性，独生子女也没有兄弟姐妹撑腰，而在学校老师们还比较信奉体罚，所以基本一路成长一路挨打，摆在我面前的经常不是挨打还是不挨打，而是打得轻点还是打得半死，打到最后自然皮糙肉厚，神经大条。
#+END_QUOTE

作者读到生物学博士，跟家庭培养关系也有限。

脱敏对一个人的成长是很重要的。

#+BEGIN_QUOTE
现在的社会环境不论家长还是老师都不可能打骂孩子，这样有利于他们构建自信心，但其内心可能依然是脆弱的，会被很多小事直接搞成情绪崩溃，到成年也一样。但如果脱敏训练足够，那么孩子可能会很叛逆，但至少是经得起风雨的。就我们当前这个不确定性越来越多的时代，今日的安稳与明日的动荡可能就是一瞬间的事，我们并不需要情感细腻的安慰而更需要豁达幽默的心态。

这里的脱敏不是说打孩子，没收手机或断网才是文明的手段，效果比动手好多了。
#+END_QUOTE

作者认为除了要脱敏，还要警惕所谓“治愈”。生理上有病要去医院，心理上有病也要去医院，“健健康康的天天要被治愈算哪门子事”，更像是变相地宠溺自己。很多人觉得世事艰难要对自己好一点，但你对自己好不改变世事艰难的事实。“治愈”的本质是一种移情，把美好可爱的东西跟自己的境遇联系到一起，这里面的情绪有寄托，也有虚幻。如果人迟早要面对真实世界的残酷，那么越早越好，省得总是无病呻吟。

现代社会指定了儿童作为社会层面的保护对象，然后美好世界的童话迷惑孩子们。儿童读物可以简化社会现象，但一定不要歪曲事实，不能通过欺骗来构建儿童世界观，这样不是保护而是宠溺甚至是加害。

人一旦发展到物质资源不缺乏的状态，就开始追名逐利。如果不能掌控自己的情绪欲望，那么那些有针对性的广告就会迷惑你让你上当受骗。做到对这些利用人情绪欲望的事物的免疫。

没了经济利益主导的情绪化，发自内心的声音才更可能被听清楚，情绪表达也会更真实而不是现在人人都去维护一个职业化角色化面具，这是大多数所谓压力的来源，很多人不适合角色扮演，仅此而已。

“脱敏”，建立自己的过滤器。不在乎那些语气助词及背后的含义，就简单去理解对方表达的意思。如果对方期待你的响应，那多半也在期待情绪化释放，这时可以看场合点明对方意图并简单陈述自己的回应或引导对方释放情绪，很多时候仅仅是把自己的情绪说出来情绪压力就会释放一大半。另一对策——隔离情绪化信息源，关闭朋友圈入口。

脱敏可以让我做更多自己想做的事情。这个世界足够允许多种不同的人生，我无意改变任何人的任何看法，所以也不喜欢别人想通过任何方式改变我的看法，这无关对错，只是个选择偏好而已。

** 如何解决信息过载
https://blackglory.me/posts/how-to-solve-information-overload
*** 专注于影响力最大的关键事物
有种被称为”幂律分布“，多见于商业、文化和创意领域。少量的关键事物会影响大多数事物。作者认为——大多数人只是无能的模仿者

关键事物往往具有远大于一般事物的价值。如果有两本书，一本是可被归类到关键事物的书籍，另一本则是被这本书影响的人所写出的书。前一本的价值远大于后一本，因此阅读后一本简直就是在浪费自己的时间。

现实中，一般事物会从各种角度与关键事物进行差异化竞争。

在解决信息过载时，识别关键事物，对减少需要处理的数据规模有巨大帮助。对于信息来说，关键信息与一般信息的差距往往是绝对的，一旦不对等的情况被消除，一般信息就会变得没有价值。
**** 史特金定律 Sturgeon's law
"Ninety percent of everything is crap." 世界上有 90% 的事物都是垃圾。

作者认为在互联网上，至少有 99% 的内容是垃圾。

事物是”垃圾“其实并不是问题，真正成为问题的是人类只有有限的时间和精力。所以对事物的挑选难免会发展成零和游戏，这使得那些缺乏有效评分体系的领域变得不值得投入大量精力，因为区分事物的好坏变得困难低效。
**** 林迪效应 Lindy effect
通过估计年龄和“健康程度”，来判定一个事物是不是会继续存在。一个事物存在的时间越长，它有望继续保持起原有地位的时间就越长。

可以依据该效应，对一件事物是否属于关键事物进行判断。可以根据事物存在的时间，以及它被挑战的次数做出决策。对于一个尚未进入的领域，保守的选择至少会让潜在的失败风险更小。

不过，部分事物长期存在所依赖的优势并不可持续，要小心：

- 如果事物当前地位是靠不对等的竞争手段维持的，则应该考虑它的竞争对手
- 如果事物当前地位是依赖于畸形的环境维持的，则应该远离事物背后的整个领域
- 如果事物当前地位是利用人性的弱点维持的，则应该远离事物背后的整个领域
*** 不会失效的过滤器
解决信息过载的办法有很多，但它们大多有漏洞，根据墨菲定律，有漏洞就一定会出现利用这些漏洞的人。

并且，过滤器在设计时没有考虑到人类的非理性行为。

人类处理信息的能力非常低下，以至于过滤后的信息仍然多到无法处理。

需要处理的信息是无规律的。

时间是一种有效的过滤器，经过漫长岁月而沉淀下来的，关键事物在其中所占比重稍高一些。

然而，把时间作为过滤器缺乏实用性，将等待作为一种策略对很多情景来说是不现实的。
*** 一次是不够的
在这个信息容易获取的时代，太多信息被制造出来，让过剩的好奇心有依托的地方。

那么，如何过滤？

一个简单的应对策略——忽略掉所有只看到一次的新信息。只有当一个信息在不同场合被提及两到三次时，才有进一步了解的必要。
*** 我不需要它：认知上的开悟
信息过载有一个不那么明显的哲学解决方案。这个解决方案基于一个非常简单的事实：当我的认知层次觉得大多数事物都有价值的时候，很难不面临信息过载。

抬头仰望时觉得一切都很庞大，低头俯瞰时觉得一切都很渺小，二者的区别是观察者所处的认知层次不同。

如果要达到更高的认知层次，人们应该强迫自己消化吸收更多信息，不仅要积累信息量，还要提升信息的深度。

#+BEGIN_SRC txt
得益于人类的适应力，在你坚持消化了足够多的信息后，在某个时刻，你会惊觉自己到达了新的境界：你掌握了一套与个人期望高度吻合的模式匹配策略——在大量消化信息的过程中，大脑训练出了一种高效率的信息过滤器。你能比以往更轻松地解构和重构信息，常常能用直觉去补足信息量不足的部分。你能闻到信息的坏味道，意识到信息背后的问题，事件之后的发展经常会验证你的预测。

这时大部分信息对你来说已经变得无趣，因为它们太低级——你注意到信息经常是以某种方式重复的，你对信息已经熟悉到可以很快发现这些重复，然后把它们视作噪音加以排除。

你看待事物的标准因此被拔高，很多事物已经不如原来认为的那样有价值——你发现优秀事物的平凡一面，而平凡的事物比过去看起来更糟——这时候一些真正优秀的事物开始脱颖而出，而以前你从未发现它们竟然有如此高的价值。

当人发觉自己已经在摒弃和拒绝那些不够高级的信息的时候，就离开悟不远了。开悟意味着你对自己熟悉的诸多事物的了解已经深刻到足以用哲学和理性的方法将其扩展到其他事物上，这需要庞大的知识储备和大量的思考。你会发现事物的价值都有待被重新判断，它们的价值往往会开始减少，有些会归零，甚至只剩下负面价值。你很可能会注意到真正有价值的东西总是存在着一些共性，于是判断事物是不是真正有价值也变得越来越容易。对抵达这一境界的人来说，信息过载只是过去式，因为有价值的信息其实是很少的。
#+END_SRC

Dunning–Kruger effect——关于自我能力的判断的认知偏差。
*** 拒绝灵丹妙药：选择最困难的路径
有时，最短、最简单的路径可能是错误的路径；而最远、最困难的路径才是正确的。所有事情都有更简单的解决方案，但却忽略了为了更简单而损失的成本。

作者认为，存在一个终极解决方案，既可摆脱摆脱商业控制，又能完美匹配个人需求。

作者观察到，在某些领域存在着这样的解决方案，但它们不是以最终产品的形式存在，而是以思想、哲学、方法论的形式存在。

只要我掌握了它们，我就可以形成自己的解决方案，而不再需要依赖现成的服务。
** 将博客改造成数字花园
https://blackglory.me/posts/from-blog-to-digital-garden
基于质量对博客内容进行过滤，博客形式对内容并无意义。当以新标准对过往内容进行审视时，大多都无法满足可维护性要求。
如果文章不可维护，那么基于文章的价值就会流失，最终变得没有价值，甚至成为一种债务。
*** 文章的可维护性
题材对可维护性起决定性影响。
容易变得过时和无效的题材所包含的信息本质上更像是对其关联事物的一种端到端测试。信息与具体事物之间的关联性往往十分脆弱。
受限于文章篇幅，篇幅越长越难以维护。
维持良好的文章结构很难，文章本质上属于树形结构，树形结构在处理分类问题时很不堪用。
作者在实践中遇到的不可维护的例子：
一节内容的主题与其他节交叉，修改到最后，节与节之间的耦合部分越来越多。导致修改某处，另一处的内容就需要变动。可维护性会变得很差。
如果需要维持良好的文章结构，就要停止过度照顾读者的感受。参考手册往往是很难读的东西，读到一半，可能会需要跳转到其他部分，以获取必要的前置知识，但参考手册的结构通常都组织得不错。
模式代表着“形式”，“框架”，或者“。
人们潜意识里对文章的理解还处于纸质印刷时期，文章已经发布就很难修改，即便修改也不过是小幅度。
但这种内容创作模式不属于数字时代。
数字时代的信息足够失控，这个时代一天产出的信息量比人类进入数字时代以前的信息的总和还要多。
巨量的信息被存储人们见不到的地方，只有机器阅读。人们在不断地接受新信息。
作者提及“可维护性”会随着时间而日渐消失，因此博客日渐衰微，转向数字花园才是关键。
**** 关键发问：文章是展示笔记最合适的选择吗？
作者说：很多写了多年博客的博主其实不是在写文章，而是以写文章的形式写笔记。
作者对笔记的要求很高，而博客文章并不适合作为写笔记和公开笔记的最佳方式。
作者对笔记的三点要求：
1. 笔记内容要足够内聚，同一主题的内容应尽量聚集在一起，而不是被拆分成多个页面
2. 笔记更适合以大纲视图，而不是文章视图呈现；文章视图的层级结构不够明显，缺乏导航价值
3. 作者不认为 Markdown 是一种适合用来做笔记的格式：Markdown 天然缺乏层级结构。作者的笔记是在 Emacs 里编写的 Org-mode 文档
大多数人无法脱离文章这一形式的根本原因在于缺乏脱离它的能力，因为：
1. 市面上绝大多数博客程序都是面向文章设计的，展示文章以外的结构化内容很难
2. 缺乏一个足够简单流行的大纲文档格式和编辑器：Org-mode + Emacs 的高难度组合劝退了太多人
*** 从博客到数字花园
数字花园的概念会作者重提，他以为数字花园的重点在于重新审视内容创作的流程，将创作比喻为园艺，从而解开来自博客时代的桎梏。
数字花园类网站的大致特征：
- 文章的排列排序是任意的，文章可能不显示发表和更新日期
- 文章没有“草稿”和“已发布”的分别，只通过“内容的成熟度”来描述文章
- 创建新内容不重要，对已有内容的“修剪”和“浇灌”才是
- 不对文章列表分页
*** 作者基于数字花园的改进
- 日期不重要

  对有可维护性的文章而言，文章的发布日期和更新日期都不重要，因为它应该是长期有效的，思考不应因时间而褪色，读者也不需要理解文章的写作背景。根据极简主义的观点，既然它并非必要，就应该舍弃
- 分类和标签引发混乱：停止使用分类和标签，迫使作者将内容的规模维持在无需分类和标签就能管理的程度
- 评论框不是必需品

过去的经历使我意识到缺乏评论框不会阻碍那些真正想要交流的人：如果真的有必要，即使在没有评论框的情况下，这些人也能通过各种方式向我发送信息，这本身是非常奇妙的。我相信那些肯付出更多努力去传达信息的人，所传达的信息相比之下会更有价值。因此我能够心安理得地将没有评论框这件事，作为用户生成内容的过滤器来使用。
- CC 协议没有现实意义
- 退出其他平台
- 内容成熟度的表示方法
- 在一个页面列出所有条目
- 个人知识管理方案公开

  笔记：是以大纲视图呈现的 Org-Mode 格式
  涉及技术细节的文章是最缺乏维护性的那类题材，技术很适合笔记形式，因为笔记对文本完成度的要求比文章低得多：写笔记时，我不需要在意文体和结构，不需要斟酌用词，一切都是以方便使用和理解为目标编写的。笔记能随着使用而逐步更新完善，也可以轻易舍弃。
- 一切都是纯文本
- 保存即发布

* 一些言语

https://twitter.com/FreiheitYu/status/1533076975014772741

大学毕业前几位老师的嘱托，这么多年来都很受用：

1. 要掌握一门能赚钱的技能
2. 务必坚持读书
3. 保持对正义的信仰很重要，但还要有清醒的头脑 
4. 准备挺身而出时，也应当“披挂上阵”而非“赤膊上阵”
5. 保留人文情怀必然会付出相应的世俗代价，不可能好处占尽
6. 人生短暂，该玩的该体验的，不要错过

------


最近裁员新闻很多，和大家分享几点忠告：

1.不论是选择考编考公，还是选择互联网外企 AI 公司等等，都要放弃幻想，现在以及以后，都没有铁饭碗了。很多地方体制内也发不出工资了，发得出工资的地方也到处调任领导，新官上任三把火各种搞改革，面对各种变化和折腾，体制内更难受，因为他们根本没得选。“拥抱变化”不是一句口号，是每一个想生存下去的人必须有的觉悟。

2.真正的铁饭碗不是更大的平台更好的行业，而是价值。你能为他人创造价值，你就永远有饭吃，你能让一个公司的人都有饭吃，你就能当老板。除此以外的什么管理之道，战略规划，企业文化什么都是虚的。做知识付费里赚钱的那批人，都是帮别人赚钱的人，你给我交 300 块我让你赚 1000 块，这种课当然能买爆；税筹规划的生意为什么火，我帮你“避税”几千万，收你几百万不过分吧。这样的生意不需要“营销”，不用讲概念，利益驱动的生意自然就滚起来了。

所以，做任何公司做任何岗位，都要为如何帮老板挣钱而焦虑得睡不着觉才行，你帮老板买车买房了，老板当然愿意给你分个三瓜俩枣，够你生存的。不要总觉得资本家在剥削你，反过来想，你就一定会是人生赢家；

3.越是熊市，越应该慢慢定投收集筹码，牛市来了才追得上，所以不到万不得已走到绝境，不要轻易被震荡出局洗下牌桌，不要过早地离开一线城市或者竞争激烈的行业、公司，等到疫情来临，看到某些“新一线”城市的骚操作后，你才会明白苟活在上海这样的城市有多么大的安全感。房子会有的，只要你熬得住，熬得起。不要听信父母辈对于安全感的定义和想象，这个时代变了。会冲浪的人才有最大的安全感。

4.既然是吃青春饭的工作，就狠狠地吃青春饭，在年轻的时候攒够一辈子的钱早点转化成固定资产提前退休，不要拿着低薪和期权去创业公司 996，那纯属有病。去正常点的公司下了班再接着副业接着斜杠或者不停社交见人攒资源，一刻也不要休息，萧红说“生前何须多睡，死后自会长眠”，换做这里可以改改，年轻的时候自己卷自己，老了卷不动了自然有的是时间休息。（但也不是让你把自己累到猝死，就不要轻易偷懒摸鱼混日子）

5.陪伴家人也是需要高质量的用心的，用你在公司学到的那一套，组织和规划一场别开生面的家庭聚会，让他们一下子可以记很多年，出去社交都有谈资——“哎哟我那个侄子哦，上次回家给我们玩了一把无人机/打了一次 VR 游戏/看了一个什么话剧，哦哟哟新鲜玩意。”然后用少量高质量的服务解放你的假期时间，不要没完没了的家庭聚会，堵住他们的嘴，也让你父母抹得开面子，然后把剩下的时间把自己关起来学习，加班，搞自己的事情。亲戚没有同行可靠，你老了还是得靠同行互相提携混饭吃。

by 李嗲 Lydia

---

新时代，拥抱变化

by 曹大

这个世界其实一直是变化的，最近这些年，中国的经济发展很顺利，很多年轻人会认为这是理所当然，但我们知道，从历史长河来看，稳定和增长其实是偶然的，而动荡和起伏才是历史的主流。

所谓调整也有两面性，从经济结构上来说，这些年高速增长的背后，确实很多历史积淀的问题需要去解决；确实有一些不和谐不健康的经济扩张需要进一步的规范；确实有一些分配不公和挥霍资源的行为需要遏制。当然，从节奏上来说，是否可以做的更平稳一些，更人性一些，值得商榷。

作为普通人，我们知道，时代的一粒灰，就可能是摧毁一个家庭的一座山。新的岗位会出现，新的机会也会出现，但这些更多属于新的一代人，作为旧人，如果只是坐等，那么很可能，你等不到柳暗花明的那一天。

这次变化很可能是深远的，年轻一代人可能不知道什么是深远的变革，因为你们所经历的中国，基本上是属于一条快速车道上直线疾驰的状态。但年长的人会记得，什么是深远的变化，比如 80 年代开始的改革开放，比如 2000 年的闯关世贸。

这绝不是前几年，一些防范投资过热，或者紧急救市的那种经济政策调整，这是深层次的经济格局调整。我们每个人，都应该认识到这一点，有些改变，很可能是长期的。

高速增长从来不是经济发展的必然，特别是中国这样变态级的选手，从追求增长到优化分配，是这次变革的核心理念。而优化分配，当然也是为了后续更长久的持续发展。

那么，我们还要记住一个事实，虽然知乎上各种年薪百万，甚至我看到有人觉得毕业入职巨头拿个年薪三四十万属于羞辱性的工资。但现实是，在现在的中国，月薪过万就已经是高收入人群。家庭年收入折合三四十万人民币，即便在很多发达国家，也是妥妥的中产阶级，而且通常是中产阶级里比较靠上的部分。美国也不是只有硅谷和互联网巨头，美国传统领域的技术人才薪酬，其实也不过如此。

认清这一点，也就希望年轻人认清一个现实，优化收入分配，不代表你们的收入会提升。因为你们很多人，特别是互联网行业从业者，很多人自毕业始，就已经是中国的高收入阶层，这听上去很诡异，但这真的是现实。

年轻人面对变局，应该做怎样的准备：

一、调整预期

每年稳定加薪，收入稳定增长，可能不再是常态。求职的时候，可能面临的竞争难度更高，面临的竞争压力更大。虽然优秀人才仍然会被市场追逐，但优秀的标准，我瞎猜一下，应该会飙升。因为提供给优秀人才的整体坑位变少了。 **随时了解自己在业内的合理薪资水平。**

二、增强通用能力的训练

什么是通用能力：英语能力、写作能力、沟通能力、逻辑思维（读一些有关经济学、博弈论）

更好地理解世界，更好地理解变革的因果关联，这有助于理解自身的位置和价值，在关键决策中做出合理的判断

三、健康的心态

不要因为前景不好就自怨自艾，乐观积极的心态能让未来的贵人拉自己一把。

四、跟踪时事动态

很多时候，一个人所谓预判能力强，并不是他真的预判到了某些事情，而是某些事情已经发生的时候，别人没有意识到，而他意识到了。你并不需要去猜测未来，你只需要比别人更早的意识到正在发生的事情，你就已经能掌握判断先机。

比如，蚂蚁金服暂停上市的那一刻，其实很多互联网巨头后续的事情已经决定了，但很多人没有意识到，仅仅当作是一个孤立事件，其实很多很多看似无关的事都是同源的。

五、做好个人和家庭风控

六、让自己增加一些多样性

七、帮助值得帮助的人

八、保持健康

---

天气冷了，跟大家说点儿暖心的话吧。

分享一个我自己觉得很有帮助的心法：“把自己想象成农民一样去生活”。

怎么理解呢？其实我一直认为，传统的农民，是最理解、最懂得遵从自然规律的一群人。什么时候播种，什么时候施肥，什么时候采摘，什么时候要做御寒的准备…

春播、夏长、秋收、冬藏，大自然无声无息，但自有规律。农民不会有任何想要和大自然较劲的想法，只是理所当然地接受一切，然后做好准备。

谁都知道，冬天就是不适合播种的；谁都知道，春夏就是不能被浪费的。所以冬天，在炉火旁；夏天，在田地里；冬天就过冬天，夏天就过夏天。

但是在急遽变化的年代里，很多人喜欢“较劲儿”。

什么是较劲呢？不断把注意力投射到自己不可控，或是某种负面的“可能性”上（仅仅是众多“可能性”之一而已）。然后，为了回避这种不安全感，想要去“操控”世界。

比如：感情中，遇到分歧和矛盾，很多人的第一反应是“对方为什么不能是这样？”而不是“ta 是这样的人，我要怎么和 ta 相处？”再比如，职场上，遇到分歧，小朋友可能会想着要争取说服对方、评估自己喜不喜欢跟这个人合作，但“老油条”们往往会思考“如果我需要和 ta 合作，我要提供什么能提高成功的概率？”

当前者想的是“这个世界为什么不能来适应我？”“这个是好的，那个是不好的”，后者早已飞快接受世界展现出的每一个不同然后思考“我怎么样更好地配合这个世界？”

以前，每当遇到类似的时刻，我就会问自己，农民会天天质问老天爷今天为什么不下雨吗？不会，也不能。

于是心安，该做啥做啥；把自己忘掉，钻进去思考“这个事情要求我怎么做”，结果证明比歇斯底里的抱怨和 judgment 有效太多。而一旦形成做事的反馈正循环，你会发现，世界对你是如此慷慨恩赐。

更重要的是，一旦开始用这种视角审视自己，就会发现很多事情并不是那么理所当然。就像大自然并不必然会在曝晒之后降雨一样，你的对象也并不必然会理解你，你的上司也并不必然要认可你。怀着这种谦卑，就会对生活中的美好有更敏锐的感知和更知底的珍惜；而这种态度，会引导身边人进一步把美好赐予你。

这就是“不较劲”的智慧。

by 即刻-唐唐唐僧人

-  [[http://www.catb.org/~esr/faqs/smart-questions.html][How To Ask
   Questions The Smart Way]]
-  [[https://docs.alpinelinux.org/user-handbook/0.1a/index.html#_definitions][一些关于
   Linux 的名词解释 /Alpine User Handbook - Alpine Linux
   Documentation/]]

* 有启发的句子

从 Slava Akhmechet: How I Read 这里知道，可以建立一个关于读书的实验室，实验室里有很多工作台，每个工作台是一个领域，领域下是通过阅读五本书的一个组合，获得的一种工具。工具多了。就成了瑞士军刀。这样遇到问题就能够根据问题领域找到应对之道。

--------------

#+BEGIN_QUOTE
  我一生中不爱任何民族，不爱任何集体。不爱德意志，不爱法兰西，不爱美利坚，不爱工人阶级，不爱这一切。我只爱我的朋友，爱我身边的人。我只知道，只信仰的唯一一种爱，就是爱人。------汉娜.阿伦特
#+END_QUOTE

--------------

喜欢的事用心去做，不为职责。------电影《假偶天成》

--------------

'Cause impress.js may not help you, if you have nothing interesting to
say. -- [[https://github.com/impress/impress.js][impress.js]]

--------------

成熟的一些标志：

#+BEGIN_QUOTE
  能克制欲望，不追求即时反馈，延迟享受。

  保持一致性，无论在人群中还是独处时，知行合一，不卑不亢，不矫揉造作，不哗众取宠。

  心中始终有底线、有原则、有追求。

  时刻反省自己：what在做什么、why为什么这样做、how如何做的更好
#+END_QUOTE

------ 尼古拉斯·鱼

https://www.scarsu.com/escape\_from\_the\_world/

--------------

#+BEGIN_QUOTE
My friend Jason, who'd just finished his Ph.D. in Applied Physics, said
the wisdom he'd learned was “Don't squander your ignorance.” He
explained that once you learn something, you end up taking it for
granted and it becomes so much harder to overcome your tacit knowledge
and ask simple, but important, questions.
#+END_QUOTE

不要浪费你的无知。当你对一门知识毫无所知时，最容易问出简单而重要的问题。

一旦你习惯了某种现象或事物，认为它是理所当然时，思维就不知不觉受到了限制。
https://www.timescale.com/blog/how-postgresql-views-and-materialized-views-work-and-how-they-influenced-timescaledb-continuous-aggregates/

Every person learns at a different speed and that's ok.

Is your speed, and you'll be fine in the future if you are consistent.

Don't compare yourself to others because we tend to see only the good in
them.

Learn at your pace.

Great point, everyone's journey is different. Just take small but
consistent steps everyday

autfu 的开源经历 [[https://antfu.me/posts/about-yak-shaving-zh]]

--------------

Randy 的编程经历 [[https://lutaonan.com/blog/my-coding-road/]]

把自行车做成了自动驾驶 [[https://www.bilibili.com/video/BV1fV411x72a]]

钉钉创始人陈航的成长故事 [[https://cjxy.zust.edu.cn/info/1075/1727.htm]]

--------------

丁红的奇特的、令我向往的人生经历（海马星球播客已被封杀）
[[https://www.jianguoyun.com/p/DWVRG5MQzZOlBxjFyaUE]]

-  选择与自己志趣相投的朋友，拒绝不合适的朋友
-  有些事情，只有做了，才会看到，有很多人，在做和我一样的事情
-  考试这种事情，它不是个凭运气的问题；它的结果取决于，你花多少时间和毅力的问题
-  先试了再说，不要想着自己干不了；（6 分的时候做成了一件 10
   分的事）一个机会只给你打 6
   分，你要拼命争取那个机会，为什么？失败了是应该的，万一不小心成功了呢？如果你真的很努力地争取这些机会，你就会很努力地弥补这些不足，慢慢的你的能力就会往那个方向提高；如果一个机会给你打
   10 分，那个机会本来就是你的，没有必要争，就看你要不要
-  对一件事的爱够不够？如果够，你就能够排除万难，做到你想做的事情

编程启蒙/从社区学习/个人竞争力（本期人物：Randy，AB）
[[https://binary.2bab.me/episodes/008-enlightenment-n-self-innovation]]

-  Randy
   对编程的理解升华到信仰------《[[https://movie.douban.com/subject/3205624/][社交网络]]》
-  Randy 的启蒙书《JavaScript DOM 编程艺术》和《JavaScript
   高级程序设计》
-  了解做一件事，如何入手
-  人是不可靠的，让程序辅助自己编程
-  开源社区帮助 Randy 赚取名声
-  前端简历没有区分度
-  在技术社区和别人不一样
-  每天看 Twitter、HN：看别人怎么解决问题
-  听技术大会 JSConf，React Conf
-  习惯于英文技术环境

--------------

maya 的故事，让我记忆深刻
[[https://www.xiaoyuzhoufm.com/episode/61257677cc5f215c6e0b868a?s=eyJ1IjoiNjA1NGU4NjFlMGY1ZTcyM2JiMjRjMzQ4In0%3D%0A]]

-  如何理解自己和父母的关系

--------------

[[https://twitter.com/codingyuri/status/1437019319557308416?s=19]]

-  做真实的自己
-  不知道一些事情是完全 OK 的
-  参与进自己的学习活动中
-  变得强大起来，不受别人的消极影响
-  建立有意义的链接

--------------

[[https://mp.weixin.qq.com/s/z_-jB2bhL6HYyGHg2MzOcg][张一鸣：我的大学四年收获及工作感悟]]

-  做好自己事情的同时，尽自己最大努力帮助别人解决问题
-  有好奇心，能够主动学习新事物、新知识和新技能
-  对不确定性保持乐观
-  不甘于平庸
-  不傲娇，要能延迟满足感
-  对重要的选择要有判断力

--------------

[[https://www.xiaoyuzhoufm.com/episode/5fca27e0dee9c1e16d0eb010][Steve
说 212 期 - 杜素娟 - 文学是人生的后悔药]]

-  建立多元价值体系，相信自己

--------------

[[https://treecat.cn/%E5%85%A5%E8%81%8C%E5%B8%86%E8%BD%AF%E4%B8%80%E4%B8%AA%E5%8D%8A%E6%9C%88%E6%9C%89%E6%84%9F/][入职帆软一个半月有感]]

------


#论独立思考

假如一个庞大的图书馆被弄得乱七八糟，其用途就不如一个小型然而井井有条的图书馆。同理，你可以积累丰富的知识；不过，你要记住，假若你对这些知识并不进行独自的深思熟虑，这些丰富的知识给你的价值，就比少量的知识给你的价值要小得多。因为只有当你把每一真理都同其他真理比较后，你才会使你的知识有条不紊，你才可能真正占有你的知识，把它变为你自身的力量。你能够深思熟虑的仅仅是你所知道的东西，因而，你应当主动学习；反过来说，你所能知道的也仅仅是那些你深思熟虑的东西。

看来，你可以自觉地使自身投入读书和学习中，然而，你实际上不可能使自己完全投入思考：思考需要精心培植，就像火苗需要风扇助力一样。它需要对其本身的目的保持某种兴趣。这种兴趣，或是一种客观的兴趣，或是一种纯属主观的兴趣。后一种兴趣只可能关注影响我们个人的东西；而前一种兴趣只属于那些就其本性便愿意思考的人，即那些把思考看作与呼吸一样自然的人，而这类人微乎其微。这就说明，为什么大多数学者并不会思考。

大脑凭自身独立思考所产生的效果，与那些通过读书所产生的效果之间存在的差异，是非常非常之大的；所以，使人的心灵下决心思考与使人的另一部分心灵下决心读书这种根源性的差异，乃在继续扩大。这是由于，读书是强行在人的头脑中注入思想；这些思想在读书的时候，与人们心灵的情绪和指向是背道而驰的。这就如印章在蜡块上打下其印记一样。心灵完全听凭外在的强制，毫无兴致地去思考这、思考那。相反，当独立思考时，心灵任随其自身的兴致。此时，思想更多的是被它周遭直接环境所决定，或由联想或其他东西来决定。而可见的周遭直接环境并不像在读书时那样，向心灵强行注入某种单一的思想；它们只向心灵提供思考的契机和素材，让心灵按适应其本性和当下情绪的方式去思考。其结局是：大多数情形下，读书都会使人的心灵失却弹性，就像久压的弹簧一样。

所以，一个人若想在根本上决不具有一点个人的见解，那么，最保险的方式，就是在你有空的时候立即拿起一本书。实际生活中这种情形的存在，正好说明，为何博学使大多数人变得迂腐和愚笨，还不如按他们的本性任其发展；而且，还使他们的写作失却所有生动活泼的感染力，他们正如普柏所说：持续地读个不停，但自己的书却从没有人读。

从根本上说，只有我们独立自主的思考，才真正具有真理和生命。因为，唯有它们才是我们反复领悟的东西。他人的思想就像别人餐桌上的残羹，就像陌生客人落下的衣衫。

读书仅仅是独立思考的一个代用品。它意味着让他人引导你的思绪。于是，许多书的作用，不过是告诉人们使你铸成大错的方式有多少，使你误入歧途的程度是如何的深，假如你真要听它们的引导的话。——所以，只有当你自身的才志枯竭时你才应去读书；当然，才志枯竭即便在仁人智士那里也是经常发生的事。时常或有这样的情形发生，一个你凭独立思考缓慢和苦苦思索都不得其解的真理或洞见，会在某一天被你在一本已经写成的书上轻易地发现。但是，假若你是经由自己的独立思考达到这一点的，那么，在更多的时候会更有价值。因为，只有在此时，它才会作为一个内在部分和活生生的成员进入你思想的体系中，与你的思想结成完美和牢固的和谐，与它的其他推论和结论协调一致，带着你整个思维方式的色彩、印记，并在你所需要的时候随叫随到。因而，可以说，它已经坚固和永远定居在你的心灵中。歌德诗歌中，对此有完美的运用，甚至作出完美的解释：那些你从父辈继承而来的东西，你必须首先通过自己去赢得它，如果你想真正占有它的话。

一种纯粹靠读书学来的真理，与我们的关系，就像假肢、假牙、蜡鼻子或人工植皮。而由独立思考获得的真理就如我们天生的四肢：只有它们才属于我们。这就说明，为什么一个思想家和一个学者是截然不同的两码事。那些终其一生于读书和靠书本获得智慧的人，就像那些凭旅行指南了解一个国度的人一样。他们可以对大量事物都采撷到一些信息，但在根本上，他们并不具有对该国度究竟如何的联贯、清晰、全面的知识。相反，那些毕其一生于思考的人就像那些亲自访问过该国度的人，唯有他们才真正的熟悉这个国度，具有关于它的联贯知识，而且才真正在这个国度中流连忘返。

独立思考的人与日常那种书本哲学家之间的关系，就像目击者和史学家之间的关系一样。前者所吐露的是他自身的直接经验。这就说明，为什么独立思考的人之间，其观点在根本上都是一致的，他们的差异仅仅是出自他们看问题的角度不一样。因为他们所表达的只是他们客观上领悟的东西，相反，书本哲学家们，所报告的或是这个人所说的东西，或是那个人所思考的东西，或是另外一个人又反对的东西，等等。所以，他要比较、掂量、批评这些陈述，进而找到问题的真理所在。由此看来，他实际上酷似具有批评眼力的史学家。

纯粹经验与思考的关系，就像进食与消化的关系一样。当经验夸口说，唯有通过它的发现人类知识才会发展时，就像口腔夸口说只有它维护着身体的活力。

总之，只有那些从一开始就是由你内心指导而进行的思考，才具有价值。思想家，可以被分成以下两种情形：那些由其自己内心的指导而进行思考的思想家，和那些受他人指导而进行思考的思想家。前者是真正的为其自身的思想家，他们是真正的哲学家。他们内心之中本身就充满了热情。他们生存的快乐和幸福全在思考活动之中。后者是雄辩家，他们把自己表现为思想家，进而从他们企求自他人那里得来的东西中去寻找幸福。这就是他们渴望的东西。一个人，究竟属于哪一种类型的思想家，可以从他整个的风格和气质中很快地看出来。李希腾堡是前一类型之典型，而赫尔德则是后一类型之代表。

精神产品要受到赞扬，其命运往往不幸。它必须要等待那些本身只能写点低劣作品的人，来吹捧它高尚。一般说来，它必须从人类的判断力手中，接过自己的皇冠；就像宫人无生殖能力一样，这种判断力，对大多数人来说，也的确是微乎其微。他们并不懂得如何识别真假良莠，如何辨认真金黄铜。他们感受不到平庸和超凡脱俗之间的巨大差异。没有人独持己见，大家都是人云亦云，这是超凡脱俗之人难以发现的口实：这也是平庸之辈尽力让不寻常之人脱颖冒尖的伎俩。其结果，就造成了一句古老诗歌听说的那种退化现象：大地上，哪有伟人的宿命？他们不再生存，人们不欣赏他们。

一旦有真诚和优异的大作问世，它首先面临的是，它的前进道路上，充斥了不少低劣的作品，而且这些作品还被人们看作是杰作。它费尽口舌拼命为自己争得一席地位，并参与到时髦的潮流中去。不需多久，它很快就被人世间涌现出的那些矫揉造作、头脑简单、粗俗不堪的模仿者所淹没，这样，它就可以悄悄顺利地进入到天才的殿堂之中。由于看不出他们之间有什么区别，原作者严肃地认为这些模仿者同他一样都是伟大的作家。正是出于这个原因，伊阿特遂用这样的诗句引出了他著名的二十八个文学寓言：在任何时候，那些庸俗的大众，总是良莠不分、黑白颠倒。

莎士比亚一去世，他的戏剧就让位于本·琼生、马辛杰、鲍蒙特以及弗莱彻，而且，一百多年来都一直拜倒在这些人的门下。同样，康德一丝不苟的哲学思考，却被费希特这个骗子，谢林这个变色龙，雅各比那唬人和虚假的胡说，以及最后发展到黑格尔这个纯粹无赖等人所取代。黑格尔还被人们抬高到一个比康德高得多的地位。即便在那些大多数人都熟悉的领域，我们也发现，瓦尔特·司各特先生这个无与伦比的大师，被那些一钱不值的模仿者很快就踢在一边了。

这就在于，任何地方的公众都不能感受出那些优异的东西，因而，要感受那些在诗歌、艺术和哲学领域的成就，其人数就微乎其微了。而这些领域的著述，才值得我们特地注意。所以贺拉斯说：上帝、人类、甚至大街上的广告牌，都不允许诗人成为一个平庸之辈。那些缺乏正确判断的可悲情形，充分表现在科学领域，表现在那些错误的和被人拒斥的理论的苟延残喘中。一旦这些理论被人们接受后，它便会阻扼真理达五十年或数百年之久，就像石头筑起的堤坝对海浪的制止一样。哥白尼甚至在时光流逝了近百年后，还没有取托勒密而代之；培根、笛卡尔、洛克，在开辟自己的道路时，花了极为缓慢和漫长的时间。牛顿也复如是。人们可以看一看莱布尼茨在与克拉克争论时，是怎样对牛顿的引力体系报以仇视与轻蔑。虽然牛顿在他的《原理》一书出版后还活了四十年，但其理论却是在他临死时才受到一部分人的青睐，而这只是在英格兰；在英国之外的地方，照伏尔泰对其理论的描述看，其追随者不过二十人。

正是由于伏尔泰的这篇描述的缘由，牛顿的理论才在他死了二十年后在法国得到人们的承认。当时，法国人正坚定、顽强以及充满爱国情怀地沉醉于笛卡尔的旋流中。而就在四十年前，法国的学校对笛卡尔哲学却是完全禁止的。不过，达热苏司法官仍不给伏尔泰以阐述牛顿学说的出版权。相反，牛顿提出的荒诞不经的光学理论，在歌德光学理论问世了四十年后，仍在这个研究领域居于至高无上的霸主地位。虽然休谟笔耕甚早而且完全以通俗的笔调写作，然而，他在五十岁之前，却无人注意或被人忽视。康德毕生都在写作和教学，然而，他在六十岁后方有声名。艺术家和诗人的园地，多少比思想家的宽广一点，因为他们的读者群要多至百倍。不过，在莫扎特、贝多芬有生之年，公众又是怎样对待他们的呢？人们是怎样对待但丁，是怎样对待莎士比亚的呢？如果莎翁的同时代人多少看重他的一点价值，那么，在那样一个绘画业空前繁荣的时代，至少会给我们留下一幅描绘他的杰出和可信赖的画像！而现在，只留下一些非常使人怀疑其真实性的画像，以及一幅十分拙劣的铜版雕刻，还有在他墓台上的那幅最糟糕的半身像。

这样缺乏判断的可悲情形，还在于这样的事实：每一世代，早先时代的优秀作品无疑都受到赞扬，而其本身时代的东西都无人赏识。本应倾注在这些作品上的力量，却花费在那些低劣的粗制滥造之物上。于是，当货真价实的东西在它本身的时代出现后，人们认可它是非常迟缓的。
