#+TITLE: 读文章《左耳朵耗子的话》
#+DATE: <2023-05-19 Fri 15:13>
#+TAGS[]: 他山之石

[[https://mp.weixin.qq.com/s/bOnW8gDJ-dXp4KbAjhDw9A][左耳朵耗子的话]]

* 创业

** 为什么会创业？

是为了帮助中小型公司，系统性地解决应用云计算技术所产生的问题。

** 创业方向选择

做网关。

用户需求：

1. 高并发，如营销活动
2. 提高上线速度，要用到灰度发布、实时发布
3. 高可用，因为用户量大、速度快，系统必然不稳定

抽象一下：

- 流量治理
- 服务治理，Java->Dubbo或Spring Cloud
- 资源治理，Kubernetes
- 数据治理

所以，陈皓前辈选择做流量治理+数据治理（监控），两个部分。

数据是没有用的，只有把数据关联起来才有意义。

由关联起来的数据，产生信息；从信息里找到因果关系，才会有知识；有了知识以后，才能导出公式完成一些事情。所有的科学实验都是走这条路。

** 为什么会选择Go语言

选择技术，考虑两点：

1. 很高的扩展性
2. 技术门槛要低

项目推进的阶段，可以划分为0到1、1到10、10到100。

- 0到1，语言随便选，可以根据自己喜好来；
- 1到10，要开始尊重两个东西：开发速度快、保证稳定性和性能；
- 10到100，只剩Java。

** 创业几年的反思

“条件受限是件好事”，它能让我们思考当更重要的事情是什么。

所有的路都是可以走的，不用担心。但不是纯靠坚持，关键是你一定要去想方法，想更好的、更优的解。这个事很关键，千万不要使蛮力，没有太大意义。

关注你的重点，不追小兔子。

* 技术

** 技术不是用来写CRUD的

一个人，一家公司，如果不思考的话，那颠覆你的往往不是这些云计算、低代码之类的技术，而是任何事情。 *因为你只是在按部就班地做事情，别人让你做啥就做啥，你没有去想更多。*

真正的技术是要拿来做创新的，你要去颠覆点什么，要去创造点什么。

** 基础知识的意义

学好基础底层技术的原因：

1. 要知道技术的原理
2. 遇到一些比较难解的问题，这些基础知识会派上用场

** 如何选择技术

为什么问这个问题？它背后的目的是什么？

是想让别人替自己做决定，还是其他。

追逐那些主流技术，站在技术的风口上。如何技术兴起才一两年，那么学习这些东西的价值没有那些 *流行一二十年的技术* 大。

** 如何完成早期的技术积累

想着去更好的地方学习技术。

人生路上，选择做那些别人认为不可能的事情做。别人不敢想的事情，如果我做成了，成就感是巨大的。

* 成长

** 996没有成长怎么办

思考找工作的目的。

如果找工作是为了生活，不让自己饿死，那996顺其自然即可。

如果是为了实现自我价值，那么如果现在的公司不能帮你达到这样的目标，你就应该勇敢寻找能够帮你达到目标的公司。

*这是一个互相成就的事情，公司成就员工，员工成就公司。*

** 大公司和小公司的权衡

无论公司大小，都能学到东西，关键是要用心。

在大公司能学到三件事：

1. 组织管理。调动很多人共同完成一件事；
2. 怎么挣钱；
3. 大公司里的高手是怎么工作的。

无论在大小公司，都有高手存在，跟着他们学习，让自己更快地进步。

** 管理时间

分为向下管理和向上管理。

向下管理，就是管理自己的时间。

向上管理。

比如一件事本来需要一个星期才能完成，他让你两三天做完。可以先答应下来，但是有附加条件：

Option 1 ：我可以再按时完成，但是质量别想。

Option 2 ：你给我足够的时间，我保质保量全部交付。

Option 3 ：我还是按你这个时间，但是你必须砍掉一些需求。

沟通的技巧：从来不说“不”。说“是”，但永远是有条件的“是”。

** 怎么才能学得更快

学习某件事物，就要把它抽象为一棵知识树。学习的过程就是往这棵树里加东西。

比如说学习编程语言，一个编程语言一定会有数据类型、条件语句、变量等概念。

** 学了就忘怎么办

学了就忘的原因是，用记忆去学，而不是基于问题去学。任何一个技术都是在解决一个实际的问题。一定要明白，学习这个技术，要解决什么问题。它是为什么而生的，当你明白这个“为什么”以后，才能记住那些原理。

必须要告诉别人，你到底解决什么样的问题。

当我们想到 Why 时，这是理性学习；当我们想到 What 时，这是感性学习。

学习一定是从感性到理性的。如果只学单一的东西，不会有那么多疑问。遇到一些实际的问题，在解决这些实际问题的时候，也会去真正地理解这个技术。

*带着问题去学习。*
