#+TITLE: Heartfelt talk with father
#+DATE: <2024-05-06 Mon 20:23>
#+TAGS[]: 随笔 English

My father cried again and spoke from the heart, and I worried that by forcing me to get a job (any job I could do, even manual labor) he was looking down on me and didn't know what I wanted to do.

That wasn't the case, my father was telling me what he knew:

- Income comes first.
- When you're young, it's good to suffer as much as you can.

If you can't make money, you'll lose money every day you eat. If you can't make ends meet, you won't have the capital to do the work you want to do.

I said I didn't want to go home because I didn't want to hear them pressuring me, and I thought I knew what I had to do, and I saw the difficulties at home.

I unconsciously think that my father looked down on me, in the speech afterwards, he cried and said, no parents look down on their children, all love their children, give you pressure is to hope that you can grow up quickly, in the suffering thinking can have a metamorphosis, the father gave the child's love is different compared to the mother, do not express is not because there is nothing to say, but want to express are embodied in the behavior.
