#+TITLE: 心理学发展史
#+DATE: <2022-11-14 Mon 15:17>
#+TAGS[]: 他山之石

Source: https://nobaproject.com/modules/history-of-psychology

主要介绍心理学在美国的发展实践。

-  discern 了解

阅读目标：

-  precursors 前兆：描述心理学建立的前兆
-  知晓美国心理学史上的关键个人和事件
-  描述职业心理学在美国的兴起
-  培养一种对科学进程发展和改变的理解
-  认识到女性和有色人种在美国心理学史上的作用

** Introduction

心理学的开始：

-  古希腊
-  19 世纪晚期，心理学被正式提及并形成

以上是心理学开始的两种观点。

本书以 19 世纪中期作为起始点。为了方便，称之为现代心理学史。

** A Prehistory of Psychology

美国心理学的前身在哲学和心理学中。John Locke 和 Thomas Reid
两位哲学家提出经验主义（empiricism），核心是一切知识来源于经验。洛克、里德和其他人的工作强调了人类观察者的作用以及感官在定义大脑如何获得知识方面的首要地位。在
19
世纪早期的美国学院和大学里，这些原则在精神和道德哲学的相关课程上被教授。大多数情况下，这些课程是基于智力、意志和感官的能力来教授心智的。

** Physiology（生理学） and Psychophysics（心理物理学）

关于心灵和知识本质的哲学问题，在19世纪通过对人类观察者感觉系统的生理学研究得到了证实。德国生理学家
Hermann von Helmholtz
测量了神经冲动的速度并探索了听觉和视觉生理。他的工作表明，我们的感官可以欺骗我们，而不作为外部世界的镜子。这些工作表明，即使人类的感官是容易出错的，心灵也可以用科学的方法来测量。总之，它表明心理学是可行的。

Helmholtz
工作的一个重要影响就是告诉我们，存在一个心理现实和物理现实，而这两者并不完全相同。像约翰
·
洛克这样的哲学家就这个问题写了大量的文章，在19世纪，关于心灵本质的哲学思考成为科学严谨性的主题。

心理(感官体验)和物质(外部现实)之间的关系问题是由包括 Ernst Weber 和
Gustav Fechner
在内的一些德国研究人员研究的。他们的工作被称为心理物理学，它介绍测量物理刺激和人类感知之间关系的方法，这些方法将成为心理学这门新科学的基础。

现代心理学的正式发展通常归功于德国医生、生理学家和哲学家威廉 ·
冯特。Wundt
提倡心理学可以作为一个实验领域，通过提供班级、教科书和实验室来训练学生，以此他帮助建立了实验心理学。1875
年他加入莱比锡大学，之后他就快速开始制定实验心理学的教学计划。1879
年，他完成了一次讲座------讲座以实验的方式进行，这被视为心理学的里程碑事件。

对这项新科学的反应是迅速的和全球性的。世界各地的人都来到 Wundt
身边和他学习实验心理学。学生被要求提供详细的自我报告，关于他们对各种刺激的反应，其中一个步骤被称为“反省（introspection）”。这样做的目的是识别其中的意识部分。除了对感觉和知觉的研究之外，还对心理测时法进行了研究，通常被称为反应时间。冯特和他的学生的工作表明，心灵可以被测量，意识的本质可以通过科学手段被揭示。这是一个令人兴奋的提议，之后在美国引起了极大的兴趣。在
1879
年冯特的实验室开放之后，仅仅用了四年时间，美国就开设了第一个心理学实验室。

** Scientific Psychology Comes to the United States

Wundt 的心理学贡献由他的学生 Edward Bradford Titchener
引入美国。Titchener
将引入美国的心理学称为结构主义。结构主义者对心灵的内容感兴趣------即心灵是什么。对
Titchener
来说，一般成年人是新心理学关注的焦点，他排除了有智力缺陷的人、儿童和动物。

实验心理学在北美传播得十分迅猛。到 1990 年，美国和加拿大已有超过 40
所实验室。随着 1892
年美国心理学协会(APA)的成立，美国的心理学也开始组织起来。Titchener
认为这个新组织没有充分代表实验心理学的利益，所以，在 1904
年，他组织了一群同事创建了现在被称为实验心理学家协会。该小组每年开会讨论实验心理学的研究。由于时代的原因，女性研究人员没有受到邀请(或欢迎)。值得注意的是，蒂钦纳的第一个教授的博士生是一个女人，玛格丽特
· 弗洛伊 · 沃什伯恩(1871-1939)。尽管障碍重重，1894
年，沃什伯恩成为美国第一位获得心理学博士学位的女性，并在 1921
年成为第二位当选美国心理学协会主席的女性(Scarborough & Furumoto，1987)。

在心理学的科学和实践之间取得平衡一直持续到今天。1988
年，美国心理学会(现在称为心理科学协会)成立，其中心任务是推进心理科学的发展。

** Toward a Functional Psychology

尽管 Titchener
和他的追随者坚持研究结构心理学，美国的其他人却在追求不同的道路。William
James、G. Stanley Hall 和 James McKeen Cattell
三人成为“功能主义”的宣扬者。受达尔文进化论的影响，功能主义关注大脑活动------即大脑能做什么。对功能主义的兴趣为研究包括动物和比较心理学在内的各种方法开辟了道路。

William James 的《Principles of
Psychology》一书，被认为是心理学界最有影响力和最重要的一本书，该书出版于
1890 年。
