#+TITLE: 参加26年香港马拉松
#+DATE: <2026-01-18 Sun 22:03>
#+TAGS[]: 随笔

我报名了半程马拉松，用时2小时16分钟49秒。

* 马拉松

刚报名马拉松的那段时间，我确实想训练，早晨时不时去附近的公园跑步。但是随着时间的推移，心里渐渐不再对这件事关注，跑步也就变成了偶尔一次。直到最近，我才临时抱佛脚似的跑上一次长距离——只有7公里。

我的号码是D7189，被分在了半马一组。马拉松起跑时间是七点四十五，我六点半起床，下楼在麦当劳吃早餐。吃完，就在街边等待着进入起跑区。街上都是人，人们穿着不同式样的运动装，做着热身。我显得有些另类——下身休闲长裤，上身是发的全绿T恤。我后来看了马拉松的相册，没见到和我一样穿休闲裤来跑的:)。

七点四十五的时候，人群开始移动，我按下了手表的计时。当看到“起点”这两个大字时，我才明白刚才的位置不是起点。但手表已经计时大概四分钟了，没有重新计时，就那样开始跑了。

刚跑的时候还不太适应，当我觉得有点累，进而看到路上的标记点时，意外发现只跑到3公里。嗯，就继续跑吧。跑到9公里时，腰侧开始有些异样，这是肌肉还不适应长距离跑步，我继续跑，这种不适感就消失了。10公里到15公里中间有一段是海底隧道，这段不好跑，闷热的环境、空气也比外面少。身处在这种环境，人很容易越跑越兴奋、越跑越快。当我越来越兴奋时，突然我跑不动了。只能慢慢放慢脚步，匀速前进。港马的路线地形很全面：上坡、下坡、斜坡和隧道一应俱全，可以说：港马能跑下来，平地上举办的马拉松确实是很轻松的。

当路标提示我已经跑完了18公里时，我意识到接下来的3公里多是很难熬的。前面的路我除了在补给点喝水时停下来，其他时刻都是在跑着。只是一味地坚持，不停地跑。心里不断在想：怎么终点还没到？当我跑到终点时，没有特别激动，好像有些过于平淡了。拍下来自己的样子，用来和跑步前对比。脸色稍微难看了些、嘴唇也比较干燥，但整体状态还好。

当我在跑步时，我在想什么：

1. 跟着别人跑也挺好
2. 别停下来，别和别人比
3. 嗯，风景不错
4. 人群的呐喊声好吵啊


住酒店的好处就是跑完之后能洗澡。我的裤子腰部和膝盖部位都是白色结晶，查了资料说是汗液水分蒸发后就是白色的。收拾一下行李，就坐高铁回深圳了。

到家后痛苦就开始了，身体并不适应突然增加的运动量，导致我的肌肉堆积了很多乳酸。表现就是：肌肉酸痛。走路时都是一瘸一瘸的。上下楼也不好受，上楼还好，下楼就很痛苦，只能一步一个台阶下，下得快了，担心会摔倒。

* 其他

一、美丽的女士

在维多利亚公园回酒店的地铁上，看到了身着黑色裙子、有气质的女士，很喜欢。好看得让我自惭形秽。她只是静静地望着地铁窗外。我看了她一眼，没看够又看了一眼。她在想什么呢？有些时候，能够遇见这样美丽的女人，其实是很好的事情呀。

二、我对他人痛苦的感受力下降了吗，还是拒绝感受呢

坐地铁回家时，发生了一件事：

一个姑娘蹲在车厢，一开始我没在意，直到她站起来然后突然跪下脑袋撞到地上。那声音大得吓我一跳，我以为她是不是精神不太正常。再然后，周围的人发现了异常，一个小哥主动上前把她扶起，有人给她让座，我才看到：她的脸色很差，整个人没什么精神。之后，那个小哥和她说话、喂她喝水，并扶她下了地铁。

如果，我能早点注意到她的情况的话，或许她可以减少一些痛苦呢？只是我没有注意到。

为什么呢？

自己一个人生活太久了，不知道怎么和他人相处。很多时候一直用一种纯理性的方式去规划自己的生活，从来不去考虑自己可能和他人有什么交集。我希望这种孤僻的生活状态，可以改变一些，自己不必把别人挡在自己的心门之外。并不是你遇到的每个人都是想伤害你的人。
