#+TITLE: 买什么药
#+DATE: <2022-12-15 Thu 14:07>
#+TAGS[]: 备忘

注意，以下信息仅供参考，真假不知。

- 解热镇痛药

常备用药：对乙酰氨基酚、布洛芬。

*用药注意：* ① 有消化道疾病的首选对乙酰氨基酚，但蚕豆病患者禁用；② 有慢性肝病的首选布洛芬，但孕妇禁用；③  *儿童最好选用滴剂或混悬剂* ，便于服用；④ 注意不要超过最大剂量。

- 普通感冒药

常备用药：①西药：酚麻美敏片（泰诺）、复方盐酸伪麻黄碱缓释胶囊（新康泰克）、美敏伪麻溶液（惠菲宁）等。②中成药：感冒灵颗粒（999）、芙朴感冒颗粒等。

用药注意：感冒药一般为复方制剂，西药主要有以下几个成分：① 金刚烷胺，早期用于抗甲型流感，现在已经不推荐儿童使用了，1岁以内禁止使用；② 右美沙芬，具有中枢镇咳作用，4岁以内儿童一般来说不推荐使用中枢镇咳制剂；③ 抗过敏成分马来酸氯苯那敏（扑尔敏）、减轻鼻粘膜充血成分伪麻黄碱，主要用于缓解鼻塞症状，不建议6岁以内的儿童使用；④对乙酰氨基酚，上面已经提到这是一种退热药。大部分复方感冒制剂都含有对乙酰氨基酚。这里就需要大家注意了，很多人会在吃了它的同时还吃退热的药，这就相当于重复用药，很有可能药量过大，引起副作用。

另外，中成药与西药联合应用时应当注意是否含有相同成分，避免重复用药，如感冒灵颗粒中也含有对乙酰氨基酚。

- 抗病毒药物

常备用药：① 西药：阿比多尔片、奥司他韦胶囊（颗粒）等；② 中成药：小柴胡颗粒、清开灵颗粒、连花清瘟颗粒等。

用药注意：这类药一般建议在医师指导下使用。阿比多尔片是广谱抗病毒药，奥司他韦主要针对甲流、乙流。还可以使用抗病毒中成药，一般在发热、咽痛黄浓痰等热像明显的时候使用；连花清瘟颗粒现在比较流行，但推荐发热患者使用，脾胃虚弱的患者容易造成腹泻。

- 止咳祛痰药

常备用药：① 止咳药：复方甘草口服溶液、强力枇杷露、复方甲氧那明胶囊等；②化痰药：氨溴索口服溶液、乙酰半胱氨酸颗粒等。

*用药注意：* ① 复方甘草合剂、强力枇杷露等止咳药含有易成瘾成分，不宜长期使用；② 服用复方甲氧那明胶囊有时引起困倦，不要驾驶或操作机械。

- 腹泻药

常备用药：蒙脱石散、黄连素片、口服补盐液等

*用药注意：* 如果腹泻次数很多，并且伴有发热、脓血便这些情况，乃至出现无尿、少尿这些症状，一定要立刻就医。如果只是普通的腹泻，为避免脱水，可补充水分和电解质，如口服补液盐Ⅲ。另外一些粘附性的止泻药也是可以使用的，例如蒙脱石散。

-----

1. 药品摆放应当遵循成人与儿童药物分开；内服与外用药物分开；西药与中成药分开原则；
2. 保留药品说明书，避免错服；
3. 严格按照说明书要求存放药品；
4. 定期检查药品效期，及时淘汰过期药品；
5. 若有疑问，我院（浙江杭州新华医院）药剂科第一党支部开通药学服务热线，可来电咨询（0571-85267209，工作时间8：00-18：00）

-----

参考资料：

- [[https://mp.weixin.qq.com/s/4hi1xynm-Fhgn_vlQB9ZcQ][拒绝过度囤药！收好这个电话更重要，新华药师教你合理用药]]
