#+TITLE: Kevin Kelly
#+DATE: <2022-11-13 Sun 15:05>
#+TAGS[]: 他山之石

** 68 Bits of Unsolicited Advice

[[https://kk.org/thetechnium/68-bits-of-unsolicited-advice/]]

昨天刚写过，不喜欢听从别人建议。今天就阅读 kk 给的建议。

#+BEGIN_QUOTE
  1.学会从那些你不同意的人身上学习，甚至那些冒犯过你的人。看看你能否从他们的信仰中找到真理。

  Learn how to learn from those you disagree with, or even offend you.
  See if you can find the truth in what they believe.
#+END_QUOTE

这种品质不容易做到。当看到一个不喜欢的人时，第一时间想到的是对方令自己不舒服的点，就顾不上观察到对方那些值得自己学习的地方。而这恰恰是我要努力克服的地方。

#+BEGIN_QUOTE
  2.保持热情等价于 25 分IQ。

  Being enthusiatic is worth 25 IQ points.
#+END_QUOTE

昨天刚写了一首诗，问自己的热情都去哪了。

#+BEGIN_QUOTE
  3.总为自己要做的事情设一个截止日期。最后期限能够降低不重要和一般的事项的优先级。它阻止你把它变得完美，所以你不得不让它有所不同。不同是更好的。

  Always demand a deadline. A deadline weeds out the extraneous and the
  ordinary. It prevents you from trying to make it perfect, so you have
  to make it different. Different is better.
#+END_QUOTE

从 21 年开始，我不再设置
deadline，也就没有了要完成事项的紧迫感。我度过了一段缓慢时光。或许是时候重启
deadline 了，让自己更专注和高效。

#+BEGIN_QUOTE
  4.不要害怕蠢问题，因为别人在 99%
  的时间里都在想着同样的问题，却因为为难而没有发问。

  Don't be afraid to ask a question that may sound stupid because 99% of
  the time everyone else is thinking of the same question and is too
  embarrassed to ask it.
#+END_QUOTE

我从不问蠢问题，因为我从不问问题。因为我觉得没什么好问的，答案自己能够找到。

#+BEGIN_QUOTE
  5.善于倾听是一种超能力。当听某人说话时，你可以不断问他们：“还有更多吗？”，直到真的没有了。

  Being able to listen well is a superpower. While listening to someone
  you love keep asking them "Is there more?", until there is no more.
#+END_QUOTE

我还蛮善于倾听的，听别人说话时都会很有耐心；时不时会问接下来的发展。

#+BEGIN_QUOTE
  6.一个有意义的年度目标：学习大量某个领域的领域的知识；以至于感叹一年前的自己是多么无知。

  A worthy goal for a year is to learn enough about a subject so that
  you can't believe how ignorant you were a year earlier.
#+END_QUOTE

期待年底总结的时候看到自己的进步。

#+BEGIN_QUOTE
  7.感谢可以激发其他美德，让你变得更好。

  Gratitude will unlock all other virtues and is something you can get
  better at.
#+END_QUOTE

学习如何感谢别人的帮助，在自己的能力范围内帮助别人。

#+BEGIN_QUOTE
  8.没有人会拒绝被请吃饭，这（请人吃饭）很容易做到。容易和老朋友沟通感情，也利于结交新朋友。

  Treating a person to a meal never fails, and is so easy to do. It's
  powerful with old friends and a great way to make new friends.
#+END_QUOTE

我不会请人吃饭，这应该不难。

#+BEGIN_QUOTE
  9.没有百试百灵的办法。

  Don't trust all-purpose glue.
#+END_QUOTE

具体问题总在变换，前人的经验无法照搬，要学会变通。

#+BEGIN_QUOTE
  10.经常为你的孩子读一些内容，不仅能让你们关系融洽，还能激发他们的想象力。

  Reading to your children regularly will bond you together and
  kickstart their imaginations.
#+END_QUOTE

阅读活动让亲子关系变得融洽。
