#+TITLE: Kishi Bashi-I Am The Antichrist To You
#+DATE: <2022-06-15>
#+TAGS[]: 音乐

/Rick and Morty/ 第五季第三集片尾曲

Who are you? Who am I to you?

I am the antichrist to you

Fallen from the sky with grace

Into your arms race

{{< br >}}

Lucid lovers me and you

A deal of matchless value

I was always quick to admit defeat

Empty statements of bones and meat

{{< br >}}

And my heart, it shook with fear

I′m a coward behind a shield and spear

Take this sword and throw it far

Let it shine under the morning star

{{< br >}}

Who are you? Who am I to you?

I am the antichrist to you

Fallen from the sky with grace

Into your arms race

{{< br >}}

One for my heart and two for show

Three tears for all the souls below

One day we turned them into figurinees

Burned them all with all my favorite things

{{< br >}}

Who are you? Who am I to you?

I am the antichrist to you

Fallen from the sky with grace

Into your arms race

{{< br >}}

Who are you? Who am I to you?

I am the antichrist to you

Fallen from the sky with grace

Into your arms

Into your arms

Into your arms
