#+TITLE: 人生危机
#+DATE: <2025-09-10 Wed 07:11>
#+TAGS[]: 随笔

早晨了六点醒来，在新的信用卡周期，买了一些做饭用的、穿的、喝的。上周开始渐渐意识到：自己不能再继续做目前的工作了，这份工作已经不能让我成长了，有的只是无聊中带着疲惫。我需要换一份工作。

选择什么工作呢？这让我茫然，我突然意识到自己以前都是在随波逐流，虽然也曾问过自己到底想做什么，可是也没有深入下去。只是追逐着社会流行他人说法，一开始想做网站开发，因为它简单易学，但也正因为这点所以被AI轻易取代。现在的工作是做硬件产品测试，想要做硬件开发的心蠢蠢欲动。

我究竟想做什么？

最近在读《续窗边的小豆豆》，这是既《窗边的小豆豆》出版以来，黑柳彻子女士时隔多年的新作。这本书讲了小豆豆逃离被轰炸的东京之后的故事。其中有两处让我感触很深：

一处是小豆豆在参加NHK演员招聘考试的时候，有道考试题是：请写出你的优点和缺点。她写自己的优点是率真和亲切，缺点最后写了：

#+BEGIN_QUOTE
也许是因为天性乐观，我十分健忘。母亲有时会问我：‘我想听听你的想法。刚才你说自己失败了，哇哇大哭了好一阵子，可是现在又哈哈大笑，咔吧咔吧地吃着脆煎饼。刚才哭过的事，就一点儿影子也没留下吗？’我仔细一想，发现自己已经彻底忘了之前的事。反省和烦恼都会立刻忘掉，我想这应该也算是缺点。
#+END_QUOTE

她很坦诚地面对自己的缺点。我是否也和她一样足够勇敢，去面对自己的缺点呢？

另一处是，小豆豆在寻找自己喜欢做的工作时，最终想当给孩子讲绘本故事的妈妈，但实际行动时却与想象中的是截然不同的：去做了演员。我想到：在找自己喜欢做的事时，并不是一次就结束的。可能经过了几个工作，最终才确定自己喜欢哪个，多尝试总没错。在寻找的过程中一定要按耐住性子，静静地体会工作中的乐趣所在，观察自己更喜欢哪类工作以及思考为什么这类工作吸引自己。

不知道从哪里听来的话：For the first 30 years of your life, you make your habits. For the last 30 years of your life, your habits make you. 30岁以前养成好习惯，30岁以后好习惯养成自己。我今年25岁，未来这5年我会进步成什么样，我很是期待。

另外一句话：You either learn your way towards writing your own script in life, or you unwittingly become an actor in someone else’s script. 自己人生的剧本只能由自己书写，这样自己才是主角；如果生活在别人的剧本里，那一辈子也只是个配角而已。

如果过于遵从社会风俗要求，没有自己的意志，很难找回自我。面对问题时才会觉得无从下手，要敢于跳出约定俗成的框架去思考。

近来我愈来愈有种直觉：如果我不改变目前的轨迹，未来的人生会出现重大危机。下一步做什么？找到一份硬件工程师工作。
