#+TITLE: 恋人絮语
#+DATE: <1999-04-30 Fri 09:05>
#+TAGS[]: 随笔

文章真实的新建日期：<2023-06-07 Wed>

提醒自己：

你的记忆不一定准确，很多她的做法你会以自己的想法让它合理化。所以，如果下面的记述和事实有偏差也不要担心，请你记住：你要记录的是两个人之间发生的美好。

如果描述中若无法分辨，就用X指代她。

2023年6月6日：

今天晚上想约她出来，问她有没有空。她说：好啊。问她几点合适、从小区的哪个门出来。说好后，我打算晚上快八点的时候去她小区门口等她。

下午回老家干活——把晒好的麦子放起来。等到我正往县城赶时，她发消息说：吃饭比较晚，要不然改天吧。我当时很失望，觉得自己见不到她了。只好回复“好吧”。想着自己过两天就要去工作了，想见面不那么容易。她回：都在一个地方，时间还长，见面很容易。我回：你什么时候有空，跟我说一声。

在回县城的路上，我思绪万千：怀疑是自己太着急，吓到她了，还是有些举动（把手搭在她的肩膀上）过于亲密了。转念一想，如果我不信任她，我们接下来还要往何处发展呢？这样想着，我决定自己去她小区看看，我数了：我家到她家一路上要经过八个红绿灯。这就是我和她的距离。在这过程中，我平复自己的心绪，让自己耐心一些，不要着急，慢慢地了解她。

八点多问了她，平时喜欢听什么歌。一个小时后，她回复：流行音乐或轻音乐。我说到想关注你的网易云音乐，她说第一次有人问她要这个账号，我回：想看看你都喜欢听什么歌嘛3。我说自己听过的歌比较杂，分成听得懂和听不懂的，听不懂的话听旋律。

互关网易云音乐后，我发现一个“一起听”的功能，发给她，她说自己在打电话。问她有没有被打断，她说没有。问她要不要一起听歌，她说还在打电话。我说：那我等等。我去洗澡了，22:23她问：你想啥歌，二十分钟后我看到这条消息，给她网易云发了一起听歌的邀请。

听了痛仰乐队的《两个人的假期》、钟立风的《爱情万岁》，还有她选择的Skeeter Davis的 /The end of the world/ 。问她感觉如何，她说有点那感觉，说不出来。我想是恋爱的感觉吗？我没有问。

快十一点了，她问我该睡觉了吧，她在刷科目四的题目。我回：确实该睡了，下午回家把晒好的麦子装起来，挺累的。她让我赶紧休息。想到之前她似乎提过自己一点多睡觉，问她：都是一点多才睡吗？她回：十一二点吧。我说：晚安。她回：晚安。

2023年6月5日：

这天上午就考科三了。走到待考大厅，刷身份证进去找座位坐下，我坐在她旁边，跟她说话，想让她放轻松。互相记忆着三条考试路线。提醒遗漏的点。在考试以前，还要从待考大厅进到一个稍小些的房间。这个过程是喊名字，喊到我的时候，我右手放在她肩膀上，轻拍了两下，让她放松一些。

在小房间里，我和她坐在一起，回顾路线图。听到喊她的名字，看她离开去考试。我在待考大厅的屏幕上看她上了哪辆车，发到群里，让教练帮忙关注着。

我们五个人考试，都考过了。她的路线是二号，我是三号。我和她一样，考了两次才考过。

下午在家里，我问她晚上几点吃饭，想约她在她家附近的地方走走。

2023年6月4日：

这一天依旧是在考试场地练习科目三，到晚上吃饭的时间，我们一行7人去了一家饭馆吃饭。在去的路上，外面还在下雨，我给她打伞。不时会碰到她的头发，想着她应该感觉到了（头发是敏感部位吧）。在过十字路口时，问她冷不冷，她说冷。有点懊悔没有穿着长袖褂，这样就可以给她穿了。同行的一个女生说：你问她有什么用？言下之意，就是她说自己冷，你也不是没做什么吗？我不这样想，即使没有行动，这样的话语在我看来也是有力量的，能表达我对她的关心。

吃饭的时候，我自然是拘谨的。因为是和不熟悉的人吃饭，担心自己流鼻涕（我一吃辣的就流鼻涕，老毛病了）被他们看见。吃饭的时候，大家讨论饭菜的咸淡，知道她口味偏淡，我也不喜欢吃太咸的。在回宾馆的路上，她说到自己不喜欢饭后刷碗，我也不喜欢。我还知道她喜欢喝奶茶，不能吃酸。

临睡前，说要买奶茶喝。她问我：只有冰的，要不要换常温的。我想到晚上不该吃凉的，容易肚子疼。我跟她说：晚上吃冰的，容易肚子疼。建议你买个常温的，给你自己。她换成了常温的。

2023年6月3日：

这一天我们去考试场地练习科目三。上午在练习靠近三号线起点的路段时，她谈到自己想谈恋爱。我当时没太在意。晚上七点多，练车返程时。一起练车的其他两个女生就开始聊到这件事，聊着聊着，她说自己遇不到合适的，之前母亲安排的相亲，最后也是不了了之。大学的时候没谈过恋爱。

之后那两个女生中的一个，就问我：是否谈过恋爱之类的话，我说自己没谈过，表白被拒了。之后，她就说：那你们两个挺合适，X是99年的，我是00年的。我当时觉得不好意思，想着能只靠着这些就能判断两个人是否相处吗？事实上，一定是不可能的。但是，那个女生的一番话让我设想到这样一种可能——我和X慢慢地认识了解，等到一定程度，就发现自己已经离不开她了。我无法停止这种美好的幻想。

如果我不主动、不放弃那些胆怯的想法，我的意中人何处寻得？

晚上到家后，以车上尴尬的聊天为契机，我向她袒露自己的想法：我们现在还不太了解彼此，可以先以朋友的关系熟悉彼此，待到有一天发现自己和对方在一起有那种处于恋爱中的心扑通扑通跳的感觉，我们就告诉对方，这样就明确自己对彼此的感觉了。她同意了。

2023年5月18日以前的某一天：

第一次加她微信是什么时候不记得了，只知道是在驾校科目二的训练场地。所以这篇文章的日期，选在了训练的某一天。当时，选择加她微信是觉得：哇，这个人蛮有趣的，说话风格呀什么的，彼此简单地聊一聊最近的生活打算。就这样结束了，加了她微信后，我就把她从消息列表删除了，当时觉得短期内不太能有什么交集。
