#+TITLE: 五一回忆——永远记得抬头看天上的星星
#+DATE: <2026-05-03 Sun 15:56>
#+TAGS[]: 随笔
#+LOCATION: 杭州 Hangzhou

* 深圳飞杭州

四月二十九日晚我启程回家，背了一个旧书包，不知道用了几年，只知道这次回来差点把它的拎手扯断。包里装着换下还没洗的衣服，还有一套换洗衣服（短袖、短裤、内裤和袜子），外加一条短裤、长裤和一个剃须刀。除此之外，还背了一个斜挎小包，里面装着墨水屏阅读器、3C充电宝、深圳家的钥匙。

晚上没加班，八点多快九点吃完饭收拾下衣物就出发了。计划从福凤路南坐公交到地铁站，但我在那里等了大概十几分钟，直到我用导航app才发现：已经没有我想坐的那班车了。不禁埋怨自己为什么不早点看导航。只能打车了，还好只花十一块。从地铁站坐到宝安机场T3航站楼，我是第一次来到这个地方，难免有些紧张。询问工作人员后才知道如何取机票。机场是个复杂的地方，各种金钱阶层的人汇聚在一起，这让我有些不自在，但是我已经见过几次这种场合了，待得时间久些也就不在意了。安检让我很没安全感且不被信任——我上次被人如此侵犯隐私是在什么时候？

候机时的等待是难熬的，我的航班晚点了。本来晚上十一点起飞，硬生生拖到凌晨十二点多才起飞。一开始我还有精神看会儿书，后面虽然疲惫但就是睡不着。担心睡着会错过航班，因为我只有一个人，没人会想着提醒我。哈欠一个接一个，总也止不住。

登机后，找到座位，坐下。读了前面布袋里的安全提醒。望着窗外发呆，远处的登机通道写着“AI就用阿里云”，嗯，好的，我不用。本来对面前的屏幕没什么兴趣，邻座的女人打开了一个航班导航的东西，我觉得挺有趣，也开始摆弄起来。

飞机起飞了，刚飞时的两次下坠让我有点慌，后面飞机慢慢上升，机身调整姿势。看着地面上的庞然大物变成一个个明亮的点，我想：这是我第二次离大地那么遥远。飞机慢慢穿过云层，上升到适合巡航的高度。某一瞬间我看到飞机海拔8871m，这已经很高了，比珠穆朗玛峰都高。坐飞机还是会头晕，不舒服。飞机上一直会有一个声音嘀嘀地叫，让我很烦。感受到飞机的颠簸，我并不害怕。内心有一种平静感，似乎是知道自己不会死掉，即使死掉不是还有赔偿吗:)

* 杭州的冷出人意料

飞机抵达杭州萧山机场是凌晨两点四十，一走出舱门，来到廊桥，我就后悔了：怎么没带长袖褂子呢？看着别人把自己上下裹得严实，我像个傻子一样完全是深圳装扮。走到机场一处供人睡觉的座位处，看到人们一人占两个座位那样蜷缩着睡，要多难受有多难受。包里还有条长裤子，扫视了周围，人们都在睡觉，没有人注意我。我拿出长裤直接套在我的短裤外面，终于感到一丝温暖了。我既冷又困，也有样学样，把自己缩成一个球，蜷在座位上。可是怎么也睡不踏实，就这样我迷迷糊糊地混到了五点多。

然后，走出机场来到马路上，从机场走出来到地铁站入口，顶多一百米。我走起来却感觉有一公里那么远，全身的骨骼肌都在战栗想要为我提供热量，但还是入不敷出。边走边找吃的，终于找到一家卖馄饨的，一看价格四十九，就一碗馄饨加一个鸡腿，这也太他妈贵了！一想到不断颤抖的身体，贵也要吃，总比冻死强。

我从萧山地铁站坐到凤起路，这时是七点十分，想去西湖转转。[[/posts/where-have-been-when-delivering/][22年我送卖时]]，有时会经过这里，但从来没有进去看过。我沿着湖顺时针走，很多人在这里：或是散步、或是跑步、或是跳舞、或是舞棍。我就走着，不紧不慢地走，看着遥远的苏堤像一条波浪线把我眼前的风景隔成上下两半。早晨的阳光照耀在身上，但是并不给人温暖。

我继续走，走到一处湖边的木椅，我坐下休息。看着湖面，看着湖面上的游船，思绪开始四散而去。离开木椅，我继续走了段距离。不知什么原因就有了离开的想法，开始看导航怎么去西湖文化广场。哦，要从定安路坐地铁。我就走啊走，一路上碰到很多卖旗袍丝绸织物的店，看起来很漂亮、精致，价格肯定不便宜。我路过一家店，本来都走过去了，脑子里突然闪现一个念头：要不给妈妈买份礼物吧。我折返去问店家方巾怎么卖。有很多价位，我选了一款花纹好看且性价比高的。到家后妈妈收到礼物时很开心。

当我到西湖文化广场时，太阳开始发热了，终于让我感到了温度。在广场上转悠，在林荫下休息时依然能感受到凉意。后面走到运河，被老人们吹奏萨克斯的声音吸引。那嘹亮清脆的声音，让我驻足倾听。如果不是该死的工作打扰，我说不定能更加投入呢！四五月的杭州，运河旁的树开着花，树下老人在深情地演奏一首情歌，他在吹给谁听？

我走到密渡桥路想要寻找当年吃过的快餐店，可惜已经找不到了。但是，宋太阳面包店还在，沙县小吃店还在。时间会让能够存在的事物继续存在下去。

* 回家、回老家

坐高铁回家了，进门时看到父母的那一刻，觉得陌生而自然。我已经一年多没有踏进这个家门了。像阔别的老友，很自然地我就融入其中了。五一回老家村子里，见到了九十多岁的爷爷，他的耳朵已经有些听不见了，和他说话要大点声才行。我看着一眼望不到头的麦田，感受到很多新鲜的、令我好奇的地方。

我拍了一些照片：一束麦穗竖着立在那里像没开屏的孔雀；蜜蜂纤细的足握住麦芒；一处野花丛中蜜蜂辛苦地传粉；父亲骑着自己改装的带篷电动三轮车在转弯；通过一定视角拍出的无尽的麦田；刚浇完水的鲜嫩欲滴的辣椒苗；小小的像豆苗一样的黄瓜苗；一处不起眼的四叶花、一瓣白色三瓣渐变蓝色；院落里的柿子树；爷爷灶屋旁的大树；纹路分明的茴香；大树和屋舍构成的和谐图景；手掌中的一个蚕豆荚。

拍了很多照片，让我重新发现了农村的美。

* 见初中同学李

我和他每年都会见上一面，吃饭聊近况。今年年初过年时没回家，还好这次五一补上了。我们约好在高中校园（我俩高中也在同一个学校虽然不同班级）门口见面。我们边走边聊，聊自己对未来的打算、聊关于当前AI技术的应用、聊家庭琐事、聊自己最近读了什么、聊自己有哪些成长。生活在不断地裹挟着我们向前，我们能做的就是以自己最积极的一面去面对。只有这样，我们才能够说：我的生活过得足够充实、足够精彩。

* 去体育场跑步

一号和三号都去县城家附近的体育场跑步了，一号只跑了两公里便停了下来，膝盖有些酸了。三号也就是今天跑的时候，跑了三次，总共二点六公里。其中有慢跑也有为了探索自己的极限而跑，也有为了体验什么叫“强风吹拂”。风掠过耳边，那哗哗的响声，全力向前冲刺的快感，让我着迷。

当我跑的时候，风沿着我的身体流动。跑动的刹那，一切仿佛都停止了，只有一个目标，那就是不断向前。

* 永远记得抬头看天上的星星

一号晚上看天，天上还没有星星，明天就要走了，今天能看到漫天星星，这是一件令人开心的事。

还记得更年轻的时候，我能一口气全力跑完四百米都不用停，甚至还有余力继续跑。现在我只能跑三分之二，身体不如从前了。随着年龄的增加，要处理的事情越来越多，对身体健康的关注不如从前了。这样持续下去并不好，长期下来，身体会越来越迟钝，精神也会变得麻木，无法感受到生活的美好。这种恶化对我来说是噩梦一样的事情。

跑完步去买点小吃，买了面筋、两个煎饼，吃的时候我站在离路边有段距离的地方，看到有三个人骑着三轮车，打算在路边卖小吃。两女一男，看起来蛮年轻的，不禁好奇，就一直在关注。有一对情侣来买东西，我留意到他们买东西的神情，应该是快乐的。突然就联想到：要抓住女人的心，抓住女人的胃是一个不错的方式。以后要锻炼自己的厨艺了。进而又在想：两个人的浪漫究竟是什么样的状态？
