#+TITLE: 确定性的忧伤
#+DATE: <2026-07-24 Fri 07:23>
#+TAGS[]: 随笔

#+BEGIN_QUOTE
And God said, Let there be light: and there was light.
神说："要有光"，就有了光。
——圣经·创世记
#+END_QUOTE

早晨上班时，我见过无数次自然——起床后来到阳台看到鸟儿从低处滑翔、远处的林叶在晨光的照射下显得湿润晶莹、下楼抬头看向天空云彩镶着金边像一件首饰佩戴在天空的身上。

可是，这些景色在一天之后都会不见，今年的第十二号台风"红霞"将登陆广东，未来一周时间我所在的深圳都将是阴雨绵绵。这不，快到周末了，雨天睡懒觉想来是惬意无比呐。

天气是人类最难以控制的自然景观之一。人只能去有限地影响它，却不能随心所欲地控制它。幸好不能，否则从历史来看，人在能够控制天气后，会给自己带来怎样的灾难还未可知。这就是所谓的不确定性。未来的天气人能够预测，但是却很难干涉。预测是一种概率性统计的手段，这意味着预测并不精准。天气预报也可能是错误的。

人类的发展历史，就是从不确定性越来越高不断趋向确定性越来越高的过程。但是，即使在二十一世纪的当下，不确定性的事件还会发生。新冠疫情就是一个典型例证。

2019年底，疫情初次在武汉爆发。2020年初，彼时的我[[/posts/first-time-in-beijing/][在北京]]，想找份临时工作挣些钱。到北京那天是1月11日，而我现在搜到的北京初次出现新冠病例的时间是1月19日。你看，意外来的是那么突然。我没有找到工作，我第二天就坐着绿皮火车回家了，由此开启了我长达八个月的居家生活。

疫情从开始到结束，我们每个人都深度参与，生活都受到极大程度的影响，人生轨迹都被改变。像这种事件，我们作为个体，想怎么办、能怎么办呢？是不是会感到一种深深的无力感？不能够左右自己的命运太悲哀了，不是吗？

我经常会有改变自己的想法，也会做一些事情，但是往往无法坚持。无法坚持的理由很简单，我没办法维持平稳的心态去面对生活中的一切事情。当我心情低落时，一切都不想做，自然也坚持不下去。我发现这样反而是一种解脱，不再强迫自己坚持，有些时候往往能带来意想不到的发现。当我处于放松的状态时，更容易听到自己内心的声音。

当面对这些无法改变的客观发生的事情，该怎么做呢？是逆来顺受，还是一副冷面孔仿佛事情和自己无关但实际却是息息相关。

人最擅长的事情是自欺，从一开始被迫自欺到最后习惯自欺。当一件事无法按计划完成时，总会在最后寻找理由为自己开脱。没有完成事情不是别人的错，而是自己的错，因为自己是生活的主人。如果自己都无法安排好自己的今天，谈何为自己安排未来呢？还有未来可言吗？

人类渴望确定性，因为确定性能带来安全感，而人的一生最重要的课题之一就是寻求自己做事的安全感。做一件事时是快乐的、享受的、平和的。

聪明的你，知道怎样找到让自己舒服地做事的状态吗？
