#+TITLE: 备忘
#+DATE: <2022-11-14 Mon 08:59>
#+TAGS[]: 备忘

-  出行必备物品
  - 笔记本
  - 身份证件
  - 手机
  - 日用品
-  跑步的时候绝不能穿平底鞋
-  我的脚长 240-250mm
-  内裤买 3XL 大小的
-  买 CPU 要买 Intel 的，和 AMD 相比更可靠（来自关鹏老师的观点）
-  电子书打印成纸质书，可以通过淘宝的专业打印服务
-  向别人介绍自己时，要告诉别人如何称呼自己
-  洗的衣服，腰的位置还有汗液的味道，需要放洗衣粉
-  鞋子码 41/42
-  短袖 XL
-  短裤
-  家庭电器实用为主，美观为辅(实用的电器，在美观方面做得也不会差)
-  定期备份项目清单
  -  配置文件
  -  要保存的文件
-  保护环境，保护地球
-  买衣服(上衣、裤子)不要买 50 元以下的，质量不好
-  《学点法律避点坑》 书本里面有个专用的 借款合同，比较全面
-  个人信用报告分为简版和详版。通过线上（手机银行 APP、网页）查询得到的报告是简版。通过线下（网点柜台、自助查询机）打印的报告是详版。
-  以后可以参加工作的地方的志愿者组织

** 坐飞机要注意什么

不能携带水

** 转运物品

邮寄东西选择物流公司，不要选择快递

快递贵，论斤；物流，论件

--------------

-  买来的电器功率越低，烧水的速度会很慢
-  别人贷款，别为别人提供信用担保，可能会把贷款转移到我的身上

* 记事
** 20221106 下午到外卖黄龙站点签订了宿舍租赁合同（电子、纸质）

西湖区翠苑街道社区卫生服务中心

办理健康证，需要大约100元

早晨空腹，时间大约在半个小时左右

八点就可以去做

刷牙

1. 早晚两刷，饭后用牙线清理食物残渣

2. 每6个月做一次口腔检查和洗牙，清理牙结石

3. 一定要找专业口腔医生进行假牙修复和正畸治疗，切不可贪图便宜

社保公积金

待业期间，可以办理灵活就业登记，自己交社保。

睡觉之前的最后一顿饭，不要吃很辣的食物。如果吃了睡觉时会感觉到肚子很不舒服。还有，吃辣的东西不要狼吞虎咽，胃同样不适。

除非天很热需要吃凉东西解渴，其他情况下，少吃凉的东西（固态/液态），如果吃了，大多数情况会不舒服。

胳肢窝的话到37.5度，才算发烧

-----

一个不错的 Android 博客软件——[[https://antennapod.org/][AntennaPod]]，代码开源：[[https://github.com/AntennaPod/AntennaPod][GitHub]]。

-----

云服务厂商拒绝阿里云等国内企业 https://twitter.com/xiqingongzi/status/1604375391267098624

-----

飞机票：

周二下午or周三凌晨买最便宜

周五买最贵

下午买便宜，上午买贵

飞行时间一早一晚的便宜，中间白天的贵

春节、寒暑假、五一、十一等旺季提前一个月预定

淡季时提前半个月预定

每年的双十一、双十二大促也可以囤机票，这是什么意思？

机票在哪里买最便宜？首选航空公司官网，很多特价机票只有官网能看到。不定时会有促销。也可以在各个旅游平台进行比价。

国内航空公司的会员日价格低至一折。

#+BEGIN_QUOTE
各航空公司的机票打折日：

- 国航：同月同日（1.1,2.2,3.3等）
- 海南：每月8日
- 东方：每月9日
- 南方：每月28日
- 深圳：每月12日
- 厦门：每月9日
- 四川：每月19日
- 吉祥：每月25日
- 昆明：每月16日
- 九元：每月9日、19日、29日
- 瑞丽：每周二下午6:00
- 西部：每周三上午10:00
- 祥鹏：每周四上午10:30-11:30
- 中国联合：每周五中午12:00
- 春秋：每月27日，每月9日，有1元抢票活动，每月15日有日本线促销
- 亚洲：一周一小促，三个月一大促。一般是2月/3月、5月、8月和11月

各航空公司主要航线城市：

- 春秋：曼谷、大阪、济州岛、普吉岛、台北中
- 中国联合：内蒙古、东营、海南
- 瑞丽：昆明、呼和浩特、沈阳、青岛
- 祥鹏：云南各大城市、曼谷、郑州
- 香港快运：昆明、兰州、清迈、岘港
- 泰国狮航：泰国国内、泰国飞国际
- 乐桃航空：日本国内、香港、台北飞日本
- 马来西亚：国内及周边国家
- 马印航空：马来飞泰国
#+END_QUOTE

关注航空公司公众号。

十人以上可以打电话定团体票。

廉价航空不提供餐食饮料，注意免费行李托运额，注意额外的托运费比机票本身还贵。

如果出发地或目的地太贵，可以看看相邻城市。

机票的价格变动很频繁，抓住时机。

购票前多次刷新网页，因为航空公司的票价随时都可能变动。

一次性买往返比分开购买划算。

每年3、4、9、11月是错峰出游的最佳时间，机票会便宜很多。

国内机票提前1-2个月买，国际机票提前3-5月买。这太离谱。

不要短时间内频繁看某个航班，为什么。

东方航空的机票和登机牌是一起的，同一张纸。可能分航空公司。

机票主要用于报销，登机牌是安检必备。提前两个小时到达机场。

-----

订阅海外服务充值：https://www.nobepay.com/app/home ，一次最少充值500

-----

支付宝-充值中心，一个月话费最多充3次

-----

未来10年只能留在国内的话，怎样做好避险措施（[[https://twitter.com/xiaojingcanxue/status/1635237633894010880][Twitter]]）

-----

酷狗M3 pro挂脖式耳机死机，解决办法：拉开磁吸，长按中间功能键，直到听到开机提示音。

死机表现：充电提示灯不亮；拉开磁吸没有开机提示音。

感谢京东酷狗音乐自营客服。

-----

做独立开发要提前注册相关品类商标

* 键盘

噪音排序：Linear（线性轴 / 类红轴） < Tactile（段落轴 / 类茶轴） < Clicky（响声段落轴 / 类青轴）

想买：罗技 MX Mechanical Mini，719元（<2023-07-29 Sat>）

挑出来的例子：

- 宁芝82/84键，静电容键盘，千元价位

品牌：

- 罗技
- 宁芝
- IQUNIX
- Cherry

闲鱼上买了个达尔优，z键不能用，用油润了之后没有效果，卖我键盘的人说需要一两天才能见效。哦，已经晚了，我已经把键座暴力拆下来了，下次润轴的时候注意吧。第二天，我把键座用502粘回去后，z键又能用了。

参考资料：

- [[https://sspai.com/post/64972][机械键盘自行选购指南：从只买一把到直入深坑 - 少数派]]
- [[https://sspai.com/post/77094][替室友按下静音键，回顾静音轴体的二十年 - 少数派]]
- [[https://zhuanlan.zhihu.com/p/261386664][什么牌子的键盘好用？2023年键盘选购建议和产品推荐。 - 知乎]]

* 防止信息泄漏

- 不要使用免费Wifi，尤其是机场
- 不要在两个手机上装同一个App
- 无线打印机的使用，家庭网络的被入侵可能
- 不要用酒店类空间提供的USB接口连接自己的USB数据线充电

* 买药

开药方式比较

（综合价格、时间成本、应急程度）

1. 医院

- 首次在该医院就诊必须得线下面诊；之后有的医院支持线上开药，不需要再单独跑一趟了
- 一般来说医院开药最便宜，（如果是非线上开药的话）时间成本较高

2. 药店

- 医保定点药店可开医保报销的药，较便宜；可以选择家/公司附近的定点药店，时间成本较低
- 在非定点报销药店去购买药品是最贵的，没有什么折扣，时间成本低，但可应急

3.电商平台（各大药房线上旗舰店、阿里药房等）

- 后置仓，买药略贵，时效性一般，约2—4天左右到货（京东会更快）

4. 外卖点药（美团买药等）

- 时间成本最低、时效性最高，价格处于较贵

#+BEGIN_QUOTE
不要用自己的医保卡给其他人买药，哪怕是亲人，要知道病因，比如高血压，糖尿病，痛风；因为，在买商业医保的时候都会进行查询，会对投保有所影响。

——https://x.com/Cydiar404/status/1710944800227340678?s=20
#+END_QUOTE
