#+TITLE: 备忘
#+DATE: <2022-11-14 Mon 08:59>
#+TAGS[]: 备忘

-  出行必备物品

-  [ ] 笔记本
-  [ ] 身份证件
-  [ ] 手机
-  [ ] 日用品

-  跑步的时候绝不能穿平底鞋
-  我的脚长 240-250mm，穿 40 码的鞋
-  内裤买 3XL 大小的
-  使用图片时要在文末/图片下方添加图片来源，以示尊重和版权
-  买 CPU 要买 Intel 的，和 AMD 相比更可靠（来自关鹏老师的观点）
-  电子书打印成纸质书，可以通过淘宝的专业打印服务
-  重修一门就算大挂
-  洗澡的时候要带必须用品（毛巾、拖鞋等）
-  学校的英文名称：Liaoning Petrochemical University
-  CNNIC 中国网络机构
-  长时间专注后突如其来的刺激的感觉可能是因为大脑短暂缺血所致
-  坚果云中有关专业的内容，永远都不要删除！！！
-  制作一个包含自己信息的二维码
-  向别人介绍自己时，要告诉别人如何称呼自己
-  婚纱避坑指南 [[https://www.jianguoyun.com/p/DeU82_wQzZOlBxjxw_4D]]

我昨天也刚婚拍完，是在珠海的一个海岛上拍的。套路确实多，从你进店的一开始，套路就开始了，后面源源不断。我再补充几个：

1，选婚拍服装的时候工作人员会一直问你什么时候结婚，需要用到婚拍的照片。如果你答很快就要用了，那么工作人员八成会说我们这边出图什么的最快也要一两个月，像你这种时间紧迫的话，需要跟修图师说加急什么的。如果你答应了，那么在修图师加急这部分，就也是要收费了，这是第一个坑。

2，第二个坑，在我老婆试婚纱的时候，工作人员竟然会跟她一起进去换衣服，然后事后会说我老婆胸型怎么怎么样的，然后还说会空杯，于是又开始推荐她们自家的胸贴了......

3，套路三，婚纱店里面还有个男士西装定制的，也会拉住你推销定制西装。如果你不要的话，她会说我们现在是最大的优惠力度，过了今天就没了。所以会劝你要不先支付
100 订金，保留今天优惠的价格力度。然后如果以后不要的话，可以把这 100
退回去。如果你真交了这
100，那以后这钱你是好意思要回来呢，还是不好意思呢？即使好意思要回来，也会被她以其他理由，比如什么还是送你一个价值
200 的高级衬衣这样来搪塞回去的...... 婚纱店的套路很多，真的要小心。

-  一流二流大学，城市分布名单
   [[https://www.jianguoyun.com/p/DZh_3J4QibDaBxixgowE]]
-  洗的衣服，腰的位置还有汗液的味道，需要放洗衣粉
-  鞋子码 41/42
-  短袖 XL
-  短裤
-  家庭电器实用为主，美观为辅(实用的电器，在美观方面做得也不会差)
-  定期备份项目清单
-  配置文件
-  要保存的文件
-  保护环境，保护地球
-  买衣服(上衣、裤子)不要买 50 元以下的，质量不好
-  《学点法律避点坑》 书本里面有个专用的 借款合同，比较全面
-  个人信用报告分为简版和详版。通过线上（手机银行
   APP、网页）查询得到的报告是简版。通过线下（网点柜台、自助查询机）打印的报告是详版。
-  以后可以参加工作的地方的志愿者组织（[[https://articles.zsxq.com/id_8aki0doo6hwu.html][来源]]）

信用卡提额的方法：

1. 信用卡不能刷整数
2. 在同一个时间段只能刷一笔
3. 单次刷卡不能超过总额度的 60%
4. 扫码单笔不能超过 1000

** 坐飞机要注意什么

不能携带水

** 转运物品

邮寄东西选择物流公司，不要选择快递

快递贵，论斤；物流，论件

--------------

-  买来的电器功率越低，烧水的速度会很慢
-  别人贷款，别为别人提供信用担保，可能会把贷款转移到我的身上

* 记事
** 20221106 下午到外卖黄龙站点签订了宿舍租赁合同（电子、纸质）

西湖区翠苑街道社区卫生服务中心

办理健康证，需要大约100元

早晨空腹，时间大约在半个小时左右

八点就可以去做

刷牙

1. 早晚两刷，饭后用牙线清理食物残渣

2. 每6个月做一次口腔检查和洗牙，清理牙结石

3. 一定要找专业口腔医生进行假牙修复和正畸治疗，切不可贪图便宜

社保公积金

待业期间，可以办理灵活就业登记，自己交社保。

睡觉之前的最后一顿饭，不要吃很辣的食物。如果吃了睡觉时会感觉到肚子很不舒服。还有，吃辣的东西不要狼吞虎咽，胃同样不适。

除非天很热需要吃凉东西解渴，其他情况下，少吃凉的东西（固态/液态），如果吃了，大多数情况会不舒服。

胳肢窝的话到37.5度，才算发烧

-----

一个不错的 Android 博客软件——[[https://antennapod.org/][AntennaPod]]，代码开源：[[https://github.com/AntennaPod/AntennaPod][GitHub]]。

-----

云服务厂商拒绝阿里云等国内企业 https://twitter.com/xiqingongzi/status/1604375391267098624

-----

我的联通卡，超套餐流量5元/G。

联通卡销户：中国联通app（套餐合约未到期，无法APP注销）或者杭州联通营业厅

-----

周二下午or周三凌晨买最便宜

周五买最贵

下午买便宜，上午买贵

飞行时间一早一晚的便宜，中间白天的贵

春节、寒暑假、五一、十一等旺季提前一个月预定

淡季时提前半个月预定

每年的双十一、双十二大促也可以囤机票，这是什么意思？

机票在哪里买最便宜？首选航空公司官网，很多特价机票只有官网能看到。不定时会有促销。也可以在各个旅游平台进行比价。

国内航空公司的会员日价格低至一折。

#+BEGIN_QUOTE
各航空公司的机票打折日：

- 国航：同月同日（1.1,2.2,3.3等）
- 海南：每月8日
- 东方：每月9日
- 南方：每月28日
- 深圳：每月12日
- 厦门：每月9日
- 四川：每月19日
- 吉祥：每月25日
- 昆明：每月16日
- 九元：每月9日、19日、29日
- 瑞丽：每周二下午6:00
- 西部：每周三上午10:00
- 祥鹏：每周四上午10:30-11:30
- 中国联合：每周五中午12:00
- 春秋：每月27日，每月9日，有1元抢票活动，每月15日有日本线促销
- 亚洲：一周一小促，三个月一大促。一般是2月/3月、5月、8月和11月

各航空公司主要航线城市：

- 春秋：曼谷、大阪、济州岛、普吉岛、台北中
- 中国联合：内蒙古、东营、海南
- 瑞丽：昆明、呼和浩特、沈阳、青岛
- 祥鹏：云南各大城市、曼谷、郑州
- 香港快运：昆明、兰州、清迈、岘港
- 泰国狮航：泰国国内、泰国飞国际
- 乐桃航空：日本国内、香港、台北飞日本
- 马来西亚：国内及周边国家
- 马印航空：马来飞泰国
#+END_QUOTE

关注航空公司公众号。

十人以上可以打电话定团体票。

廉价航空不提供餐食饮料，注意免费行李托运额，注意额外的托运费比机票本身还贵。

如果出发地或目的地太贵，可以看看相邻城市。

机票的价格变动很频繁，抓住时机。

购票前多次刷新网页，因为航空公司的票价随时都可能变动。

一次性买往返比分开购买划算。

每年3、4、9、11月是错峰出游的最佳时间，机票会便宜很多。

国内机票提前1-2个月买，国际机票提前3-5月买。这太离谱。

不要短时间内频繁看某个航班，为什么

-----

订阅海外服务充值：https://www.nobepay.com/app/home ，一次最少充值500

-----

支付宝-充值中心，一个月话费最多充3次

-----

再也不要买罗森便利店的盒饭，我觉得它并不新鲜，味道怪怪的。
