#+TITLE: 月读（2022年9月）
#+DATE: <2022-09-15 Thu 16:06>
#+TAGS[]: 他山之石

* [[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy][Proxy - JavaScript | MDN]]

The =Proxy=  object enables you to create a proxy for another object, which can intercept and redefine fundamental operations for that object.

* [[https://yufree.cn/cn/2022/04/24/accent/][口音 - Miao Yu | 于淼]]

#+BEGIN_QUOTE
注重细节是一种对他人对礼貌，但礼貌的度应该是构建在互相尊重而不是互相讨好或施虐受虐上的。新人进入社会时老人最喜欢做的事就是教育新人如何讨好他人取悦领导而融入集体之中，这不过是反复上演屠龙少年变成龙的戏码而已。
#+END_QUOTE

#+BEGIN_QUOTE
细节很多时候都是情绪化的引子，很多人在讲细节的重要性时用的例子大都是一个点没注意到然后某件事失败的小故事。但这里面有点概念混淆，很多例子中的细节其实并不是细节，例如所有的安全检查都不算是细节，缺了都算事故；另外一些细节确实起作用了，但更准确说是对特定的人或者群体起作用了，并不具备演绎到所有人的价值。
#+END_QUOTE

#+BEGIN_QUOTE
但这种脱敏对一个人的成长还是很重要的。现在的所谓鸡娃都是在灌输家长的意志并顺应时代需求，是把孩子当成产品在包装打磨，但很少去问孩子自己对环境的感受。现在的社会环境不论家长还是老师都不可能打骂孩子，这样有利于他们构建自信心，但其内心可能依然是脆弱的，会被很多小事直接搞成情绪崩溃，到成年也一样。但如果脱敏训练足够，那么孩子可能会很叛逆，但至少是经得起风雨的。就我们当前这个不确定性越来越多的时代，今日的安稳与明日的动荡可能就是一瞬间的事，我们并不需要情感细腻的安慰而更需要豁达幽默的心态。这里的脱敏不是说打孩子，没收手机或断网才是文明的手段，效果比动手好多了。
#+END_QUOTE

#+BEGIN_QUOTE
如果想脱敏不妨先构建自己的滤波器，不去在乎或响应那些语气助词跟背后的含义，就简简单单去理解对方表达的意思。如果对方期待你的响应，那多半对方也是在期待情绪化释放，这时可以看场合点明对方意图并简单陈述自己的回应或引导对方释放情绪，很多时候仅仅是把自己的情绪说出来情绪压力就会释放一大半。另一个对策就是隔离情绪化信息源，如果你觉得自己还不足以控制自己的情绪，那就关掉信息源
#+END_QUOTE

从口音讲到人的感性

作者生活的纽约，有着来自世界各地的人们，他们的英语也大多存在口音。其实，如果对方的目的是交流，彼此之间不太把口音当一回事。

注重细节确实是对他人的一种礼貌，但礼貌的度应该是构建在相互尊重而不是相互讨好或施虐受虐上的。

现代职业结构的冗余造成大系统里的螺丝钉既不需要有自我意识，也不需要创造性技能，因此会对走流程守规矩特别看重。

通过细节引导情绪化。很多人在将细节的重要性时用的例子大都是一个点没注意到然后某件事失败的小故事。但这里面有点概念混淆，很多例子中的细节其实并不是细节，例如所有的安全检查都不算是细节，缺里都算是事故。

从作者的语文成绩，说到感情脱敏。

#+BEGIN_QUOTE
我小时候摔了喊疼，大概率得不到任何反馈，要是喊得时间长还会被说娇惯坏了，跟别的小朋友打架回家告父母大概率是在家里反思为啥跟人打架后再挨顿打长记性，独生子女也没有兄弟姐妹撑腰，而在学校老师们还比较信奉体罚，所以基本一路成长一路挨打，摆在我面前的经常不是挨打还是不挨打，而是打得轻点还是打得半死，打到最后自然皮糙肉厚，神经大条。
#+END_QUOTE

作者读到生物学博士，跟家庭培养关系也有限。

脱敏对一个人的成长是很重要的。

#+BEGIN_QUOTE
现在的社会环境不论家长还是老师都不可能打骂孩子，这样有利于他们构建自信心，但其内心可能依然是脆弱的，会被很多小事直接搞成情绪崩溃，到成年也一样。但如果脱敏训练足够，那么孩子可能会很叛逆，但至少是经得起风雨的。就我们当前这个不确定性越来越多的时代，今日的安稳与明日的动荡可能就是一瞬间的事，我们并不需要情感细腻的安慰而更需要豁达幽默的心态。

这里的脱敏不是说打孩子，没收手机或断网才是文明的手段，效果比动手好多了。
#+END_QUOTE

作者认为除了要脱敏，还要警惕所谓“治愈”。生理上有病要去医院，心理上有病也要去医院，“健健康康的天天要被治愈算哪门子事”，更像是变相地宠溺自己。很多人觉得世事艰难要对自己好一点，但你对自己好不改变世事艰难的事实。“治愈”的本质是一种移情，把美好可爱的东西跟自己的境遇联系到一起，这里面的情绪有寄托，也有虚幻。如果人迟早要面对真实世界的残酷，那么越早越好，省得总是无病呻吟。

现代社会指定了儿童作为社会层面的保护对象，然后美好世界的童话迷惑孩子们。儿童读物可以简化社会现象，但一定不要歪曲事实，不能通过欺骗来构建儿童世界观，这样不是保护而是宠溺甚至是加害。

人一旦发展到物质资源不缺乏的状态，就开始追名逐利。如果不能掌控自己的情绪欲望，那么那些有针对性的广告就会迷惑你让你上当受骗。做到对这些利用人情绪欲望的事物的免疫。

没了经济利益主导的情绪化，发自内心的声音才更可能被听清楚，情绪表达也会更真实而不是现在人人都去维护一个职业化角色化面具，这是大多数所谓压力的来源，很多人不适合角色扮演，仅此而已。

“脱敏”，建立自己的过滤器。不在乎那些语气助词及背后的含义，就简单去理解对方表达的意思。如果对方期待你的响应，那多半也在期待情绪化释放，这时可以看场合点明对方意图并简单陈述自己的回应或引导对方释放情绪，很多时候仅仅是把自己的情绪说出来情绪压力就会释放一大半。另一对策——隔离情绪化信息源，关闭朋友圈入口。

脱敏可以让我做更多自己想做的事情。这个世界足够允许多种不同的人生，我无意改变任何人的任何看法，所以也不喜欢别人想通过任何方式改变我的看法，这无关对错，只是个选择偏好而已。

* [[https://www.tdpain.net/blog/a-year-of-reading][I Tracked Everything I Read on the Internet for a Year :: Thomas Pain]]

作者制作了一个自动生成阅读文章列表的自动化流程。

* [[https://blackglory.me/posts/from-blog-to-digital-garden][将博客改造成数字花园 - BlackGlory]]

基于质量对博客内容进行过滤，博客形式对内容并无意义。当以新标准对过往内容进行审视时，大多都无法满足可维护性要求。
如果文章不可维护，那么基于文章的价值就会流失，最终变得没有价值，甚至成为一种债务。
** 文章的可维护性
题材对可维护性起决定性影响。
容易变得过时和无效的题材所包含的信息本质上更像是对其关联事物的一种端到端测试。信息与具体事物之间的关联性往往十分脆弱。
受限于文章篇幅，篇幅越长越难以维护。
维持良好的文章结构很难，文章本质上属于树形结构，树形结构在处理分类问题时很不堪用。
作者在实践中遇到的不可维护的例子：
一节内容的主题与其他节交叉，修改到最后，节与节之间的耦合部分越来越多。导致修改某处，另一处的内容就需要变动。可维护性会变得很差。
如果需要维持良好的文章结构，就要停止过度照顾读者的感受。参考手册往往是很难读的东西，读到一半，可能会需要跳转到其他部分，以获取必要的前置知识，但参考手册的结构通常都组织得不错。
模式代表着“形式”，“框架”，或者“。
人们潜意识里对文章的理解还处于纸质印刷时期，文章已经发布就很难修改，即便修改也不过是小幅度。
但这种内容创作模式不属于数字时代。
数字时代的信息足够失控，这个时代一天产出的信息量比人类进入数字时代以前的信息的总和还要多。
巨量的信息被存储人们见不到的地方，只有机器阅读。人们在不断地接受新信息。
作者提及“可维护性”会随着时间而日渐消失，因此博客日渐衰微，转向数字花园才是关键。
**** 关键发问：文章是展示笔记最合适的选择吗？
作者说：很多写了多年博客的博主其实不是在写文章，而是以写文章的形式写笔记。
作者对笔记的要求很高，而博客文章并不适合作为写笔记和公开笔记的最佳方式。
作者对笔记的三点要求：
1. 笔记内容要足够内聚，同一主题的内容应尽量聚集在一起，而不是被拆分成多个页面
2. 笔记更适合以大纲视图，而不是文章视图呈现；文章视图的层级结构不够明显，缺乏导航价值
3. 作者不认为 Markdown 是一种适合用来做笔记的格式：Markdown 天然缺乏层级结构。作者的笔记是在 Emacs 里编写的 Org-mode 文档
大多数人无法脱离文章这一形式的根本原因在于缺乏脱离它的能力，因为：
1. 市面上绝大多数博客程序都是面向文章设计的，展示文章以外的结构化内容很难
2. 缺乏一个足够简单流行的大纲文档格式和编辑器：Org-mode + Emacs 的高难度组合劝退了太多人
** 从博客到数字花园
数字花园的概念会作者重提，他以为数字花园的重点在于重新审视内容创作的流程，将创作比喻为园艺，从而解开来自博客时代的桎梏。
数字花园类网站的大致特征：
- 文章的排列排序是任意的，文章可能不显示发表和更新日期
- 文章没有“草稿”和“已发布”的分别，只通过“内容的成熟度”来描述文章
- 创建新内容不重要，对已有内容的“修剪”和“浇灌”才是
- 不对文章列表分页
** 作者基于数字花园的改进
- 日期不重要

  对有可维护性的文章而言，文章的发布日期和更新日期都不重要，因为它应该是长期有效的，思考不应因时间而褪色，读者也不需要理解文章的写作背景。根据极简主义的观点，既然它并非必要，就应该舍弃
- 分类和标签引发混乱：停止使用分类和标签，迫使作者将内容的规模维持在无需分类和标签就能管理的程度
- 评论框不是必需品

过去的经历使我意识到缺乏评论框不会阻碍那些真正想要交流的人：如果真的有必要，即使在没有评论框的情况下，这些人也能通过各种方式向我发送信息，这本身是非常奇妙的。我相信那些肯付出更多努力去传达信息的人，所传达的信息相比之下会更有价值。因此我能够心安理得地将没有评论框这件事，作为用户生成内容的过滤器来使用。
- CC 协议没有现实意义
- 退出其他平台
- 内容成熟度的表示方法
- 在一个页面列出所有条目
- 个人知识管理方案公开

  笔记：是以大纲视图呈现的 Org-Mode 格式
  涉及技术细节的文章是最缺乏维护性的那类题材，技术很适合笔记形式，因为笔记对文本完成度的要求比文章低得多：写笔记时，我不需要在意文体和结构，不需要斟酌用词，一切都是以方便使用和理解为目标编写的。笔记能随着使用而逐步更新完善，也可以轻易舍弃。
- 一切都是纯文本
- 保存即发布


* 如何解决信息过载
https://blackglory.me/posts/how-to-solve-information-overload
** 专注于影响力最大的关键事物
有种被称为”幂律分布“，多见于商业、文化和创意领域。少量的关键事物会影响大多数事物。作者认为——大多数人只是无能的模仿者

关键事物往往具有远大于一般事物的价值。如果有两本书，一本是可被归类到关键事物的书籍，另一本则是被这本书影响的人所写出的书。前一本的价值远大于后一本，因此阅读后一本简直就是在浪费自己的时间。

现实中，一般事物会从各种角度与关键事物进行差异化竞争。

在解决信息过载时，识别关键事物，对减少需要处理的数据规模有巨大帮助。对于信息来说，关键信息与一般信息的差距往往是绝对的，一旦不对等的情况被消除，一般信息就会变得没有价值。
**** 史特金定律 Sturgeon's law
"Ninety percent of everything is crap." 世界上有 90% 的事物都是垃圾。

作者认为在互联网上，至少有 99% 的内容是垃圾。

事物是”垃圾“其实并不是问题，真正成为问题的是人类只有有限的时间和精力。所以对事物的挑选难免会发展成零和游戏，这使得那些缺乏有效评分体系的领域变得不值得投入大量精力，因为区分事物的好坏变得困难低效。
**** 林迪效应 Lindy effect
通过估计年龄和“健康程度”，来判定一个事物是不是会继续存在。一个事物存在的时间越长，它有望继续保持起原有地位的时间就越长。

可以依据该效应，对一件事物是否属于关键事物进行判断。可以根据事物存在的时间，以及它被挑战的次数做出决策。对于一个尚未进入的领域，保守的选择至少会让潜在的失败风险更小。

不过，部分事物长期存在所依赖的优势并不可持续，要小心：

- 如果事物当前地位是靠不对等的竞争手段维持的，则应该考虑它的竞争对手
- 如果事物当前地位是依赖于畸形的环境维持的，则应该远离事物背后的整个领域
- 如果事物当前地位是利用人性的弱点维持的，则应该远离事物背后的整个领域
** 不会失效的过滤器
解决信息过载的办法有很多，但它们大多有漏洞，根据墨菲定律，有漏洞就一定会出现利用这些漏洞的人。

并且，过滤器在设计时没有考虑到人类的非理性行为。

人类处理信息的能力非常低下，以至于过滤后的信息仍然多到无法处理。

需要处理的信息是无规律的。

时间是一种有效的过滤器，经过漫长岁月而沉淀下来的，关键事物在其中所占比重稍高一些。

然而，把时间作为过滤器缺乏实用性，将等待作为一种策略对很多情景来说是不现实的。
** 一次是不够的
在这个信息容易获取的时代，太多信息被制造出来，让过剩的好奇心有依托的地方。

那么，如何过滤？

一个简单的应对策略——忽略掉所有只看到一次的新信息。只有当一个信息在不同场合被提及两到三次时，才有进一步了解的必要。
** 我不需要它：认知上的开悟
信息过载有一个不那么明显的哲学解决方案。这个解决方案基于一个非常简单的事实：当我的认知层次觉得大多数事物都有价值的时候，很难不面临信息过载。

抬头仰望时觉得一切都很庞大，低头俯瞰时觉得一切都很渺小，二者的区别是观察者所处的认知层次不同。

如果要达到更高的认知层次，人们应该强迫自己消化吸收更多信息，不仅要积累信息量，还要提升信息的深度。

#+BEGIN_SRC txt
得益于人类的适应力，在你坚持消化了足够多的信息后，在某个时刻，你会惊觉自己到达了新的境界：你掌握了一套与个人期望高度吻合的模式匹配策略——在大量消化信息的过程中，大脑训练出了一种高效率的信息过滤器。你能比以往更轻松地解构和重构信息，常常能用直觉去补足信息量不足的部分。你能闻到信息的坏味道，意识到信息背后的问题，事件之后的发展经常会验证你的预测。

这时大部分信息对你来说已经变得无趣，因为它们太低级——你注意到信息经常是以某种方式重复的，你对信息已经熟悉到可以很快发现这些重复，然后把它们视作噪音加以排除。

你看待事物的标准因此被拔高，很多事物已经不如原来认为的那样有价值——你发现优秀事物的平凡一面，而平凡的事物比过去看起来更糟——这时候一些真正优秀的事物开始脱颖而出，而以前你从未发现它们竟然有如此高的价值。

当人发觉自己已经在摒弃和拒绝那些不够高级的信息的时候，就离开悟不远了。开悟意味着你对自己熟悉的诸多事物的了解已经深刻到足以用哲学和理性的方法将其扩展到其他事物上，这需要庞大的知识储备和大量的思考。你会发现事物的价值都有待被重新判断，它们的价值往往会开始减少，有些会归零，甚至只剩下负面价值。你很可能会注意到真正有价值的东西总是存在着一些共性，于是判断事物是不是真正有价值也变得越来越容易。对抵达这一境界的人来说，信息过载只是过去式，因为有价值的信息其实是很少的。
#+END_SRC

Dunning–Kruger effect——关于自我能力的判断的认知偏差。
** 拒绝灵丹妙药：选择最困难的路径
有时，最短、最简单的路径可能是错误的路径；而最远、最困难的路径才是正确的。所有事情都有更简单的解决方案，但却忽略了为了更简单而损失的成本。

作者认为，存在一个终极解决方案，既可摆脱摆脱商业控制，又能完美匹配个人需求。

作者观察到，在某些领域存在着这样的解决方案，但它们不是以最终产品的形式存在，而是以思想、哲学、方法论的形式存在。

只要我掌握了它们，我就可以形成自己的解决方案，而不再需要依赖现成的服务。