#+TITLE: 月读（2023年3月）
#+DATE: <2023-03-05 Sun 08:02>
#+TAGS[]: 他山之石

{{< monthly "How to Learn React in 2023" "https://www.freecodecamp.org/news/how-to-learn-react-in-2023/">}}
学习 React 需要掌握的 JS 概念：

- Variables
- Arrays (and the .map() function)
- Objects
- JavaScript events
- Functions and arrow functions
- Scopes and closures
- Promises and async-await syntax.
- Basic error handling

https://beta.reactjs.org/

You Don't Need to Learn Class Components: Class components are still a part of React and they are still used in production code in a number of instances (such as error boundaries). But just be aware that you do not need to learn them in order to be skilled at React.

Learn React Query `@tanstack/react-query`: The greatest benefit of using React Query comes from that fact that is gives you a cache (a store) that lets you hold on to the result of each query, so you can "save" the data that you've fetched. Plus it has many tools to update that cache exactly the way you want.

You Don't Need to Learn Redux
{{< /monthly >}}
{{< monthly "使用 Cloudflare Workers 解决 OpenAI 和 ChatGPT 的 API 无法访问的问题" "https://github.com/noobnooc/noobnooc/discussions/9">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "将 ChatGPT 变成你的生产率" "https://pepcn.com/gtd/jiang-chatgpt-bian-cheng-ni-de-sheng-chan-lu">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "谈谈我对 ChatGPT 应用的 prompt 的看法" "https://reorx.com/makers-daily/004-prompts-and-parameters-transparancy/">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "OpenAI 选择了使用 Server-sent events 来实现 ChatGPT 是逐句给出答案" "https://twitter.com/mr_easonyang/status/1632407953889447937">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "Modular Web Design: The New Playbook for B2B Websites" "https://www.webstacks.com/modular-web-design">}}
模块化网页设计

Modular design is an approach for designing complete products by combining smaller, independent parts. As shown in the example above, the smaller pieces are independent of each other, but when assembled, they can form different finished products.
{{< /monthly >}}
{{< monthly "关于笔记的一些思考" "https://www.usmacd.com/2022/09/16/note/">}}
我们应该寻找与我们观点相反的论点或者事实来挑战我们的既有思维，但是受「确认偏差」的影响，我们会不经意地忽略这些信息，那些和我们观点一致的信息有很大吸引力，因为这些信息可以证明自己很博学。解决「确认偏差」的方法：把寻找证实性信息变为收集所有信息，不需要关注这些信息支持的具体观点。
{{< /monthly >}}
{{< monthly "学习神经网络的一点笔记" "https://blog.codingnow.com/2023/03/feedforward_nn.html">}}
读了这篇文章，开始对机器学习感兴趣了。但奈何时间不够用，还要找工作，只能暂时搁置了。
{{< /monthly >}}
