#+TITLE: 月读（2023年6月）
#+DATE: <2023-06-02 Fri 10:02>
#+TAGS[]: 他山之石

{{< monthly "黃仁勳2023年台大畢典演說全文" "https://www.businessweekly.com.tw/focus/blog/3012429" >}}
在现在这个时期，大环境复杂多变。面临着地缘政治、社会和环境上的变化和挑战。

- 坦诚面对错误，谦卑寻求帮助
- 追求愿景的艰苦过程塑造我们的品格
- 学会放弃是通向成功的核心关键
{{< /monthly >}}
{{< monthly "浪漫爱的迷思｜hayami’s blog" "https://mp.weixin.qq.com/s/lV4hfDyDWWKzYO3CYBAghw" >}}
一见钟情与日久生情。

前者依靠的是瞬时的化学反应，后者依靠的是时间的累积。

#+BEGIN_QUOTE
日久生情需要“催化物”，比如人品、个人魅力、经济基础，甚至是“他对我好”的默默温情，一些些叠加在上面，一点点培养出叫作“感情”的产物。固然这些东西都是重要的，必须的，但我对培养皿里生长出来的爱情从来不感兴趣。我只喜欢一刹那的火山爆发，一秒钟的心跳漏拍，一步踩在云朵上微微失重的眩晕。
#+END_QUOTE

感情里的事情好像不是只有「感觉」，还有承诺，还有责任。

#+BEGIN_QUOTE
相遇只是爱中时间序列的开始，而爱是坚持到底的冒险，是抵抗分离的决心。是跨越时间、空间、世界所造成的障碍的冲动，是永恒的努力与试图，将相遇的偶然化为命中注定。

——Alain Badiou /In Praise of Love/
#+END_QUOTE

做出承诺 -> 让步

承担责任 -> 让渡自我

陪伴和远方能否共存

爱情与自由是否矛盾

#+BEGIN_QUOTE
在一起的人不一定相爱，相爱的人不一定能在一起。而当相爱却不在一起的人终于面对面，才发现人与人之间或许什么都没有，timing only.
#+END_QUOTE
{{< /monthly >}}
{{< monthly "届不到。" "https://mp.weixin.qq.com/s/D1U3DGarg-scrJcW06hLzg" >}}
#+BEGIN_QUOTE
你喜欢一个明星，博主，画手，作者，都要说出来。不要觉得对方关注者多，不差你一句彩虹屁。差的。就差你这句。你这一句吹下去，心灰意冷的作者就会有动力继续写，被骂哭的明星就会多一个笑容，久不更新的博主也会被鼓舞。

不要默默喜欢，因为讨厌他们的人不会默默讨厌。
#+END_QUOTE
{{< /monthly >}}
{{< monthly "《花束般的恋爱》：如何和100%合拍的人说再见" "https://mp.weixin.qq.com/s/UUgARDGvayzeasRnNA7-CQ" >}}
#+BEGIN_QUOTE
也是在今年渐渐懂得，爱情既不是混沌时的冲动，也不是成功后的犒赏，它只是人生阶段的问题。不用再去纠结过去和对错，很多事情没有结局，就已经是我们当时力所能及最好的结局。
#+END_QUOTE

#+BEGIN_QUOTE
我们总是会与一些人虚度光阴，与一些人吃住，与另一些人醉酒做梦。
#+END_QUOTE

#+BEGIN_QUOTE
“我爱你”是一种宣言。从个体而言，是要将生命中的一段偶然（与他或她相遇）变成必然，变成命运。所以，每一句“我爱你”，其实是在说“我会永远爱你”。实际上，爱的宣言意味着，从此在偶然的相遇出发，去追求和抵达永恒，把瞬间变作永恒。

——Alain Badiou /In Praise of Love/
#+END_QUOTE

是否存在连续不断的爱意？爱情只存在于一瞬间中吗？

在《夜以继日》的导演见面会，有观众提问：

#+BEGIN_QUOTE
之前看过您的《夜以继日》，想知道为什么您总是把人与人之间的关系定义为脆弱无常的、不确定的，但在今天很多爱情片或者其他片里，人和人之间都很甜蜜，会一起做一些铭记一生的事情。

但您的电影中都是脆弱无常的关系，我想问一下为什么？
#+END_QUOTE

滨口龙介回答：

#+BEGIN_QUOTE
您看的确实没错，我认为人和人之间的关系就是这样子的，所以会直接反映在我的片子里。

我并不是想要吓唬大家，但是大家真的确信人和人之间有一种很确定的关系吗？这其实是我想要问大家的问题。
#+END_QUOTE

提问：你现在的女朋友可以像我当年那样和你聊这些书于音乐么? 还是说这一切其实并不重要？

Hayami 答：爱情的最终指向从来不是婚姻。也许有一天我们终将不会再谈风华和雪月，但那些读过的书本，看过的电影，听过的音乐，爱过的人，它们早已融入了我的血与肉，塑造了我的现在，成为了我身体的一部分。

#+BEGIN_QUOTE
别怕美好的一切消失，咱们先来让它存在。

——李银河&王小波《爱你就像爱生命》
#+END_QUOTE
{{< /monthly >}}
