#+TITLE: 月读（2023年6月）
#+DATE: <2023-06-02 Fri 10:02>
#+TAGS[]: 他山之石

{{< monthly "黃仁勳2023年台大畢典演說全文" "https://www.businessweekly.com.tw/focus/blog/3012429" >}}
在现在这个时期，大环境复杂多变。面临着地缘政治、社会和环境上的变化和挑战。

- 坦诚面对错误，谦卑寻求帮助
- 追求愿景的艰苦过程塑造我们的品格
- 学会放弃是通向成功的核心关键
{{< /monthly >}}
{{< monthly "浪漫爱的迷思｜hayami’s blog" "https://mp.weixin.qq.com/s/lV4hfDyDWWKzYO3CYBAghw" >}}
一见钟情与日久生情。

前者依靠的是瞬时的化学反应，后者依靠的是时间的累积。

#+BEGIN_QUOTE
日久生情需要“催化物”，比如人品、个人魅力、经济基础，甚至是“他对我好”的默默温情，一些些叠加在上面，一点点培养出叫作“感情”的产物。固然这些东西都是重要的，必须的，但我对培养皿里生长出来的爱情从来不感兴趣。我只喜欢一刹那的火山爆发，一秒钟的心跳漏拍，一步踩在云朵上微微失重的眩晕。
#+END_QUOTE

感情里的事情好像不是只有「感觉」，还有承诺，还有责任。

#+BEGIN_QUOTE
相遇只是爱中时间序列的开始，而爱是坚持到底的冒险，是抵抗分离的决心。是跨越时间、空间、世界所造成的障碍的冲动，是永恒的努力与试图，将相遇的偶然化为命中注定。

——Alain Badiou /In Praise of Love/
#+END_QUOTE

做出承诺 -> 让步

承担责任 -> 让渡自我

陪伴和远方能否共存

爱情与自由是否矛盾

#+BEGIN_QUOTE
在一起的人不一定相爱，相爱的人不一定能在一起。而当相爱却不在一起的人终于面对面，才发现人与人之间或许什么都没有，timing only.
#+END_QUOTE
{{< /monthly >}}
{{< monthly "届不到。" "https://mp.weixin.qq.com/s/D1U3DGarg-scrJcW06hLzg" >}}
#+BEGIN_QUOTE
你喜欢一个明星，博主，画手，作者，都要说出来。不要觉得对方关注者多，不差你一句彩虹屁。差的。就差你这句。你这一句吹下去，心灰意冷的作者就会有动力继续写，被骂哭的明星就会多一个笑容，久不更新的博主也会被鼓舞。

不要默默喜欢，因为讨厌他们的人不会默默讨厌。
#+END_QUOTE
{{< /monthly >}}
{{< monthly "《花束般的恋爱》：如何和100%合拍的人说再见" "https://mp.weixin.qq.com/s/UUgARDGvayzeasRnNA7-CQ" >}}
#+BEGIN_QUOTE
也是在今年渐渐懂得，爱情既不是混沌时的冲动，也不是成功后的犒赏，它只是人生阶段的问题。不用再去纠结过去和对错，很多事情没有结局，就已经是我们当时力所能及最好的结局。
#+END_QUOTE

#+BEGIN_QUOTE
我们总是会与一些人虚度光阴，与一些人吃住，与另一些人醉酒做梦。
#+END_QUOTE

#+BEGIN_QUOTE
“我爱你”是一种宣言。从个体而言，是要将生命中的一段偶然（与他或她相遇）变成必然，变成命运。所以，每一句“我爱你”，其实是在说“我会永远爱你”。实际上，爱的宣言意味着，从此在偶然的相遇出发，去追求和抵达永恒，把瞬间变作永恒。

——Alain Badiou /In Praise of Love/
#+END_QUOTE

是否存在连续不断的爱意？爱情只存在于一瞬间中吗？

在《夜以继日》的导演见面会，有观众提问：

#+BEGIN_QUOTE
之前看过您的《夜以继日》，想知道为什么您总是把人与人之间的关系定义为脆弱无常的、不确定的，但在今天很多爱情片或者其他片里，人和人之间都很甜蜜，会一起做一些铭记一生的事情。

但您的电影中都是脆弱无常的关系，我想问一下为什么？
#+END_QUOTE

滨口龙介回答：

#+BEGIN_QUOTE
您看的确实没错，我认为人和人之间的关系就是这样子的，所以会直接反映在我的片子里。

我并不是想要吓唬大家，但是大家真的确信人和人之间有一种很确定的关系吗？这其实是我想要问大家的问题。
#+END_QUOTE

提问：你现在的女朋友可以像我当年那样和你聊这些书于音乐么? 还是说这一切其实并不重要？

Hayami 答：爱情的最终指向从来不是婚姻。也许有一天我们终将不会再谈风华和雪月，但那些读过的书本，看过的电影，听过的音乐，爱过的人，它们早已融入了我的血与肉，塑造了我的现在，成为了我身体的一部分。

#+BEGIN_QUOTE
别怕美好的一切消失，咱们先来让它存在。

——李银河&王小波《爱你就像爱生命》
#+END_QUOTE
{{< /monthly >}}
{{< monthly "史铁生作品全编-史铁生-微信读书" "https://weread.qq.com/web/bookDetail/c4a3266071b1986fc4a3ddc" >}}
这本书由人民文学出版社，于2016年12月出版。

在这本书里找到了这段话：

#+BEGIN_QUOTE
人与人的差别大于人与猪的差别。人与猪的差别是一个定数，人与人的差别却是无穷大。所以，人与人的交往多半肤浅。或者说，只有在比较肤浅的层面上，交往是容易的。一旦走进复杂，人与人就是相互的迷宫。

——书信-给李健鸣（1）
#+END_QUOTE

我是认可这句话的，两个人一旦开始深交，必然要面对彼此人性中复杂的部分。

Twitter用户@jefflijun这样写道（[[https://twitter.com/jefflijun/status/1666148717827588116][ref]]）：

#+BEGIN_QUOTE
切忌交浅言深。

现在愿意和别人肤浅且快乐地相处。一旦开始深交，和某个人产生羁绊，也就意味着这个人有了伤害你的权利。
#+END_QUOTE
{{< /monthly >}}
{{< monthly "避免婚前同居：这在理论上是对的，但不适合实践？" "https://stephenleng.com/on-cohabitation/" >}}
我还从未想过结婚这件事，看看这样的讨论也是挺有趣的。

科学理论有一定的参考价值，但在实际行动中不一定严格科学地来做。

真诚很重要
{{< /monthly >}}
{{< monthly "结婚前必须要问的13个问题 - 纽约时报中文网" "https://cn.nytimes.com/style/20160325/t25marriage/" >}}
1. 当有分歧发生的时候，你的家人是会摔盘子、冷静地讨论，还是缄口不言？
2. 我们是否会生小孩？如果生的话，你会换尿布吗？
3. 与前任在一起的经历对我们是会有所帮助还是阻碍？
4. 宗教的重要性有多大？如果要庆祝宗教节日的话，会是怎样的形式？
5. 一方有债，是否共同承担？你是否愿意在经济上资助我？
6. 为一辆车、一张沙发或一双鞋，你最多愿意花多少钱？
7. 你能接受我不带你，自己去做一些事吗？
8. 我们喜欢彼此的父母吗？
9. 性对你来说有多重要？
10. 与他人的调情可以进行到什么程度？看色情作品可以接受吗？
11. 你知道都有哪些表达“我爱你”的方式吗？
12. 我身上有哪些东西是你比较欣赏的，又有哪些是你不能忍受的？
13. 你觉得十年后的我们会是什么样？
{{< /monthly >}}
{{< monthly "让陌生人迅速相爱的36个问题 - 纽约时报中文网" "https://cn.nytimes.com/culture/20150123/t23questions/" >}}
两个陌生人之间的亲密关系或许可以通过彼此询问一些特别的个人化问题而快速升温。

这36个问题分为三组，一组比一组来得寻根究底。

这个理论的核心是，共同的脆弱能促进亲近感。这项研究的作者们称：“同伴之间发展亲密关系的关键模式在于持续、逐步升级、相互且个人化的袒露自我。”允许自己和另一个人共享脆弱可能非常困难，下面这个练习能迫使你做到这一点。

卡特隆和她的朋友在文中尝试的最后一件事是彼此对视四分钟，这个过程没有被详细记录（其实可以从两分钟到四分钟不等）。但是卡特隆毫不迟疑地推荐这件事。“两分钟的效果已经很惊人了，”她告诉我，“四分钟真的非常有效。”

第一组
1. 如果可以在世界上所有人中任意选择，你想邀请谁共进晚餐？
2. 你想成名吗？想以什么方式成名？
3. 打电话之前你会先排练一下要说什么吗，为什么？
4. 对你来说，“完美”的一天是什么样的？
5. 你上次自己唱起歌来是在什么时候，给别人唱呢？
6. 如果你能活到90岁，同时可以一直保持30岁时的心智或身体，你会选择保持哪一种呢，心智还是身体？
7. 你是否曾经秘密地预感到自己会以怎样的方式死去？
8. 说出三件你和你的伴侣看上去相同的特征。
9. 人生中的什么东西最令你感激？
10. 如果你能改变被抚养成人过程中的一件事，会是哪一件。
11. 花四分钟时间，尽可能详细告诉伴侣你的人生经历。
12. 如果你明天一觉醒来就能拥有某种才能或能力，你希望那会是什么能力呢？

第二组
13. 如果有一个水晶球可以告诉你关于自己、人生，未来乃至任何事情的真相，你会想知道吗？
14. 有没有什么事是你一直梦想去做而没有去做的，为什么没有做？
15. 你人生中最大的成就是什么？
16. 在一段友谊之中你最珍视的是什么？
17. 你最宝贵的记忆是什么？
18. 你最糟糕的记忆是什么？
19. 假如你知道自己在一年内就会突然死去，你会改变现在的生活方式吗？为什么？
20. 友谊对于你来说意味着什么？
21. 爱与情感在你生活中扮演着什么样的角色？
22. 和你的伴侣轮流说出心目中对方的一个好品质，每人说五条。
23. 你的家人之间关系是否亲密而温暖，你觉得自己的童年比其他人更快乐吗？
24. 你和母亲之间的关系是怎样的？

第三组
25. 每人用“我们”造三个句子，并含有实际情况，比如“我们俩在屋子里，感觉……”
26. 补完这个句子：“我希望和某人在一起，分享……”
27. 如果你想和对方成为亲近的朋友，请告诉对方有什么重要的事情是他或她需要知道的。
28. 告诉对方你喜欢他或她身上的什么东西，要非常诚实，说些你不会对萍水之交说的东西。
29. 和对方分享生命中那些尴尬的时刻。
30. 你上次在别人面前哭是什么时候？自己哭呢？
31. 告诉对方，你已经喜欢上了他或她身上的什么品质。
32. 你觉得什么东西是严肃到不能开玩笑的，假如有的话。
33. 如果你今晚就将死去，而且没有机会同任何人联络，你会因为之前没有对别人说什么话而感到遗憾，你为什么到现在都没有对他们说这些话呢？
34. 假设你拥有的全部东西都在你的房子里，现在房子着了火，救出家人和宠物之后，你还有机会安全地冲进去最后一次，取出最后一件东西，你会拿什么，为什么？
35. 你的家人中，谁去世了会令你最难过，为什么？
36. 说出一件你的个人问题，问对方如果遇到此事要如何解决。另外，也要让对方如实告诉你，在他或她眼中，你对于这个问题的感受是怎样的？
{{< /monthly >}}
{{< monthly "如何快速与陌生人相爱 - 纽约时报中文网" "https://cn.nytimes.com/culture/20150123/t23love/" >}}
我们都有一套关于自己的说辞，用来提供给陌生人或点头之交，但亚伦博士的问题让你不可能依赖那套说辞。我们的交谈就像小时候在夏令营，和新朋友整晚不睡，交流自己短短人生中的各种细节，快速增进友谊。13岁，第一次远离家乡的时候，快速了解别人是很自然的事情。但成年后就很少有这样的环境了。

我曾经沿着陡坡滑雪，曾经腰间系着短绳攀岩，但在整整四分钟里静静凝视一个人的眼睛是我一生中最精彩也是最刺激的体验。头几分钟里，我试着调整呼吸。后来我们又神经质地笑起来，最后终于安静下来。
我知道眼睛是灵魂的窗口之类的说法，但那一刻的核心并不在于“我是真的在看某人”，而在于“我看到某人是真的在看我”。一旦我开始接受这种认知中可怕的成分，让不适感慢慢消失，我就进入了未曾预料到的境界。

我猜想我们之间的关系会怎样发展。至少我觉得这算是个好故事。但我现在明白，这个故事不是关于我们两人的，而是关于费心去了解别人有多么重要，“被人了解的意义”，这确实是个好故事。

确实，你不能选择让谁来爱上你，尽管多年来我一直希望可以这样选择；你也不能仅仅为了自己方便就创造出浪漫气氛。科学告诉我们，生物学起到了作用，我们的信息素与激素在恋爱过程中扮演很重要的角色。

“爱情”并不是发生在我们身上的事情，我们相爱是因为我们都选择如此。
{{< /monthly >}}
{{< monthly "爱情需要用心经营 - 纽约时报中文网" "https://cn.nytimes.com/health/20130205/c05love/" >}}
尽管有些人离婚有非常正当的理由，比如身体和精神上的虐待，难以忍受的婚外情，成瘾行为或者不可调和的矛盾，但是专家表示，许多破裂的婚姻似乎只是源于感情的减弱和消亡，因为夫妻双方没有努力保留爱情火焰的余烬。

我用“余烬”这个词，是因为爱情的火焰——这种感情促使人们忘记所有的烦恼，如同脚生双翼，在大街上飞奔——并不会持续很久，即使情侣们竭尽全力也不会长久。新恋情点燃的热情不免会冷却，必须逐渐转化成对彼此的关心、同情和友谊，双方才能维持长久的关系。

理查德·卢卡斯(Richard E. Lucas)和他在密歇根州立大学(Michigan State University)的同事进行的研究表明，通过婚姻提升的幸福感只能持续大约两年的时间，此后人们会恢复到原来的幸福水平——或者再次感受到不幸福。

加州大学河滨分校(University of California, Riverside)的心理学教授索尼娅·柳博米尔斯基(Sonja Lyubomirsky)表示，迷恋与热情持续的时间甚至更短，必须转化成“伴侣之爱，包括更多深厚的亲情、友情和喜爱”。

一、构建伴侣关系

柳博米尔斯基博士呼吁，夫妻双方应该在遇到麻烦之前，采取措施来缓解、防止或抵消“享乐适应”的影响，挽救平淡的婚姻。她推荐的策略包括抽出时间一起聊天，真诚地倾听彼此的想法，向对方表达赞美和爱慕。

柳博米尔斯基博士强调“赞赏的重要性”：珍惜你获得的幸福，不要想当然地对待你的配偶。经常提醒自己和你的伴侣，你多么赞赏对方和这段婚姻。

变化也同样重要，这是内在的刺激和奖励，心理学家写道，“如果我们想避免享乐适应，变化显得至关重要”。心血来潮地换个新花样，改变你和伴侣相处的方式，让你们的关系保持“新鲜感，充满意义和积极性”。

新鲜感是强有力的兴奋剂，也能增加夫妻性生活的情趣。不过柳博米尔斯基也承认，“科学发现保持激情之爱的方法乏善可陈。”她把激情的衰退与人类的成长和衰老联系起来，“这仅仅是人性的一部分。”

除了变化，我们还有另一个小窍门：制造惊喜。随着时间的流逝，伴侣通常对彼此过为熟悉，陷入单调乏味的日常生活。他们应该振作精神，尝试新的活动，游览新的地方，结识新的朋友，共同学习新的技能。

柳博米尔斯基博士写道，“拍拍后背，握紧对方的手，轻轻的拥抱，搂住肩膀——科学表明肢体接触能够挽救平淡的婚姻。”更多的无性爱身体接触和每天的情感交流，将有助于人们重新感到温暖，心中充满柔情。

她建议：“在你们的婚姻关系中，增加身体接触的次数，要将每周增加的接触次数”控制在舒适的范围内，而这个范围要根据配偶的个性、背景以及对无性爱接触的接受程度来决定。

二、正能量

支持你伴侣的价值观、目标和梦想，对他（或她）带来的好消息充满兴趣和喜悦。我丈夫的热情在于为音乐剧写剧本。每当他的日常工作转移到其他城市，我都会建议他追求自己的梦想，而不是劝他找份新的工作。他的工作永远不会带来丰厚的金钱回报，但是这份职业让他感到满足，让我激动不已。

为了让你们的关系步入更加幸福的轨道，心理学家建议你每天写下自己和伴侣之间积极和消极的表达，努力提高积极情绪对消极情绪的比例。

她建议你每天早上扪心自问，“在今天，我能不能用五分钟时间做些什么，让我的伴侣感到生活更美好？”最简单的行为，比如分享有趣的事情、面带微笑或者幽默逗趣，都能增加婚姻的幸福感。

{{< /monthly >}}
{{< monthly "教这一代人如何去爱 - 纽约时报中文网" "https://cn.nytimes.com/education/20140423/t23love/" >}}
情感的脆弱性

“如果我们想体验亲密关系，保持脆弱就是我们不得不承受的一个风险，”休斯顿大学(University of Houston)教授布林·布朗(Brené Brown)写道。布朗女士一直致力于研究脆弱的必要性，以及对脆弱失去敏感会导致什么后果等问题。

他们不知道如何追求一位潜在伴侣，更遑论找到这样做的语言了。

逃避脆弱会使我们丧失建立恋爱关系，以及让这种关系结成正果的机会。

当我们扼杀经由催产素产生的亲密情感时，我们也就进一步降低了我们自己对爱情的敏感度。这种“爱情”荷尔蒙是在性高潮时被释放出来的，但它也会在拥抱或深情缠绵后涌入身体和大脑。

性关系生物学，求爱的多文化历史，脆弱心理学和社会学。
{{< /monthly >}}
{{< monthly "平庸的博士们" "https://stephenleng.com/mediocre-phds/" >}}
我们能否在今天的博士群体中——或者干脆所有受过至少正规本科教育的人当中——找到康德、叔本华、莎士比亚、弗吉尼亚·伍尔夫、拉斐尔、爱因斯坦、达尔文、库布里克、布列松？今天的这些天才在哪里？这是每个受过或者给别人进行高等教育的人都应该思考的问题。

一个对以往那些充斥着天才的时代有所了解的人，很容易会对我们这个时代的平庸感到失望，并意识到事情的严峻程度。我们对博士们寄予厚望，但现实却令人沮丧。而且，我们不仅很难找到天才（genius），甚至很难在博士群体中找到具有高度创造力（creativity）的人，这就是我所说的“平庸的博士们”——一边是普遍的平庸，一边是对普遍平庸的普遍失望，这就是我们这个时代的特点。

当然，天才只能是极少数人，而对于作为大多数的我们来说，提升自己的创造力也意义重大。就此而言，我相信所有人都还有希望。
{{< /monthly >}}
{{< monthly "无意义感与迷茫：对重新参加高考梦的一个解释" "https://stephenleng.com/dreaming-exams-interpretation/" >}}
梦中产生的焦虑实际上起源于白天的残余经验。

为什么不安和迷茫会跟高考联系在一起呢？现在回想起来，虽然大家当时想考上理想大学的口号喊得很响，但是包括我自己在内的许多人都不知道那究竟意味着什么，就像没人知道共产主义社会是个什么样子但是还是继续喊口号。那个所谓的理想大学，只是一个空泛的名字而已，并不带有任何内容。

*在狂热的荒诞下，繁忙而紧张的高三教室里，人们活在一种抽象的没有内容的对未来的期盼中，而且由于半军事化生活过于严酷而单调，也不得不把眼光完全放在未来，这里面隐藏着对现实生活的无意义感以及对未来的迷茫。*

我们拼命地为一个未来的目标奋斗，但是却对那个目标以及完成目标的意义一无所知。
{{< /monthly >}}
{{< monthly "作者的银行IT工作经历" "https://aassbb987.blogspot.com/2023/06/it-hr3-hrhroffer-2023483000-domain-know.html" >}}
看了这篇文章，我不会去银行做IT。

{{< /monthly >}}
