#+TITLE: 月读（2023年7月）
#+DATE: <2023-07-02 Sun 22:16>
#+TAGS[]: 他山之石

{{< monthly "相亲100次后，她参透了“好嫁风”的秘密" "https://mp.weixin.qq.com/s/sRoiXP9KnkE12sQ0MakK1A" >}}
这篇文章的主人公黄引，是个有趣的人。

一些引起我注意的引用：

#+BEGIN_QUOTE
我看到湖南老家一个相亲群的聊天记录，里面全是家长，每个适婚男女的背景资料会转化成一串数字发进群里，包括年龄、身高、收入，以及车房情况等。大家就根据这些数据挑选匹配对象。这种对人的物化是非常明确和赤裸裸的。

对人的物化和工具化，在相亲这种活动中，方方面面都有体现。有人会直接问你家里几口人，收入如何，工作忙不忙，有没有在广州买房，要不要求对方有房，愿意要几个孩子。情商高一点的，会把这些话藏在聊天对话中侧面打听。比如问你来广州多久了，学什么专业，以此大概推断你的工作和收入，再通过你住的位置，判断你的生活标准或者有没有房。这种模式非常像面试，好像只关注数据，完全不想了解你的性格和思想，有什么爱好和追求。过强的目的性，让我很不舒服。

我觉得这涉及一个边界问题，一些男生并没有意识到这个行为对女生意味着骚扰和不尊重，或者这就是他的一种试探。如果女生不拒绝的话，他就会进行下一步。

当我用“子欣”这个角色玩相亲游戏，发现迎合了男性需求后，自己的选择面变广了，结婚好像简单了许多。但同时我会觉得这些东西没意思，会厌恶“子欣”这个在相亲市场中受欢迎的角色，而更加想做回自己。

在我相亲过的人当中，IT行业的男生更接近我理解中的正常人。因为行业里男多女少，加上性格比较内向或不会打扮，导致他们在相亲市场里比较劣势，反而对女生各方面条件不会太挑剔，人也大多朴实简单。其实从综合条件来说，他们三观都算不错，属于会赚钱、不会花钱的，还都挺尊重女性。就是精神生活贫乏，人呆了点儿，不太会聊天。

因为他们在20多岁的年纪里，还没有足够的经济条件和自信去相亲，觉得自己没有资本，还需要再努力。这种社会规训，对男性也是一种枷锁。

其实男性在市场里也并不是真的占优势，因为经济往往是相亲市场中的女性排在第一位的择偶条件。

很多男性想要找弱势一点的对象，而优秀的、有能力的女性又喜欢找比自己强的，这就导致双重失衡，男女两方都成了父权制的受害者。其实在我看来，要组建家庭，双方互补就可以。男性只要尊重女性，即使当一个全职爸爸，也是应该被鼓励的。而人与人相处，应该看到的是个体，欣赏具体的人，那些外在的条件不应该成为壁垒。

相亲的时候，我会带着一些问题去跟对方聊，比如你想要什么样的生活，你期待两个人是什么样的关系，想要什么样的家庭生活，以及为什么要相亲，为什么要结婚。随着聊天的深入，我发现，他们给出的很多答案并没有真正经过消化和思考。比如大家普遍受到了主流价值观的影响，开口就是想要寻找温柔善良贤惠的异性，但真正相处起来，你会发现他喜欢的并不是这些东西。而且，绝大多数人并没有思考过婚姻这个问题。往深里去问，只有少部分人会说渴望稳定，但很多人不是真的向往婚姻，只是因为大家都在做这件事。他们自然而然默认结婚是个标准答案，大家只是按照规定路线在走而已。

我开始重新审视这段关系——可能他现阶段要成长为一个具有独立人格，能对自己的人生和另一半负责任的人，还差了很大距离。这不是我想要的彼此独立又平等的关系。
#+END_QUOTE

能够认识自己，然后认识对方。彼此构筑一种独立且平等的关系，共同生活。
{{< /monthly >}}
