#+TITLE: 月读（2023年5月）
#+DATE: <2023-05-02 Tue 11:10>
#+TAGS[]: 他山之石

{{< monthly "Forced Optimization - YouTube" "https://www.youtube.com/watch?v=LVEGRj3RZSA" >}}
[[https://deno.com/]]

- Deno 2.0 今年夏天发布。
- Deno 对 Node.js 有天然的支持
- Deno KV
{{< /monthly >}}
{{< monthly "What is a Vector Database? | Pinecone" "https://www.pinecone.io/learn/vector-database/" >}}
Vector embeddings 是一种帮助 AI 记忆事物的工具。在执行一些复杂任务时很方便。

Embbedding 由 AI 模型生成，有着巨量的特征信息，这些特征信息代表了数据的不同维度，对于理解模式、关系和底层结构至关重要。所以，需要设计一种专门存储这些信息的数据库。矢量数据库通过为嵌入提供优化后的存储和查询功能，以此满足这一需求。矢量数据库具有传统数据库所没有的独立矢量索引的能力，以及传统标量数据库所没有的专门处理矢量嵌入的能力。
{{< /monthly >}}
{{< monthly "IndexedDB as a Vector Database" "https://paul.kinlan.me/idb-as-a-vector-database/" >}}
#+BEGIN_SRC html
<script type="module">
  import { VectorDB } from "./node_modules/idb-vector/index.js";

  const db = new VectorDB({
    vectorPath: "embedding"
  });

  await db.insert({ embedding: [1, 2, 3], "text": "ASDASINDASDASZd" });
  await db.insert({ embedding: [2, 3, 4], "text": "GTFSDGRG" });
  await db.insert({ embedding: [73, -213, 3], "text": "hYTRTERFR" });

  // Query returns a list ordered by the entries closest to the vector (cosine similarity)
  console.log(await db.query([1, 2, 3], { limit: 20 }));
</script>
#+END_SRC
{{< /monthly >}}
{{< monthly "TypeScript is 'not worth it' for developing libraries, says Svelte author, as team switches to JavaScript and JSDoc • DEVCLASS" "https://devclass.com/2023/05/11/typescript-is-not-worth-it-for-developing-libraries-says-svelte-author-as-team-switches-to-javascript-and-jsdoc/" >}}
作为 Svelte 的用户，依然可以在 Svelte 中使用 TypeScript，但是对于该框架的开发将变成 JavaScript + JSDoc。
{{< /monthly >}}
{{< monthly "关于 TweetID:1658453862561501184 中典型诡辩论部分的拆解 | Kivinsae's Nest" "https://www.kivinsae.com/2023/05/17/2023-05-17-no_sophism/" >}}
逻辑分析很精彩，知道了：

诡辩、滑坡论证、从众式论证、强加因果

等概念。
{{< /monthly >}}
{{< monthly "An introduction to Pinia – Vue’s favourite state management library - YouTube" "https://www.youtube.com/watch?v=rrdi0P6ODFI" >}}
Live视频笔记：

- Pinia的状态管理
- 什么时候知道应该在项目中使用 Pinia？
  - 有些嵌套组件之间需要共享状态的
  - 如果知道应用能够增长的

{{< /monthly >}}
{{< monthly "How I manage GitHub Notifications - Anthony Fu - YouTube" "https://www.youtube.com/watch?v=gu-0b6KCf80" >}}
@antfu 分享了自己是如何管理大量 GitHub 通知的
{{< /monthly >}}
{{< monthly "陈佩斯 时间不会欺骗我｜新刊" "https://mp.weixin.qq.com/s/egavRuORSjrjHSXAZUQtlg" >}}
https://chinadigitaltimes.net/chinese/696236.html

话剧《惊梦》——故事说的是解放战争背景下，一个昆曲戏班的生死命运，以及历史的偶然和必然，幽默又悲凉，大气也婉转。

#+BEGIN_QUOTE
他也糊涂过。筹备《惊梦》的剧本时，他以为故事里最大的事儿是新旧文化更替，是昆曲班子学唱新戏的波折。真到排练演出来，他感到这新旧文化冲突却是最弱的驱动力。

“最重的是命，是活命。”他说，“唱新戏并不是最重的，因为并不能因此生发出一连串的情节。是他们因为要活命，去寻找生路，才找到了新戏，是为了保住性命才答应唱山歌北曲，童孝璋（老班主）也不知道新戏是什么，接到手发现，完了，寸步难行，可不得了。”
#+END_QUOTE

#+BEGIN_QUOTE
“在极端困苦的环境下，一个人活不成，人人都互相帮助，必须一群人共同去完成目标，一点点活下来。”陈佩斯说，“所以那种人性的光辉，我也沐浴过。而且在那里头，把我们打造成特别的好人，离开那儿以后，你见不到那么多好的人。”
#+END_QUOTE

#+BEGIN_QUOTE
“你会对人失去信心吗？”我们问他。

“不会，因为我看过好的。”他斩钉截铁回答，“这么多年苦难的生活历练之后，当我们都成了一群很好的人，我发现那种善良的东西，是最有力量的。”
#+END_QUOTE

#+BEGIN_QUOTE
“不是每个人都有机会做个好人，有时候机会都不会给到他们。这是身不由己，所以你看了才会悲从中来。”陈佩斯又强调道，“但这不是我作品的第一目的。我不是为了教化或者笑中带泪，只是因为人物深陷困境，这种身不由己的状态，会给人新的感受。”
#+END_QUOTE
{{< /monthly >}}
