#+TITLE: 月读（2023年2月）
#+DATE: <2023-02-14 Tue 00:11>
#+TAGS[]: 他山之石

- [[https://juejin.cn/post/7199329705706324027][Node常见的三种安全防范手段 - 掘金]]
- [[https://juejin.cn/post/7199176487688667173][Node.js 是什么以及如何学习？ - 掘金]]
- [[https://juejin.cn/post/7199131771669332024][this，你到底是谁？--javascript前端 - 掘金]]
- [[https://juejin.cn/post/7199137002947117093][JavaScript中for in与for of - 掘金]]
- [[https://juejin.cn/post/7199329705706324027][Node常见的三种安全防范手段 - 掘金]]
- [[https://juejin.cn/post/7199000425348743229][实现三列等高布局 - 掘金]]
- [[https://juejin.cn/post/7198910507515920443][退出历史的舞台的arguments - 掘金]]
- [[https://juejin.cn/post/7198626288135340087][JavaScript之this - 掘金]]
- [[https://juejin.cn/post/7198626040355668027][简单利用抽象语法树AST实现一个AOP切面逻辑 - 掘金]]
- [[https://v8.dev/blog/understanding-ecmascript-part-1][Understanding the ECMAScript spec, part 1 · V8]]
- [[https://juejin.cn/post/7199000425349152829][浏览器缓存是如何提升网站访问速度的 - 掘金]]
- [[https://juejin.cn/post/7199152037928599611][前端重点：DNS和CDN - 掘金]]
- [[https://juejin.cn/post/7199161123974201402][前端对密码进行AES加密（AES/ECB/PKCS5Padding） - 掘金]]
- [[https://mp.weixin.qq.com/s/9ISGaRofG6hhh0g6DpGyTQ][Web Worker的正确打开方式]]
- [[https://type.cyhsu.xyz/2018/07/a-guide-to-compositions/][疑难符号使用与输入指南 - Neverland]]

引号的标准用法；横线、圆点

#+BEGIN_QUOTE
无论是在正式场合追求规范的符号，还是在非正式场合选择更加活泼的变通形式，最终的目的都是一致的——用符号更好地表情达意，拓展文字传递信息的带宽。
#+END_QUOTE

参考资料

- [[https://unicode-table.com/en/][Basic Latin — ✔️ ❤️ ★ Unicode Character Table]]
- [[https://home.unicode.org/][Unicode – The World Standard for Text and Emoji]]
- [[http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf][标点符号用法——中华人民共和国国家标准]]
- [[https://www.w3.org/TR/clreq/][Requirements for Chinese Text Layout - 中文排版需求]]

-----

- [[https://abcdxyzk.github.io/blog/2023/01/30/mail-base64/][Base64编码知识详解 - kk Blog —— 通用基础]]

Base64——64 个可打印字符

-----

- [[https://vickiboykis.com/2022/12/05/the-cloudy-layers-of-modern-day-programming/][The cloudy layers of modern-day programming | ★❤✰ Vicki Boykis ★❤✰]]

#+BEGIN_QUOTE
There’s the change that I’m really worried about: that the way a lot of programming goes today isn’t any fun because it’s just plugging in magic incantations — combine somebody else’s software and start it up. It doesn’t have much creativity. I’m worried that it’s becoming too boring because you don’t have a chance to do anything much new. Your kick comes out of seeing fun results coming out of the machine, but not the kind of kick that I always got by creating something new. The kick now is after you’ve done your boring work then all of a sudden you get a great image. But the work didn’t used to be boring.
#+END_QUOTE

-----

- People really don't care. They might chuckle for a moment if you really goofed up but they forget very fast. It's us who amplify what others might be thinking. Someone said it rightly: We suffer more in imagination than in reality. -https://news.ycombinator.com/item?id=33877124

-----

- [[https://rohit.blog/care/][No one cares | Rohit Kumar]]

No one cares who you are, what you know, and what you have created. People are busy in their own lives. They are lost in their own world.

{{< monthly "So, what's next? by core-js author Denis Pushkarev(@zloirock)" "https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md" >}}
开源项目的难处和吸引人的地方，都在这里。
{{< /monthly >}}

{{< monthly "Ramin Honary: The best way to learn Emacs" "https://tilde.town/~ramin_hal9001/articles/2022-04-27_best-way-to-learn-emacs.html" >}}
{{< /monthly >}}
{{< monthly "Comparing the Gatsby, Next, Nuxt, and Nest Open-source JavaScript Frameworks" "https://www.twilio.com/blog/comparing-nextjs-nestjs-nuxt-gatsby" >}}
{{< /monthly >}}

{{< monthly "入行 14 年，我还是觉得编程很难" "https://www.piglei.com/articles/programming-is-still-hard-after-14-years/" >}}
写代码很简单，但写好代码很难。
{{< /monthly >}}

{{< monthly "很遗憾，教书不再是老师最重要的事了" "https://mp.weixin.qq.com/s/FbHKtHgUMAjcCaKfH2JkrA">}}
忽视老师的健康，很多老师因为学生的行为受到身体和心理上的伤害。

> “唯一能把他们黏在这个岗位上的，是他们回想起来有些学生，会觉得内心很温暖。”张然说，“但也仅此而已，你再去看，没有其他更多了。”
{{< /monthly >}}

{{< monthly "Writing Javascript without a build system" "https://jvns.ca/blog/2023/02/16/writing-javascript-without-a-build-system/">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "Testing JavaScript without a (third-party) framework" "https://alexwlchan.net/2023/testing-javascript-without-a-framework/">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "乱记（熊猫-国保）" "http://www.qyjohn.net/?p=7044">}}
<!-- note -->
{{< /monthly >}}
{{< monthly "身为男性，如何尊重女性" "https://hayami.typlog.io/ueno">}}
他自己作为男性深知自己没有办法100%设身处地地为女性着想，所以才要学会倾听，多去理解女性的处境。

然后他也补充了，作为男性最好把自己对女性权益的理解讲给身边的男性，影响他们，而不是觉得自己有解决方案了来说教女性。

说完他就闭麦了，说他是来学习的。
{{< /monthly >}}
