#+TITLE: 月读（2022年10月）
#+DATE: <2022-10-15 Tue 21:10>
#+TAGS[]: 他山之石

* [[https://www.cs.rpi.edu/~hendler/ProgrammableWebSwartz2009.html][Programmable Web - Aaron Swartz]]

为互联网自由斗争的著名人物

* [[https://mp.weixin.qq.com/s/BmgDr1DlW6nFFMBZMijDMw][全民反诈，我的一些建议]]

讨论法律意义上的诈骗行为。

** 建立基本逻辑

- 天上不掉馅饼
- 风险与回报共存
- 技术能伪造身份
- 正经的企业招聘、警方查案、银行风控等，不需要把钱转出去，也不需要缴纳押金
- 任何可能导致自己被要挟，被勒索的隐私信息不能提供给任何第三方
- 相信科学，懂一点经济学，懂一点博弈理论。要看教材性质的，不要看专家解读，就算是真的专家也会因利益低头
- 警惕因为小便宜产生的脱离监管保障的私下交易行为

** 有信息核对能力

- 知道什么是可信信息源
- 能够信息溯源
- 亲戚借钱，领导转账，一定要求真人视频确认
- 电话中奖，警方调查，银行调查，快递调查等，知道如何二次核对，如何寻找可信渠道核对

** 关爱亲人
** 止损心态

一个人从不被骗只能说明这个人非常保守，拒绝相信一切。好处是对一切骗局免疫，坏处是经常错失机会。

* 了不起的创造者

** Xyla Foxlin

[[https://www.youtube.com/c/xylafoxlin][Xyla Foxlin - YouTube]]

一个女孩，是一个创造工程师。

* [[https://yufree.cn/cn/2020/08/01/life-sci-manual/][生活科学手册 - Miao Yu | 于淼]]

《生活科学手册》是改开时期的一本生活指南书籍。

劳动能够给人带来充盈的幸福感而娱乐更多给人带来负罪感。如果不参与创造而仅仅消费别人的劳动成果，自己会觉得不舒服。参与劳动过程中，大脑会想出解决问题的办法，之后便是验证后的成就感。

#+BEGIN_QUOTE
虽然工作也本应如此，但现代社会提供的工作岗位绝大部分是螺丝钉式的，创造性跟高风险是好伙伴，一个谋求稳定发展的职业本能上喜欢标准化流程而厌恶创造，这是现代化的原罪。
#+END_QUOTE

#+BEGIN_QUOTE
现代化的理论不代表现代化的技术，我们当前的通识教育过多侧重了原理而对具体实现做了太多简化。
#+END_QUOTE

#+BEGIN_QUOTE
知识付费的今天搞出很多所谓的新行业，一大堆“资深”人士跑到各个平台上割韭菜。我最厌恶的有三类：情感咨询、职场交际还有成功经验。这三个领域都是弱理论强场景，也就是根本不应该存在“专家”的行业，每个人遇到的具体问题套用似是而非的理论除了搞些亚文化外并不具备最佳解决方案，高度依赖场景。很多人总结的所谓成功经验其实是赢家说了算的东西，经不起时间考验。
#+END_QUOTE

#+BEGIN_QUOTE
能形成理论的学科抽象度都很高，数学、物理就是这一类，但经验不同于理论，经验要依附于个体所在场景，好比我给你画个绿洲图纸你也做不到在沙漠里建出来的结果，很多经验是需要依赖外部帮助的，这个很多人是不会告诉你的，他们执着于告诉你什么是对的，但不告诉你他自己怎么总结出来的，这样的结论听多了就会精于判断疏于思考。
#+END_QUOTE

#+BEGIN_QUOTE
这代人社会角色转换一直有问题的现象，距离劳动比较远，所以带孩子带学生都过分焦虑或不会转换角色，现代人对自己负责还能做到，但对家庭成员或课题组成员负责经常做不到，在现代化社会中家庭作为一个主流单元的情况可能不会持续太久。
#+END_QUOTE

#+BEGIN_QUOTE
我自己愈来愈感到对世界的了解实在肤浅与抽象，而这很大程度是因为我忽视了对自己的了解。我其实无法感受很多别人描述出来的感受，只能说人与人间的认知区别远大于不同观点间的区别。
#+END_QUOTE

我对自己的了解足够了吗？

#+BEGIN_QUOTE
我不是一个需要环境赋能的人，也就没必要关心别人的认可。我意识到注定会被局限在这个时代，但不接受局限在部分观点之中。我需要从生活本身中获取更多的体验，拿着手机看温度不如出门用皮肤去感受。
#+END_QUOTE

* [[https://taoshu.in/net/github-actions-vpn.html][使用 GitHub Actions 科学上网]]
* [[https://yufree.cn/cn/2022/10/03/blog-10-years/][开博十年 - Miao Yu | 于淼]]

互联网打碎了熟人社会，但无法给予安全感，让我们不希望寄托在陌生人身上。

科学思维。找到观点背后的理由。讨论而非辩论，辩论是预设立场而讨论不预设立场通过证据和逻辑来得到结论，大多数现实存在的问题需要讨论而非辩论。

#+BEGIN_QUOTE
所谓大隐隐于市，很多新观点新发现新解决方案其实都埋在日常的琐碎之中，习惯了麻木了有结论了，也就不会再有新的体会了。
#+END_QUOTE

#+BEGIN_QUOTE
这个世界没有啥秘籍去通关，甚至都没有通关这一说，只是人把自己的一生划成了一个又一个的阶段，然后有目标去努力。然而，其实人生并不存在阶段，也没有那么需要别人的经验，很多人给出的经验说白了都是很片面的总结，他们只是用斩钉截铁的语气来对你提出的问题给出答案，但很多问题根本就是开放式的，没有标准答案，得去探索才行，躲在“高人”指点后的人生或许平稳，但太浪费。
#+END_QUOTE
* [[https://via.zhubai.love/posts/2188744921278689280][【事不过三】9 月的 30 条阅读碎片(月刊 2209) | 事不过三]]

* [[https://cn.gijn.org/][全球深度报道网]]

* [[https://www.163.com/dy/article/HG0R2N3H055339TT.html][梁晶：最平凡与最伟大的|奥运会|马拉松|越野赛|越野跑]]
