#+TITLE: 我与计算机之缘
#+DATE: <2026-02-28 Sat 22:34>
#+TAGS[]: 随笔

读过太多厉害人物早期接触计算机的故事，经历大多相像：一开始因为对计算机感兴趣，后来慢慢学习直到选择计算机作为职业。我真正玩计算机时已经在读大学，那是2019年元旦，父亲带着我去一家HP专卖店买了一台笔记本电脑。从那时至今我一直用它学习工作。早年也接触过电脑但那都是在学校的浅尝辄止，因为家里没有电脑所以没有学习编程的环境。笔记本电脑虽然有时会卡顿但还能继续使用，在现在这个经济不好的时期不买新电脑会省下一大笔钱。我给笔记本做过一次官方售后清洁，把老旧的SATA机械盘换成了SATA固态，并把新固态作为系统盘使用。

我用的操作系统是Arch Linux，它已经陪伴我五年时间了，我很感激能有这个操作系统存在。日常使用的桌面环境是KDE，满足了我的使用习惯，我一直都在用它。当初我从Windows逃离时，第一个操作系统选择的是Ubuntu，使用的GNOME桌面，使用了半年时间。大概是因为不喜欢Ubuntu整体的设计思路以及GNOME作为桌面环境有些让我觉得不爽的地方，后来就弃用了。听说Arch Linux自然是因为它最大的特点——滚动发行、软件一直都是最新的。

入坑以后，初期阶段踩坑不少，最近两年升级系统时从未出现过影响我使用的大问题。我为此觉得很幸运。

我很羡慕那些技术厉害的开发者们，他们比我对技术更为沉迷、比我更热爱编程，也有着想让程序更好的意愿。我觉得自己可能永远都只是在追赶他们，在模仿、在向他们学习。我看不懂他们写的代码，因为我并不具备他们的深厚积累。计算机科学浩瀚的知识海洋里总有些无聊乏味的东西，但是那些真正吸引我的、珍珠般闪耀的事物，让我不断地去学习去了解技术背后的道理。

代码是纯粹的、逻辑的，开发者书写代码表达自己对于世界的思考，这是极浪漫的事情。我也深深地被这种浪漫所吸引。在这样的世界里，我能远离世俗的人情世故，尽情徜徉在智识的海洋。我想我永远也不愿离开这种氛围，除非我死掉了。

当我读到阮一峰的科技爱好者周刊（第386期）时，我被他所描绘的、可能就是未来图景的样子吓到了：程序在调动人力来完成自动化流程。AI时代调动人力的就是那些AI模型。人不再是社会经济的核心，AI是。这种可能的未来让我觉得，我需要很长时间来适应这种变化，尽管我并不知道这种变化什么时候开始。

当环境发生变化时，人们首先会想：我该怎么办？我也是这样。我不想也不能坐以待毙，我还有父母要养，未来可能会结婚。我要做什么来保持我的竞争力？我会持续地思考这个问题。
