#+TITLE: 永远的新裤子——新裤子30周年演唱会
#+DATE: 2026-08-23T18:59:00
#+TAGS[]: 随笔

新裤子乐队成立于1996年，是现今仍存世的历史最悠久的乐队之一。今年的演唱会是在纪念他们成立30周年。

和很多人一样，我是在《乐队的夏天》这档综艺节目上知道他们的。那个综艺忘得差不多了，留在脑海里的，只有几支喜欢的乐队，新裤子就是其一。

不知道是什么契机让我知道了这次演出，我没花多久就决定买票去看看。因为我想看一下新裤子的现场是什么样的，想去感受一下什么叫新浪潮朋克。我看完了，现场确实不错，我很高兴自己来看了。

脑袋里最早的听歌经历是五岁到十岁吧，那时候用诺基亚手机反复播放《又见炊烟》、《月亮之上》等老歌，也没有更多选择。后面媒介渐渐丰富起来，大概是2010年从大连回老家以后，听的歌多了，种类也渐渐多了起来。

以前我听得最多的是什么呢？说起来我自己都不会相信：龙井说唱的《兄弟》、庞龙的《兄弟抱一下》、张卫的《机器铃 砍菜刀》。小学初中时有个混社会的同学，他喜欢听这类歌，我也受他影响，当时听着觉得还不错，现在再回看，哇！你好土。

后面，流行歌渐渐听得多了起来。听周杰伦、王菲，我还记得初中音乐课学的[[/posts/wangfei-world/][王菲的《人间》]]，当时看的MV里，这个女人画着浓妆在唱歌，觉得很惊讶。因为以前我没见过这样的女性。当时听歌也很局限，除了老师教的，就是那个时期的流行歌曲。我印象最深的有少女时代的《Gee》和辉星的《失眠症》韩语版。

现在再回听，感慨万千。从小时候到现在，我对音乐的发展不感兴趣，也不关心什么是朋克、什么是摇滚。我只是在听，好听的旋律就多听，不好听的下次绝对不听。

我是在17年注册的网易云音乐，当时我还没有自己的手机号，我想不起来自己是怎么注册的。从17年到现在我一直在听，种类曲风不限。听古典、听流行、听摇滚、听民谣、听乡村、听纯音乐。我在探索自己喜欢的音乐风格，前段时间我列出了自己最近喜欢听的歌，十首，无一不是近一两年听的。以前听过的那些音乐好像被埋葬在脑海深处，没有外部刺激不会主动浮现。

音乐是个奇妙的东西，它能触及人内心最脆弱的部分。它能让人欢欣，也能让人流泪。它能承载人们对过去的回忆。

然而，一个人听是一种体验，和一群人一起听是另外一种体验。以前我都是一个人听，除了在博客写写感受也不会和人分享。现在呢，我有了更多欣赏音乐的方式。我可以去线下，去live、去演唱会，去体会现场。如果你选择去看现场，一定要选择你喜欢的歌手。因为台上的人唱的歌你都不熟悉，你去这个演唱会的意义在哪里呢？

这次演唱会，和[[/posts/eve-ai-shenzhen-2026/][上次艾怡良那场]]，有相似的经历。一开始特别放不开，当周围人要么挥舞手臂，要么跟着一起跳舞时，我就静静地看着。心想：他们难道不累吗？让自己舒服地享受音乐，做一个安静的美男子不好吗:)

后面，当我渐渐进入状态时，我开始唱，跟着鼓点拍手，我发现自己很容易拍对节奏，这让我很受鼓舞。

当前排的人站起来时，后排的我被挡住了视线，不得不也跟着站起来。我感到对后面一排的人很抱歉。因为这是一种强迫行为，如果不这样做就看不到舞台。

所以，为了不对后面的人造成困扰，我只在《你要跳舞吗》这一首歌时站了起来，后面的所有音乐，即使再燥，我能坐着绝对不站着，站着多累啊。

我分到的座位在中间，左右两边都有人，左边的男孩演出前简单聊了一两句，右边的女生在演出开始一小时后才来。

结束的时候，我分别问他们：你享受这次演出吗？

男孩说，还不错，就是还不太放得开。是的，他的状态就好像我[[/posts/first-time-at-a-livehouse/][第一次看演出]]时的状态。整个人很害羞。不太敢大幅舞动，怕尴尬。后面慢慢看的演出多了，就会好的。

女生说，挺好的。我对女生说，你只来了后半段，挺可惜的。

我度过了一个美好的夜晚。
