#+TITLE: 随手记 d
#+DATE: <2022-12-19 Mon 22:20>
#+TAGS[]: 随笔

今天的外卖配送工作，只跑了午高峰，从十点到一点。晚高峰不跑休息一次，但仍然要上线挂时长。这份工作给了继续生存的东西——一张床、一些钱，尽管钱并不多，勉强让我吃饱饭。

谈论是否喜欢做某件事，是太天真的行为或想法，因为现实逼人。一件事，即便你不喜欢，如果它能让你有一定收入，足够自己生存，你就没有理由停止。一件事，即便喜欢得不行，也无法整天都做，因为现实中还有其他事情要考虑。

最近脑子里闪烁了太多内容，我要记下来，梳理一下。

在听过《不明白播客》的几期节目后，我愈发觉得：中国未来的前景将无比黑暗，我这样的普通人将连生存都无比艰难。中国的执政者嘴上为民，实际民在他们眼里狗屁不是。这大概是编程随想博客中“屁民”一词的来源。我认为自己应该开始了解自己的国家，了解它的历史，了解它的政治。

未来的生活不会越来越好，但也要活下去，因为生活本身能够给予我价值，我能够思考，能够阅读，这已足够。

未来政府对民众的控制，只会越来越强，科技在这一方面能够帮助政府更好地控制民众。一个明显的例子，通过健康码变黄变红就能轻易限制一个公民的自由。通过《不明白播客》学到一个词——大数据极权主义，用在这里很贴切。政府广泛收集民众信息，通过收集来的信息数据反制民众。

与庞大的人口数量相比，中国受教育的人太少，在受教育的人群里有自己思考判断的人更少。普通民众只会也只能听从主流媒体意见，而主流媒体全都为政府工作，不愿为政府工作根本活不下去。控制媒体的行为早在建国伊始就已经开始，这是为了宣传自己是为人民服务而作准备的，当然他们也达成目的——让民众相信自己是为他们服务的。但实际上，所谓的“共同富裕”，不过是先让自己人富起来的借口罢了。

以上所写，源自于我的阅读观察体会，更包含我的情绪。

一个人，如何看待自己的国家，自己国家的政府，这对他自己来说很重要。这关系到，他自己的生活。我是很久才意识到这一点，政治曾经离我很远，因为对于现实的困惑与愤怒，我开始关注政治与历史。现实的压抑让我痛苦不堪，学习研究政治与历史，至少能够让我明白自己的痛苦是如何形成的，今后将如何演变。

我的思想还很孱弱，我读的书还不够，经历的事情还不够，思考的深度还不够。未来的路，对我来说，是漫长而又艰辛的。不知道我会在哪里停下来。
