#+TITLE: 巴黎圣母院 Notre-Dame de Paris
#+DATE: <2024-12-22 Sun 23:27>
#+TAGS[]: 音乐剧

八点四十多醒，九点多醒来，洗了开源社送的白色卫衣，洗了工作用的静电衣，喝了口水便出门了。

公交地铁，辗转到东角头地铁站，朋友住在这里，快十点出发，到达时已经十一点多了。在地铁过闸机的位置站着，等朋友下来。他穿着一件长衫，我笑他姗姗来迟。之后到他推荐的港式云吞店吃饭，每人一碗鲜虾云吞面，吃的时候我不住地咬断面条才能吃进嘴里，虾肉饱满，好奇一碗只卖16块店家会不会亏本。不过店很小，只能坐五个人，还是开在小区里面，希望可以继续开下去。

吃完饭，一起去海边闲逛，他说着老板拖欠工资的事情，说着澳洲打工签证被抽中的事情。前者的发生可能会导致他无法继续留在深圳，而后者一件初一看是很幸运的事情，却因为前者和语言学习的问题，可能也无法成行。生活总在我们有所渴望时给我们突然一击，令我们猝不及防。

十二点多了，我担心会迟到，但我又担心自己没有好好陪朋友。于是，在真的快来不及时才提到，要去看音乐剧了。我们开始往回走，我从东角头的B口下去，在14号东部快线上，看着时间分秒度过，我快要迟到了、我迟到了，害怕不能入场，一边安慰自己一边又为自己惋惜。我跟着地图的导航和路人的指引，找到了坪山大剧院的所在。一楼大厅的小哥帮我取票，二楼演出厅外的小姐姐和我说明进场的一些情况，因为迟到了，所以需要在一段音乐结束时才能进场。在门口等待的几分钟，我渐渐平复了因狂奔紧张兴奋而剧烈跳动的心。

看了一会后，那种兴奋劲儿才到来。听到了美人、月等名曲，爱斯梅拉达真的很美，那种女人的魅惑、性感由台上的演员展现出来。卡西莫多“钟楼怪人”，对爱斯梅拉达的爱与自卑，可悲可叹。

上帝啊，你为何如此捉弄人。真心爱着爱斯梅拉达的卡西莫多生而丑陋，道貌岸然的卫队长却是爱斯梅拉达的心属。

卡西莫多抱着爱斯梅拉达的那段特别打动我。流泪了。曲子名为《起舞吧，我的爱斯梅拉达 Danse mon Esmeralda》。

#+BEGIN_QUOTE
Danse mon Esméralda

Chante mon Esméralda

Danse encore un peu pour moi

Je te désire à en mourir

Dans mon Esméralda

Chante mon Esméralda

Laisse moi partir avec toi

Mourir pour toi n'est pas mourir
#+END_QUOTE

旁边坐着一位外国美女姐姐，中文问她这是结束了吗？她回自己不会讲中文。英文问她她回好像是的。还问她是第一次看这个音乐剧吗她回是的。这个姐姐会说法语，最后有个合唱她跟着一起唱了。有点后悔没有提前半小时进场，如果没有迟到那么就有机会和外国姐姐聊天了。在看的过程中，发现她好像在喝什么，我猜测是酒，觉得这位姐姐好酷。

这是我第一次看现场演出的音乐剧，那种声音穿透我身体的力量，我深切地感受到了。我以后还要去看更多现场音乐剧，去享受音乐带给我丰富的情感体验。
