#+TITLE: 考C1机动车驾驶证
#+DATE: <2023-05-17 Wed 08:42>
#+TAGS[]: 随笔

我希望自己在驾驶机动车时，能够为同车人提供安全的体验。当我握着方向盘时，我必须要为乘客的安全负责，一切干扰行车安全的事情都要杜绝。

车只是交通工具，它能把人从A点送到B点，除此之外的其他活动都是多余且危险的。

-----

目前通过情况：

- +科目一+ （考了4次通过）
- +科目二+ （考了1次通过）
- +科目三+ （考了2次通过）
- +科目四+ （考了1次通过）

* 科目一

科目一考的时候，一次预约有2次机会，我是在第二次预约的第4次才及格的。《驾考宝典》App上，科目一有两千多道题目，做完需要时间，做完之后还能停留在短期记忆里也需要时间。最终，我完成了第一步——科目一。

* 科目二

扣了20分：上桥时，右前轮距路边缘线超过30cm未超过50cm；前保险杠未在中间实线处。

科目二考试项目次序：倒车入库（右库、左库）、侧方位停车、曲线行驶、直角转弯、坡道定点与起步。

开始考试前的准备工作：

1. 座椅前后调整到合适（踩离合能使上劲儿，双手前伸能够触碰到方向盘两边的空调出气口）；
2. 座椅高度调整到最低；
3. 座椅靠背调整到垂直；
4. 查看右左后视镜，如果看到后车门把位于后视镜内侧的三分之一处，或者没有偏差过大，就不要调整；
5. 车门关紧；
6. 发现熄火，回空档后再启动；
7. 系上安全带；
8. 刷身份证，感应好拿掉；
9. 准备进入第一项，如果并排两三辆车商量着谁先进项目——倒车入库。

一些提醒：

- 在该停车的地方停车，在不该停车的地方不要停；
- 停车时踩刹车不要松，起步时才松刹车。

** 倒车入库

右倒车入库步骤：

1. 行车至肩膀对线时停车，与边线的距离要调整得大一些；
2. 倒车至与前线重合位置，方向盘右打死（如果第二步骤的实际距离过短，在车库中表现为：距离右边线过近）；
2. 倒车至车库右前角，在后视镜中距副驾门把手距离达预设距离后，方向盘向左旋转一圈；
3. 当右角消失在后视镜中的那一刻时，方向盘右打死；
4. 在左反光镜中，当看到左后角时，方向盘回正，如果车身较斜需要及时调整；
5. 最后，倒车至内边线与来自后视镜角度的视线重合，完成右倒车入库。

倒左库时，为了不让停车时左侧过窄，当后视镜中左后轮与角距离比预设距离稍大时，此时可以右打一圈，之后看车轮是否压过左角延长线，当压过延长线时，方向盘回正，调整入库角度。

** 侧方位停车

侧方位停车时，倒车角消失时等1-2秒再右打死，为了在停好时车头部分的空间稍大些，出侧方车位时不致右车轮压线。

** 曲线行驶

S弯时要向右侧身抬头看右后视镜与车窗夹角下的黄色边线。

** 坡道定点与起步

上桥对线时，身体坐正看外边线，左反光镜对应点超过中间宽线四指。

-----

曾经在 [[https://news.ycombinator.com/][Hacker News]] 上看到过一个人的文章——介绍了发动机的运作原理。经过一番寻找，终于找到——[[https://ciechanow.ski/internal-combustion-engine/][Internal Combustion Engine]]。

这篇文章通过交互式动画的方式，阐述了内燃机——汽车发动机的工作原理。

* 科目三

练习了两天，一共三条考试线路。一共练习了8圈。第一次考试，在最后一项——靠边停车时，当时前面不远处有一辆考试车。在我看到“终点”字样的方形牌时，我以为停在此刻的位置就可以结束了，但实际上还应该前进一些距离，瞄准地面上的白色点，进行停车。

这一次考试，当我遇到前方考试车辆离我很近时，如果我选择踩离合刹车，回空档等待，就可以了。之后，当前面的车离开以后，我再挂一档前进瞄点进行停车。

* 科目四

<2023-08-04 Fri> 这天调休，去考了科四。花了我100块从住处到驾校集合的地方。坐驾校的车还晕车。

考试的时候，不知道要在考场外寄存手机，被问及是否带了手机得到肯定回复后，考官让我下去放手机，我上来又继续考试了。

-----

* 意外的好感

在练习科目二时，认识了女生X，她开朗的性格引起了我的注意，我觉得她是个有趣的人。聊了一些有关大学工作的一些事。想着自己以后可能会和她有交集，于是加了她的微信。

在练习科目三时，我听到了X说自己想谈恋爱，但从大学到现在一直没有谈过，遇不到合适的人。

在从考试场地回到驾校的路上，同车的其他人不知怎么得就聊到了X谈恋爱这件事，具体内容已经记不清了，最后就是他们在起哄，说我和她很合适。听他们说话，我脸很红，觉得不好意思。好在天黑她们看不到我的表情。

聊到这儿，我不仅想到这种可能——了解X，并和她谈恋爱。

于是，我和她说了自己的想法，她表示同意。于是，我们现在正在互相了解对方。

结束了，她对我没感觉。