#+TITLE: 八角笼中 by 王宝强
#+DATE: <2023-07-08 Sat 20:04>
#+TAGS[]: 电影

很久没有到电影院看电影了。电影院里看电影的人还算有素质，少有人说话。IMAX效果不错，这钱花得值，￥60。

喜欢王宝强这部作品。

* 故事情节

向腾辉职业格斗出身，在一次比赛中获得冠军，因尿检阳性被取消冠军资格，他的母亲求领导网开一面，实际上比赛前教练让他吃药。母亲求领导的时候，向腾辉愤怒地殴打教练，导致他入狱多年。

出狱后，他经营一座砂石场，因发不出工资而找人假办格斗俱乐部实则帮助肖央扮演的这个人卖东西。向找到一群半道抢劫的孩子们，让他们到自己的砂石场，开始假戏真做。让他们跑步，击打用沙子做的沙袋。

后来肖央饰演的这个人因为卖假货进监狱，向腾辉找来的这群孩子就没了用处。孩子们想办法留了下来，于是，向开始让他们锻炼、假打，找到一个场地开始假打赚钱。

后来因为假打被曝光，向开始真正让他们进入职业格斗。几年过去了，孩子们长大了，主要角色苏木马虎，开始参加正式比赛，在一次预选赛上其中一人获得冠军。但是，却没有进入正式比赛。因为有人在网络中发布了过去他们假打的视频，让“广大网民”们自以为向在以这些孩子们为主要盈利手段。

之后一部分的情节顺序记不清了。我记一下还记得的情节。向说：喝了这杯酒，我们的缘分就到头了，曲终人散。

苏木和马虎到了新的俱乐部，苏木情绪低落，无心练拳，新俱乐部经理就让他吃药，苏木拒绝了，新俱乐部的人就把他的腿打伤了，马虎为了帮助苏木治伤，又重操旧业ーー半道抢劫。最后，马虎与向见面，知道了事情的原委。

因为合同的缘故，如果苏木和马虎想要获得自由，从新俱乐部离开，就要支付巨额违约金。于是，向想出一个办法：他让入狱的马虎指控自己，引起媒体关注，然后他通过上节目来告诉“广大网民”，如果自己不把他们骗出大山，那么他们就只能一辈子待在大山，骗他们是给了他们一条出路。

电影的高潮，苏木的腿治好了，他开始了一场重要的比赛：比赛全程黑白镜头，我猜测是因为场面太过血腥，怕观众观影不适。

两局，第一局败，第二局胜。格斗是什么，苏木说，格斗就是我们的出路。

* 感想

整部电影，有节奏紧张的部分，也有轻松愉快的部分，既让人流泪又让人发笑。各个部分连接自然，足见王宝强的导演功力。

看这部电影的契机是，著名影评人程青松在首映现场看过《八角笼中》后，想让王宝强把六年前发给他的金扫帚奖还给他。金扫帚奖会颁发给年度最差华语电影。由此可见，程青松对这部作品评价比较高。至少王宝强不必拿今年的金扫帚奖（笑～）。我在大学的时候读过程青松编著的《青春电影手册》，因而对他有了一些印象。

看到故事里讲述的大山里的留守儿童，我不知道真实的境况到底是怎样，但不会比故事里讲述的还要好。没有人引导这些孩子们，怎么能走上正路？如果将来我有能力，想帮帮这些孩子们，让他们能够像我一样，有一个即便不那么出色但也足以自傲的人生。故事里讲述这孩子们的出路，故事外的我也在思考着自己出路。我现在主要工作是地图编辑，任务不重的时候不需要加班，每天工作八小时，待到转正后需要上夜班。每天的工作就是面对着电脑屏幕，完成一条条像服装厂计件一样的任务。每个月能挣到三四千，需要努力一些才能挣到五六千。所以，只做这一份工作是不够的，我还需要接软件项目为自己增加收入。目前就是这样计划的。

电影中不断提及的综合格斗，英文为 mixed martial arts，以下摘自[[https://en.wikipedia.org/wiki/Mixed_martial_arts][维基百科]]：

#+BEGIN_QUOTE
Mixed martial arts (MMA) is a full-contact combat sport based on striking, grappling and ground fighting, incorporating techniques from various combat sports from around the world.

综合格斗（MMA）是一项基于击打、格斗和地面格斗的全接触格斗运动，融合了来自世界各地的各种格斗运动的技术。
#+END_QUOTE

我看了电影，也找了 UFC（Ultimate Fighting Championship，终极格斗锦标赛）视频看，这种运动太过野蛮血腥。我不喜欢看两个人在八角笼里打架，不管使用什么方法，只要把对方打倒就算赢。我在看电影的时候倒是没有表现出来，对于刺激场面的不适感觉。我瞟了一眼右侧的两个姑娘，她俩握着对方的手，看起来好紧张。

我想到《老友记第三季》第18集里莫妮卡第一次遇到的男朋友Peter，他想要成为 UFC 冠军，但是他太菜了，每次比赛都被打得不行。

最后，在记录这段文字的时候，我想到以前看过的王宝强演的电影——《Hello！树先生》、《天下无贼》、《人在囧途》、《人再囧途之泰囧》、《李米的猜想》、《新喜剧之王》、《唐人街探案》系列。天哪，他演的角色跨度真大，是个好演员。
