#+TITLE: 23岁的我，不会玩
#+DATE: <2023-07-14 Fri 06:41>
#+TAGS[]: 随笔

#+BEGIN_QUOTE
且提醒：回忆里的那些故事，离现在的我太过遥远。我已经记不清细节，有些内容是我的想象，如果遇到不符合逻辑的部分，还请见谅。
#+END_QUOTE

在Twitter上看到一个开发者写自己在面试（[[https://twitter.com/shengxj1/status/1678679793175527424][twitter.com]]）前端研发岗时，国内外公司的HR对他截然不同的两种态度。之后看到一个人的回复（[[https://twitter.com/kistovincent/status/1678712205259468803][twitter.com]]），再看到这位开发者的回复（[[https://twitter.com/shengxj1/status/1678713072083677184][twitter.com]]）。

眼泪猛得汇聚在眼眶，一颗一颗滴落在桌子上。我轻声抽噎着，把自己能记住的那些关于“玩”的记忆，一一从脑海中捡拾。

一、

2005年，我5岁。我模糊地记得：自己和一个村庄的小伙伴出去玩，玩到很晚，大人们开始着急、四处寻找我们。后来，我们自己回去了，爷爷打我打得厉害。当然，现在已经不记得有多疼了。

而那年，也是我的奶奶去世的那一年。我偶尔会想，是否因为我而让奶奶过早离世。我已经不记得她的样貌了，所得的零落印象只有来自爷爷的讲述。我是一个没有奶奶的人。

二、

奶奶去世后，我就离开老家去了大连，住在甘井子区鑫境界家园附近，那时还没有楼房有的只是外地人来这里打工住的平房组成的大院。先是在七巧板幼儿园，然后在锦华小学。

大连的小学，每个星期三都只上半天。在某个星期三，和牟宇琦一起去爬墙头。那墙头大概有两三米高，他爬上去了，我不敢爬，不断幻想着自己不小心摔下来、腿受伤的情景。牟宇琦已经在翻墙头上的铁栅栏了，我怕他丢下我，就开始想办法上去。

破旧的柜子帮了我的忙，它斜立在三面墙相交的墙角，地面上杂乱的石块，完美地支撑住了柜子，不让它倒下。我抬起左脚，吃力地放在柜子的最高处，贴着墙慢慢向上移动。右手，能够触碰到墙头的棱角，借着这个支点，左手能够握住铁栅栏与墙头连接的地方。右腿搭在墙头，弯曲着，把左腿拉上来。我跪在墙头上，带着死里逃生的心绪。

喜悦萦绕心间，先前的害怕早已无影踪。

扶着栅栏站起来，看着自己的高度，我又开始害怕了。想赶快翻过栅栏，去栅栏那边的土堆上玩。翻过后，遇到一个日晷样子的石墩，在那里的土堆上玩了很久。

那天，天黑才回到家。我挨了父亲的打，这是几次我记得的父亲打我的回忆之一。

三、

我一直找不到适合我的网络游戏（电脑手机）。学习新事物总是会失败，当我玩游戏时，只要失败个两三次，我就不玩了。游戏不是生活中的其他事物，游戏是可以放弃的娱乐。有些游戏需要的是，和别人协作，而这种是我最不习惯的部分。生活中的我不会主动社交，除非某个人的某个地方吸引我，让我对Ta产生兴趣。游戏中，能单独完成，也就不喜欢和其他人一起完成。而这，往往就成为失败的契机。

我想玩，但苦于金钱的限制，不能像同龄人那样买很贵的东西。玩对我来说，会带给我负罪感。心里的声音会说，你能用这个时间做更有益于你自己的事情。但实际上，即使我不玩，那个时间也会被我无所事事地消耗掉。

我已经不需要游戏带给我的快乐，我的生活里没有它的位置（真的是这样吗）。

我现在的娱乐方式，细细想来，大概分为三种：捣鼓操作系统和系统之上的应用软件，读科幻小说，刷我想看下去的电影或电视剧。如果以后稍微有些钱，可以再加上这个——骑自行车穷游。

-----

玩带来的负罪感，一部分来自父母带来的道德绑架，一部分来自自己对自己的道德绑架。我在努力将这种感觉消除，告诉自己你能够心安理得地玩，这能让你快乐，而让你自己快乐是你的一生里为数不多的关键事物之一。
