#+TITLE: 请大家给我发一封邮件
#+DATE: <2024-05-10 Fri 21:02>
#+TAGS[]: 随笔

读到标题的你应该会好奇，我为什么会有这样的请求？一句话版本，我想请你向我说些鼓励的话，以此来帮助我继续坚持寻找编程相关的工作。

* 背景介绍

我的上份工作于四月底结束，它的主要内容是更新地图应用的道路状态（开通或封闭）。

这种工作经过培训后就可以上手，但要想做好这份工作并不容易，有三点需要注意：

1. 需要对工作中可能遇到的情况有所预判；
2. 我的工作做完，还需要经过两次检查，才会真正生效。这意味着如果我和其他两人的想法不一致（这种情况很常见），就会出现错误，而错误关系到绩效，进而和工资挂钩；
3. 上夜班很痛苦。

我干了十个月，月均四千，这只够我自己花的。

我回到家，父母见我闲了几天，就开始说我，希望我快些挣钱，最好是去汽车厂之类的工厂。对于这种工作，我本能得抗拒，因为我觉得自己一旦进入这种环境，自己就会发生不好的改变，可能会离我喜欢的编程越来越远。

我想象过工厂生活，那种生活并不是我想要的，那么关键问题是：我还有机会从事编程相关工作吗？

父母每日辛苦看在眼里，但心里却不是为他们着想。父亲胳膊三月份动手术现在还没好，依然要出去工作，他是干室内装修的，主要是刮大白。为什么？因为每月要还两千多的房贷。如果他不工作，房贷就还不上，还不上住的地方就没了。母亲几乎每天都要加班到晚上九点，她在服装厂上班。我想的是什么：不想放弃继续学习编程，这是我下一份工作的敲门砖。

关于学习，父母还有个误解：他们认为学习一辈子都学不完，不能现在一直学，要立刻找工作。但我的情况是，基础知识还没掌握，如何能投简历找工作呢？

* 为什么需要你的邮件

“请大家给我发邮件”的想法，是今天的一次灵光乍现。我害怕很多事情，比如，害怕干重体力活、害怕在面对事情背后没有一个人。我希望有人对我说，你可以、没问题、坚持下去。现在的我没有能面对面交谈的朋友，没办法向人诉说我的苦闷，排解我的消极情绪。

当我独自一个人做些事情的时候，我的激情是就是全部的动力，但是激情有消退的时刻。面对现实的时候，光有激情是不够的，还要有承担消极后果的勇气。现在的我在害怕这种消极后果，我需要你来给我勇气，告诉我不用害怕。

你可以写些鼓励的话，非常欢迎你分享自己的想法和故事。

* 一些注意事项

- 在文章的底部，有两种发邮件的方式：
  1. 直接邮件发送，我把邮件主题已经设置好了，你也可以改成自己喜欢的；
  2. 在一个单独的留言框，填好名字、邮箱、想说的话，点击“Send email（发送邮件）”即可。
- 当使用第二种方式时，一定要检查邮箱是否填对了。如果填错了，我可以收到你的邮件，但却没办法回信感谢你了；
- 如果我收到了你的来信，一定会在两天内给你回信，如果没有，有两种可能：我没收到信或我发给你的信你没收到。
