#+TITLE: 哲学的故事
#+DATE: <2022-10-13 Thu 00:05>
#+TAGS[]: 阅读
 
作者是美国的威尔·杜兰特。译者是蒋剑峰、张程程。

这本书能够解答我当前的很多困惑，是一本不可多得的好书。

* 致信

#+BEGIN_QUOTE
致我的妻子

坚强些，我的伴侣……那样我倒下时

你犹能站立；那样我会确信

我破碎的歌曲仍能在你那儿

拥有更优美的旋律；

我将告诉我的心，你正

经过我的抛弃的地方，并掘得更深。
#+END_QUOTE

* 再版序

信息爆炸的时代，知识高度积累，无限延展，各门学科都在向细微处划分。即便穷尽人一生的精力，也不大可能掌握所有知识。正如作者所言：

#+BEGIN_QUOTE
人类掌握的知识已远远超出其理性所能承受的极限。
#+END_QUOTE

学术界把自己封闭在公众视野之外，对于非学术的事情概不热衷，而细分到不同学科之间，彼此相互隔阂，用词只有“圈内人”才能理解，使得知识的普及更加困难。

有一个好老师，能够将学生带进知识海洋，并教学生如何不迷失在知识世界中。

#+BEGIN_QUOTE
在这样一个时期，教师的责任尤为重大，即在“职业学者”与普通民众之间架起一座沟通的桥梁。如同“职业学者”学习大自然的语言，教师应该学习术语，从而将这些职业领域内的知识转化为普通民众熟知的语言和表达形式，打破知识与需求间的隔阂。
#+END_QUOTE

知识如果无法在民众中传播，就会失去生命力，无法在时间中流传。

#+BEGIN_QUOTE
知识若庞杂到无法在民众中普及，则极易沦为经院哲学，甚至演化为民众对权威的盲目迷信；人类也将因此进入对“职业学者”这个新兴牧师群体无限崇拜的新信仰时代，而人类文明借助教育之普及升华自身的希望行将破灭；同时，作为人类文明垄断者的学术阶层，在日新月异的术语、词汇的重重包围下，也将蒙上一层神秘莫测的面纱，彻底与世人隔离，在无形中侵蚀、动摇文明原本坚实的根基。
#+END_QUOTE

#+BEGIN_QUOTE
人类对知识进行人性化改造的历史开始于以“对话”体裁著书立说的柏拉图。
#+END_QUOTE

* 导言：哲学的作用

哲学是否能使人愉悦？

目前，我可能触摸到愉悦的门槛了，因为在阅读这本书的过程中，我能从中找到长久困扰我的问题的答案，这种解惑的喜悦让我继续读下去。我感到一种割裂——思想上的高光时刻与生活中的日日挣扎，或许矛盾才是常态，或许还有更完美的解决办法等待我去探寻。

#+BEGIN_QUOTE
哲学使人愉悦，即使是形而上学的幻景也蕴含诱惑，每个学习者都能体会得到，直到粗粝的生存需求将我们从思想的高峰拽下，抛入生活的撕扯琐碎中。
#+END_QUOTE

是啊，追寻那些美好吧，其他的如果没有跟着到来，也不必惋惜，因为我已经获得了最宝贵的东西。

#+BEGIN_QUOTE
“首先去追求思想中那些美好的内容吧，”培根告诫，“其余的部分即使不是接踵而至，也会在失去时不觉可惜。”
#+END_QUOTE

什么是哲学，什么是科学？威尔·杜兰特给出了自己的解释：

#+BEGIN_QUOTE
科学始于哲学，止于艺术，始于猜测和设想，止于完美的成就。哲学是对未知（譬如形而上学）或不尽知（譬如道德论或政治哲学）的臆想式诠释。

科学是分析式描述，哲学是综合式诠释。科学企图将整体分解为局部，以表达清楚事物的现状和作用、研究事物在现阶段的本质和变化作为自己的目标；哲学结合事实和经历得出意义和价值。
#+END_QUOTE

作者对哲学的分类，以及对应子类的解释：

#+BEGIN_QUOTE
哲学包括以下五门学科：逻辑学、美学、伦理学、政治学和形而上学。

逻辑学探究的是思考与研究的理想方法：观察和内省、推理和归纳、假设和实验、分析和综合——这些人类行为的形式正是逻辑学试图解释和提供指引的领域。

美学研究理想的形式，即美，是艺术的哲学。

伦理学研究理想的行为方式。

政治哲学研究理想的社会组织形式；君主制、贵族制、民主制、社会主义、无政府主义、女权主义——这些都是政治哲学舞台上的角色。

形而上学研究万物的“终极实在”，其中又包括：研究“物质”的真实终极本质的本体论，研究“心灵”的哲学心理学，研究认知过程中“心灵”与“物质”相互关系的认识论。
#+END_QUOTE

为什么女权主义会被纳入政治哲学的范畴？

每个人都是由生到死、由年少到年老，思考变化的过程以及变化的意义和价值，是一件少有人做但值得做的事情。

#+BEGIN_QUOTE
我们有着同样的经历，但未能深入挖掘其中的秘密和隐藏的涵义：我们往往为苍茫现实所迷惑，而忽略了它的弦外之音。
#+END_QUOTE

人人吃饭，人人睡觉；但并非人人都能从生活的琐碎中，感悟出真理。

#+BEGIN_QUOTE
“理智起来吧，”苏格拉底教导克里托道，“不要在意教授哲学的老师是好是坏，你只要思考哲学本身，对她进行细致而公正的研究。假若哲学为恶，那么你应说服所有人远离她；假若哲学确如我所信奉的那样，那么请你追随她并效力于她，而且心甘情愿。”
#+END_QUOTE

* 第一章：柏拉图

智者学派的人士已经讨论过，我们面对的哲学问题了。

#+BEGIN_QUOTE
对于今天我们仍在人类心灵和行为的哲学性探讨中讨论或注释的几乎每一个问题，他们都意识到了、讨论过了。
#+END_QUOTE

能够思考的我们，反思自己时，便能更进一步。

#+BEGIN_QUOTE
唯有当思想者回过头来反思自身时，哲学才有真正的意义。就像苏格拉底所说：认识你自己！
#+END_QUOTE

哲学最初起源于对于物理世界的好奇，为了探究万物的构成，这种思考方式的终点是德谟克利特的唯物论。
