#+TITLE: 哲学的故事
#+DATE: <2022-10-13 Thu 00:05>
#+TAGS[]: 阅读
 
作者是美国的威尔·杜兰特。译者是蒋剑峰、张程程。

这本书能够解答我当前的很多困惑，是一本不可多得的好书。

* 目录

- 再版序
- 致读者
- 导言：哲学的作用
- 一、柏拉图
- 二、亚里士多德和希腊科学
- 三、弗朗西斯·培根
- 四、斯宾诺莎
- 五、伏尔泰和法国启蒙运动
- 六、伊曼努尔·康德和德国唯心主义
- 七、叔本华
- 八、赫伯特·斯宾塞
- 九、弗里德里希·尼采
- 十、现代欧洲哲学家：柏格森、克罗齐和伯特兰·罗素
- 十一、当代美国哲学家：桑塔亚纳、詹姆斯和杜威

* 摘录评论

#+BEGIN_QUOTE
致我的妻子

坚强些，我的伴侣……那样我倒下时

你犹能站立；那样我会确信

我破碎的歌曲仍能在你那儿

拥有更优美的旋律；

我将告诉我的心，你正

经过我的抛弃的地方，并掘得更深。
#+END_QUOTE

#+BEGIN_QUOTE
在这个时代，知识高度积累，无限延展，各个分门别类的学科衍生出更加细致的分支。
#+END_QUOTE

深以为然

#+BEGIN_QUOTE
人类掌握的知识已远远超出其理性所能承受的极限。
#+END_QUOTE

#+BEGIN_QUOTE
如今，科学家“知道的愈来愈多，研究的却愈来愈少”，而哲学家“研究的愈来愈多，知道的愈来愈少”。
#+END_QUOTE

#+BEGIN_QUOTE
每一门学科、每一个哲学流派都在发展中逐渐形成了各自面向“圈内人”的术语体系，于是，随着人们对世界的了解不断增加，向同样受过良好教育的“圈外人”介绍和解释自己所从事和奉献的行业变得愈加困难，横亘在人生与知识之间的沟壑也愈发宽广：统治者无法理解智者的思考，求知者无法理解知者的观点。前所未有的学习热情引发的却是集体性无知的蔓延，无知和愚昧的模范被推选为世界上伟大城池的统治者。
#+END_QUOTE

#+BEGIN_QUOTE
在这样一个时期，教师的责任尤为重大，即在“职业学者”与普通民众之间架起一座沟通的桥梁。如同“职业学者”学习大自然的语言，教师应该学习术语，从而将这些职业领域内的知识转化为普通民众熟知的语言和表达形式，打破知识与需求间的隔阂。
#+END_QUOTE

#+BEGIN_QUOTE
知识若庞杂到无法在民众中普及，则极易沦为经院哲学，甚至演化为民众对权威的盲目迷信；人类也将因此进入对“职业学者”这个新兴牧师群体无限崇拜的新信仰时代，而人类文明借助教育之普及升华自身的希望行将破灭；同时，作为人类文明垄断者的学术阶层，在日新月异的术语、词汇的重重包围下，也将蒙上一层神秘莫测的面纱，彻底与世人隔离，在无形中侵蚀、动摇文明原本坚实的根基。
#+END_QUOTE

#+BEGIN_QUOTE
人类对知识进行人性化改造的历史开始于以“对话”体裁著书立说的柏拉图。
#+END_QUOTE

#+BEGIN_QUOTE
哲学使人愉悦，即使是形而上学的幻景也蕴含诱惑，每个学习者都能体会得到，直到粗粝的生存需求将我们从思想的高峰拽下，抛入生活的撕扯琐碎中。
#+END_QUOTE

#+BEGIN_QUOTE
“首先去追求思想中那些美好的内容吧，”培根告诫，“其余的部分即使不是接踵而至，也会在失去时不觉可惜。”
#+END_QUOTE

#+BEGIN_QUOTE
哲学是对未知或不尽知的臆想式诠释，站在以围堵策略获取真理的最前沿。

科学是分析式描述，哲学是综合式诠释。

哲学家不满足于描述事实，他希望将事实与经历结合起来，从而得出意义和价值；他通过诠释性的综合建立事物间的联系，以一种比以前更好的方式，尝试把被科学家们大卸八块的伟大宇宙重新组装起来。

只有真正的智慧，即在全部经验指导和协调下的思想，才能够告诉我们什么时候该救，什么时候该杀。

对过程的观察、对方法的构建是科学，对目的的批判和协调是哲学。
#+END_QUOTE

#+BEGIN_QUOTE
如今，我们在生存手段和生存工具的发展方面取得的成就远远超过我们对自身理想和目标的诠释和综合，我们的生活充斥着嘈杂和躁动，空洞无聊。
#+END_QUOTE

#+BEGIN_QUOTE
因为不指向欲求的事实毫无意义，不联系目的和整体的事实不可能完备。

没有哲学指导的科学和欠缺眼光及价值的事实无法将我们从大劫难和大绝望中拯救出来。
#+END_QUOTE

#+BEGIN_QUOTE
科学给予我们知识，但唯有哲学赋予我们智慧。
#+END_QUOTE

为什么？

#+BEGIN_QUOTE
哲学包括以下五门学科：逻辑学、美学、伦理学、政治学和形而上学。

逻辑学探究的是思考与研究的理想方法：观察和内省、推理和归纳、假设和实验、分析和综合——这些人类行为的形式正是逻辑学试图解释和提供指引的领域。

美学研究理想的形式，即美，是艺术的哲学。

伦理学研究理想的行为方式。

政治哲学研究理想的社会组织形式；君主制、贵族制、民主制、社会主义、无政府主义、女权主义——这些都是政治哲学舞台上的角色。

形而上学研究万物的“终极实在”，其中又包括：研究“物质”的真实终极本质的本体论，研究“心灵”的哲学心理学，研究认知过程中“心灵”与“物质”相互关系的认识论。
#+END_QUOTE

为什么女权主义会被纳入政治哲学的范畴？

#+BEGIN_QUOTE
我们有着同样的经历，但未能深入挖掘其中的秘密和隐藏的涵义：我们往往为苍茫现实所迷惑，而忽略了它的弦外之音。
#+END_QUOTE

人人吃饭，人人睡觉；但并非人人都能从生活的琐碎中，感悟出真理。

#+BEGIN_QUOTE
“理智起来吧，”苏格拉底教导克里托道，“不要在意教授哲学的老师是好是坏，你只要思考哲学本身，对她进行细致而公正的研究。假若哲学为恶，那么你应说服所有人远离她；假若哲学确如我所信奉的那样，那么请你追随她并效力于她，而且心甘情愿。”
#+END_QUOTE

#+BEGIN_QUOTE
对于今天我们仍在人类心灵和行为的哲学性探讨中讨论或注释的几乎每一个问题，他们都意识到了、讨论过了。
#+END_QUOTE

#+BEGIN_QUOTE
唯有当思想者回过头来反思自身时，哲学才有真正的意义。就像苏格拉底所说：认识你自己！
#+END_QUOTE