#+TITLE: 荐《给阿嬷的情书》
#+DATE: <2026-07-07 Tue 00:13>
#+TAGS[]: 电影

看过电影，时间已经临近十二点，我走在回家的路上，不禁思绪万千。我要说些什么？说与谁听呢？不知道从哪里听来的：表达是有对象的。当我在写这篇文章时，我希望写给谁？

曾经写文章只为我自己，因为我是个怀旧的人，当自己韶华已逝之时，我希望自己有些东西可以缅怀。

如今我发现可以真正分享自己的情绪给对方，让她感受我所感受的、体会我体会的，我觉得这是很美好的事情，我很想永远珍藏这种美好。

年少私奔，木生与淑柔情定终生，新育一女二子，奈时局艰，木生迫而下南洋，颠沛流离，从马来亚至暹罗，十年而已。修路三轮货船，终苦尽甘来时，竟遭歹人害命。可怜淑柔拉扯子女，幸得南枝相助十八载，方得儿孙满堂。

木生去世六十年，淑柔才知道事情原来是这样的——原来是南枝在默默帮助自己啊。

那封封家书，道不尽的纸短情长，情义满溢指尖。

#+BEGIN_QUOTE
吾妻淑柔，展信安康。随信寄两百元，我一切无恙，生意昌顺。行船入夜，恰江上升明月，圆如玉坠，仿若身在故乡，似与你并肩共享。江海万里，心中念你，便不觉遥远。湄南河畔木棉花盛开，像极了家乡的春天，压了一朵在信中，望你也能闻到花香。近来握笔练字，学会了你的名，虽然潦草，努力数日定会成功。纸短情长，伏惟珍重。——夫 木生
#+END_QUOTE

#+BEGIN_QUOTE
木生吾夫，五十元收到。听到要去汕头市区照相，三个小孩高兴得睡不着，天未亮就出门。穿衣服的是大弟，白衣服的是小弟，大妹最聪明，折了飞机和船摆姿势，还叮嘱我一定要把飞机寄给你。想爸爸时，一眨眼就能飞回来。
#+END_QUOTE

#+BEGIN_QUOTE
信件及家用已悉数收到，家中诸事皆顺，庄稼长势尤好，番薯肥美壮实。昨日将其烤作晚餐，孩子们十分喜爱。大弟最馋嘴，半夜抹黑，又偷啃番薯，声响吵醒我们。大妹气得直跺脚，细弟更是严厉，强其开口，务必查明罪证，终于水落石出。不过多时，三人又嬉闹起来，待鸡鸣声响，方才睡去。望你见此，定能感同身受，因这三个可爱的孩子备感幸福。
#+END_QUOTE

书信一来一往，道不尽情深。

片中不乏让人发笑的场景，我记下的有这么一刻：

木生因殴打纵火印度商人入狱，嘱托南枝替自己收债五十港币寄给家里，但并未收够五十。南枝爸拿自己私房钱凑给木生。南枝对爸说：你长大了:)

南枝如姨两人脚踩洗衣的样子真可爱呀！

什么是银信局？银指钱，信即家书，一起来理解就是帮人往家里寄钱和家书的地方。

什么是无米粿？又称韭菜粿，一种潮汕小吃，主要用番薯粉和韭菜制作。外形似饼，分为甜馅和咸馅两种。蒸熟后粿皮呈半透明，可看见里面的馅料。

什么是爱情？爱，对对方之爱，情，对对方之情。情爱者，用心至深也。

那声声情话，诉的是火热的思恋，怨的是不能长久在一起。既然不能相见，就让这情思附着纸上，飘洋过海，代我表达相思。

现在的社会，物质生活太过丰富，人浸在物欲中太久会忘记从哪里来，要到哪里去。时刻需要某些人和事来提醒自己，人生在世最重要的是什么——觅一伴侣，友二三，父母安康，阅天下风景，如此而已。
