#+TITLE: 罗密欧与朱丽叶 Roméo et Juliette (musical)
#+DATE: <2025-11-23 Sun 21:19>
#+TAGS[]: 音乐剧

这部剧刚开始预售的那天，我就买了，而且买了两张，花了一千多。心里想找个女孩一块看，甚至还在网络中找人，最后的确有人和我一起看，只是全然没有了当时幻想的样子。在今天，我想说：找到一个喜欢的人，还是蛮难的。

因为这需要我克服自身的缺点、正视自己，也满怀期待地希望能够遇到这样一个人。没有找到一方面是运气不够好，另一方面还是自己不够努力。自己花多少时间在这上面，我是一清二楚的。

今天和我看剧的女孩子很有趣，笑起来很好看，虽然没有聊几句。为了看清楚台上的人，竟然带了一个小望远镜，出乎我的意料。

-----

什么是爱情？

每个人都有一个自己的答案。而我的答案又是什么呢？关于爱情，关于亲密关系，我到底在渴望什么？我对此的感觉还是很模糊的。说不清楚道不明白。我对于爱情其他没有太多思考，因为从未处过一段关系之中，自然也不知道其中酸甜苦辣。有超出现实层面的憧憬，但也仅此而已。

现实已经压得我喘不过来气，爱情对我来说很奢侈。

我希望自己能够遇到这样一个人，在她面前我不会感到自卑，在她面前我谈笑自如，在她面前我无须伪装。我会遇到这样一个人吗？在读这篇文章的你，你说，我会遇到吗？

观赏这部剧时，前三分之二我都没有太大的情绪起伏，除了听到了熟悉的名曲，比如世界之王、爱，那一刻内心是愉悦的。直到罗密欧之死、朱丽叶之死，那之前的一首首曲子，一次又一次冲击着我的心的曲子，给我的冲击似乎都在那短短的几分钟爆发了。两人相继自杀，这世间容不下这两人的爱情，父辈的仇恨牵连了后代。

如果这世间真有天堂，罗密欧与朱丽叶一定过得很幸福。我这样想着。

悲剧的核心就是事与愿违，你想看团圆结局，作者偏不如你愿。偏偏要创造一些痛苦来刺激人们，让人痛苦，也让人思考。如果一切顺心如意，内心没有敬畏之心，行事便会横行无忌。如果每天过得都是应付，如那寒号鸟一般，过了今天不讲明天。未来人生有什么希望可言？

我需要一个锚点，一个fixed point，不论外界如何变化，我的核心信念不会改变，如果迷失了，再寻回来就好，花不了太多时间。

关于剧中场景，有两点提一下：

1. 当母亲告诉朱丽叶，她必须嫁人时。楼上有真实的两人，楼下仿佛是镜像一般也有两人，处于暗中。我以为这是母亲和朱丽叶的内心的具象。通过动作表演来表达双方的内心挣扎，很是有趣。
2. 死神的舞蹈贯穿剧目始终，是个很特别的存在。死亡阴影一直笼罩在其中，一场悲剧在人死亡的那一刻达到剧情的高潮。

返场曲目我很喜欢，摘录只言片语：

#+BEGIN_QUOTE
Avoir 20 ans, c'est jusqu'au matin

二十当头，通宵悠游

Avoir 20 ans, c'est gratter sur des guitares

二十当头，抱起吉他胡弹乱奏

Refaire le monde même si ça change rien

想改变世界，可世界依旧

Avoir 20 ans, c'est rêver tout haut

二十当头，天真梦想云雾飘游

Nous, on n'a rien du tout

我们，一无所有

La vie devant nous

只有生活在前头

Avoir 20 ans, c'est trembler de peur

二十当头，彷徨无奈

D'oser aimer, d'ouvrir son cœur

谁敢为爱，敞开心怀

Avoir 20 ans, c'est se mettre en colère

二十当头，一腔愤慨

Ne croire en rien mais attendre tout

只信美梦，渴望期待

Avoir 20 ans, c'est rêver tout haut

二十当头，大声梦想
#+END_QUOTE

与诸君共勉
