#+TITLE: Run 7 kilometers, Jupiter at opposition
#+DATE: <2026-01-11 Sun 14:10>
#+TAGS[]: English 随笔 天文

I worked eight hours of overtime yesterday, and didn't want to work any more in the evening because I felt unwell, so I went home and slept from 6 pm to 9 pm. Seeing photos of the starry sky on my WeChat Moments reminded me that I could observe the "Jupiter opposition" phenomenon. So, I put on warm clothes, went downstairs, walked to an open area in a nearby park, lay down on the ground, and held up my binoculars. At first, I couldn't find Jupiter, so I opened a star chart app and found that Jupiter was roughly in the northeast at that time. Through the binoculars, Jupiter appeared as a very bright dot, but because the magnification of the binoculars wasn't high, Jupiter's rings weren't very clear.

I didn't fall asleep until after 2 AM this morning, and woke up after 8 AM. The sun was shining brightly outside, reaching the balcony, so I took out the blankets that hadn't been aired for a few days to dry. I was thinking about whether to go for a run. The reason I wanted to run is because of the marathon next week; if I don't run a long distance, I might not be able to finish the actual marathon. I set my fitness watch to 11 kilometers, but only ran 7 kilometers. My shoes started rubbing my feet while I was running, and when I took them off when I got home, I saw I had a blister on my foot :). I was constantly breathing heavily while running because I haven't run a long distance in a long time. Fortunately, I felt pretty good after the run, but my foot was still hurting because of the blister, so I could only walk a bit and then stop.

While running, I listened to an episode of the podcast "Culture Limited" that talked about some things about Buddhism and mentioned many profound concepts that I don't quite understand yet, but I want to learn more about them.
