#+TITLE: 跑步
#+DATE: <2022-11-12 Sat 15:45>
#+TAGS[]: 他山之石

https://conge.github.io/2022/04/09/ReturnPoint-warming-up/

https://www.douban.com/group/topic/258858314/?\_i=9816887NYOt6Da

（一）我现在跑步感觉腿抬不起来，不做额外的力量训练的话可以吗？单靠跑步本身会提高很慢吗？我一月跑了
90 公里，一次 5 公里，配速几乎没什么提高。

不做额外的力量训练的话可以吗？单靠跑步本身会提高很慢吗？

我现在跑步感觉腿抬不起来，

#+BEGIN_QUOTE
  建议，找人帮你录一下你的跑姿，确认一下你的感觉是不是准。
#+END_QUOTE

不做额外的力量训练的话可以吗？单靠跑步本身会提高很慢吗？

#+BEGIN_QUOTE
  可以是可以，但就像你说的提高会比较慢。人的身体有一个很奇怪的悖论。它不喜欢变化，但一旦你不给它什么变化，它就会“懒”下来。比如，如果你总是用同样的配速和距离去跑步，你的身体就会在适应了这种方式之后，不再提高。似乎，它总是在追求最省力的方式，来完成一件事。所以，要想身体得到锻炼，就得给它施加一些变化的刺激。额外的训练，会有更好的效果。如果只想跑步，也应该在跑步中加入不同的训练方式和训练场景。变速跑，间歇跑，长距离，匀速跑，爬坡，越野，等等。
#+END_QUOTE

我一月跑了 90 公里，一次 5 公里，配速几乎没什么提高。

#+BEGIN_QUOTE
  取决于你跑步水平，如果你刚开始跑步，这样就挺好的。主要是养成习惯。如果你已经跑了三个月以上，不妨增加月跑量，同时，考虑一下上面提到的变速跑和间歇跑。提高自己的摄氧能力。

  我个人跑步，是不追求配速的，我跑步追求的是有恒。我一年大概只会有一两次全力跑五公里。好消息是，我几乎每次的自测，似乎成绩都比上一年有了提升。配速的提升，对于我来说，真的是缓慢的。但，那不是我追求的目标，所以，我也是无所谓的态度。
#+END_QUOTE

（二）怎么保护膝盖

怎么保护膝盖，髌骨带还是护膝，只带髌骨带有用咩

#+BEGIN_QUOTE
  回答这个问题之前，我要先说一下，我自己开始跑步之前就属于偏瘦的体型，也就是说，我的体重负担不大。

  回到保护膝盖上。最根本的原则其实就一个，不超量训练。

  对于髌骨带或护膝之类的保护装备，我的态度是，能不戴就不要戴。

  你可能会说，没有那些保护，我就跑不快，跑不远，完成不了自己跑步的目标。对此我的回答是，你的目标超过了你的身体可承受程度了。跑远了，跑快了，达到你定下的跑步目标了，你就过量了。

  举个关于跑鞋的例子。鞋子是对脚的保护。你想想，如果你不穿鞋，你跑得了 5
  公里吗？以我的经验，如果你用穿鞋跑步的速度，不穿鞋跑，两三公里就给你磨出泡来。很可能，你都承受不了
  1
  公里，就疼的呲牙咧嘴放弃了。再想一下，脚承受不了一上来就两三公里，你凭什么认为你的膝盖能承受
  5 公里？你穿上鞋，把脆弱的脚保护起来，强上 5
  公里，你的膝盖不坏，谁的坏？知道上护膝的人，把膝盖也保护起来。让自己完成本不能承受的跑量，膝盖能不出问题吗？
  我们锻炼的目的，是完成那些跑量还是想要强健的身体？为了完成跑量而把身体的薄弱部分保护起来，是不是本末倒置了？
  为什么这么多人跑步伤膝盖？一大原因就是身体跟不上自己的野心。野心太大，身体就得吃它的亏。所以我说，跑步这事儿，不要求猛。要循序渐进，持之以恒。让身体在他能承受的住的情况下，给它压力和挑战，然后让它恢复。这才是锻炼。

  我个人的跑步装备里，几乎没有保护性的装备。我目前赤脚跑步。我在赤脚跑步之前穿的跑鞋，也都是没有任何而外保护的极简跑鞋。护膝护腕之类的都没有过。我的膝盖，至今也没有出过问题。

  在跑步的时候，我对保护性装备的态度是，如非必要，就不要穿戴。

  最后，重申一遍，保护膝盖的最佳办法，就是不超量锻炼。
#+END_QUOTE

补充一句，如果你的膝盖已经疼了，就要减量或者停跑，给身体充分的休息。

养好之后重新开始跑步的时候，要从一个非常低的水平开始，慢慢的加量，用两到三个月的时间，回复到之前的运动水平。

关节是身体各个部位中，对跑步适应最慢的。而且，各个关节都非常任劳任怨，不善于给人以及时的反馈。哪怕你运动时已经超过了它的负荷许多，它也会默默顶住。直到你停下来休息的时候，它才会向你发出抱怨，让你知道，它们不行了。

所以，自己出发跑步之前，要好好检查自己的关节，做好热身，善待它们。千万别突然加量过大。

（三）身体方面的很明显的改善有哪些呢

就是会得到一个跑者的身体和心态。可以毫不费力的说服自己出去跑步。在自己想要养成新习惯的时候，有充分的信心。

曾国藩说过一句话“一事有恒，万事渐振。”真理。

（四）

1.平均每天的跑量，跑步场景

#+BEGIN_QUOTE
  跑步时间在 10 分钟到 60 分钟之间，距离在一千六百米到 11
  公里之间。跑的最多的距离在 7.5 公里左右，其次是 6
  公里。之所以这样，是因为常去跑步的公园有两个我最喜欢的出口。从一个出口返家事
  7.5 公里，另一个是 6 公里。在公园多跑一圈儿，就多出 5
  公里。所以有时候会跑 11 公里。疫情之前，我跑步上班，也是 7，8
  公里的样子。
#+END_QUOTE

2.楼主喜欢喝咖啡吗 ，怎么看咖啡和运动的关系

#+BEGIN_QUOTE
  曾经喜欢，后来戒掉了。主要是因为，咖啡虽然能让我醒着，但是并不能使我更专注。我对咖啡因比较敏感，对比喝与不喝的感觉，不喝反而更好。我的运动不需要咖啡。
#+END_QUOTE

3.用三个词总结跑步对你来说意味着什么

#+BEGIN_QUOTE
  节制 健康 有恒
#+END_QUOTE

（五）

我给自己定了下限，如果跑了十分钟，或者一英里（1.6
公里），这一天就算跑了。

我还没有受过让我连 10 分钟都跑不了的伤。

病呢，一般的小病，我几乎不得。

但是，我的确生过大病，住院的那种。当然，不是跑步引起的，是我自己的先天病。

生病住院，那就中断了。

中断了就重新开始。

这次的 800 天，其实是我第三次持续跑步的尝试。之前的两次，一次跑到过 1012
天后病了。第二次，是 383 天。

（六）跑前需要做哪些准备活动呢

根据不同的跑步目和自己身体的素质的而不同。

现在的我，是不热身直接跑的。

但刚开始的跑步的时候，是至少也要活动一下脚踝和膝盖才开始跑的，因为除了脚掌之外，关节是跑步新手最容易受伤的地方。活动一下关节，拉伸一下韧带，都是很好的热身。然后，快走几步，再跑。

关于自己的不热身，我多说几句，免得有误解。

我呢跑 5 公里，如果用全力，可以用 19 分钟左右完成。

如果用 5 分配速跑，我可以轻易的跑十几公里。

而我平时跑步，大多数情况下，一是用 30 分钟左右跑 6
公里。也就是说，我不追求成绩：跑的速度和距离，都大大的低于我的极限能力。这种放松跑的情况下，我不特意热身的，跑的前五分钟一般都很慢，是我的热身跑。等身体全热起来之后，再开始增到自己的轻松跑速度。

偶尔，非常少的情况下，我是会测试一下自己的跑步极限，看看自己 5K，10K
可以跑多快。那么在这种跑之前，我是要拉伸一下，跑跑跳跳，慢跑几分钟等等，用作热身。一边热身，一边检查身体的关节肌肉是否活动开了，呼吸是否顺畅，心率是否提高到可以直接开跑的程度，衣服是否舒服，等等。然后才开跑。
