#+TITLE: 海马星球——采访丁红
#+DATE: <2023-02-23 Thu 14:25>
#+TAGS[]: 他山之石

现在这篇采访已经不存在了，即便在其官方网站上也已经找不到了，幸好我已经保存了一份音频，也就有了下面的笔记。

* 在公司睡

不知道自己什么时候会离开，觉得租房子很麻烦，还有无法忍受拥挤的地铁，于是就住在公司。

* 六分战十分

不要给自己设置“根本不存在的限制”。

考试是花多少时间、花多少毅力的问题，不是智商的问题。

雅思只有四分，就敢写简历投世界顶级的大公司。

#+BEGIN_QUOTE
六分战十分：

你的人生永远要找一个只给你打六分的机会去斗。

你的人生总有那么一些事情，那个机会是只给你打六分的，你要拼命争取那个机会。这种机会很值得争。因为失败了，是应该的，本来你就很勉强。但是万一不小心成功了呢？

如果你真的很努力地去争取这个机会，在这一过程中你可以看到自己哪里有不足，慢慢地，你的人生就会朝着你期待的方向前进。
#+END_QUOTE

但是，你不能做那些给你打十分的事情，因为一个机会给你打十分，那这个机会本来就是你的，就看你要不要。

* 选择什么样的朋友

#+BEGIN_QUOTE
同事觉得（丁红的生活方式）奇怪，朋友没有。
#+END_QUOTE

除非你是个没有勇气拒绝你不喜欢的人的人，否则你的朋友们不会对你的行为有什么不满、或是觉得奇怪。

特立独行不一定会受到惩罚，反而可能会收获很多朋友。

选择筛选自己的朋友。每个人都有自己的朋友和敌人。如果非要讨好每个人，那么活该你没有真正的朋友。

* 选择自己的路

当你找到自己的本心，你觉得自己想要这样的生活方式，你想要去做这件事，走在你该走的路上，你就会遇到这条路上和你走同路的人。如果你一直走在你不确定要不要走的路上，那你肯定会遇到一些对你有抵触，你都不知道为什么反对你的那种人。

如果你觉得自己特立独行，那是因为你没有走在自己该走的路上，但凡你走在自己该在的路上，你就会遇到和你走同一条路线上的人，你才会知道那些人是什么样的。你看到那些人，你就会相信：你做的这件事其实没有什么大不了。

* 别人看到你做事的决心时，都会来帮助你

意识到需要给你支持。

* 看重做事的能力，而不是年龄性别

国内的环境已经无法容得下35岁的女性了，没有新西兰的环境对女性友好。

在国内，技术型人才，在30岁后受到的挤压很严重。

* 不消费主义

不能让贫穷限制自己前进的步伐
