#+TITLE: 九月和十月
#+DATE: <2025-10-06 Mon 23:09>
#+TAGS[]: 随笔

现在是晚上十一点钟，刚洗完澡，身上只穿了短裤，背对着风扇吹，希望屁股快点干，我想舒舒服服地坐在椅子上，写这篇文章。戴着耳机听草东没有派对，那灵动的鼓点，让人很难不跟着节奏律动，真棒！

一号的时候，我出去玩儿了，凌晨看到有个画展（印象派150周年），宣传图里有梵高的星空，所以我就去看了，花了88元。中午吃完饭我就去了，到地方是三点多，看完展四点多，很快就过了一遍。那个地方比较小，整个空间像是一条蛇，从入口进出口出。

看着那些曾经见过的、没见过的画，想要找寻能让我共鸣的地方。如果你对艺术感兴趣，可以去了解一下，入口处的小册子尤其重要，因为如果你看完展还不过瘾，小册子上有展览中的全部画作，可以回去好好看个够。

一些特别的画作，我会特别拍下来，想要留个纪念：

1. 女神游乐厅的吧台，马奈作于1882年。一位年轻女子，双手手心朝外，就这样扶着吧台目视前方。她在想什么，为何出现在这里？哇，一连串的好奇，在看这幅画时都会涌现。
2. 睡莲池，莫奈作于1899年。绿意盎然、生机勃勃的一幅画。画里睡莲分着层次，中间点缀一两点粉红。远处的树吹进池中，别有一番风景。
3. 印象・日出，莫奈作于1872年。这一幅如果把彩色转为黑白，那就是一幅中国山水画。所以看到时觉得很是亲切。画笔或重或浅抹上几笔，人啊船啊，水中涟漪啊，也都形象了。
4. 圣维克多山，塞尚作于1902-1906年。这幅吸引我的就是那满眼的绿。绘画手法导致的层次感，构成那些树林，莫名的一种整齐感。
5. 向日葵，梵高作于1889年。梵高最出名的画作之一。注视着这幅画，脑海里想到的第一个词是和谐，像是浑然一体。
6. 自画像，梵高作于1889年。
7. 星月夜，梵高作于1889年。我最喜欢的画作之一。要让我说为什么喜欢，也说不上来，就是莫名的那种感觉而已。

看完画我就坐地铁去海上世界，那里有个想去的酒吧——圣乔治西餐厅。去年和朋友李来过一次，此后就念念不忘，今年也来了。点了一大杯啤酒，一边喝一边看书。背后的乐队在演奏着什么。很喜欢这种感觉。当我离开的时候，人都醉了。只好找个长椅坐下，等了一会儿才离开。

之后，去吃了披萨，不过这次点的有点腻人，不好吃。再然后就打车回家了。

二号到今天六号，一直都在家，也不出去。我做了哪些事情呢？

1. 写了计划但只完成一点点
2. 把这么些年攒的照片整理了一下，相册网站也终于搞定了，对相册的备份也有思路了
3. 写了网站：更新图片Exif数据中ImageDescription属性，这样相册网站上当我点击某张图片时就可以展示相关的描述，而不用单独写文字
4. 写网站：一个小工具，每当我读到一篇文章想记录。就在这个页面输入相应的标题、链接和笔记，然后就可以保存到对应的GitHub仓库文件中
5. 网文永夜君王，看完了剩下的一半。追忆似水年华开始看了
6. 行骗天下韩国版看到最新了，女主好看、剧情搞笑，不比日版差。坂本日常日漫更完，我终于有空看，也就看完了。日漫琉璃的宝石科普矿物的，看完了也算是了解了一些知识吧

假期还剩两天，明后两天想做的事情看看能不能完成三分之一：

1. 捣鼓Emacs
2. 工作上的一些学习资料看一下
3. 做一个机器学习方向的项目，需要软硬件的知识
4. 思考如何使用PVE

上个月22号，从工作了一年多的工厂转岗到总部，还是做硬件测试，但是能够接触的人变多了：硬件工程师、软件工程师和产品经理。我可以学习到更多东西，当然也有很多需要学习。我不怕困难、不怕工作中的各种别扭，我只有一个目标，尽快适应、尽快掌握，让自己真正成长，能够真的帮助到别人。
