#+TITLE: How I read by Slava Akhmechet
#+DATE: <2022-11-14 Mon 15:48>
#+TAGS[]: 他山之石

https://www.spakhm.com/p/how-i-read

每天阅读 40 页，一年就能阅读 20 本书。

#+BEGIN_QUOTE
  Consider: one book gives you more knowledge about a subject than
  almost every other person on the planet, because people don't read.
  Two books on the same subject give you more knowledge than almost any
  reader, because people don't read two books about the same thing. How
  many people who read The Power Broker went on to read a second book
  about Robert Moses?
#+END_QUOTE

当阅读关于同一主题的两本书后，再阅读第三本这一主题的书，能够获得的知识变少了。有一种可以摆脱这种限制的方式。一本书是一个作者的世界观。你只是读者，因此无法改变书的内容。但是你有选择阅读哪一本书的自由。That
means you can stitch together multiple pinhole views into a unique lens
to examine the world. 这种独特视角是通过几本书组合在一起实现的。

例如，通过技术史观察一切。可能组合书单：

-  The Victorian Internet
-  Empires of Light
-  The Wright Brothers
-  The Network
-  Hackers

世界上少有人把这几本书全部读完。即使在硅谷，每个人的生活都依赖于创造新的无处不在的技术，如果你读了这五个，你对于技术如何变得无处不在的理解也将在第
95 个百分点(可能更高)。 You will now be armed with a unique instrument
that few others possess, and assuming twenty books per year, it only
took you three months to acquire.

另一个例子是通过研究寻求连任但失败的美国总统的传记来看美国的历史和失败的动态。There
were ten: John Adams, John Quincy Adams, Martin Van Buren, Benjamin
Harrison, William H. Taft, Herbert Hoover, Gerald Ford, Jimmy Carter,
George H.W. Bush, and now Donald J. Trump. It may be difficult to
stomach ten presidential biographies in a row, but it's doable to read
five. That's enough to pick up a new lens. Another three months; another
sophisticated instrument to examine the world at your disposal.

阅读书籍不要一本一本读，而是要五本一起读。Less than five feel lacking;
more than five gets repetitive. Every cluster has a goal of the form
"study X through Y". Study American history through technological
expansion, or study failure through one term presidents are just a few
examples.

*I try to be creative and make Y unusual*. For instance, everyone likes
to read about presidents who are believed to be successful. A simple
trick is to inverse it and read about unsuccessful ones instead. Or skip
the presidents altogether, and read about vice presidents. It doesn't
matter what Y is because you're trying to study X, and it's more fun to
make Y unusual.

I don't bother diversifying books within a cluster by time period,
cultural or linguistic background of the author, or anything like that.
*I simply try and find the best books on the subject*. Sometimes they
turn out to be diverse along some axes; other times they're homogenous.

I never read forewords or prefaces and always finish every book in a
cluster. I prefer paper to digital, and used books to new ones.

I never take notes or, god forbid, create flashcards. My goal is to suck
the juice out of a book, not to hold on to pieces of the carcass. If I
ever need to remember a specific detail, it's always waiting for me on
the shelf. 不必做笔记，我需要的是领会书中的思想，而不是抱残守缺。

This system gives me four new instruments per year, each capable of
inspecting the world in a different way.
设想一个实验室，实验室中有很多工作台，每个工作台都放着一些与之相关的工具。当我需要解决一个问题时，我就去与之相关的工作台寻找对应的解决办法。

我并不维护要阅读的书单。不提前规划要获得的一系列工具。一旦我读完这一堆书，我会问自己：what
instrument can I add to double the utility of my lab?
另一种方式是把这个问题说出来：what is the most important subject that I
know the least about? It's easy to think of many possible answers to
this question; I then pick the answer that seems the most interesting,
construct a new cluster of five books, and recurse.

Because the instruments are constructed from books, they are endlessly
upgradeable. Sometimes you might choose to upgrade an existing
instrument to increase its power and get higher resolution, rather than
acquire a new one. You can do that one book at a time. To use the
examples above, you can read another book about ubiquitous technology,
or another book about a one term president.

If you organize your reading this way, your bookshelf won't be arranged
by genre like a typical bookstore. Rather than having sections for e.g.
biographies, essays, novels, military history, all sorted by author, you
will instead have sections for addressing different problems, likely
sorted by clusters of books in order that you encountered them. *The
arrangement won't make sense to anyone except you. But you'll be able to
find what you need instantaneously, and your capacity to examine the
world from different perspectives will dramatically increase.*

TL;DR: Read ~40 pages/day, assume 30% failure rate. That's 10k pages and
~20 books annually. Pick a problem, and read clusters of five books to
study that problem from a unique perspective. Visualize each cluster as
an instrument to inspect the world. Collect instruments into a mental
lab, with various stations for related instruments. You can upgrade the
instruments one book at a time. Have your bookshelf reflect this mental
image. Win the decade, not the day. Start now and never stop.
