#+TITLE: Stargazing Diary 241202
#+DATE: <2024-12-03 Tue 00:04>
#+TAGS[]: 随笔 天文 English

Recently, I came across a [[https://neutrino7.top/posts/the-life-of-neutrino-16/][Chinese blog post]] by Neutrino7 where he/she mentioned using binoculars for stargazing. This reignited my long-dormant passion for astronomy, and I immediately emailed hism/her to ask about the specific model he/she used. He/She recommended the BOSMA, then I choose the BOSMA Hunter II 7x50.

Today, the weather was exceptionally clear, perfect for stargazing. Yesterday, I used my binoculars only to see a few stars, but compared to today, that was nothing. At around 10 p.m., I took my binoculars to the rooftop and started scanning the sky. I looked around in all directions, trying to estimate the number of stars in each area. Finally, when I looked straight up, wow! There were so many stars! I felt so happyto see those distant stars, their light reaching my eyes after traveling for countless years.

The view wasn't as spectacular as the countless stars of the Milky Way, but the sheer number of stars was simply overwheming.

I didn't use a star chart to locate constellations yet. I plan to simply observe the sky for a few days and then begin to use a star chart to identity the constellations present.

