#+TITLE: 心的強大，才是真正的強大：許峰源 at TEDxNCCU
#+DATE: <2022-08-28 Sun>
#+TAGS[]: 他山之石", "随笔

- [[https://www.youtube.com/watch?v=5YIT-byVUOY]]
- 周围的人都劝我趁年轻学习，多看书，提升自己，可是我不想怎么办? -
  老君不坏的回答 - 知乎

[[https://www.zhihu.com/question/354919014/answer/906152325]]

从第二个链接找到许峰源先生的演讲视频。

最近这段时间（两个月）努力程度还不够，我慢慢放下了自己的目标，自甘消极。每个人的时间都是一样的，有的人在利用时间让自己成长，有的人在消磨时间无所事事。我最近的心态属于后者，但我不想这样活着。这种活法没有任何意义。

许先生的人生目标是让父母亲过上好日子，所以他为之拼命努力。最终他的父母也都因为自己的儿子而荣耀。尽管许先生的父母先后因为癌症去世，并没有享受多少儿子给他们带来的好日子。

我的人生目标是什么？

其中之一是让父母因为我而感到幸福；另一个便是尽可能多的体验不同的生活，目前是第一种生活------编程者，这是提供经济来源的根本。

- 人生目标是由生到死的跨度；
- 将人生目标分割成以十年为单位；
- 2022 - 2032：在编程方向上，有着深厚的造诣
- 接下来将十年划分为两个五年；
- 2022 - 2027：打基础的阶段，基础包括计算机科学所有主要内容
- 将第一个五年划分为 3 + 2；
- 2022 -
  2025：数据结构和算法->SICP->操作系统->计算机网络->编程语言和编译器

许先生演讲中，最重要的那句话就是标题------ *心的强大，才是真正的强大* 。

每个人看到这句话都有自己的理解，我谈谈自己的想法：所谓「强大」（第二个），不是指能够向他人炫耀的力量的强大，而是一种抗风险能力。每个人未来都会面对各种不确定性，有些能让人幸福，有些让人痛苦，而痛苦的时候是占多数的。痛苦的来源有很多，亲人（父母兄弟姐妹）生病健康受到威胁、自己身体出现问题、因变故导致丧失经济来源，无法恢复到过去的生活。

当面对这些时该怎么办？自己的心态如何调整，如何找到解决办法？

「心的强大」需要锻炼，所以每天运动是必不可少的，至少跑 10 分钟。
