#+TITLE: 知识的幻觉
#+DATE: <2023-07-16 Sun 08:18>
#+TAGS[]: 他山之石

[[https://www.oaktreecapital.com/insights/memo/the-illusion-of-knowledge][The Illusion of Knowledge]] by [[https://en.wikipedia.org/wiki/Howard_Marks_(investor)][Howard Marks (investor) - Wikipedia]]

#+BEGIN_QUOTE
Marks is admired in the investment community for his "memos", which detail his investment strategies and insight into the economy and are posted publicly on the Oaktree website. He has also published 3 books on investing. According to Warren Buffett, "When I see memos from Howard Marks in my mail, they're the first thing I open and read. I always learn something, and that goes double for his book."

马克斯的“备忘录”在投资界广受赞誉，这些备忘录详细介绍了他的投资策略和对经济的洞察力，并公开发布在橡树网站上。他还出版了3本关于投资的书籍。沃伦·巴菲特（Warren Buffett）说：“当我在邮件中看到霍华德·马克斯（Howard Marks）的备忘录时，我会第一时间打开并阅读。我总是能学到一些东西，读他的书可以得到双倍的收获。”
#+END_QUOTE

Howard 想要解释：为什么做出有用的宏观预测如此困难。

* Food for Thought

#+BEGIN_QUOTE
There are two kinds of forecasters: those who don't know, and those who don't know they don't know.

-- John Kenneth Galbraith
#+END_QUOTE

无论是在制造业、学术界，甚至是艺术领域，为了生产出有用的东西，你必须拥有一个可靠的流程，能够将必要的输入转换为需要的输出。Howard 认为，不可能有这样的一个过程，能够持续地将与经济和金融市场相关的大量变量（输入）转化为有用的宏观预测（输出）。

* The Machine

#+BEGIN_QUOTE
The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.

-- Daniel J. Boorstin
#+END_QUOTE

Howard在花旗银行工作到头十年（1969-1979）时，有一个流行词：计量经济学（econometrics）。这种做法是：在经济学数据中找到一种关系，以便对未来进行预测。简单来说，计量经济学关注的是建立一个经济的数学模型。在20世纪70年代有很多有关计量经济学的讨论，到现在21世纪20年代，已经没有这样的声音了。

无论如何，预测者都在根据模型进行判断。根据模型的定义，它含有绝对的逻辑判断，“A发生会导致B发生”。但是，我们在不相信模型的情况下，不可能采用模型的输出。每当Howard想到对一个经济体建模时，他的第一反应便是思考它有多复杂。

例如，美国有大约3.3亿人口，除去最年轻的和最年长的，所有人都是经济的参与者。因此，有数以亿计的消费者，加上数以百万计的工人、生产者和中介（许多人不止一种身份）。为了预测经济发展的路径，你必须预测这些人的行为——即使不是每个参与者，那么至少是群体行为。

如果真的要对美国经济进行模拟，就要处理数以亿计的节点交互，这包含供应商、顾客，以及来自全球的其他市场参与者。真的有可能做到吗？比如，

(a) 如果他们获得了额外收入（什么是边际消费倾向）

(b) 如果能源价格上涨，挤占了其他的家庭预算

(c) 如果一种商品的价格相对与其他商品上涨（是否存在替代效应）

(d) 地缘政治是否受国外政治局势变化的影响

当这些事情发生时，是否有可能预测消费者的行为？

模型只能在既有的思维模式中推导因果，而人的行为是充满不确定性的，是模型不可预测的。消费者之所以购买某件商品可能不是因为价格更便宜，生产商对生产出的产品的定价不一定都由成本决定。

此外，模型必须预测经济中的每一组参与者在各种环境的行为方式。但变化是多方面的。例如，消费者可能在某个时刻一种方式表现，而在另一个类似的时刻以不同的方式表现。鉴于涉及大量变量，两个“相似”时刻似乎不可能以完全相同的方式发挥作用，因此我们将目睹经济参与者的相同行为。除此之外，参与者的行为会受到他们的情绪的影响，而他们的情绪可能受到定性的、非经济发展的影响。如何对这些进行建模？

一个经济模型如何能够足够全面地处理从前从未见过或现代从未见过的事物（在可比较的情况下）？以上是另一个例子，用来说明为什么模型根本无法复制像经济这样复杂的东西。

当然，一个典型例子就是Covid-19大流行。它导致世界大部分经济体停摆，彻底改变了消费者行为，并激发了政府的大规模援助。现有模型能够预测这次大流行的哪些方面影响？

除了复杂性以及捕捉心理波动和动态过程的困难之外，还要考虑一下试图预测某些不可能保持不变的事情所带来的局限性。

Howard引用了文章《[[https://collabfund.com/blog/little-ways-the-world-works/][Little Ways The World Works]]》中与经济模型和预测的讨论相关的两条内容：

#+BEGIN_QUOTE
Stationarity: An assumption that the past is a statistical guide to the future, based on the idea that the big forces that impact a system don’t change over time. If you want to know how tall to build a levee, look at the last 100 years of flood data and assume the next 100 years will be the same. Stationarity is a wonderful, science-based concept that works right up until the moment it doesn’t. It’s a major driver of what matters in economics and politics. “Things that have never happened before happen all the time,” says Stanford professor Scott Sagan.

平稳性：假设过去是对未来的统计指南，基于这样一种观点，即能够影响系统巨大力量不会随着时间的推移而改变。如果你想知道建造堤坝的高度，看看过去100年的洪水数据，然后假设未来100年也是如此。平稳性是一个美妙的，以科学为基础的概念，直到它不起作用的那一刻。它是经济和政治领域的主要驱动力。斯坦福大学教授斯科特•萨根（ScottSagan）表示: “以前从未发生过的事情一直在发生。”
#+END_QUOTE

#+BEGIN_QUOTE
Cromwell’s rule: Never say something cannot occur, or will definitely occur, unless it is logically true (1+1=2). If something has a one-in-a-billion chance of being true, and you interact with billions of things during your lifetime, you are nearly assured to experience some astounding surprises, and should always leave open the possibility of the unthinkable coming true.

克伦威尔定律：永远不要说某事不会发生，或者肯定会发生，除非它在逻辑上是正确的（1 + 1 = 2）。如果一件事情有十亿分之一的机会成为现实，并且你在一生中与数十亿件事情互动，你几乎肯定会经历一些令人震惊的惊喜，并且应该始终保留不可想象的事情成为现实的可能性。
#+END_QUOTE

平稳性在物理科学领域更为常见。例如，由于万有引力定律，在给定大气条件下，物体下落的速度总是确定的。这个数值永远不会改变。但在我们的世界中，很少有过程可以指望是静止的，特别是考虑到心理、情感以及人类行为所扮演的角色，以及它们随时间变化的倾向。

在市场和经济中，几乎没有什么是绝对必须发生或绝对不能发生的。在 Howard 的《周期》（ /Mastering the Market Cycle/ ）一书中，他列出了投资者应该从词汇中清楚的七个术语：“从不”、“总是”、“永远”、“不能”、“不会”、“将会”和“必须”。但如果这些词确实必须被抛弃，那么建立一个能够可靠地预测宏观未来的模型的想法也必须被抛弃。换句话说，在我们的世界里，几乎没有什么是一成不变的。

Howard一连串的追问：

#+BEGIN_QUOTE
Thinking about all the above, can we ever consider a model of an economy to be reliable?  Can a model replicate reality?  Can it describe the millions of participants and their interactions?  Are the processes it attempts to model dependable?  Can the processes be reduced to mathematics?  Can mathematics capture the qualitative nuances of people and their behavior?  Can a model anticipate changes in consumer preferences, changes in the behavior of businesses, and participants’ reactions to innovation?  In other words, can we trust its output?

考虑到上述所有因素，我们是否可以认为经济模型是可靠的？模型可以复制现实吗？它可以描述数百万参与者及其互动吗？它尝试建模的流程可靠吗？这些过程可以简化为数学吗？数学能否捕捉人们及其行为的细微差别？模型能否预测消费者偏好的变化、企业行为的变化以及参与者对创新的反应？换句话说，我们可以相信它的输出吗？
#+END_QUOTE

显然，经济关系并非天然产生，经济也并非由模型产生的示意图预测。当模型不起作用时，准确的预测会凸显出价值。（准确的预测，指的是什么？）

* The Inputs

#+BEGIN_QUOTE
No amount of sophistication is going to allay the fact that all of your knowledgeis about the past and all your decisions are about the future.

-- Ian H. Wilson (former GE executive)
#+END_QUOTE

考虑到一个经济体令人难以置信的复杂性，以及需要作出简化的假设，从而降低任何经济模型的准确性，现在让我们深入了解一下模型所需的输入——预测的原材料。这种大约的输入是否有效？我们对它们的了解是否足以使得最终的预测具有意义？或者我们只是被提醒关于模型的终极真理：“进去的是垃圾，产出的也是垃圾”？显然，预测的质量是基于它的输入原材料的。

以下是Niall Ferguson（尼尔·弗格森）于2022年7月17日在《彭博社评论》上的文章：

#+BEGIN_QUOTE
考虑一下，当我们提出这个问题时，我们隐晦地提出了什么问题：通货膨胀是否已经见顶？我们不仅询问94,000种不同商品、制造业和服务的供求情况。我们还在询问美联储设定的未来利率路径，尽管美联储大肆吹嘘的“前瞻性指引”政策远非确定无疑。我们想知道美元的强势将持续多久，随着美元持续压低美国进口商品的价格。

但还有更多问题。我们还在问，乌克兰战争将持续多久，因为自今年2月俄罗斯入侵乌克兰以来造成的混乱，已显著加剧了能源和食品价格的上涨。我们在问，沙特阿拉伯等产油国是否会回应西方政府关于增加原油产量的请求。

我们或许还应该问问自己，最新的冠状病毒奥密克戎子变体——BA.5对西方劳动力市场会有什么影响。英国的数据表明，BA.5的传染性比其前身BA.2高出35%，而后者又比原始的奥密克戎毒株的传染性高出20%以上。

当你把所有这些变量加到你的模型中，只能祝你和你的模型好运了。事实上，无法确定未来通胀的道路，就像无法确定乌克兰战争和冠状病毒流行病的未来道路一样。
#+END_QUOTE

与尼尔在一个观点不同，Howard认为确定未来通胀的道路要比确定乌克兰战争和冠状病毒流行病更加困难，因为为了确定前者，要把后面两件事以及其他很多事确定好。

Howard在《预测的价值》（ /The Value of Predictions/ ）中对预测过程的粗略描述：

#+BEGIN_QUOTE
我猜想，对大多数基金经理来说，这个过程是这样的：“我预测经济将出现A。如果出现A，利率应该是B，股市应该是C。在这种环境下，表现最好的板块应该是D，股票E应该上涨最多。”在这种情况下预期表现最好的投资选择随后被组合起来。

但是，E股票上涨的可能性有多大？E是以A、B、C和D为条件的。在概率的世界中，三分之二的正确率是极了不起的。但是，如果这五个预测中的每一个都有67%的可能性是正确的，那么有13%的可能性所有五个都将是正确的，那只股票将如预期那样表现。
#+END_QUOTE

基于A、B、C和D的假设来预测事件E，Howard称之为单一情景预测。换句话说，如果关于A、B、C或D的假设被证明是错误的，那么E的预测结果不太可能实现。所有潜在的预测都必须是正确的，这样E才能像预期的那样出现，这是不可能的。如果不考虑

(a) 每个因素的其他可能结果

(b) 这些替代场景的可能性

(c) 如果其中一个成为实际结果，将会发生什么

(d) 对E的影响

任何人都无法进行明智的投资。

弗格森的文章提出了一个关于经济模型的有趣问题：关于经济参与者将在何种宏观环境下运作，我们应该假设什么？这个问题实际就暗示了一个悖论。为了预测经济的整体表现，我们需要对消费者行为作出假设。但是要预测消费者行为，我们不需要对整个经济环境作出假设吗？

Howard在曾经的文章中，提到一次关于冠状病毒讨论，哈佛大学流行病学家马克·利普西奇（Marc Lipsitch）曾说过：

(a) 事实

(b) 根据与其他病毒的类比进行推断

(c) 观点或预测

这是我们处理不确定事件的标准步骤。就经济或市场预测而言，我们有大量的历史和许多类似的过去事件可以推断（但2019冠状病毒并不符合过去这些事件所具备的特征）。但是，即使这些东西被用来作为一个构造良好的预测机器的输入，它们仍然极不可能预测未来。它们可能有用，也可能一无是处。

为了说明这一点，人们经常问我，在我过去经历的周期中，哪一个最像这一个。我的答案是，目前的发展与过去的一些周期有一定的相似性，但没有绝对的相似性。这些差异在每个案例中都意义深远，超过了相似之处。即使我们可以找到一个相同的前期，我们应该在多大程度上依赖于一个样本大小？我觉得没什么。投资者之所以依赖历史参考（以及他们提出的预测） ，是因为他们担心，如果没有历史参考，他们就会盲目行事。但这并不能说明他们是可靠的。

* Unpredictable Influences

#+BEGIN_QUOTE
Forecasts create the mirage that the future is knowable.

-- Peter Bernstein
#+END_QUOTE

如果我们没办法先确定我们的世界是有序的还是随机的，我们就不能考虑预测的合理性。我认为，我们的世界有一些确定的道理，但绝大多数时候都是随机的。

物理世界的规则是简单明了的，但到了经济和市场，就不受自然法则的支配了。

#+BEGIN_QUOTE
The real trouble with this world of ours is not that it is an unreasonable world, nor even that it is a reasonable one.  The commonest kind of trouble is that it is nearly reasonable, but not quite.  Life is not an illogicality; yet it is a trap for logicians.  It looks just a little more mathematical and regular than it is; its exactitude is obvious, but its inexactitude is hidden; its wildness lies in wait.

-- English writer G. K. Chesterton
#+END_QUOTE

*我们不知道将会发生什么，我们不知道市场会对将要发生什么做出什么反应。* 但我们希望将会发生符合自己预期的未来。

* Do Forecasts Add Value?

#+BEGIN_QUOTE
It ain't what you don't know that gets you into trouble. It's what you know for sure that just ain't so.

-- Mark Twain
#+END_QUOTE

尽管缺乏有关其价值的证据，但宏观预测仍在继续。

* Practitioners' Need to Predict

#+BEGIN_QUOTE
Forecasts usually tell us more of the forecaster than of the future.

-- Warren Buffett
#+END_QUOTE

为什么宏观预测的成功率那么低，很多经济领域的人还是在不停地进行预测？

Howard认为原因可能集中在以下几点：

- 这是工作的一部分。
- 投资者总是这么做。
- 我认识的人都这么做，尤其是我的竞争对手。
- 我一直都是这么做的——我现在不能放弃。
- 如果我不这样做，我将无法吸引客户。
- 既然投资包括将资本配置成从未来事件中获益，那么如果没有对未来事件的看法，人们怎么能期望做好工作呢？我们需要预测，即使它们并不完美。

Howard谈到自己读到的一本书——《出现错误（但不是我造成的）》（ /Mistakes Were Made (but Not by Me): Why We Justify Foolish Beliefs, Bad Decisons, and Hurtful Acts/ ）。它的主题是自我辩护。这本书的作者解释，当人们面对新证据，质疑他们之前存在的立场时，“认知失调”就会出现。当这种情况出现时，潜意识机制使他们能够证明并坚持这些立场。以下是精选名言：

#+BEGIN_QUOTE
If you hold a set of beliefs that guide your practice and you learn that some of them are incorrect, you must either admit you were wrong and change your approach or reject the new evidence.

Most people, when directly confronted by evidence that they are wrong, do not change their point of view or plan of action but justify it even more tenaciously.

Once we are invested in a belief and have justified its wisdom, changing our minds is literally hard work.  It’s much easier to slot that new evidence into an existing framework and do the mental justification to keep it there than it is to change the framework.
#+END_QUOTE

人们回应让他们的信念受到质疑时的证据时通常采用的机制包括以下几点：

#+BEGIN_QUOTE
- an unwillingness to heed dissonant information
- selectively remembering parts of their lives, focusing on those parts that support their own points of view
- operating under cognitive biases that ensure people see what they want to see and seek confirmation of what they already believe
#+END_QUOTE

这些都是人们能够持续作出和消费预测的因素之一。在这种情况下，他们肯呢个采取什么特定的形式？

- 将宏观预测视为投资不可或缺的一部分
- 令人愉快地回忆起正确的与蹙额，尤其是那些大胆而不一致的预测
- 高估预测正确的概率
- 忘记或者最小化那些错误的
- 没有记录预测的准确性
- 专注于预测正确所带来的巨额回报
- 说“每个人都这样做”
- 也许最重要的是，将不成功的预测归咎于被随机事件或外部事件打个措手不及

大多数人——即使是出于好意的诚实的人——也会依照自己的利益提出观点，有时会牺牲他人或客观事实。他们不知道自己在做什么；他们认为这是正确的事；他们有大量的理由。

#+BEGIN_QUOTE
Nothing is easier than self-deceit. For what every man wishes, that hs also believes to be true.

-- Demosthenes
#+END_QUOTE

预测者并不是骗子。大多数人是聪明、受到过教育的人，他们认为自己正在做一些有用的事情。但是自我利益使他们以某种方式行事，而自我辩护使他们在面对相反的证据时能够坚持下去。

* Can They or Can't They?

#+BEGIN_QUOTE
I never think about the future - it comes soon enough.

-- Albert Einstein
#+END_QUOTE

事实上，人类在任何特定的时间只能在他们的头脑中记住一些东西。很难考虑到大量的因素，特别是理解大量的事物将如何相互作用（相关性始终是一个难题）。
