#+TITLE: 参加 Maker Faire 深圳 24 的收获
#+DATE: <2024-11-18 Mon 00:55>
#+TAGS[]: 随笔

Maker Faire SZ 24 是一场在深圳南山举办的创客峰会，今年的主题是万物皆可AI。我作为开源社的志愿者参加了这次活动。

走在西丽，并没有感到和其他地方的街巷有何不同。但当我走入楼宇，看到建筑顶部印着一些出名公司的名字时，似乎才意识到：哦，这并不是普通的一处地方，而是众多科技公司的聚集处。

人们在这个地方的工作，影响着中国乃至世界中的很多人。

周六那天，我到达会场时，还没有人到，庞大的地下通道让我迷了路。只得在走过一遍后，重新再走，才找到开源社的展位。

* 开源社是做什么的

我坐在展位前，人来人往，驻足停留的人大都会问我一个问题：你们是做什么的？我没思考过这个问题。开源社存在的意义在哪里？我加入开源社对于我的意义在哪里？

人们刚开始问的时候，我的回答类似于说，我们是一个开源社区，由一群志愿者组成，大家在一起交流技术，开发开源项目。渐渐地，我就能够用自己的话表达了：开源社就是一个社区，社区里的人可以分享自己对于技术的见解和大家互通有无，共同进步。这是一种理想化的表达，现实情况可能是：大多数人是不活跃的，活跃的往往是少数的几个人。

即使是这样也没关系，每个人都有自己生活的关注点，当你关注点在这里时我们欢迎，当你的关注点转移了我们随时等你回来。

* 我来参加活动的目的是什么

当人们不断问我关于“你们是做什么的”之类的问题时，我大多数时候都不知道如何回答。问得多了，心会逃避，开始不耐烦。坐在椅子上，坐立不安，觉得自己不该来这儿。

现在我思考，我来是因为我想见到不一样的人，当人在重复机械的劳动中待久了，会变得迟钝。我想打破这种麻木的感觉，接触新鲜的刺激，让我的心重新火热起来。我觉得这次活动帮助我达成了这一点。我见到很多平时接触不到的新鲜事物，尽管我不一定每一个都感兴趣，但见的多了体会到了人的思考方式的不同。这其实也是一种收获。

我问旁边的深圳DIY的一个人，你来这儿参加活动的目的是什么？他回答：交朋友。多么简单的回答。

这提醒了我，我也是来交朋友的。包括我加入开源社，也是想要认识和自己不同的人，结交朋友。分享我对于事物的看法，了解他人对同样事物的不同，收获更为全面的认知。这或许就是交朋友的意义所在。

* 见过了什么人，有什么思考

和大鹏见了第二次面，第一次见是在北京的开源年会。两个人坐在那里，看着人们走过，好奇地瞧着我们，欲言又止的样子，让人忍俊不禁。大鹏不是第一次参加这个活动，所以一切都显得轻车熟路，把我们的物料拿出来，摆放在桌子上，等待着有缘人。

有位志愿者姓唐，虽然比我大，但长着娃娃脸。有些展位会送“我的世界”人物的折纸，他拿到了两个，组装好后，坐在座位上开始让这两个小人战斗。当我看到这一幕时，不是想他好幼稚，而是想：哇！他好可爱，竟然还保持着童真的快乐。

和Chirs约了见面。认识Chirs是一次偶然的网友见面，之后两人就一起出去玩，彼此聊得来，我很幸运能拥有这样的朋友。带着他逛了逛，和 Seeed 的一个人聊了他们的环境检测产品，又在树莓派的展位逗留了许久。

在树莓派展位，有位法国来的小哥，在和树莓派的人在聊。我出于好奇一直在听，现在想来是不太礼貌的。但当时却没想那么多。只是一直听，看看自己能听懂多少。还好，他们语速不快，我听清了大部分的内容。后来在离开时，还碰到小哥，鼓起勇气约他一起吃饭，但中途接到第二天要考试的消息，无奈只能回学校复习了。

* 和 Chirs 聊天

离开后，我们到一家韩国烤肉店吃饭。饭后在马路边散步聊天。

聊到如何组自己的 Homelab、各自和父母的关系、对于未来的打算以及焦虑的地方。

和朋友来一次这样的、敞开心扉的聊天是很棒的经历。有些话语只有在表达出来后，才能更明白自己在说什么。

我们坐在路边的一处凉亭聊天，马路近在咫尺却没感到吵。月亮一路爬升，在云层之后，忽隐忽现。哦，多么美妙的夜晚。
