#+TITLE: 深圳三月，人间亦三月
#+DATE: <2024-10-14 Mon 23:21>
#+TAGS[]: 随笔

六月三十日到深圳，距今已经三个月多了，这个世界也前进了三个多月。九月的时候就想写这篇，今天才动笔，我真是够拖延的。想着不能这样惯着自己了，于是开始下笔。

一次偶然的工厂投递，让我能够在深圳继续生活。投递的烙铁工，到地方人家说烙铁不缺人，需要一个人做电路板测试。我应了下来。工作是为电池管理系统（一种集成度颇高的电路板，Battery Management System，BMS）进行测试，每天的工作就是这个，一周工作六天，每天都要加班，但下班时间不固定。早的话下过七点半，晚的话十一点才下班。当然这是极端情况，一般情况下会在九点下班，前后误差不过半小时，也就是说，下班时间一般在八点半到九点半。日复一日的这种生活，如果不主动做些事情，寻找意义，人很容易就慢慢麻木了。我做了很多努力，颇有成效，现在分享给你。

* 健康

我一直觉得身体健康是很重要的，只是刚工作身上没钱，没有条件去实践我关于健康的想法。在吃了一个多月外卖之后，我终于有钱租房子了。九月四日从公司的免费宿舍搬进了现在住的地方，房租一个月六百五、水整个楼层均摊、电一块三一度。在信用卡进入新的结算周期后，我就买了锅碗瓢盆等做饭用具，最贵的是一个三百多的志高冰箱。这样我买的肉就不会坏掉。

每天早晨煎两个鸡蛋、吃一份全麦面包、喝二百五十毫升鲜牛奶；中午就炒菜下面条；傍晚喝牛奶吃全麦面包。这就是我正常的饮食规划。

没搬进新家前，早晨的话会煮玉米、喝牛奶；中午就点外卖，炒面炒饭之类的；晚上回出去吃些油大的食物，大饼之类的。在居住条件上，自己搬出来住有了很大改善，至少不会有人半夜一两点打扰我不让我休息。

运动的话只有跑步，这三个月跑步的次数并不多，但是不会停止跑步。读到 Keep 提供的健康报告，发现体重下降了但体脂下降并不明显，我的基础代谢偏低需要改善。跑步是一个颇费精力的运动方式，如果我晚上九点半以后下班，我很难有意愿去离住处不近的森林公园跑步。我开始想到，可以选择一些能够在室内进行的运动，比如跳绳、波比跳等。设计一些简单的动作，让自己很容易就坚持下去。

* 技术

我很明显感觉到，生活中技术的占比大幅下降了。因为工作占据了大部分时间，只有少的可怜的时间用于研究技术。即使时间如此之少，我还是做成了不少事情的：

- 参加了 VueConf 2024，见到了一些人，聊了一些天
- 学习了 C 语言基础
- 更新了 read 的一些内容
- 把博客的样式从 Sass 换成了 TailwindCSS

这么一列，感觉有点少哈。不过我还是很高兴占据能做成这几件事的。

最近刚办电信三百兆宽带，想着把这高速互联网给利用起来，就想到了 Homelab，以后会分出部分精力来研究这些东西，做些分享。

* 思维

我是认真地在生活的，我不想让自己变得麻木，不知道体会生命带来的美好。我的生活和你的生活肯定是不一样的，我不会羡慕你的生活，你也不会羡慕我的。我只是在我的时间线上，笔直地前进而已。

我觉得自己很棒，即使生活在工作占据大部分时间的环境里，我也没有妥协。我积极地寻求改变，改变自己的思考方式，学习他人的优点。

这个世界不是我掌控的，你不是我掌控的，我自己有时候也掌控不了自己。

作为一个喜欢控制的人，我不太能习惯这种无法掌控的情况。我不是老友记里的Monica，我不会对自己的生活中鸡毛蒜皮的小事斤斤计较，但我渴望看到自己的变化，变得更像自己理想中的自己。在变好的每一刻，我都是幸福的。

我努力在我能控制的范围里，为自己营造舒适的氛围，让自己快乐地改变。但有些时刻，我是那么地想要逃避一些事，当然我也真的逃避了。这没关系，我不必每件事都积极地完成，挑那些想要做到的事情做就好，别人不会责备我，自己更不会。有些时候，临阵脱逃不见得对自己有坏处。

Tiny Habits（福格行为模型）里提到的微习惯方法，对我来说很有效。每天做到一件小事，时间长了，大事也能做了。

福格提到，一件事的完成需要完成这件事的动机、能够做到这件事的能力以及恰当的提示。当这三者都满足条件，这件事就会完成。我给自己定的习惯——每天读书5分钟。这是一件我想做到的事情，每天读5分钟太简单了，我告诉自己早晨上班以前读。这个习惯有中断的时候，但当我继续的时候，不会有生疏的感觉，很快就知道该怎么做。

TO BE CONTINUED...
