#+TITLE: 粤语注音字体的使用
#+DATE: <2023-05-10 Wed 16:06>
#+TAGS[]: 技术

[[https://visual-fonts.com/][Visual Fonts – Type Good Pictures]]

在 [[https://news.ycombinator.com/item?id=35867275][HackerNews]] 网站看到这条，觉得新奇，于是进入网站。被美丽的注音字体所吸引，于是想要安装，下载字体后，按照我的 Arch Linux 的 [[https://wiki.archlinux.org/title/Fonts][Wiki]]，新建文件夹 =/usr/local/share/fonts/ttf= ，将字体文件 VF-Cantonese.ttf 放到文件夹中。

使用浏览器插件 Stylebot（或者 Stylus），导入下载文件中的 chrome-stylebot/stylebot_backup.json 文件，打开一个网页：[[https://zh.wikipedia.org/zh-hk/Wikipedia:%E9%A6%96%E9%A1%B5][中文维基百科-香港繁体页]]。如果文件设置的样式不够合适，可以自己调整：

#+BEGIN_SRC css
#mp-2012-body p {
  font-family: "VF Cantonese";
  font-variant: "Jyutping";
  font-size: 4rem;
};
#+END_SRC


之后，即可看到效果

该字体作者在「[[https://visual-fonts.com/canto/canto-why-font/][Why a Font?]]」页的一些话：

#+BEGIN_QUOTE
Local computing have lots of dependencies. Few file format endures through time. Times New Roman from Windows 3.1? It still runs on your machine. One-off purchase of the Cantonese Font provides value for your grand-daughter (or just your future self).
#+END_QUOTE

现在（2023 年）很难找到在古老的 MS-DOS 系统上运行的应用，但是，字体 Times New Roman（发布于 1932 年）跟随着 Windows 3.1（发布于 1992 年）来到大众的视野，三十多年过去了，这个字体依然存在于 Windows 电脑中。字体在某种程度上，比其他应用程序存在的时间更久。

#+BEGIN_QUOTE
Where can you use the Cantonese Visual Font? Use it in your documents, or spreadsheet, or presentation, or graphics design, or 3D animation, or over-ride Chinese text in browsers (with a UserCSS). Use it on screen, use it in print, use it to drive embroidery machines, CNC routers, or 3D printers. Use it to learn, use it to teach, use it to create.
#+END_QUOTE

可以在任何地方使用粤语字体，用它来学习、教学、创造。
