#+TITLE: VueConf CN 2024——Anthony 的开源之路
#+DATE: <2024-07-07 Sun 14:00>
#+TAGS[]: 技术 随笔

按计划应该5:45起床，最后能够在8:00以前到，但实际上6:18才出发，7:03才坐上马安山往车公庙的11号线，8:11到达。计划的时间是根据高德地图给的总时间设定的，但高德的总时间似乎比实际真正所花的时间要多一部分，这为本次行程提供了充裕的时间。即便如此，久不运动的我背着背包，跑完接近2公里的路程，身体吃不消，头有眩晕感。

好在，我最终按时到达，身体也没什么大问题。

* 会议分享

记录了一些东西：

** 勾三股四（赵锦江）——十年

质量好的项目是不需要维护的。（一个极端的说法）

** Eduardo (posva)——数据加载器 - 将 Vue 中的数据获取提升到新高度

保证核心细节的正常加载，不那么重要的部分可以延迟加载。

** Anthony Fu——Anthony 的开源之路：Yak Shaving「薅牛毛」

薅牛毛，用在技术领域是指从一个简单的问题出发，不断对问题的问题产生兴趣，进而为其构建工具的过程。

这种偏离原本目标的结果，本来是负面意义的。

但是Anthony将其用在自己的开源之路上，

- 从自己的需求出发，对问题有更加深入的了解
- 解决自己的问题，也许能够帮助到其他人
- 自己的需求，可能也是别人的需求，通过社区验证想法
- 在社区的推动下进行迭代，完善设计

开源工具发想与实现流程

- 理解问题，考虑可能的解决方案
- 利用已有的工具解决问题，如果工具不够好，可以提建议参与贡献
- 如果现有工具无法满足需要，就要在本地先构建一个最小可执行方案；验证方案可行性；保持接口解耦的想法进行设计；及时回归到要解决的核心问题上来
- 抽离实现成为库；添加简要的文档和动机；开源仓库然后发布包
- 适当的宣传，并收集社区反馈，鼓励写成技术博客
- 交由社区验证
  - 无人问津：解决了自己的问题、总结来解决方案，不错的收获
  - 有人问津：社区参与讨论、报错、贡献；帮助到了别人也帮助到了自己

关于“保持接口解耦”的解释：在设计软件组件时，尽量让它们之间的依赖关系最小化，使得各个组件相互独立、互不影响。

** Evan You 尤雨溪——面向未来的 Vue 和 Vite

Evan 提到：Vue 3.5今年会发布，正在使用Rolldown替代esbuild/Rollup统一开发和生产构建环境，而Rolldown底层依赖的OXC能够极大地提高性能。他表示，希望能为现代前端开发提供统一的、更快的体验。

记了两个Q&A环节的问题：

第一、新人如何推广自己的开源项目

1. 找到问题
2. 写好 README，用清晰准确的语言，描述自己解决的问题
3. 利用社交媒体进行推广

第二、如何提交 PR 才会被更大可能被 Merge

1. 解决 issue 中已经存在的问题
2. 有测试用例
3. 遵循想要贡献的目标仓库的代码风格
4. 改尽可能少的代码，PR的职责要单一，站在reviewer的角度思考问题（换句话说，一个 PR 只能涉及一个特性新增 or BUG 修复）

* 意外之喜——见到Randy Lu

Randy的博客是[[https://lutaonan.com/][lutaonan.com]]。

在X（Twitter）互关蛮久了，在赵锦江老师提到他也来这次会议时，就想着要和他见面。在程序员的圈子里，我们这些首先在网络上认识的人，往往会因为对方的技术或者其他优秀能力而过高地评价对方，而如果没有较高的自尊水平，很容易产生对自身无能的自卑中。如果现实中见了一面，即使只是一面，也会感受到很多。

我明白了，Randy也和大家一样，都是参会的，和我没什么不同。

认识到这一点很重要，因为这给了我信心，让我知道：尽管我可能和Randy没有相似的人生经历，但如果我努力的话，我会慢慢地按自己想要的方式塑造自己的人生。

尽管现实中的压力会让人为了生存而不得不选择苟且，但总有一些空间存在，是留给自己的。

在过程中加到两个人的微信，一个是和我一样来深圳找软件开发工作的湖南小伙，一个是有10年+开发经验的姐姐。在和后者的互相交流中，我觉得自己在当下的环境下无法在短短几天找到工作，为什么会只有几天？因为来深圳带的钱快花完了。所以，我目前的打算是以生存为主，找一份工厂工作，先干着。尽力每天挤出时间学习。

* 其他想法

参加这样的活动，能够见到写出优秀代码的开发者，和他们进行面对面的交谈，这是一件快乐的事情。

当身处在其中，自然地会想：当看到比自己厉害的人，如何正视自己与他们的差距？

我目前的想法是：

#+BEGIN_QUOTE
这要看你关注这些厉害的人的目的是什么，如果你是一个只知抱怨而不行动的人，看着这样的差距时是会退却的，会想着：“人家那么厉害，我追不上的”。

可是，从来没有人要求你一定要和最优秀的那些人一样厉害，只是你自己一厢情愿地许愿似地想：要是我和那些人一样厉害该有多好。

可是，这种情况永远也不会发生。因为不同人的境遇不同，大环境不同，即使相同的选择，在过去所造成的结果和在未来是不同的。

我曾经无数次地想过一些问题：要是我从小学就开始接触电脑有多好、要是我是一几年大学毕业该多好……可惜，历史无法改变。

我能做什么呢？

按照自己的想法，加上大家的建议，慢慢地在开源的道路上前进。我不在乎对方比自己厉害多少倍，因为那对我技术的提升没啥意义。

经过这几年，我慢慢明白了，自己还是蛮喜欢写代码的。
#+END_QUOTE
