#+TITLE: 我想谈恋爱了
#+DATE: <2025-01-02 Thu 23:04>
#+TAGS[]: 随笔
#+DRAFT: true

#+BEGIN_QUOTE
文字是我内心的流露，希望你可以好好读读。
#+END_QUOTE

这篇文章三个月以前就有了写的念头，只是当时觉得不是时候，还需要一段时间酝酿。现在，我觉得是时候了。今年早些时候的某个时刻我告诉自己，今年要谈个女朋友。现在今年快要结束了，女朋友是没有，想谈恋爱的心意总要表达出来，明年继续努力:)

读大学的时候表白过两次被拒，或许是心灰意冷了，没有再鼓起勇气追别人，也没有再遇见能让我心动的女孩。当时觉得自己一个人还好些，只需要考虑自己的感受，做自己喜欢的事情就好了。

我以为自己会一直习惯这种状态，一个人能做很多事。但直到进入九月以后，我突然觉得自己改变了，迫切地渴望一个人能陪在我身边。我遇到了[[/posts/girl-from-work/][一位工作上的女孩]]，对她的感觉让我体会到了什么是恋爱，可惜她已经有男朋友了。内心渴望有这样一个女孩，我们一起读书、一起听歌、一起看电影。两个人在一起有想不到的趣事等着我们去做，生活不再和以前一样都是一个人去做这些事。一个人做这些事情固然很快乐，但两人一起做会获得双倍的快乐。想像美剧《老友记》里钱德勒和莫妮卡那样，幸福地生活在一起。当他们订婚时，钱德勒这样说：

#+BEGIN_QUOTE
我以为开口的时间地点很重要，后来才发现唯一重要的是你。你让我得到超乎想象的幸福。所以如果你愿意，我愿意用下半生，让你跟我一样幸福。
#+END_QUOTE

我想找到这样的女孩，对她说：让你幸福，是我下半生唯一重要的事情。我想对读到文章的女性读者说，如果你读了我的文字，觉得可以认识一下，欢迎写邮件（邮箱是 =i@tianheg.co= ）。我目前住在深圳宝安，做硬件测试。我还有个生活相册站：[[https://img.tianheg.org/][img.tianheg.org]]（点击网址即可打开）。

写这篇文章有两个目的，一个是整理一下自己关于亲密关系的看法，一个是吸引对我感兴趣的异性和我聊天、增加建立亲密关系的可能性。

* 我眼里的爱情

两个人相识，一开始可能小心翼翼地试探，慢慢摸清对方的品性，了解对方的种种习惯。如果好感持续上升，那么彼此的距离会快速拉近，随着时间的渐进，两人越来越无法分离。

开始同居，彼此的生活开始交织在一起，生活的琐碎是一个考验，两个人在一起会怎样处理生活中大小事，如何商量怎么做决定，这些都需要磨合。慢慢的，两人在生活中需要争吵的事情越来越少，生活中的大事小事都能站在对方的角度思考，为对方着想。每天都会觉得自己过得很幸福，因为有这样一个人在身边。我们会逗彼此开心，在对方难过的时候体贴地在一旁陪伴，听对方诉说自己的困扰。
