#+TITLE: 战争、国家与 GitHub
#+DATE: <2023-04-14 Fri 08:13>
#+TAGS[]: 随笔

前两天，我无意间看到 GitHub 网站政策中的一篇文章—— /[[https://docs.github.com/en/site-policy/other-site-policies/github-and-trade-controls][GitHub and Trade Controls]]/ 。

摘录一些对于我来说比较重要的内容：

#+BEGIN_QUOTE
GitHub.com、GitHub Enterprise Server 以及你上传到任意一个产品中的信息可能会受到贸易管制法规的限制，包括美国出口管理条例（EAR）的限制。

GitHub 的愿景是成为全球开发者协作的平台，无论开发者身在何处。我们认真对待审查政府制裁的责任，以确保用户和客户不会受到超出法律要求的影响。这包括保持公共仓库服务的可用性和可访问性，包括那些面向开源项目的服务，以支持涉及受制裁地区开发者的个人通讯。这也意味着 GitHub 将倡导受制裁地区的开发者享有更大的平台访问权，并全面享受全球开源社区的权益。

由于我们与美国监管机构的倡导和努力，GitHub 已经获得了美国财政部外国资产控制办公室（OFAC）的许可，以恢复我们为伊朗的开发人员提供的服务。我们将继续与美国监管机构合作，以获得类似的许可，为其他制裁地区的开发人员提供协作服务，例如叙利亚和克里米亚等地区。我们致力于倡导最广泛的开发者访问，因为我们相信为制裁地区的开发者提供代码协作服务会使全球开发者社区更强大，推动人类进步，并支持美国推广言论自由和信息自由流动的外交政策。

虽然我们已经为您提供了下面的信息以方便您使用 GitHub 的产品和服务，但最终，确保您使用 GitHub 的产品和服务符合所有适用的法律法规，包括美国出口管制法，是您的责任。

用户有责任确保他们在 GitHub.com 上开发和共享的内容符合美国出口管制法，包括 EAR 和美国国际武器贸易条例（ITAR）。在 GitHub.com 提供的云托管服务未经设计来托管受 ITAR 约束的数据，并且目前无法限制特定国家/地区的访问权限。

FAQ:

美国政府对哪些国家和地区进行了制裁？

GitHub 的服务不适用于克里米亚、顿涅茨克和卢甘斯克的分裂地区、古巴、伊朗、朝鲜和叙利亚等地。然而，针对伊朗，GitHub 现在已经获得了美国财政部外国资产控制办公室（OFAC）的许可，可向该国的开发人员提供云服务。GitHub 的云服务（包括免费和付费服务）通常也可供古巴的开发人员使用。

如何定义这些特定用户？

如果 GitHub 确定一个用户或客户位于受到美国贸易管制限制的地区，而 GitHub 尚未获得美国政府的许可，或该用户受到美国经济制裁的限制，那么相关账户将被限制以符合这些法律要求。确定用户和客户位置以实施这些法律限制的依据包括 IP 地址和支付历史等多种来源。国籍和种族不会被用来标记受制裁限制的用户。

受贸易限制的用户是否可以访问私有存储库数据（例如下载或删除存储库数据）？

不幸的是，根据我们对法律的理解，我们没有选项可以允许下载或删除私有存储库内容，除非得到美国政府的授权。我们将与美国监管机构强烈倡导，争取受贸易限制的用户获得保护其私有存储库内容的权利。我们还将为更多制裁市场的开发人员提供 GitHub 服务进行倡导，并进一步强调协作对于全球开发人员支持个人通信的重要性。
#+END_QUOTE

我想起曾经有一个俄罗斯的开发者，似乎就是因为制裁，而无法访问自己的 GitHub 账户，当然也无法下载或删除数据。

如果美国对中国的制裁，涉及到了 GitHub，那么我的账号极可能会被禁止访问——因为我用 PayPal 中国区付过款。

为了这种可能出现的情况，我需要提前做好准备——使用 Gitea 自己建仓库，将最重要的几个仓库在本地 push 的时候就同时推送到 GitHub 和自建 Git 站点。我当然希望美国对中国的制裁不涉及 GitHub，如果那一天真的来临，我已经有所准备。

俄乌战争还没有结束，这个地球的其他地方也遍布着各种冲突。虽然身在和平的中国，我明白：战争会深刻地影响着每个国家的每个人，不论是身体上还是精神上。如果武力收复台湾成为现实，那么大陆的中国人的和平生活的轨迹会被改变。没有人知道下一站会是哪里。

每个人都有自己的信息茧房，它的存在是多方作用的结果，有学校教育、环境影响、自我改变。我没有面对面地见过生活在台湾的人，只是在网络中听到一些台湾人的消息，罗大佑就是在台湾嘛。我也不知道他们心里怎么想，当然说得无情一些，我并不关心。但是，我知道每个人心里都渴望自己的生活幸福。而战争会打破对幸福的渴望，让人们仇恨彼此。

战争会改变我们，我不要战争影响我的生活。

<2023-05-18 Thu> 更新：

在 Twitter 又看到有人提及：GitHub并不可靠。

#+BEGIN_QUOTE
我们不知道 Microsoft 接下来会对 GitHub 做出怎样的更改，但是从 Microsoft 的历史上来看，它是一家有作恶倾向的公司。它曾经对开源世界持有[[https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish][拥抱、扩展再消灭]]的态度，而从近期它和它的伙伴「[[https://news.ycombinator.com/item?id=35163587][ClosedAI]]」的表现来看，Microsoft 似乎走回了老路。

Git 是一个去中心化的版本控制系统。GitHub 将 Git 变成半中心化的，但最终，即使没有 GitHub，你依然可以保存一个属于你自己的 Git 仓库，并将它公开给所有人，或是和人进行代码的交换与合并。这一切并不依赖 GitHub，甚至并不一定需要互联网。

我们唯一能做的，就是现在去备份一份自己存放在 GitHub 上的代码，放到哪里都好：自己的本地、NAS 上、VPS 上、或是其他代码托管平台，给自己多留一条后路。
#+END_QUOTE

参考资料

- [[https://blog.edwardloveall.com/lets-make-sure-github-doesnt-become-the-only-option][Let's Make Sure Github Doesn't Become the only Option]]
- https://twitter.com/baobao1270/status/1658870637514092552 || [[https://josephcz.xyz/log/talk-about-github/][文章]]
