#+SETUPFILE: ./hugo_setup.org
#+TITLE: 2021年10月上旬总结
#+DATE: <2021-10-15 Fri>
今天是 10 月 15 日，10 月上半部分总结的时间。

新开了 38 个 issues，涉及了如下内容：

- 为 GitHub Codespaces 配置 dotfiles
- Docker 镜像制作
- 反诈骗
- Ángeles Alvariño 一位西班牙海洋学家
- 认知偏差
- 21 年诺贝尔奖
- DeepL API
- 为博客选择证书
- KDE 下的蓝牙关闭后无法开启问题
- Wilson Miner - When We Build
- AdGuardHome 屏蔽广告的全平台方案
- 兼职时的失误
- 历史觅迹------费曼
- 现代技术让人变愚蠢
- 技术书卖给谁
- 沟通的两点注意事项
- 限制激发创造性
- 很多问题必须自己想清楚才算数
- 计算机应当辅助人类工作
- 稳定电力的重要性
- 刻意思考与自然思考
- 历史觅迹------沁园春·长沙
- 如何进行线上学习
- 我的问题
- 给我鼓舞的话/故事
- 「归档」页面响应式布局问题
- 换手机
- JavaScript for Beginners Specialization - Coursera
- 包耳式耳机
- uptime-kuma 网站状态监控
- 攻壳机动队 S.A.C.
- 把代码像小说一样进行推荐
- Rebel Without a Cause 无因的反叛
- stormzhang-如何打造个人 IP
- GitHub New Projects
- 来自 Limboy 的一些话
- 2021 年 10 月下旬
- How We Travel

总结一下，我关注了 21 年诺贝尔生物/医学奖的研究成果、找到了自己的博客的
bug、自己正在使用的桌面系统的
bug、一些关于代码的想笔记、使用了新的工具（GitHub New
Projects、Uptime-kuma）、一部《无因的反叛》看了一部分、计划买耳机和换手机、攻壳机动队（早年的两个系列看完了，后来的系列太难）、来自自己和别人的关于沟通/人生等问题的思考。

在这段时间胡思乱想了很多事情，通过写下来希望能理出一些值得继续思考的观点来。

*从食物看选择*

学校有三个主要食堂，我现在只在一个食堂吃饭，时间久了，渐渐地只去一家吃，即使吃腻了也不换。因为选择是一件很麻烦的事情，每天在固定的地点吃固定的饭多好啊。每当我在食堂兼职时，看着那些在菜单面前犹豫的同学，总会在想：他/她会吃什么呢？这是一件蛮有趣的事情，看着他们用手指在菜单上一行行划过，却不点餐，我的心里也很焦急：有那么难以选择吗？不就是吃个饭吗？

由此想到，选择太多并不好。一般以三个为最佳。这是符合我的思维习惯的。

*书应该怎么读和应该读什么书和怎么写读书笔记*

书最简单的就是从头到尾读，另一种则是通过目录了解大意，选择感兴趣的阅读。前者适合喜欢的经典文学作品，不肯错漏一字；后者则适合增进知识、无聊但值得读的书。

书的选择，主要根据自己的兴趣，其次来自朋友、名人的推荐。

我现在的读书笔记，还只是摘录，写几句自己的理解，最后写一个总的感悟。还可以只使用自己的话把书籍中的含义表达出来。

读书越多越发现自己的匮乏，所以也就愈加要读喜欢读，这是一个正向循环。
