#+SETUPFILE: ./hugo_setup.org
#+TITLE: 2021 年终总结
#+DATE: <2022-01-01 Sat>
#+HUGO_TAGS: 年终总结
1. 总结 2021
2. 展望 2022

* 2021

** 关于博客

博客是我记录自己学习和生活的地方。所以，博客的数量某种程度上代表了我学习的广度和对生活的思考。但是，很多博客文章都是写了个开头，草草了事。我很喜欢的一个比喻——蜻蜓点水。这就是我写文章的一个特点。

11 月 20 日那天，开始用 Org Mode[fn:org-mode] 作为博客的基础设施。格式转换工作断断续续地进行，明天就能完成。为什么要用 Org Mode 呢？因为好奇。Emacs 是上世纪就流传的文本编辑器，另一款比较流行的编辑器是 Vim，经常会有人询问 Emacs 和 Vim 哪一个更好用，其实无论是否好用，不到使用的时候根本不知道。Emacs 使用了 2 个月，能够进行文本编辑、记住了几个常用快捷键。我在去年就接触了 Emacs，不过最近两个月才开始真正使用。这是为什么？我认为这就是学习新事物的过程，一个黑箱摆在面前，害怕的同时又很好奇；害怕是因为对自己期待太高，进而担心学不会，好奇就是，想知道这个东西到底是干什么用的，能不能为我所用，提高我的效率？

于是，我开始用 Emacs，自然就了解到基于 Emacs 的 Org Mode。Org Mode 和 Markdown 一样，是一种用于标记文本的文本格式，有自己的语法，能够被导出为 HTML、PDF 等常见格式。学习 Org Mode 的收获，就是你正在阅读的这个博客网站。文章结构全部由自己决定，主题来自 org.css[fn:org-css]。

关于博客的内容，我是一直在改变看法的：

1. 只记录自己的技术笔记，和生活所思
2. 加入阅读书籍、观看电影、听音乐的笔记和感想
3. 加入阅读别人的文章的笔记

博客内容的改变主要集中在究竟是只记录 1,2 还是记录 1,2,3。阅读别人的文章有时是一种美妙的享受，这时会想把自己关于文章的一些理解与评论记录下来，这样能够让自己对文章的理解更深刻，也能让更多人读到好的文章。在这种改变之间，鼓舞我的是 @dirtysalt，他的博客[fn:dirtysalt]只有文字，没有样式。他写的内容既有技术又有生活，既有自己对技术的理解，也有阅读别人好的文章或书籍所记的笔记。

** 关于自我认知

我只挑选一件事来说，通过这件事我想说明自己还不够了解自己。

有一天，从外面回到寝室，在路过别人寝室门口时，看到一个人正在咳嗽，手里拿着烟。我心里想：看吧，这就是抽烟的后果——咳嗽不断，最后可能癌症缠身。我想当然地认为那个人是因为吸烟才咳嗽的，进而觉得这个人真活该。我为什么会有这样的心理？因为我几乎每天都能在走廊里看到有人吸烟，闻到烟味的我认为自己的身体受到了伤害，这种消极情绪长时间积累下来，遇到新的刺激就会爆发。所以，我回到寝室，兴奋地跟室友说，这个人因为抽烟咳嗽，真活该啊。

一个室友回了一句，你这是反社会啊。就像一块正燃烧的木炭，倒上一碗水。心情一下子变得沉闷，也无法继续学习了。我坐在床边，弯腰趴在双腿上，无声地哭了起来，脑子里只有一个词——反社会。这是一个很严重的词，它用在我身上，让我很不安。我那样嘲笑别人，真的不对吗？或许，没有所谓对与错，只是立场不同，观点不同。

张鑫旭在文章《我对知乎前端相关问题的十问十答[fn:1]》中，提到：

#+BEGIN_QUOTE
自我认知带来的好处就是更自信，内心更加强大了，比方说一些说话刻薄的人说你是“变态”，你就大可不必放在心上。
#+END_QUOTE

我为什么会谈到这句话？因为直到今天才明白，我对自己还没有足够的认识，仅凭人家一个「反社会」，就能轻易将我击溃。我曾经的自信似乎是自己的无知营造的假象，我并没有自己想象的那样厉害，我还有很多亟需改变。人在年轻的时候总爱做梦，梦见自己是主角，功成名就；来到现实，却发现自己是无名小卒，微不足道。改变很简单，好好生活。理想不是用来实现的，而是用来追逐的，这是《[[/posts/o-alquimista/][牧羊少年奇幻之旅]]》告诉我的道理。

** 关于工作

「别人都找到工作了，我还没有找到。」、「你已经大四了。再找不到工作怎么办？」

这些是我未曾说出，却潜藏在心里的话。会有很多类人给我压力，我努力把这些压力排解掉，一步一步地朝着既定目标——找到一份前端工程师工作，前进着。学习一遍的内容，会很快忘记，需要再学习一遍；这是一个循环：学习->遗忘->学习->遗忘->学习……直到某一天，再也不会遗忘了。就算任何人都在否定自己，不断地说你不行，你也别放弃，因为他们并不了解你，不知道你内心的渴望。

我进行过[[/posts/first-interview/][一次面试]]，通过这次面试我明白自己还无法胜任公司的工作。通过上文提及的张鑫旭的文章[fn:1]，我明白自己应该花时间学习 JavaScript 基础。

** 关于书影音

读书的话

今年读了毛姆的主要作品：《月亮与六便士》现在已经忘记、《刀锋》则对主人公去印度感受自然的描写，神往异常、《人性的枷锁》讲述了主人公菲利普与两个女人的纠葛。还有上个星期刚读的一本畅销书《克拉拉与太阳》，讨论了未来世界人与人之间的关系是如何影响我们的行为的。

观影的话

看了《你好，李焕英》、《鸟人》、《遗愿清单》、《007》系列、《爱乐之城》、《比海更深（海よりもまだ深く）》、《吉祥如意》、《地球上的星星》

听音

回顾了许嵩的歌，《雅俗共赏》、新专辑《乌鸦》；遇到新歌手王菀之，她的《画意》听得最多。最爱《Life Is Wonderful (Live in Amsterdam)》，Jason Mraz 演唱。

* 2022

接下来的一年，期待自己的成长：

1. 找到属于自己的笃定、自信
2. 找到一份前端工程师工作，并努力为公司创造价值、让自己获得历练

[fn:1] https://www.zhangxinxu.com/wordpress/2017/06/ten-question-about-frontend-zhihu/
[fn:org-mode] https://orgmode.org/
[fn:org-css] https://github.com/gongzhitaao/orgcss
[fn:dirtysalt] https://dirtysalt.github.io/html/blogs.html