#+SETUPFILE: ./hugo_setup.org
#+TITLE: 2021年11月上旬总结
#+DATE: <2021-11-16 Tue>
#+HUGO_TAGS: 总结
11 月前半段主要完成了：

1. 确定两个对自己的要求（最重要），「*自信*」与「*不断问问题*」，前者让我坚信自己，后者我已经具备，因此让我更加自信
2. /Learning How to Learn/ 笔记记录 3
   小节，思考专注与发散思维模式的区别，并应用于自己的学习生活中

- Using the Focused & Diffuse Modes
- What is Learning?
- A Procrastination Preview

3. MDNFE（MDN 的前端开发者教程）完成，对前端的发展历史、Web
   标准有了更多的认识

- Getting started
- Semantics and structure with HTML

4. 阅读《帅张星球算法项目手册》[fn:1]第一小节：递归思维训练，留下初次印象

在哈佛大学教授，泰勒·本·沙哈尔的《积极心理学》课程中，有这样的陈述：

#+begin_quote
  So here is the longitudinal study that was done by John Kotter. John
  Kotter, Professor of Leadership Management, the business school across
  the river, came to Harvard in 1972, joined the faculty and started to
  follow Harvard class, MBA class of 1973 and followed them for 20
  years. And what he waa interested in was to find out all the
  information that he could about this class.

  What he found 20 years later, early 90s, when the study ended, was
  these students were extremely successful. Or ex-students were
  extremely successful, very wealthy, having a lot of impact, whether
  it's on the organization, the community. They did extremely well, but
  within the large group of highly successful Harvard MBAs, he found a
  small group that was extraordinarily successful, more successful than
  the rest of the group, whether it's in terms of income, whether it's
  in terms of impact, whether it's in terms of overall quality of life,
  extraordinarily successful.

  And what he wanted to identify was, why. What distinguish the small
  group from the rest of the pack? Very successful, but not quite as
  successful as that small group.

  And he found only two things. It was not their IQs that made no
  difference what so ever to their long-term success, It was not where
  they came from pre MBA. What they did had nothing to do with it. Two
  and two things alone mattered in terms of determing who will be the
  extraordinarily successful and the rest.

  The first thing was the extraordinarily successful groups *really
  believed in themselves*. They thought they could do well. They were
  driven. They were motivated. They thought "I'm going to make it, I'm
  going to succeed."

  And the second thing that he found, was this group, they were always
  asking questions, they were always at the state of curiosity. Always
  looking up, opening up , wanting to understand the world the more.
  They were life-long learners.
#+end_quote

就是这两种品质------自信和不断地问问题，让我更有动力去做那些让自己更好的事情。

/Learning How to Learn/ 是一门教人如何学习的在线课程。

1. 专注和发散模式是两种不同的思考方式，前者更关注要学习的事物本身，后者则要找到事物之间的更多联系。
2. 睡眠能够让我们的大脑得到休息从而更好地工作。
3. 当你不想做某件事情时，你的大脑会产生痛苦的感觉，为了消除这种痛感，你会选择做那些能让你愉快的事情；但是，经过研究发现，痛苦的感觉只是暂时的，一旦度过那个阶段，你能够获得极大的成就感。

MDNFE（front-end web developer learning
pathway）本阶段了解了互联网的发展历史，其中 Tim Berners-Lee
是核心人物，他创造了 HTML 和
HTTP，前者是网页的骨架，后者是浏览网页的重要协议，协议是双方通信都要遵守的共同约定。互联网发展离不开这些内容，但是为了所有人都能看到大体一致的网页内容，需要开发者组织起来，制定一些标准。这样就形成了各种互联网组织：WHATWG[fn:2]，制定
HTML 标准；ECMA[fn:3]，制定 ECMAScript 标准，它是编程语言 JavaScript
的基础。除此之外，还有很多其他的互联网组织，制定其他应用于互联网的标准。

还学习了如何使用 HTML
插入段落文本、图片、音频和超链接，学习如何让残疾人士更好地理解网页内容，学习如何使用表格整理数据。

《帅张星球算法项目手册》是知识星球「帅张和他的朋友们」的球友 labuladong
写作的算法学习手册，知识星球是一款社群工具，有网页端、app
和微信小程序。我的笔记：

1. 数据结构的存储方式：数组和链表
2. 数据结构的基本操作：增删改查

11 月已经过半，下旬继续努力！

[fn:1] https://labuladong.github.io/zgnb/

[fn:2] https://whatwg.org/

[fn:3] https://www.ecma-international.org/
