#+SETUPFILE: ./hugo_setup.org
#+TITLE: 日志
#+DATE: <2022-04-27 Wed 17:46>
#+HUGO_TAGS: 随笔

今天上午在查找资料，为 [[https://github.com/spencerwooo/onedrive-vercel-index][spencerwooo/onedrive-vercel-index]] 添加一个授权页面；它是一个 Next.js（React.js 框架）应用，我找到了 Next.js 官方文档推荐的 [[https://github.com/nextauthjs/next-auth-example/][nextauthjs/next-auth-example]]，最终成功地运行了这个示例项目——能够通过邮件和 GitHub 授权登陆。我对这一过程进行了简单记录——[[/posts/auth-for-nextjs/][为 Next.js 应用添加授权]]。

我还读了于淼的一篇博客《[[https://yufree.cn/cn/2022/04/24/accent/][口音]]》，从这篇文章里，我获得了一种令我警惕的东西——“情绪化“对自己的影响。”情绪化“，是指不经过推理便视为理所当然的行为。

我是有些情绪化的。在某些事情上，服从主流观点不是件坏事。但是，如果在一些对自己的成长极为重要的事情上，不认真对待，形成的苦果只能自己承担了。

于淼提到”感情脱敏“。结合文章，我的理解是：面对现在这个不确定的社会，自己要能经得起磨砺，不会有人像在学校里那样看待你这个人。做错事要自己承担，后果自己承受。内心脆弱的人不适合面对真实的社会。”微小的事情也可能让自己情绪崩溃“ 这就是内心脆弱的一种表现。

现代社会向儿童描绘了一个美好的未来，但当他们成年后才发现社会的真实。这种欺骗，究竟是为何？为什么不循序渐进地告诉孩子社会的真实与残酷？

一个人，如果物质欲望得到满足，就会开始追名逐利；被过去因物质匮乏而压抑的精神需求需要一个宣泄的出口。

于淼认为”脱敏“的第一步，可以是构建自己的一种应对外界环境的方式——不去在意那些语气助词跟背后的含义，就简单地理解对方想表达什么。通过问询来互相理解表达。另一种对策是隔离情绪化信息源，让自己远离能够产生强烈情绪的信息源。

晚上去操场跑步，用小米手环5记录相关数据，同步到我的跑步网站 [[https://run.tianheg.xyz/][Running]] 上。当我跑完的时候，身体很舒坦，因为一天的大部分时间都坐在电脑前。但当我看手环时，发现没有把这次跑步记录下来。我在跑道上走着，本来想要生气，转而却觉得：这给我一个启发——技术并非 100% 可靠。

如果我太过于依赖技术，我会不那么关注生活中那些真正鲜活的事物。所以，需要在生活和技术之间求得一个平衡。
