#+SETUPFILE: ./hugo_setup.org
#+TITLE: 你是一个有想象力的人吗？
#+DATE: <2019-05-22 Wed>
小时候的那种天马行空的想象似乎不存在了，取而代之的是对未来的焦虑，嗯，是焦虑。这个词挺流行的，大部分青年人都是在焦虑中度过每一天。

此时的想象力似乎并不能够与孩提时期的想象力相提并论。那么，想象力对于我们现在的年轻人来说，还重要吗？

你可能会说：答案肯定是不重要。

现在在这个社会里，你说自己会做 PPT
都有可能比你说自己拥有想象力强。为什么？因为它没用。

这个社会需要的是会各种技能的人才，懂得处理各种职场关系，懂得如何运用好自己手头的资源，懂得为公司谋求最大的利益，只有这样的人才是社会认可的。

这是由这个社会价值体系决定的。那么，想象力对于我来说又意味着什么？

*问*：孩提时代，你用想象力做过哪些发明创造，或是构想过什么奇异的东西吗？

对于孩提时代的故事，记忆里似乎没有那些清晰的细节了，能够拾起的，只是那些零星的碎屑般的东西。

不知道是不是一种悲哀。

觉得自己小时候是很喜欢天马行空的，爱发呆，不多说话，没人打扰时就在那里想，什么都想，往往能从一件很普通的事物，想到很远，想到很荒谬。

*问*：你有因为想象力而被大人嘲笑或是否定过，或者被人支持过吗？

谁都会有这样的经历，每当你准备做一件事情时，周围的人总会用怀疑的口气说，你能行么？这件事这么难以你的能力应该做不好吧。

往往这时候你是比较失落的，因为你已经听到过太多类似的话了。

没有人理解似乎是一种常态，但这其实从小时候就已经体现得淋漓尽致。

小时候的我想象力超级丰富，不论和人讲到什么东西，最后都能和吃扯上关系。

有一次，路过一家服装店，看到衣架上的一件衣服的前面是由冰激凌装饰的，我就问妈妈，妈妈妈妈这件冰激凌能吃吗？我想吃这件冰激凌。妈妈说，你是想吃冰激凌，还是想吃这件衣服？想清楚再问我。

我当时其实在想：为什么不能把衣服做成冰激凌口味的呢？这样我就可以边走边吃了。

就这样，一次想象力的产物就这样终结了。

在小孩子的时候还有很多很搞笑的，但是又很有意义的事情发生。

我曾被大人们嘲笑，也曾被另外一些人支持，不论支持还是嘲笑，都会成为我宝贵的财富。

*问*：长大之后，你做过将想象力甚至是“空想”付诸实施的事吗？

有这个念头，但是总有一些阻碍。能够把想象力亦或是“空想”付诸实施是一件很了不起的事情。这会成为我永远的追求。

想象力是一个好东西，它能带给我们很多好东西。

发现世外桃源的快乐，找寻真理的沉醉，逍遥宇宙的自得。

这些就是好东西，你在其他地方是很难得到的。

尽管想象力的培养需要很多条件，但是我对它并不陌生，我熟知想象力，就如同我们熟知自己一样。

我知道自己最喜欢天马行空了，无论看到什么都会保持一定的好奇心，有些疑问就会寻求帮助，寻求父母的帮助，寻求身边人的帮助。

这种培养，可能到现在我也不知道，会对我以后的发展产生什么样的影响。但是，这种无意识的童年的培养对于我来讲一定是有益的。

可能只有以后我才能知道我这些童年的无意识的培养有多重要。
