#+SETUPFILE: ./hugo_setup.org
#+TITLE: 读《以鸟兽之名》
#+DATE: <2022-07-29 Fri 08:56>
#+HUGO_TAGS: 阅读

6 月 10 号读完的，用的是微信读书。它统计读了4时4分，分成无数次的这些时间。

整本书由三篇小说构成：《以鸟兽之名》、《骑白马者》、《天物墟》。豆瓣简介里有这样一段文字：

#+BEGIN_QUOTE
孙频在《以鸟兽之名》的写作中，把时间、历史和记忆，通过文物、山林、故友等元素巧妙纳入了文本中，进而轻轻打开现代生活中，每一个人的内心，又将它轻轻地掩上。她试图通过人与物、人与时间、人与自我之间关系的梳理，为当下人内心的疑惧、惶惑、漂泊以及追寻，指引一条具有疗愈效果的庇护之路，从而安顿每一个需要成长的我们。
#+END_QUOTE

第一次接触到这本小说集，是在《文化有限》播客上，当时似乎是被他们介绍的《以鸟兽之名》的故事吸引了，想着 2022 年要读一读这本书。于是就加入了今年要读的书里面。

* 摘录

** 以鸟兽之名

#+BEGIN_QUOTE
去年春天，我整个人变得越来越焦虑，失眠也越来越严重，经常半夜的时候赤足在屋子里游荡，或是守在窗前，数着爬进来的月光的脚印。下弦月总是在后半夜才悄无声息地出来，脚印洁净极了。如此一段时间之后，眼看就到了桃花盛开的时节，我决定回一趟老家。
#+END_QUOTE

"我"写不出东西。回家找寻素材。

#+BEGIN_QUOTE
只见这小区孤零零地悬在那个角落里，孱弱瘦小，天外来物一般。
#+END_QUOTE

大足底小区

#+BEGIN_QUOTE
他虽然平素寡言，总像静静潜伏在水面之下，有时候却会忽然从别的什么地方浮出水面，且姿态悠扬，头顶着水草或月光，使他看起来就像只华美的海兽。
#+END_QUOTE

这句话写的是游小龙

#+BEGIN_QUOTE
他办公室里的那点灯光一直压迫着我，我担心他写着写着会忽然变成一只庞然大物，然后绝尘而去。而我则被遗弃在原地，变得越来越颓败平庸，最后彻底淹没在人群里。
#+END_QUOTE

担心被同伴超过

#+BEGIN_QUOTE
他往桌角指了指，下酒菜是一只削了皮的梨。他解释道，花生还得剥皮，粗俗了些，肉食又有味道，不够洁净，不如这雪花梨，清甜干净，配玫瑰汾的花香倒正好。
#+END_QUOTE

#+BEGIN_QUOTE
有一次，我们被派到一个乡镇做捐书活动，在乡政府做完捐书仪式，我看到他顺手把一支放在桌上的圆珠笔装进了自己包里，一支圆珠笔而已，我假装没看见。在回去的路上，他一语不发，只是扭脸看着窗外，脸色有些难看，我以为他是身体不舒服。第二天他请假要再去那个乡镇一趟，因为是个人私事，他坐着城乡公交车，中途又换了一趟公交车，半天时间才到那个乡镇，紧接着又用了半天时间慢慢返回来，等他回来了我们已经下班了。我实在忍不住好奇，在楼道里碰到他时，便问了一句，你又去那乡镇上干吗了？

他看了我一眼，径直从我身边走了过去，这在我的预料之中。我正准备走开时，忽听见他在我身后说，我把那支笔送回去了。我扭脸看着他，他也看着我，他的目光在昏暗的楼道里变得很亮，像刚刚擦拭过一般，语气里也隐隐浮动着一层光亮。他的话猝不及防地就多了起来，他说，昨天我也没有多想，下意识地就把那支笔装进了自己包里，大概是因为觉得它不是什么值钱东西，拿回去也可以用。它确实不是什么值钱东西，可是拿了这支笔，我一夜都没睡着，我必须得把它送回去。

我站在那里，迟疑了片刻才说，其实没有人会在意的，只是一支圆珠笔而已。

他对着我慢慢绽开了一个笑容，同时又满足地叹息道，就是因为只是一支不值钱的圆珠笔，我才必须得送回去。
#+END_QUOTE

我也能如他这般做到对自己诚实吗？

#+BEGIN_QUOTE
我记得有一次，我和他一起坐着公交车去看电影，公交车里挤得水泄不通，连站的地方都没有，又是大夏天，我们身上的衣服很快都湿透了。就在这个时候，我们身边站着的一个女人手里拎着的一桶菜籽油忽然爆炸了，可能是温度太高的缘故，溅出来的油正好喷到了我们两人身上。你猜怎么？那么拥挤的车厢里立刻给我们两人让出了一个圈，我们俩油光满面地站在那个圈里，身上还不停滴着油，一边享受着人群让给我们的某种特权，一边高声谈论着诗歌。下了公交，我们就那么淋着一身油进了电影院，从容看完了电影，又淋着一身油走出电影院，再次上了公交车。我们很油腻、很骄傲地站在别人专门为我们让出的领地里，兴致勃勃地讨论着博格曼和塔可夫斯基，不知不觉就到了学校门口。尽管从不联系，我却时常会想起他，这样风雅的人如今不多了，我心里很仰慕他。
#+END_QUOTE

#+BEGIN_QUOTE
只见他慢慢地笑了，那种笑容打开得很缓慢很用力，散发着金属的味道，简直有点可怕。
#+END_QUOTE

对人笑的描绘

#+BEGIN_QUOTE
众人笑嘻嘻地围观着，并把其中厉害的那个称为是“狮子搏肚”。我吓了一跳，我第一次看到一个词语在我面前现出了形状，就像一个透明的魂魄忽然长出了面目。打闹了一会，其中一个壮汉想去旁边撒尿，还要把另一个也捎上，好有个做伴的。于是两条大汉搭着肩膀嘻嘻哈哈地一起去几米外的地方，解开裤子就撒尿。门口坐着的女人们捡起地上的石子和烂菜叶，一边笑骂一边往他们身上扔。两条大汉也不躲闪，头上顶着烂菜叶，还在比谁的尿程射得更远。
#+END_QUOTE

一个词语的形象描绘；不受城市文明约束的山野文化

#+BEGIN_QUOTE
一个枯瘦的老汉披着一身霞光回头看了看落日，脸上被染得金光闪闪，他长叹了一声，又把一天用完了呵。众人如石像一般，沐浴着晚霞，都久久不动。只消片刻，落日便完全坠入山谷，暮色变得苍茫起来，众人陆续起身，开始慢慢回巢。
#+END_QUOTE

“又把一天用完了”，还剩多少天呢？

#+BEGIN_QUOTE
我忽然打断了他，我说，你为什么一定要用普通话呢？阳关山的方言我也能听得懂，我觉得我们用方言说话，会更自然一点。

他停住了，有些吃惊地看着我，然后又慢慢转头看着一个角落，沉默了很久，他对着那个角落说，我觉得用方言表达一些东西，会给人一种羞耻感，比如我说星空之下人会觉得自己渺小，这样的话就不适合用方言讲出来。还有的话即使用普通话讲出来也还是会觉得羞耻，那就只能用诗，只能用诗把它写出来。其实，我还写了很多诗，不过，这些诗也不是写给人看的，都是写给山里的鸟兽草木看的。
#+END_QUOTE

有些话用不同的语言表达，有着不同的意味与情感

#+BEGIN_QUOTE
她们在绣一堆花红柳绿，鲜艳的颜色浮动在黑压压的人群之上，像一群举止欢快的小孩。
#+END_QUOTE

明亮颜色对比

#+BEGIN_QUOTE
这些女人的手上都戴着闪闪发光的大戒指和大手镯，似乎要把整个家底都披挂出来，再加上那些鲜艳的刺绣，使这群女人看起来个个都富丽堂皇。我后来才意识到，她们把所有的家底披挂在身上，是怕被平原上的人看不起。
#+END_QUOTE

来自山里，搬到平原，自卑

#+BEGIN_QUOTE
在人群的正中间坐着一个瘦小干枯的老汉，戴着一顶灰色的八角帽，穿着半个世纪前的中山装，眼睛浑浊发黄，嘴里叼着一杆一尺多长的黄铜烟枪，烟枪下吊着烟袋，右手上佩戴着一块巨大的手表。
#+END_QUOTE

#+BEGIN_QUOTE
就是在我最接近人群的时候，其实也被放逐在人群之外；然而，就是在那些离人群最远的地方，我却又奇异地走进了他们的最深最暗处。
#+END_QUOTE

即将知道这群人之间隐藏了怎样的秘密

#+BEGIN_QUOTE
我猜想，可能是因为他总是一个人寂寞地在山里开车，早已经习惯了车厢里空无一人。真的拉了几个人，又很快忘掉了车厢里居然还有人，不由得还是会回到空无一人的状态。
#+END_QUOTE

空无一人的状态

#+BEGIN_QUOTE
只听他又说，你不了解他们，你知道他们为什么要拼命去保护一个杀人犯？因为他们知道杀了人是要偿命的，而这样一个杀人犯在大山里的时候，和他们没有什么两样，日出而作，日落而息，每日种地、放羊、采蘑菇，饭市上和大伙一起吃饭一起吹牛，但这样一个人在下山之后却忽然杀了人，变成了杀人犯。他们觉得正是这个杀人犯把他们所有人的苦难都承担下来了，他把所有人即将遭受的磨难承担在了他一个人的肩上，他们觉得他是要替他们去死的，他就像一个全村人献出的祭品。他们对他有一种类似于宗教的感情在里面，所以才拼命要保护他。
#+END_QUOTE

祭品，保护

#+BEGIN_QUOTE
他们是被时代带进大山里的，最后也会被时代带走。你今天看到的城里人的样子，就是以后山民们的样子，他们会被时间慢慢化掉的。你看历史上不管发生过什么，最后都化掉了，慢慢化成了今天；今天的一切也都要化掉的，会化成将来，将来又化成将来的将来。
#+END_QUOTE

#+BEGIN_QUOTE
我已经无法确认眼前的人到底是游小龙还是游小虎了。更重要的是，我发现我其实并不想确认。
#+END_QUOTE

哥哥替弟弟牺牲

** 骑白马者

#+BEGIN_QUOTE
土豆是山民们的主要食物，几乎顿顿不离土豆。
#+END_QUOTE

在《以鸟兽之名》那篇小说里，也提及了这一点

#+BEGIN_QUOTE
我在这山里第一次遇见他的时候，他就是这样，穿着这身旧迷彩服，眼睛一旦盯住什么就半天不动，像压路机一样死命在上面碾压。
#+END_QUOTE

我也有这种习惯，习惯性地注视着东西

** 天物墟

#+BEGIN_QUOTE
此后他就在家里赋闲了一年多，在院子里养了一只八哥，一只狗，天天教那只八哥怎么骂狗，又教狗怎么跳起来恐吓八哥。时间久了，那八哥能说一口极其娴熟的脏话，张口就是，你妈个×。那狗则练出了一身上好的弹跳功夫，一蹦多高，简直像长出了两只翅膀。
#+END_QUOTE

#+BEGIN_QUOTE
我特别喜欢看那些冬天的树，原因之一就是，树叶全部落尽之后，骨骼般的干树枝上却不顾一切地挂着一只小小的鸟窝，像大树在寒天中坦露出了自己的心脏，温柔极了。
#+END_QUOTE

#+BEGIN_QUOTE
那晚，我就住在了父亲曾住过的那间房屋里。我抚摸着父亲留给我的那块玉璧，在烛光里，它散发着一种沁凉的光芒，饕餮花纹神秘悠远。细细端详，便能看到里面有丝丝缕缕的血沁。我想到父亲生前日夜玉不离手，便觉得这也许是父亲的血液已沁入了玉璧。此时把这玉璧捧在手中，竟像是童年时牵着父亲的一只手，那只大手干燥温暖，曾带着我步行几里路去看露天电影；带着我去买图画书和水彩笔；带着我去省城公园里看人家划船。
#+END_QUOTE

#+BEGIN_QUOTE
古代的君子们身上必佩玉，佩玉只有在不快不慢且有节奏的步伐下，才能发出清脆悦耳的声音，时刻提醒君子们一言一行都要温文尔雅、不紧不慢，玉佩撞击的声音也可以显示君子们的光明磊落。
#+END_QUOTE

#+BEGIN_QUOTE
我最讨厌你们见到文物就想它值不值钱。文物的身上留着古人的余温，文物上面的每一道花纹都是古人的感情和寄托。每一件小小的文物背后都是你来我往，是人类早期的文明，是古老的社会制度，它们记录着国家的形成，朝代的更迭，礼仪的教化，这才是文物的价值。
#+END_QUOTE

什么是文物的价值

#+BEGIN_QUOTE
河流在山谷间甩出一个极优美的弧度，岸边的芦苇已经衰败，雪白的芦花在阳光里闪着银光，与枯黄的河柳一起在风中摇曳。
#+END_QUOTE

多美呀

#+BEGIN_QUOTE
这时候我又想起了父亲对我说的最后那句话，抽空回趟老家吧，回去看看。
#+END_QUOTE

#+BEGIN_QUOTE
灶洞里的火烧得通红，不时有火舌从里面吐出来，屋里渐渐暖和起来，我卧在那里，颓然看着窗外无边的夜色。我来到这大山里已经两个多月了，不知道自己还要在这里躲多久，也不知道离开这里后自己还能干什么。我又给自己倒了一杯酒，慢慢喝完了才说，今晚就不写了吧。他端坐在那里，表情威严地说，我像你这个年纪的时候，为了写点东西能熬几个通宵。我接口道，你是阳关山上最厉害的文物专家，可惜被埋没在这大山里了。我和你不一样，我本来就什么都不是，我也不知道自己到底能干什么。

他愣了半晌，说，那你走吧。我一惊，呆在了那里。只见他下了炕，走到门口把门打开了，寒风立刻扑了进来，我的酒意醒了一半，回头一看，他正站在那里看着我，脸上清冷倨傲。他说，你要是想走早就走了，我家里这些文物，你要是想拿也早就拿了，我就是看中你这点品性，有耐性，不贪财。你和我年轻时候还真有点像，我年轻的时候也不知道自己到底是谁，年龄大了就慢慢知道了，总会知道的。
#+END_QUOTE

#+BEGIN_QUOTE
有些事情不是做给别人看的，是做给自己的，自己就会看得起自己。
#+END_QUOTE

#+BEGIN_QUOTE
你以为，真正的高手都在大学里？
#+END_QUOTE

我觉得这是作者发出的嘲讽

#+BEGIN_QUOTE
一个人的出身其实没有那么重要，重要的是，你愿意把自己看成什么。
#+END_QUOTE

我愿意把自己看成什么身份呢
