#+SETUPFILE: ./hugo_setup.org
#+TITLE: 记账 2.4 年
#+DATE: <2022-06-23 Thu 22:53>
#+HUGO_TAGS: 随笔

总结从 2019 年 10 月到 2022 年 3 月的花费情况。如无特别说明，货币种类均为人民币。

* 2022.01-03

三个月共花费 2051.04 元，分类：日常饮食、返校火车票、和妹妹看电影《四海》（123.8）、腾讯云充值（167.83）、域名续费（49）、b站季度会员（45）、买书：JavaScript语言精粹（40.5）、核酸检测（40）、网易云音乐包季会员（30）、得到电子书会员（21）、微信读书包月（19）、付费看《007无暇赴死》（6）、微信豆10个，阅读付费文章、LeetCode训练营。

* 2021.10-12

三个月共花费 3629.4 元，分类：日常饮食、知识星球：「帅张的朋友」（319.2 元）、小米手环5 NFC版（169 元）、少楠《产品沉思录》（159 元）、知识星球「MacTalk的朋友们」（111 元）、回家的火车票（90.5 元）、知识星球：汤质的茶馆（88 元）、寄书（83 元）、一套秋衣秋裤（67 元）、顺丰运显示器回家（65 元）、微信读书季度会员（60 元）、秋季薄毛衣（55 元）、外套（53.9 元）、买梵高星空油画（48.9）、续费网易云音乐会员（45）、续费b站会员（45）、腾讯云账户充值（162）、体检费（40）、走路用的鞋（35.9）、Cloudflare Images$5、、即刻会员（20）、毕业证书拍照（17）、80微信豆阅读小众消息文章《腾讯 Q3 财报简析》（8 元）、得到电子书会员，首月（6）。

* 2021.07-09

三个月共花费 1771.23 元，分类：日常饮食、caoz的小密圈（108 元）、QQ 音乐包季（38 元）、Selfhostedserver 电子书订阅服务(1个月，30 元)、蓝色帆布鞋（23.9 元）、亚马逊 Kindle会员（12 元）、腾讯云账户充值（31 元）、腾讯云轻量应用服务器(1个月，40 元)、火车票（90.5 元）、核酸检测（60 元）、flomo定制T-Shirt（59 元，这是我仅有的两件夏天衣服之一 :-)）、力扣plus会员一个月（49 元）、哔哩哔哩大会员（45 元）、一个短裤（29 元）、树莓派3b外壳+风扇（17.8 元）。

* 2021.04-06

三个月共花费 2831.79 元，消费类别涉及：日常饮食、域名由阿里云转移至NameCheap（124 元）、QQ音乐季度会员（18 元）、哔哩哔哩会员包季（45 元）、买书：JavaScript高级程序设计+JavaScript DOM编程艺术（156.42 元）、遮阳帽（11 元，很少戴，有一天戴出门，同时戴着口罩，被认识的人说像杀人犯，难过了很长时间）、买火车票（90.5 元）、罗洛·梅《人的自我寻求》（35 元）、两种版本的文化苦旅（25.1 元）、无线鼠标（61 元）、首月腾讯视频会员（8 元）、买双跑步用的运动鞋（129 元，这是我自己买的最贵的一双鞋，现在「2022年月」还穿着它跑步）、腾讯云充值、挖财会员（不符合我的使用习惯的记账软件，忘记取消自动续费了，19 元）、白描普通会员终身版（18 元）、网易云音乐会员包季（26.8 元）、无线键盘（75 元，最近刚换，已经用得很油腻了）。

* 2021.01-03

三个月共花费 2135.6 元，消费类别涉及：日常琐碎、一日三餐、去加附近的高铁站报销火车票、赞赏 stormzhang（6.66 元）、赞赏 知识星球 『阿海的圈子』的「一条优秀的鱼」的理财分享（2.33 元）、加入帅张的知识星球（299）、买台灯（57.23 元）、首月开通QQ音乐会员（4.8 元）、剪头（也称理发，10 元）、为了评论明白的星球而赞赏（1 元）、Boss 直聘简历刷新（2 元）、买无线耳机（51.8）、阿里云充值（20 元）、一年的flomo教育版会员（49 元）、高压除尘罐（28 元）、买电子书（英文小妇人、同样没看）、哔哩哔哩会员（14.9 元）、买课本、买书《永隔一江水》（28.62 元）、买双运动鞋（68 元）。

* 2020.10-12

三个月花费 3904.27 元，消费类别涉及：日常琐碎、一日三餐、购买课本（还买错版本了）、买了双鞋（28 元）、买笔记本键盘膜、「hope」app 给一年后的自己写封信（9 元）、e-paper墨水屏，用于树莓派的一个天气显示项目（129.05 元，然而买回来，让它运行一次，就再也没用过了）、赞赏镇守海（1 元）、vultr 服务器充值（10美元，67.28 元）、路由器TL-WDR6500（55 元，本来想装 OpenWRT，但总也装不上）、买 16G 内存（410 元，练习了如何拆惠普笔记本）、买 Kindle 电子书（史蒂夫·乔布斯传，15.79 元，买回来很少读）、加知识星球「caoz的梦呓（180 元）」、买《第一行代码第3版》（73.7 元）、《数据结构与算法之美》极客时间（84 元）、打印自控实验报告（b5，第一次打成A4，因此多付了7元，最终共付 14.8 元）、做核酸检测（11 元）、坐出租车去沈阳北站回家（50 元）。

* 2020.07-09

三个月花费 4326.73 元，消费类别涉及：日常琐碎、一日三餐、报名六级、还钱、交话费、买火车票、买口罩、买树莓派 3b 和电源、HDMI 线、2010 年生产的 Dell 显示器（闲鱼 80 元 + 运费 35 元）、买课本、买阿里云轻量服务器、为了下载 Multisim10 的安装包开通了百度网盘超级会员（25 元）、《姜子牙》电影票（33 元）、域名从腾讯云转入阿里云（69 元）。

* 2020.04-06

三个月花费 473.17 元，消费类别涉及：买菜、话费。此时还没有停止使用花呗。

* 2020.01-03

三个月花费 832.05 元，消费类别涉及：三餐、话费、交通、会员、买电子书和音乐。

* 2019.10-12

三个月花费 2876.88 元，消费类别涉及：三餐、话费、交通、会员（影视、笔记软件、微信读书、百度网盘、滴答清单、智行火车票）、买书（算法导论、代码大全）、日常琐事。
