#+SETUPFILE: ./hugo_setup.org
#+TITLE: 读《寂寞的游戏》
#+DATE: <2022-07-29 Fri 10:45>
#+HUGO_TAGS: 阅读

袁哲生作品，他已离世。

* 摘录

** 寂寞的游戏

#+BEGIN_QUOTE
这个故事一直烙印在我心底，陪伴我成长，像是一则寓言。它描写了一个涉世未深的少年，在一个很偶然的时刻降临时，他很本能、很熟练地走向他生命开始之前（或是结束之后）的那一点去。
#+END_QUOTE

走向死亡

#+BEGIN_QUOTE
现在回想起来，或许这就是为什么我那么喜欢捉迷藏的原因：它一开始就引人入胜，并且充满期待。当扮鬼的同伴处心积虑地想找出我们，我们却在黑暗的角落里蜷缩着身体，紧绷着神经，盯着向我们寻来的同伴时，我总是感到自己深陷在一股漆黑的幸福之中无法自拔。通常，在这段游戏中最静谧、最美好的时刻里，我会轻轻地从裤袋里搜出一颗压得皱皱的糖果来，剥进嘴里，再用那把油亮亮的小刀把糖果纸切成雪花般的碎片，一面品尝烟消云散的滋味，一面咀嚼糖果的甜美。

在扮鬼的人愈来愈接近我，就要发现我的那一刻，和其他人一样，我也撕扯着嗓子发出刺耳的尖叫声，然后在争先恐后的赛跑中，和同伴一路狂奔回到游戏的起点，上气不接下气的，我们沉浸在一阵虚脱之中，失去一切感觉……这是捉迷藏游戏的另一项迷人之处，它总是把我们带回到游戏的起点，而且从不枯燥。
#+END_QUOTE

我喜欢这些文字，一种陌生的熟悉

#+BEGIN_QUOTE
他说：“学生时代是人生最好的黄金时期。”想到未来还会比现在更糟，我感到前所未有的害怕，几乎要发抖起来。
#+END_QUOTE

我以前从未想过，最好是意味着什么。意味着以后的日子都在走下坡路。

#+BEGIN_QUOTE
我们的村子构造很简单，就像一条大拉链，中央一条马路直通到底，两边延伸出许多平行的小巷子，绿油油的树叶从围墙后面伸出头来，家家户户都是头对头、尾朝尾。
#+END_QUOTE

太形象了

#+BEGIN_QUOTE
面对这样令人感动的一幕，我只想静静地沉浸在那份完美的消失之中……我很羡慕那艘潜水艇，羡慕得几乎想要哭起来。
#+END_QUOTE

消失

#+BEGIN_QUOTE
那时，我在心底深深渴望着能变成一个很小很小的人，然后驾驶着孔兆年的潜水艇，整天在阳明湖底下绕来绕去，把那些虾子和乌龟的眼珠子都吓得掉出来，浮到湖面上。一想到那满满一湖的眼珠子，我就得意得禁不住想要笑出来。还有什么比潜水艇更会躲藏的呢？潜水艇倏地潜入水底，消失在所有人的视线之中，在水中无声地移动着，那样地滴水不漏又没有半点缝隙，还有什么比这一小方空格更隐秘、更令人期望的呢？
#+END_QUOTE

#+BEGIN_QUOTE
我看到我躺在木板床上，像一只死老鼠。我发现自己用一种很陌生的姿势躲在一个阴暗寂寞的角落里。我奋力划动双臂，转过身去背对自己。我的泪滴从空中滚落，穿过屋瓦，滴在我的额头上，发出一串冰冷的水声。
#+END_QUOTE

悲哀

#+BEGIN_QUOTE
看着地上的碎叶片，我心底的窃笑化作一团拥挤、细小的水泡，不断地上升扩大，发出像豆荚绽裂般的清脆声。
#+END_QUOTE

真好

** 父亲的轮廓

#+BEGIN_QUOTE
我永远记得和父亲并肩坐在空荡、黑暗的体育馆长椅上，而心里渴望着时光永远停止，或是快速跨过的情景。父亲先是取出温热的蒸饺和我一起吃，他细心地把白色保丽龙的盒子掀开，然后为我撕开卫生竹筷子的封套。我知道那是父亲在夜市入口的小摊上买的，摊子后面是宏光钟表行，隔壁是间杂货铺，杂货铺的天花板上吊着一包包的干鱿鱼和紫菜，老板娘是个扎着一条蓝围裙的胖女人……父亲取出口袋里的卫生纸放在我前面备用，他像面对一位长辈似的对待我，令我终生感激。我知道父亲拙于言辞，在面对生命中难以省略的伤痛时，更无力打破沉默。吃蒸饺的时候，我想起那些蒸饺原先排列在小蒸笼里冒着蒸汽的模样；我想起那个卖蒸饺的老人坐在圆凳上，被一团团白色水汽模糊了脸孔的形象；我仿佛看见父亲孤独地走上前去，两眼茫茫的老人从圆凳上站起来，剥下一只保丽龙盒子，再给它穿上一层透明的塑胶袋，然后掀开其中的一个蒸笼盖……我想到那些蒸饺原先蹲在竹笼子里高兴地窃窃私语着的样子，我想到这个世界上必定还有类似蒸笼那样温热且快乐的角落。那天晚上，是个寒冷的夏夜，父亲和我相对无语，临走前，他对我说了一句话：“ *好好活下去，不一定要在意别人的话，人生有时候要走自己的路* 。”

那句话同时把我和父亲变成了另外一个人。父亲成了我心目中的无名英雄，我永远忘不了，那天晚上，他为了避过校门口警卫的询问，索性爬墙离开的那一幕。在淡蓝色的月光映照下，他奋力攀上围墙，骑在墙顶上向我挥手，并且很诚恳地将手掌划向眉梢，向我行了一个军礼，然后才纵身跳落校外的小路上。我站在墙内，听到父亲落地的一声轻响，顿时热泪盈眶。我紧握双拳， *叮嘱自己永远不可再有想死的念头* 。
#+END_QUOTE

#+BEGIN_QUOTE
背着母亲，我偷偷到父亲出事的现场去了几次，每次都待上很长的时间。父亲在我心中的无名英雄形象，变成了一个用白色漆线勾勒在柏油路面上的空白轮廓，肢体虽然扭曲，但是依然完整。南来北往的车辆不断地从父亲的轮廓上压辗而过，每压一回，关于父亲的生前种种便更加清晰起来。父亲依旧活在我的心中，依然继续为我增添新的记忆，只是不再与我分担新的悲伤。
#+END_QUOTE

#+BEGIN_QUOTE
父亲的轮廓日益模糊、褪色，终至消失不见。旧的路面被刮掉了，重新铺上一层新的碎石和柏油。那份曾经不止一次支持我活下去的力量将永远埋藏，不为外人所知，包括父亲在内。

父亲走后，我已习惯睡前不再将房门锁上。母亲几乎每夜都会来到我的房里，不同的是，她从不在我的书桌上留下任何字句，也从不扭亮任何一点灯光。我依旧像从前那样：在母亲转动门把的时候翻过身去面对墙壁，眯着双眼；我依然不敢贸然起身惊动母亲，依然没有勇气在那样的时刻里与母亲的眼神相对。

突然有一个晚上，当母亲走进来的那一刻，我从床上坐起来，叫唤了一声：“妈！”我听到母亲立在门边的黑影渐渐发出沉重的呼吸，过了不知道多久的时间，母亲的轮廓开始颤动、啜泣起来。我对自己突如其来的举动感到十分后悔，不知该如何面对这个终于到来的时刻。

母亲仿佛一个做错事的小孩那样，将门重新掩上、离去。我的眼前又恢复成一片黑暗。我坐在床沿，紧握双拳，心中又重新燃起了一股想死的念头。
#+END_QUOTE

** 没有窗户的房间

#+BEGIN_QUOTE
鲔（wěi）鱼
#+END_QUOTE
