#+SETUPFILE: ./hugo_setup.org
#+TITLE: 一个男生对一个女孩的内心独白
#+DATE: <2019-05-16 Thu>
#+begin_quote
  暗恋的人都具备了能在人群中一眼看到对方的超能力，却都缺了另一种让对方一眼就看到自己的超能力。

  ------卢思浩《离开前请叫上我》
#+end_quote

今天，我终于要把一些长久不能写出来的东西，写出来。以一种我从来没有尝试过的方式------小说。看了很多小说，各种类型的都看，不知道当我真正实际去写的时候会产生奇怪的效果。我讨厌去列那些繁琐的提纲，我只想进行最直接的写作。

故事开始。

#+begin_html
  <center>
#+end_html

男主人公：四级 女主人公：六级

#+begin_html
  </center>
#+end_html

故事发生在一个寂静无人的下午，四级给六级发消息，六级迟迟没有回应。

四级很心急，他在胡思乱想：她怎么还不回我消息，她是不是有什么事耽搁了，她是不是对我一点感觉都没有。

四级想前想后觉得不行，我得试探一下，我要确定她是不是对我有感觉，不然我的感情付出岂不是白费了吗？

于是，四级在找各种各样的机会去验证自己的想法，去试探六级到底喜不喜欢自己，自己需不需要继续这样默默地喜欢她。

于是，在很多相遇的瞬间，男孩总会对女孩说一些看似漫不经心的话，探探六级的“虚实”。

可是，六级对四级很冷淡，爱答不理的，发信息很久才回，或者根本不回。就像那条信息根本不存在一样，四级心凉了，心想：算了吧，她怎么喜欢我呢？

我们平时连说话的时候都没有，连我主动和她联系，她都不回应我，她对我应该是没有任何感觉的吧？可是又怎能轻易放弃？

从大一军训开始时就注意到的这么一个人，不曾想最后竟分到一班，可是好运并没有继续降临，除了最初一段时间的短暂交流之后，六级以后再也不理四级了。

看着六级自然地和班里的男生谈笑，四级对这种样子的出现除了一丝嫉妒，还有深深的渴望：要是她也能这样自然地和我交流就好了。

可是这真的得怨你自己了，你为什么在酒后表白心意呢？你真是一个莽撞的人。

如果不是这样的话，你还是可以和她做朋友的，说不定你也可以像现在班里其他男生那样和她交流。这能怨谁呢？这只能怪你自己。

"算了，我再也不喜欢她了。"四级这样想着。于是，四级每天都会刻意地回避，每天都会刻意地注意不要见到她，讨厌她，不喜欢她！

很多时候，四级会忽然就想到六级。因为四级的四级已经过了，六级的六级还没有过。有时候看着单词，看着看着就开始想六级，就开始想六级。

四级会想，我的六级考试正在准备中，她也在为六级做准备。

四级每天都在想着六级考试，想着想着就想起六级了。想起她的一颦一笑，想起她说话时的神情，想起她说话时的语态。想着那些不多的交流的场景。

四级在面对六级时是羞涩的，不敢多说一句话
，生怕给六级留下什么不好的印象。可就是这短暂地几分钟的交流时间足够让四级紧张得心惊肉跳，两人并行，彼此进行简单的交流。

在四级眼里，六级是一个很独特的女生，她跟班里的其他女生不太一样，这就是她之所以在军训时就吸引四级的原因。

很长时间过去了，四级渐渐地不再那么关注六级了，因为四级也在做着自己喜爱的事情，四级也在确立自己人生的方向，四级也很迷茫。

四级有时候会想：要不我先用对于其他东西的追求来转移一下自己的注意力呢？要不然每天这样不是很累吗？

嗯嗯，四级心里的一个自我很支持主体的决定。四级决定换一种方式去解决这个问题，就这样，他完全沉浸在了自我的海洋里。

只留有一小部分空间来观察着六级的动态，是的，四级还是放不下六级，

*因为四级终归是要考过六级的*。

--------------

也可能不过，因为我就不打算继续考六级（我已经考了 4 次）
