#+SETUPFILE: ./hugo_setup.org
#+TITLE: 教育出了问题，如何改变
#+DATE: <2021-11-28 Sun>
#+BEGIN_QUOTE
任何一个“社会性”的词汇的产生都对应着一种复杂的社会问题，且标志这个问题已经相当稳定且难以改变。「内卷（involution）」一词就是如此。——汤质
#+END_QUOTE

* 关于学校教育

中国学校的教育，从来都做不到培养人，只是筛选人。中国人那么多，比起培养人，筛选才是最重要最严重的问题，因此学什么考什么仿佛并不那么重要。

学校勉强算做到不让学生入歧途、获得点糊口的知识技能，其他就是放养，修行在个人，努力的本能努力，放逸的本能放逸。因此中国的大学生含金量其实很低，因为可以混下来，本科中思维低下的人数不过来，更高学历的也不鲜见。

当代大学起源于欧洲修道院模式，学生必须花费既定的时间和精力苦修。而随着时间推移，当初传授的知识早就不适用于当下。学校教育的弊端，一则花费四年时间仅为一纸本科文凭，二则四年间学校教授的是过去的陈旧的知识，当学生毕业时无法很快得适应社会生活。

在现代这个时间点，你可以很方便地通过 Udacity，Coursera，可汗学院等在线学习网站进行自我教育，学校教育已经式微。这里的教育所指的是非学术教育，也就是说教育的目的不是为了进行学术研究。[fn:daxue]在阅读阮一峰的《[[file:../2020/survivors-of-the-future.org][未来世界的幸存者]]》时，读到「为什么你可以不读大学」，文中表达了关于学校教育已经式微的类似观点。

中国教育有普鲁士教育的基因，再混以儒学和科举传统，形成一种特殊的教育体系。当初普鲁士人创造如今认为的「标准教育模式」，是为了大量炮制忠诚且易于管理的国民，这种教育体制的积极一面就是，在当初创造出大量的中产阶级。但是，放到当代社会却并不是适合。这种体制阻碍了学生进行深度探究，对他们培养独立思考的习惯有害无益。

当今社会需要的是，具有创造力、充满好奇心并能自我引导的终身学习者，他们有能力提出新颖的想法并付诸实践，不幸的是，从普鲁士沿袭下来的教育体制却并不鼓励这种积极探索。[fn:pulushi]

* 所谓「内卷」

「内卷」，说到底还是人太多了，整个社会达到了一个临界点。所谓的国家发展了，在个人身上是通货膨胀，贫富差距被不断拉大，生存压力越来越大。学校只负责培养出来一般性人才，在前二十年绝对是正确的，但是现在，既有学校学习，不可能满足走向社会后，那些基本的生存需求了，在学校按部就班出来的年轻人，注定无法适应这个社会。

#+BEGIN_QUOTE
*现代青年（学生们）有着，最无用的善良、最羞耻的欲望、最自私的刻薄、最愚蠢的愤怒，我很敬畏年轻人，他们很有力量，但也有太多的问题，如夏天的苍蝇一样嗡嗡不停。*
#+END_QUOTE

Z时代的年轻人，自小就得接受网络上的狗屎观念，和学校老师喂的狗屎，长大后总是需要很多很多的思考，才能把脑子的狗屎给扽出来，重新热爱这个世界。

在所谓的「内卷」下，现代青年开始躺平，躺平用另一个词表达就是：颓废。似乎一种名为“虚无主义”的幽灵在所有年轻人并不稳固的精神里游荡，因此尼采简直是现代青年的灵魂导师，尼采的格言体最能使他们大脑高潮。

他们病态的病因是“一无所有”，仿佛是预感到再怎么努力都看不到的希望，终究是靠着冥想和游戏而忘记存在的问题，暂时慰藉自己的无助灵魂。寻医问药式的去追求知识去追求真理，这种行为也许能获得一些对问题的解答，但最重要的是通过这种行为能把他们和那些颓废的庸人拉开距离，而获得一种看似是超越的意义，实则是弱者的挣扎，一点也不超人。[fn:tangzhi]

[fn:daxue] [[https://www.ruanyifeng.com/survivor/collapse/university.html][为什么你可以不读大学]]
[fn:tangzhi] 来自知识星球「汤质的茶馆」
[fn:pulushi] https://mp.weixin.qq.com/s/d1xRxUkz8E_wWLap2BAX_A