#+SETUPFILE: ./hugo_setup.org
#+TITLE: 自由第一步：注销域名备案
#+DATE: <2022-06-19 Sun 16:13>
#+HUGO_TAGS: 随笔

20 年 1 月份的时候刚接触这些东西（域名、服务器），什麼都不太了解，阿里云有学生优惠，我买了三个月的轻量服务器。等到部署域名时发现需要备案。当时不知道香港服务器不需要备案，况且服务器已经买好改不了区了。

就这样，我有了一个备案域名。这件事意味着什么呢？它意味着我不再敢发表对于政治的言论，我害怕哪一天警察上门，我就「被消失」了。我压抑着自己这方面的表达欲望，转向对自我的剖析，这些是「安全的不会审查的」内容。

21 年 6 月 4 日，我域名备案所在地，也是我老家那个县的网信办给我打电话，问我「是否在社交平台发表了不当言论」。当时，第一反应是害怕，第二反应是疑惑，我以为他所说的社交平台指的是微信公众号和微博这些平台，我没在这些平台上发表过相关言论。我一再否认，他说如果不承认，后果很严重。我更害怕了，但我还是不知道我做了什么。仍然否认。要他再确认。他挂断电话，打了第二通。这次他问我，「一大加贝」是不是你的网站。他这么一说，我瞬间就明白了。

[[https://program-think.blogspot.com/][编程随想]]是一个值得学习的人，他的博客政治内容丰富，不仅包含时事评论，还有基本原理解释。网传中共已将其抓获，大概是「被失踪」了。我出于学习他网站技术内容的目的，用我的已备案域名做了一个镜像站，放在 GitHub 上。没想到在 6 月 4 日这天捅了蚂蜂窝。

为什么？因为编程随想的博客里有着大量针对六四事件的评论，以及其他各种不利于中共的观点言论。他的网站，2009 年开始，大概率止于 2021 年。内容涵盖：翻墙技术、信息安全、提升个人能力、洗脑与反洗脑、心理学、政治、历史、编程技术、职场与管理。

当那个人和我说过后，我立马把已备案域名的 DNS 删掉。我很害怕。

我，一个无名小卒，无权无势。如果我被抓起来，我身边的人怎么办？移民对目前的我来说不现实。我要如何在这个社会体制下生存？我是不是应该做到统治者所宣扬的那样呢？愚昧无知，浑噩过完一生。

《一九八四》读过一遍，现实越发像小说中描绘的那样了。当局没有封禁这本书，是不是也在暗示：没错，我就是要像《一九八四》那样搞，你们都是我的玩具，玩坏了还会有下一代。但如果我们是「最后一代」呢？

当自我审查成为一种习惯，人作为人的自由意志何在？每天麻木地生活在世界里，[[https://blog.k8s.li/thinking-2019.html][木子]]说的不错，高科技一方面代表着对未来的憧憬，另一方面又引发对技术的滥用。人脸识别、人工智能等技术，在中国这样的专制国家，被大量用于监控他们的人民，反动言论绝对不能存在，人民不能有也不该有一丝怨言。

抖音快手这样的毒瘤，就是麻痹人、让人愚昧的最好工具。这也是如此多人使用的原因。抖音快手的海外版本则是把目标放在非汉语世界，麻痹其他国家的人民。

6 月 17 日网信办发布了《[[http://www.cac.gov.cn/2022-06/17/c_1657089000974111.htm][国家互联网信息办公室关于《互联网跟帖评论服务管理规定（修订草案征求意见稿）》公开征求意见的通知]]》，要让评论的人实名制。我想博客不能有评论了吗？当时并未在意。想着独立博客可能并无大碍。

直到今天，我读了木子的《[[https://blog.k8s.li/thinking-2019.html][毕业后的一些思考]]》，读到其中「域名和备案」一节，他写到：

#+BEGIN_QUOTE
备案个锤子，备案是为了方便抓你。最近几年管制越来越严了，现在域名备案要求工信部和公安部，双备案。相信以后也会越来越严格的。还是选择国外的域名服务商吧。
#+END_QUOTE

幡然醒悟😂。毅然决定注销备案。

---

从此，我的思想更加开放，博客内容也会稍有变化。
