#+SETUPFILE: ./hugo_setup.org
#+TITLE: 《献给阿尔吉侬的花束》与我的梦境
#+DATE: <2022-05-28 Sat 06:25>
#+HUGO_TAGS: 阅读 梦境 随笔

深藏在潜意识里的我又告诉了我一件事。

我是一个温和的人，我始终不敢粗鲁地对待别人，我害怕别人待我不好，我一遍又一遍地说谢谢，感谢别人。我在想，这些感谢中，有多少是因为真的很感谢对方，有多少是因为害怕对方伤害自己。

梦里，我骑自行车，走在路上。路的左边是沟，沟很宽，但沟里水不多；路的右边是拥挤的蔓延到路的居民住宅。路不过三米宽。

我走到一个地方，发现：有人用各种电线把路挡住了。我觉得这样并不安全，想找到这些电线的主人并让他们把这些电线拉高到一定距离。我询问站在路边的一个女人，一副不好相与的样子，她说这些线有一部分是她的。

当我要她把这些电线拉高以便不伤害别人时她并不情愿，言语之间蹦出几句脏话，不堪入耳。没讲几句，周围突然来了很多看热闹的人，每个人都发表自己对事情的看法似乎每个人都与这件事情关联。

接下来，发生了一件事，让我在梦中发出恐惧的大叫——“妈的，全都滚开”。开始有人对我动手动脚，开始把我的东西扔到沟里，我的身边携带着对来说很重要的东西，眼见那人把它丢在沟里，我却不敢有所行动。这样的行为一直不断，直到我再也受不了，或者是不想再忍受下去，我说了句，“妈的，全都滚开”。我就醒了。

我没有读过精神分析领域的任何著作，所以我对自己精神心理的分析建立在生活经验和碎片阅读的基础上。

我是一个自卑的人，不论我如何掩盖，它都是事实，但它并非不可改变。我在朋友关系中总是那个温和的一方，我不太主动追喜欢的女孩。我要说一件事，关乎我的隐私，多年来一直在我的脑海里回响。

在镇上上幼儿园，五岁左右。在厕所附近，有男孩让我含着他的鸡巴（男性生殖器），我不知道那时的我为什么照做了，可能是对方有很多人，逼着我不得不做，否则就要挨打，也可能是其他原因。时间已经走了那么远距离，细节已经记不清。总之一句话，我在五岁左右的时候含了某个人的鸡巴。

写下上面这段话时，我止不住地流泪，似乎想把多年来的委屈与不满全部哭出来。 *我在害怕，害怕别人在看到这段话后看轻我，认为我是一个不值得相处的人* 。所以，我从未跟别人说过这段往事。但是，今天的梦是个来自深层次的我的暗示：你要说了。 *如果不说，如果我持续地压抑着这类的想法，我不知道自己能不能撑得下去* 。

现在看来，我开始问为什么这个习惯，可能是从那时开始的。我猜测：那时的我在遭遇过这种事后不断地问，“为什么是我？”

这件事也可能差点转变了我的性取向，我开始思考，现在自己的性格里有多少还是受着那件事的支配。写到这里，我想到，那些被强奸的女性们，她们的感受我能体会一部分了。

《献给阿尔吉侬的花束》讲了一个故事，一个叫查理的人，是一个弱智的人，想变聪明，于是有人找到他告诉他可以让他变聪明。

这个人是个大学教授做心理研究与他配合的还有一个脑神经科学的医生。实验已经在一个叫阿尔吉侬的老鼠身上做过，结果是阿尔吉侬能解开复杂的迷宫。

查理，在最初的时候有很多朋友，他认为大家相处得很好；当他变聪明之后，他发现以前大家只是在借自己的愚笨显示他们的聪明、时常嘲笑自己，在他亲手斩断这段关系后，他开始明白，要让朋友们觉得他们比自己聪明比较重要，也就是说朋友们嘲笑自己并不是恶意，他们只是想显得聪明。

查理变聪明后，成为了一个天才，精通很多语言，能进行学术研究。但是，他虽然足够聪明，却缺少与之对应对于人的理解。所以，他显得格格不入。

我也是如此。我还没有接触更多的复杂的人，我还不知道人与人相处时那些“不能说的秘密”。23号的时候写了一句话，“ /我是涉世未深的绵羊，社会是大灰狼。狼吃羊，宿命的殇/ 。”

希冀自己被社会吞噬后还能保持自我，还能 *思考* ，还能 *向往* 。
