#+SETUPFILE: ./hugo_setup.org
#+TITLE: 杭州日记：0603-0604
#+DATE: <2022-06-05 Sun 08:41>
#+HUGO_TAGS: 随笔

三号下午接近五点来到杭州的一个小区，到达之前坐了近14个小时的绿皮火车、4个小时的和谐号高铁、在杭州地铁上坐了半小时。我是第一次坐高铁，不知道座椅的升降是从哪里和怎么控制的，我错误地把邻座的一个女孩的座椅调低了，等意识到这一点的时候，连忙跟她说，抱歉，这是我第一次坐高铁。

本来想着房子只租一个月，在一个租房群里发出这样的消息后，就有人告诉我这么短的时间，没有人会租给我。但是，有一个人联系我了，Ta告诉我可以租一个月，房租1000，我看了Ta录的视频我挺喜欢。和这个人联系的时候，我还在学校，于是和Ta约定到杭州的时候看房子。但是，当我到杭州后，微信无论是发消息还是打电话都不会，这时我明白Ta大概率不会租给我了。

我急需一个居住的地方，而小区近在眼前。我询问保安是否有房子出租，他联系了一个房东，房东告诉我现在就可以入住，待到第二天房东从外地回来签租赁合同。保安让我自己去看房子，我来到房子里面，在一楼，很阴暗，有一个窗户；一个卫生间虽然小却让我洗澡；一张床；一方桌子。房租是 1100，押一付一。

说实话，房子并不好：没有阳光；空气不够流通；屋子里的阴暗气氛让我感觉不好。但是，这是我进入社会的第一步，也是我学习的开始，我应该学会接受这一切，并认真思考环境如何塑造我。

对于天气，三号是阴天，四号晚上开始下雨，今天早上也在下。空气湿度大，对人有很深的影响。

此时此刻，外面下着雨，内心的躁动也不如昨天那般强烈。在一个空气不流通的环境里，闷热是唯一的选择，我尝试在这种环境下学习，但失败了，脑子想的全是凉爽的东西。

这两天我的脑子里一直在思考一个问题——在这样“一切都由我安排”的环境里，如何约束自己让自己高效学习工作？多少明白一些别人口中的“白天上班、晚上回家只想着放松”是怎么回事了。人在成长过程中会慢慢丢掉一些东西，稚嫩的白色纸面上会泛起层层褶皱，但一个困惑始终萦绕在我的心头—— *我何以成为我* 。 *这一困惑引领我逼迫我鼓励我，思考自身与外在的关系，思考社会与自我的关系，思考家庭与自我的关系* 。

尽管思考得如此深刻，待到实践时却发现，自己总是会分神，不能专注到一件事情。我曾听人说，没必要强求专注，让自己在能够专注的时候学习即可。这是另一种思考方式。

约束自己的行为（行为指与想要达成的事情无关的事情），是为了让自己能够更好地做那些有益于思考的事情——阅读、写作、交流。我了解自己的欲望，关乎性，关乎电子产品，其余的保持适当水平就行，不像前两者的需求大。
