#+SETUPFILE: ./hugo_setup.org
#+TITLE: 我找到一份工作了！
#+DATE: <2022-06-20 Mon 23:37>
#+HUGO_TAGS: 随笔

我找到一份工作了！没有笔者更令我兴奋的事情了。

昨天，在 Boss 直聘上，询问的一位 HR，今天上午的时候就联系我。问我是否会 Socket.IO 和 three.js？我回答，Socket.IO 跟着官方文档的 Getting Started 教程做过一遍；three.js 不熟悉。

然后她就申请交换微信，然后我把简历发给她，她建了一个群，第三个人是 CEO。CEO 出了一道题：实现一个匿名聊天室，保留 30 天聊天记录。

然后，我就开始 Coding。一开始，打算基于那个 [[https://socket.io/get-started/chat][Getting Started]] 教程，为每条信息添加上时间戳，但是发现一个问题：

#+BEGIN_QUOTE
不管我做什么，每条信息的显示的时间都只能为当前时间。而不是发出消息的那个时间点。
#+END_QUOTE

我在搜索引擎和 Stack Overflow 里找了半天也没找到合适的解决办法。我又期待 GitHub 上有人分享自己关于这个的解决方案。

我真的找到了：[[https://github.com/ezesundayeze/anonymouse-realtime-chat-app][ezesundayeze/anonymouse-realtime-chat-app]]。这个项目使用 MongoDB 存储聊天数据，按照这个部署下来，正好满足题目要求。

于是，我就这个项目部署下来，放在了我的服务器上，供 CEO 测试。

在遇到这个项目之前，我尝试了很多办法：GitHub 上各种应用 Socket.IO 技术写出的应用，都不满足要求。改动的话因为不了解又显得无从下手。在这期间，内心一直在怀疑自己能否做到。还好，最后做到了。

说一下时间：11:06 CEO 出了这道题，14:06 的时候因为那个「无法保存发消息时的时间」的问题弄得焦头烂额，于是问了 CEO 这个问题，但她的回答有些答非所问。于是，我又继续寻找解决办法。终于，最终找到了。于是抓紧时间部署，完成时间在 15:38。

在这四个半小时，精神高度集中，很紧张。再加上没吃饭（早饭 + 午饭），头有些晕。

为了准备找工作，我 6 月 3 号到杭州，半个月的时间用于学习准备。最开始还能点外卖，后来就开始吃泡面。中午吃一袋，晚上吃一袋。快吃吐了。但是，当我很饿的时候，不会在乎是否吃腻的，我唯一想的就是填饱肚子。

现在找到工作了，另一段旅程开始了。
