#+SETUPFILE: ./hugo_setup.org
#+TITLE: 恍惚间，自己变化那么大
#+DATE: <2019-06-20 Thu>
#+begin_quote
  今天来了第一位室友，见到同班同学修长浩、张洋、陈慧婷，感觉很好。

  今天是新生报到日，在图书馆前的广场上见到了我们院的学长、学姐们。我觉得今天所经历的一些事意义非凡。我要加入自主创业协会、V
  帮联盟和思源社团。目的：1.培养各方面能力；2.认识各种各样的人，拓宽人脉；3.看看能不能找一个女朋友（不要笑我，确实是当时内心的真实想法）

  今天下午自我介绍有些不好意思，不过没事，相信自己可以做得更好。
#+end_quote

这是大一刚入学时记的日记。

*以后就很少再记录了，没有让自己坚持下去。没有这个意识了，现在看日记，觉得这种重读的感觉真好。我能记起那时的快乐时光。*

可是后来跟一些人就形同陌路了，也许是性情不合，也许是志向不同，也许是也许。那时能够经常见到的人现在很少见面了，那时能够开怀大笑的人现在见面竟有些拘谨，那时的情景再也回不来了。

这真够让人唏嘘的，这才过去多长时间，*时间的力量竟是如此强大*，它能够让友情变淡，能让恋人忘记彼此，能够让那些久经考验的情谊变得那么脆弱不堪。

那么我就很好奇，我们一生中遇到那么多的人，遇到新人，忘记旧人，我们在这新旧之间有什么变化吗？

是啊，我们的变化在哪里呢？我们曾经邂逅的那些人，他们究竟给了我们怎样的精神力量？我来告诉你。

人的关系组成不过就这 4 种，亲情、友情、爱情、对手情。

亲情是世界上最为宝贵的东西，它告诉我们爱为何物，教会我们如何去爱，我们从一个懵懵懂懂的稚子变成一个心中有爱的人。

友情是最有力量的，我们孤独时，友情会相伴，我们伤心时，友情会相伴，我们快乐时，友情也会相伴。

爱情是多么美好啊，我憧憬它，向往它。它能教会你如何爱你生命里的另一半。

对手情这个词比较别扭，但是我们同样应该感谢这样一种广义上的人，它对你的帮助有时候可能会更大。与对手竞争会让我们对生活的激情倍增，充满活力。

在我们一生中，我们会不断地忘掉那些我们以为不会忘记的人，但是他们留给我们的痕迹还在。我们的人生正是因为有他们的存在才有了我们的现在。

所以，高中同学许久不联系成为必然，好久不见的人只能成为 QQ
空间和朋友圈里的点赞之交，为什么？没有为什么。

黑格尔说："存在即合理。"我想说，见过了就不必再见了。这个人已经影响你的生命一次了，如果还能够见到第二次就已经足够精彩了。你们还可以继续互相影响彼此。

今天写了点随想，放在结尾吧。

当你一次又一次地失败时，支持你走下去的动力是什么？我相信自己一定会赢。

当你快要成功时，为什么会那么容易失败？在我成功之前，我在预想成功之后所带来的各种事情。丝毫没有意识到------我还没有成功。

*我自己喜欢什么东西，做它就好了。你证明那么多，就算证明给全世界看又有什么用呢？*

*懂我的人不必太多。*

想要解释又太多。

时间也不会停留，不会替你说话。

*踏出第一步，就算失败了，总比什么都没有好。*

不安于世。

人生只是一趟无止境的练习，你无需见着所有的阶梯，踏出第一步的奇迹，源自自由的你。
