#+SETUPFILE: ./hugo_setup.org
#+TITLE: 向别人介绍自己
#+DATE: <2021-02-03 Wed>
向别人介绍自己有很多场合，比如加微信、和陌生人交流时。那么如何让一个陌生人，同意你的好友申请、想和你交流？一个恰当的自我介绍必不可少。

好的自我介绍包括：

1. 你叫什么
2. 你是做什么的
3. 我可以帮你什么

** 你叫什么
   :PROPERTIES:
   :CUSTOM_ID: 你叫什么
   :END:
名字的存在是为了区分你和别人，所以名字一定和自己的某些特征相符合。如果你觉得想一个独特的名字很复杂，你不妨向我学习：我的中文名字是「高天贺」；我的中文网络名是「一大加贝」，就是把我名字「天贺」拆开；我的英文名是「Tianhe
Gao」（本来是 Jim
Gao，不过这个名字不具有法律效益，不被英语国家承认。不过，私下里我就用
Jim Gao，因为它简单）；我的英文网络名是「tianheg」。

目前来看，我的中英文网络名都是独一无二的。当你想和说中文的人对话时可以用中文网络名自我介绍，如果已经很熟悉，不妨说出自己的真名；如果你和说英文的人对话，你可以先说自己的正式的英文名，然后告诉对方："你也可以叫我
Jim，我的另一个好记的名字是 Jim Gao"。

** 你是做什么的
   :PROPERTIES:
   :CUSTOM_ID: 你是做什么的
   :END:
可以先给自己打几个容易理解的标签，然后再稍微展开说一下。

- 大概介绍一下你的职业经历
- 可以列举一些做过的事情
- 不局限于工作，自己业余做的博客、小项目都可以介绍

** 我可以帮你什么
   :PROPERTIES:
   :CUSTOM_ID: 我可以帮你什么
   :END:
我知道你是谁，你有多厉害，但是这些好像都和我没什么关系。

你要说明自己能为对方提供怎样的价值。从另一个角度来看这个标题，也可以是你的诉求是什么，比如说，我就是想观摩一朋友圈学习学习，那么至少让对方知道你的诉求是什么。要不然来历不明的人可能连朋友圈都可以直接屏蔽。

** 其他
   :PROPERTIES:
   :CUSTOM_ID: 其他
   :END:
格式：姓名，简要介绍，个人简介，能提供资源，需要资源。

1. 介绍自己，时刻准备（利于快速定位，提升沟通效率）
2. 不同场景，不同名片（商业合作伙伴：背景、资源、需求；拓宽人脉时：背景、与主要人物的关系、爱好、行业位置）
3. 制作名片核心------换位思考

--------------

*参考资料*：

1. [[https://mp.weixin.qq.com/s/V00gYPJ6XA_OfTpc82iY3A][你是谁？]]
