#+SETUPFILE: ./hugo_setup.org
#+TITLE: 哲学地生活
#+DATE: <2021-04-04 Sun>
最近读到一本《哲学概论》，书中出现了“哲学地生活”这一短语，我不很理解。

很少听到这个词，但好像又对这个词有些感触，这种朦胧的感觉萦绕我的心间。昨晚，去行知吃饭，一道菜令我印象深刻------花子菜。这道菜和我平时吃到的不一样，它是酸的。我以为它坏掉了，不过到现在为止（写下这篇文章），我也没有不舒服的迹象，所以，那道菜大概率没问题。当我尝到那酸，体味到与众不同的感觉时，我就在思考：是不是该停止吃它，如果吃下去自己生病该怎么办？我又想，这会不会是我吃到口味不同的食物太少，以至于遇到不同的，就以为那东西对自己是有害的。

这种情形推及至自身也是相同的，害怕接触新事物，害怕新事物会改变自己的状态。但是，我们怎么知道自己不是变得更好，而是变得更差？如果我们一直怀着变差的心态去接触新事物，那么最终很大概率会变差。因为有一个心理学的概念------自证预言（Self-fulfilling
prophecy），它是一种社会心理现象，一个人预测或者期待某事发生，预测或者期待就真的发生了；这是因为这个人相信它会发生，他产生的所有行为都会促进预测或期待的发生。

当我们越害怕某件事的发生，某件事就越有可能发生。

饭后走路去小操场，抬头看天，星星只有两颗。操场很多人在跑步，我在散步，看到天上的一个光点在闪，告诉自己这不是星星。因为星星距离我很遥远，它传递的光能够很久都不变，所以如果一个光点在闪烁，那它一定不是星星。

散步的时候，提出了几个有趣的问题，思考的时候那种不断逼问自己的感觉很真实，很有力。

** 0 是谁发明的
   :PROPERTIES:
   :CUSTOM_ID: 是谁发明的
   :END:
这个问题是我第一次问自己。但是问题本身并不重要，重要的是由这个问题引申出的无尽的思考。0
的重要性不言而喻，设想一下如果没有 0
的存在，我们的生活会发生怎样的变化？

之所以会考虑到这个问题，还要从关老师说起，他是我的启蒙老师。这学期教我们一门专业课。他谈到自己对电影《信条（Tenet）》的理解------既没有过去，也没有未来，只存在当下。因为过去可以被未来改变，当下可以改变未来。他的这种理解，引起了我对时间的思考。究竟是谁定义的过去、现在、未来，更甚者，根本没有所谓的过去、现在、未来，那只不过是部分人根据自己的理解所定义的单词罢了。

然后，我想到温度计、数轴......一切具有正负、0 的事物或数学工具。开始对 0
的存在好奇，这实在是一个极了不起的壮举。

** 谁定义的过去，现在，未来
   :PROPERTIES:
   :CUSTOM_ID: 谁定义的过去现在未来
   :END:
上一问题中提及了这个问题。我到现在才开始真正思考，这是一个多学科的问题，首当其冲的是物理学，赵峥老师的《从爱因斯坦到霍金的宇宙》帮我学习了这部分的知识。古罗马的奥古斯丁有一句话："时间是什么？人不问我，我很清楚；一旦问起，我便茫然。"关于时间的讨论，最开始是从哲学开始，古希腊哲学家柏拉图、亚历士多德都对时间进行过一些论述。

*柏拉图*

时间是“永恒”的映象；

时间是“永恒”的动态相似物；

时间不停地流逝，模仿着“永恒”；

时间无始无终，循环流逝。（36000 年一个周期）

*亚历士多德*

时间是运动的计数；

时间是运动持续的量度；

时间是循环的。

中国古代的哲学家孔子也有过关于时间的论述：逝者如斯夫，不舍昼夜。

这些论述表明在很久以前，人类对于时间的思考已经开始了。我们对于时间的理解，反过来会影响我们如何利用时间。

** 音乐因何而存在
   :PROPERTIES:
   :CUSTOM_ID: 音乐因何而存在
   :END:
我觉得这个问题已经存在我的心里很久了，只不过昨天才正式地问自己。我每天都在听，不只是手机中的音乐、生活中的音乐------人发出的声音，我也在听。音乐是为了什么而存在的？它又会如何发展？

音乐是极个人化的事物，每个人的音乐习惯都不同，喜好的音乐都不同。音乐是为了让人沉浸在一个短暂的氛围里吗？音乐的工具属性很明显，"音乐能......"的表述日益增多，音乐本身却鲜少被提及。*音乐是由演奏者使用专用乐器演奏出的带有规律频率的声波，人们听音乐就是为了与一些声波产生共鸣，进而引起自己感情的变化*。这是恰当的表述。

我经常唱，大多数的环境都是操场，跑步之后会选择一些音乐，跟着歌词唱。没有什么特定的目的，只是唱。在这种情景下，自身的某种束缚被释放，沉浸在自我的世界。

** 科技的未来在哪里
   :PROPERTIES:
   :CUSTOM_ID: 科技的未来在哪里
   :END:
我对科技的未来是悲观的，但对目光所及之处的科技的发展又是乐观的。我特别好奇，如果科幻小说、电影里的事物成为了现实，我们那时该如何面对世代面临的共同问题？如果我能来到未来，我会特别想知道未来人的精神状态、对于幸福的感觉......

** 总结
   :PROPERTIES:
   :CUSTOM_ID: 总结
   :END:
我很幸运，能够想出这几个问题思考，是否有答案不重要，重要的是我享受思考的过程。这就是我的理解------关于“哲学地生活”。

--------------

*参考资料*：

- 《哲学概论》杨方
