#+SETUPFILE: ./hugo_setup.org
#+TITLE: 爱自己
#+DATE: <2021-12-11 Sat>
你有多久没有关心自己了？有多久没有好好地听自己心里的话？

这个问题尤其让我思考：我究竟在追逐些什么？我极力避免这种追逐，尽管我知道如果不加入这场游戏，我会被淘汰出局。我渴望身心灵的自然提升，我正在这样做，虽然会受到各种因素干扰。

我是爱自己的。12 月 5 日的下午，在长久地坐在电脑前，一次偶然的站立时，我感到一阵眩晕（之所以用「眩晕」，是因为经过查询后它的含义更贴近我的感受）。我认为是坐得太久没有活动了，于是我站起来活动了 10 分钟，然后继续在电脑前学习。那一天，尽管我入睡前并无不安，但我那天休息得并不好；第二天，那种感觉依然纠缠着我，我害怕极了，死亡随时可能降临，可我还有那么多未竟的事情，我在想如果我能摆脱这次病痛，会怎样珍惜生活；第三天，依然眩晕，于是我决定去校医院看看，可因为找不到辅导员开假条而未成行。

第四天，心里想，大概（眩晕）要跟着我了。索性也就看开了，情绪从消极缓和了一些，也能继续学习。第五天的时候，眩晕缓和了一些，我很高兴，尽管没有完全消失。直到今天（第七天），眩晕还跟着我，但我的心态却已经从当初的消极转为正常。我畏惧死亡，它让我远离那些美好生活；但我也很疯，这源于和父亲的抗争，我无数次地幻想过：在和父亲的争吵中，被父亲杀死或自杀。

爱自己，可能就是听听自己的心里话，关注自己的身体变化。有钱的时候多做体检，看看身体的哪些部位需要特别关注；没钱的时候，做不了体检。通过这次眩晕，我思考了很多。我写过这样一句话：「只有当病痛来临的时候，人才会意识到自己是人，自己会生病。其他的时间肆意压榨自己的身体」。这就是自己的写照。怎么改变？听听自己的身体发出的那些信号吧！

别人爱不了自己，只有当每一个人都爱自己的时候，这个世界才可能达到理想意义的乌托邦。自爱，不是一个词，它是一种行为。代表着我能珍惜自己的身体、时间，去做那些自认为有意义的事情。在乎他人的目光只会让我徒增伤悲，但是我无法让自己做到完全不顾他人，所以我会对自己说：「在小事上，可以跟着别人走，这样最省力；大事上，别人的话没有参考价值」。

我已经很久没有，像这样把自己内心的话写出来了。我也很久没有写出像我曾经写出的文章那样的感觉了。我觉得，自己过去的文章写得真好，自己越写越无法打动自己。这是为什么？大概是我对自己还不够真诚，还没有看清楚一些问题的本质。等到我看清的那一天，我便能够写出和过去的自己那样真挚的文字。

补充：

我觉得头晕可能是因为该注射新冠疫苗的第三针了，因为注射过之后，我再也没有类似上文描述的那种眩晕感觉。