#+SETUPFILE: ./hugo_setup.org
#+TITLE: 沉思录190514
#+DATE: <2019-05-14 Tue>
*每天翻箱倒柜地找话题，反复折腾着我那本来就不多的积累，*

*真是苦了我了。*

*智商越来越不够用了，*

*如果发现我的语言越来越难懂了，*

*那就说明我的智商下降了，*

*一定要提醒我一下！！！*

*我好悬崖勒马，从此搁笔不写。*

我写一写自己的日常随想吧。权当娱乐。

早晨起来，小雨下得格外冻人，不得不添点衣裳。微风轻吹，雨后初凉。下过雨的早晨显得格外凉爽。凉风像阳光一样肆虐。皮肤表面的温度将我从幻想中拉进现实。在这个时间段见到了许多勤奋努力的人。早起去图书馆的学姐、早起晨练锻炼身体的长辈，当然还有像我这样，吃过早饭，出来走走的。现在是北京时间早上 6:35。我正在走到 4 教 301。

Find a group of people who challenge and inspire you,spend a lot of time with them,and it will change your life.

师北宸写作笔记：

1 视频不分先后，可以按自己的喜好去听

2 学思维方式比学习技巧点更有用

3 听课中可以时不时停下来，想一想、记一记。只有你不断地把自己有收获的或者有困惑的或者有启发的内容记下来

写于五月十三日早晨

有时候会有这样一种错觉：我现在所接收到的信息，是真正的正在发生的信息吗？还有另外一个问题，我现在所接触的这些东西，它真的有用吗？似乎在目前，我身边的这个大环境里，还没有正在做这种事的人。我错了吗？我不知道。还是我的眼光不够毒辣，看不出来身边的人真正在做着什么事情？

突然就发现一件很有意思的事情。我能够在一瞬间，从一个背影、步态看出我是不是认识这个人。

写于五月十三日

我从来没有想过这个制度是公平的，我知道它只会赢一小部分，我只是相信我可以继续优化自己，使自己成为其中之一。

I never thought the system was equitable.I knew it was winnable for only a small few.I just believed I could continue to optimize myself to become one of them.

写于五月十三日晚

一直都想写一些关于歌的故事，关于歌手的故事，但是还没有想好怎么写，就这样暂时搁置吧。

写于五月十四日
