#+SETUPFILE: ./hugo_setup.org
#+TITLE: 听「无人知晓第九期：孟岩对话黄海」
#+DATE: <2022-01-19 Wed>
[[https://www.xiaoyuzhoufm.com/episode/61dbf5b519e8465da2f8f4fd?s=eyJ1IjoiNjA1NGU4NjFlMGY1ZTcyM2JiMjRjMzQ4In0%3D][E09 孟岩对话黄海：让更多人知道你，还是让爱你的人更爱你 by 无人知晓]]

一、如何定义「品牌」？

黄海：品牌即信任。他认为信任有两种类型：一种是基于人的信任；一种是基于公司的信任。

People follow people, people don't follow the company.

为什么「人与人之间天然地易产生信任关系」？现在的我对陌生人就会有种戒备心，戒备心和信任是可以共存的。

二、星巴克是怎么成为今天的庞然大物的？

关注顾客的感受，建立人与人的链接。

三、做品牌的优秀创始人的思考方式

让喜欢我的人尽可能地更喜欢我，而不是让更多的人的喜欢我。

知名度在眼，美誉度在心，伟大的品牌是心与心的连接。by 孟岩

四、效率和体验如何兼顾？

品牌构造的早期，体验为先，在体验完成后，效率为先。

阿里和美团是 KPI 导向的公司。

多关注体验型公司。

五、品牌是不是智商税？

黄海：品牌不是智商税。

看待世界，不能只以成本作为导向。

六、随着经济社会发展，精神和内心满足类的需求会越来越多


七、投资方式对比：Inside-out, fit-in

真正能够做出好品牌的人：Inside-out，由内而外地表达；很多想做品牌的人是 fit-in。

八、二级市场，宏观经济、政策、国际政治因素，对公司的影响？

企业有自己的生存周期。

孟岩：A 股中两种投资方式：自上而下（关注政策、宏观经济后再决定如何投资）和自下而上（主要关注公司本身、创始人、商业模式、文化）。孟岩坚持自下而上。他认为国家政策不可预测、且不重要，如何避免受到政策影响，分散投资风险，投资数十家。

长期持仓、关注价值。

名词解释

ROI（投资回报率，Return on Investment），指通过投资而应返回的价值，即企业从一项投资活动中得到的经济回报。

SKU（库存量单位，Stock Keeping Unit），即库存进出计量的基本单元。现已引申为产品统一编号的简称，每种产品均对应有唯一的 SKU 号。

SOP（标准作业程序，Standard Operating Procedure），指将某一事件的标准操作步骤和要求以统一的格式描述出来，用于指导和规范日常的工作。

一级市场，是资本需求者将证券首次出售给公众时形成的市场。

二级市场，是有价证券的交易场所。