#+SETUPFILE: ./hugo_setup.org
#+TITLE: 对大脑强有力的训练
#+DATE: <2022-08-24 Wed 11:06>
#+HUGO_TAGS: 他山之石 心理学

https://zenhabits.net/mindtraining/

我们每个人都有一种思维模式，它让我们陷入某种消极情绪中：

- 失望、气馁：这样做有什么意义，反正都是要失败的，为何还要尝试呢，这太难熬了

尽管不想承认，我时不时会有这些沮丧的想法，但却告诉自己：你没有这些想法，你是一个坚定地朝着自己目标前进的人。但是，现实不是这样，最近这段时间尤其如此，内心总是处在一种消极情绪里，不知道如何/不想走出来，以此来逃避现实。

- 合理化不想做的事情：跳过这个是可以的，我可以之后再做，尝试一次没有坏处，不要那么全力做那件事，等到闹钟响起结束，装装样子

我也是，有些时候明明不该那么做，却为自己选择那么多退路，不断告诉自己这些是可以改变的，可以因为自己的一时欲望而改变。

- 防御他人的攻击：这不是我的错，我本意并非如此，为什么他们要攻击我

这三点，前两点在生活中遇到过。有些时候，不知道自己究竟犯了什么错；另外一些时候，因为自己的一些举动而被人误会。产生这两点的关键在于沟通，如果彼此之间，能够有一个交心的沟通的话，或许可以让这些负面情绪消失。

- 逃避：这令我难以承受，我只查看一条消息，我不知道我是否能够这样做

我也有逃避心理。遇到看起来很难的事情，首先想到的不是解决，而是是不是可以不这样做；另外，有时会因为自己的没有目标，而不断在社交网络游荡。因为不想让自己接受真正的磨砺，而不断地退缩、编理由找借口。

- 责备他人：他们为什么要这样，他们总是对我很坏，因为他们我不能有一个很好的生活

我小时候还有这样的心理，成年后很少出现了。现在从来没有。

- 预测评价：人们不会喜欢我这样的，他们并不珍惜我的贡献，他们会认为我是个失败者或蠢货，我甚至不应该尝试

在这个点我倒是没有顾虑，别人跟我要做的事情没什么关系，或者说，我现在要做的事情只需要我的主观意识上的努力就足够，暂时还不需要他人的参与。所以，目前的我不在意其他人怎么看我。但是，因为我生活在一个社会里，终究还是被身边人影响，在某些时候会在意其他人怎么看我。

- 对自己苛刻（高标准要求自己）：我糟透了，我需要更好，我总是搞砸事情，我现在应该比这更好

能够高标准要求自己是一件好事，但是如果不给自己喘息放松的时间或者让自己放松又无法把握尺度，会让自己陷入低效的循环中。

思维模式的精确分类并不重要——重要的是思维模式对自己是否有帮助。当你开始思考它的时候，你有怎样的感受？它是帮助你向你想要的生活前进了，还是让你停滞不前？

当这些思维模式发生时我们中的大多数不会注意到，所以我们在不知不觉中被它们的力量控制。

需要澄清的是，这些都不是“坏”想法——它们的出现是自然且正常的，但它们并不总是有益于我们。

如果这些想法没有帮助，那么怎样改变才能让这些想法更有帮助呢？

我们可以用一个更强大的思维模式来训练我们的大脑。

比如，你可以尝试以下之一：

- 我不知道这样是否行得通，但我将总是尽我最大的努力，得到我能获得的最好结果

有这种心态，会让自己更有动力。

- 生命短暂且珍贵，我想好好利用它。我有意识地、有力地使用我的时间

我时常忘记这一点。

- 我已经足够强大，能够面对那些让我感到不确定、害怕或不知所措的事情，然后让它们教会我一些事情

相信自己足够强大，相信自己能够从中学到一些东西。

- 我不知道我是否将擅长这个，但假设我将擅长它，我会拥有不合理的自信

自信，是我目前缺乏的心理。

- 我不知道别人怎么想，但直到我尝试的那一刻我才知道那是否值得。 *不管结果如何，我都会有一次难以置信的学习之路*

我需要的就是这种心态，暂时不去管结果，我只需要知道自己想要尝试，想要去学习。

- 他们可能会很沮丧，但是我不会任由他们摆布

别人对我失望，是因为他们对我期待过高，并不了解我；我不能对自己失望，我要给自己动力。

- *我珍惜我自己，承认我的光芒*

我能够让自己生活得很好，我能够了解自己和这世界。

* 思维训练的步骤

1. 你会发现自己使用旧的思维模式

当你感到灰心、四处分散注意力、逃避或推脱、对某人感到生气、觉得自己是受害者时，你通常会意识到自己在使用旧有的思维模式。

2. 停下手中的所有事情，清空脑袋，承认你的恐惧

在旧的思维模式之下，只是一种身体感觉上的不确定和恐惧。承认它就在那里，感到恐惧并没有什么，安慰它，让它冷静下来。

3. 尝试新的思维模式

对自己诉说新的思维模式，试着真的相信它。充分沉浸在其中，感受效果。

---

你要一遍又一遍地这样做。尽可能设置视觉提醒。在你的手机、镜子或桌子上写下这些步骤。不断练习。当你对练习感到沮丧时，注意到哪一个思维模式让你沮丧，尝试另一个新的。
