#+SETUPFILE: ./hugo_setup.org
#+TITLE: 如何考取中科院心理咨询师基础培训证书
#+DATE: <2021-06-12 Sat>
#+HUGO_TAGS: 备忘

* 准备工作
一、报名条件（满足其中任意一条即可报名）

1. 具有大专及以上学历；
2. 是大专及以上的在校学生，可出具在校证明或者学生证；
3. 具有医学，教育学，心理学相关专业的中级以上职称；

报名条件不会有所变更的，也是不限制专业的，毕业多久都是可以报名的，年龄方面也没有限制。

二、如何报名

在[[https://jcpx.psych.ac.cn/iip/ArticleView/?GUID=DEB321AA-06FA-441B-8331-A64E3392C6D5][这里]]可以查到「2021 年度心理咨询师基础培训项目对接机构名录（1-12 批）」。

- 通过名称/机构代码查询，确认师资、课程、收费情况，不同机构多加比对，不可图便宜而上了骗子的当。
- 可以跨区域报考
- 这一证书不是资格证书，只是培训证书

#+begin_quote
本项目是一个心理学知识普及性和心理咨询技能入门性培训产品，重在学习知识和专业技能基础。学员通过综合考试后所获得的”心理咨询基础培训合格证书”，只是作为学员参加心理咨询基础培训经历的有效证明，以及从事社会心理服务的资格参考。

——中科院继教学院声明
#+end_quote

2021 年度考试费用收费标准：技术服务费 300 元/人，考务管理费 100 元/人，合计 400 元/人；证书费 60 元/人。[[https://jcpx.psych.ac.cn/iip/ArticleView/?GUID=2AB78DB3-F624-4D2E-B1DA-B762878CCC0C][来源]]

中科院心理研究所心理咨询师基础培训项目考试时间为每年的 5 月份和 11 月份，第三周周六上午 9:00—11:30。报考时间：3 月底、9 月底。

三、[[https://jcpx.psych.ac.cn/iip/ArticleView/?GUID=F99F73C0-F8C4-475A-AC86-1C2BDAF8DEF4][FAQ]]

1. 想继续专业成长和从业的学员还要参加哪些培训？

学员在取得本项目培训合格证书后，如果想继续专业成长并从业，可以参加一些心理咨询基本功训练课程，咨询方法和技术的专项课程，以及面向专业服务执业水平的实战训练。如果具备条件，建议学员寻求通过咨询心理学的学历教育和*准学历教育*来提高素质，实现专业和职业成长。

* 挑选机构

既然必须要通过机构报考，那我们在挑选机构时，一定要擦亮眼睛！给大家列了一下需要注意机构的这几个方面，供大家参考。

1、授权：培训机构必须要有官方的授权证书，才能叫正规。关于有没有授权我们可以从那些第三方颁发证书机构的官网、公众号、在线电话查询，有没有授权一查便知。

2、保障：一定要有基本的协议签订、协议要得到法律认可。机构正规，接下来最重要的就是在这里学习，机构能给我们的保障，口说无凭，可以让机构把协议直接发给你看。

3、师资：好的老师，可以让你的学习事半功倍。告诉你老师的基本介绍之后，可以去百度百科或者其它地方确认老师的师资，确保教学质量，才能确保学习质量。

选择「杭州心聆护航健康咨询有限公司（JC1933XLHH）」，地点位于「浙江省杭州市西湖区益乐路39号1幢16A05室（[[https://www.dingtalk.com/qidian/company/1180716023011259227][消息来源]]，但更新时间为 19 年不确定是否还在这里）」。

*参考资料* ：

1. [[https://jcpx.psych.ac.cn/][中科院心理所心理咨询培训项目官网——报名考试查询服务系统]]
2. [[https://lib.psych.ac.cn/library/home][中国心理科学信息中心]]
3. [[https://new.qq.com/omn/20220801/20220801A02G9100.html][介绍「中科院心理咨询师基础培训证书」培训]]
