#+SETUPFILE: ./hugo_setup.org
#+TITLE: Programmers' Manifesto(宣言)
#+DATE: <2021-04-15 Thu>
#+HUGO_TAGS: 他山之石
From [[https://lhs.nu/about]]

1. Continually and actively improve ourselves as programmers

   作为程序员，持续地、活跃地提升自己

Accept what is, but do not be satisfied by it.

接受是什么，但是不满足于此。

Strive to improve your knowledge of your craft, to improve it through
creating new things, doing research, collaborating, dissecting the code
of others and in turn having yours dissected, taking part in discussions
and generating them.

努力提升技术知识的理解，通过创造新的事物、做研究、合作、剖析他人的代码，然后反过来剖析自己的代码，参与讨论并提出建议。

2. Create new things

   创造新事物

There are too many people wasting time, effort and creative energy by
reinventing the wheel. Strive instead to seek out the inventions of
others, learn how they work, use them in order to create new things. The
giants are already out there, all you have to do is go and stand on
their shoulders.

有太多人浪费时间、精力和创造力去重复造轮子。而不是努力寻找他人已有的发明，学习它们的工作原理，使用它们，为了创造新的东西。巨人已经在那里，需要你做的只是去站在他们的肩膀上。

3. Show and share our creations and what we learned during the process
   of creating them

   在创造的过程中展示分享我们的创意和我们学习到的知识

A thing is wasted if it isn't shared.

不分享的事物是浪费的。

Actively discuss your creations with other people, exchange them, give
them away for free, sell them - anything but hoard them.

积极地和其他人讨论你的创意，交换它们，赠送它们，出售它们------除了囤积它们，任何方式都是可行的。

4. Facilitate human connections between programmers

   促进程序员的人际关系

Programming as a an occupation and a hobby is far too solitary for the
benefit of anyone. Actively connect with other programmers, with
creators in other fields. Discuss and dissect the similarities and
differences between your approaches, philosophies, lifestyles.

作为一项职业和业余爱好进行编程对任何人的利益来说都太孤独了。积极地和其他程序员连接，和其它领域的创造者链接。讨论并消化你们之间在方法、哲学、生活方式上的相似和差异。

Connect with others, life is too short and precious to be an isolated
island.

与他人保持联系，生活太短暂和宝贵，无法成为一个孤立的岛屿。