#+SETUPFILE: ./hugo_setup.org
#+TITLE: 心理学与生活
#+DATE: <2022-08-11 Thu 15:41>
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_TAGS: 心理学 阅读
#+HUGO_DRAFT: true

心理学与生活 19 版，作者是 Richard J. Gerrig, Philip G. Zimbardo。

* 19 版序言

现代中国是一个富于竞争的时代。教育、科学、技术为时代注入了巨大的活力，基于知识和智慧的竞争成为社会成分的固态成分。是否过于激烈了？不过，我还没有亲眼见到。

* 前言

这本书的主旨：心理学是一门科学，同时关注心理学在生活中的应用。

** 生活中的批判性思维

通过向学生提供可靠的科学工具，教他们自己通过工具推导出合理的心理学结论。

** 生活中的心理学

通过具体的生活例子，来体会心理学是如何影响我们的日常生活的。

** 探索研究

解释重大研究对人类产生的积极影响。

** 教学专栏

- 停下来检查一下
- 要点重述
- 关键术语

* 第一章：生活中的心理学

解答关于日常生活的诸多疑惑。

进行一次科学探索，探寻人类行为如何发生，发生什么，何时发生，以及为何发生？探寻我在自己、他人以及动物身上所观察到的行为的原因和结果。解释我独特的思考感觉和行动方式。什么使我与众不同？为什么在多数情况下，我会跟随大多数人的选择？我是由遗传塑造还是在更大程度上其实是被个人经历塑造？攻击和利他、爱和恨、疯狂和创造性如何能在人类这种复杂的生物身上同时存在？

在第一章，我们能够知晓所有这些问题为什么以及如何与心理学产生关联。

** 心理学为何独具特色

定义：

把心理学（psychology）正式定义为关于个体的行为及心智（mind）过程的科学研究。为什么涉及这几部分（科学、行为、个体、心智）？

科学：心理学的科学特征要求通过科学可靠的方式得到能够证明心理学结论的证据。科学方法（scientific
method）包括一组用来分析和解决问题的有序步骤。这种方法用客观收集到的信息作为得出结论的事实基础。

行为：行为（behavior）是有机体适应环境的方式。行为就是行动。心理学的研究主题主要是人类和其他动物的可观察行为。微笑、哭泣、奔跑、攻击、交谈以及触摸，这些都是你所能观察到的行为的常见例子。心理学家探索在既定的行为情境和更广泛的社会或文化环境中从事什么，以及如何行事。

个体：心理学作为新兴的认知科学领域的一部分，针对人类的心智活动如何与计算机科学、人工智能和应用数学的研究和理论相关联，心理学家提出了许多问题。作为一种健康科学，心理学与医学、教育、法律和环境研究都有联系，它寻求提升每个个体和集体的幸福感。

学这个领域的最佳方式是学会分享心理学家的目标。

心理学的目标：心理学家从事基础研究的目的是描述、解释、预测和控制行为。这些目的构成了心理学专业的基础。

心理学的第一个任务是对行为进行准确的观察。心理学家通常把这种观察称为他们的数据。行为数据（behavioral
data）是关于机体的行为以及行为发生条件的观察报告。

描述必须忠实于可觉察的信息，而解释却需有意地超越可观察到的现象。

每个研究者必须具有一种见多识广的想象力，把已知和未知的事物创造性地整合起来。一个受过良好训练的心理学家，可以通过使用他对人类经验的洞察力和以前的研究者对同一个现象已经发现的事实，来解释观察到的现象。许多心理学研究都试图确定几种解释中的哪一种能最精确地解释特定的行为模式。

心理学中的预测是表述一个特定行为将要发生的可能性和一种特定关系将被发现的可能性。

对很多心理学家来说，控制是核心的、最强有力的目标。控制意味着支配行为的发生或不发生------启动行为，维持行为，停止行为，并影响行为的形式、强度或发生频率。如果一个对行为原因的解释能设定有关条件以使行为受到控制，那么这个解释就是有说服力的。

*控制行为的能力很重要，因为它为心理学提供了帮助人们提升生活质量的途径。*

** STOP

1. 心理学定义的四个成分是什么？
2. 心理学家的四个目标是什么？
3. 为什么解释行为和预测行为总是紧密相联？
