#+SETUPFILE: ./hugo_setup.org
#+TITLE: 查拉图斯特拉如是说
#+DATE: <2021-04-12 Mon>
** 第 1 章 序言
   :PROPERTIES:
   :CUSTOM_ID: 第-1-章-序言
   :END:

#+begin_quote
  我就如一只蜜蜂，因为采集了太多的花蜜，所以厌倦了自己的智慧，只想张开双臂。
#+end_quote

厌倦了智慧

#+begin_quote
  直到尘世中睿智的人们，一次次为自己的愚钝与拙劣感到欣喜；人间的穷苦者，一次次为自己的富有感到欣喜和满足
#+end_quote

为自己的愚钝感到惊喜，为自己的富有感到惊喜

#+begin_quote
  做一只空杯，是这只杯子最热切的希望
#+end_quote

空杯

#+begin_quote
  耄耋
#+end_quote

耄耋（mào
dié），汉语词语，指人年老、高龄。有耄耋之年这一说法，指人的八九十岁。该词出自《汉·曹操·对酒歌》："人耄耋，皆得以寿终。恩泽广及草木昆虫。"

#+begin_quote
  孤独是承载你生活的海洋
#+end_quote

孤独是生活的主旋律

#+begin_quote
  与其赠送礼物，倒不如帮助他们分担一些肩上的负重，如果你愿意那么做，他们会喜闻乐见，并对你无限感激。
#+end_quote

分担负重

#+begin_quote
  我还没有贫穷到能去施舍的地步
#+end_quote

有深意

#+begin_quote
  对人类而言，我们踽踽的脚步显得太孤独。就像是黎明到来之前的深夜，他们躺在床上，听到门外有脚步声传来，就会猜想：这么晚了，这个小偷要到什么地方去。
#+end_quote

神明是人所不可知的

#+begin_quote
  上帝已经死亡
#+end_quote

尼采的说法

#+begin_quote
  许多生物都通过克服自身而创造了许多不朽的物质
#+end_quote

何谓克服自身

#+begin_quote
  从前，你们还不是人，是猿猴，现在，你们变成了人类，但很多时候，你们比一只真正的猿猴更像是猿猴。
#+end_quote

比真正的猿猴更像猿猴，徒有人类的外表，而内里却是一副文明尚未涉足的模样

#+begin_quote
  在整个人类群体中，智慧最卓著的，也不过是介于植物与鬼神之间的混种
#+end_quote

这句话不甚理解

#+begin_quote
  超人
#+end_quote

超人，超越人类

#+begin_quote
  超人是大地的意义。
#+end_quote

何为超人

#+begin_quote
  不要将信任轻易给予那些妄谈超脱尘世的人，不管他们是有心还是无意，无论他们无知还是全知，他们都是不折不扣的坏种。
#+end_quote

为何这样贬低那些人呢

#+begin_quote
  人身上总有一种伟大的特质，这种特质在于人不是目的，而只是一座桥梁。人的身上，有着一种落寞，人本身，就是一种动物朝着超人的过渡，而这，也正是人的可爱之处。
#+end_quote

人是由动物向超人的过渡

#+begin_quote
  他们，对邻人还充满着友爱，只因为，他们赖以生存的热量有一部分来自与邻人的摩擦。
#+end_quote

友爱所以存在，是因为能给自己带来什么

#+begin_quote
  人生总是处处透着阴森，没有任何的意义：一个穿着彩衣的小丑也能轻易变成别人的噩梦。
#+end_quote

噩梦指代什么

#+begin_quote
  少年小丑
#+end_quote

少年小丑🤡又指代什么

#+begin_quote
  我突然醒悟过来，我需要的是伙伴、活的伙伴，而不是一个我想要带到哪里去就带到哪里去的已经死去的伙伴------一具尸体。
#+end_quote

寻找活的伙伴

** 第 2 章 三种变形
   :PROPERTIES:
   :CUSTOM_ID: 第-2-章-三种变形
   :END:

#+begin_quote
  负重和最沉重的事物是精神的必需，因为，只有负重，精神才会变得强壮。
#+end_quote

负重使精神健壮

#+begin_quote
  莫非它是要用贬低自己的方式来伤害自己的傲慢？莫非它是要用表现愚蠢的方式来嘲谑自己的智慧？
#+end_quote

傲慢与智慧

** 第 3 章 德性讲坛
   :PROPERTIES:
   :CUSTOM_ID: 第-3-章-德性讲坛
   :END:

1.

#+begin_quote
  对睡眠心怀敬意，这是非常重要的事情，在睡眠面前，要保持谦卑与羞怯的心，要远离那些在夜里精神奕奕的人和一切睡眠质量差的人。
#+end_quote

2.

#+begin_quote
  睡眠很重要，它不是一件小事，白天，我们精神奕奕，保持理智和清醒，为的就是在晚上能够睡好。

  白天的时候，你必须克制自己十次，这样你就会疲倦，但这是灵魂的罂粟。

  白天的时候，你必须调和自己十次，因为，克制本身是痛苦的，不调和就无法安眠。

  白天的时候，你必须寻找到十种真理，否则，你还要在夜间继续寻找，你的灵魂处于饥饿状态。

  白天的时候，你必须欢快地大笑十次，否则，肠胃会让我们感受到痛苦的滋味，它最擅长在夜晚捣乱了。
#+end_quote

3.

#+begin_quote
  好的睡眠要求我们服从上司的安排，对领导表示敬重，哪怕这个领导本身并不正派，但我们又能如何呢，权力本身就跛足前行。
#+end_quote

4.

#+begin_quote
  我不需要煊赫的名声与巨额的金钱，它们会让我的脾脏发炎，但我也需要一些钱财和一点微薄的名誉，否则我的睡眠质量会很差。
#+end_quote

5.

#+begin_quote
  睡眠亲吻着我的眼，我的眼睛慢慢地闭合。睡眠轻轻抚着我的唇，我的唇张开了。

  它的动作很轻柔，就像是世间最可爱的窃贼，我的思想被偷走了，我的身体还傻傻地站着，就像这个讲坛。

  可是，我站立的时间其实也很短，因为，我的身体躺倒了。
#+end_quote

6.

#+begin_quote
  站在讲坛上的所有所谓的智者，其实都不懂得生命的美好和意义，在他们看来，能够一夜安睡，没有梦魇，就是最现实的智慧。
#+end_quote

** 第 4 章 彼世论者
   :PROPERTIES:
   :CUSTOM_ID: 第-4-章-彼世论者
   :END:

1.

#+begin_quote
  我认为世界就是一件永远都承受着悲痛与苦难的作品，而作品的主人正是上帝。
#+end_quote

2.

#+begin_quote
  在我看来，不管是善良还是罪恶，不管是快乐还是痛苦，不管是我还是你，都不过是创造者为了抛撇自我而创造的多彩烟雾，他才因此创造了整个世界。
#+end_quote

3.

#+begin_quote
  过去，我认为，世界就是一个不完美的倒影，是矛盾的倒影，这种矛盾永远都存在，这个世界永远都不完美。但对于同样不完美的、世界的创造者而言，这个世界本就是完美的，是值得沉醉其中的。
#+end_quote

4.

#+begin_quote
  我会将一种新的意志传达给人类，教会他们不再盲目地行走，教会他们承认新道路的正确与美好，教会他们不要和奄奄一息的垂死者和病入膏肓的病人一样悄无声息地背弃这条道路。
#+end_quote

** 第 5 章 身体的蔑视者
   :PROPERTIES:
   :CUSTOM_ID: 第-5-章-身体的蔑视者
   :END:

1.

#+begin_quote
  我有一句话想要和蔑视身体的人说。从我的角度来看，他们没有必要去改变自己的学识和教养，他们要做的，只是离开，悄无声息地离开自己的身体。孩子们说："我的身体就是我的灵魂。"是什么原因让人们不愿意和孩子说一样的话呢？
#+end_quote

2.

#+begin_quote
  你们以自我为骄傲，但你却不愿意相信其实最伟大的从来都是你的身体和你的理性，它不是说自我，而是做自我。

  事实上，感觉和认知从来都没有终点，它是无尽的。所有的感官和精神都是自负的，它们想要让你相信，你所看到的、感觉到的、认知到的便是一切，是终点。

  感官也好，精神也好，不过都是自身的一种工具。自身可以用感官的眼睛去探寻，也可以用精神的耳朵去倾听。

  自身在不停地倾听和寻找，它进行征服、对比、毁灭、强迫。它统治着，也统治着自我。

  兄弟们啊，总有一个你看不到的主宰在掌控着你的思维和感情，这个主宰就是自身，是你自己。它住在你的身体里，它其实就是你的身体，但你对它并不熟悉。
#+end_quote

3.

#+begin_quote
  "来这里，感受一下痛苦的滋味吧。"自身这样对自我说。于是，自我开始痛苦，痛苦的同时，它在不停地思索怎样才能让自己不痛苦，而它，本就应当对这些进行思考。

  "来这里，感受一下快乐的滋味吧。"自身这样对自我说。于是，自我变得快乐，快乐的同时，它在不停地思索怎样才能让快乐变得长久，而它，本就应当对这些进行思考。

  我有一句话想和蔑视身体的人说，他们的尊重本就是由蔑视构成的。尊重、蔑视、价值、意志都是如何诞生的呢？

  尊重和蔑视都是自身为自己创造的，快乐与痛苦也是自身为自己创造的，自身具有创造性。精神是创造性的身体创造的，其存在的意义就是作为意志的手掌。
#+end_quote

4.

#+begin_quote
  蔑视身体的人啊，我永远都不会步你们的后尘，对我而言，你们也从来都不是那座架设在人类与超人之间的过渡的桥梁。
#+end_quote

** 第 6 章 快乐与热情
   :PROPERTIES:
   :CUSTOM_ID: 第-6-章-快乐与热情
   :END:

#+begin_quote
  被克服、被毁灭是人类的命运，所以，你应该挚爱你的德性，因为它会把你毁灭掉。
#+end_quote

** 第 7 章 苍白的罪犯
   :PROPERTIES:
   :CUSTOM_ID: 第-7-章-苍白的罪犯
   :END:

#+begin_quote
  一个为了自我的存在而苦恼的生命是没有任何办法能够拯救的，除了迅速的死亡。
#+end_quote

** 自由的死亡
   :PROPERTIES:
   :CUSTOM_ID: 自由的死亡
   :END:
所有希望沐浴荣光的人，都应该学会在恰当的时候、在必要的时候把荣耀舍弃，去修炼一种生与死的艰难艺术，亦即，在最恰当的时候，选择离去。

** 救赎
   :PROPERTIES:
   :CUSTOM_ID: 救赎
   :END:
意志最寂静的忧伤是什么？是它不能盼望回到过去，也无法回到过去，它无法冲破时间的束缚，也无法满足时间的祈望。

** 日出之前
   :PROPERTIES:
   :CUSTOM_ID: 日出之前
   :END:
与其看到光辉圣洁的天空被轻浮动荡的云朵亵渎，我宁可面对一片幽锁的天空，我宁可蹲在深渊底部的桶里仰望那黯淡无光的天穹。

相比于野猫一般小心翼翼地、充满了质疑的宁静，我宁可选择狂风、暴雨和喧嚣。哪怕是行走在人群中，我也更憎恨那些谨小慎微、唯唯诺诺、踌躇不前、充满怀疑、轻浮动荡如云朵般的人。

** 三种罪恶
   :PROPERTIES:
   :CUSTOM_ID: 三种罪恶
   :END:
这个被界定的世界被我那稳稳的梦窥视着、观察着，我的梦很满足，它对新鲜的事物并不钟爱，它对古旧的事物也不偏好，它不害怕什么，也不会祈祷和恳求什么。

对权力的欲望、淫邪的欲望以及自私自利

** 正午
   :PROPERTIES:
   :CUSTOM_ID: 正午
   :END:
睡眠正如羽毛一般轻缓地、温柔地在我的身体上舞蹈，就像那无法寻觅到踪迹的微风舞动在平静无澜的海面上。

** 高等级的人
   :PROPERTIES:
   :CUSTOM_ID: 高等级的人
   :END:
只有卑微的小人才有“舍己为人”"同类互助"的德性，你们是自私自利的，所以，你们没有必要“为邻人”做任何事，"邻人"也无权要求你们去做任何事。是的，即便你们不做，他们也无能为力。

--------------

*参考资料*：
