#+SETUPFILE: ./hugo_setup.org
#+TITLE: 90岁台积电创始人1.5小时演讲
#+DATE: <2022-02-10 Thu>
https://zhidx.com/p/301575.html

通常一个CEO的工资是工程师的50倍不止，因为CEO会对公司的经营的影响比工程师更大。因此其需要具备技术、分清商品和客制品概念、行销、市场学、会计、订价、有说服力的简报、聆听、包容、领导等多种能力。

* 50股IBM股票启发张忠谋金融知识，了解大公司运作

我也看report，也知道了一点大公司，IBM是很大的公司是怎么做的。我也学会了P/E（市盈率）、P/B（市净率）这些东西。因为我想了解股价吗，这是20岁。

* 黄金时间效力于TI，30岁让对手绝望

而且我一回去，从斯坦福一回去，那个是33岁。一回去啊就把我升作一个business unit（事业部）的head（负责人）。TI是organized by business units（按事业部划分）。这个是大家先要认清楚的，你的公司是organized by business units还是organized by function（按功能划分）。其实如果一个公司是organized by business units，那么一个business units是很好训练general manager（总经理）的地方。

可是并不是每一个公司都能organized by business units的，台积电就不能organized by business units。台积电我曾经在1996年，我是董事长，总经理是一位外国人，名字叫down Rocks。他做总经理已经做了5/6年了，那个时候1996年的时候，他做总经理已经做了5/6年了。他有一点做得很累了，他跟我说，要organized by business units。

我说不行啊，我们这个技术总是在进步的，假如你是以技术organized by business units，某某技术是这个business units，某某技术是另一个business units。那有的customer（客户）是各个技术都用的，它就要跟不同的单位来商量，那不好。而且比较advance（先进）的技术，business unit过了两年它的这个business就不是那么先进了。假如是你把新的都给他了的话，落后的慢慢就缩小了，这个是不行的。

那好的，我们的总经理跟我争，我就去说：“我们找McKinsey（麦肯锡）。”这是我第二次用consulting。事实上，麦肯锡是支持了我的想法，可是它倒找出了另外一个问题。另外一个问题就是麦肯锡说：“你们的customer对你们不是那么好诶。”这个是一个很大的问题，这是我以前不是很知道的，这是1996年，后来我就想把它改进。

我先问他，VMware是什么样的公司，因为我真的不知道。那他就在15分钟之内告诉我，解释给我听VMware什么公司。解释的很好，那我就知道这个家伙是个人才哦。

这就是“有说服力的简报”，其实有说服力的简报，有一个track（花招）。这个track就是你自己要相信在简报什么东西，其实我现在有点si-track。我头一次演讲，在TI的时候，30几岁，头一次有人请我演讲。我就很焦虑，从来没有经验，这个是一个演讲，不是一个paper。

所以到现在为止，我always talk about something I know（经常讲我知道的）。所以说是刚刚我给他（会议主持）两个选择，一个是半导体，一个是我自己学习的电子，这两个我都知道。

* 台积电以用户为主，揭秘唯一手写策略

* 台积电初期主打欧美市场，美国重构供应链努力不可能成功