#+SETUPFILE: ./hugo_setup.org
#+TITLE: 什么是 POP3、SMTP 及 IMAP？
#+DATE: <2021-01-31 Sun>
** POP3
   :PROPERTIES:
   :CUSTOM_ID: pop3
   :END:
POP3 是 Post Office Protocol 3 的简称，即邮局协议的第 3
个版本，它规定怎样将个人计算机连接到 Internet
的邮件服务器和下载电子邮件的电子协议。它是因特网电子邮件的第一个离线协议标准，POP3
允许用户从服务器上把邮件存储到本地主机（即自己的计算机）上，同时删除保存在邮件服务器上的邮件，而
POP3 服务器则是遵循 POP3 协议的接收邮件服务器，用来接收电子邮件的。

** SMTP
   :PROPERTIES:
   :CUSTOM_ID: smtp
   :END:
SMTP 的全称是“Simple Mail Transfer
Protocol”，即简单邮件传输协议。它是一组用于从源地址到目的地址传输邮件的规范，通过它来控制邮件的中转方式。SMTP
协议属于 TCP/IP
协议簇，它帮助每台计算机在发送或中转信件时找到下一个目的地。SMTP
服务器就是遵循 SMTP 协议的发送邮件服务器。

SMTP 认证，简单地说就是要求必须在提供了账户名和密码之后才可以登录 SMTP
服务器，这就使得那些垃圾邮件的散播者无可乘之机。

增加 SMTP 认证的目的是为了使用户避免受到垃圾邮件的侵扰。

** IMAP
   :PROPERTIES:
   :CUSTOM_ID: imap
   :END:
IMAP 全称是 Internet Mail Access Protocol，即交互式邮件存取协议，它是跟
POP3 类似邮件访问标准协议之一。不同的是，开启了 IMAP
后，您在电子邮件客户端收取的邮件仍然保留在服务器上，同时在客户端上的操作都会反馈到服务器上，如：删除邮件，标记已读等，服务器上的邮件也会做相应的动作。所以无论从浏览器登录邮箱或者客户端
软件登录邮箱，看到的邮件以及状态都是一致的。

[[https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac21b87735d7227c217][来源]]
