#+SETUPFILE: ./hugo_setup.org
#+TITLE: Steve Jobs 的话
#+DATE: <2021-02-19 Fri>
*友情提示* ：翻译水平有限，词不达意时，请阅读源文。

*1.*

那些疯狂到认为自己能够改变世界的人，往往改变了世界。

The people who are crazy enough to think they can change the world are
the ones who do.

*2.*

在过去的 33
年里，我每天早晨面对镜子问自己："如果今天是我生命的最后一天，我还会做今天我将要做的事吗？"如果连续多天答案都是不会，我知道我需要改变了。

For the past 33 years, I have looked in the mirror every morning and
asked myself: "If today were the last day of my life, would I want to do
what I am about to do today?" And whenever the answer has been "No" for
too many days in a row, I know I need to change something.

*3.*

你的工作将会占据你生活的大部分，真正满意的方式是做你相信是伟大的工作。而唯一做伟大事业的方式就是热爱你所做的事情。如果你还没有找到，继续找。不要犹豫。心会告诉你，你将知道什么时候会找到它。

Your work is going to fill a large part of your life, and the only way
to be truly satisfied is to do what you believe is great work. And the
only way to do great work is to love what you do. If you haven't found
it yet, keep looking. Don't settle. As with all matters of the heart,
you'll know when you find it.

--------------

*参考资料*：

1. [[https://blog.hubspot.com/sales/steve-jobs-quotes]]
