#+SETUPFILE: ./hugo_setup.org
#+TITLE: 文化苦旅
#+DATE: <2022-03-16 Wed>
#+HUGO_TAGS: 阅读

* 原版初序

文化和人生的种种定位毕竟还有很多可以重新选择的余地，也许，正是对这种弹性的容忍幅度，最终决定着一种文化、一种人生的心理年龄和更新可能。

#+BEGIN_QUOTE
我抛弃了所有的忧伤与疑虑，去追逐那无家的潮水，因为那永恒的异乡人在召唤我，他正沿着这条路走来。

——泰戈尔《采果集》
#+END_QUOTE

文化和人生的更新，自我的努力，改变一些事情

#+BEGIN_QUOTE
但是，历史终究会以自己的漫长来比照出人生的短促，以自己的开阔来显现出人生的局限。培根说历史使人明智，也就是历史能告诉我们种种不可能，给每个人在时空坐标中点出那让人清醒又令人沮丧的一点。

不知天高地厚的少年英气，是因为尚未悟得历史定位，一旦悟得，英气也就消了大半。待到重重叠叠的人伦定位、职业定位以及其他许多定位把人团团包围住，最后只得像《金色池塘》里的那对夫妻，不再企望迁徙，听任蔓草堙路，这便是老。
#+END_QUOTE

少年时不知天高地厚，历史告诉我们自己的局限。自己不是数年难见的天才，不过是芸芸众生中的一员，做好自己想做的事情，走好自己的人生。

#+BEGIN_QUOTE
我站在古人一定站过的地方，用先辈同样的黑眼珠打量着差不多的自然景观，静听着与千百年前没有丝毫差异的风声鸟声，产生了一种特别的感觉。在我居留的大城市里有很多图书馆和大学，以前总把它们看作文化的贮存地。现在才明白，中国文化的真实步履，贮存在这山重水复、莽莽苍苍的大地上。大地默默无言，只要来一二个有悟性的文人一站立，它封存久远的文化内涵也就能哗的一声奔泻而出；文人本也萎靡柔弱，只要被这种奔泻所裹卷，倒也能吞吐千年。
#+END_QUOTE

真正的文化贮藏地在大地上，而非大城市里的图书馆和大学中

#+BEGIN_QUOTE
我们这些人，为什么稍稍做点学问就变得如此单调窘迫了呢？如果每宗学问都要以生命的枯萎为代价，那么世间学问的最终目的又是什么？如果知识文明总是给人们带来沉重的身心负担，那么再过千百年，人类不就要被压得喘不过气来？如果精神和体魄总是矛盾，深邃和青春总是无缘，学识和游戏总是对立，那么，何时才能问津人类一直苦苦企盼的自身健全？
#+END_QUOTE

为什么文化的大放异彩一定要以人生命的枯萎为代价？文化应该是滋养人的身心的

#+BEGIN_QUOTE
我想，任何一个真实的文明人都会在心理上过着多种年龄相重叠的生活没有这种重叠，生命就会失去弹性，很容易风干和脆折。但是，不同的年龄经常会在心头打架，有时还会把自己弄得挺苦恼。例如连续几个月埋首砖块般的典籍中之后，从小就习惯于在山路上奔跑的双脚便会默默地反抗，随之而来，满心满眼满耳都会突涌起向长天大地释放自己的渴念。我知道，这是另一种年龄在捣乱了。
#+END_QUOTE

在同一个时间段里，少年、青年、老年的心态都在身体中

#+BEGIN_QUOTE
在一次对全国各省青年学生做民意测验，询问「谁是你最喜爱的中国当地作家」。余秋雨位列第一，冠军奖杯就是一座余秋雨的雕像。因为未曾谋面，雕刻者钱为先生把余秋雨刻瘦了。不过余秋雨按着雕像的标准锻炼塑身。结果，一段时间下来，他已经和雕像一模一样了。

这件事，牵扯到很多话题。例如，艺术与对象的关系，主体与客体的互代，人的自我改造可能，等等。
#+END_QUOTE

人是可以进行自我改造的

* 新版小叙

千般荒凉，以此为梦；

万里蹀躞，以此为归。

十六字，四句，道尽文化苦旅的内涵

* 写经修行

《心经》的第一个字“观”，是指直接观察，可谓之“直观”。"直观"也就是“正视”，经由“直观”和“正视”，产生“正见”和“正觉”。

玄深的佛教，居然从“直观”和“正视”开始，可能会让后代学者诧异。但是，一切真正深刻的学说都有最直接的起点。深刻，是因为能“看破”。因此，"看"是关键。

佛陀“直观”人生真相，发现的一个关键字是“苦”。生、老、病、死、别、离，一生坎坷，都通向苦。为了躲避苦、害怕苦、转嫁苦，人们不得不竞争、奋斗、挣扎、梦想、恐惧，结果总是苦上加苦。那么，再直观一下，苦的最初根源是什么？佛陀发现，所有的苦，追根溯源，都来自于种种欲望和追求。那就必须进一步直观了：欲望和追求究竟是什么东西？它们值得大家为之而苦不堪言么？

在这个思维关口上，不同等级的智者会作出三种完全不同的回答。低层智者会教导人们如何以机智击败别人，实现欲望和追求；中层智者会教导人们如何以勤奋努力来实现欲望和追求，永不放弃；高层智者则会教导人们如何选择欲望，提升追求。

佛陀远远高出于他们。既高出于低层、中层，也高出于高层。他对欲望本身进行直观，对追求的目标和过程进行直观，然后告诉众人，可能一切都搞错了。大家认为最值得盼望和追求的东西，看似真实，却并非真实。因此，他不能不从万事万物的本性上来作出彻底判断了。

终于，他用一个字建立了支点：空。

空，对佛教极为重要。甚至，历来人们都已习惯把佛门说成是“空门”。

空是一个常用汉字，很容易被浅陋理解。我从诸多经文中揣摩佛陀的本意大致有如下三层意涵：

第一层，空，是指万事万物都没有“自性”；

第二层，空，是指万事万物都不是稳定实体；

第三层，空，是指万事万物本应该空寂明净。

这三层意涵，细说起来相当深奥。但是，佛陀既然要唤醒众生，便等不得过于迟缓的推演了，而只是用急切的声音不断宣布，世间的一切物态现象和身心现象，都空而不实，似有实无。

《心经》用一个“色”字来代表物态现象，又用一个“蕴”字来代表身心现象。"色"有多种，"蕴"也有多种，但都是空。

《心经》一上来就说："五蕴皆空"。

《心经》最著名的回转句式是："色不异空，空不异色；色即是空，空即是色。"来回强调，让人不能不记住。《心经》紧接着又说“受想行识，亦复如是”，那是在指身心现象了。

从这样的句式，可以知道佛教在这个根本问题上的果决透彻，不留缝隙。

为什么万事万物皆是空？因为万事万物都因远远近近各种关系的偶然组合而生成。佛教把关系说成是“缘”，把组合说成是“起”，于是有了“缘起”的说法。由于万事万物都这么来的，因此不可能有真实而稳定的自我本性，所有的本性都只能指向空。把这两层意思加在一起，就构成了四个重要的字："缘起性空"。在汉传佛典中，这四个字具有透视世界的基础地位。

缘起性空，从根本上改变了人们的固化思维，把僵滞的世界图像一下子激活了。

例如，我们低头，看脚边这一脉水，它从何而来？它的“缘起”，就有无数偶然的关系。初一看，是一条条山溪，遇到了一重重山坡；但山溪里的水又怎么生成？那就会追及一朵朵云，一阵阵雨；那么，云从何而来？又如何变成了雨？而这山坡又是怎么产生的？......

还可以再进一步问，这水会一直保持自己的本性吗？它会被树木吸收，也会因天气蒸发，那它还算是水吗？吸收它的树木，可能枯朽成泥，也可能砍伐成器。器迟早会坏，变成柴火，一烧而汽化。那么，以前每一个阶段的“性”又在哪里？这个过程，大致能说明“缘起性空”的部分意涵。

世间绝大多数民众由于身心局限，只能从“缘起性空”的大过程中截取一些小小的片段，将它们划界定性，然后与其他片段切割、对比、较劲、争斗、

互毁、互伤，造成一系列障碍和恐怖。世界的灾难，都由此而生。因此，"缘起性空"的惊醒，有救世之功。

但是，这种惊醒很难，因为多数民众已在固化片段中安身之命、自得其乐。他们把暂且的“拥有”当作了天经地义，听说是“缘起”已经觉得失去了历史，听说是“性空”更觉得失去未来了。

"性空"？这不是在预告失去、散布悲哀吗？

对此我想多说几句。

"性空"，不止是预告失去，而是更锐利地指出：今天的拥有也是“假有”。

我看到不少书籍在解释“空”和“性空”的时候，喜欢用这样一些词语：转瞬即逝、多而必失、富而难守、高而必跌、时过境迁、物换星移......这并没有完全说错，却是浅解。照佛陀的意思，即便在未逝、未失、未跌、未迁之时，就已经是“空”了。因此，不是“易空”，而是“性空”，即本质之“空”。拥有之时，已“空”。

佛教对于一位巨富，并不是预告他“财产不永”，而是启迪他此时此刻也不是实有。同样，佛教也不是告诫一位高官，会“空”在退或罢免之后，而是提醒他，在未退未罢的今天，权位的本性也是“空”。

我相信他们从心里不服，甚至会以自己拥有的金钱、产业、房舍、任命状来自我安慰。佛教希望他们，搁置这种自我安慰。

我们不妨用一个最温和的例子来说明“拥有”之空。且说一位教师，他对学生的“拥有”就很不真实。任何学生，一生都重叠着无数社会角色，"学生"只是他们早年的一个薄薄片段，而且他们总会面对很多学校，很多教师，很多课程。这个教师教了这门课，那要问：用的是什么教科书？这教科书是谁编的？内容有多少与编者本人有关？教师和编者又有什么关系？教的内容，学生接受了多少？丢弃了多少？接受的，后来忘记了多少？没有忘记的，对他的人生是障碍还是助益？......这一连串浅浅的问题，说明教师对学生的“拥有”，在极大程度上是“假有”。教师的职业，在社会依存度和信赖度上都远远高于富人和官员，连这个职业都是如此，更不待说其他了。

以一个“空”字道破一切，是不是很悲哀呢？

不。

人世间确实为脆弱和虚荣的人群设置了一系列栏杆和缆绳，道破它们的易断和不实，一开始也许会让人若有所失，深感惶恐。其实，让脆弱暴露脆弱，让空虚展现空虚，让生命回归生命，反而会带来根本的轻松和安全。

空，是一种无绳、无索、无栏、无墙、无羁、无绊的自由状态。好像什么都没有了，又好像什么都有了。在空的世界，有和没有，是同一件事。只不过，以空为识，获得洞见，就不一样了。有和没有，也都进入了觉者的境界。

对于这一点，我忍不住要从美学上来说几句。东方诗画中的“空境”，是“上上胜境”。如果说“境”是佛语中的一种“色，那么“空即是色”的道理就能在东方美学中获得最佳印证。但这不仅仅属于东方，属于中国。英国戏剧家彼得·布鲁克（Peter Brook）所著《空的空间》The Empty Space），正是在呼唤一种新世纪的“性空美学”，即让出无边的空间，创造无边感受。无边界，无束缚，无限制，流动不定，幻化无穷。此为美学大道，在当代功利世界已经很难见到。未料，前不久，居然在索契冬奥会的开幕式上隆重领略，喜叹大美未亡。

* 鱼尾山屋

现在的我们已经不可能抹去或改写人类以前的文明史，但有权利总结教训。重要的教训是：人类不可以对同类太嚣张，更不可以对自然太嚣张。

这种嚣张也包括文明的创造在内，如果这种创造没有与自然保持和谐。

文明的非自然化有多种表现。繁衍过度、消费过度、排放过度、竞争过度、占据空间过度、繁文缛节过度、知识炫示过度、雕虫小计过度、心理曲折过度、口舌是非过度、文字垃圾过度、无效建构过度……显而易见，这一切已经构成灾难。对这一切灾难的总结性反抗，就是回归自然。

中华文明能成为唯一没有中断和湮灭的古文明的原因：

- 一是赖仗于地理环境的阻隔，避开了古文明之间的互征互毁；
- 二是赖仗于文明的体量，避免了小体量文明的互相吞食，也避免了自身枯窘；
- 三是赖仗于统一又普及的文字系统，避免了解读的分割、封闭和中断；
- 四是赖仗于实用理性和中庸之道，避免了宗教极端主义；
- 五是赖仗于科举制度，既避免了社会失序，又避免了文化失记。

这五点使得中华文明源远流长。

* 山庄背影

在我们中国，许多情绪化的社会评判规范，虽然堂而皇之地传之久远，却包含着极大的不公正。我们缺少人类普遍意义上的价值启蒙，因此这些情绪化的社会评判规范大多是从封建正统观念引申出来的，带有很大的盲目性。

这种情况直到今天还在持续。

* 沙原隐泉（鸣沙山，月牙泉）

茫茫沙漠，滔滔流水，于世无奇。唯有大漠中如此一湾，风沙中如此一静，荒凉中如此一景，高坡后如此一跌，才深得天地之韵律，造化之机巧，让人神醉情驰。

以此推演，人生、世界、历史，莫不如此。给浮嚣以宁静，给躁急以清冽，给高蹈以平实，给粗犷以明丽。唯其这样，人生才见灵动，世界才显精致，历史才有风韵。

* 莫高窟

只是，它们记录了我们历代祖先的信仰和悲欢，我们一有机会总要赶过去探望它们，隔着外国博物馆厚厚的玻璃，长久凝视，百般叮咛。

20 世纪 20 年代，白俄士兵用黑烟和油污覆盖了大批壁画和雕塑，用黑漆在壁画上乱涂乱画；后来的美国学者虽然痛斥白俄士兵的行为，但他们的行为却更加恶劣：他们用化学溶剂把壁画粘到纱布上，剥下墙壁并带回美国。为首的两个人分别是哈佛大学的兰登·华尔纳、宾夕法尼亚博物馆的霍勒斯·杰恩。

* 道士塔

王圆箓因为自身文化的不足，刷去精美的古代壁画，打毁塑像

* 都江堰

拜水都江堰，问道青城山

* 我的山河

山河间的实际步履，使一切伟业变成了寻常风景，因此也使我们变得轻松，人类本应把一切都放下，放下在山河之间。因此我们也就找到了终点，价值的终点和生命的终点。

只有走在路上，才能摆脱局限，摆脱执着，让所有的选择、探寻、猜测、想象都生气勃勃。

长城内外的冲突和交融正是中国文化的核心主题。

中华文化的三条最大的天地之线（按重要性排序）：黄河，长江，长城（四百毫米降雨量的分界线）

对最后一个的解释：>400mm，适合种植农作物；<400mm，多草原、沙漠，适合游牧。而且，400mm 降雨分界线与长城多方重叠，证明了长城的功用：区分两种文明，让农耕文明不受游牧文明的侵犯。这是天地之力借秦始皇之手画下的一条界线。

作者认为生态原因是历史的第一手指，它推动着历史的前进。孟子的「天时不如地利，地利不如人和」。到作者这里便成了「人和不如地利，地利不如天和」。人终究无法和天地自然抗争，只能顺应自然的脚步前进。

在读了很多很多书，经历了很多很多灾难之后，我终于蓦然醒悟，发现一切文化的终极机制，人间是非的最后衡定，还是要看山河大地。说准确一点，要看山河大地所能给予的生存许诺。p42

大山大河让我们生存，大山大河让我们痛改前非（文革），大山大河让我们认识到人生为人的意义

* 信客

一头是没有了家的男人，一头是没有了男人的家。两头都踮着脚，怎么也看不到对方，我是帮他们跑跑腿。p23
