#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 如何真正理解一个新概念

1. https://mp.weixin.qq.com/s/PcvVYxerhO4DAlrnDNzsOQ
2. https://sites.google.com/view/efratfurst/learning-in-the-brain

真正的知识体系在脑海中。

* 一种建立长期记忆的方式

** Know

学习新概念的第一步：知道这个概念。我知道这个概念后，就会在脑中记忆下来。如果在很近的未来，我再次遇到这一概念，就能认出来，并在大脑中建立链接。

** Understand

通过解释概念让它变得有意义。意义产生于与学习者已有知识（已经熟悉的事物）的链接。当理解后，开始意识到新概念可能在哪里发挥作用。

** Use

了解到哪里能用，接下来就开始使用。

Next, it is crucial to practice what was learned to establish accessibility and function. The goal is to build pathways that will enable recalling the concept when needed, ideally over time, changing environment and various retrieval cues. Distributed and varied retrieval practice is the way to achieve that: when trying to recall the information, access pathways are built and maintained. When a network of related concepts is established, the learner is able to USE the stored knowledge.

** Master

When using the new concpet is repeated over time, in various contexts and ways, we eventually get to a state of MASTERY: the former learner is able to use it easily and quickly, even automatically. This state of concept representation is described as a “Schema” (very well cnnected and practiced network of concepts).

* 知识和理解是同一件事物的2个部分

知识是点，是结网的基础；理解是线，用线才能把点串起来。

大脑中的知识并不以书本、文章的形式存储，而是一个一个的知识点。

在构建知识体系时，着重理解每个新概念。