#+SETUPFILE: ~/repo/blog/tpl/nil-site-tpl.org
#+TITLE: 如何编程

如何掌控生活，处理新信息，让自己有动力并且专注于正确的部分。

如果你对学习到的东西感到兴奋，并且感到不知所措，你将成为一个好的开发者。

- 如何处理新信息
- 如何保持动力

关注自己微小的但十分关键的进步。

** 高效处理新信息
   :PROPERTIES:
   :CUSTOM_ID: 高效处理新信息
   :END:
在开始学习如何编程之前，你需要学习
[[/posts/how-to-study/][如何「学习」]]。

当观看课程或者读文档时感到沮丧困惑是完全正常的，每个人都会在第一步挣扎。

*** 不要跳过基础知识
    :PROPERTIES:
    :CUSTOM_ID: 不要跳过基础知识
    :END:
基础知识是极度重要的，如果你不注意它们，你会后悔的。

你现在还在基础上挣扎？不要灰心，这并不表示你以后成不了好的程序员。

在每 10
分钟，或者在你阅读每段之后，用你自己的话解释学习到的东西。这可能很难，但你很快就会发现你不是很理解哪一部分。教是最好的学习方式，即使身边没有人！假装你在向某人解释，一旦弄清楚你不是非常理解的部分------*立刻研究它，写下答案*。通过实际写下结果，你会对答案有更多的思考，这让记住它变得容易得多。

不要仅仅听课或者阅读文档：*积极地建立个人项目参与其中*。实现每一个你学习的新知识，不论这个知识多么不起眼。这可并不像听起来这么容易，实际上可能令人非常沮丧，这时你就明白自己做对了。通过写代码提高编程技能，而不仅仅是知道它。相信我，你每次这样做都会使你比以前更擅长编程，即使你并没有意识到这一点。

** 保持学习动力
   :PROPERTIES:
   :CUSTOM_ID: 保持学习动力
   :END:
每个人都喜欢玩游戏，无论哪种类型。*你喜欢游戏是因为你从中得到了即刻的满足感，你认为自己实现了什么，并在这方面变得更好*。这就是动力的完美公式！我从编程中获得了类似玩游戏时的成就感。而这比你想象得要容易。

*设定小目标*。Not because you don't care about improvement: but because
you */do/* care about
improvement（这句读不懂）。制作一个需要当天完成的待办清单：可以是阅读 1
页文档，看 1 节课，或者只是写 10
行代码。*每次你完成整个待办清单，你会感到满足，并对你的进步更有信心*。"我已经完成了今天想做的所有事情"比“今天我只完成课程的
2%”更好。并且，即使你只读了 1
页文档或创建了一个输入字段，这样的小事依然很重要，并且被你知道。即刻的满足！

*不断地提醒你自己已经走了多远*。这可能真的很难，因为这很难被注意到。你不会积极地关注自己的经，但相信我：每天，只要你、编程（即使只是一点点），你就会变得更擅长。最好的方式就是写子弹日记。用一句话描述你当天遇到的问题，一个月以后再看。如果你对日记中的问题不再困惑，这会是一个很大的进步。你能看到自己变得更好。

*专注于一个你真正感兴趣的项目*！不是那无数待办清单中的一个，而是一个你真的想做的项目。现在不要考虑自动驾驶汽车或者是能帮你洗碗的机器人，而是选择那些更小的，比如重新创建一个网站布局或者写一个小游戏，你会注意到自己有更强的动力完成它。一旦项目完成，你就有了能够炫耀的事情：你实现了它！

*意识到你比自己认为的更加优秀*。这也被称为 Impostor
Syndrome（不懂）。你可能觉得身边的每个人知道的都比你多，也都比你更优秀：但事实并非如此。我尽可能强调：如果你持续进步，你会成为一名杰出的开发者。你已经证明：只要有足够强的学习动力，就可以编写代码。你完全符合这一点。

** 总是提醒自己
   :PROPERTIES:
   :CUSTOM_ID: 总是提醒自己
   :END:

- *不要将你自己和其他开发者进行比较*。老调重弹，但这是非常关键的。不要把你的第
  1 章和别人的第 20 章进行比较。你将会到达他们的位置，比你认为的要快！
- *你的进步比你认为的更大*。每次学习或者编程，你都在成长。接受它就好（我知道这很难）。
- *每个人都会在入门的时候挣扎，你并不孤单，而这并不意味着你会成为一个糟糕的程序员*。你现在有这种感觉是完全正常的，而这只是学习过程的一部分。不久，当你回顾自己经历的这段挫折时，会同意我的说法的。

*参考资料*

1. [[https://medium.com/free-code-camp/successfully-teaching-yourself-how-to-code-f6aac23db44a][How
   To Successfully Teach Yourself How To Code - Medium]]

2. [[/posts/how-to-study/][如何学习]]

3. [side project]：a side-project is something that you are doing aside
   from your main objective or job

4. [Impostor Syndrome]：Impostor syndrome (IS) refers to an internal
   experience of believing that you are not as competent as others
   perceive you to be. While this definition is usually narrowly applied
   to intelligence and achievement, it has links to perfectionism and
   the social context.
   [[https://www.verywellmind.com/imposter-syndrome-and-social-anxiety-disorder-4156469][source]]

5. [[https://www.linkedin.com/in/lydia-hallie/][Lydia Hallie -
   Linkedin]]
