* chinese-way-of-innovation
:PROPERTIES:
:CUSTOM_ID: chinese-way-of-innovation
:END:
https://www.foreignaffairs.com/articles/china/2022-04-21/chinese-way-innovation

> Rapid technological advancement, many in the United States believed, required the kind of fearless, "disruptive" thinking that was most at home in a freewheeling, democratic society.

> The roots of China's technological takeoff are more complex, and formulating an effective U.S. policy response requires a solid grasp of emerging technologies and a degree of projective empathy---understanding how an ambitious Chinese bureaucrat is likely to view innovation and the range of tools available for encouraging it.

​## STATE INTERVENTION（国家干预）

> Any individual Chinese innovation is the product of creative thinking by hard-working technologists.

> But explaining China's technological rise at a macro level requires understanding the steps the Chinese government took to encourage the development of one of the world's most dynamic innovation ecosystems.

> Instead, innovation is viewed as a social and economic process, one that can be guided and accelerated with the right mix of physical resources and bureaucratic resolve.

> Although China's approach contradicts Silicon Valley's deeply ingrained assumptions about the necessity of free markets and free speech, it has yielded more technological advances and commercial success than most American experts believed possible.

In China, that process has involved three crucial steps.

The first step in that process, one that took place from 2000 to 2010, was for China to create a large, semiprotected market.

Fostering a nascent innovation ecosystem required markets to be lucrative enough to fuel fierce competition, but it also required some degree of protection so that the established juggernauts of Silicon Valley did not come in and steamroll local startups before they could get off the ground.

China achieved this balance by combining decades of breakneck economic growth with the creation of the Great Firewall, which blocks access to leading foreign online platforms such as Facebook and Google.

The prospect of winning China's massive domestic market attracted huge capital investments from abroad and fostered fierce competition, but the Firewall also gave the local startups a fighting chance against their foreign competitors.

Crucially, the Great Firewall was never rock solid. For most of the past two decades, the Firewall always remained somewhat porous, insulating the Chinese market from foreign competition but never fully isolating it from new ideas.

Google, Facebook, and Twitter competed in China for years before being blocked. Less politically sensitive consumer platforms such as Airbnb, Uber, Amazon, and LinkedIn were never fully blocked; instead, they were beaten out by scrappy local startups.

The Great Firewall's porous nature allowed Chinese entrepreneurs, engineers, and scientists to stay up to date with leading technology trends and products without letting those products dominate the Chinese market.

At the same time, the sheer size of China's market kept foreign tech companies on their best behavior when interacting with the Chinese government, in the hopes that it would one day give them access to a billion new customers.

​## U.S.-CHINESE COLLABORATION

Those relationships were integral to the second, and most controversial, step in the process.

For decades, China has maintained scientific and commercial ties to leading Western companies, universities, and labs---especially U.S. ones.

These have ranged from professors at American universities collaborating with Chinese peers on public AI research to Chinese venture capitalists investing in Silicon Valley startups.
