name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: 'Building...'
      uses: tianheg/github-actions@hugo
      env:
        DEPLOY_REPO: tianheg/self
        DEPLOY_BRANCH: gh-pages
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai