name: Publish on Deno Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  PAGEFIND_VERSION: 1.0.2
  DART_SASS_VERSION: 1.67.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install PageFind and Dart Sass
        run: |
          wget -q https://github.com/CloudCannon/pagefind/releases/download/v${{ env.PAGEFIND_VERSION }}/pagefind_extended-v${{ env.PAGEFIND_VERSION }}-x86_64-unknown-linux-musl.tar.gz -O - | tar -xz -C ./node_modules/.bin
          mkdir -p ./bin
          wget -q https://github.com/sass/dart-sass/releases/download/${{ env.DART_SASS_VERSION }}/dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz -O - | tar -xz -C ./bin
          export PATH=./bin/dart-sass:$PATH
          sass --embedded --version
          bun run all

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: hugo-blog-tianheg
          entrypoint: https://deno.land/std@0.140.0/http/file_server.ts
          root: public