#+TITLE: GitHub
#+HEADER: Git
=https://github.com/tianheg.keys=

#+BEGIN_SRC sh
mkdir -m 700 ~/.ssh
curl https://github.com/USERNAME.keys >> ~/.ssh/authorized_keys
chown 600 ~/.ssh/authorized_keys
#+END_SRC

=https://github.com/tianheg.gpg=

GPG 公钥

#+BEGIN_SRC sh
curl https://github.com/USERNAME.gpg >> ./gpg-pub.txt
gpg --import ./gpg-pub.txt
#+END_SRC

To import a GPG public key and set permissions, you can follow these steps:

1. Obtain the GPG public key file (.asc or .gpg file) from the person or source you want to import the key from.

2. Open a terminal or command prompt on your computer.

3. Navigate to the directory where the GPG public key file is located using the =cd= command. For example, if the file is in your Downloads folder, you can use the command =cd Downloads= to navigate to that directory.

4. Import the GPG public key by running the following command:

=gpg --import <keyfile>=

Replace =<keyfile>= with the name of the GPG public key file you obtained. This command will import the key into your GPG keyring.

1. Set the appropriate permissions for the imported key by running the following command:

=gpg --edit-key <keyID>=

Replace =<keyID>= with the ID or email associated with the imported key. This command will open the GPG key editor.

1. In the GPG key editor, enter the command =trust= to change the trust level of the key.

2. You will be prompted to select a trust level for the key. Choose the appropriate level based on your level of trust in the key owner.

3. Save the changes and exit the GPG key editor.

Once you have imported the GPG public key and set the appropriate permissions, you can use it to verify signatures or encrypt messages with the corresponding private key.

** GitHub Sponsors

+86 手机号就行，开这个主要是，你地区不能填中国，我是填的香港地址 + 香港银行卡。

卡得肉身去香港办，这样。可以网上搜搜中银香港、汇丰银行的申请指南。

国内外汇管得很严，基本没法收外汇。

另外我了解到的，是得用境外的卡，github 会验证你的地区。

你填中国直接就过不了

填香港就必须给香港的银行卡

by https://twitter.com/ryan4yin

** 如何找到 Github 用户的邮箱

https://github.com/didi/xiaoju-survey/commit/3dc15aeb688f04dfdf69f0f46b0f66902303f92d.patch
