* Prompt Principle for Instructions
:PROPERTIES:
:CUSTOM_ID: prompt-principle-for-instructions
:END:
https://arxiv.org/pdf/2312.16171v1

1、与LLM交流不需要礼貌，所以无需添加“请”、"如果你不介意"、"谢谢"、"我想"等短语，直接切入主题。

2、在提示中整合预期的受众，例如，受众是该领域的专家。

3、将复杂任务分解为一系列更简单的提示，进行互动对话。

4、使用肯定指令，例如“做...”，避免使用负面语言如“不要...”。

5、当你需要对一个主题、想法或任何信息有更深入的理解时，可以使用以下提示： 用简单的术语解释[插入具体主题]。 像对11岁的孩子解释一样对我解释。 像对[领域]的初学者解释一样对我解释。 用简单的英语写[文章/文本/段落]，就像你在向一个5岁的孩子解释一样。

6、添加“我要给出$xxx的小费以获得更好的解决方案！”

7、实施示例驱动的提示（使用少量示例提示）。

8、在格式化你的提示时，以‘###Instruction###'开头，然后是‘###Example###'或‘###Question###'（如果相关）。随后，呈现你的内容。使用一个或多个换行符来分隔指令、示例、问题、上下文和输入数据。

9、包含以下短语："你的任务是..."和“你必须...”。

10、包含以下短语："你将受到惩罚"。

11、在提示中使用短语“以自然、人类化的方式回答一个问题”。

12、使用引导词，例如“逐步思考”。

13、在你的提示中添加以下短语："确保你的回答是公正的，不依赖于刻板印象"。

14、通过提问让模型从你这里获取足够的信息，以提供所需的输出（例如，"从现在起，我希望你问我问题，以便..."。

15、如果你想了解一个具体的主题或想法或任何信息，并且你想测试你的理解，可以使用以下提示："教我[任何理论/主题/规则名称]，并包含一个测试，但不要给我答案，然后告诉我当我回答时是否正确"。

16、为大语言模型分配角色。

17、使用分隔符。

18、在一个提示中多次重复某个特定的词或短语。

19、将思维链与少量示例提示相结合。

20、使用输出引导词，即通过以期望输出的开始来结束你的提示。利用输出引导词，通过以预期响应的开始来结束你的提示。

21、要写一篇详细的文章/文本/段落/文章或任何类型的文本："为我写一篇关于[主题]的详细[文章/文本/段落]，详细添加所有必要的信息"。

22、要在不改变风格的情况下更正/更改特定文本："尝试修订用户发送的每段文字。你应该只改进用户的语法和词汇，并确保它听起来自然。你不应该改变写作风格，例如将正式段落变成随意段落"。

23、当你有一个可能在不同文件中的复杂编码提示时："从现在起，每当你生成跨多个文件的代码时，生成一个[编程语言]脚本，可以运行该脚本以自动创建指定的文件或对现有文件进行更改以插入生成的代码。[你的问题]"。

24、当你想要使用特定的单词、短语或句子来启动或继续文本时，使用以下提示："我为你提供了开始[歌曲歌词/故事/段落/文章...]的开头：[插入歌词/单词/句子]。根据提供的单词完成它。保持一致的流动性"。

25、明确说明模型必须遵循的要求，以生成内容，包括关键词、规定、提示或指令。

26、要写任何文本，如文章或段落，目的是与提供的样本相似，包括以下指示："请根据提供的段落/标题/文本/文章/答案使用相同的语言"。
