* Ten Principles of Good Design
:PROPERTIES:
:CUSTOM_ID: ten-principles-of-good-design
:END:
https://sharing.ia.net/presenter/4facc352d646499b9b8d3bb6c2fbad2b/view

Dieter Rams think good design is:

** Innovative
:PROPERTIES:
:CUSTOM_ID: innovative
:END:
The possibilities for innovation are not, by any means, exhausted. Technological development is always offering new opportunities for innovative design.

But innovative design always develops in tandem with innovative technology, and can never be an end in itself.

** Useful
:PROPERTIES:
:CUSTOM_ID: useful
:END:
A product is bought to be used. It has to satisfy certain criteria, not only functional, but also psychological and aesthetic.

Good design emphasises the usefulness of a product whilst disregarding anything that could possibly detract from it.

** Aesthetic
:PROPERTIES:
:CUSTOM_ID: aesthetic
:END:
The aesthetic quality of a product is integral to its usefulness because products we use every day affect our person and our well- being. But only well-executed objects can be beautiful.

** Understandable
:PROPERTIES:
:CUSTOM_ID: understandable
:END:
It clarifies the products structure. Better still, it can make the product talk. At best, it is self-explanatory.

** Unobstrusive
:PROPERTIES:
:CUSTOM_ID: unobstrusive
:END:
Products fulfilling a purpose are like tools. They are neither decorative objects nor works of art.

Their design should therefore be both neutral and restrained, to leave room for the users self-expression.

** Honest
:PROPERTIES:
:CUSTOM_ID: honest
:END:
It does not make a product more innovative, powerful or valuable than it really is. It does not attempt to manipulate the consumer with promises that cannot be kept.

** long-lasting
:PROPERTIES:
:CUSTOM_ID: long-lasting
:END:
It avoids being fashionable and therefore never appears antiquated. Unlike fashionable design, it lasts many years - even in today's throwaway society.

** Thorough down to the last detail
:PROPERTIES:
:CUSTOM_ID: thorough-down-to-the-last-detail
:END:
Nothing must be arbitrary or left to chance. Care and accuracy in the design process show respect towards the consumer.

** Ecological - environmentally friendly
:PROPERTIES:
:CUSTOM_ID: ecological---environmentally-friendly
:END:
Design makes an important contribution to the preservation of the environment. It conserves resources and minimizes physical and visual pollution throughout the lifecycle of the product.

** Minimal
:PROPERTIES:
:CUSTOM_ID: minimal
:END:
Less, but better - because it concentrates on the essential aspects, and the products are not burdened with non-essentials. Back to purity, back to simplicity.
