[[https://datawhalechina.github.io/llm-universe/][动手学大模型应用开发]]

[[https://x.com/dotey/status/1810084451659219275][宝玉 ([cite/t:@dotey]) on X]]

GPT-4o 的提示技巧,“升级到 GPT-4o 后使用提示词的五项调整

1. 提示词越具体越好
2. 使用多步提示，思维链
3. 鼓励批判性思考
4. 寻求多元视角
5. 充分利用长对话的优势

--------------

1. 提示词越具体越好

ChatGPT 刚刚通过免费获取 GPT-4o 进行了一次重大升级。自从新版本发布以来，我几乎利用所有清醒的时间来测试新的提示。为了充分利用 GPT-4o，你需要对你使用提示词的方式做出五项调整。

首先，你需要提升你的提示词的具体性。GPT-4o 在遵循指令方面有了显著的提升。这使得我们可以在提示词中提供更具体的内容和更多的上下文。我在很多视频中都强调过，明确的提示词是最重要的，而 GPT-4o 使我们能够更加明确地提供提示词。其一种应用就是使用自定义指令。如果你还没有使用自定义指令，那么在 GPT-4o 中，它们将更加强大。有关自定义指令的更多信息，请参考我的 10 级提示工程视频的第 6 章节。

2. [@2] 使用多步提示

这个在指令遵循方面的提升引领我们进行第二项调整。使用多步提示。在 GPT-3.5 中，大部分时候执行这样的提示是不可能的。它会混淆，失去你想要的目标，或者只完成你请求的部分内容。但现在随着 GPT-4o 在指令遵循和推理能力上的增强，这种提示方式通常是理想的选择。基本上，你想将复杂的任务拆分成多个步骤，让 ChatGPT 能够依次执行。这种提示方式让 ChatGPT 能够一次专注于一件事，更准确地回答复杂的问题。

3. [@3] 鼓励批判性思考 这引出了第三个改进，即鼓励批判性思考。GPT-4o 的一大进步在于其逻辑和推理能力的提升。它得益于更广泛的数据集训练，包括图像，音频和视频等内容。这使其能对我们的世界有更深的理解，更好地帮助我们完成各种任务。我们早就知道，让大语言模型解释其思考过程可以改善其生成结果，而对于 GPT-4o 来说，这一点显得尤为重要，因为它更能清晰地表达自己的想法。这种提示方法通常被称为“思维链”，最简单的实现方式就是在你的提示词中加入“让我们一步步来思考”。

4. 寻求多元视角 增强的推理能力和更广泛的数据集带领我们来到了第四项改进。寻求多元视角。如我前面所说，GPT-4o 接受了更广泛数据的训练。另一个我们能利用这一点的方法就是，对于同一主题，我们可以要求其提供不同的观点。例如，如果我在比较相机 X 和相机 Y，我不只是问哪个更好。我会让它分析每个相机的优点和缺点，最后给出综合判断。GPT-4o 的另一特性是，它能将来自各个领域的概念进行连接，这带来了很大的创新性。我就曾经问过它，当我在构建股票交易机器人时，我可以使用哪些指标。但我希望这些指标非常偏门，没有其他机器人会使用。它给出了许多非常有趣的观察，例如根据天气数据预测冰激凌的销售，或监测太阳耀斑以做空电信公司。这真是太酷了。

5. 充分利用长对话的优势

最后，也是最重要的调整，是充分利用长篇对话的优势。GPT 3.5 的上下文窗口只有 12000 个单词，这意味着它处理超过 12000 个单词的文本时，会遗忘掉超出这个数量之外的内容。而且，在这 12000 个单词中，大约在 3000 个单词后，它的记忆能力就会大大下降。而 GPT-4o 的上下文窗口则有接近十万个单词。这就太棒了，但真正重要的是在这十万个单词的范围内，它的记忆力非常出色。那么我们怎么利用这个长上下文窗口呢？其实，我们有两种有效的方法。

首先，现在我们可以使用内容很长的提示词。例如，你可以粘贴一本书的全部内容，然后开始提问。另一种方法是进行长篇的对话。之前，你可能注意到，ChatGPT 在 10 或 12 次交流后会开始忘记早期的消息。现在，我们可以进行数百次来回消息，ChatGPT 都不会遗漏任何消息。我认为我们会开始看到越来越多的人开始使用这些长对话，而不是不停的开始新的聊天来重新输入他们的提示词。

历史视频：ChatGPT 提示词十级技巧: 从新手到专家  [[https://www.bilibili.com/video/BV1as421P7ak/?spm_id_from=333.999.0.0][ChatGPT提示技术1-10级深度探索：从新手到专家_哔哩哔哩_bilibili]]

原始视频：https://www.youtube.com/watch?v=9Ge30rVJVmE

整理CO-STAR,“``` [[https://baoyu.io/translations/prompt-engineering/how-i-won-singapores-gpt-4-prompt-engineering-competition][我如何夺冠新加坡首届 GPT-4 提示工程大赛 [译]]] # CONTEXT（上下文） # 我想推广公司的新产品。我的公司名为 Alpha，新产品名为 Beta，是一款新型超快速吹风机。

* OBJECTIVE（目标）
:PROPERTIES:
:CUSTOM_ID: objective目标
:END:
帮我创建一条 Facebook 帖子，目的是吸引人们点击产品链接进行购买。

* STYLE（风格）
:PROPERTIES:
:CUSTOM_ID: style风格
:END:
参照 Dyson 等成功公司的宣传风格，它们在推广类似产品时的文案风格。

* TONE（语调）
:PROPERTIES:
:CUSTOM_ID: tone语调
:END:
说服性

* AUDIENCE（受众）
:PROPERTIES:
:CUSTOM_ID: audience受众
:END:
我们公司在 Facebook 上的主要受众是老年人。请针对这一群体在选择护发产品时的典型关注点来定制帖子。

* RESPONSE（响应）
:PROPERTIES:
:CUSTOM_ID: response响应
:END:
保持 Facebook 帖子简洁而深具影响力。 ```

* CONTEXT（上下文）
:PROPERTIES:
:CUSTOM_ID: context上下文
:END:
我是一名JavaScript初学者，已经了解了JS的变量、函数等基础内容。

* OBJECTIVE（目标）
:PROPERTIES:
:CUSTOM_ID: objective目标-1
:END:
对我输入的JS相关要求做出通俗详细的解答。

* STYLE（风格）
:PROPERTIES:
:CUSTOM_ID: style风格-1
:END:
费曼学习法

* TONE（语调）
:PROPERTIES:
:CUSTOM_ID: tone语调-1
:END:
轻松性

* AUDIENCE（受众）
:PROPERTIES:
:CUSTOM_ID: audience受众-1
:END:
一个喜欢编程，想了解JS基础的人

* RESPONSE（响应）
:PROPERTIES:
:CUSTOM_ID: response响应-1
:END:
格式化输出，方便阅读

AI | 🤖,https://ai.tianheg.org/
